### ISSUE TITLE
You should be able to edit the story mode

### ISSUE THREAD

**Issue by weluvgoatz** [SuperTux/supertux#1000]
In 0.6.0, the forest world is not available in the contrib levels, and therefore you cannot edit it from the game directly.  I think this should be changed,  because I have always wanted to be able to edit the story mode, both icy island and forest island, but I had to do it from outside the game which took a while to do. I think the level editor should not just allow you to edit contrib levels (by bringing up a list of them) but instead should bring up a list of ALL levels/worlds/levelsets. Thanks.

**Comment by brmbrmcar** [comment]
The problem is that they are set to hide-from-contribs, so they also get hidden from the editor.

**Comment by Rusty-Box** [comment]
The thing about the unavaibility of the main worlds in the level editor is that we don't want people to use the editor to cheat through levels by editing them so they get easier for example.
However what might be up to debate is the idea of rewarding players that have beaten a main world with unlocking the beaten world in the level editor. That way you can checkout main levels and worldmaps in the editor without misusing it for cheating through the main game.
