### ISSUE TITLE
Reset (underground #t) when updating to 0.6.0

### ISSUE THREAD

**Issue by Ordoviz** [SuperTux/supertux#1002]
**SuperTux version:** 0.6.0
**System information:** Arch Linux

On my old profile for 0.5.1 Tux was standing in the underground of the Story Mode worldmap. When I updated to 0.6.0 `(underground)` was still set to `#t` what causes this:
![underground-glitch](https://user-images.githubusercontent.com/37733333/50394369-4e636300-075d-11e9-85df-55d17f578992.png)
So I had to manually change this with a text editor in `world1.stsg`.

**Comment by tobbi** [comment]
These variables are set using squirrel script code, which makes it fairly difficult to track their state. I track the visibility of the tilemaps using the settings file. I could *maybe* reset / delete the tilemap visibility upon a certain event happening, but what's that event gonna be?

**Comment by tobbi** [comment]
So, I *hope* this fixes things. It won't fix things for manually resetting the position of Tux to the main spawnpoint using the cheat menu. This needs an additional fix.
