### ISSUE TITLE
Tux.set_visible(false); deactivates Tux’ collision

### ISSUE THREAD

**Issue by Ordoviz** [SuperTux/supertux#1003]
**SuperTux version:** 0.6.0
**System information:** Arch Linux

##### Expected behavior
`Tux.set_visible(false);` makes Tux invisible
##### Actual behavior
`Tux.set_visible(false);` makes Tux invisible and deactivates his collision. Tux then falls out of the level and dies.
##### Steps to reproduce actual behavior
Create a new test level and insert script trigger with `Tux.set_visible(false);`.

I think this bug is what causes “Picnic with Penny” to come to a standstill after the camera scrolls to Penny: the rap_scene never gets activated and I can’t see Tux. I went to the game files and commented `Tux.set_visible(false);` in `intro.nut` and `intro.stl`out and the cut scene ran trough without the bug.

**Comment by Rusty-Box** [comment]
@tobbi Can you maybe take a look at this one?

**Comment by weluvgoatz** [comment]
I can confirm this issue exists, although I am not sure what priority it would be since making Tux invisible is something very uncommon.
