### ISSUE TITLE
0.6.0 AppImage does not run on Gentoo with KDE5

### ISSUE THREAD

**Issue by Kopilov** [SuperTux/supertux#1006]
**SuperTux version:** SuperTux_2-v0.6.0.glibc2.14-x86_64.AppImage
**System information:** Gentoo Linux with OpenRC, KDE5

##### Expected behavior
Execute the game by
```bash
wget https://github.com/SuperTux/supertux/releases/download/v0.6.0/SuperTux_2-v0.6.0.glibc2.14-x86_64.AppImage
chmod +x SuperTux_2-v0.6.0.glibc2.14-x86_64.AppImage
./SuperTux_2-v0.6.0.glibc2.14-x86_64.AppImage
```
##### Actual behavior
Error on the last step:
```
./SuperTux_2-v0.6.0.glibc2.14-x86_64.AppImage 
supertux2: error while loading shared libraries: libp11-kit.so.0: cannot open shared object file: No such file or directory
```
##### Steps to reproduce actual behavior
 * Install Gentoo Linux with xorg-server and plasma-desktop. Probably, any another GNU/Linux with any another non-Gnome desktop environment (or non-SystemD init) will be good.
 * Download and try to execute current AppImage

##### Additional debugging information
Installing `app-crypt/p11-kit` package has fixed the problem. Please add it to the image and look for other unsupplied dependencies.

**Comment by tobbi** [comment]
@probonopd Is this a blocklist issue?

**Comment by probonopd** [comment]
Yes, so far we have assumed that this library is available in the default installation of all common desktop distributions. Gentoo Linux is not one of the distributions we are targeting because there appears no clear desktop baseline default installation (am I wrong on this?). 

https://github.com/AppImage/pkg2appimage/blob/83483c2971fcaa1cb0c1253acd6c731ef8404381/excludelist#L134

I have opened an issue there:
https://github.com/AppImage/pkg2appimage/issues/356

**Comment by probonopd** [comment]
According to https://packages.ubuntu.com/xenial/libs/libp11-kit0,

> Provides a way to load and enumerate PKCS#11 modules. Provides a standard configuration setup for installing PKCS#11 modules in such a way that they're discoverable.

I wonder why a game would need this in the first place...

**Comment by Kopilov** [comment]
> I wonder why a game would need this in the first place...

@probonopd, I had asked about this problem on the [russian Unixforum](https://unixforum.org/viewtopic.php?f=2&t=146481#p1322326) before opening this issue. The [answer](https://unixforum.org/viewtopic.php?f=2&t=146481#p1322333) was:

> Each *typical* desktop has p11-kit by default, so this bug was not caught before.  
>  
> p11-kit is a dependency of gnutls, gnutls is a dependency of curl, curl is a dependency of supertux to work with Internet.

But in Gentoo (at least with desktop/plasma profile selected) p11-kit is disabled in gnutls by default.

**Comment by probonopd** [comment]
Thanks for your clarification. Then I think it should be enabled in Gentoo like everywhere else. If Gentoo deviates very far from most "mainstream" distributions, it's not feasible (with a reasonable amount of work) to be targeted by AppImages. For the same reason, Gentoo is not listed as a compatible distribution on the AppImage website.

**Comment by Kopilov** [comment]
Thanks! I did not know that AppImage is declared as compatible with some defined list of distributions.
And specially thanks for the [https://github.com/AppImage/pkg2appimage/blob/83483c2971fcaa1cb0c1253acd6c731ef8404381/excludelist](excludelist).

In Gentoo p11-kit would be automatically enabled if you install something that really depends on it by the package manager. This feature is called USE-flag.

Installing native `games-arcade/supertux-0.6.0`  package (upgraded in repository after I had tested the AppImage) has not enabled it, so p11-kit is a really ballast dependency for supertux. You can try to disable it in your AppImage if you would like.

**Comment by probonopd** [comment]
I guess my real gripe with Gentoo is that virtually no 2 systems are the same or have the same set of installed software. It's a system for tinkerers. If someone wants to, once could probably make a metapackage that would install the libraries defined in the exclude list, which would help AppImage compatibility.

**Comment by SylvianHemus** [comment]
> I guess my real gripe with Gentoo is that virtually no 2 systems are the same or have the same set of installed software. It's a system for tinkerers. If someone wants to, once could probably make a metapackage that would install the libraries defined in the exclude list, which would help AppImage compatibility.

Yes, please do that. I don't have issues with other kinds of AppImages, and I don't want to have to compile your stuff from source with this guy's unofficial layman overlay https://github.com/shiznix/unity-gentoo
