### ISSUE TITLE
The Yeti sometimes continues running around after Tux slays him

### ISSUE THREAD

**Issue by weluvgoatz** [SuperTux/supertux#1008]
In the latest version (s) of SuperTux, when you kill the Yeti, snow flies off of it and it becomes dizzy before it dies. If Tux does the final blow to the yeti and the dizzy yeti hits a walll before it dies, it will continue running around endlessly. Tux cannot interact with they yeti at this point so the level becomes impossible if the player does not restart the level. Please fix this, thank you.

**Comment by tobbi** [comment]
Can I have a screencast of this?

**Comment by Alasdairbugs** [comment]
I can reproduce this issue. It makes the boss fight of my add-on, the Grand-master journey impossible to beat :/

**Comment by tobbi** [comment]
@weluvgoatz @Alasdairbugs Please try to reproduce the issue with the latest nightly build.

**Comment by weluvgoatz** [comment]
Fixed.
