### ISSUE TITLE
Jumping off ledges doesn't initate the jump key

### ISSUE THREAD

**Issue by Alasdairbugs** [SuperTux/supertux#1009]
Supertux 0.6.0
win10 64-bit.

Running and jumping off a ledge (right at the VERY edge, about 10-ish pixels from the solid boundary) should simply let you run and jump off the ledge.

However, instead of jumping, the game ignores the jump key and you just walk off.

Try running and jumping off a ledge late. You should probably record yourself to make sure you're actually on a ledge when you try to jump. I have a video here showcasing my struggle: https://youtu.be/jb3J9e8t3wI

This does not, and I mean absolutely not, have anything to do with the powerup you currently have. Its just as easy to mess this jump up with any other odd powerup. I do recognise that the air flower does in fact give me more speed, however, when playing casually, I find moments where I don't have the air flower to reproduce the same effect shown in the video. It simply can't be my late instinct alone, because normal speed produces the same results.

Also, its good to note this makes the game practically unplayable 10% of the time, and more frustrating than ever. And since half the amount of powerups per level were wiped from existence (who honestly thought that was a good idea), its even harder to get back to where you left. If this one thing was fixed it'd make the game a lot, lot better, making it more fluid and concise.

**Comment by Alasdairbugs** [comment]
It isn't you hitting it late

**Comment by Semphriss** [comment]
Coyote time has been added to the game, closing this
