### ISSUE TITLE
Add ability to toggle visibility of spawn points/invisible blocks when testing levels in the editor

### ISSUE THREAD

**Issue by 165your4** [SuperTux/supertux#1010]
I like that we're able to see them now - it's useful for testing - but it would be nice if we could turn that off too.

**Comment by Grumbel** [comment]
Fixed spawnpoints, but couldn't find anything wrong with invisible blocks, they are already invisible when testing in the editor. Spawnpoints can be made visible by enabling showing collision rects (F2 for debug menu, requires developer mode to be enabled).

**Comment by Ordoviz** [comment]
These tiles are shown when testing levels in the editor:
![Block](https://user-images.githubusercontent.com/37733333/50575173-fa115080-0df8-11e9-9cc5-c171a3009e0e.png)
![Unisolid](https://user-images.githubusercontent.com/37733333/50575174-0a293000-0df9-11e9-9ef5-cae9af6f9faa.png)
