### ISSUE TITLE
Supertux 0.6.0 appimage does not run on Xubuntu

### ISSUE THREAD

**Issue by supercookiemonster** [SuperTux/supertux#1012]
Supertux 0.6.0 appimage does not run on Xubuntu.
He does not execute or signal.

**Comment by Kopilov** [comment]
@supercookiemonster do you get any error output on executing your appimage in terminal?
If you have, is it similar to my, in the issue #1006?

**Comment by tobbi** [comment]
@probonopd I know this is a very vague issue, but, could you take a look at this as well if you got time?

**Comment by probonopd** [comment]
@supercookiemonster which Xubuntu version?

**Comment by supercookiemonster** [comment]
It is the Xubuntu version 18.04 LTS 32 bits.
But as I had many problems with it I changed to Kubuntu, and in it the appimage also gives nothing.
I also ran the supertux 0.6.0 on windows 10 (HP intel), it gets kind of slow on the forest island.

**Comment by qwertychouskie** [comment]
The 32-bit OS is probably the problem.  A 64-bit OS should always be used, except for some VERY specific circumstances (e.g. pre-2004 hardware, which is very rare).  Most distros are dropping 32bit support outright.  Can you re-test with a 64-bit installation?

**Comment by supercookiemonster** [comment]
I installed by way of flathub in Kubuntu 32 bit recent version, the game runs well.But a bit slow and with some errors.

**Comment by probonopd** [comment]
Why would anyone still need 32-bit Intel? Are you still running _that_ old hardware?

**Comment by supercookiemonster** [comment]
Yes, I use.

**Comment by qwertychouskie** [comment]
What processor do you have?  Even Core 2 Duo fully supports 64bit.

BTW, theoretically a multi-arch AppImage could be made, the AppImage would launch an sh script that then launches the correct binary.  E.g. https://jacobspctuneup.tk/SuperTuxKart should launch SuperTuxKart on 32-bit and 64-bit systems.

**Comment by qwertychouskie** [comment]
The AppDir used to generate that AppImage: https://jacobspctuneup.tk/SuperTuxKart.AppDir.7z

**Comment by supercookiemonster** [comment]
My processor is Intel (R) Pentium (R) 4 CPU 2.8GHz.
The graphics card is Intel (R) 82915G / GV / 910GL Express Chipset Family.

In Kubuntu the game SuperTux Kart 0.9.2 runs well (and this is for new video cards).

**Comment by qwertychouskie** [comment]
Hmm... Maybe search Ebay for an old Core2Duo system or something.  It's probably not worth the effort to compile multiple binaries into the AppImage.

**Comment by probonopd** [comment]
For 32-bit Intel, a separate AppImage would be needed. Like we do for https://github.com/AppImage/AppImageKit/releases

**Comment by enigma9o7** [comment]
> What processor do you have? Even Core 2 Duo fully supports 64bit.

Pentium 4 here, so only 32-bit.  But I just use supertux from ubuntu repos, havent tried appimage.

**Comment by Semphriss** [comment]
I will close this as there is not enough demand for 32-bit Linux builds; if you want to use SuperTux on 32-bit Linux, the preferred way would be to either use package managers, or to compile from source.
