### ISSUE TITLE
Idea: Changing the sprites of enemies that come out of dispensers.

### ISSUE THREAD

**Issue by weluvgoatz** [SuperTux/supertux#1013]
Right now, when a dispenser dispenses an enemy, it is in its default sprite, and as far as I know, there is no way to change that. Can this be in the game so that I can change the sprites of the dispensed enemies before they come out of their dispensers? For example, the poison ivy that comes out of the dispenser could automatically have a pumpkin sprite, etc. Thanks!

**Comment by Rusty-Box** [comment]
This seems to be required if attempting to spawn enemies usually obtained via sprite changing.

**Comment by tylerandari13** [comment]
I just found this. When can we hav? :snowball_clueless:
