### ISSUE TITLE
Levels with lanterns crash after a few minutes

### ISSUE THREAD

**Issue by darkbasic** [SuperTux/supertux#1015]
**SuperTux version:** 0.6.0
**System information:** Arch Linux 4.19.12

##### Actual behavior
Levels with lanterns crash after a few minutes.

##### Steps to reproduce actual behavior
Try to play Deep Cavern (The Frozen Mountains by Michel)

##### Additional debugging information

coredumpctl -o supertux2.coredump dump /usr/bin/supertux2
gives me a 2.0 GB coredump, is it normal? How should I attach something that big?

**Comment by boomboompsh** [comment]
Also having this problem. same OS and version.

[https://upload.disroot.org/r/68uts9LF#nz8luc9YLfBC7ZzoR4mweACkcFoYxYqL1yQmcdHJYkY=](url)
is the compressed coredump. expands to 1.7 GB.

**Comment by boomboompsh** [comment]
Does the problem persist if you run supertux with the command line `supertux2 --renderer sdl`?
It goes away when I do that.

**Comment by tobbi** [comment]
Does this issue still occur with SuperTux 0.6.1?

**Comment by Semphriss** [comment]
Could not reproduce (0.6.2: consistently 78.1Mb throughout the whole playthrough)

Considering this issue has gone inactive, I'm closing it. Please open a new issue if this problem happens again.
