### ISSUE TITLE
Editor does not delete paths when associated object is deleted

### ISSUE THREAD

**Issue by 165your4** [SuperTux/supertux#1019]
e.g. if you create a moving platform, give it a path, and delete the platform, the path remains in the .stl file. Can also be seen when changing the camera mode to 'manual' or 'autoscroll' - which automatically gives the camera a path - and then setting it back to 'normal'.

**Comment by Rusty-Box** [comment]
Don't know if this is still occuring but if so, I believe @Grumbel might know what to do here.
