### ISSUE TITLE
Stuck in 'or is it just me?'

### ISSUE THREAD

**Issue by zorbakus** [SuperTux/supertux#1021]
**SuperTux version:**
0.6.0-3-gd75e87666

**System information:**
Linux Mint 19.1 Cinnamon
Cinnamon v4.0.8
kernel: 4.15.0-43-generic

##### Expected behavior
In level 'or is it just me?' in Cave World, if you take the over-the-level shortcut, you skip a good portion of the level

##### Actual behavior
you get stuck inside the floor near the end where you're supposed to fall down (in both small and large Tux form).
![tuxbug](https://user-images.githubusercontent.com/43297999/50567705-fb327700-0d3f-11e9-80a1-3f711fa86f08.png)
it looks like you can't get out by jumping or even backflip

##### Steps to reproduce actual behavior
just keep moving forward without jumping; if you jump just near the end, you fall down, skipping the glitch

**Comment by clintmoyer** [comment]
Strange behavior, Tux seems to drop about 15 pixels into the cracks. The change I made in #1026 gives Tux the space to keep moving forward.
