### ISSUE TITLE
Breakout of scripted walk sequences

### ISSUE THREAD

**Issue by clintmoyer** [SuperTux/supertux#1023]
**SuperTux version:** [0.6.0](https://github.com/SuperTux/supertux/tree/v0.6.0)
**System information:** [Linux 4.20.0-arch1-1-ARCH](https://git.archlinux.org/linux.git/tree/?h=v4.20-arch1)

##### Expected behavior

Accessing a menu should not enable the user to break a scripted sequence. Pressing \<Esc\> works as expected, but seeing a breakout through Debug and Cheat menus.

![expected](https://user-images.githubusercontent.com/19230462/50569366-8c91f100-0d20-11e9-9b99-67f0252690e3.gif)

##### Actual behavior

Tux can get stuck in a scripted walking sequence when Debug or Cheat menu is accessed. These menus seem to allow the user to pass another action (left or right) to Tux breaking the scripted sequence.

![supertux](https://user-images.githubusercontent.com/19230462/50569275-9dd9fe00-0d1e-11e9-8b4b-83ff5d7f99b1.gif)

##### Steps to reproduce actual behavior

1. Initiate a scripted walking sequence, such as the beginning of [Castle of Nolok](https://github.com/SuperTux/supertux/blob/v0.6.0/data/levels/world1/castle_of_nolok.stl?short_path=6d5fd50#L351)
2. Open the Debug (F2) or Cheat (F1) menu
3. Hold down the left or right key to move Tux
4. Exit the menu by either right clicking, \<Esc\>, or pressing the menu button again
5. Tux will cancel his scripted motion

**Comment by tobbi** [comment]
@Grumbel Do we not pause the VM when the debug or cheat menus are opened?

**Comment by Rusty-Box** [comment]
@tobbi or @weluvgoatz: Any of you wanting to tackle this one?
