### ISSUE TITLE
Level highscores lost on exit

### ISSUE THREAD

**Issue by ghost** [SuperTux/supertux#1024]
**SuperTux version:**
0.6.0-3-gd75e87666

**System information:**
Linux Mint 19.1 Cinnamon
Cinnamon v4.0.8
kernel: 4.15.0-43-generic

##### Expected behavior
Your best coins collected, foes killed etc. should be listed in each level and saved when you exit the game.

##### Actual behavior
Highscores are lost on restarting the game, but if you managed to complete them all, yellow flash on a level is still present. Level's completion status is however saved correctly (world map progress).

##### Steps to reproduce actual behavior
Just make any score in any level (collect some coins, kill some foes...) then restart the game and those will be lost.

**Comment by clintmoyer** [comment]
Is that intended? It looks like the level state only remembers if it was finished or 100% completed.

```
struct LevelState
{
public:
  LevelState() :
    filename(),
    solved(false),
    perfect(false)
  {}

  std::string filename;
  bool solved;
  bool perfect;
};
```

https://github.com/SuperTux/supertux/blob/v0.6.0/src/supertux/savegame.hpp#L27

**Comment by zorbakus** [comment]
Well, this was a disappointment for me personally because I collected all coins and foes and secrets but wanted to leave best time for later, and when I relaunched the game it was all gone...

**Comment by Wuzzy2** [comment]
Can confirm on a Parabola system. Linux 4.20.

**Comment by Wuzzy2** [comment]
Can confirm on Parabola (Linux 4.20).

This bug is a regression, because it worked in previous versions.
