### ISSUE TITLE
Ground-pound helmet-tux animation

### ISSUE THREAD

**Issue by ghost** [SuperTux/supertux#1025]
**SuperTux version:**
0.6.0-3-gd75e87666

**System information:**
Linux Mint 19.1 Cinnamon
Cinnamon v4.0.8
kernel: 4.15.0-43-generic

##### Expected behavior
Tux with fire flower powerup should use the more detailed butt-pound animation that he uses with the lower-tier generic egg powerup (big Tux).

![tux-nice](https://user-images.githubusercontent.com/43297999/50572749-21e3c280-0dbf-11e9-973a-1c693bace5d9.png)

##### Actual behavior
He uses the old, less detailed animation where only his legs change position a bit.

![tux-bad](https://user-images.githubusercontent.com/43297999/50572752-27410d00-0dbf-11e9-9e31-6a2eddbd83db.png)

##### Steps to reproduce actual behavior
Butt-pound as a fire flower Tux.

**Comment by clintmoyer** [comment]
Looks like the new ground-pound animation was only provided for Big Tux. 7 new ground-pound animations were provided for Big Tux back in June 2018 in 3b4e444. Conversely all the other version of Tux have a single ground-pound image provided back in June 2016 in 1da0dd9. We could either update each respective Tux powerup or try to merge the new animations in, accepting that Tux would "lose his power" for a brief moment during the animation.

**Comment by Alasdairbugs** [comment]
I believe Altzer S said he is already working on some animations for the powerup variants of tux.

**Comment by Rusty-Box** [comment]
This issue has been fixed. Closing this.
