### ISSUE TITLE
Texts in InfoBlocks are not wrapped in some languages which have no spaces between words

### ISSUE THREAD

**Issue by ryonakano** [SuperTux/supertux#1028]
**SuperTux version:** 0.6.0-58-g631d2bf3a
**System information:** Linux 4.15.0-43-generic, elementary OS 5.0 Juno (built on Ubuntu 18.04.1)

### Background knowledge

Generally, Japanese does not have any spaces between words, unlike English, French, etc. For example:

**English (has a space between each words):** Bonus blocks can contain coins, power-ups or special items to help you in your quest.
**Japanese (has no space between each words):** ボーナスブロックには、冒険を助けるコインやパワーアップアイテム、特別なアイテムが入っていることがあります。

Chinese also has no spaces between words like Japanese.

### Expected behavior

![screenshot from 2019-01-05 18-42-53](https://user-images.githubusercontent.com/26003928/50724097-18de5280-112b-11e9-95a1-8ba7ecb1f169.png)

Texts in InfoBlocks should be wrapped even in some languages which have no spaces between words, like in English.

### Actual behavior

![screenshot from 2019-01-05 18-42-17](https://user-images.githubusercontent.com/26003928/50724094-11b74480-112b-11e9-9676-37282f527405.png)

Texts in InfoBlocks are not wrapped in some languages which have no spaces between words.

### Steps to reproduce actual behavior

* Download latest Japanese & Chinese Traditional translations of World 1 from Transifex (because built-in translations may be old)
* Run SuperTux in Japanese or Chinese
* Play some level that has InfoBlocks (e.g. "Welcome to Antarctic" in World 1)
* Hit some InfoBlock. You should see texts in InfoBlocks are not wrapped

### Additional information

![screenshot from 2019-01-05 20-34-21](https://user-images.githubusercontent.com/26003928/50724101-1f6cca00-112b-11e9-86f7-f0d418d9111e.png)

I face this issue in Japanese, which is my mother tongue. However, I also face this issue when I play in Chinese Traditional (zh_TW).

![screenshot from 2019-01-05 18-41-10](https://user-images.githubusercontent.com/26003928/50724141-10d2e280-112c-11e9-8539-6226fb077867.png)

Also, I confirmed Japanese texts were also wrapped when I added a space between words on purpose.

Considering those 2 points, I suppose this issue may occur in any languages which have no spaces between words.

**Comment by tobbi** [comment]
Can those strings in Japanese be wrapped without losing any of the meaning?

**Comment by ryonakano** [comment]
Japanese texts don't lose meanings no matter where the wrap is, because in Japanese it's easy to recognize separation of words thanks to the different kind of alphabets like Hiragana, Katakana and Kanji.
But if possible, it is better to be wrapped between words, because if so we can read more easily.
