### ISSUE TITLE
'Find the bigger fish' stuck in secret area

### ISSUE THREAD

**Issue by ghost** [SuperTux/supertux#1029]
**SuperTux version:**
0.6.0-3-gd75e87666

**System information:**
Linux Mint 19.1 Cinnamon
Cinnamon v4.0.8
kernel: 4.15.0-43-generic

##### Expected behavior
Platform should descend back to you if you walk off it before getting into the pipe.

##### Actual behavior
Platform never returns.

##### Steps to reproduce actual behavior
If you activate the wooden platform at the exit pipe of the secret area in "Find the Bigger Fish" level and jump off it before it gets you into the pipe, you are stuck there and must kill yourself with the spiky vines nearby.

**Comment by Wuzzy2** [comment]
I believe the same could be said for the level “Crystal Cave”. If you miss the final elevator, you lose.
