### ISSUE TITLE
'Penguins don't grow on trees' badly placed cannon enemies

### ISSUE THREAD

**Issue by ghost** [SuperTux/supertux#1033]
**SuperTux version:**
0.6.0-3-gd75e87666

**System information:**
Linux Mint 19.1 Cinnamon
Cinnamon v4.0.8
kernel: 4.15.0-43-generic

##### Expected behavior
Leaf enemies launch from rightside of the cannon aligned correctly.

##### Actual behavior
They launch too low compared to the cannon.

##### Steps to reproduce actual behavior
Look at screenshot from the level, the leaf enemy is too low compared to cannon's position when launching from the right side. From left side it's properly aligned, though.

![cannon](https://user-images.githubusercontent.com/43297999/50738052-1d107b80-11d0-11e9-81c8-8d023e27251b.jpg)

**Comment by plonibarploni** [comment]
Also said leaves push all badguys in their way into the abyss together with them. Is that intended?
