### ISSUE TITLE
Add world select

### ISSUE THREAD

**Issue by Alzter** [SuperTux/supertux#1036]
Modern Mario platformers, or just platformers in general have a world select menu to choose which world to warp to on the fly. Currently in SuperTux you have to go through all the levels to move worlds. Can we get a world select menu for convenience?

**Comment by Alzter** [comment]
The world select should only be able to select worlds that you have unlocked. Worlds you have not discovered should not appear.

**Comment by plonibarploni** [comment]
> Worlds you have not discovered should not appear.

...or be greyed out/disabled?

**Comment by sss75m4** [comment]
it would be better for it to not appear because spoiler alerts

**Comment by HybridDog** [comment]
There are already teleporters, see Bonus Islands I. Maybe you can save which teleporters are enabled; disabled teleporter pairs can be enabled only from one side (unlock).
Btw: Some levels have multiple exits, but you always achieve the same on the worldmap independently on what you did on the level. Maybe in addition to the Final Goal and End Seq points, something could be used to save a specific message for the time when the player finishes or exits the level. When the level is finished, this message is used by the worldmap e.g. to unlock paths.
