### ISSUE TITLE
Spring requires 2 jumps to bounce high

### ISSUE THREAD

**Issue by ghost** [SuperTux/supertux#1037]
**SuperTux version:**
0.6.0-3-gd75e87666

**System information:**
Linux Mint 19.1 Cinnamon
Cinnamon v4.0.8
kernel: 4.15.0-43-generic

##### Expected behavior
If you hold jump button while falling onto a spring, you should jump very high.

##### Actual behavior
You jump normally. To actually use the spring's jump boost, you have to land on it again without touching the ground midway, holding the jump button.

##### Steps to reproduce actual behavior
Fall onto a spring while holding jump button.

**Comment by tobbi** [comment]
I can't reproduce the issue here. Can anyone else?

**Comment by HybridDog** [comment]
Maybe it's related to 1069.

**Comment by weluvgoatz** [comment]
Perhaps this is intentional behaviour?

**Comment by Rusty-Box** [comment]
I don't think so. But if, then this is not really ideal.

**Comment by Semphriss** [comment]
Since nothing happens here, I'm gonna close it...
