### ISSUE TITLE
Water under first bridge in forest world looks a bit ugly

### ISSUE THREAD

**Issue by Wuzzy2** [SuperTux/supertux#1040]
**SuperTux version:**
0.6.0

##### Expected behavior
In the forest world, the water under all bridges looks nice.

##### Actual behavior
The first bridge in the forest overworld (before the level “Like a leaf in the wind”) has an ugly water color. It is much darker than the surrounding water, you can see a sharp and ugly contour.

##### Steps to reproduce actual behavior
- Play Forest World, stay on the overworld
- Go to the first bridge
- Look at the bridge

**Comment by Rusty-Box** [comment]
@Wuzzy2 This is not related to the water graphics them selves. The weird contour is a part of the currently "not so good" brown bridge graphics and those are indeed in need of a redraw.
