### ISSUE TITLE
Arabic is broken in 0.6.0

### ISSUE THREAD

**Issue by Fahad-Alsaidi** [SuperTux/supertux#1045]
**SuperTux version: 0.6.0 appimage**
**System information:  KDE neon**

I though after closing #97 that Arabic is going to displayed correctly. I don't know what's happen after that. However, Arabic is broken.

![image](https://user-images.githubusercontent.com/1632566/51088101-1c01c000-1775-11e9-8589-2e6edb34fe12.png)

**Comment by christ2go** [comment]
Is the orientation still wrong or do you mean the missing translation?

**Comment by Fahad-Alsaidi** [comment]
> Is the orientation still wrong or do you mean the missing translations?

orientation is wrong. It is from LTR and not connected. The right thing here:
![index](https://user-images.githubusercontent.com/1632566/51088428-f4145b80-1778-11e9-9feb-2eef117f5062.png)

**Comment by tobbi** [comment]
@Grumbel Do you have any idea why this happened? Do we need another font for Arabic after all?

**Comment by Fahad-Alsaidi** [comment]
@tobbi it is not about font, it is about shaping & rendering.

**Comment by Grumbel** [comment]
Might be something simple like not defining `HAVE_RAQM`?

**Comment by Grumbel** [comment]
Looks like it got broke in 10c6d0df7dd12506408faf81a56d48a2f029a85c, which switched from configure to using cmake for SDL_ttf.

**Comment by tobbi** [comment]
@Fahad-Alsaidi Can you please verify that https://prnt.sc/ntbjz2 is correct again?

**Comment by Fahad-Alsaidi** [comment]
@tobbi Yes, it is correct. Thanks for your work.

**Comment by tobbi** [comment]
Fixed with #1114
