### ISSUE TITLE
Inconsistencies with the Icy Island

### ISSUE THREAD

**Issue by weluvgoatz** [SuperTux/supertux#1046]
Expected: At the beginning of "A Yeti in the distance", the end poles and igloo should be there, because they were JUST there at the end of the previous level, which takes place in this exact spot.

Actual: The igloo and end poles have magically disappeared. Did Tux take them down? Did they Yeti break them? It's pretty lazy and inconsistent that they were magically disappeared without explanation.

Solution: Maybe remove them from the previous level, or add them to the cutscene? Or make the cutscene at the end of the previous level? Please fix.

**Comment by Rusty-Box** [comment]
I don’t see this as an issue. The goal pole and the igloo (same goes for the forest variation) are meant (for me atleast) only as a way of marking the end of a level. This means that they don’t have to exist in a cutscene as it would look quite ugly.

**Comment by weluvgoatz** [comment]
I suggest maybe merging the level and cut-scene together as to get rid of
the inconsistency altogether, if that is possible.

**Comment by Rusty-Box** [comment]
The goal poles and exit houses do not really exist in Tux's Journey. They just serve to mark the end of a level for players. Closing this.
