### ISSUE TITLE
Inconsistencies with the Icy Island #2

### ISSUE THREAD

**Issue by weluvgoatz** [SuperTux/supertux#1047]
Expected: In the level, "Over the Frozen Bridge", the pipes appear to all be solid.

Actual: Two of the pipes are unisolid, rather than solid, which is inconsistent and confusing.

Solution: Maybe change it to the other dark background tiles that show up in this level? I know a solid platform is needed to get to atop the high platform, but please make it consistent with the rest of the level.

**Comment by Rusty-Box** [comment]
I have too agree with that.
