### ISSUE TITLE
Building blocks are very broken. Consider removal from official levels

### ISSUE THREAD

**Issue by Wuzzy2** [SuperTux/supertux#1053]
**SuperTux version:** 0.6.0

##### Problems
The building blocks seem to be very broken and buggy.

- They wiggle by about 1px up and down all the time. It gets worse when you stack them
- It's easy to hurt yourself (re-catching a flying building block does not work)
- Building blocks stacking is even more broken (evidence video: https://youtu.be/aDMH9DwsOaE)

##### Steps to reproduce actual behavior
Play around with building blocks.

##### Request
I request to remove building blocks from all official levels until they have been fixed AND are balanced out to improve the game quality.
It's very frustrating to have levels with broken mechanics in the official levels.
Alternatively to remove/disable official levels that contain building blocks.

**Comment by brmbrmcar** [comment]
No, it should just be fixed in my opinion, as it would be far easier overall and there wouldn't be a release between it or anything.

**Comment by divVerent** [comment]
From making a level myself, I learned that trampolines have the same issue: stack two trampolines on top of each other, and it becomes very easy to kill yourself by removing the bottom one.

**Comment by Wuzzy2** [comment]
Bug still present in 0.6.1 beta 1.

**Comment by tobbi** [comment]
In my opinion, this issue has been fixed in the latest nightly (not sure about 0.6.2). Therefore I'm closing this issue. If you disagree, please re-open it.
