### ISSUE TITLE
SuperTux crashes on add-on check

### ISSUE THREAD

**Issue by plonibarploni** [SuperTux/supertux#1054]
In SuperTux 0.6.0-105-bb3bcae, when I attempt to check online for add-ons, instead of downloading the add-ons, the program just crashes with a 'Segmentation fault'.

**Comment by tobbi** [comment]
Do you know how to get a stack trace? That'd help.

**Comment by plonibarploni** [comment]
This is what I get when I run it in debugging mode:

> Thread 1 "supertux2" received signal SIGSEGV, Segmentation fault.
0x0000555555a38338 in std::vector<std::function<void (bool)>, std::allocator<std::function<void (bool)> > >::push_back(std::function<void (bool)> const&) (
    this=0x10, __x=...) at /usr/include/c++/7/bits/stl_vector.h:941
941		if (this->_M_impl._M_finish != this->_M_impl._M_end_of_storage)

Backtrace:

> #0  0x0000555555a38338 in std::vector<std::function<void (bool)>, std::allocator<std::function<void (bool)> > >::push_back(std::function<void (bool)> const&) (
    this=0x10, __x=...) at /usr/include/c++/7/bits/stl_vector.h:941
#1  0x0000555555a38197 in TransferStatus::then(std::function<void (bool)> const&) (this=0x0, callback=...)
    at /home/user/Downloads/supertux/src/addon/downloader.hpp:61
#2  0x0000555555c971d1 in DownloadDialog::DownloadDialog (this=0x5555587064c0, 
    status=
    std::shared_ptr<TransferStatus> (use count 1483760856, weak count 21844) = {...}, auto_close=false, passive=false)
    at /home/user/Downloads/supertux/src/supertux/menu/download_dialog.cpp:33
#3  0x0000555555c90826 in std::make_unique<DownloadDialog, std::shared_ptr<TransferStatus>&, bool, bool&> (__args#0=
    std::shared_ptr<TransferStatus> (use count 4, weak count 0) = {...}, 
    __args#1=@0x7fffffffd2e0: false, __args#2=@0x5555586f80f0: false)
    at /usr/include/c++/7/bits/unique_ptr.h:825
#4  0x0000555555c8f1f7 in AddonMenu::check_online (this=0x5555586f8070)
    at /home/user/Downloads/supertux/src/supertux/menu/addon_menu.cpp:282
#5  0x0000555555c8edce in AddonMenu::menu_action (this=0x5555586f8070, 
    item=...)
    at /home/user/Downloads/supertux/src/supertux/menu/addon_menu.cpp:218
#6  0x0000555555a7ffbd in Menu::process_action (this=0x5555586f8070, 
---Type <return> to continue, or q <return> to quit---
    menuaction=@0x7fffffffd448: MenuAction::HIT)
    at /home/user/Downloads/supertux/src/gui/menu.cpp:506
#7  0x0000555555a7fcc7 in Menu::process_input (this=0x5555586f8070, 
    controller=...) at /home/user/Downloads/supertux/src/gui/menu.cpp:457
#8  0x0000555555a8b04d in MenuManager::process_input (this=0x555558256470, 
    controller=...)
    at /home/user/Downloads/supertux/src/gui/menu_manager.cpp:173
#9  0x00005555559d19c4 in ScreenManager::update_gamelogic (
    this=0x7fffffffd7d0, dt_sec=0.0100000007)
    at /home/user/Downloads/supertux/src/supertux/screen_manager.cpp:221
#10 0x00005555559d235a in ScreenManager::run (this=0x7fffffffd7d0)
    at /home/user/Downloads/supertux/src/supertux/screen_manager.cpp:424
#11 0x00005555559bd9ee in Main::launch_game (this=0x7fffffffdef7, args=...)
    at /home/user/Downloads/supertux/src/supertux/main.cpp:528
#12 0x00005555559be1d9 in Main::run (this=0x7fffffffdef7, argc=1, 
    argv=0x7fffffffdfe8)
    at /home/user/Downloads/supertux/src/supertux/main.cpp:598
#13 0x00005555559bbe29 in main (argc=1, argv=0x7fffffffdfe8)
    at /home/user/Downloads/supertux/src/main.cpp:23
