### ISSUE TITLE
Segfault on contrib level

### ISSUE THREAD

**Issue by afontenot** [SuperTux/supertux#1057]
**SuperTux version:** 0.6.0 release
**System information:** Linux 4.20.4-arch1-1-ARCH

In `ATTNW1/16 - spaceship_secret.stl` I frequently get a crash near the rotating color wall early in the level. Usually either right before it at the powerup or right after it at the Nolok statue. 

Edited to add: I don't think I see the crash if I switch the renderer to SDL.

Backtrace:
> 0x00007fffef9d0b0e in ?? () from /usr/lib/dri/i965_dri.so
0x00007fffef9d098e in ?? () from /usr/lib/dri/i965_dri.so
0x00007fffef9d0ca4 in ?? () from /usr/lib/dri/i965_dri.so
0x00007fffef9d08ad in ?? () from /usr/lib/dri/i965_dri.so
0x00007fffef9d0935 in ?? () from /usr/lib/dri/i965_dri.so
0x00007fffef9da4ab in ?? () from /usr/lib/dri/i965_dri.so
0x00007fffefb00751 in ?? () from /usr/lib/dri/i965_dri.so
0x0000555555ca080d in GLPixelRequest::request (this=0x7fffffffd290, x=114, y=80)
    at /home/adam/Downloads/supertux/SuperTux-v0.6.0-Source/src/video/gl/gl_pixel_request.cpp:56
0x0000555555c9f613 in GLPainter::get_pixel (this=0x555556c29f60, request=...)
    at /home/adam/Downloads/supertux/SuperTux-v0.6.0-Source/src/video/gl/gl_painter.cpp:483
0x00005555559fbedb in Canvas::render (this=0x555556c28698, renderer=..., filter=Canvas::ALL)
    at /home/adam/Downloads/supertux/SuperTux-v0.6.0-Source/src/video/canvas.cpp:99
0x0000555555a04c16 in Compositor::render (this=0x7fffffffd560)
    at /home/adam/Downloads/supertux/SuperTux-v0.6.0-Source/src/video/compositor.cpp:74
0x00005555559cc26c in ScreenManager::draw (this=0x7fffffffd850, compositor=...)
    at /home/adam/Downloads/supertux/SuperTux-v0.6.0-Source/src/supertux/screen_manager.cpp:189
0x00005555559ccd8e in ScreenManager::run (this=0x7fffffffd850)
    at /home/adam/Downloads/supertux/SuperTux-v0.6.0-Source/src/supertux/screen_manager.cpp:428
0x00005555559b724c in Main::launch_game (this=0x7fffffffdf37, args=...)
    at /home/adam/Downloads/supertux/SuperTux-v0.6.0-Source/src/supertux/main.cpp:528
0x00005555559b7a37 in Main::run (this=0x7fffffffdf37, argc=2, argv=0x7fffffffe028)
    at /home/adam/Downloads/supertux/SuperTux-v0.6.0-Source/src/supertux/main.cpp:598
0x00005555559b5738 in main (argc=2, argv=0x7fffffffe028)
    at /home/adam/Downloads/supertux/SuperTux-v0.6.0-Source/src/main.cpp:23

**Comment by tobbi** [comment]
This is a graphics driver issue. There is nothing we can do about it. Can you report it to the Arch people, please?
