### ISSUE TITLE
Carrying a Mr. Ice Block while invincible, and going into another bad guy kills the Mr. Ice Block

### ISSUE THREAD

**Issue by n3rdopolis** [SuperTux/supertux#1059]
**SuperTux version:** Master
**System information:** Linux, Debian Testing
 
##### Additional debugging information

*If available, please attach a backtrace of a crash (you can get one using GDB or another debugger), or a core dump. If you're on GNU/Linux and your distro is using systemd, it's highly likely that a core dump is available using `coredumpctl(1)`.
If the issue only occurs in a custom level, please attach that too.*

##### Guidelines for reporting issues

- [x] I have read <https://github.com/SuperTux/supertux/blob/master/CONTRIBUTING.md#bug-reports>.
- [x] I verified this isn't an issue that's already been reported.
- [x] This report only includes details about **one** (1) issue, feature request or topic.
- [x] If I make a mistake while submitting this report I will use the edit feature instead of closing this issue and opening a new one.
- [x] This issue is **not** about wrong translations (use Transifex for those), or anything unsupported (e.g. third-party add-ons).
- [x] Once you're done, please remove the section 'Guidelines for reporting issues', the 'Additional debugging information' if it is empty, and any text in *italic font*.

**Comment by HybridDog** [comment]
Where is the code for the

**Comment by HybridDog** [comment]
I've found the relevant code; there's the PR: #1095
