### ISSUE TITLE
Mattie's World Add-on Not opening

### ISSUE THREAD

**Issue by Ronnie101** [SuperTux/supertux#106]
Every time I try to open the Mattie's World Add-on, it takes me back to the start screen, Im not sure what the issue is, I just wanted to play the levels

**Comment by tobbi** [comment]
Do you have anything useful in the game console? Or in the Terminal you start SuperTux from?

**Comment by Ronnie101** [comment]
I use supertux on my laptop, but even after I tried everything I could to fix it, I ended up having to uninstall the entire game and restart

**Comment by tobbi** [comment]
Does it work now after you did that?

**Comment by Ronnie101** [comment]
Yea it did, I just dont want other people to have to uninstall everything and have to restart

**Comment by tobbi** [comment]
Unfortunately, it's now quite difficult to find out what went wrong. So, if you have the same issue again, please notify us here, and reopen the bug report.
