### ISSUE TITLE
Carried Objects only survive in a sector

### ISSUE THREAD

**Issue by n3rdopolis** [SuperTux/supertux#1060]
**SuperTux version:** Master
**System information:** Debian Testing

##### Additional debugging information

*If available, please attach a backtrace of a crash (you can get one using GDB or another debugger), or a core dump. If you're on GNU/Linux and your distro is using systemd, it's highly likely that a core dump is available using `coredumpctl(1)`.
If the issue only occurs in a custom level, please attach that too.*

**Comment by n3rdopolis** [comment]
[level1.tar.gz](https://github.com/SuperTux/supertux/files/2848341/level1.tar.gz)

**Comment by Rusty-Box** [comment]
Sounds like a neat thing to have. Would possible allow form some sort of puzzel element in levels.

**Comment by tobbi** [comment]
This would be a breaking change. Do we have levels that rely on the ability for you to not be able to take objects with you?

**Comment by HybridDog** [comment]
>This would be a breaking change.

It would probably also be difficult to design a level with trampolines in some sections and ensure that in other sections Tux cannot use a trampoline.
You could add a level setting which allows carrying objects to other sectors (enabled by default only for new levels).

**Comment by Rusty-Box** [comment]
> Do we have levels that rely on the ability for you to not be able to take objects with you?

@tobbi Not as far as I know. At least none of the offical levels.

> It would probably also be difficult to design a level with trampolines in some sections and ensure that in other sections Tux cannot use a trampoline.

Not neccesarrly. With careful planning it is easily doable.

> You could add a level setting which allows carrying objects to other sectors (enabled by default only for new levels).

@HybridDog That is a good way of implementing this. I know a few level editors who handle it that way. Having a checkbox for allowing object "transport" through level warps (i.e doors, script trigger) could be a good way of handling it. But the default should then be set to false.

**Comment by tobbi** [comment]
> > You could add a level setting which allows carrying objects to other sectors (enabled by default only for new levels).
> 
> @HybridDog That is a good way of implementing this. I know a few level editors who handle it that way. Having a checkbox for allowing object "transport" through level warps (i.e doors, script trigger) could be a good way of handling it. But the default should then be set to false.

We would also introduce some inconsistency into the game.

**Comment by Rusty-Box** [comment]
@tobbi Like I said, it is quite possible to design levels with this feature existing permanently. The main levels don't seem to cause any hinderends and if they or other offical levels do we will make them adapt.

**Comment by n3rdopolis** [comment]
> This would be a breaking change. Do we have levels that rely on the ability for you to not be able to take objects with you?

I feel like it makes more sense, if Tux picks up a Mr. Ice Block, and goes through a door to another sector, he loses it, but then if you can go to the other sector again, Tux magically gets the Mr. Ice Block again

**Comment by HybridDog** [comment]
> That is a good way of implementing this.

It's not necessarily good: you need extra code if you have both cases (setting on and setting off). If there are no compatibility problems, it is better to always allow carrying the object to the other sector I think. 

> I feel like it makes more sense, if Tux picks up a Mr. Ice Block, and goes through a door to another sector, he loses it, but then if you can go to the other sector again, Tux magically gets the Mr. Ice Block again

To me it makes less sense. If you keep star and other powerups, you should also keep the carried object.

> With careful planning it is easily doable.

You're right. I think if you simply put a ladder, Tux cannot keep the carried object.

**Comment by Semphriss** [comment]
Given the amount of time this has gone undiscussed, I'll close as intended behavior; if this is still wanted, please create a [Discussion](https://github.com/SuperTux/supertux/discussions) to give a space to discuss about how the new method will be handled.
