### ISSUE TITLE
icicles hit by fire flower bullets are still dangerous as they fall

### ISSUE THREAD

**Issue by n3rdopolis** [SuperTux/supertux#1061]
**SuperTux version:** Master
**System information:** Debian Testing

##### Hit a low enough icicle with a fire flower bullet, and run under it as it falls.

**Comment by weluvgoatz** [comment]
As far as I know, hitting the fireball isn't melting it, but rather loosening it so it falls.

**Comment by Rusty-Box** [comment]
This behavior seems to be intended as it is never shown to be melting. And since logically a falling stalactite is nothing to be standing right under when it falls, I am closing this.
