### ISSUE TITLE
Can't open 'Contrib Levels'

### ISSUE THREAD

**Issue by plonibarploni** [SuperTux/supertux#1064]
**SuperTux version:**
SuperTux 0.6.0-112-4c21606

**System information:**
Ubuntu Mate 18.04.1
Kernel Linux 4.15.0-45-generic x86_64

##### Expected behavior
I should be able to access and play contributed levels.

##### Actual behavior
When I attempt to open 'Contrib Levels', SuperTux hangs for about a minute, then exits.

##### Steps to reproduce actual behavior
Check for add-ons, and install (and enable) the world 'The Frozen Mountains', and then click 'New game' > 'Contrib Levels'. At this point it should hang and then exit.

##### Additional debugging information
This is the output when running from a terminal:
>[WARNING] /home/user/Downloads/supertux/src/supertux/world.cpp:61 Failed to load levels/misc/info:Couldn't open file 'levels/misc/info': 11
[WARNING] /home/user/Downloads/supertux/src/util/log.cpp:84 
[TINYGETTEXT] levels/monde/en.po:15: error: expected 'msgid': ﻿#: levels/monde/info
[WARNING] /home/user/Downloads/supertux/src/util/log.cpp:84 
[TINYGETTEXT] levels/monde/en.po:15: error: expected 'msgid': ﻿#: levels/monde/info
[WARNING] /home/user/Downloads/supertux/src/util/log.cpp:84 
[TINYGETTEXT] levels/monde/en.po:15: error: expected 'msgid': ﻿#: levels/monde/info
[WARNING] /home/user/Downloads/supertux/src/util/log.cpp:84 
[TINYGETTEXT] levels/monde/en.po:15: error: expected 'msgid': ﻿#: levels/monde/info
[WARNING] /home/user/Downloads/supertux/src/util/log.cpp:84 
[TINYGETTEXT] levels/monde/en.po:15: error: expected 'msgid': ﻿#: levels/monde/info
[WARNING] /home/user/Downloads/supertux/src/util/log.cpp:84 
[TINYGETTEXT] levels/monde/en.po:15: error: expected 'msgid': ﻿#: levels/monde/info
[WARNING] /home/user/Downloads/supertux/src/util/log.cpp:84 
[TINYGETTEXT] levels/monde/en.po:15: error: expected 'msgid': ﻿#: levels/monde/info
[WARNING] /home/user/Downloads/supertux/src/util/log.cpp:84 
[TINYGETTEXT] levels/monde/en.po:15: error: expected 'msgid': ﻿#: levels/monde/info
[WARNING] /home/user/Downloads/supertux/src/util/log.cpp:84 
[TINYGETTEXT] levels/monde/en.po:15: error: expected 'msgid': ﻿#: levels/monde/info
[WARNING] /home/user/Downloads/supertux/src/util/log.cpp:84 
[TINYGETTEXT] levels/monde/en.po:15: error: expected 'msgid': ﻿#: levels/monde/info
[WARNING] /home/user/Downloads/supertux/src/util/log.cpp:84 
[TINYGETTEXT] levels/monde/en.po:15: error: expected 'msgid': ﻿#: levels/monde/info
[WARNING] /home/user/Downloads/supertux/src/util/log.cpp:84 
[TINYGETTEXT] levels/monde/en.po:15: error: expected 'msgid': ﻿#: levels/monde/info
[WARNING] /home/user/Downloads/supertux/src/util/log.cpp:84 
[TINYGETTEXT] levels/monde/en.po:15: error: expected 'msgid': ﻿#: levels/monde/info
[WARNING] /home/user/Downloads/supertux/src/util/log.cpp:84 
[TINYGETTEXT] levels/monde/en.po:15: error: expected 'msgid': ﻿#: levels/monde/info
[WARNING] /home/user/Downloads/supertux/src/util/log.cpp:84 
[TINYGETTEXT] levels/monde/en.po:15: error: expected 'msgid': ﻿#: levels/monde/info
[WARNING] /home/user/Downloads/supertux/src/util/log.cpp:84 
[TINYGETTEXT] levels/monde/en.po:15: error: expected 'msgid': ﻿#: levels/monde/info
[WARNING] /home/user/Downloads/supertux/src/util/log.cpp:84 
[TINYGETTEXT] levels/monde/en.po:15: error: expected 'msgid': ﻿#: levels/monde/info
[WARNING] /home/user/Downloads/supertux/src/util/log.cpp:84 
[TINYGETTEXT] levels/monde/en.po:15: error: expected 'msgid': ﻿#: levels/monde/info
[WARNING] /home/user/Downloads/supertux/src/util/log.cpp:84 
[TINYGETTEXT] levels/monde/en.po:15: error: expected 'msgid': ﻿#: levels/monde/info
[WARNING] /home/user/Downloads/supertux/src/util/log.cpp:84 
[TINYGETTEXT] levels/monde/en.po:15: error: expected 'msgid': ﻿#: levels/monde/info
[FATAL] /home/user/Downloads/supertux/src/supertux/main.cpp:604 Unexpected exception: couldn't create texture: Texture dimensions are limited to 16384x16384

**Comment by tobbi** [comment]
@plonibarploni Is this still an occuring thing? If so, does disabling add-ons help?

**Comment by plonibarploni** [comment]
@tobbi The issue has been fixed. It no longer crashes.
