### ISSUE TITLE
Death after pressing lever

### ISSUE THREAD

**Issue by HybridDog** [SuperTux/supertux#1065]
After pressing the lever in the village level on the forest map I always die. Is this supposed to happen?
[death lever world2_village.stl.mp4.zip](https://github.com/SuperTux/supertux/files/2873075/death.lever.world2_village.stl.mp4.zip)

**Comment by Rusty-Box** [comment]
The village level has been removed from the current version.

**Comment by HybridDog** [comment]
You're right, sorry. I somehow didn't notice that my supertux was so old.

**Comment by Rusty-Box** [comment]
No worries.
