### ISSUE TITLE
Mr. Ice Block elastic collisions

### ISSUE THREAD

**Issue by HybridDog** [SuperTux/supertux#1066]
![2019-02-19-125450_1920x1080_scrot](https://user-images.githubusercontent.com/3192173/53013432-18cdb400-3446-11e9-8e42-5c26760c3a5d.png)
![img](https://upload.wikimedia.org/wikipedia/commons/c/c6/Elastischer_sto%C3%9F.gif)

Currently when Mr. Ice Block collides with another one, it simply kills the second one.
For some badguys, different behaviour could be added when colliding with a Mr. Ice Block.
For example, when the moving Mr. Ice Block collides with a quiet Mr. Ice Block, the moving one could stop and the quiet one could start moving.

**Comment by brmbrmcar** [comment]
I personally feel that if this were implemented and the iceblocks stayed at the same speed when kicked or thrown that they currently are, it would make things too hard. I know a lot of people want more difficulty, but I though that SuperTux was meant to be fun not challenging.

**Comment by Alzter** [comment]
I feel like this is a bit _too_ realistic for SuperTux and would just be confusing / frustrating. Maybe if this is changed somewhat and made more subtle it'd be more suitable.

**Comment by HybridDog** [comment]
You could enable the elastic collision only if the second Mr. Ice Block is not walking around. Then it happens only if Tux jumps on both and then kicks one into the other one (and in very rare edge cases where some enemy jumps onto the second Mr. Ice Block).

**Comment by Semphriss** [comment]
Since this has been inactive for a bit, I'll go with the current popular vote (two voices, plus mine if it counts) and close this issue.
