### ISSUE TITLE
Bonus island III secret worldmap broken, all levels inaccessible

### ISSUE THREAD

**Issue by boomboompsh** [SuperTux/supertux#1068]
**SuperTux version:** v0.6.0
**System information:** kernel release: 4.20.11-arch2-1-ARCH
I am running arch linux, with the supertux version from the community repository. the error is also present on the release binary.

##### Expected behavior
being able to follow the paths on the secret worldmap to play the secret levels

##### Actual behavior
Tux continues to follow the main map paths, and there is no way to restore display of the main map
##### Steps to reproduce actual behavior
enter the secret worldmap in bonus island III

**Comment by plonibarploni** [comment]
On the latest build, I find that I am able to access the first secret level, but then I cannot access the rest, because just before the next level there's a "level" that says:

> Congratulations... You found the secret pathway!

But there is no level there, and no way to pass it.

**Comment by Rusty-Box** [comment]
I believe @serano01 was working on a potential fix. So, I assigne you.

**Comment by serano01** [comment]
Yes, I worked on an radical Overhaul, instead to an underground secret path, it now leads to an second Twin Island, where the levels are now accessible. It's not perfect, but an huge improvement in my opinion. So I'm closing this, since the error no longer exists.
