### ISSUE TITLE
Jump on Snail does not always work

### ISSUE THREAD

**Issue by HybridDog** [SuperTux/supertux#1069]
If I jump on a Snail which moves down a slope, it sometimes stays unharmed.
![mpv-shot0001](https://user-images.githubusercontent.com/3192173/53341859-f7207100-390c-11e9-94a4-f8c536af07ff.jpg)
Here's a video where it happens: [v.webm.zip](https://github.com/SuperTux/supertux/files/2900808/out3.webm.zip)

**Comment by tobbi** [comment]
Fixed by #1304
