### ISSUE TITLE
The Silent Walls level doesn't work

### ISSUE THREAD

**Issue by maceleiro** [SuperTux/supertux#107]
It is impossible to overcome the level, is the last level of the castle in the forest world

**Comment by maceleiro** [comment]
Sorry :)

**Comment by tobbi** [comment]
At which point do you have problems with this level?

**Comment by Mathnerd314** [comment]
I just beat this level (twice), so it is not impossible at all.

**Comment by maceleiro** [comment]
@tobbi Some woods will not let me go: http://youtu.be/8NoJq54MEyo

And another question that has nothing to do: you can hide out the terminal in Windows in parallel with the game?

**Comment by tobbi** [comment]
There's a way to do that, but should I spoil it? :smile: 
Anyway, you notice that only one of the barriers can be open at a time, right? That should possibly give you some ideas what to do?
I have no idea whether it's possible to hide the terminal window.

**Comment by maceleiro** [comment]
Honestly, I've spent enough time researching ... Could you tell? :pray:

It would be nice to disable the terminal. It would be another improvement for the new version. :smile:

And please, add the game in the Windows Store (Windows 8, 8.1 and 10): https://dev.windows.com/en-us/ Thanks!

**Comment by maceleiro** [comment]
I do not ask me how, but I completed the level. :open_mouth:

**Comment by tobbi** [comment]
:D Good. That means you don't need me to screencast a solution :)

**Comment by sydneyjd** [comment]
LOL, Congrats @maceleiro.

**Comment by maceleiro** [comment]
Thanks @sydneyjd :smile: @tobbi Me I can after that, I am a professional of Supertux? :smile: 

@tobbi Bug in add-ons: https://github.com/SuperTux/supertux/issues/110

**Comment by Fabian42** [comment]
It's really not apparent that this camera dude is what's causing the doors to close. I think the level should be reshaped a bit to make it clear. The first door just opens when you get near it, the second one closes when you're near it. And since the window is so small for the third door to not get seen, it just looks like it closes right after the second door or right when it gets on screen.

**Comment by maxteufel** [comment]
@Fabian42 This level will be removed anyway due to the Forest redesign (cc: @SuperTux/level-designers).
