### ISSUE TITLE
Knocked-out badguys move in front of water

### ISSUE THREAD

**Issue by lheckemann** [SuperTux/supertux#1073]
**SuperTux version:** 0.6.0
**System information:** NixOS 18.09, Linux 4.14.98

##### Expected behavior

When a badguy is behind a foreground water layer (?), it should remain behind the layer even when knocked out (e.g. by an ice cube).

##### Actual behavior

Badguys move in front of the water when knocked out.

##### Steps to reproduce actual behavior

Play "The shattered bridge" and knock some badguys out using ice cubes.

**Comment by HybridDog** [comment]
This is intentional behaviour: corpses are put to the front layer so that they cannot reveal secret areas.
