### ISSUE TITLE
Getting an egg while climbing a ladder causes falling off

### ISSUE THREAD

**Issue by lheckemann** [SuperTux/supertux#1074]
**SuperTux version:** 0.6.0
**System information:** NixOS 18.09, Linux 4.14.98

##### Expected behavior

When climbing a ladder and touching an egg, Tux grows and continues climbing.

##### Actual behavior

When climbing a ladder and touching an egg, Tux grows and falls off the ladder.

##### Steps to reproduce actual behavior

Climb a ladder and get hit by an egg. This can be done in "End of the tunnel", a bit after the checkpoint.

**Comment by Alzter** [comment]
IMO climbing in general needs work. #972
