### ISSUE TITLE
New home screen - Menu layout

### ISSUE THREAD

**Issue by maceleiro** [SuperTux/supertux#108]
It would be nice to make a new start screen, like the SuperTuxKart application. Furthermore, it would have to remove the buttons Start game and Levels provided, and merge them in the button Play. By pressing this button, show all worlds. Thanks!

**Comment by maceleiro** [comment]
@tobbi Any news?

The current display is quite ugly.

**Comment by tobbi** [comment]
We're debating it internally, I guess. I *could* possibly do something about this, but I have no idea whether it'd look good or not. Plus, you still should be able to watch the Tux animation in the background. If you can code something together to showcase, we can decide whether it looks good or not.

**Comment by Hume2** [comment]
So what you're suggesting is putting the main world into contrib levels and delete the "start game" button. Am I right? And how will the people recognize which world is main?

**Comment by MarkkusCraft123** [comment]
I think this is somewhat of what he means about the play button.
![this](https://cloud.githubusercontent.com/assets/11138048/9345123/8f1477c6-45d3-11e5-8e42-148ee2b0f0ad.png)
I got kind of lazy after the menu thing. :)

**Comment by maceleiro** [comment]
Exactly! The design that sent @MarkkusCraft123 is perfect! I just want to download levels function directly in the list of add-ons

**Comment by Hume2** [comment]
Now it looks like a short crappy menu...
So when I want to play levels in a levelset, I'd have to press enter once more per level. (Annoying)

**Comment by MarkkusCraft123** [comment]
It may be a tiny bit longer but it is more organized. I'm sure most people won't mind. How about temporarily implement it and see how it goes, but have an option to go back to the classic menus.

**Comment by Hume2** [comment]
It's only my opinion, so we should wait for the other developers to decide that.

**Comment by MarkkusCraft123** [comment]
Yeah, that is probably best.

**Comment by mahboi** [comment]
I believe this is what they mean: https://youtu.be/XW_nLfSbBYk (yes, I wrote this myself)

**Comment by sydneyjd** [comment]
@mahboi Sorry for the late response, but if you would like to polish up that menu then open a pull request, we would love to at least test it out.

Thanks!

Also, @MarkkusCraft123 @maceleiro @Hume2 @tobbi What do you guys think of his video?

**Comment by Hume2** [comment]
Firstly, there's the one-extra-enter annoyonce.
Secoundly, the forest world should be available after the icy island is done.

**Comment by maceleiro** [comment]
I really love the target distribution that appears in the video.

I think the forest level should always be available. I think it have to give more prominence.

**Comment by sydneyjd** [comment]
I think it should always be available also.

**Comment by Hume2** [comment]
The forest world is supposed to be after icy island, so no no. The reason why it's separate now is just that the worldmap transitions isn't done so far.

**Comment by MarkkusCraft123** [comment]
I remember that in the earlier versions of Supertux Milestone three. I don't know why it was changed. In my opinion it makes more sense that way.

**Comment by Hume2** [comment]
There was a reccession in 2010-2013. Someone has told that the forest island is for milestone 3 and therefore must be deleted. They wanted to do bugfixes instead. I hope, the bugfixes will end in 0.4.0 and there will be bigger changes after that.

**Comment by Karkus476** [comment]
This is the menu @mahboi created SuperTux/supertux/pull#121

**Comment by brmbrmcar** [comment]
Looks good, but I personally prefer the implemented version.

**Comment by sydneyjd** [comment]
Ok, we are going to do a vote. Calling @tobbi @brmbrmcar @Karkus476 @Savsish @Hume2 @mahboi @Mathnerd314 @leyyin @MarkkusCraft123 @MatzeB @maxteufel @maceleiro And everyone else. 

Vote 1: Use Mahboi's Menu #121 or one like it. 
Vote 2: Use the current design.
Vote 3: I don't like either menu.

The voting period starts at the time of this post and ends at 8PM Eastern Daylight Time September the 26th.
 
Post your vote here or in IRC. They will only be accepted in here and in IRC.

If we have equal votes on all three options, we will re-vote until one ranks higher than the others. 

Whatever gets the highest percentage wins, and we will do our best to implement that start screen.

If anyone has complaints/opinions, please voice them here.

**Comment by sydneyjd** [comment]
I vote for Option 1.

**Comment by tobbi** [comment]
I am somewhat in-between, thus voting for option 3:
1) I think that people will be expecting the menu to be like it was pre-0.4.0.
2) It makes sense to merge the two menus together, because Contrib levels are "Starting a game" as well.

**Comment by MarkkusCraft123** [comment]
I vote for option one. It makes more sense like @tobbi said. It is also more organized. As @Hume2 said, "there's the one-extra-enter annoyonce", I'm sure most people won't mind.

**Comment by mahboi** [comment]
As the author of #121, I guess that makes me automatically vote for option 1.

**Comment by Hume2** [comment]
If the test collesction was removed in 0.4.0, I'd be for option 1, because there will be no levelsets anymore.
So I vode for option 1, but I strongly recommend removing test collection in official releases, because many of those levels are unplayable. However, they could be still in the git repository.

**Comment by Karkus476** [comment]
Vote for option 1 from me :) it's more organised and maybe installed addons could appear in the play game menu????

**Comment by mahboi** [comment]
I agree with @Hume2 that the test levels should be removed for official releases, but I think that's a different issue.

**Comment by maceleiro** [comment]
Option 1

**Comment by maxteufel** [comment]
Option 3. I actually think there was the idea of using a scripted level as a menu (see `data/levels/test/menulevel.stl`) which seems like a nice solution to me.

**Comment by brmbrmcar** [comment]
Option 2.

**Comment by Karkus476** [comment]
@maxteufel  I like the idea but it would make the world maps feel out of place.

**Comment by pazkero** [comment]
It's nice, but the 'campaign' idea however, well... You basically separated in two main games. :/
They don't look a single game, they look various games in different worldmaps.
The image is better in organization, although it doesn't need the selection between Forest World and Antartica... yet, at least. For sake of simplicity, I prefer the image one, without the 3rd layer menu for main game. If you add it, people will ask: "Which one should I start with?"
It's also simpler and easier to understand. About expecting the same-old for 0.4... Well, surprise! DEV team did some redecoration. Hope you liked. ;)

So on 'Play', you can add: 'Main Levels', 'Addon Levels' and 'Bonus Islands' in that case. Don't add more than 3 buttons on this menu, 3 is actually a 'good' number, and I'm speaking in maths and marketing.
You'll need to think in a way to show were to start when you add multiple main games (giving continuity).

So in resume, Option 1/3 which makes option 0.333. :P 
Anyway... well, liked the images, but prefer the above tips. They were on IRC, you know. :)

**Comment by mahboi** [comment]
@pazkero By 'campaign', do you mean in the video? I've changed it, as seen in the screenshots for #121. I agree that 'campaign' wasn't a good word to use but I was lacking a better term so I used the first one I thought of. I probably should have polished up the menu before releasing a video, and seeing that it might cause confusion I'm going to label it as such for anybody reading this.

**Comment by pazkero** [comment]
Many thanks.
The screenshots on #121 are fine, and "Story Mode" is actually a very good name for it. Personally I think better to keep Ghost Forest on contrib as "Story: Ghost Forest" while main story is just it and Antarctica.
As I said before, an extra menu for 2 choices can be annoying if the choices are too similar. (ie. parts of the same storyline)

Personally the "Contrib levels" name could be polished as "Extra Levels", and as Bonus Islands are classics officially supported by SuperTux (as far as I remember) it can be added on the start game menu. It will have 3 buttons, which is the ideal number of buttons. ;)

And as said by hume... Until icy islands are done, I would rather keep Ghost Forest on Extra Levels, and think in how to show the sequence on Story Mode. We will probably end up using something like "1. Antarctica", and adding "3. Ghost Forest" will result in boring tickets saying "where is 2" or "Why Antarctica doesn't connect to Ghost Forest" even if we put a big red-letters warning at the intro.

So those are my ideas...
On Start Game, thee buttons: "Story Mode", "Bonus Islands" and "Extra Levels"
Story mode starts immediately, but will be named like "9. Ninth Name"
Extra Levels have prefixing words as we are talking about organization, like "Testing: Features Test" and "Story: Ghost Forest"

...Which makes my vote somewhere along 1 and 3. 1/3 is 0.333, I insist :smile: 

Ps. Should I comment #121 as well? Or is it not necessary?
--
Jesusalva

**Comment by MarkkusCraft123** [comment]
Nah, you don't need to. This is fine. But please select 1 or 2 or 3.

**Comment by Savsish** [comment]
I vote for 1.

**Comment by pazkero** [comment]
@MarkkusCraft123 It's somewhere along 1 and 3, as I said.
One like @mahboi did on #121 but with minor text changes, so it's probably a ***1***.

My vote however, is relative to your literalness. :smile: 
...But it definitively isn't 2. I liked the idea to change the menu... as most did.
--
Jesusalva

**Comment by sydneyjd** [comment]
Hehe, oops. I forgot to review this post. I will tally the vote and see what we come up with.

**Comment by Hume2** [comment]
Something between 1 and 3 means 3, because anything that is not 1 or 2 is definitely 3.

**Comment by sydneyjd** [comment]
Ok, the final tally:
Option 1: 6 people
Option 2: 1 person
Option 3: 4 people

So, i guess we will see what we can do.

**Comment by sydneyjd** [comment]
Ok, Merged. Thanks everyone!!! And thanks for the code @mahboi!
