### ISSUE TITLE
Sliding In SuperTux

### ISSUE THREAD

**Issue by weluvgoatz** [SuperTux/supertux#1081]
Just like swimming, sliding in SuperTux is considered an essential penguin behaviour according to the Internal Chat.  Multiple things worth considering about sliding are:

- Does it work on all slopes? Or just special blocks?
- How does Tux attack enemies while sliding?
- What actions can Tux do?
- Would it break levels?

**Comment by Alzter** [comment]
In my opinion sliding should:
- Kill enemies on touch.
- Only work on downwards slopes by pressing down.
- Let you gain momentum to be propelled up a slope and get launched off it.
- Be cancellable by jumping.

**Comment by qwertychouskie** [comment]
Also:
 - Be auto-cancelled when (pseudo-code) `!tux->isOnDownwardSlope() && tux->getSpeed() <= tux->getNormalRunningSpeed()`

**Comment by weluvgoatz** [comment]
Some other things:

- Does Tux need to be big or can he do it small?
- How to activate it? (My opinion: Tux should probably run, jump and press down in quick succession)

**Comment by weluvgoatz** [comment]
Also, Tux should only do the sliding when he is on *snow* slopes, I think it would be weird if Tux slid on dirt...

**Comment by Rusty-Box** [comment]
@weluvgoatz I don't think so. This would rather limit the usage of such an essential feature for a game having a penguin as a playable character. Sliding shall be aviable in any enviorment. Even the non-snow ones. Otherwise what's the point of even having it when only one world (main game speaking) would be supporting such feature.

**Comment by weluvgoatz** [comment]
Hmm, maybe it's just that the current dirt tiles (the ones from like 2005) look dry and crusty... Maybe if we had snail slime slopes or mud slopes or just ones that don't look dry... But new forest dirt tiles have already been added into the game which look slide-able.

**Comment by plonibarploni** [comment]
FWIW what I remember from playing Mario is that there was a special powerup that enable this behavior by simply consistently moving in one direction for a period of time (I think it was 3-5 seconds). The effects of it were that he looked/behaved like a snail that had been hit.

**Comment by Alzter** [comment]
> FWIW what I remember from playing Mario is that there was a special powerup that enable this behavior by simply consistently moving in one direction for a period of time (I think it was 3-5 seconds). The effects of it were that he looked/behaved like a snail that had been hit.

That's the Blue Shell from New Super Mario Bros (DS).

**Comment by HybridDog** [comment]
I stopped using the Blue Shell when I noticed (in multiplayer) that running without this powerup is faster than moving as shell.
Anyway, I think that if Tux can slide on snow and dirt slopes it's important that snow slopes have less friction than dirt or even grass slopes.

**Comment by weluvgoatz** [comment]
What level would this be introduced in?

**Comment by Rusty-Box** [comment]
@weluvgoatz It shall be introduced in the very first level of the game as it is a universal useable ability, like jumping, ducking, etc.

**Comment by weluvgoatz** [comment]
The first level already has a lot of things, how about in the first level
on the linear path with slopes? This would be either "A Fork in the Road"
or "23rd Airborne".

**Comment by Alzter** [comment]
Are we going to implement this?

**Comment by HybridDog** [comment]
> Are we going to implement this?

I think that #854 should happen first.

**Comment by weluvgoatz** [comment]
My ideas for sliding in SuperTux:
1) There should be a separate slippery slope tile that  the player can slide on that can be universal for all terrains.
2) If the player slides on any sort of slippery tile, flat or sloped, they gain momentum and continue sliding.
3) Sliding kills enemies in Tux's path that come into contact with his sides.
4) When Tux reaches a non-slick tile, he stops sliding and returns to normal.

**Comment by weluvgoatz** [comment]
My NEW ideas on sliding:
1) Tux can start sliding only on slopes, but he can slide on solid land as long as he started on the slope.
2) When sliding, he slips down with a slightly-lower friction and goes at high speed (for extra fun :D)!
3) Functions similar to buttjump, meaning he can kill basic enemies but not spiked ones (might be too OP if he was able to)
4) He starts sliding by pressing "down" on slopes, and continues sliding until he reaches an almost-zero velocity or by pressing "jump", if he hasn't already stopped.

**Comment by Alasdairbugs** [comment]
i think also if you jump and then ground pound onto a slope you immediately start sliding, and you gain even more momentum by falling from the air. This would be really cool i think.
