### ISSUE TITLE
Allow us to set .sprite files as backgrounds

### ISSUE THREAD

**Issue by 165your4** [SuperTux/supertux#1089]
Allows for animated backgrounds. You could also allow us to set the background's sprite action through scripting (like what is possible with FloatingImages), e.g. the level background is a volcano, once the player flips a lever the volcano in the background begins to erupt

**Comment by weluvgoatz** [comment]
This is a nice idea... but I think someone made a similar issue, no? See #385

**Comment by Frostwithasideofsalt** [comment]
Someone should work on this lol
