### ISSUE TITLE
Graphical issue

### ISSUE THREAD

**Issue by maceleiro** [SuperTux/supertux#109]
In the general world, there is a small problem (not very important) in the graphics: 
![Uploading graficsupertuxc.PNG…]()

**Comment by maceleiro** [comment]
Sorry, I can not attach the capture, now I go on Dropbox

**Comment by maceleiro** [comment]
![graficsupertuxc](https://cloud.githubusercontent.com/assets/11487343/9284671/0842c8f8-42de-11e5-9e13-a6a31827421f.PNG)

**Comment by maceleiro** [comment]
It is on the top right.

**Comment by sydneyjd** [comment]
@maceleiro Thanks for pointing this issue out. We are working on fixing it currently. Thanks!

**Comment by tobbi** [comment]
Fixed in 6ffd4d31
