### ISSUE TITLE
Color ignores the display gamma

### ISSUE THREAD

**Issue by HybridDog** [SuperTux/supertux#1097]
Most displays use the sRGB colour space nowadays and Color in Supertux ignores this.
A 2.2 gamma value can be used to approximate sRGB. https://en.wikipedia.org/wiki/SRGB#The_sRGB_transfer_function_(%22gamma%22)
The gamma ignorance makes some visual things in Supertux work incorrectly. For example, when the screen is gradually darkened when dying in a level, the darkening happens non-linear.

**Comment by Semphriss** [comment]
This was merged, but not automatically by GitHub. Closing :)
