### ISSUE TITLE
Worldmap events triggered inside a level

### ISSUE THREAD

**Issue by HybridDog** [SuperTux/supertux#1098]
I would like to see levels where you can press a button in a secret area and when finishing the level, something is unlocked on the worldmap, e.g. a secret path.
Currently, after finishing a level, on the worldmap Tux walks to the next level or stays on the current one if there is a secret path, which exposes the secret path. In Super Mario games you need to go to a separate level exit to unlock a secret path.
The information passed from inside the level to the worldmap could also be used to change a teleporter destination, make a boat appear, put Penny next to an igloo, and more.

**Comment by weluvgoatz** [comment]
Wasn't something similar to this already implemented?

**Comment by HybridDog** [comment]
I don't know, I'm quite unfamiliar with this topic. I also don't know why exactly the yeti looks different after it is defeated.
![jdti](https://user-images.githubusercontent.com/3192173/57646707-75fa8100-75c1-11e9-8a2a-28fc71e804d6.jpg)

**Comment by Alzter** [comment]
So you're suggesting alternate exits that unlock a different route from the level when complete?

**Comment by HybridDog** [comment]
> So you're suggesting alternate exits that unlock a different route from the level when complete?

I'm suggesting this and more complex possibilities; for example pressing a hidden button in a level can open a cave entrance on the worldmap.

**Comment by Alzter** [comment]
> > So you're suggesting alternate exits that unlock a different route from the level when complete?
> 
> I'm suggesting this and more complex possibilities; for example pressing a hidden button in a level can open a cave entrance on the worldmap.

That sounds pretty cool. Maybe there could be an unlock level script of sorts, which unlocks a level from the worldmap while in another level.

**Comment by HybridDog** [comment]
I don't know much about scripts; is it possible to add a script in the worldmap and a script in the level and these scripts can pass information to each other when entering or leaving a level?

**Comment by Alasdairbugs** [comment]
I think if there was like an avalanche in a level, then there could be a cutscene that fades out to the world map and shows the avalanche cutting off a path to another level, or something. I think that would be cool. Just the ability to switch to the worldmap and make cutscenes there would also be neat.

**Comment by Semphriss** [comment]
There is a `state` object which is shared by an entire levelset, which allows sharing information between a worldmap and its levels; does that do the job?

**Comment by HybridDog** [comment]
I remember that there are worlds where the player can collect things from levels, e.g. keys in the old forest world.

My issue is not concrete and I don't know much about scripting in SuperTux, so I'm closing it for now.
