### ISSUE TITLE
Issue After Installing Add-on

### ISSUE THREAD

**Issue by marc280492** [SuperTux/supertux#110]
After installing a world map, the home screen is me becomes: 
![captura1](https://cloud.githubusercontent.com/assets/11487343/9284050/e015e2fc-42d8-11e5-885f-1ee2e645ba07.PNG)

**Comment by tobbi** [comment]
Which world map did you install?

**Comment by maceleiro** [comment]
@tobbi Yeti's revenge

**Comment by tobbi** [comment]
Please chat with us at http://supertux.github.io/contact.html and let's see if we can resolve the problem.

**Comment by maceleiro** [comment]
@tobbi This problem happens after I get off any world map

**Comment by maceleiro** [comment]
Any news @tobbi?

**Comment by maceleiro** [comment]
Installing Levels of wolfs, I have not had the same problem. The main menu has worked for me. But I would very slow animations (including the video leaving background, Tux is very slow)

**Comment by maceleiro** [comment]
In the mobile format I not have this problem. I think that only happens in certain circumstances. I have a ASUS R510J with Windows 10. Please put the issue label.

**Comment by Karkus476** [comment]
It's difficult to know what to do unless this is reproducible. I haven't had this problem, but if you think this is something that needs fixing at this end, you need a set of instructions for us to get the same bug.

**Comment by tobbi** [comment]
I have actually never experienced this problem. No idea what might be causing this or whether it's something we can fix.

**Comment by Karkus476** [comment]
@maceleiro  Try removing the addon and trying again maybe?

**Comment by sydneyjd** [comment]
Something sounds corrupt.
@maceleiro Does it still do this?
If you don't respond in the next week i will just go ahead and close this issue.

**Comment by maceleiro** [comment]
Even I have the same problem...

**Comment by tobbi** [comment]
Can you give us a copy of your supertux profile folder?

**Comment by maceleiro** [comment]
@tobbi Where is this folder...? :smile:

**Comment by tobbi** [comment]
In .supertux in your home directory, if I recall correctly.

**Comment by maceleiro** [comment]
Thanks!! https://drive.google.com/file/d/0B6JsEr5ZVJgPZzB1UkJiVTRWWkE/view?usp=sharing

**Comment by tobbi** [comment]
Unfortunately, I cannot reproduce the issue here. I loaded your configuration files, and it displayed fine for me.

**Comment by tobbi** [comment]
By the way: Do things change if you start it with ./supertux2 --renderer sdl vs ./supertux2 --renderer opengl?

**Comment by Karkus476** [comment]
Requesting close

**Comment by tobbi** [comment]
Please re-open if this issue occurs again.
