### ISSUE TITLE
Change Tux animations

### ISSUE THREAD

**Issue by Alzter** [SuperTux/supertux#1106]
I've been working on some new Tux sprites for SuperTux, and want to make some changes to Tux's animations. Some animations I want to change will need some code edits to work, and since I don't know how to do that I'm going to ask if someone can do it for me. Here's what I want:

- New "fall" animation for Tux. Plays after Tux has completed his "jump" animation or if he falls off a ledge. If Tux jumps, he plays the "jump" animation followed by the "fall" animation, if he falls off a block or otherwise enters the air without jumping, he should play the "fall" animation.

- A "land" animation, which plays after Tux lands from a jump.

- Big Tux running animation. Give Big Tux and all other forms of Tux (Fire, Ice, etc.) a running animation.

- Remove rotation from the backflip animation. I'm planning on revamping it with a new animation, so removing rotation would be cool.

**Comment by Vankata453** [comment]
Fixed by #2333 and #2479.
