### ISSUE TITLE
Game crashes when selecting level subset then exiting

### ISSUE THREAD

**Issue by Alzter** [SuperTux/supertux#1107]
**SuperTux version: 0.6.0**
**System information:** *Windows 10*

##### Expected behavior
Going to the level editor, then selecting a level subset from the level editor followed by pressing back brings you to the level subset menu.

##### Actual behavior
Going to the level editor, selecting a level subset and then pressing back crashes the game.

##### Steps to reproduce actual behavior
Go to the level editor, select a level subset and then press back.

**Comment by tobbi** [comment]
@Alzter Can you reproduce this issue with the latest development version from http://download.supertux.org ?

**Comment by Rusty-Box** [comment]
This issue can still be reproduced after starting the editor from the main menu and selecting a level subset and exiting it again.
