### ISSUE TITLE
Add option to hide undo/redo buttons in level editor

### ISSUE THREAD

**Issue by Alzter** [SuperTux/supertux#1108]
**SuperTux version: 0.6.0**
**System information:** *Windows 10*

Can we add an option to hide and show the undo and redo buttons in the level editor?

**Comment by weluvgoatz** [comment]
Related #1103

**Comment by Rusty-Box** [comment]
I would rather suggest a repositioning of the undo/redo button. Maybe to the near the tile/object selection menu

**Comment by tobbi** [comment]
Can we redo the editor interface so that those things are at the top?

**Comment by weluvgoatz** [comment]
I'm working on this.

**Comment by Ordoviz** [comment]
The buttons are now at the top-left corner. Can this issue be considered fixed?
