### ISSUE TITLE
Add "loop postion" for looping animations

### ISSUE THREAD

**Issue by Alzter** [SuperTux/supertux#1109]
What I'm suggesting is that we add a "loop position" option to animations in .sprite files. The loop position is which frame to play the animation at when it loops. For example, I could make a running animation for Tux that has a transition into running for frames 1 - 3 and the actual running at frames 4 - 12. By setting the loop position to 4 once the animation loops Tux would continue running and skip the transition at the start of the animation for subsequent loops.

**Comment by tobbi** [comment]
You mean something like `loop-start` and `loop-end`

**Comment by Alzter** [comment]
> You mean something like `loop-start` and `loop-end`?

Yeah. Wait, does that exist already?

**Comment by tobbi** [comment]
> > You mean something like `loop-start` and `loop-end`?
> 
> Yeah. Wait, does that exist already?

no.

**Comment by Alzter** [comment]
> > > You mean something like `loop-start` and `loop-end`?
> > 
> > 
> > Yeah. Wait, does that exist already?
> 
> no.

Can you please add it?

**Comment by Rusty-Box** [comment]
Something I would really appretiate to have! Would help adding animation with build up, like jumping, for badguys like Captain Snowball and Haywire
