### ISSUE TITLE
Make cloned/mirrored .sprite actions have the same properties as the source animation

### ISSUE THREAD

**Issue by Alzter** [SuperTux/supertux#1111]
I want cloned / mirrored actions in .sprite files to get the properties of the source action. For example, if I make an action and I give it the property `(loops 1)`, and then I make an action that mirrors or clones the previous action it will have loops set to 1 for default unless otherwise specified.

**Comment by LiquidityC** [comment]
I've got a PR for this. I decided to copy the props: "fps", "loops" and "hitbox". Not sure if you wanted all that.

**Comment by tobbi** [comment]
Closed as per #1275
