### ISSUE TITLE
Bouncing snowballs sometime bouncy extremely high into the air

### ISSUE THREAD

**Issue by weluvgoatz** [SuperTux/supertux#1118]
**SuperTux version:**
WIP 0.6.1 
**System information:** *(details about your kernel, operating system, or distribution)*

Uhhhh... Windows 10?

##### Expected behavior

Bouncing snowballs jump normally, only a few tiles up.

##### Actual behavior

When they hit tiles below their previous elevation, they are hurled extremely high into the air.

##### Steps to reproduce actual behavior

Turn on developer mode, turn off Vsync, set fps to 30, and go into the level "Night Chill" and go to the area where the bouncing snowballs bounce down the hill.

**Comment by Rusty-Box** [comment]
I believe this is not really a bug but rather intended. Due to momentum the bouncing snowball gains more height after bouncing up again from a higher position. I personally like the way they can get momentum and wouldn't mind this to stay.

**Comment by weluvgoatz** [comment]
No, it jumps really far above the level no matter how low the dip is. I am aware of the small jump boost, but this is an actual bug because it hurls way farther into the air than it should. And it stays this way each time it jumps.

**Comment by Rusty-Box** [comment]
You have an example level where I can check that?

**Comment by weluvgoatz** [comment]
"Night Chill" in 0.6, where the bouncy snowballs are bouncing on the hill.

**Comment by Rusty-Box** [comment]
I cannot reproduce this issue. They jump perfectly fine and lose momentum after a while and get back to their normal jump height as usual.

**Comment by weluvgoatz** [comment]
Have you followed the steps to reproduce the issue? I am also on a slow computer, maybe that has something to do with it...

**Comment by Rusty-Box** [comment]
I did and they all behave as they should.

**Comment by Rusty-Box** [comment]
This might just a be an issue with your system but until it's for sure I'll leave this one open.

**Comment by weluvgoatz** [comment]
Yet again, another problem with my buggy computer. :P
