### ISSUE TITLE
Speedy Icecubes sometimes clip into the wall

### ISSUE THREAD

**Issue by weluvgoatz** [SuperTux/supertux#1119]
**SuperTux version:**
WIP 0.6.1
**System information:** *(details about your kernel, operating system, or distribution)*

Windows 10

##### Expected behavior

When fast icecubes hit a wall, they turn around and speed the other directions.

##### Actual behavior

They will clip a little into the wall before turning around and speeding the other direction.

##### Steps to reproduce actual behavior

Go into "Night Chill" and go to the area where there are icecubes and a thick wall and make them fast.

**Comment by christ2go** [comment]
That might be by design, our current collision detection works by moving objects some fixed amount, checking for collisions and only then resolving.  Not sure if this is a bug.

**Comment by weluvgoatz** [comment]
Closing.
