### ISSUE TITLE
Update the ground blocks in Ghostly World (Forest World)

### ISSUE THREAD

**Issue by marc280492** [SuperTux/supertux#112]
The current ground is very ugly:

![screenshot011](https://cloud.githubusercontent.com/assets/11487343/9295509/9657c114-4470-11e5-8dfb-204871dea0fb.png)

Could you please tell if this is the web where to translate SuperTux? https://www.transifex.com/arctic-games/supertux/

Thanks! :smile:

**Comment by tobbi** [comment]
Agreed, we definitely need better blocks for this. We could actually need more tiles for Ghost Forest overall.

That above URL is correct, by the way.

**Comment by Hume2** [comment]
I know that I have already failed with it, but I'll try it once again.
Would you be for this? http://supertux.lethargik.org/wiki/File:Ghostwood.png

**Comment by Karkus476** [comment]
@Hume2 can you make a pull request (with [ci skip] in the commit message) so I can pull and see what they look like in-game?

**Comment by marc280492** [comment]
The new design is beautiful! Thanks.
