### ISSUE TITLE
False assert encountered in code in 0.5.1 with empty worldmap (no levels added)

### ISSUE THREAD

**Issue by mikeweilgart** [SuperTux/supertux#1124]
**SuperTux version:** 0.5.1

**System information:** Ubuntu 18.04

##### Expected behavior

World progress files that were created only by accessing the game normally (through the UI) should not crash the game when attempting to load them.

##### Actual behavior

This line of code was triggered: https://github.com/SuperTux/supertux/blob/v0.5.1/src/scripting/serialize.cpp#L75

Here is the error message:

```
supertux2: /build/supertux-BAk5qJ/supertux-0.5.1/src/scripting/serialize.cpp:75: void scripting::load_squirrel_table(HSQUIRRELVM, SQInteger, const ReaderMapping&): Assertion `false' failed.
Aborted (core dumped)
```

##### Steps to reproduce actual behavior

I tried reproducing on a new levelset and I couldn't, so I attached the one that produces the problem.

Obviously this means I don't know ALL the preparatory steps to reproduce 100%.  However, I have some idea, as I learned how to fix it for this levelset and then un-fix it.

To fix - delete the `christopher.stsg` file with the saved info about the progress in that levelset.  This will allow the world to be opened only once, then it will crash again the next time.

Note that the crash occurs simply on clicking "play game" and then "contrib levels" - it crashes before displaying the list of worlds.

To fix permanently - edit the worldmap also, to add levels.

(I confirmed this worked, then I removed the levels from the worldmap again, confirmed that it created the problem again, and then got the coredump and tarred up the levels for this bug report.)

It has something to do with having added levels to the worldmap, and then played them, and then removed the levels again from the worldmap.  However as I said I couldn't reproduce this using ONLY those steps (on a fresh level set), so there's something more to it.

It is worth noting that all the levels, and the worldmap itself, were created and edited only via the SuperTux program itself - no manual edits.

##### Additional debugging information

[supertux2.coredump.gz](https://github.com/SuperTux/supertux/files/3313313/supertux2.coredump.gz)

[c-levels.tar.gz](https://github.com/SuperTux/supertux/files/3313341/c-levels.tar.gz)

**Comment by qwertychouskie** [comment]
Does this same crash occur in version 0.6.0?

**Comment by tobbi** [comment]
I'm closing this. Please report back when you've tried with 0.6.0.
