### ISSUE TITLE
Create a tablet mode

### ISSUE THREAD

**Issue by MarcCeleiro** [SuperTux/supertux#113]
Please create a few buttons to move Tux, specially designed for tablets, similar to Minecraft style

![f0af0d2ca00034768deec20cdb99146e_screen_512x320](https://cloud.githubusercontent.com/assets/11487343/9295545/93380d76-4471-11e5-94ef-d523a357cd53.png)

Also took the opportunity to ask a possible version for Android devices. :+1: 

Thanks!

**Comment by maceleiro** [comment]
And the option to enable or disable this option (in settings page)

**Comment by sydneyjd** [comment]
We already have an unofficial Android Port on Google Play, and Supertux is build for the desktop/laptop. Interesting idea though. Also we don't have the man-power to do something like this, and alot of phone/tablet GPUs cannot handle it from what i've seen.

**Comment by sydneyjd** [comment]
And a 70+MB game on a phone/tablet eats alot of space IMHO.

**Comment by maceleiro** [comment]
Okay, the app for Android is discarded. @sydneyjd 

But the buttons is a good idea, since now many tablets contain Windows.

**Comment by sydneyjd** [comment]
We will consider it. Thanks for the idea. Im being a little hasty with the "close issue" button, sorry.

The android port seems to be thriving. https://play.google.com/store/apps/details?id=org.lethargik.supertux2

**Comment by maceleiro** [comment]
@sydneyjd  The Android app is very nice, it works pretty well. Although I think it has not put the same code as the game for Windows. Here I send some ideas:

- Remove all animations (if not too slow).
- Remove the bonus levels to save space (let alone the Forest World and Halloween)
- Improve the loading screen (where you load the game)
- Make much larger menus (IMPORTANT)
- Hide buttons to move Tux in the home, credits and settings screens
- The arrow button (top left), what is it? Its function would be to exit the level or world map (when pressed, you leave a message confirming that you want to leave if you are within a level)
- That the arrow looking up jump to Tux:
![screenshot_2015-08-17-11-00-09](https://cloud.githubusercontent.com/assets/11487343/9301557/a5f5b6bc-44cf-11e5-8537-4a7a4a259314.png)


And an overall improvement: changing icon. I found one on the Internet that is perfect, you can ask the author to see if you can use: http://www.deviantart.com/art/Supertux-Dock-Icon-176711771

Thanks! :smile:

**Comment by tobbi** [comment]
The "up" button is needed for climbing and entering doors, so it definitely can't be removed.

**Comment by maceleiro** [comment]
So better not touch :sweat_smile: 

For what serves blue button? To climb stairs?

**Comment by tobbi** [comment]
I think it's right and left mouse button respectively.

**Comment by sydneyjd** [comment]
The blue button is 'fire'.

**Comment by maceleiro** [comment]
Okey! Thanks.

**Comment by MarkkusCraft123** [comment]
The android version on my device cannot properly display levels with lighting.

**Comment by mahboi** [comment]
@MarkkusCraft123 Gotta love them Mali OpenGL ES drivers! @maceleiro But I believe the Android port's controls are just an overlay, and you can modify them if you don't like it.

**Comment by sydneyjd** [comment]
@tobbi If i dog up the buttons can you code this for us?

**Comment by sydneyjd** [comment]
Arg, this is getting no interest... I like the idea though.

**Comment by tobbi** [comment]
I could. But let's target this for post 0.4.0. Too much work for a release that is due in 2 months.

**Comment by Hume2** [comment]
Isn't Ravu al Hemio working on this?

**Comment by qubodup** [comment]
@APPMRC your image is quite the attention grabber :) even if there was no up function: imagine running and then jumping. Imagine using one finger to press both left and up at the same time. The jump button has to be separate from the directional pad.

**Comment by weluvgoatz** [comment]
SuperTux already has a Mobile Port, please close this.

**Comment by qwertychouskie** [comment]
Especially since the issue blocking the Android port going to 0.6.0 is that the buttons lib being used is incompatible with 0.6.0's renderer.

**Comment by Semphriss** [comment]
SuperTux now has official touchscreen controls, available for the Ubuntu Touch port.

**Comment by gitmanbloggus** [comment]
is it in source? every version should have it

> SuperTux now has official touchscreen controls, available for the Ubuntu Touch port.
