### ISSUE TITLE
Objects fall unrealistically slowly

### ISSUE THREAD

**Issue by weluvgoatz** [SuperTux/supertux#1134]
I am on Windows 10.  This issue occurred sometime between the release of 0.6.0 and July 1st/2nd of 2018, because that was the latest time when I knew for sure the issue didnt exist. 
Anyway, this issue happens whenever something falls, such as Tux or a fireball or an icecrusher.  Whenever something falls, it goes down very slowly, slower than normal, and also it goes diagonally a lot slower than normal too.  Please fix, since this was a major issue in release 0.6, thank you.

**Comment by tobbi** [comment]
You mean *2019 right?

**Comment by weluvgoatz** [comment]
I said what I meant...

**Comment by HybridDog** [comment]
#1158
