### ISSUE TITLE
ReaderMapping::get returns wrong value for float vectors

### ISSUE THREAD

**Issue by tobbi** [SuperTux/supertux#1135]
I noticed the following:

In ambient_light.cpp, we have the following code in line 46:
```
 std::vector<float> color_vec;
  if (mapping.get("color", color_vec))
  {
    if (color_vec.size() < 3) {
      log_warning << "ambient-light requires three float arguments" << std::endl;
    } else {
      m_ambient_light = Color(color_vec);
    }
  }
```
The value returned by the mapping.get call is always an array of zeros, at least on my system (Mac OS X), which suggests something being wrong with the ReaderMapping. 

I am not competent enough to figure out what's wrong there, so I hope someone else will.

The result of this bug is all ambient lights being read as black so the level being completely dark.

**Comment by tobbi** [comment]
@Grumbel I'm sorry to say I don't understand enough about the reader code to know why it fails. Could you take a look?

**Comment by Grumbel** [comment]
Sure that the ReaderMapping is causing problems? I added test cases for the array reading and that seems to work fine.

**Comment by tobbi** [comment]
I've ran the test suite which ran through just fine. I changed the code above to
```
  if (mapping.get("color", color_vec))
  {
    if (color_vec.size() < 3) {
      log_warning << "ambient-light requires three float arguments" << std::endl;
    } else {
      m_ambient_light = Color(color_vec);
      // log_warning << val << std::endl;
      log_warning <<  color_vec[0] << std::endl;
      log_warning <<  color_vec[1] << std::endl;
      log_warning <<  color_vec[2] << std::endl;
      log_warning << m_ambient_light.to_string() << std::endl;
    }
  }
```

and the output was
```
[WARNING] supertux/src/object/ambient_light.cpp:53 0
[WARNING] supertux/src/object/ambient_light.cpp:54 0
[WARNING] supertux/src/object/ambient_light.cpp:55 0
[WARNING] supertux/src/object/ambient_light.cpp:56 0,000000 0,000000 0,000000
```

which makes me believe that the issue is inside the reader methods somewhere.

**Comment by tobbi** [comment]
Fixed due to recent update of the sexp lib.
