### ISSUE TITLE
Delete outdated Backgrounds

### ISSUE THREAD

**Issue by serano01** [SuperTux/supertux#1143]
I'm writing this here, so people have time to complain.

I'm planning to delete the old backgrounds, because as far as I'm informed, no one uses them anymore. Additionally, their are ancient, have only an resolution of 640x480, and look quite ugly. BlasterMaster contributed many new Backgrounds, which shall be used in future levels.

The backgrounds which are going to be deleted, are:

- arctis.png
- arctis_bottom.png
- arctis_bottom_para3.png
- arctis_top.png
- ocean.png
- extro.png
- arctis_dark.png
- arctis_para2.png
- arctis_para3.png
- forest1.png
- forest2.png

I already deleted snowtrees.png and snowtrees_back.png, because I was the sole user and Author of these, but with better artists in this project, I leave the making of backgrounds to others.

Questions and Suggestions, or other things can be posted in this Issue.

**Comment by weluvgoatz** [comment]
I just suggest making BlasterMaster's backgrounds parallax so they can be used in all sorts of times of day.

**Comment by serano01** [comment]
I've deleted them in the meantime, so I'm closing this.

**Comment by busybody42** [comment]
(RIP COMPATIBILITY)

**Comment by HybridDog** [comment]
The arctis.jpg, arctis_top.jpg, arctis_bottom.jpg and maybe more of them are used in the `The Frozen Mountains` Add-on. Now I get warning messages and see the dummy background.

For backwards compatibility, maybe fallbacks could be added: https://github.com/SuperTux/supertux/blob/ae5f833b48448f00abc8b687fab94e3c2a0e44d7/src/object/background.cpp#L354
