### ISSUE TITLE
Game is extremely laggy and jittery

### ISSUE THREAD

**Issue by Alzter** [SuperTux/supertux#1147]
**SuperTux version: Latest Nightly**
**System information:** *Windows 10*

The game framerate is extremely jittery for me and I can't get any smooth gameplay. The game randomly speeds up and slows down due to the Vsync compensation fix, which is supposed to make the game more smooth, but just ends up making the game feel unstable. The game takes up a ton of CPU and power usage for no good reason and is ridiculously laggy and jittery. The camera jitter bug is still there, when Vsync is set to "adaptive" it's less noticable but it still happens. The game is ridiculously slow and jittery when compared to 0.5.1 or any prior version and I can't discern why or how.

**Comment by weluvgoatz** [comment]
No use complaining, I've already stated these bugs so many times, but they only seem to notice you...

**Comment by Alzter** [comment]
If they noticed me they'd say or do something about this, but they won't.  At this point we might as well roll everything back to 0.5.1, at least that update worked. I've been working on a new version of SuperTux that nobody cares about in Godot, hopefully if it gets good enough people will notice and it can become Milestone 3 and we can get out of this endless development hell.

**Comment by HybridDog** [comment]
Does this mean that I'm the only one who tested my Pull Requests #1055, #1123 and #1125?
These changes made the game work smoothly for me on Linux.

**Comment by tobbi** [comment]
@Alzter is this still the case?

**Comment by weluvgoatz** [comment]
Well, this problem doesn't exist for me anymore.  The game indeed lags a bit, but it is quite playable and fun.

**Comment by tobbi** [comment]
I'm gonna close this issue for now. Should it re-occur please re-open.
