### ISSUE TITLE
Translations bug

### ISSUE THREAD

**Issue by maceleiro** [SuperTux/supertux#115]
A few months ago I helped in the translation into Catalan, I think I did on this page, but I've seen that neither was part of the translation team, and also the Catalan language has been deleted. Can someone help me out? If this is the translation page, please add the current translations of Catalan and add me as a translator.

https://www.transifex.com/arctic-games/supertux/

And before taking the final version, remember that you have to update the credits of translators if necessary!

**Comment by giby** [comment]
Oh? here you are, I just sent you a message on Tx ;) with the good link, apply again ;)

**Comment by maceleiro** [comment]
Thanks @giby!!!

**Comment by tobbi** [comment]
Can this be closed?

**Comment by maceleiro** [comment]
Yes @tobbi, thanks!
