### ISSUE TITLE
Game Sucks Up Memory and Battery

### ISSUE THREAD

**Issue by weluvgoatz** [SuperTux/supertux#1150]
Windows 10, SuperTux since after July 2018, yadah yadah...

I have noticed that the game takes up so much battery power off my computer.  Playing the game makes my computer make very loud whirring noises, presumably trying to cool off the computer.  This was not a problem prior to the pre-0.6 updates, but now it is??? I have no clue what could be causing this, besides the apparent new rendering system that was supposed to make the game run smoother but instead fricked up my system.

**Comment by Alzter** [comment]
Same for me, game takes up a lot more power ever since 0.6 and it runs slower too.

**Comment by HybridDog** [comment]
#1158

**Comment by weluvgoatz** [comment]
@HybridDog Nope, still exists, even under that Pull Request.

**Comment by HybridDog** [comment]
Then I think that this issue could be related to #1051
