### ISSUE TITLE
Won't Launch

### ISSUE THREAD

**Issue by mdavidjohnson** [SuperTux/supertux#1155]
0.6.0-1
Debian 10 Buster

Expected behavior: Install and Launch

Actual behavior Install but not launchable - But see below

Just installed Debian 10 Buster.

From my sudoer account, went to Software | All | Games | SuperTux | Install. It installed and showed UR installed icon but would not launch. SuperTux NOT shown on Installed list.

(Installed Pingus - it worked as expected).

From "fish" account, went to Software | All | Games | SuperTux. It wouldn't launch. But I noted it appeared on "Installed" list - still wouldn't launch. Went back to All | Games and noted that there was a new entry, SuperTux2 with the UR installed icon. It does NOT appear on the Installed list, but it DOES launch from the All list.

Went back to sudoer account and note that it now looks just like "fish" account with respect to SuperTux.

**Comment by tobbi** [comment]
Can you check with the people at Debian first, maybe using the IRC channel #debian on freenode?

**Comment by tobbi** [comment]
I'm gonna close this due to lack of response. If it still happens, it's most likely a debian problem and not a problem with our code.

**Comment by mdavidjohnson** [comment]
Thanks – I still haven’t figured it out – Oh well L

 

 

---

M. David Johnson

mdj@bds-soft.com
