### ISSUE TITLE
Slow download

### ISSUE THREAD

**Issue by rugk** [SuperTux/supertux#116]
Is it normal that the binary files download with 12-20 KB/s?

**Comment by sydneyjd** [comment]
@rugk What binary files are you talking about?

**Comment by rugk** [comment]
the Windows ones. FYI they have just finished. (with ~30 KB/s :snail:)
But it's the same with the others too.

As it seems they get downloaded from Amazon AWS. However I have no idea why those specific downloads are so slow.

**Comment by tobbi** [comment]
Which binaries are you talking about? The SuperTux installation file? Where did you download them from? Our Github downloads page?

**Comment by rugk** [comment]
Yes the GitHub page. It was the 64bit setup file.
I have no idea why it was so slow, but well... I wasn't in hurry.

**Comment by sydneyjd** [comment]
There is nothing we can do about it then, if it was Github's fault. 
Github Hosts it.

**Comment by rugk** [comment]
Yes I know. Just wanted to let you know - in case anyone else experiences this.
(And as the links on your website also just link to the GitHub versions, which are itself hosted on Amazon AWS I had no other choice)
