### ISSUE TITLE
Egg bounces off Tux at certain points

### ISSUE THREAD

**Issue by n3rdopolis** [SuperTux/supertux#1161]
There are certain points where the egg seems to touch, or go near Tux, that instead of Tux growing, it starts to roll in the other direction

I have found the essayist place to replicate it is in the first secret area in "...or is it just me"
https://streamable.com/8x1i9

**Comment by n3rdopolis** [comment]
It happens when Tux is at x=255, y=257
I did not figure out how to turn on the coordinates display in time for the video capture

**Comment by tobbi** [comment]
It It's not Tux the egg is touching, it's the small "rock" part to the left as it falls down. Because of this, the direction gets changed. I am not sure if this is a bug.

**Comment by n3rdopolis** [comment]
Testing again, running away before it falls, seems that sometimes it *does* bounce off that wall (sometimes it doesn't). Guess I was wrong (There were times where I thought the egg started to roll the other way, but those were faster paced, harder to replicate, and it could just be my imagination...
