### ISSUE TITLE
Wireless Xbox 360 does not work

### ISSUE THREAD

**Issue by trymeouteh** [SuperTux/supertux#1162]
**0.60 AppImage**
**Linux Mint 19.1**

I tried using a wired xbox 360 controller and a wireless xbox 360 controller. Only the wired one was registering in the game. Both controllers work since they do both work in other games on my computer.

Both controllers also work with the tarball version of SuperTuxKart, if that helps.

**Comment by Semphriss** [comment]
Closed as it went inactive for a long time. It this error is still valid, please **open a new issue**, as re-opening this old issue could go unnoticed.
