### ISSUE TITLE
More worlds for the main game

### ISSUE THREAD

**Issue by HybridDog** [SuperTux/supertux#1164]
At the moment, in the SuperTux main game there are only the main and forest
world. They do not have lots of levels, so you can finish the main game in
less than a week. Here is a suggestion for a greater world map.
Tiles and enemies already exist, for example there are castle tiles for houses,
and steel, saws, electricity, Jumpy and Spiky for the city.
In my opinion it is more important that finishing the game (with reasonable difficulty) takes a long time than having all levels strictly fulfil conditions such as being able to collect all coins.

![STworld](https://user-images.githubusercontent.com/3192173/64474144-cd27f100-d170-11e9-80f9-791f05efe46e.png)

#### World 1: Tux' Home Island
This is the first world (currently called main world I think).
Most levels are simple so that the player can get accustomed to the gameplay.
When Tux reaches the end of the Nolok's Castle level,
he sees shackles made for a penguin.
There is a hole in the wall and the manacles are forcefully broken.
Tux concludes that Nolok took Penny into chains here and is now searching for
seasoning in the forest world,
and while he is away, something broke the wall and stole Penny.
Tux exits the castle through the hole and outside he finds and follows
footsteps. Then he meets the Jeti, defeats it, and finds Penny's skull.
The Jeti has eaten Penny already; now Tux wants to take revenge on Nolok.
He travels by boat to the second world: the forest.

#### World 2: Forest
In the forest, Tux has to face new enemies.
After finishing some levels, he meets a ranger and talks to him
about the bereavement.
It turns out that a long time ago,
the ranger has lost an important person, too.
The ranger heard and investigated stories about reviving death people,
but he did not succeed for a long time,
so he gave up and accepted the death of that person.
Nonetheless, he tells Tux the stories about a secret laboratory in the city
where reviving the dead is possible.
Then he shows Tux the way to the village.
The transition between the Forest and Village worlds is smooth.
For example, there are building blocks in the forest,
ruined houses, and even a sawmill with electricity.

#### World A: Ghost Forest
The Ghost Forest is an optional Forest subworld.
If Tux goes this way, he meets ghosts who inform him about the infinite
possibilities of the world.
He comes to the conclusion that the idea of taking revenge does not help him
in the continuation of his life,
so he is no longer actively searching for Nolok.
Nonetheless, after defeating the ghost tree boss, the path leads to one of
Nolok's castles. There Tux defeats Nolok not to take revenge, but to ensure that
the kidnapping of Penguins happens never again.

#### World 3: Village
In this world, there are levels where Tux can jump around houses,
and he can meet other non-enemy life forms.
He finds the path to the city through the mountains. The world transition is
smooth again, so there are, for example, mountain cottages.

#### World 4: Mountain
This world has lots of steep levels with much stone. It is the world
between the village and the city.
The smooth transition between the mountains and the city has streets,
electricity and a few small houses.

#### World 5: City
The city has lots of skyscrapers, streets and maybe cars. Some levels are only
for climbing a big skyscraper house, or walking through an underground metro
network. Somewhere in the city, there is an entrance to the laboratory subworld.
On the other side of the city, there is a transition to another forest world.
It is similar to the transition between the forest and village world.

#### World B: Secret Laboratory
There are difficult levels and in the end, Tux can find a machine which revives
Penny. <br/>
The laboratory also has an experimental teleporter station.
In each world, Tux can find and repair a teleporter which leads to this station.
He has to repair them so that he can only teleport to worlds which
he already met before.
In the station, the teleporters are placed optimally so that it takes a very low
effort to switch between frequently visited worlds.

#### World 6: Second Forest
This is a small world which smoothly connects the city with another snow world.
Therefore there is also a smooth transition between forest and snow world,
where there falls snow in the forest. Maybe there are mudslides, puddles,
many fish, dangerous half-frozen lakes, and more.
This world also introduces fairy-type enemies. These are intelligent versions of
the usual enemies which can be visually distinguished by their wings and pair
of antennae. The fairy-type enemies could be implemented very easily.
Just make a subclass of the usual enemies where the visual fairy features
are shown and the enemy behaviour differs.
Implementation-wise the fairy-types should not have to be backwards compatible,
so, for example, a fairy snowball could use a new pathfinding algorithm to
go to Tux faster which may make some levels more difficult.
The fairy enemies are not physically stronger but only more intelligent.
For instance, a fairy crusher may stop prematurely
when it notices that it cannot hit Tux, and a fairy Snowball could change
the walking direction right before Tux jumps on it.

#### World 7: More Snow Islands
This world has many and very difficult levels. It could be very big and with
teleporters the player may go to the Bonus Islands and Incubator Island.
There also exist fairy-type enemies.

#### All Worlds
The jewel caves are hidden and spread around every world.
Furthermore, each world could have a oneway path where new levels are
added before inserting them in the main path(s) through the world.

**Comment by Rusty-Box** [comment]
I hate the yeti has eaten Penny thing. I don’t get why one wishes to make fun platformer about a penguin so dark.
Also, having a worlds be just a village/city is highly unfitting imo.

**Comment by Rami-Slicer** [comment]
> I hate the yeti has eaten Penny thing. I don’t get why one wishes to make fun platformer about a penguin so dark.

Wouldn't that also ruin the plot? 

> Also, having worlds be just a village/city is highly unfitting as well as their themes them selves, imo.

Also, SuperTux seems to take place in an area that had/has little to no humans who could build giant cities.

**Comment by Wuzzy2** [comment]
I think we have some very high-quality user worlds that would easily improve on SuperTux' story.

It would be a good idea to just drop them into the core game. But that might require a change of the story (so it makes sense in the main game).

Also, I would like it more if the game would concentrate more on the ice/snow theme. I think the whole “blue mountain” tileset is completely unused and I believe there was one level pack that made superb use of it (can't find it right now, sorry), and afaik there's only one level of “crystal cave” style. That's lot of untapped potential right here.

The forest levels are fun, but I just don't think they fit into the game's theme. Well, at least the forest is coniferous. I suggest the use of snowy trees to have a more smooth transition from arctic to forest. Currently, the transition from ice to forest is too sharp. Generally, I encourage the use of more ice/snow themed levels.

The Frozen Mountains and Hume's Crystal Cave are my favourite level packs.

Just a few random thoughts.

**Comment by HybridDog** [comment]
> It would be a good idea to just drop them into the core game. But that might require a change of the story (so it makes sense in the main game).

I think the Bonus Islands could all be put to the main game but not to the main path, so instead of going to the castle and defeating the Jeti, Tux could also go to a teleporter which leads to various Bonus Islands. 
These alternative worlds should be easily accessible, i.e. the player should not have to walk for a long time to switch between paths; for simplicity, a world selection menu could be shown when pressing ESC so that switching between worlds is as easy as selecting them the main menu. Maybe the player has to unlock some bonus worlds before being able to select them.

**Comment by Rusty-Box** [comment]
There is now a set plan for how many official worlds we want for story mode and what their themes are going to be.
Closing this.

**Comment by papb** [comment]
Hi @Rusty-Box, what is the plan?

**Comment by Rusty-Box** [comment]
We decided to go with three worlds and one final small world. The themes for the three main worlds are set in stone and will be snow, forest and tropical island.
