### ISSUE TITLE
Level editor: Show music subfolder after right-clicking on music

### ISSUE THREAD

**Issue by HybridDog** [SuperTux/supertux#1171]
This is a small issue.
If you set the music in a new level, you usually want to go to the music subfolder, so this folder could be opened by default if you right-click on the music button.

**Comment by tobbi** [comment]
Something easy for a change ;)

**Comment by tobbi** [comment]
Or not so easy, my commit caused music to not get saved.

**Comment by tobbi** [comment]
This was fixed by #1830
