### ISSUE TITLE
Dangerous tiles hurt Tux even when they are blocked off

### ISSUE THREAD

**Issue by HybridDog** [SuperTux/supertux#1175]
**SuperTux version:** v0.5.1-1937-g4d1c419ea
**System information:** lubuntu

##### Expected behavior

![2019-09-29-113032_1920x1080_scrot](https://user-images.githubusercontent.com/3192173/65830124-cf332a80-e2ac-11e9-80b4-49eb8c2f9af2.png)
Tux does not get hurt when he jumps onto the rock

##### Actual behavior
The spikes kill Tux although they are blocked by a rock object, which is as high as one tile

##### Steps to reproduce actual behavior
See the screenshot, jump onto the rock

**Comment by tobbi** [comment]
I feel like this is a collision rect problem where the collisiion rect of the spikes is maybe 1 or 2px larger than that of the block.

**Comment by HybridDog** [comment]
If I understand the collision system correctly, it firstly moves objects to target positions, which depend on the objects' velocities. Then it tests if the object at the target position intersects with a tile, and after that it tests collision with other objects.
https://github.com/SuperTux/supertux/blob/3827b0555c294e69f100525f7360b2b652362f4d/src/collision/collision_system.cpp#L494
If it works this way, Tux would also get hurt when his velocity is high enough and the rock is bigger than the spikes.

**Comment by tobbi** [comment]
That doesn't seem to be a good idea. If that's indeed the case, we'd have to change it.

**Comment by HybridDog** [comment]
Here's a similar problem:
When I press left while falling right of a wall and then release left before the end of the wall, Tux nonetheless gets hurt by the spike:
https://user-images.githubusercontent.com/3192173/105752916-2f40ec00-5f48-11eb-99d6-3bc4f7ea88b0.mp4
