### ISSUE TITLE
"Problem when reading Add-on list" in version 0.5.1

### ISSUE THREAD

**Issue by javaxubuntu** [SuperTux/supertux#1176]
**SuperTux version:** 0.5.1
**System information:** *Ubuntu Bionic*

Hi,
I love this game, and I found that I cannot install add-ons on version 0.5.1.
In the Add-ons menu, when I click on "check online", it shows the message "Problem when reading Add-on list"

##### Additional debugging information
When I click on "check online", the log is:

> [WARNING] /build/supertux-BAk5qJ/supertux-0.5.1/src/addon/downloader.cpp:339 Exception in Downloader: Problem when reading Add-on list: Parse Error at line 168: trailing garbage in stream

I've found that it downloads the file https://raw.githubusercontent.com/SuperTux/addons/master/index-0_5.nfo
If I modify Supertux to download a local file instead, I've found that I can fix the problem if I remove the right parenthesis line 167 of file index-0_5.nfo.
Then, once I've downloaded the fixed index-0_5.nfo file, there is an MD5 problem with most of the files:

> [WARNING] /build/supertux-BAk5qJ/supertux-0.5.1/src/addon/downloader.cpp:339 Exception in Downloader: Downloading Add-on failed: MD5 checksums differ

Only "Level of wolfs" can be downloaded without MD5 error.
If I modify an MD5 value to match the real MD5 of the zip file, it fixes the problem.

This issue can also be reproduced with the unofficial Android version, which also is 0.5.1.

Best regards.

**Comment by serano01** [comment]
Download should be working now. But music will not be playing, since the music folder and its files have been rearranged. I highly recommend to use the newest version 0.6.0.

**Comment by javaxubuntu** [comment]
Hi,
Thank you for the update, the MD5 are Ok now, but there is still a right parenthesis that must be removed in file [index-0_5.nfo](https://raw.githubusercontent.com/SuperTux/addons/master/index-0_5.nfo), line 166. Without this, the add-ons list cannot be downloaded.

> [WARNING] /build/supertux-BAk5qJ/supertux-0.5.1/src/addon/downloader.cpp:339 Exception in Downloader: Problem when reading Add-on list: Parse Error at line 168: trailing garbage in stream

Best regards.

**Comment by javaxubuntu** [comment]
Hi,
I successfully checked the addons list several minutes ago, the problem it's fixed. I successfully installed every addons.
Best regards.
