### ISSUE TITLE
Boss fights are too easy, short and basic

### ISSUE THREAD

**Issue by weluvgoatz** [SuperTux/supertux#1179]
https://forum.freegamedev.net/viewtopic.php?f=67&t=12590

Read this and post your ideas here or on the forum.

**Comment by HybridDog** [comment]
Here's a related issue: #1083

**Comment by Semphriss** [comment]
Since there is no definite criterion to close this issue, I'll close as vague; design discussions should happen in [GitHub Discussions](https://github.com/SuperTux/supertux/discussions) now that we have that.
