### ISSUE TITLE
Certain key combinations aren't recognized

### ISSUE THREAD

**Issue by Zwatotem** [SuperTux/supertux#1188]
**SuperTux version:** Since at least 0.1.3 to latest development builds
**System information:** Linux and Windows

##### Expected behavior
Jump while walking left
##### Actual behavior
Walks left only
##### Steps to reproduce actual behavior
Press left, up and jump simultaneously
##### Additional information

It's possible, that there are more of those combinations. In the code `m_controller- >hold(Controll::JUMP)` returns `false` while holding up and left. Strangely This doesn't occur for neither: left-down, right-down, right-up pairs.

**Comment by HybridDog** [comment]
I cannot reproduce this.
What is your keyboard layout and your SuperTux key combination settings?
Could you upload your config file (e.g. ~/.local/share/supertux2/config)?

**Comment by Zwatotem** [comment]
Oh, that must be my laptop keyboard fault. I plugged external keyboard, and there is no sign of this problem. I'm closing the thread.
