### ISSUE TITLE
Localization support for addons

### ISSUE THREAD

**Issue by LMH0013** [SuperTux/supertux#119]
Although this issue is somewhat already known, I wanted to draw some attention to it and make sure it is not forgotten.  Basically, localization does not work in addons.  Many addons have had translation work done for them, but unfortunately they have never been used since the game does not support them.  Given that there are more levels available as addons than in the regular game and the fact that there is a high potential for further growth, this really undermines the localization features of the game.

Ideally, the fix would not require adding the .po files to the addon itself since this would lead to issues with maintaining the addon list.  Perhaps a revamp of the localization is warranted (or worth discussion)- having a structure similar to the addon manager keeping all the translation files together in one place rather than having them all over file structure.  Then a particular language could be downloaded when selected instead of packaged with every distribution.  Also localization updates would not require changing the main repo and could be done after a release without issue.  This would make localization more robust and give translations the same freedom for improvement that addons currently have.

Personally I feel this is important enough that it should probably be addressed before making a stable release.  Otherwise our localization is really very partial.

**Comment by tobbi** [comment]
The main problem with this is that we can only have __one__ dictionary in tinygettext, and that is our main .po file for each language with the main supertux strings. We could, however, try to add the relevant items of each .po file in the add-ons to the dictionary...or create an add-on dictionary, I don't know yet what would be best.

**Comment by Hume2** [comment]
I think it already works. When the .po file is in the levelset in the addon, it works at least for me. Try Narreland (cs.po) or Frozen Continent (fr.po).

**Comment by LMH0013** [comment]
Check to make sure you do not have additional copies of the levels in your data directory. These can give the illusion that it is working properly.
		
        
		
		 ---- On Tue, 06 Oct 2015 07:44:16 -1000  notifications@github.com  wrote ----I think it already works. When the .po file is in the levelset in the addon, it works at least for me. Try Narreland (cs.po) or Frozen Continent (fr.po).

**Comment by Hume2** [comment]
I had, but after I deleted it, it still worked.

**Comment by tobbi** [comment]
@LMH0013: I just tested this very briefly with the "The Frozen Continent" add-on. And it works there, please check other add-ons as well.

**Comment by tobbi** [comment]
@LMH0013: Having separate locale add-ons works now. A thing to note:
*The subdirectory the language files are in has to have the same name as the add-on ID. From there, please create a subdirectory for each levelset. You can then place the po file in that directory. You can find the source for the german-language-pack in the add-ons repository.
