### ISSUE TITLE
Explosion sprites locked to 90 degree intervals

### ISSUE THREAD

**Issue by LMH0013** [SuperTux/supertux#120]
Something that has been bothering me since we moved over to SDL2 is that the one-time rotation of the sprite for bomb explosions no longer works properly.  Other things continue to handle sprite rotations correctly (rolling egg, spotlight, for example), but the explosions are fixed to 90 degree intervals for some reason.  This kind of defeats the purpose of the rotation (which was to produce a quasi-random feel for the explosions) and looks kind of off.  I feel it should be a simple fix, but have not had any luck with it.  Perhaps I've just been blinded by staring at the code too long.

**Comment by tobbi** [comment]
The angle seems correct way down till the native SDL / OpenGL function calls. I wonder if this is an issue with SDL itself...

**Comment by Hume2** [comment]
That doesn't happen to me. Maybe you only think that because the explosion sprite looks confusing, so you don't know, how it's oriented. Try changing the explosion sprite to another, where it's clear. I changed myself its sprite to bonusblock sprite and it worked correctly.

**Comment by LMH0013** [comment]
The sprite is not that confusing, and if the bug is happening it is very apparent.  Just imagine a line of several bombs exploding at the same time- many of the explosions would appear exactly the same since there could be only four orientation possibilities for any given sprite.  However, if you are not seeing it on your machine that does imply that it may be platform-specific.  In fact, I'm somewhat worried that it may be specific only to me- I have had some issues with my machine as of late, but figured that since this has been happening well before any of my issues that it was unrelated (and thus safe to report).  If the problem goes away when I finish my rebuild, and if no one else experiences the same problem, I'll just quietly close the issue and pretend that it never happened.

**Comment by tobbi** [comment]
I assume you're using the latest versions of all the dependencies?

**Comment by brmbrmcar** [comment]
I quite like them at 90 degree intervals. A completely random angle would look strange.

**Comment by tobbi** [comment]
@brmbrmcar So, you can reproduce the issue? Because I can't.

**Comment by brmbrmcar** [comment]
Yes. Shall I take a screenshot?

**Comment by tobbi** [comment]
Yes, please. Also, is this the SDL or OpenGL renderer?

**Comment by brmbrmcar** [comment]
I'm not sure about the renderer. Here is the screenshot (sorry about them being pushed together).
![screenshot from 2015-09-24 15 55 18](https://cloud.githubusercontent.com/assets/14400196/10076728/d702f45e-62d4-11e5-884f-a17e2cb34208.png)

**Comment by tobbi** [comment]
Can you check whether it's really 90 degree intervals? i.e. by adding a debug statement for the degrees to SuperTux? It might be a rendering issue.

**Comment by Hume2** [comment]
Pick a structure on the explosion and observe it how it's still on another place.
@brmbrmcar , at least what I see on your screenshot, it works correctly. I said that it looks confusing.

**Comment by LMH0013** [comment]
I have actually checked this earlier. The code does produce random angles. I think you are right that it is the renderer. I will have to check to see if all dependencies are updated, my guess is that they are not. This brings up another issue: in the past it was my understanding that SuperTux required some minimum version of each dependency, in the last year or so, the project has shifted to require up-to-date dependencies. The documentation of this has been pretty poor, with the exception of SDL2 migration. I see advantages for each approach, but regardless I think we need to figure out what ST really requires and make that clear.  My guess is that we have just lost some compatibility with older systems.
        
		
		 ---- On Thu, 24 Sep 2015 05:08:02 -1000  notifications@github.com  wrote ----Can you check whether it's really 90 degree intervals? i.e. by adding a debug statement for the degrees to SuperTux? It might be a rendering issue.

**Comment by brmbrmcar** [comment]
Before I reinstalled Ubuntu on my Chromebook, it was at 90 degree angles only. I hadn't changed anything; it was an identical build.

**Comment by Hume2** [comment]
It would be fine if you provided a screenshot. As I see, it has already confused brmbrmcar. Let me tell you whether is it real bug or just an illusion.
Anyway, what platform do you use? I use Ubuntu 14.04.

@brmbrmcar When did you take that screenshot? Did you take it when it was buggy or after that bug disappeared?

**Comment by brmbrmcar** [comment]
Just before I posted it. I was stupid and didn't realise the bug had disappeared. I have Ubuntu 14.04, Unity.

**Comment by LMH0013** [comment]
Since I wrote this particular piece of code, I'm pretty sensitive to how it behaves and don't need to be told what is an illusion.  Again, it is not confusing if you see the bug- the explosion sprite is static (which is probably something else that should be fixed at some point) with defined sub-features that if appear in one of four different spots every time looks awkward.  I'm confident enough to say this is isolated to certain older builds due to some issue in a outdated dependency.  Checking my wife's computer, it works correctly in the most recent binary.  I don't want to try to revitalize my old system for this (SuperTux doesn't even build anymore due to the changing requirements for building), so I'm going to close the issue.

**Comment by tobbi** [comment]
I'm sorry to reopen this, but it seems I am experiencing this (again). Not sure if I ever experienced this or just wasn't paying attention, but apparently this is the case.

**Comment by tobbi** [comment]
@brmbrmcar I know this might sound like I am lazy, but could you give me the test level from above?

I got a feeling that this has something to do with transform targets.

**Comment by brmbrmcar** [comment]
I made another one [here](https://drive.google.com/file/d/0BzQ95zbrEQrhM0FIb3Jsb0p5MW8/view?usp=sharing), but I have long lost the other level to computer powerwashes and resets.

**Comment by tobbi** [comment]
The interesting thing is that this issue only occurs for the large, hurting explosion. The small "pop" explosion is unaffected.

**Comment by Grumbel** [comment]
![untitled](https://user-images.githubusercontent.com/45727/44314196-fff03180-a415-11e8-9f6d-4dff1d6eb8f4.png)

Can anybody reproduce this issue? Seems to work fine for me.

**Comment by weluvgoatz** [comment]
A new explosion sprite was already added. Can this be closed @tobbi

**Comment by tobbi** [comment]
@weluvgoatz Does it rotate properly?

**Comment by weluvgoatz** [comment]
@tobbi The new explosion sprite seems to be very circular, so the explosion never appears strange, like it was once before.
