### ISSUE TITLE
Change the camera's anchorpoint to the center for scripts

### ISSUE THREAD

**Issue by Rusty-Box** [SuperTux/supertux#1209]
Have the camera use the center as an anchorpoint rather then the top left when using camera related scripts such as `Camera.scroll_to(x, y, t);` and `Camera.set_pos(x, y);`.

**Comment by Rusty-Box** [comment]
Maybe adding a section in the script where one can set an anchor point for the camera would be an idea, wouldn’t it @tobbi?

**Comment by tobbi** [comment]
This issue is with the commit above, I suppose.
