### ISSUE TITLE
Switches are... not switches???

### ISSUE THREAD

**Issue by weluvgoatz** [SuperTux/supertux#1218]
In-game, switches are not mentioned as switches, but instead as "Unknown Object"s.  Intentional? Most likely not.  Please fix.  This may be due to the switch not having a display name, and no one adding one for a long time.

**Comment by tobbi** [comment]
> Three swiss witch-bitches, which wished to be switched swiss
witch-bitches, wish to watch swiss Swatch watch switches. Which swiss witch-bitch which wishes to be a switched swiss witch-bitch, wishes to watch which swiss Swatch watch switch?
