### ISSUE TITLE
'To be continued.....' What do I do now?

### ISSUE THREAD

**Issue by Joe23232** [SuperTux/supertux#1222]
In the forest area, after doing `What is happening` level (which is just a short video), when I move down it shows `To be continued...` What do I do now?

**Comment by serano01** [comment]
Wait for the next release. The story will continue.

**Comment by Joe23232** [comment]
@serano01 I see. Would I be prompted for the update or do I have to manually reinstall the game to get the update?

**Comment by tobbi** [comment]
The latter. We do not currently have any way of informing users about updates. This will have to change eventually.

**Comment by Joe23232** [comment]
Ok thanks
