### ISSUE TITLE
Оutdated copyright year - 2018

### ISSUE THREAD

**Issue by adem4ik** [SuperTux/supertux#1223]
**SuperTux version:** SuperTux-v0.6.0-1019-gc78d73405-win32 (nightly build)
**System information:** *Windows 10*

##### Expected behavior
Copyright (c) 2003-2019 SuperTux Devel Team

##### Actual behavior
Copyright (c) 2003-2018 SuperTux Devel Team

##### Steps to reproduce actual behavior
- Start the game
- Read the bottom part of the screen

##### Additional debugging information
Source string: https://github.com/SuperTux/supertux/blob/master/src/supertux/title_screen.cpp#L43

**Comment by tobbi** [comment]
Thanks, I'll have to fix it.
