### ISSUE TITLE
Optimize/decrease PNGs sizes with OptiPNG

### ISSUE THREAD

**Issue by adem4ik** [SuperTux/supertux#1224]
ST uses PNG images a lot and there are tools for optimizing PNGs w/o losing any information. For example - http://optipng.sourceforge.net/ . I think that would be a good practice to start using such tools before the every release. It would provide smaller packages and installations.

Here is a result of using OptiPNG on `SuperTux\data\images` folder with `-o2` option (fast but efficient):
- Overall size before: 51.4 MiB
- Overall size after: 42.3 MiB
- Overall saving: ~9 MiB

Comparison of subfolder sizes in Double Commander:
![image](https://user-images.githubusercontent.com/4707112/69498391-103c6980-0f01-11ea-8713-1111607d0582.png)

Most noticeable comparison:
![image](https://user-images.githubusercontent.com/4707112/69498425-627d8a80-0f01-11ea-97ca-3c98164e9ad0.png)

It might be easier to try it on Linux, but here is how to use it on Windows:
- Download http://prdownloads.sourceforge.net/optipng/optipng-0.7.7-win32.zip?download
- Extract `optipng.exe` into `C:\Windows`
- Apply the following reg-file:
```
Windows Registry Editor Version 5.00
[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Folder\shell\OptiPNG]
@="Run OptiPNG on Folder"
[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Folder\shell\OptiPNG\command]
@="cmd.exe /c \"TITLE Running OptiPNG on %1 && FOR /r \"%1\" %%f IN (*.png) DO optipng.exe -o2 -strip all \"%%f\" \""
```
- Restart PC
- Run OptiPNG on folder by right mouse click menu and wait
- To remove the previous registry change apply the following:
```
Windows Registry Editor Version 5.00
[-HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Folder\shell\OptiPNG]
[-HKEY_LOCAL_MACHINE\SOFTWARE\Classes\Folder\shell\OptiPNG\command]
```

**Comment by tobbi** [comment]
I'm gonna use ImageOptim which will recompress the PNGs with a number of different algorithms so it can get the smallest possible filesize.

**Comment by Mathnerd314** [comment]
There's already a script to recompress them, using optipng and advpng: https://github.com/SuperTux/supertux/blob/32263950d315b0d7dbf1d70dedc8b7cd98cf57db/tools/png_recompress.sh

I think it would be a good idea to run it as a pre-commit hook, so that the Git history doesn't fill up with uncompressed versions.

**Comment by Grumbel** [comment]
You guys realize that this just makes the git repository bigger? If you want to optimize, optimize at build time.

**Comment by Alzter** [comment]
But why image compression? The images in SuperTux are pretty tiny as it is, wouldn't compressing some of the many large audio tracks be a better solution?

**Comment by Semphriss** [comment]
Closing this as it is a forever-issue; there will always be more data that'll need to be compressed, and it'll be too difficult to track every single contribution and enforce that they are optimal.

(It might be possible by adding a CI entry that runs OptiPNG and checks for changes, but it'd be very inconvenient for contributors anyways)

**Comment by Mathnerd314** [comment]
Maybe we could have a scheduled reminder, "compress every 6 months".

**Comment by mrkubax10** [comment]
Or just compress every release

**Comment by Mathnerd314** [comment]
ah yes, as the OP wrote
> I think that would be a good practice to start using such tools before the every release.

**Comment by Mathnerd314** [comment]
The logical place to put such a step would be a release checklist, but it seems we don't have a release checklist. So I opened #2117

**Comment by Semphriss** [comment]
Considerations before re-considering this issue (or opening another):
- The amount that can be saved with file optimisation (a few 10's of megabytes) is neglectable to the important increase in size of the repository file, as Grumbel mentioned.
- Optimisation can be done at build time, as Grumbel mentioned as well, to avoid cluttering the repo history. However, it might be notable that my 12-core CPU took at least half an hour to optimise all PNG's in the repository.
- Optimising all files (PNG's, audio, other) will require frequent checking as new files are added. Also, various programs might perform various optimisations, which will probably result in changing programs every once in a while.
- Enforcing optimisation with the CI would require contributor to use the very specific program the CI uses with the same settings, which is not always convenient, or even possible at all.

Most of all: All packaging methods (to my knowledge) already use compression algorithms. Manually compressing files on top of that would be redundant as well as inefficient.
