### ISSUE TITLE
Screen briefly turns dark and laggs in the world1/world2 transition

### ISSUE THREAD

**Issue by Wuzzy2** [SuperTux/supertux#1228]
**SuperTux version:** 0.6.1 beta 1
**System information:** GNU/Linux

##### Expected behavior
The transition between world1 and world2 (Story Mode) is smooth.

##### Actual behavior
If you go between world1 and world2, the transition is very visible. The screen briefly turns black and the game lags a bit. This is slightly irritating.

##### Steps to reproduce actual behavior
1. Go from world1 to world2 on the worldmap in Story Mode (or vice-versa)

**Comment by weluvgoatz** [comment]
This is possibly a lag issue, due to both worldmaps being large and hefty files in terms of worldmaps.

**Comment by Rusty-Box** [comment]
Possibly. If so I might have a solution that makes the lag unnoticeable.

**Comment by serano01** [comment]
Has been fixed with https://github.com/SuperTux/supertux/pull/1496, therefore I'm closing this.
