### ISSUE TITLE
Help block text might get cut off

### ISSUE THREAD

**Issue by Wuzzy2** [SuperTux/supertux#1229]
**SuperTux version:** 0.6.1 beta 1
**System information:** GNU/Linux

##### Expected behavior
All help block texts are fully visible on the screen.

##### Actual behavior
In the first Forest level, the help block text is not completely visible on my screen (1920×1080 fullscreen).

##### Workaround
When I press "scroll up", I can see the full text. But still, that's confusing!

##### Steps to reproduce actual behavior
1. Go to the first help block in the first Forest level
2. Activate it
3. Look at the text. Is it fully visible or cut off by the screen?

**Comment by Wuzzy2** [comment]
Also affects Ghoul's Lair.

**Comment by serano01** [comment]
> Also affects Ghoul's Lair.

In the meantime, I've fixed the issue regarding that level.
