### ISSUE TITLE
Coins are displayed in credits screen

### ISSUE THREAD

**Issue by Wuzzy2** [SuperTux/supertux#1230]
**SuperTux version:** 0.6.1 beta 1 (dev build)
**System information:** GNU/Linux

##### Expected behavior
Coins are not displayed in credits screen.

##### Actual behavior
Coins are displayed in credits screen.

##### Steps to reproduce actual behavior
1. Open the credits screen from the main menu

**Comment by Rusty-Box** [comment]
@weluvgoatz That one's for you

**Comment by Rusty-Box** [comment]
Fixed via f410ade7c316776cfbfc04a946102cee19ec508d
