### ISSUE TITLE
Can no longer use arrow keys to speed up credits screen

### ISSUE THREAD

**Issue by Wuzzy2** [SuperTux/supertux#1231]
**SuperTux version:** 0.6.1 beta 1
**System information:** GNU/Linux

##### Expected behavior
When you press up and down in the credits screen, you can scroll the credits.

##### Actual behavior
Can no longer use arrow keys to scroll in or speed up the credits. **This is a regression from 0.6.0!**

##### Steps to reproduce actual behavior
1. Open the credits screen
2. Press up or down

**Comment by Rusty-Box** [comment]
@weluvgoatz This one is for you too. ;)

**Comment by weluvgoatz** [comment]
This is not much of a priority, and also textscrollers as a whole are a bit broken (they don't accept key inputs) so whoever first implemented to textscroller item shall know how to fix it.
