### ISSUE TITLE
Cut scene bars don't extend all the way to screen border

### ISSUE THREAD

**Issue by Wuzzy2** [SuperTux/supertux#1233]
**SuperTux version:** 0.6.1 beta 1
**System information:** GNU/Linux

##### Expected behavior
The black "cut scene bars" are black all the way to the screen border.

##### Actual behavior
In the opening Icy Island cut scene (and other cutscenes), the black bar does at the bottom does not cover the bottom completely (the lowest 1 pixel is transparent). My resolution is 1920×1080 fullscreen.

##### Steps to reproduce actual behavior
1. Launch Icy Island cutscene (or any other)
2. Look very very closely at the bottom. Are the pixels black or not?

**Comment by Semphriss** [comment]
Couldn't reproduce a year later, I assume this has been fixed. Closing
