### ISSUE TITLE
Tux the Builder: Music restarts after using door

### ISSUE THREAD

**Issue by Wuzzy2** [SuperTux/supertux#1234]
**SuperTux version:** 0.6.1 beta 1
**System information:** GNU/Linux

##### Expected behavior
In the level Tux the Builder (Forest World), the music does not restart

##### Actual behavior
In the level Tux the Builder (Forest World), the music restarts after using a door, although it's the same track.

##### Steps to reproduce actual behavior
1. Play the said level
2. Use any door

**Comment by Rusty-Box** [comment]
This is due to an overlooked .ogg file in the level which has not yet been swapped with a .music file.
This is an easy fix.

**Comment by serano01** [comment]
Yes, it is. I've fixed it.
