### ISSUE TITLE
Can't walk over first bridge in Forest World

### ISSUE THREAD

**Issue by Wuzzy2** [SuperTux/supertux#1235]
**SuperTux version:** 0.6.1 beta 1
**System information:** GNU/Linux

##### Expected behavior
I can walk over the first bridge in Forest World.

##### Actual behavior
I can't. The bridge has disappeared.
**This is a serious regression from 0.6.0!** In 0.6.0, this bridge is crucial to accessing further levels. Without this bridge, I cannot proceed in Forest World.

The changelog for 0.6.1 beta 1 does not say that any levels were removed or became inaccessible.

##### Steps to reproduce actual behavior
1. Enter Forest World
2. Go to first bridge
3. Try to walk over it
4. Fail

**Comment by weluvgoatz** [comment]
Do you have any edited image or level file?  Because this can be causing
your issue.  Otherwise I assign @Rusty-Box to this. ;)

**Comment by Rusty-Box** [comment]
I wouldn't be suprised if someone messed with the ice_world.strf

**Comment by Rusty-Box** [comment]
Okay according to my inspection there is nothing wrong with the .stars nor the image file being missing. I now heard from a few that this is an issue but I can't get why it happens to some.

**Comment by weluvgoatz** [comment]
@Rusty-Box You were last person to touch that file

**Comment by Wuzzy2** [comment]
I have done this a 100% clean build, but not on a clean profile. I will try again on a clean profile soon(TM).

**Comment by Rusty-Box** [comment]
Oh yeah. I think someone else with the same issue also had it linked to an older profile.

**Comment by Wuzzy2** [comment]
I deleted my `config` file and then it worked! :-)

Closing.
