### ISSUE TITLE
Forest World worldmap has decidous trees which don't actually exist in the levels

### ISSUE THREAD

**Issue by Wuzzy2** [SuperTux/supertux#1237]
**SuperTux version:** 0.6.1 beta 1
**System information:** GNU/Linux

##### Expected behavior
The Forest World worldmap only has trees that you can also see in the levels.

##### Actual behavior
However, the Forest World worldmap has both coniferous and deciduous trees.

But in the levels we have only coniferous trees, both in foreground and background.

##### Steps to reproduce actual behavior
1. Enter Forest World world map
2. Look at the trees
3. Examine all Forest World levels
4. Look if you find ANY deciduous trees in the levels

##### Suggestion
Replace all deciduous trees on the worldmap with coniferous trees so the worldmap actually makes sense.

##### Future considerations
If you ever add levels in Forest World with deciduous trees (IF!!!), you can still update the worldmap afterwards. In this case, I'd add the deciduous trees in the worldmap only where they are actually match the levels, and not just randomly.

But personally, I like the levels as they are right now, with only coniferous trees. I don't see the need to add any deciduous trees tbh. The level style is good as-is.

**Comment by weluvgoatz** [comment]
The forest tileset is being reworked anyway, and it might include deciduous
trees.

**Comment by Rusty-Box** [comment]
That is not necessarily a bug but rather the result of the worldmap sprites being newer than the rest. The forest is awaiting a graphical overhaul in future updates but not this one. Not v0.6.1.
