### ISSUE TITLE
“Excellent!” voice can be heard in non-English locale

### ISSUE THREAD

**Issue by Wuzzy2** [SuperTux/supertux#1239]
**SuperTux version:** 0.6.1 beta 1
**System information:** GNU/Linux

##### Expected behavior
If you find a secret area and play not in English, a sound plays that is not in English.

##### Actual behavior
If you find a secret area and play not in English, you hear a voice saying “Excellent!”

##### Steps to reproduce actual behavior
1. Enable sound
2. Set language to non-English
3. Find a secret area

##### Suggestion
If you play in non-English language, instead of playing the “Excellent!” voice, play a different, more generic sound effect. Maybe one of the funny Tux sounds from the Icy Island intro could be re-used. But maybe a different sound effect is better.

**Comment by Zwatotem** [comment]
This is the second I finally found out, what it actually says.

**Comment by weluvgoatz** [comment]
> In hedgewars they are all talking english...

Why must it matter in SuperTux, then? 🤔

**Comment by huftis** [comment]
I think it would be better if the same sound was used for **all** languages. I actually don’t think the ‘Excellent’ fits very well in the game in the first place. Why not just have neutral ‘success’ sound, e.g. a ‘tada’, fanfare or applause? For example, something similar to one of these:

https://freesound.org/people/FunWithSound/sounds/456966/
https://freesound.org/people/MattiaGiovanetti/sounds/477153/
https://freesound.org/people/fabian_lm/sounds/436437/
https://freesound.org/people/Scrampunk/sounds/344696/
https://freesound.org/people/mickleness/sounds/269198/

**Comment by Wuzzy2** [comment]
Yeah, a sound effect instead of a voice would be good idea, too.

**Comment by vpzomtrrfrt** [comment]
Just played the game, and I agree the clip is a strange sound

**Comment by cooljeanius** [comment]
as a long-time SuperTux player the "Excellent!" sound effect is kind of nostalgic for me and so I'm kind of attached to it, but I guess if other languages wanted to switch it up for their locale that'd be ok

**Comment by serano01** [comment]
Inspired by "Yeti's Revenge", it now plays a clapping sound when a secret area is found. Therefore I'm closing this, since it's now obsolete.
