### ISSUE TITLE
Ice in the Hole level has a sneaky big deadly ice crusher

### ISSUE THREAD

**Issue by Wuzzy2** [SuperTux/supertux#1240]
**SuperTux version:** 0.6.1 beta 1
**System information:** GNU/Linux

##### Expected behavior
In Ice in The Hole (Icy Island), you get warned about the big ice crusher.

##### Actual behavior
In Ice in The Hole (Icy Island), you do not get warned. Instead, there's a up arrow sign that even lures you right below the ice crusher, which you will see when it's already too late.
The reason is the ice crusher is *just* out of view. At least for me.

##### Steps to reproduce actual behavior
1. Be a n00b
2. Play this level the 1st time
3. Get lured by the sign into the deathtrap
4. Die

##### Discussion
I see the need for the up arrow sign. It's because players might overlook this critical area.
But a warning sign is missing.
Therefore, this will lure players right into the danger zone.

BUT! It is debatable if this nasty trick is intentional or not. This I don't know. Note that this is not about me, it's about what I think how other players will experience the level. Note this issue is obviously opinionated, YMMV.

But I argue that this level is on the first world, so I think it would be more fair to be a little bit more easy on the player.
If the level would have been on Forest World, I would probably not have opened this issue.

Therefore, I suggest to add a warning sign before the big ice crusher. But if you think this level is fine as-is, I will totally accept this.

**Comment by tobbi** [comment]
@Rusty-Box I kinda think the warning would not be too verbose, so it might make sense to add one. What do you think?

**Comment by Rami-Slicer** [comment]
The ice crusher is actually very easy to find, especially if you make use of "peek up"

**Comment by Guih48** [comment]
How i can place theese big ice crushers in my level?

**Comment by Zwatotem** [comment]
> How i can place theese big ice crushers in my level?

You place a normal crusher, and then right click it and change it's sprite to krosh.sprite

**Comment by Alasdairbugs** [comment]
"peek" features should not be *required* to play the game as they are quite obscure. signs before off-screen ice crushers should always be the ! sign

**Comment by Rami-Slicer** [comment]
Introducing peek features somewhere in the "tutorial" levels would be a good idea anyways IMO. Warning signs would still be a good idea.

**Comment by tobbi** [comment]
Closing because Ice in the hole is completely remade in recent master.
