### ISSUE TITLE
Explosions affect magic color blocks

### ISSUE THREAD

**Issue by Wuzzy2** [SuperTux/supertux#1241]
**SuperTux version:** 0.6.1 beta 1
**System information:** GNU/Linux

##### Expected behavior
Explosion don't affect magic color blocks.

##### Actual behavior
Explosions activate all magic color blocks and turn them into the solid state briefly.

##### Steps to reproduce actual behavior
1. Blow up a bomb near some magic color blocks

**Comment by HybridDog** [comment]
The fire cloud caused by the explosion lights up its surroundings, and the magic blocks react to light. I think that this is a feature and not a bug.

**Comment by tobbi** [comment]
We've discussed this issue internally, and basically agree with HybridDog that this is not a bug, but rather a feature.
