### ISSUE TITLE
Update Transifex

### ISSUE THREAD

**Issue by Wuzzy2** [SuperTux/supertux#1244]
**SuperTux version:** 0.6.1 beta1
**System information:** N/A

##### Expected behavior
Transifex source strings are up-to-date.

##### Actual behavior
It isn't. Missing are e.g. strings from `menu-principale` and `world2` and probably other resources as well.

Some user worlds are also missing completely (not sure if intentional).

Please make sure all resources on Transifex are up-to-date so that we can actually a 100% translated game for next release.

##### Evidence
Check if the string “Confirm aborting level” exists there. This string exists in the game as “tooltip” of the second-to-last checkbox in the options dialog.

**Comment by Rusty-Box** [comment]
That will be too difficult to achieve until release since it basically depends on the community helping out with translating.

**Comment by Wuzzy2** [comment]
Isn't “updating locale files” and “alert translators” part of the normal release process?

**Comment by Rusty-Box** [comment]
People that are being alerted then would also have to translate and if they don’t, they don’t.

**Comment by Wuzzy2** [comment]
I believe you totally don't understand what I mean. I am NOT talking about the *actual* translations being updated, I talk about the *translation templates* *not* being updated on Transifex.

The whole issue is ONLY about source strings. There is a mismatch between source strings on Transifex and source strings in … well … the source code.

Again: Isn't it normal to update the source strings on Transife?

Or is it actually intentional that translators on Transifex will work on outdated source strings?

**Comment by adem4ik** [comment]
Let me join the conversation:
- Russian is fully translated on Transifex 10 days ago.
- Recently there was a sync of GitHub with Transifex.
- After that v0.6.1-beta.2 was released.

So now I'm on v0.6.1-beta.2 with Russian enabled, and there are some untranslated strings. Seems like they are not presented on Transifex, and I as a translator can't do anything about it:
- Localization update pack, Various
![image](https://user-images.githubusercontent.com/4707112/70212633-175d4600-1751-11ea-8246-d515fc4e9e95.png)
- Confirm aborting level
![image](https://user-images.githubusercontent.com/4707112/70212866-89358f80-1751-11ea-8452-c86e2ac8453f.png)
- Automatically pause the game when the window loses focus
![image](https://user-images.githubusercontent.com/4707112/70213024-dd407400-1751-11ea-89cc-f3d41409943e.png)
- Choose world
![image](https://user-images.githubusercontent.com/4707112/70213636-3eb51280-1753-11ea-95fe-1cf5ecbd0385.png)
- Create world
![image](https://user-images.githubusercontent.com/4707112/70213656-4b396b00-1753-11ea-9c44-6e03927fe5b0.png)
- New world
![image](https://user-images.githubusercontent.com/4707112/70213680-5f7d6800-1753-11ea-81f2-2293fd6c4582.png)
- Tiles
![image](https://user-images.githubusercontent.com/4707112/70213914-e3375480-1753-11ea-988a-3958c24c358a.png)

It is just an example, I believe there can be more of such strings. Seems like the whole template presented on Transifex doesn't have all strings for translation.

**Comment by adem4ik** [comment]
Transifex project was updated recently, some of missing strings were added. But still there are some untranslated strings like: `Confirm aborting level` & `Automatically pause the game when the window loses focus`

**Comment by Semphriss** [comment]
Closing this as this is a forever-issue (translations are packaged before each release). Issues about missing translations should warrant individual issues for each release.
