### ISSUE TITLE
Ghost tree on world map has wrong depth sorting

### ISSUE THREAD

**Issue by Wuzzy2** [SuperTux/supertux#1245]
**SuperTux version:** 0.6.1 beta 1
**System information:** GNU/Linux

##### Expected behavior
The ghost tree in the world map renders after the tree above.

##### Actual behavior
The ghost tree in the world map renders before the tree above.

##### Steps to reproduce actual behavior
1. Go to forest world map
2. Mark the ghost tree level as unfinished
3. Look at the ghost tree animation, especially the top branches. They render below the tree above, which looks very wrong.

**Comment by serano01** [comment]
Fixed as well.
