### ISSUE TITLE
Invisible blocks can be "felt" from the side

### ISSUE THREAD

**Issue by divVerent** [SuperTux/supertux#1247]
**SuperTux version:**
0.6.0

**System information:**
Debian Buster running in ChromeOS's "Crostini" container. 

##### Expected behavior
Invisible blocks cannot be detected other than by activating them.

##### Actual behavior
Touching invisible blocks only at the corner moves Tux to the side without activating the block (very intentional behavior for solid blocks to make their corners feel "round" and to make it easier to jump into one tile gaps). Can be used to "feel out" the location of invisible blocks without causing them to activate.

##### Steps to reproduce actual behavior
In attached level1.stl, jump from the spawnpoint to one of the trampolines and hold the jump button. Tux will not just fly straight upwards, but also move towards the center of the platform, until Tux activates two invisible blocks at the top.

##### Additional debugging information
level1.stl attached to quickly reproduce the issue. Screenshot of level attached too so you can see the construction exhibiting the issue best.

[level1.stl.gz](https://github.com/SuperTux/supertux/files/3899327/level1.stl.gz)
![Screenshot 2019-11-27 at 8 04 21 PM](https://user-images.githubusercontent.com/251568/69769236-fcd40d00-1151-11ea-9163-d634f62b5e11.png)

**Comment by divVerent** [comment]
Confirmed: from above or from the side, not-yet-activated invisible blocks are nonsolid, as they should be.

**Comment by Semphriss** [comment]
This is fixed now; I believe it was the same issue that allowed portable blocks to "bounce" on moving coins. (Can,t find the issue number but there's a report here on GitHub)
