### ISSUE TITLE
Bonus Island II: Clouds disappear too fast

### ISSUE THREAD

**Issue by Wuzzy2** [SuperTux/supertux#1253]
**SuperTux version:** 0.6.1 beta 1
**System information:** GNU/Linux. Screen resolution = 1920×1080

##### Expected behavior
The background clouds don't disappear.

##### Actual behavior
In Bonus Island II, there are a few levels with moving clouds in the background.

However, as soon one of these clouds reaches the left or right border of the screen (with some offset), it visibly disappears *before* it is completely gone from the screen. This looks ugly.

This bug occurs in the official version of Bonus Island II, the NON-add-on version.
In 0.6.0, when Bonus Island II was still an addon, this bug did not occur.

##### Steps to reproduce actual behavior
Play in the official (!) Bonus Island II any of the following levels:

* Mario's Supposed to Deal with This ...
* Cliff Jumping
* You have 1 Minute
* Water Ways
* fjerd
* Blind to the World
* A Path Through the Clouds
* Luft Airship

And look at the clouds in the background for a while.

**Comment by weluvgoatz** [comment]
Bonus Island II was never an addon.... or at least is wasn't an addon in
0.6.0.

**Comment by Wuzzy2** [comment]
Looks like I got confused. Anyway. Is this issue valid?

**Comment by Wuzzy2** [comment]
OK, this issue actually is not specific to Bonus Island II at all. I have reproduced it with any other level that have moving background clouds, including official Story Mode levels.

**Comment by HybridDog** [comment]
I can confirm this. The left cloud (highlighted in screenshots) disappears too early:
![fot_2020-01-26-10:29:26_400053360](https://user-images.githubusercontent.com/3192173/73133299-029d8000-4027-11ea-9229-84fd8ebfbb94.jpg)
![fot_2020-01-26-10:29:27_612483950](https://user-images.githubusercontent.com/3192173/73133300-03361680-4027-11ea-8f1a-074d30c50cbb.jpg)

**Comment by busybody42** [comment]
oops, the scrolling render distance broke...
