### ISSUE TITLE
Nolok's Castle in worldmap doesn't display level records properly

### ISSUE THREAD

**Issue by Wuzzy2** [SuperTux/supertux#1256]
**SuperTux version:** 0.6.1 beta 1
**System information:** GNU/Linux

##### Expected behavior
After you finished Nolok's Castle on Icy Island, and walk on the level on the worldmap, the correct level stats are shown.

##### Actual behavior
When you stand on the level in the worldmap, the coins, badguys and secrets level records are all set to 0/0, which is incorrect. This level has plenty of coins and badguys. Only the 0 secrets are correct.

##### Steps to reproduce actual behavior
1. Complete Nolok's Castle
2. Walk on the level on the worldmap

**Comment by AndetSTK** [comment]
The same seems to be true for The Tower of Ghosts.

**Comment by mrkubax10** [comment]
Fixed by #2012
