### ISSUE TITLE
0/1 enemies defeated in Ghosttree's Challenges

### ISSUE THREAD

**Issue by Wuzzy2** [SuperTux/supertux#1258]
**SuperTux version:** 0.6.1 beta 1
**System information:** GNU/Linux

##### Expected behavior
If you win Ghosttree's Challenges, the level stats on the worldmap displays 1/1 defeated enemies.

##### Actual behavior
Worldmap shows 0/1 defeated enemies.

##### Steps to reproduce actual behavior
1. Play Ghosttree's Challenges in the Forest World and win

**Comment by Rusty-Box** [comment]
This issue stems from the placeholding design choice of the boss fight. In this level you don't defeat the tree you just push a button which simply ends the level without really having beaten the tree itself.
Basically, this might not even get fixed as there isn't a reason to fix it. It doesn't break the game, its just the result of a temporary solution for a boss that is not fully ingame yet.

**Comment by weluvgoatz** [comment]
Can it be closed?

**Comment by Rusty-Box** [comment]
> Can it be closed?

I would say so.

**Comment by Rusty-Box** [comment]
I'll close this as this issue is linked to a poor design choice rather than an actual bug of the game.
