### ISSUE TITLE
Allowing Tux to crawl when ducking

### ISSUE THREAD

**Issue by Rusty-Box** [SuperTux/supertux#1259]
Tux does get hurt when trying to standup under a narrow, one block high celing and instead of simply removing this, it would be a nice solution to allow Tux to crawl when pressing left and right while in a ducking position.

Note: This of course requires additional graphics!

**Comment by LizzyBach** [comment]
But, I do think that the damage thing should be removed. Yeah, I know that it makes more sense for Tux to take damage but, I always find it to be really annoying and unnecessary. Please try to remove it. In my opinion, this should make the game much better and fun to play.

**Comment by Guih48** [comment]
I think this is removes small-tux-only gates from the game, so this isn't good. I think there can used a special area block (like climbable), that in big tux becomes temponary small (and it use small tux's graphics, but recolored (black pieces becomes big-tux-grey))

**Comment by mrkubax10** [comment]
You can go through such gates by jumping anyway.

**Comment by Rusty-Box** [comment]
This has been addressed and added with #2284. Closing this.
