### ISSUE TITLE
Infinite purple bomb growl if you run away very fast from it

### ISSUE THREAD

**Issue by Wuzzy2** [SuperTux/supertux#1260]
**SuperTux version:** 0.6.1 beta 1
**System information:** 

##### Expected behavior
If you activate a purple bomb, it growls. If you run away very fast from it (so that it is out of view before it explodes), the growl should no longer be hearable.

##### Actual behavior
If you activate a purple bomb, it growls. If you now run very fast away from it (so that it is out of view before it explodes), the growl will continue to play forever.

##### Steps to reproduce actual behavior
1. Turn on sound
2. Play a relatively flat level with a purple bomb in it
3. Jump on the purple bomb to activate it
4. Run as fast as you can to the right to get out of view before the purple bomb explodes

**Comment by slackstone** [comment]
I don't have a fix, but it's kind of a funny bug and doesn't seem like it's going to wreck somebody's day. I'm not closing because I can't personally fix this one. I'll be on the lookout, I want  to try this now :-)

**Comment by busybody42** [comment]
I guess that... maybe we can have it's sound fade out the farther it is offscreen...
