### ISSUE TITLE
Bad background ambient in Lost Village

### ISSUE THREAD

**Issue by Wuzzy2** [SuperTux/supertux#1263]
**SuperTux version:** 0.6.1 beta 1
**System information:** GNU/Linux

##### Expected behavior
The background ambient of Lost Village (ghost forest) is nice to hear and not buggy.

##### Actual behavior
The following problems exist in the Lost Village level:

* The rain background noise in the first part of the level sounds really bad. It sounds very artificial, as if the sound file has been heavily compressed
* When you die in the first part and respawn, the rain background noise is gone. There is no background noise/music at all until you proceed to the next part or you exit to the worldmap

##### Steps to reproduce actual behavior
1. Play Lost Village level

**Comment by Semphriss** [comment]
The whole ghost forest world will be remade, there are complaints about it fusing from everywhere :laughing: 

I'll close this issue as it has 9 chances out of 9 to end up forgotten about, but rest assured that we have this problem - along with many, many others - in mind.
