### ISSUE TITLE
No audio

### ISSUE THREAD

**Issue by weluvgoatz** [SuperTux/supertux#1266]
SuperTux no longer plays audio. I tested on other versions, and they all have audio.  But the nightly build, does not.  And yes, the sound and music settings are on and set to 100%.

**Comment by Rusty-Box** [comment]
Which nightly build did you use while experiencing this?

**Comment by weluvgoatz** [comment]
This is the latest one.

**Comment by tobbi** [comment]
What operating system?

**Comment by weluvgoatz** [comment]
Windows 10.

**Comment by tobbi** [comment]
Can you check whether SuperTux is not muted in the sound settings? Also, can you upload your settings file here?

**Comment by weluvgoatz** [comment]
This issue seems to only occur in 64 bit builds and not 32 bit ones.  Therefore, reopening.
