### ISSUE TITLE
Delete those key placeholders

### ISSUE THREAD

**Issue by Zwatotem** [SuperTux/supertux#1267]
**SuperTux version:** 0.6.x

##### Expected behavior
Forest world levels don't have key placeholders, since there's no key collection in current forest world.
##### Actual behavior
Forest levels have key placeholders in upper left corner
##### Steps to reproduce actual behavior
Play _any_ world2 level. Empty places for NOLOK keys will appear in upper-left corner of a level.

**Comment by weluvgoatz** [comment]
In order to fix this, I assume all that must be done is remove the file: "data/levels/world2/default.nut"

Whoever fixes this, should probably do that.

**Comment by tobbi** [comment]
@SuperTux/level-designers
