### ISSUE TITLE
Level Intro Should Show Relevant Tux Animation

### ISSUE THREAD

**Issue by Karkus476** [SuperTux/supertux#127]
When you start any level, the Tux animation "small-walk-right" is shown. It would be nice if this animation could be replaced with the walk right animation for the current bonus that Tux has. For example, if you start the level as Fire Tux, the "fire-walk-right" animation should display.
-Karkus

**Comment by Karkus476** [comment]
For clarification, I am talking about the level intro (where the level creator and best statistics are shown).

**Comment by Karkus476** [comment]
I've made a fix for this on my fork, how should I go about submitting my changes?

**Comment by maxteufel** [comment]
[Open a pull request.](https://help.github.com/articles/using-pull-requests/)
