### ISSUE TITLE
Graphics glitch for narrow levels

### ISSUE THREAD

**Issue by Wuzzy2** [SuperTux/supertux#1270]
**SuperTux version:** 0.6.0 beta 2
**System information:** GNU/Linux

##### Expected behavior
If you play a narrow level (a level that has a low overall width), the left and right level bounds are black or rendered in some other way that indicates that its out of level bounds.

##### Actual behavior
There's a weird graphical glitch at the left and right level bounds.

Evidence: Level “Flower Bonus” from Bonus Island III:

https://satoshiupload.com/images/1TScduq6Zw.png

##### Steps to reproduce actual behavior
Play with a wide screen resolution a level with a low level width.
I recommend playing a couple of levels in Bonus Island III, which has a couple of narrow levels where this can be seen.

Affected Bonus Island III levels:

* The Toilette Zone
* Flower Bonus
* Deep, deeper …
* … the deepest
* (possibly other levels)

**Comment by weluvgoatz** [comment]
You've already made this bug report (#1250). Why did you make a duplicate?

**Comment by Wuzzy2** [comment]
Because I'm stupid. :D
Lol, when I posted this, I actually believed I posted it before, but could not find it. That was probably because I looked in the addons repository. So yeah, stooooopiiiddddd. :D

Anyway, I closed #1250 now because this issue (#1270) is more detailed.

**Comment by slackstone** [comment]
Well at leat you clearly stated which levels to look at. Thanks for that info.

**Comment by busybody42** [comment]
ummm... this is a beta version of 0.6.0

**Comment by busybody42** [comment]
invalid, but it also seems to be because the level width or height is too small...

**Comment by Wuzzy2** [comment]
Issue is still reproducible in 0.6.1.

**Comment by Zwatotem** [comment]
How do we want it to be solved?
1. Resize existing levels, so that they fit every screen width.
2. Reprogram level displaying, to have black stripes at either end of screen.
3. Both.
4. Modulo mode 🙂 (optional for level, specified in the editor)

**Comment by Wuzzy2** [comment]
I prefer black stripes (2), as this is an universal solution.

**Comment by busybody42** [comment]
It also occurs in 0.6.0... Hence t he confusion...
I prefer to take an extra (3rd) option...
this time, a 5th option...
We do none of the 4 things listed, and we instead make the camera zoom in to fit the level, without showing ANYTHING outside the level size...
