### ISSUE TITLE
Can't fix some translations for bonus islands

### ISSUE THREAD

**Issue by Wuzzy2** [SuperTux/supertux#1272]
**SuperTux version:** 0.6.0 beta 2
**System information:** N/A

## The problem
This is translation-related.

I want to fix some German translations for the bonus islands but Transifex doesn't let me. So can someone look into this and figure out why I can't update these strings? I can translate most strings fine and Transifex accepts my changes, but there are *some* strings for which Transifex rejects ANY updates.

## List of bad translations

Here's a list of wrong translation. I always write it in this format:

```
Current bad translation
Proposed fixed translation
```

NOTE: There is one translation which contains a bad character which the font doesn't support.

### `bonus-1`

```
Thompson's Reich verlassen
Thompsons Reich verlassen
```

### `bonus-2`

```
Neues Versteck gefunden! 
Du hast ein Versteck gefunden!
```

```
Nach Hause teleportieren…
Nach Hause teleportieren …
```

### `bonus-3`

These contain a broken character which the font doesn't support (n-dash), so the character needs to be replaced.

```
Regnen oder nicht regnen – Das ist hier die Frage
Regnen oder nicht regnen - Das ist hier die Frage
```

```
Regnen oder nicht regnen – Das ist hier die Frage (Antarktisch)
Regnen oder nicht regnen - Das ist hier die Frage (Antarktisch)
```

**Comment by adem4ik** [comment]
If the string was reviewed by Reviewer/Coordinator, not a single translator can edit it anymore.
![image](https://user-images.githubusercontent.com/4707112/70389173-41269f00-19d5-11ea-8739-4ecd8c2c0f99.png)

If you want to edit them, you should get Reviewer permissions for this project at least. That's how it works on Transifex.

**Comment by Wuzzy2** [comment]
Sadly, I can only access Transifex indirectly with a script, so this is not an option. I don't even know if I have reviewer status. Probably not.

Another solution would be if someone else could do these changes for me because I'm not allowed.

FYI: I translated a couple of games, but the biggest workload so far is me translating the lion's share of Cataclysm: Dark Days Ahead, a game with an enormous amount of strings. Ask the C:DDA devs if you don't trust me.

In case the strings I mentioned above are already fixed, consider this issue done.

**Comment by adem4ik** [comment]
There is no reviewers in German team atm: https://www.transifex.com/arctic-games/teams/95/de/ And you're just a regular translator.
![image](https://user-images.githubusercontent.com/4707112/70399472-bc23a000-1a3d-11ea-8ad9-9e73bd629e10.png)

You should contact devs and ask them to make you Reviewer of German language if you think you're good enough. I usually do such via Transifex PMs. But since you don't have direct access to Transifex site, there should be another way. Mb some of devs will notice this thread on GitHub...

**Comment by Wuzzy2** [comment]
As a German native speaker who translated lots of FOSS games in the past, I probably think I'm good enough.

It's strange there are no reviewers. Then how come some strings have been locked down? I thought only reviewers can do this. o_O

**Comment by adem4ik** [comment]
Probably by coordinators, they can review strings too.

**Comment by Wuzzy2** [comment]
Oh right, I totally forgot!

**Comment by busybody42** [comment]
google translate?
I mean, it's not a bad idea!

**Comment by Wuzzy2** [comment]
Status report: All strings are fixed except this one:

```
Nach Hause teleportieren…
Nach Hause teleportieren …
```

Basically just a missing space. It's minor.

**Comment by busybody42** [comment]
It's probably just an error with the letters we have for the game fonts...
We should probably add more characters to the fonts we use...

**Comment by tobbi** [comment]
Seems fixed on Transifex as well... Everything good now?

**Comment by Wuzzy2** [comment]
No. The string in my previous post is unchanged. It's for `bonus-2`. Just add a space before the “…”, then it will be fixed.

@busybody42: This has NOTHING to do with fonts. You completely misunderstand this issue. Also, I verified that all characters that I use do exist in the font, don't worry.

**Comment by busybody42** [comment]
oh... sorry...
Translation is not really my strong suit...
...But I do (kinda) have a guess why this happens...
...I'm guessing it's because of the missing space...
...It ends up getting confused, and won't translate correctly...
...I'm thinking it mistakes the "..." for an actual word... which causes the translation errors...

**Comment by tobbi** [comment]
I added the missing space in the translation.
