### ISSUE TITLE
Credits opens pause menu when losing focus

### ISSUE THREAD

**Issue by Wuzzy2** [SuperTux/supertux#1273]
**SuperTux version:** 0.6.1 beta 2
**System information:** GNU/Linux

##### Expected behavior
No pause menu when losing focus while playing credits.

##### Actual behavior
When you play the credits, then the window loses focus, and then you return, the pause menu opens.
What's weird is the title of the pause menu. The pause menu is titled “vfeb79x98f”.
o_O

##### Steps to reproduce actual behavior
* Start credits
* Lose window focus
* Return to window

**Comment by weluvgoatz** [comment]
The title of that title screen is there, because it represents the token that the level uses in order to function properly.
