### ISSUE TITLE
Double Jump for Airflower

### ISSUE THREAD

**Issue by weluvgoatz** [SuperTux/supertux#1274]
Tux should be able to double jump, if he is collected a certain amount of air-flowers.  This would be a nice idea, and I have already made a code-test of it.

**Comment by Ordoviz** [comment]
I’m against this. It’s unintuitive that a propeller helmet gives you this power. Besides, the air flower already lets you jump very high. And adding a powerup store (#473) requires dropping the powerup stacking feature anyway.

**Comment by Rusty-Box** [comment]
@Ordoviz 1) No one limits us to change the visuals and mechanics of the air powerup to make more sense and 2) regarding the store: I am personally already against the whole stacking gimmick of the powerups in supertux so dropping that I’d be in favor with.

**Comment by Alzter** [comment]
Maybe instead it could just be changing the hover ability. Currently the hover lacks any sort of visual feedback, that being particles and animations, and is only noticeable by how Tux slows down in air. I think it would be cool to re-think the hover ability to be more interesting.

**Comment by Alasdairbugs** [comment]
Bad idea. The hover ability makes more sense, tux wears a hat that keeps him in the air for longer. He also already gains a ton of jump height, plus, he also gains even more height from springs. The glide ability is much more useful for manipulating jumps, landing on places, and once you get good at the glide ability, its very fun.

A double jump ability would be much more boring. I've played this game for 10 years and this is probably the most boring change to a powerup you can add.

**Comment by Zwatotem** [comment]
The majority is against. Should I close and remove from 0.7.0 milestone? @weluvgoatz

**Comment by weluvgoatz** [comment]
Now that I look back on it, even I am against it, so yes I will close it.
