### ISSUE TITLE
Rocks retain velocity after leaving something that moved them

### ISSUE THREAD

**Issue by weluvgoatz** [SuperTux/supertux#1276]
I am using a custom build, but the code for the rocks remains the same.  I implemented a conveyor belt feature that moves rocks around the level, but the rocks keep the same velocity, even after they left the conveyor belt.  Maybe this should be fixed...?  I know this doesn't currently affect anything currently in the game but it would be great to fix this for future features (like a conveyor belt ;))

**Comment by Semphriss** [comment]
Fixed a while ago, I don't remember when (open a new issue if not fully fixed)
