### ISSUE TITLE
Game crash when hitting left world border while holding ice cube

### ISSUE THREAD

**Issue by Wer-Wolf** [SuperTux/supertux#1277]
SuperTux version: v0.6.0
System information: Windows 10 1909 64 bit

Expected behavior: 
In 23rd Airborne (and any other level), when holding an inactive ice cube as small tux and hitting left world border, nothing special should happen.

Actual behavior:
Game crashes :-(

Steps to reproduce actual behavior:
When entering 23rd Airborne (or any other level), "deactivate" the first ice cube and collect them as small tux.
Then hit left world border --> crash.

Additional debugging information:

Using official binary for Windows 64 bit.

**Comment by Wer-Wolf** [comment]
Edit: Also happens when using Linux (MX Linux 19, Kernel 4.19)

**Comment by Wer-Wolf** [comment]
Error message: supertux2: /build/supertux-Uwn74d/supertux-0.6.0/src/object/player.cpp:922: void Player::position_grabbed_object(): Assertion `moving_boject` failed.

**Comment by Zwatotem** [comment]
This problem will be solved in next release 0.6.1, which comes soon.
Duplicate #1058, fixed by #1176

**Comment by tobbi** [comment]
Closing as per https://github.com/SuperTux/supertux/issues/1277#issuecomment-565810617 

We just released 0.6.1. Please check it once it's built.
