### ISSUE TITLE
Linux AppImage: Arabic is broken in 0.6.1

### ISSUE THREAD

**Issue by Fahad-Alsaidi** [SuperTux/supertux#1279]
I don't know what's happening sine #1045 was fixed. Today, I tested 0.6.1 and it is broken see the screen shot.
![supertux6-1](https://user-images.githubusercontent.com/1632566/70908401-83c72780-2024-11ea-85e4-f9b079e47ada.png)

**Comment by tobbi** [comment]
Okay, so this is on OS X:
https://prnt.sc/qbofws

I assume this still looks good, right?

Let me look through the Windows builds.

**Comment by tobbi** [comment]
Windows screenshot using Wine:
https://prnt.sc/qboh3z

Looks the same as the one above, so I assume that that's good as well.

**Comment by tobbi** [comment]
@Fahad-Alsaidi How did you install your build?

**Comment by Fahad-Alsaidi** [comment]
@tobbi I am using  SuperTux_2-v0.6.1.glibc2.14-x86_64.AppImage.

**Comment by tobbi** [comment]
This:

While trying to build libraqm:
```
ecking for FREETYPE... yes

checking for HARFBUZZ... no

configure: error: Package requirements ( harfbuzz >= 1.7.2) were not met:
```

**Comment by tobbi** [comment]
@Fahad-Alsaidi Please try this https://supertux-ci-downloads.s3-us-west-2.amazonaws.com/c520670cfde8c8805f565fd74a06333b6ff6e35a/travis/linux/268725430/SuperTux_2-v0.6.1-7-gc520670.glibc2.27-x86_64.AppImage

**Comment by Fahad-Alsaidi** [comment]
> @Fahad-Alsaidi Please try this https://supertux-ci-downloads.s3-us-west-2.amazonaws.com/c520670cfde8c8805f565fd74a06333b6ff6e35a/travis/linux/268725430/SuperTux_2-v0.6.1-7-gc520670.glibc2.27-x86_64.AppImage

It works correctly... Thanks

**Comment by tobbi** [comment]
I've pushed 0.6.1.1 with this fixed.

**Comment by tobbi** [comment]
Closing.
