### ISSUE TITLE
Level Editor: Autotile

### ISSUE THREAD

**Issue by weluvgoatz** [SuperTux/supertux#1281]
It would be nice to have autotile in the level editor.  For those who don't know, this means that placing a tile will automatically adjust its sprite so it looks proper and avoids tile errors.  This also means that level builders won't have to go through their structures and clean up edges, as it would automatically adjust.  Tux Builder implements this already, so ask @Alzter if you're still stuck.  Feel free to discuss autotile here.

**Comment by Rusty-Box** [comment]
I am personally not in favor of this idea. To me, it limits certain design techniques as you have no control over how the tiles will be displayed.
For example: If you want or need a sharp edge or cutoff for a transition of tiles without having to add a separate tilemap it is just simply impossible.

The only alternative I see myself agree with is having autotiling be a separate tile-placing tool, like the default placing, filling bucket etc.

**Comment by weluvgoatz** [comment]
This is why it would be available as a setting or tool...

**Comment by LizzyBach** [comment]
I'm in favor of this idea. It'll be a cool edition but please, make it available as a separate option.

**Comment by Zwatotem** [comment]
Closed by #1519.
