### ISSUE TITLE
Controls no longer settable

### ISSUE THREAD

**Issue by weluvgoatz** [SuperTux/supertux#1282]
**SuperTux version:** 0.6.1
**System information:** *(details about your kernel, operating system, or distribution)* Windows 10, 64-bit

##### Expected behavior

You can change your controls and expect them to save between playing sessions.

##### Actual behavior

They don't save.  After exiting and reentering the game, your controls have been reverted to the original ones.

##### Steps to reproduce actual behavior

1) Change some control settings
2) Exit SuperTux
3) Reenter
4) The controls are the original ones

##### Additional debugging information
This likely was introduced in one of the latest commits that was about controls and player defined keys, but I can't find it....

**Comment by HybridDog** [comment]
Saving the controls works for me on Linux.
https://github.com/SuperTux/supertux/pull/1070#issue-257164290
However, I still do not know why my control settings were reset one time (only one time) after I have applied that PR.

**Comment by busybody42** [comment]
This also applies to 0.6.0 as well! This oddity has persisted for over a year! 

... we really should get this fixed...

**Comment by HybridDog** [comment]
It may need to be fixed in `src/control/keyboard_config.cpp`.

I'm not sure if iterating over a std::map and changing it at the same time works reliably:
https://github.com/SuperTux/supertux/blob/f31276d3d6a4d4ce2d593d750190197e3bb2a4e3/src/control/keyboard_config.cpp#L91-L103

**Comment by christ2go** [comment]
That should not be a problem since the iterator is first incremented and then the element is deleted. It could even be shortened into ´´m_keymap.erase(I++);´´ (c.f. https://stackoverflow.com/questions/8234779/how-to-remove-from-a-map-while-iterating-it <https://stackoverflow.com/questions/8234779/how-to-remove-from-a-map-while-iterating-it>).

**Comment by Zwatotem** [comment]
I am now on 0.6.1 and keys are being permanently saved for me. Can we close this, or does anyone still have a problem with this?

**Comment by Semphriss** [comment]
@weluvgoatz Can you check whether this is still the case? I'll close the issue if it isn't.

**Comment by Semphriss** [comment]
This is reported to no longer be the case, closing.

Please **open a new issue** if this is still the case.
