### ISSUE TITLE
cant start game 

### ISSUE THREAD

**Issue by samson510** [SuperTux/supertux#1283]
cant open game after last update version 0.6.1-1 i running arch full updated  and when start game with terminal  get this output  before everything work great until i updated game 
> [samson@archPC ~]$ supertux2
terminate called after throwing an instance of 'std::runtime_error'
  what():  locale::facet::_S_create_c_locale name not valid
Aborted (core dumped)

**Comment by tobbi** [comment]
https://github.com/SuperTux/supertux/issues/1157

**Comment by tobbi** [comment]
Please follow the issue above and see whether it helps.

**Comment by samson510** [comment]
after trying dont work still   i was install from default repository not flatpak

**Comment by tobbi** [comment]
Can you pastebin your locale.conf file in /etc/locale.conf ?

**Comment by samson510** [comment]
here is 

> [samson@archPC ~]$ cat /etc/locale.conf
LANG=en_US.UTF-8

**Comment by tobbi** [comment]
So I take it you re-ran `locale-gen` ?

**Comment by samson510** [comment]
when re run that command i get this output  nothing change  in  `` /etc/locale.conf ``
 
> [samson@archPC ~]$ sudo locale-gen
[sudo] password for samson: 
Generating locales...
  en_US.UTF-8... done
  en_US.ISO-8859-1... done
  hr_HR.UTF-8... done
  hr_HR.ISO-8859-2... done
Generation complete.
[samson@archPC ~]$ cat /etc/locale.conf
LANG=en_US.UTF-8

**Comment by tobbi** [comment]
Try this: https://github.com/potree/PotreeConverter/issues/281#issuecomment-335471817

**Comment by samson510** [comment]
not work neither i found solution kinda   in my regional settings need to set on US  instead Bosnian  now just need to use to it for English months and days in my calendar  instead my language

**Comment by tobbi** [comment]
Okay, at least you've found a workaround. I feel like this is an OS bug / problem, so if you could check with the people from arch, that would be good.
