### ISSUE TITLE
Ghost Tower level is unplayably slow

### ISSUE THREAD

**Issue by Wuzzy2** [SuperTux/supertux#1284]
**SuperTux version:** 0.6.1
**System information:**

GNU/Linux
OpenGL version string: 3.0 Mesa 19.2.6
OpenGL core profile version string: 4.5 (Core Profile) Mesa 19.2.6
Graphics card: Haswell-ULT Integrated Graphics Controller

##### Expected behavior
Ghost Tower level is playable.

##### Actual behavior
It's unplayable. It's very very slow (less than 5 FPS).

##### Steps to reproduce actual behavior
1. Start Ghost Tower level in Story Mode

To me it happens with both renderers (both `sdl` and `opengl`).

##### Related issue

I already reported this here in a comment:

https://github.com/SuperTux/supertux/issues/1051

But I figured this might have been overlooked, so I post this again, but this time, as a separate issue. Also, it's not clear to me whether these two issues are actually the same or not.

**Comment by tobbi** [comment]
The culprit here is the Lava tilemap at z-index -1. With that removed, everything is fine.
