### ISSUE TITLE
IceBlocks behave buggy when the player presses down

### ISSUE THREAD

**Issue by Ordoviz** [SuperTux/supertux#1285]
**SuperTux version:** 0.6.1
**System information:** Arch Linux 5.4.5-arch1-1

##### Expected behavior
Tux throws IceBlocks in the direction he is facing.

##### Actual behavior
When pressing down, Tux throws IceBlocks to the right. If he was facing left, he will take damage. If the IceBlock slides into a wall, it will stick to it.

**Comment by HybridDog** [comment]
It also happens to me.

**Comment by weluvgoatz** [comment]
This has been fixed.
