### ISSUE TITLE
Remove thorns in “Find the Bigger Fish!“

### ISSUE THREAD

**Issue by Ordoviz** [SuperTux/supertux#1286]
**SuperTux version:** 0.6.1

![fuck-thorns](https://user-images.githubusercontent.com/37733333/71271043-f4cf4d80-234a-11ea-92fb-76516191047c.png)

When I saw the ?-Blocks, I immediately hit them and collected the shiny fireflowers on top of them in a rush. I didn’t pay any attention to the disguised thorns at the top left corner which resulted in big frustration since I lost my power-up for burning the hay bales. I felt cheated by the level. Please remove those nasty thorns.

**Comment by tobbi** [comment]
@SuperTux/level-designers Thoughts?

**Comment by serano01** [comment]
I thought they had some sort of purpose, e. g. if you're small Tux with no power-up, you can "escape your fate".

**Comment by enigma9o7** [comment]
you have to burn your way out so being small doesn't help.

But lotsa things in the game are like that, you learn and do better the next time.

**Comment by serano01** [comment]
I removed them in the meantime, since they had no real purpose.
