### ISSUE TITLE
Save “Show controller” option in config file

### ISSUE THREAD

**Issue by Ordoviz** [SuperTux/supertux#1289]
Currently, if you activate this option in the developer mode, it gets reset when you close the game. Besides, you shouldn’t need to activate developer mode to use this feature as it’s very useful for speedrunners. Therefore, I suggest making this option settable in the options menu or – if you don’t like that – make it at least settable in the config file.

**Comment by tobbi** [comment]
I'll leave this open as a good first issue. If anyone wants to work on this, please ping @tobbi and I'll get you up to speed!

**Comment by shawnanastasio** [comment]
Hi @tobbi, I've submitted a PR that implements this. Comments would be appreciated!

**Comment by tobbi** [comment]
Fixed! Thanks!
