### ISSUE TITLE
Problems With Slippery Terrain

### ISSUE THREAD

**Issue by Karkus476** [SuperTux/supertux#129]
I have found a few issues concerning the icy/slippery terrain (e.g. at the very start of Arctic Ruins):
1. Tux's legs move as if walking even when you aren't pressing any buttons (As a result of his movement)
2. You cannot jump properly off the icy terrain
3. If you run onto the ice then jump off into another (not icy) platform, then the ice effect persists

Some of them may not be bugs but I just wanted to put them up for discussion at least

Thank you!
Karkus

**Comment by Karkus476** [comment]
Note to self:
See Player::apply_friction()
https://github.com/SuperTux/supertux/blob/master/src/object/player.cpp#L512
more specifically Line 518

**Comment by tobbi** [comment]
I'm pretty reluctant to change these game mechanics, mainly because many levels depend on the slippery terrain to work exactly as described.

**Comment by Karkus476** [comment]
I cant disagree with that.
