### ISSUE TITLE
No bridge in forest after bouncy coils level

### ISSUE THREAD

**Issue by tuxandrews** [SuperTux/supertux#1290]
Hello,after when i made update of the game,bridge in the forest is dissapeared.Storymode.
![forest bug](https://user-images.githubusercontent.com/59146366/71325616-06a22380-24f8-11ea-862b-3ef2ed94e421.jpg)

**Comment by Ordoviz** [comment]
Strange. The bridge exists for me. Do you have a `worldmap.stwm` in `$SUPERTUX2_USER_DIR/levels/world2/`? If yes, try renaming it `worldmap.stwm.bak`. Just to make sure you have no files overwriting the standard worldmap.

**Comment by tobbi** [comment]
I am able to reproduce the issue, I just don't know why it happens. My worldmap.stwm file is the same as in git so I don't think that's the reason.

**Comment by tobbi** [comment]
I was able to fix it by using different tiles. I still have no idea why it happens.

**Comment by busybody42** [comment]
Let's just make another level where the bridge is broken and you have to cross the floating wreckage (and other ground) to get to the other side! There, easy fix!

**Comment by tobbi** [comment]
The issue happens because a custom tiles.strf file installed through an add-on has the ability to override the user installation. Fixing this is not as trivial as I'd originally thought.

**Comment by Sirix1995** [comment]
I just downloaded the release 0.6.1 of supertux, and I got the same issue. I can't go back to Icy island ! :(

**Comment by tobbi** [comment]
@Sirix1995 Disable all add-ons, and then try again!

**Comment by Morality-debugger** [comment]
I tried disabling the add-ons and it fixed the issue for me. Thanks for the tip 💯

**Comment by kollerfuzzi** [comment]
It appears to be "Treasure Mountain" by "Daniel" which causes the bridge to break. All other addons had no impact.
