### ISSUE TITLE
Set Level Message

### ISSUE THREAD

**Issue by weluvgoatz** [SuperTux/supertux#1291]
Level builders should be able to set a message at the beginning of the level (on the black screen where the title, author and stats are displayed) similar to Pingus, and it would appear right above or below Tux's feet.  Feel free to discuss here :-)  Of course, this would be optional, in order to not break other levels.

**Comment by Ordoviz** [comment]
I usually immediately skip the black screen. What kind of messages had you in mind? Something like “Watch out for falling stalactites!” or “This level contains 4 crystals. Can you find them all?”?

**Comment by busybody42** [comment]
Not a bad idea!

**Comment by tobbi** [comment]
Sorry, but this broke our CI, due to -Werror

**Comment by tobbi** [comment]
Oh, the PR that is.
