### ISSUE TITLE
Revert to the 1-up counter for players

### ISSUE THREAD

**Issue by Rusty-Box** [SuperTux/supertux#1293]
This might become a controversial idea but:

Instead of having the complicated coin math, percentage mumbo jumbo, the game should revert back to the 1-up counter for players. However, incase the idea of adding shops still is being consitered for the future the coin counter should not be limited to only 100 coins.

Depending over the game's overall difficulty every 100 coins can reward the player with an extra 1-up besides the Tux doll (i.e. if the game would end up too easy it would only make things worse... but I assume that is not the case here).

**Comment by weluvgoatz** [comment]
I am strongly against this idea.  A one-up counter seems like it will make
the game more complicated than it already is.  Also, the 1-up counter is
one of the things that confused me the most about 0.1.3, because it was
unclear what would happen when the 1-up counter reached zero.  In my
opinion, it will be better if the coin deduction "mumbo jumbo" is just
removed, because I still like collecting coins for the sake of having
something collectible and countable.

**Comment by weluvgoatz** [comment]
Also, weren't 1-ups directly related to the lives system, which is
something that was considered a rejected feature forever?

**Comment by Rusty-Box** [comment]
> Also, weren't 1-ups directly related to the lives system, which is something that was considered a rejected feature forever?
Possibly, I don't know. Most likely I wasn't around at that time so I'm unaware of that statement if that's true.
> A one-up counter seems like it will make the game more complicated than it already is.
Is it really? 2 lifes -> You die -> 1 life left etc.?

**Comment by weluvgoatz** [comment]
But what about when the lives counter reaches zero?

**Comment by Rusty-Box** [comment]
> In my opinion, it will be better if the coin deduction "mumbo jumbo" is just removed, because I still like collecting coins for the sake of having something collectible and countable.

So no lifes, no coins related to checkpoint restarts? A bit too easy isn't it? ATleast for my taste.

> But what about when the lives counter reaches zero?

Game Over? Like... in every other game that uses this mechanic? You will replay the level again from the very beginning. Like already handled when you have no coins or less then 25, I believe.

**Comment by Rusty-Box** [comment]
Maybe get kickout back to the world map first so you need to re enter the level first.

**Comment by weluvgoatz** [comment]
Well "Game Over" doesn't work well in my opinion because 1) It sounds like
you must restart the game if you run out of lives, which is misleading and
2) Having to restart from just the beginning of a level is a bit tame if
you must have a "Game Over" and "Lives" screen.

**Comment by weluvgoatz** [comment]
And if the "Game Over" penalty works exactly how the coin deduction
currently works, then what's the point of readding that penalty to begin
with?

**Comment by Rusty-Box** [comment]
We could go for a more "extreme" approch which would be: Game Over = Restard an entire world.
But in general the lifes main prupose would be to allow you to restart after dying from a checkpoint instead of the very beginning so it is somewhat punishing. (like the coin count right now, but imo it is too vague and made unnecessarily complicated).

That's how it goes in many jump 'n' runs/platformers.

**Comment by Rusty-Box** [comment]
Why use random 25 coins as a limit for a checkpoint restart if it is more easily communicated to a player that they cannot go below 1 life when wanting to restart from a checkpoint.

**Comment by Rusty-Box** [comment]
I just noticed that right now coins don't even get reduced upon dying which makes them not even work as a life count alternative right now.

**Comment by Ordoviz** [comment]
IMHO Tux should always respawn at checkpoints but dying should cost 10% of your coins. The coins can then used for something different like a shop.

> So no lifes, no coins related to checkpoint restarts? A bit too easy isn't it? Atleast for my taste.

No, the difficulty should arise from the platforming. Farming lives or coins is not difficult, just time-investing.

> That's how it goes in many jump 'n' runs/platformers.

That's how it goes in many **old** jump 'n' runs/platformers. Celeste is a great example for a very hard modern platformer. I has permanent checkpoints after every room but the rooms themselves are really hard. For the ultimate challenge you can try getting golden straw berries though that you get when you complete a level without dying.

The golden strawberry equivalent of SuperTux is to max out all stats for a level and get a flashing level dot.

Related: #556

**Comment by Rusty-Box** [comment]
@Ordoviz Not a bad argument. Going for a modern approach might actually be more beneficial. But maybe have Tux only loose the coins he gathered before a next checkpoint or level goal has been reached to make it a bit more fair. Like in Celeste, the strawberry collectibles are saved once you landed safely. You don’t loose them again after dying unless you die during the process of getting it.

**Comment by Zwatotem** [comment]
So you suggest coin counter state to be saved and permanent checkpoint on every bell? I feel then it dethrones a level form the role of basic division of the game, that one needs to be able to walk through at once (or with only few mistakes) to proceed. I would like to have some form of warranty, that level was played smoothly, not tryharded, before the next one can be started.

Also for the coins: Leaving them as currency you can only earn, not spend makes little sense. If we leave them with no way to be lost, they should remain as one-time collectibles, to encourage players to get them all.

**Comment by Rusty-Box** [comment]
> Also for the coins: Leaving them as currency you can only earn, not spend makes little sense. If we leave them with no way to be lost, they should remain as one-time collectibles, to encourage players to get them all.

There is the idea for an item shop (like a toad house) where coins can be spend on powerups or other goods like tips on the locations of secret exits (a feature that is considered for v0.7)

**Comment by HybridDog** [comment]
We could add a number next to the coins number which shows how many times Tux can die and respawn at the checkpoint without collecting coins between the deaths. Calculating this number mentally is too difficult I think (enthusiastic players may remember the coin thresholds up to 10 deaths by hard).

If we want to use coins for a shop and do not like that coins disappear when dying, we could save the lost coins as another number. The shop could offer goods for which the player has to pay regular and lost coins.

**Comment by Alzter** [comment]
The checkpoint coin deduction idea is stupid in my opinion. It's literally just lives but more complicated, and you need to pull out a calculator to check how many you have left. As for replacing coin deduction with a lives counter, I don't know. Reverting to lives _would_ make things a lot simpler but maybe we should just get rid of limited continues altogether, as after all lives are a bit of an archaic concept and having the player get punished for dying too much on a hard level and lose their checkpoint doesn't sound very fun, and some hard levels like the Grandmaster Journey already compensate for lives by giving you 100 coins at every checkpoint.

**Comment by busybody42** [comment]
NO... I think lives make it more like a generic mario clone... and that's boring... and that's terrible!
Stick to coins! Maybe, we could have a mechanic, where dying without being able to pay for a respawn at a checkpoint will make you respawn at the PREVIOUS checkpoint hit, and forgetting about the one you just hit... so you'll lose progress, if you can't afford a respawn, but not ALL progress!

**Comment by busybody42** [comment]
also, using the item shop is risk and reward
Do you risk getting a new powerup safely, but guarantee the loss of coins, and making it more likely to run out of coins for the next checkpoint? Or do you try to find the same powerup in a previous level, and risk losing it before the end, or dying and losing coins anyways?
It's your choice.

**Comment by Alzter** [comment]
@busybody42 That just sounds even MORE confusing and complicated, and most story levels only have one checkpoint to begin with.

Tweaking random game mechanics just for the sake of "not being a Mario clone" with no true benefit to the gameplay doesn't improve anything, and I think the coin deduction only complicates the lives system to nobody's benefit. At least revert it to lives.

**Comment by busybody42** [comment]
Lives were pointless... you should know if you played milestone 1 before to the end... (stupid milestone 1 Miyamoto Monument, however that's spelled)
At least make the coins useful for more than lives, if they're added...

**Comment by busybody42** [comment]
... I just thought that there were more levels that had multiple checkpoints... :/
It's not like that lives really mattered anyways... coins were a better idea, because that adds a unique flair to the game... If there's no uniqueness, then what's the point of playing this other a true mario game? Or, furthermore, secret maryo chronicles? It was a stupid limit that only served to make it harder, and it frusturated me to the point where I almost just gave up on the game. (This game's lucky that milestone 1 was so great for it's time!) Yes, coins didn't really benefit much, but lives benefited us even less. If the player get's too infuriated, then what's stopping them from rage quitting? Visibility is already a problem, but ragequitters? They'll just say that the game is (censored) and garbage and that there's no point in playing it... and then even LESS people will know or care about this game, and it'll probably go extinct and cease development if nobody cares anymore... if we readd lives, then all of those factors will come in fruition again... ;(
We can't add lives, or we'll be forgotten and left in the dust... and in many MANY years, when people remember this game, if that happens... will there even be any point in playing anymore?
(Note: I just gave myself a bit of sadness from typing this... let's hope this doesn't happen in reality...)

**Comment by busybody42** [comment]
Umm... crap... this is what slackstone said about my 2 suggestions: 1337 and 1338, if those are correct; they say (SUGGESTION) in the title:
"I'm not sure suggestions in the issue queue are appropriate. Please use this space for reporting actual bugs and issue related communications. Remember Super Tux is a community driven open source game. Folks have limited time. The ST engine is really good, there's scripting and all kinds of examples. Use the force, study it and then make it do what you want."

**Comment by Alzter** [comment]
> At least make the coins useful for more than lives, if they're added...

I say we remove the coin deduction and instead make a powerup shop in the worldmap that lets you buy powerups for the coins you earn. (Maybe even add some new powerups so we can get a bit more than just the existing four?)

**Comment by busybody42** [comment]
(Like this one: A hard hat that lets tux use a hammer, and a cape (based off of revenge in redmond supertux) that lets him use a spin attack)

**Comment by Alzter** [comment]
> ...A hard hat that lets tux use a hammer

> ...generic mario clone... and that's boring... and that's terrible!

So you're okay with copying Mario ideas (Super Hammer from SMM2) but not game mechanics (lives counter) that are much less specific to just Mario? Confusing. Anyway bringing back the Redmond cape sounds cool, but maybe it could do more than just a SMW like spin attack. Ideas anyone?

**Comment by Ordoviz** [comment]
If anyone has an idea for a new powerup, he or she should post on the forum. This issue is about choosing between

- a coin system (status quo),
- a live system, and
- always respawning

**Comment by HybridDog** [comment]
```lua
#!/usr/bin/env luajit

local function count_lives(coins)
	if coins < 25 then
		return 0
	end
	coins = coins - math.max(math.floor(coins / 10), 25);
	return 1 + count_lives(coins)
end

local t = {{0, 0}}
local lives = 0
for coins = 1,100000 do
	local l = count_lives(coins)
	if l > lives then
		lives = l
		t[#t+1] = {coins, lives}
	end
end

for i = 1,#t-1 do
	local coins_min = t[i][1]
	local coins_max = t[i+1][1]-1
	local lives = t[i][2]
	print(coins_min .. " - " .. coins_max .. " | " .. lives)
end
```

coins range | respawns
-----|----
0 - 24 | 0
25 - 49 | 1
50 - 74 | 2
75 - 99 | 3
100 - 124 | 4
125 - 149 | 5
150 - 174 | 6
175 - 199 | 7
200 - 224 | 8
225 - 249 | 9
250 - 276 | 10
277 - 306 | 11
307 - 340 | 12
341 - 377 | 13
378 - 418 | 14
419 - 464 | 15
465 - 515 | 16
516 - 572 | 17
573 - 635 | 18
636 - 705 | 19
706 - 783 | 20
784 - 870 | 21
871 - 966 | 22
967 - 1073 | 23
1074 - 1192 | 24
1193 - 1324 | 25
1325 - 1471 | 26
1472 - 1634 | 27
1635 - 1815 | 28
1816 - 2016 | 29
2017 - 2240 | 30
2241 - 2488 | 31
2489 - 2764 | 32
2765 - 3071 | 33
3072 - 3412 | 34
3413 - 3791 | 35
3792 - 4212 | 36
4213 - 4680 | 37
4681 - 5200 | 38
5201 - 5777 | 39
5778 - 6418 | 40
6419 - 7131 | 41
7132 - 7923 | 42
7924 - 8803 | 43
8804 - 9781 | 44
9782 - 10867 | 45
10868 - 12074 | 46
12075 - 13415 | 47
13416 - 14905 | 48
14906 - 16561 | 49
16562 - 18401 | 50
18402 - 20445 | 51
20446 - 22716 | 52
22717 - 25240 | 53
25241 - 28044 | 54
28045 - 31160 | 55
31161 - 34622 | 56
34623 - 38468 | 57
38469 - 42742 | 58
42743 - 47491 | 59
47492 - 52767 | 60
52768 - 58630 | 61
58631 - 65144 | 62
65145 - 72382 | 63
72383 - 80424 | 64
80425 - 89360 | 65
89361 - 99288 | 66

**Comment by busybody42** [comment]
gasp

**Comment by Rusty-Box** [comment]
It has been decided again the concept of lives as well as removing the link between coins and checkpoint respawning. See #1410
