### ISSUE TITLE
unexpected character control

### ISSUE THREAD

**Issue by kompowiec** [SuperTux/supertux#1299]
**SuperTux version:** 0.6.0
**System information:** *(details about your kernel, operating system, or distribution)* Sabayon linux but IMO doesn't matter here.

##### Expected behavior
you should be able to climb the ladder with Mr. IceBlock
##### Actual behavior
https://gfycat.com/pooramplearabianwildcat
##### Steps to reproduce actual behavior
as above

**Comment by serano01** [comment]
Should Tux really be able to hold something and climb a ladder in the same time?

**Comment by HybridDog** [comment]
> you should be able to climb the ladder with Mr. IceBlock

I disagree. Tux does not have fingers; I have fingers and even I cannot climb a ladder and hold something big and heavy with both hands at the same time.

**Comment by kompowiec** [comment]
well you can take something big and heavy under the arm but it's a matter of optics. 

Anyway, if no one is interested in this enhancement, i close.
