### ISSUE TITLE
Rainy levels are slow with opengl renderer

### ISSUE THREAD

**Issue by HybridDog** [SuperTux/supertux#1301]
**SuperTux version:** 0.6.1
**System information:** Lubuntu 18.04, intel gpu, 1920x1080 screen

##### Expected behavior

Rainy levels are not laggy

##### Actual behavior

In rainy levels (e.g. the Shocking level in the Forest world), I often get less than 30 FPS. If I decrease the window resolution, I get more FPS.
This does not happen with the opengl20 or sdl renderer. 

I've tried to find out why rain reduces the framerate.
I changed the code so that the raindrops do not move. When the drops are drawn on the screen I have low FPS, and when I walked right so that the drops are not drawn, the framerate increases significantly.

##### Steps to reproduce actual behavior

Play the Shocking level.

**Comment by HybridDog** [comment]
I've disabled raindrop collisions and rainsplashes, and set the new x position to always the same value.
I still get about only 41 FPS.
![rain](https://user-images.githubusercontent.com/3192173/71767252-840f6000-2f0a-11ea-85ea-7541a1513af7.jpg)
code changes: https://pastebin.com/raw/MLMntkYk

**Comment by busybody42** [comment]
... I recommend that you try disabling all addons that you can, except for whatever one you're using, then reboot the game...
That seems to stop lag, apparently...

**Comment by HybridDog** [comment]
> ... I recommend that you try disabling all addons that you can, except for whatever one you're using, then reboot the game...
That seems to stop lag, apparently...

I've temporarily renamed the addons folder in ~/.local/share/supertux2/ to disable all addons; it hasn't stopped the lag.

**Comment by Semphriss** [comment]
@HybridDog Can you please confirm that this is still an issue? I doubt the situation has improved, but I might get to work on it if it still happens.

**Comment by HybridDog** [comment]
Yes, I still get a low frame rate in these levels.

**Comment by HybridDog** [comment]
When I play the Going Underground level, I get 38 FPS with the `opengl` renderer and 86 FPS with `opengl20`. In both cases I disabled vsync and enable redundant frame rendering.

**Comment by tobbi** [comment]
@HybridDog Can you see whether the commit I pushed improves anything?

**Comment by tobbi** [comment]
I did not notice any more slowdowns recently. I'm therefore gonna close this.

**Comment by HybridDog** [comment]
I could no longer reproduce this since I've switched to a newer operating system.
