### ISSUE TITLE
Expose enemies to scripting

### ISSUE THREAD

**Issue by weluvgoatz** [SuperTux/supertux#1320]
Enemies in SuperTux should be scriptable.  They already support namespaces, so they could use that.  Scripting for enemies would also be super fun and useful.  

Here's a list of scripts I want for enemies:

kill(type) - This would kill the enemy, either by killfalling it or by burning it.

set_sprite() - This would change the enemy's sprite to a new sprite.

set_action() - This would change the enemy's sprite action.

Please consider, thanks!

**Comment by tobbi** [comment]
Duplicate of #366
