### ISSUE TITLE
Make rocks more dynamic

### ISSUE THREAD

**Issue by weluvgoatz** [SuperTux/supertux#1321]
This issue suggests 2 new rock features:
1)  Rocks can bounce off trampolines.
2) Rocks can set off pushbuttons.

This might need discussion, but these are my ideas.

**Comment by Ordoviz** [comment]
I strongly support increasing the interactivity of items in SuperTux. In Super Mario, coins for instance can be collected, can be temporally turned into destructible blocks with a P-Switch and fall when a POW-block explodes. When everything can interact with each other, the amount of ways a level designer can use the items increases exponentially with each newly added item. (The amount of glitches increases exponentially aswell).

**Comment by Zwatotem** [comment]
You can assign me to this. (I'm not sure, if non-members can be assigned though)

**Comment by busybody42** [comment]
Like having an ice block that acts like a rock? ( a rock that can be kicked like mr ice block, but then becomes ridable) SURE!

**Comment by busybody42** [comment]
also, let's add rocks that break and act like projectiles! (in case you want to make a boss fight like the big boo from super mario world)
