### ISSUE TITLE
Better organize grey castle tiles

### ISSUE THREAD

**Issue by Alzter** [SuperTux/supertux#1322]
Currently the old "grey" castle tiles reside in multiple image files, I think it'd be nice to organize them into one.
![image](https://user-images.githubusercontent.com/22513909/72782146-26ec0c00-3c77-11ea-8540-029bcb004b64.png)

**Comment by serano01** [comment]
Additionally, I personally never use them, because it's hard to figure out what's supposed to be the edge, the wall, the inner block etc.

**Comment by Rusty-Box** [comment]
> Additionally, I personally never use them, because it's hard to figure out what's supposed to be the edge, the wall, the inner block etc.

@serano01 White bricks = top edge, dark bricks = bottom edge, the rest is just the middle grey tone :)

**Comment by Alzter** [comment]
The edges are hard to make out and I'm not sure they're even listed in the level editor in the convex shape.
