### ISSUE TITLE
incorrect full screen resolution is set also to x environment after exit

### ISSUE THREAD

**Issue by e3k** [SuperTux/supertux#1326]
**SuperTux version: 0.6.0-1**
**System information:debian buster stable**

##### Expected behavior
if i set a wrong resolution it should not affect the resolution in X

##### Actual behavior
if i set a wrong resolution it is taken also to X after exiting supertux

##### Steps to reproduce actual behavior
Example: you have a 1280x1024 monitor.
1. set the resolution of the game to 640x480 for fullscreen
2. turn on full screen
3. restart the game
4. exit the game

##### Guidelines for reporting issues

- [no i did just do a search on github ] I have read <https://github.com/SuperTux/supertux/blob/master/CONTRIBUTING.md#bug-reports>.
- [yes i tried that on github ] I verified this isn't an issue that's already been reported.
- [x] This report only includes details about **one** (1) issue, feature request or topic.
- [x] If I make a mistake while submitting this report I will use the edit feature instead of closing this issue and opening a new one.
- [x] This issue is **not** about wrong translations (use Transifex for those), or anything unsupported (e.g. third-party add-ons).
- [?] Once you're done, please remove the section 'Guidelines for reporting issues', the 'Additional debugging information' if it is empty, and any text in *italic font*.

**Comment by slackstone** [comment]
I feel like as long as I've played with SuperTux, this has always been a behavior you can reproduce. I know exactly the issue described. I've seen it many times over many  ST versions running on various Linux based systems.  

Running SuperTux at the wrong resolution so you can break/crash X windows when you exit is a potential feature. Mr.Tree and his bad guy friends use this trick all the time. (I think they are responsible for this issue.)

**Comment by e3k** [comment]
a bonus problem happens when you set half of the resolution + set the zoom at 50%. Then supertux seems to run in correct resolution but once you quit it your desktop resolution is wrong.

it took me ages to figure out what happened after my son did this setting.

**Comment by slackstone** [comment]
We all like a good bonus but what the .. ? 
"set half of the resolution + set the zoom at 50%. " 

I'm glad we have this captured in the notes. It's know that on Linux systems your can do strange resolution moves. There are a lot of variables involved so your mileage may vary. At the end of the day, try to get your resolution set properly.

If this is a critical issue where you can't get a valid resolution to work, then I may be able to help debug things further. Otherwise I'm going to close for now.

(By the way, Your kid sounds smart. Go SuperTux.)

**Comment by e3k** [comment]
well it would be nice to have that supertux would first aquire the system resolution and on exit it would set it back. it is not critical for me and i can set the correct resolution myself. but my 5 years old browses the menus instead of playing sometimes and tends to brake things as it is too early for him to understand what native resolution means.
