### ISSUE TITLE
Addons on fourms don't show up on contrib levels... and sometimes on the enable/download/disable addons menu.

### ISSUE THREAD

**Issue by busybody42** [SuperTux/supertux#1330]
**SuperTux version: 0.6.0 (apparently the repository downloaded the wrong version)**
**System information: raspbian os, Cana Kit computer...**
##### Expected behavior
The addons from the fourms (aside from divTrolololo) would work normally when put in addon folder.
##### Actual behavior
The addons from the fourms, except for divTrolololo, don't show up in the contrib levels screen... after adding in a missing file, they do appear on the download/enable/disable addons menu on the title screen, but they still do not appear in the contrib levels menu, not even if they're enabled...
Also, Forest Adventure World doesn't show up in contrib levels either, but does in the download addons menu.
##### Steps to reproduce actual behavior
just... put any fourms addon (except divtrolololo, which works like intended, and mattie's beta world, which acts like matties world in the editor) into the game's addon folder...
downloading forest adventure world also has the same error, for some reason.
##### Additional debugging information
N/A

**Comment by busybody42** [comment]
**EDIT:** Welp, it turns out that tux strikes back ALSO doesn't work right!

**Comment by slackstone** [comment]
So if I understand correctly, the older ST code may have looked at the forms but now it looks at the addon repository on Github. An older build of SuperTux was used in this case. We may still have some addon bugs but this is probably not related at the moment, It should be safe to close.

**Comment by busybody42** [comment]
agreed. let's hope this works soon, and let's hope we make the addons work, even if they're not in the repository...
