### ISSUE TITLE
Repository has wrong version...

### ISSUE THREAD

**Issue by busybody42** [SuperTux/supertux#1332]
**System information: Cana kit raspberry pi, Raspbian os**

##### Expected behavior
the command "sudo apt install supertux --fix-missing" command would download 0.6.1 or 0.6.1.1 when ran in the terminal
##### Actual behavior
It downloaded version 0.6.**0** instead... and it doesn't say it has to/ can be updated...
##### Steps to reproduce actual behavior
go to the terminal
type the following in the terminal and then run the command:
sudo apt install supertux --fix-missing

**Comment by busybody42** [comment]
sorry. not bug apparently.

**Comment by slackstone** [comment]
Just a note, OS provider that package SuperTux often don't have the latest code. Sometime you have to download and install the latest version manually if you want new and shinny Super Tux.
