### ISSUE TITLE
(SUGGESTION) Add rewards for meeting level goals

### ISSUE THREAD

**Issue by busybody42** [SuperTux/supertux#1334]
Add rewards for meeting the target time, target score, (from https://github.com/SuperTux/supertux/issues/1333 if it's added) all enemies killed, and all coins collected, in a single level...
Only for the first time those requirements are met, (if target time and score were even enabled) you would get some extra coins and maybe even lives, if those are added. (I wish they aren't)
...I mean, it's probably a bit better than a glowing worldmap dot to brag about...

**Comment by slackstone** [comment]
I'm not sure suggestions in the issue queue are appropriate.  Please use this space for reporting actual bugs and issue related communications.  Remember Super Tux is a community driven open source game. Folks have limited time. The ST engine is really good, there's scripting and all kinds of examples. Use the force, study it and then make it do what you want. 

This ticket will now serve the purpose of being the first use of the all new Super Tux slogan  for 2020 ..." Quality Grade Side Scroll Fun " TM 2020 Mr.Tree

**Comment by busybody42** [comment]
Aww... sorry...
