### ISSUE TITLE
Where's the lightning?

### ISSUE THREAD

**Issue by plonibarploni** [SuperTux/supertux#1336]
**SuperTux version:** Latest git master

##### Expected behavior
Lightning makes the water deadly, killing/hurting Tux and any badguys in the water.

##### Actual behavior
Instead of the bright flash of lightning, the water temporarily disappears, and nothing happens to objects in the water.

##### Steps to reproduce actual behavior
Play the Shocking level and wait a few seconds for the lightning.

**Comment by tobbi** [comment]
Can you disable all your add-ons, then restart SuperTux and then see if the issue is fixed?

**Comment by plonibarploni** [comment]
Yes, disabling all add-ons fixes the issue.

**Comment by busybody42** [comment]
first the bridge, and now the lightning? What is going on?

**Comment by busybody42** [comment]
Why does this even happen? 
Is it because of THAT type of lag?

**Comment by busybody42** [comment]
I think there may be too much lag going on at once... we may need to fix it soon...

**Comment by plonibarploni** [comment]
I can no longer reproduce this issue, even with add-ons enabled.
