### ISSUE TITLE
What's wrong with background?

### ISSUE THREAD

**Issue by soviet-man** [SuperTux/supertux#1338]
![изображение](https://user-images.githubusercontent.com/33825590/74068777-900ca700-4a0d-11ea-8a1d-1dd2e78d93b2.png)

**Comment by busybody42** [comment]
...Wrong place... post that on the DISCORD, not here!
This is for the actual game!
That's just an addon!
Can somebody please close this?
...however, I AM going to tell sugar about this... (they DID make this addon's sprites, after all...)
...But I'll do it on the DISCORD...

**Comment by slackstone** [comment]
**Missing tiles.** 
The pink image glitches are missing/incomplete tiles or unsupported levels using improper assets.

The add-on in question here is under very active development at the moment. 2020 is a big year enjoy. Be sure to refresh your Add Ons daily for the latest updates and fixes. (plug - > Forest World Adventure Pack : -)

**Comment by slackstone** [comment]
Yo. And thanks for playing.

**Comment by soviet-man** [comment]
This is from stody mode. Not from addon.
