### ISSUE TITLE
Allow level authors to define behaviour for custom game objects

### ISSUE THREAD

**Issue by tobbi** [SuperTux/supertux#134]
It would be great if level authors could for example say: "This object behaves like a bonus block" and gets rendered properly with all the animations in place or something similar.

**Comment by Karkus476** [comment]
As a feature of the editor?

**Comment by tobbi** [comment]
This needs to be implemented in both the editor and the game itself. However, the editor is lower priority because level authors can edit their level by hand to do the required settings.

**Comment by mahboi** [comment]
@tobbi Do you mean as in setting an object's sprite and type separately? Or defining custom behaviour?

**Comment by tobbi** [comment]
Assuming I wanted to create a custom bonus block, I could say: Take this sprite and let it behave like a bonus block. Something like that. I haven't thought this through any further.

**Comment by Mathnerd314** [comment]
Something like this is already possible, you can do (sprite "blahblah/mysprite.sprite") and it will use your custom sprite. This is used to make krosh: https://raw.githubusercontent.com/SuperTux/supertux/ee1d48f973ac254a339225eaae8ce2ae5985f4c8/data/levels/bonus3/-89-2_degrees.stl

And it is supported in the editor, see the SpriteFile property: https://github.com/SuperTux/supertux-editor/blob/0c666e8ccc7daf9e9720fe79abd63f8fa979c5e5/supertux-editor/LevelObjects/SimpleObject.cs#L107
