### ISSUE TITLE
weapons dont work (fireflower, iceflower etc)

### ISSUE THREAD

**Issue by fishstew** [SuperTux/supertux#1340]
**SuperTux version:** supertux2 v0.6.1 

**System information:** *(details about your kernel, operating system, or distribution)*
Linux 5.5.1-arch1-1 #1 SMP PREEMPT Sat, 01 Feb 2020 16:38:40 +0000 x86_64 GNU/Linux

##### Expected behavior
after collecting flower powerup to use the said powerup by pressing ctrl

##### Actual behavior
nothing happens expect you can run thats about it

##### Steps to reproduce actual behavior
collect flower powerup and try to fire with it.

##### Additional debugging information

> The key you just pressed is not recognized by SDL. To help get this fixed, please report this to the SDL forums/mailing list <https://discourse.libsdl.org/> X11 KeyCode 130 (122), X11 KeySym 0xFF31 (Hangul).
The key you just pressed is not recognized by SDL. To help get this fixed, please report this to the SDL forums/mailing list <https://discourse.libsdl.org/> X11 KeyCode 130 (122), X11 KeySym 0xFF31 (Hangul).

*If available, please attach a backtrace of a crash (you can get one using GDB or another debugger), or a core dump. If you're on GNU/Linux and your distro is using systemd, it's highly likely that a core dump is available using `coredumpctl(1)`.
If the issue only occurs in a custom level, please attach that too.*

##### Guidelines for reporting issues

- [x] I have read <https://github.com/SuperTux/supertux/blob/master/CONTRIBUTING.md#bug-reports>.
- [x] I verified this isn't an issue that's already been reported.
- [x] This report only includes details about **one** (1) issue, feature request or topic.
- [x] If I make a mistake while submitting this report I will use the edit feature instead of closing this issue and opening a new one.
- [x] This issue is **not** about wrong translations (use Transifex for those), or anything unsupported (e.g. third-party add-ons).
- [x] Once you're done, please remove the section 'Guidelines for reporting issues', the 'Additional debugging information' if it is empty, and any text in *italic font*.

**Comment by Zwatotem** [comment]
Did you make sure, that your key binding in game settings are correct?
Tell how does pressing different keys for _action_ work, and if _Lctrl_ is the only one not recognized.
As far as I was able to state the problem is that SDL does not recognize certain keys on some keyboards, so I'm worried we won't be able to neither reproduce the problem without having your keyboard, nor repair it without completely changing the method of capturing input.

**Comment by fishstew** [comment]
the Lctrl works fine on my keyboard.

its a strange thing. because as Lctrl is the action key (for run and shoot) the running aspect is ok, however the firing isnt. 

The key bindings are the default ones. is there any way to change them to say left shift instead? 

Also i should point out i have tried to delete my config file/folder to see if that does the trick and make sure its all updated. is there any troubleshooting steps i should try as well, :-)

**Comment by Zwatotem** [comment]
If you are playing 0.6.1, then note, that running with ctrl is no longer a thing. Tux starts running after ~1s of pressing left. Furthermore in this version default keybinding for action is Lalt for some reason. And yes, you can change your keybindings, by choosing `Options -> Setup Keyboard`.

**Comment by fishstew** [comment]
ah ok. I will give it a try when i get home and let you know how i get on. Thanks for getting back to me though so quickly. :-)

**Comment by fishstew** [comment]
You was right it was the key binding that change between 0.6 and 0.5

who's crazy idea was that without telling the user?! anyway its sorted now i have set the key back to lctrl and it seems to work.
