### ISSUE TITLE
Spring sprite changing back in editor

### ISSUE THREAD

**Issue by busybody42** [SuperTux/supertux#1342]
Whenever I try to change the spring sprite to a mr jump sprite, with a newassets folder, It'll just change back as soon as I load/undo/redo the level again!
However, when I do it WITHOUT messing with the portable = true/false option, It works just fine!
Can anybody please help me?

**Comment by busybody42** [comment]
https://forum.freegamedev.net/viewtopic.php?f=68&t=12970#p90276
I tried to fix this myself, since nobody seems to have noticed or cared...
I don't want to make a pull request, because I'm kinda worried about that...

**Comment by tobbi** [comment]
It's not *technically* a bug...fixed sprites have a default sprite that gets used at any time.

**Comment by busybody42** [comment]
but it keeps changing back to it when I want it to be a DIFFERENT sprite!
