### ISSUE TITLE
Wall Jumping

### ISSUE THREAD

**Issue by weluvgoatz** [SuperTux/supertux#1343]
https://www.youtube.com/watch?v=G9TWxHjqXks

Here is a demo of wall-jumping that I've added, but I think we should discuss whether or not to actually add it here.  You can react to this comment or add your own comment to give your opinions.

**Comment by busybody42** [comment]
... Maybe as an option for a certain level, like in mario multiverse... (complete with showing you on the level loading screen that you can do so)

**Comment by serano01** [comment]
I like the idea, and like I wrote in riot, I don't think it would create the need to change many levels, as I can't recall any where two walls are as close as in the video.

**Comment by Zwatotem** [comment]
I recommend adding a tile attribute `sticky` for tiles, that Tux can attach to and jump of.

**Comment by busybody42** [comment]
I agree with Zwatotem...
Either my idea, and/or his idea could be added...
non-sticky tiles aren't affected...
maybe make it an option for invisible walls?

**Comment by busybody42** [comment]
I meant maybe we could make it an option for invisible walls to be walljumpable, so tux may be able to clutch-walljump out of a death pit... 
And/or maybe we could add in a unique thing (like invisible walls, in terms of sizing) that makes it possible to wall jump at that point! (You have to be touching an invisible wall or a solid tile WHILE you're in the zone for the walljump object for it to work, though)

**Comment by slackstone** [comment]
I like attributes for sticky tiles idea if it keeps things more backwards compatible. Wall jumping doesn't look that natural. If the game play is fun.

**Comment by Alasdairbugs** [comment]
i think there should be a graphic for sticky tiles that someone can add over their tiles (basically just foreground decoration) so players can distinguish when they can wall jump and when they cant. I dont think this should be used everywhere though, because it removes the need for kaizo jumps being able to scale large walls. And they're a pretty cool mechanic which keeps tux's skill ceiling high.

**Comment by LizzyBach** [comment]
I love wall-jumping so, it'll be a nice idea.

**Comment by LizzyBach** [comment]
What about an option, which you can enable in the editor to allow wall-jumping in that particular level?

**Comment by Rusty-Box** [comment]
> What about an option, which you can enable in the editor to allow wall-jumping in that particular level?

That is a bad idea. It’s too confusing for players. If walljumping is added it shall be useable in all levels. Either on all walls or limited to a certain type of wall (I personally prefer the second).

**Comment by papb** [comment]
Wall-jumping is really nice, but it should not be added automatically to any wall, otherwise all existing levels would be completely messed up (becoming a lot easier). I like @Zwatotem idea. Maybe there could also be a new visual indicator that could be placed in the wall by the level creators to allow players to know whether or not a wall is 'jumpable'.

**Comment by Ordoviz** [comment]
If we don’t come up with a good visual indicator for sticky walls, we could go through the old levels and add an ice overlay  to walls that are _not_ supposed to be walljumpable. While doing that, we could also fix other level issues (especially in the bonus islands).

**Comment by weluvgoatz** [comment]
I think sticky tiles should be added to walls that aren't walljumpable, as
well as convert some "non slippery" tilesets to walljumpable (ghost forest,
cave) and just update levels accordingly.  Normal tiles, if needed to be
walljumped, could use the sticky tiles and there could be a sign to
indicate that the tiles near it are walljumpable the first time you see
it.  I'd hate to only be able to walljump on walls with one specific
indicator, it should feel more natural but not be available on every. tile.

Walljumping as I tested it is not OP at all.  You can't one-wall wall jump
so on those types of walls it already is useless, and in the main story
mode there are only a few zones with two parallel walls that might even
slightly allow a skip, and bonus worlds might be similar.

**Comment by LizzyBach** [comment]
Are you sure that you can't do one sided wall jumps in any scenario?

**Comment by Semphriss** [comment]
Closing as this was added in the game with #1631 .
