### ISSUE TITLE
Reorganize Levels from the (core) game

### ISSUE THREAD

**Issue by serano01** [SuperTux/supertux#1344]
As of now, there are 8 "official" Add-Ons in-game: Bonus Islands 1-4, Community Island 2016, Halloween 2014, Revenge in Redmond, and the Christmas Special. For better overview, we could make subfolders for the main menu, e. g. "Bonus Islands" which leads to the Bonus Islands, "Seasonal Add-Ons" which leads to the other 4 worlds. Plus, there are many more add-ons ready for download in the repository on our github site, or the forums, which could after download and installing be found under "DLCs" or something like that.

Your own ideas are welcome, and someone, who could execute it, as well.

**Comment by busybody42** [comment]
... Community islands is NOT a seasonal world...
Revenge in Redmond, only fits in bonus islands...
However, we could also add a third subfolder, and name it "Miscellaneous Islands," and include the Community island and Revenge in Redmond addons in THERE!

**Comment by busybody42** [comment]
Oh, yeah...
Don't forget about incubator island! (misc subfolder too)

**Comment by Rusty-Box** [comment]
This basically goes somewhat hand in hand with #720

**Comment by mrkubax10** [comment]
Added in #1790
