### ISSUE TITLE
Flip Level Transformer doesn't flip decals

### ISSUE THREAD

**Issue by weluvgoatz** [SuperTux/supertux#1355]
**SuperTux version:** 
0.6.1
**System information:** *(details about your kernel, operating system, or distribution)*
 Windows 10
##### Expected behavior 
Flipping the level should flip the decals, since it flips the entire sector.
##### Actual behavior
It doesn't, and causes weird graphical glitches.
##### Steps to reproduce actual behavior
Go into a level that has decals and flips the level, then flip the level.
![Screenshot (516)](https://user-images.githubusercontent.com/39805490/75789503-a7923380-5d1e-11ea-8d8e-ce00fefc29b8.png)

**Comment by tobbi** [comment]
It's only the position that needs changing, isn't it?

**Comment by weluvgoatz** [comment]
The image itself also needs to be flipped.

**Comment by Zwatotem** [comment]
I think there is a reason why this feature was deprecated in official levels. There are still lot of hard to predict edge cases, so I'd be very careful about it.
