### ISSUE TITLE
Idea: Ice Cutlass

### ISSUE THREAD

**Issue by weluvgoatz** [SuperTux/supertux#1356]
I suggest the iceflower's shooting bullets ability get removed.  Why? Two reasons: the fire flower already has the bullet ability, and better.  The ice bullets can barely freeze any enemies, and can't even kill them at that.  The fire flower just does the bullet ability so much better than the ice flower, so I recommend replacing the ice bullet ability with something more original, like an ice cutlass/sword.

This ability would work by this: Pressing ACTION will make Tux very quickly draw his sword and stab anything in front of him and quickly pulling back, making Tux do a little dash in the process.  This will kill anything in range of the sword (including multiple enemies at once!)  

Please tell me your thoughts on this idea, thanks.

**Comment by busybody42** [comment]
... Good attempt, but no thanks... The ice flower is ok as is... we need to be able to kill fire flames *somehow,* right?

**Comment by weluvgoatz** [comment]
> ... Good attempt, but no thanks... 
Who are you to tell me what ideas get implemented which don't?
> The ice flower is ok as is...
No? The Ice flower sucks, and there's not really anything support your claim. :/
> we need to be able to kill fire flames somehow, right?
Ice cutlass??? I feel like it'd make just as much sense to kill flames with an ice sword than with what's basically an ice gun.

**Comment by Alzter** [comment]
Definitely sounds more interesting than "worse bullet powerup", and making it double as a movement option with Tux dashing forward when he slashes sounds like an opportunity for it to actually be utilized. Keep working on it :D

**Comment by Zwatotem** [comment]
Okay, you convinced me. My concept is a little different though. First of all ability to freeze should stay in place for this power up. Sword should only kill some enemies, most notably those that make no sense being frozen, and freeze others. It'll go well along with #683 if it gets implemented.

**Comment by weluvgoatz** [comment]
Testing this out: It works nice.  Tux can currently stab and kill most enemies, including enemies that can only be killed with ice bullets.  It also functions similar to spin-jumping from Mario, because the little dash Tux does temporarily halts his fall.  

TODO: 
- Create sprites for ice cutlass + action for Tux using the sword
- Add a separate collision rect whenever the sword is stabbing, for longer reach.

**Comment by HybridDog** [comment]
Is the proposed movement behaviour similar to the Teeworlds ninja powerup?
https://www.youtube.com/watch?v=h0TUTtpIrKE&t=364

**Comment by Alasdairbugs** [comment]
Yeah this idea sucks because it 1: removes kaizo jumps made possible by freezing bomb enemies and doing kaizo style jumps to do large and cool skips. I think that feature makes the gameplay and Tux's movement options more developed and interesting than having a dash when you go inside enemies.

2: i think the ice flower should be buffed though, like shooting 2 bullets per powerup you have, and maybe after a few seconds, if an enemy isnt picked up, the enemy can freeze to death.

If you could demonstrate the dash thing then maybe i'd consider it cooler but im not convinced it will be as useful.

**Comment by busybody42** [comment]
or it could slide backwards when frozen, and act like a mr ice block that dies when it hits a wall.

**Comment by Semphriss** [comment]
This went inactive, and since then we've had multiple discussions about the ice flower. Closing
