### ISSUE TITLE
Level editor: scrolling on the side bar scrolls the entire level map

### ISSUE THREAD

**Issue by AvdonR** [SuperTux/supertux#1358]
**SuperTux version: 0.6.1**
**System information: Linux Mint 19.3, Linux Kernel 5.3.0-40**

##### Expected behavior

Scrolling on the side bar of the level editor should just scroll the implementable level elements and not the entire map

##### Actual behavior

Scrolling on the side bar of the level editor scrolls not only the implementable level elements but also the entire map at the same time

##### Steps to reproduce actual behavior

Scroll up/down on the side bar of the level editor

**Comment by busybody42** [comment]
... That is not a proper bug in my opinion...
I'm sorry, but that's so we actually can put stuff that would normally be behind the editor bars, like the bottom bar, and the tiles bar on the right... 
This would take a lot of time and work to change it, and all for a harmless quirk in the engine...
I don't think this is an error, just a design oddity... sorry...

**Comment by martinvanzijl** [comment]
Apologies, I think I accidentally introduced this in #1177.

@Rusty-Box You may want to try returning `true` in `EditorToolboxWidget::on_mouse_wheel` if the mouse is actually over the toolbox. I think this will prevent the main area from scrolling at the same time.

**Comment by tobbi** [comment]
@martinvanzijl I'm really sorry. It was an inside joke. RustyBox is not a programmer but our graphics guy :) Can you fix it?

**Comment by martinvanzijl** [comment]
@tobbi That's OK :) I will try later today.
