### ISSUE TITLE
get_nearest_player is slow

### ISSUE THREAD

**Issue by icecream95** [SuperTux/supertux#1361]
**SuperTux version:** 0.6.1

`Sector::get_nearest_player` is very slow, and can end up dominating execution time, because rather than iterate through a handful of Player objects, it has to try an expensive `dynamic_cast<Player*>` on every single game object to see if it is a player.

`std::vector<Player*> m_players` could be added to `GameObjectManager` in a similar way to `m_solid_tilemaps`, so that `get_nearest_player` could just iterate through that.

**Comment by Zwatotem** [comment]
This is surely considerable. Player is (I believe) referenced quite often, so this could help a bit with performance.
