### ISSUE TITLE
Level editor crashes when attempting to remove a saw blade

### ISSUE THREAD

**Issue by mikeweilgart** [SuperTux/supertux#1363]
**SuperTux version:** 0.6.1
**System information:** Kubuntu 18.04

##### Expected behavior

When attempting to remove one of the saws (hurtling blades) from the attached level, the blade should be removed.

##### Actual behavior

The level editor freezes for a moment and then crashes.

##### Steps to reproduce actual behavior

1. Open the level editor.
2. Open the attached level.
3. Choose "objects" and choose a page of objects (this step needed because of #1169).
4. Click the eraser.
5. Click on one of the saws.

I also tried clicking on one of the objects in the page of objects in between steps 3 and 4.  This produced a faster crash: with the above steps, the program hangs for several seconds (cursor stops moving) and then crashes; if an object is chosen from the page between steps 3 and 4, the program crashes instantly after step 5.

##### Additional debugging information

[supertux2.coredump.gz](https://github.com/SuperTux/supertux/files/4399746/supertux2.coredump.gz)

[level128.stl.txt](https://github.com/SuperTux/supertux/files/4399732/level128.stl.txt)

**Comment by tobbi** [comment]
This issue should be fixed in an up-to-date nightly build. Can you please go to http://download.supertux.org and download the latest nightly build for the master branch, see whether that fixes things.

**Comment by mikeweilgart** [comment]
@tobbi confirmed; it works now.  Thanks for the quick turnaround!  (This is a nice illustration for my six-year-old son about the benefits of open source, too.  This is his level.)  :)
