### ISSUE TITLE
Broken Screen Scroll/Cutscene(?) in A Tower of Ghosts

### ISSUE THREAD

**Issue by Lemmings42** [SuperTux/supertux#1375]
**SuperTux version: 0.6.1**
#### System information:

MacOS 10.15.3
Graphics: Intel Iris Plus Graphics 655 1536 MB
Processor: 2.7 GHz Quad-Core Intel Core i7
RAM: 16 GB

##### Expected behavior
Screen scrolls normally, following tux, and tux can move when offscreen
##### Actual behavior
On the platform to the left of the second checkpoint (bell), the player loses control of Tux and the frame drops all the way to the bottom of the level, then slowly scrolls back up. when this is happening, tux is pushed by enemies, but takes no damage, and is immovable, like a cutscene.  Once this scrolling ends, the player regains control of tux and the level continues like normal.
##### Steps to reproduce actual behavior
1. Enter story mode level *A Tower of Ghosts*.
2. Reach platform adjacent to second bell.
The *Actual Behavior* sequence will occur

**Comment by Ordoviz** [comment]
The script that triggered this behavior got removed in https://github.com/SuperTux/supertux/commit/61daa42812002584211771c91d28dbc726ec5352
