### ISSUE TITLE
32-bit AppImage Release request

### ISSUE THREAD

**Issue by enigma9o7** [SuperTux/supertux#1381]
Just saying it'd be nice if some brilliant developer could build and release a 32-bit app-image for recent Supertux (like 0.61).

**Comment by Semphriss** [comment]
We do not have access to 32-bit Linux distros; you may instead [compile it from source](https://github.com/SuperTux/supertux/blob/master/INSTALL.md).

Since we unfortunately cannot support 32-bit Linux, I'll close this issue.

**Comment by Semphriss** [comment]
@enigma9o7 (I hope you don't mind the ping, I saw you on another thread)

Just to inform you that #1675 will add official support for 32-bit Linuxes. See [the nightlies](https://download.supertux.org) and under "Linux", search for the packages with "i386" in the name.

**Comment by enigma9o7** [comment]
A minute too late!  I'd forgotten about this post, but as you saw in my recent issue, I just installed a debian bullseye which does have recent supertux in 32-bit repository!  I find it unlikely an alternate build of the same thing will be any different in my case but I'm for sure going to try the upcoming appimage cuz it can't hurt, and this is good news for others.   Maybe it'll run on tinycore or slitaz too :)
