### ISSUE TITLE
Holding UP or DOWN when releasing icecubes is buggy

### ISSUE THREAD

**Issue by Ordoviz** [SuperTux/supertux#1387]
**SuperTux version:** 0.6.2-beta1 AppImage
**System information:** Arch Linux

### Holding DOWN

I appreciate that we can now easily place icecubes on the ground. However, if you release the icecube in mid-air, it falls down with hyper speed and starts walking to the right when it lands. _In this state the icecube attaches to walls or other enemies instead of turning around._

This is similar to #1285.

### Holding UP

I hope that the ability to throw icecubes up or diagonally gets restored because the current behavior is not very useful and broken:

- If you stand on the ground, hold UP, and release the icecube, it walks to the right no matter in what direction Tux is facing. _If Tux faces left, he instantly gets hit._ The icecube also attaches to walls or other enemies just like before.
- If you do this mid-air, the ice-cube slowly falls down and behaves like above. _It is very easy to accidentally hurt yourself in mid-air when you do this._

**Comment by HybridDog** [comment]
I can confirm that throwing mr ice cubes does no longer work.
