### ISSUE TITLE
The background “icecliffs” creates black stripes

### ISSUE THREAD

**Issue by Ordoviz** [SuperTux/supertux#1388]
**SuperTux version:** 0.6.1 and 0.6.2-beta1
**System information:** Arch Linux

Go to *Bonus Island IV* and play the first level *Glacier Danger*. This is the first screen:

![black-stripe](https://user-images.githubusercontent.com/37733333/80802161-144e7080-8b9e-11ea-9626-9e49f96f06e1.png)

**Comment by HybridDog** [comment]
I've seen the black stripe, too.

**Comment by serano01** [comment]
Has finally been fixed. The top image was an inch shorter than the middle one.
