### ISSUE TITLE
Tux cannot jump off a downwards moving trampoline

### ISSUE THREAD

**Issue by Ordoviz** [SuperTux/supertux#1389]
**SuperTux version:** 0.6.2-beta1 AppImage
**System information:** Arch Linux

##### Expeted behavior

Tux can jump off trampoline.

##### Actual behavior

Tux bounces on the trampoline like he does on buttons: [Video](https://peertube.social/videos/watch/c6aab392-61a8-4a60-8d2b-bb7df88ee480)
##### Steps to reproduce

Place trampoline on vertically moving platform. Jump on it.

**Comment by Narre** [comment]
I think this might be related to #401 
The behaviour looks almost the same as on downwards moving unisolid tilemaps.

**Comment by Ordoviz** [comment]
#1514 may fix this.

**Comment by tobbi** [comment]
Fixed by #1514
