### ISSUE TITLE
Problems With Pause Menu

### ISSUE THREAD

**Issue by Karkus476** [SuperTux/supertux#139]
When Abort Level is pressed, for a single frame tux can be seen behind the menu in the level wearing the previous bonus.
How to reproduce:
- Start a level as fire tux
- Run forward and get hurt
- Run back to the start (So that you can see tux)
- Pause
- Click Abort Level while watching tux
- See him change back to fire tux before the level quits

Also if you pause and unpause, tux's jump animation show briefly

**Comment by brmbrmcar** [comment]
I think it's intended behaviour. Abort Level goes back to what you started with, as if you had never clicked on that level.

**Comment by sydneyjd** [comment]
Can this be recreated?

**Comment by Karkus476** [comment]
While the level aborts tux returns to what you started with and you can see it happen in the level behind the menu. It's nothing big, just a timing problem with the Screen fading.

**Comment by Karkus476** [comment]
I shall close this for now as I no longer think this can be considered an issue worth spending time fixing.
