### ISSUE TITLE
Skull Tiles wobble around in the level editor

### ISSUE THREAD

**Issue by Ordoviz** [SuperTux/supertux#1395]
**SuperTux version:** 0.6.2-rc.1-1-93d8ec
**System information:** Arch Linux

##### Expected behavior

Skull Tiles look in the editor like they look when playing a level

##### Actual behavior

Skull Tiles wobble around

##### Steps to reproduce actual behavior

Place Skull Tile in level editor

**Comment by tobbi** [comment]
Are we talking about these? https://prnt.sc/se7dnv
I can't reproduce the issue

**Comment by Ordoviz** [comment]
[This is how it looks on my system](https://peertube.social/videos/watch/5120276a-0d6e-416b-9759-7956e375a882). There are probably more important issues at the moment, though.

**Comment by busybody42** [comment]
they do that so you can tell what they are if you change their sprites

**Comment by Rusty-Box** [comment]
> they do that so you can tell what they are if you change their sprites

No. That's not why they do that.

@tobbi I can reproduce this. The tiles you showed are from the worldmap but hey are talking about the new skull object that falls if the player stands on them for too long.
