### ISSUE TITLE
Throwable objects interact with coins

### ISSUE THREAD

**Issue by Ordoviz** [SuperTux/supertux#1398]
**SuperTux version:** Introduced between 0.6.0 and 0.6.1-beta.1. I assume that https://github.com/SuperTux/supertux/commit/ee86826392ef68d7e05e2a07e917e727d82a41e8 is to blame

##### Expected behavior

Throwable objects (e.g. rocks, trampoline, lanterns) do not interact with coins, checkpoints or the rotating ice balls you typically see in castles.

##### Actual behavior

Throwable objects bounce off coins etc. This causes throwable objects to land on a different spot than you indented or fall more slowly because they fall through a trail of coins.

##### Steps to reproduce actual behavior

- Throw a rock from the side on top of a coin
- Throw a rock down on a trail a of coins

**Comment by Alasdairbugs** [comment]
I think throwable objects should collect the coins, for example, throwing springs, ice cubes, blocks and more. This could allow for some more creative, and deeper gameplay.
