### ISSUE TITLE
Earth flowers are underpowered

### ISSUE THREAD

**Issue by Alasdairbugs** [SuperTux/supertux#1399]
The earth flower has an ability (in the dark) to use a flashlight so you can see where you're going. So, in the rare case that you're actually in the dark (which i think is only like.. what, 1 level in the story mode so far?) it shines a poor, measly light in front of tux. This light should be bigger i think.

Also, his stone ability, while it is cool, i think it would be cooler if his stone ability maybe turned him into poison ivy or immune to ivy of some sort, and even maybe kill enemies when they touch him as he turns to stone. Would be cool. Also instead of freezing him maybe make him move slowly? or able to use his ability mid air? Some ideas.

I also think maybe he should have the ability to break tiles in some way, like tux can pull out a hatchet and start chopping at those wood blocks that act vertically, that would be cool.

**Comment by Ordoviz** [comment]
> Also instead of freezing him maybe make him move slowly?

You can already slide a bit after turning into stone. (Somebody needs to make a level with the earthflower and floor made out of slippery tiles where you can slide through spikes and stuff.)

> use his ability mid air?

Yes please! It would be a lot of fun to smash enemies with spikes from above.

> This light should be bigger

This is a no-brainer.

But having an underpowered powerup is maybe not that bad. The earth flower can be used as a powerup that simply grants you one more hit.

**Comment by SlackySlackereon** [comment]
I honestly disagree. Since making the light bigger makes dark areas too easy to see, and giving Tux the effect of being immune to Ivies, or even giving him the ability to kill enemies that come in contact with me (Not sure if this is what you meant) makes the game too easy.

**Comment by Ordoviz** [comment]
#1527 allows you to try out turning to stone mid-air.

**Comment by Guih48** [comment]
Yes it's underpowered, and would be nice a tanooki-statue-like ability, and plase make more effective to magic blocks too!
