### ISSUE TITLE
Having slopes that end in a wall produces Tux to jitter

### ISSUE THREAD

**Issue by Grumbel** [SuperTux/supertux#14]
Original [issue 3](https://code.google.com/p/supertux/issues/detail?id=3) created by SuperTuxTeam on 2010-02-21T10:11:55.000Z:

&gt; What steps will reproduce the problem?
1. ./supertux data/levels/test/nightcave.stl
2. run into a wall
3. see Tux jitter

&gt; What is the expected output? What do you see instead?
Tux should either stop or turn into a push-wall animation.

**Comment by tobbi** [comment]
This is fixed properly with c12910d.

We now set the on_ground flag even though Tux is slightly above the ground. This fixes the alternating states. Tux can now jump properly, it still jitters a *little* bit, but I think this fixes it better.

**Comment by tobbi** [comment]
This is a nightmare. Now Tux doesn't jitter but has problems jumping on sloped tiles.

**Comment by datahead8888** [comment]
What source file contains the geometry related code for the slope implementation?  I was curious.

**Comment by tobbi** [comment]
Okay, so this issue is fixed with the commit above. Again, we have a slight up-and-down movement (barely noticeable). If anyone wants to find the time to fix this properly (and knows what to do), just go ahead and do it.
