### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by Wuzzy2** [SuperTux/supertux#1401]
**SuperTux version:** 0.6.2

Several strings are not translated / not translatable, despite the German translation on Transifex being at 100% right now:

* World 2: Besides the Bushes
* World 2: The text messages when you reach the end of the Tower of Ghosts
* Main menu: Values of VSync (on/off/adaptive)

This suggests that probably some translation update script was not run …

(Yes, this issue comes several days too late, but I notified you about this in the forums 1 day before release. :-( )

**Comment by Zwatotem** [comment]
@tobbi Is this still valid issue, or can it be closed?
