### ISSUE TITLE
Walking fire continues walking after a bomb kills it

### ISSUE THREAD

**Issue by HybridDog** [SuperTux/supertux#1403]
**SuperTux version:** v0.6.2-3-g40357959f
**System information:** lubuntu 18.04

##### Expected behavior

I don't know what should happen when a bomb hits a walking fire.

##### Actual behavior

When I threw a bomb onto the fire, it just continued walking and went through walls and on the air:
![fot_2020-05-19-20:07:14_673337358](https://user-images.githubusercontent.com/3192173/82362539-c2667100-9a0c-11ea-8631-cc359e05e953.jpg)
![fot_2020-05-19-20:07:19_160176785](https://user-images.githubusercontent.com/3192173/82362544-c4303480-9a0c-11ea-862f-2d8b936bc36c.jpg)

It does not hurt when Tux touches it, so the fire is probably dead.

##### Steps to reproduce actual behavior

Attack a walking fire with a bomb.

**Comment by Ordoviz** [comment]
I can reproduce this. You need to walk into a flame while holding a bomb. The flame then flies off the screen, heading diagonally downwards.
