### ISSUE TITLE
Almost uncollectable coins in 'Wooden Roots'

### ISSUE THREAD

**Issue by Narre** [SuperTux/supertux#1404]
Ubuntu 20.04
SuperTux 0.6.2

In 'Wooden Roots' in world2, there is a coin-explode bonusblock, however, in roughly 9/10 cases, at least one of the coins flies off the edge into the hole, making any efforts to complete the level 100% extremely frustrating as the player has to restart the level over and over again and hope for good RNG. The bonusblock doesn't have enough space above it, so it can't be emptied from the top to avoid the coins flying everywhere.

The platform should either be wider, so the coins don't go flying off the edge, or there should be enough space above the bonusblock so it can be emptied from the top.

![roots](https://user-images.githubusercontent.com/14074789/82374727-c18b0a80-9a1f-11ea-803d-ba1b52c3e592.png)

**Comment by Alasdairbugs** [comment]
This also occurs in Under The Ice, and is a pretty good example of sloppy design...

**Comment by Narre** [comment]
But the bonusblock in 'Under the Ice' can be emptied from the top, which prevents the coin spillage.

**Comment by busybody42** [comment]
Some addons also have this problem... one happens in the halloween addon... a coin rain has a coin fall off the platform... and into a bottomless pit...

**Comment by Alasdairbugs** [comment]
@Narre Then whats the problem??? if you're saying they can be collected from the bottom then they can be collected from the bottom here too, making your entire post redundant. That, therefore, is not a valid reasoning. Please don't make redundant statements.

**Comment by Alasdairbugs** [comment]
I can fix this one

**Comment by Alasdairbugs** [comment]
Actually, In wooden roots, you can place bricks besides the coin explosion box to stop coins from raining either side of it. Yes, its exhausting to move all those blocks, but there is a way to mitigate the explosion and hence coin loss. But i'll fix it anyway this week.

**Comment by tobbi** [comment]
Fixed by merging #1996
