### ISSUE TITLE
A new key for picking things up.

### ISSUE THREAD

**Issue by LizzyBach** [SuperTux/supertux#1412]
0.6.2
Windows 7

Suppose if Tux has a fire flower and he wants the pick up an Ice cube, but when he tries to pick it up, he instead shoots a fireball which melts the Ice cube. So, this can get really annoying as you would instead have to take damage before picking it up. So, this problem can be fixed by assigning a separate key for picking up items.

(LOL, I make dumb mistakes)

**Comment by Ordoviz** [comment]
Giving players the option to assign *picking up* to a separate key is a no-brainer. *Picking up* could still default to the same key as shooting. It should be noted though, that the game currently does not allow assigning a key to multiple actions.

**Comment by LizzyBach** [comment]
> Giving players the option to assign _picking up_ to a separate key is a no-brainer. _Picking up_ could still default to the same key as shooting. It should be noted though, that the game currently does not allow assigning a key to multiple actions.

Okay, got it.

**Comment by plonibarploni** [comment]
> Suppose if Tux has a fire flower and he wants the pick up an Ice cube, but when he tries to pick it up, he instead shoots a fireball which melts the Ice cube.

A simple way to avoid this is to turn and press the action key, and before releasing it turn back around and pick up the ice cube.

**Comment by LizzyBach** [comment]
> > Suppose if Tux has a fire flower and he wants the pick up an Ice cube, but when he tries to pick it up, he instead shoots a fireball which melts the Ice cube.
> 
> A simple way to avoid this is to turn and press the action key, and before releasing it turn back around and pick up the ice cube.

Yeah, that's what I normally do. So it's not a problem anymore. Thanks:-)

**Comment by LizzyBach** [comment]
> > Suppose if Tux has a fire flower and he wants the pick up an Ice cube, but when he tries to pick it up, he instead shoots a fireball which melts the Ice cube.
> 
> A simple way to avoid this is to turn and press the action key, and before releasing it turn back around and pick up the ice cube.

Yeah, that's what I normally do now. This issue is pointless. Thanks for helping me:-)

**Comment by papb** [comment]
I think this is still a good feature to exist though
