### ISSUE TITLE
Mr. Candle - a badguy suggestion

### ISSUE THREAD

**Issue by 165your4** [SuperTux/supertux#142]
[Details](http://pastebin.com/8nAYact4) (I can't be bothered to write them up here)

I think it'd be cool for puzzles.

**Comment by 165your4** [comment]
I've made graphics and a .sprite file for it, but GitHub won't let me attach .zip files.

**Comment by giby** [comment]
Hi :) nice you propose new badguys and graphism... I cannot see it yet... but if you want to work on graphism, please look at this http://supertux.lethargik.org/wiki/Worlds

**Comment by tobbi** [comment]
Relevant forum post with files: http://forum.freegamedev.net/viewtopic.php?f=68&t=6552&sid=cc974c7d27c2d7ca54e3580ab9d17b2e

**Comment by brmbrmcar** [comment]
It looks pretty good. I think it would need to be made and tested first though, to see how well it would work.

**Comment by Karkus476** [comment]
idea tag? feature tag?

**Comment by Hume2** [comment]
@165your4 , you said that you no longer want it. May I close it then?

**Comment by tobbi** [comment]
Please don't close it. I think it's a good idea, in principle at least.

**Comment by brmbrmcar** [comment]
Implement it. See how it goes.

**Comment by sydneyjd** [comment]
I have no spare time to code this. @tobbi could you?
Im also not sure how to implement him properly. Grumbel knows though.

**Comment by sydneyjd** [comment]
Just so we can see how he looks. ;)

**Comment by brmbrmcar** [comment]
Yes. Add them to basic levels.

**Comment by Karkus476** [comment]
I personally do not think at the current time this is worth implementing right now. It is definitely a good idea though, and could be considered for the future.

**Comment by brmbrmcar** [comment]
It will  be difficult. The next few releases will be stable, but this should be tested. Something needs to be done...

**Comment by Hume2** [comment]
I'll implement it.

**Comment by tobbi** [comment]
This is now merged to master, pending a sign that explains the badguy to users (since I believe it might not be understandable at first glance.

**Comment by Karkus476** [comment]
@tobbi not much is really explained in the forest world.

**Comment by tobbi** [comment]
True that.

**Comment by brmbrmcar** [comment]
Has anyone tried it yet? Video?
