### ISSUE TITLE
Display Cut-scene text without coding

### ISSUE THREAD

**Issue by LizzyBach** [SuperTux/supertux#1420]
Supertux 0.6.2
Windows 7 32-bit

Currently, you can only display cut-scene text by typing a 4-5 line code for each sentence. Yes, I know that you can display text with the message box but, they can only be activated by hitting them. So, I guess a new script trigger for displaying cut-scene text with fade in/out, code to process before and after the text is displayed and selecting font, maybe?, I don't know. I think so that it'll be a nice idea. What do you think about that?

**Comment by Alzter** [comment]
We should really have a designated text box for cutscenes.
