### ISSUE TITLE
Allow different types of things to come out of cannon, dispensers etc.

### ISSUE THREAD

**Issue by LizzyBach** [SuperTux/supertux#1421]
SuperTux 0.6.2
Windows 7 32-bit

Currently, you can only have enemies come out of cannons, dispensers etc. Maybe, you can also have  other things like power-ups, stars, and others stuff come out of them as well. It'll be much better. Maybe, we can also have pipes give out stuff. In this game, Pipes don't serve any purpose except for just acting as solid ground. I know that it'll require some optimizations but it'll be a good addition to the game.

**Comment by Ordoviz** [comment]
Using invisible dispensers to make it look like the enemies came out of the pipe is fine for me. Powerups would be a logical addition.

**Comment by LizzyBach** [comment]
> Using invisible dispensers to make it look like the enemies came out of the pipe is fine for me. Powerups would be a logical addition.

Exactly
