### ISSUE TITLE
Update Chinese(simplified) translation

### ISSUE THREAD

**Issue by nios34** [SuperTux/supertux#1422]
I translated SuperTux a few days ago. For some reasons, I don't want to use transfix to contribute it. I already sent a email to "teamj@supertux.org" on May 27 and didn't get reply.

Can you update them for me?

PO file: https://nios34.acgp.club/translation/supertux/zh_CN-20-05-24.po

**Comment by tobbi** [comment]
Uploaded to transifex.

**Comment by nios34** [comment]
> Uploaded to transifex.

ty tobbi
