### ISSUE TITLE
Cheats in level editor level testing

### ISSUE THREAD

**Issue by HybridDog** [SuperTux/supertux#1426]
I think the Cheats and other debug features could be allowed in level testing in the Editor.
Furthermore, a button to en-/disable lighting (`Compositor::s_render_lighting`) could be added to the debug menu.
A fast-forward key (in addition to the debug speed settings) may also be helpful so that e.g. a moving platform path can be tested more easily.

**Comment by Rusty-Box** [comment]
I am in favor of this as it can be quite annoying if only wanting to test a section further in the level.
