### ISSUE TITLE
Be able to throw Mr Bomb

### ISSUE THREAD

**Issue by Karkus476** [SuperTux/supertux#143]
At the moment you can only drop Mr Bomb. I think it would be better if you could throw him, as dropping a bomb is useless as it just blows you up.

**Comment by Karkus476** [comment]
Interestingly, in the code this is intentionally disabled. See bomb.cpp Bomb::ungrab():
"// portable objects are usually pushed away from Tux when dropped, but we
  // don't want that, so we set the position
  //FIXME: why don't we want that? shouldn't behavior be consistent?"
Do we want it or not.
Note: commenting out the line below has next to no effect.

**Comment by brmbrmcar** [comment]
It would be good to be able to throw the bomb. However, it could annoy users who are used to the old dropping method.

**Comment by Hume2** [comment]
Is there anyone who used carrying bombs frequently?
No, because of this thing.

**Comment by brmbrmcar** [comment]
I don't do it either.

**Comment by sydneyjd** [comment]
I would carry bombs more if i could throw them. i always get killed.

**Comment by brmbrmcar** [comment]
Cheeseman is a modification with interesting bomb-carrying behaviours.

**Comment by Karkus476** [comment]
Assign me to this, I'm gonna try to get it done.

**Comment by sydneyjd** [comment]
@Karkus476 No need to assign anyone, just fix it and open a pull request. We don't have much competion about who fixes stuff around here. :smile:

**Comment by Karkus476** [comment]
Can I change this issue to include frozen enemies? They could slide along the ground...

**Comment by sydneyjd** [comment]
@Karkus476 I would leave the frozen bombs alone. They should not do what icecubes do. ;)

**Comment by sydneyjd** [comment]
Also, i cannot assign people who are not in the Supertux organization to a issue.

**Comment by sydneyjd** [comment]
Merged in #159

**Comment by tobbi** [comment]
@Karkus476 Next time, you can add "closes ##" to the commit message to automatically close this :)
