### ISSUE TITLE
Melting stunned icecube in mid-air causes it to splash pink water

### ISSUE THREAD

**Issue by erratic-c-programmer** [SuperTux/supertux#1430]
Supertux v0.6.2-68-gec5e2f521 on Arch Linux

##### Expected behavior
When water hits ground, it splashes, with a white colour
##### Actual behavior
When water hits ground, it splashes, with a pink colour
##### Steps to reproduce actual behavior
1. Jump on an icecube
2. Jump and release in mid-air
3. Immediately melt it with a fireball in mid-air

**Comment by Ordoviz** [comment]
This is intended behavior for the pink ice cubes. Does it also happen with the white ones?

**Comment by Zwatotem** [comment]
On the newest master both normal and pink ice cubes have their intended melting/splashing colours. So if this clarifies things I think we can close this @erratic-c-programmer.

**Comment by erratic-c-programmer** [comment]
Ok, sorry, will close
