### ISSUE TITLE
Unordered paths are no longer supported

### ISSUE THREAD

**Issue by Hume2** [SuperTux/supertux#1439]
**SuperTux version:** 0.6.2
**System information:** *irrelevant*

##### Expected behavior
Unordered paths should work as they used to.
##### Actual behavior
Unordered paths don't work anymore.
##### Steps to reproduce actual behavior
Play the level https://gitlab.com/cecflit/overunderground/-/blob/master/underground3.stl . There is a three-state elevator near the exit. It stops working after the lift reaches the bottom level.
##### Additional debugging information
The support was removed in the commit b3dd633815775. There is a reason but it only explains why Grumbel didn't like the feature, not why it had to be removed. I agree that it wasn't used in any official level or addon at that time but it was present a few times in a planned addon: https://gitlab.com/cecflit/overunderground

Even though the randomness might not be a good idea itself, there is no way to fix the three-state lifts. A platform can always go only to the next node but it can never return one node back without visiting the other nodes. If there are nodes A, B and C, the platform can go either A -> B -> C -> A or A -> C -> B -> A but the decision can't be changed during playtime. The platform can go A -> B but then it can't go B -> A without visiting the node C.

**Comment by LizzyBach** [comment]
Yes, you're right. A little randomness is okay in my opinion. I hope that this feature will make its return.

**Comment by HybridDog** [comment]
Maybe selecting the next point randomly makes it no longer fit to the definition of a path; "unordered path" sounds non-intuitive in my opinion. 
Here's a suggestion for an alternative for the unordered path in existing levels: You could pregenerate a random path; if it is long enough, the player does not notice that it is not really random.

**Comment by Hume2** [comment]
Well, what you say is only a game with words. Tell me one reason why a game should use rigorous definitions, this is not a math exam ;)

What you suggest doesn't fix the issue stated in the OP - there is no way to make the platform skip a node.

**Comment by Grumbel** [comment]
Unordered path is simply illogical. A path is a railroad track. You go forward and backward on it and that's it. Jumping between nodes makes no sense on a railroad track.

**Comment by HybridDog** [comment]
Maybe instead of an "Unordered path", a general abstract Movement Behaviour could be implemented. A Path and what is called "Unordered path" here are then just types (subclasses) of Movement Behaviour. Another Movement Behaviour example would be [Brownian Motion](https://en.wikipedia.org/wiki/Brownian_motion).

**Comment by Hume2** [comment]
It's a game, it doesn't have to be logical ;)

A player who didn't see the technical details might have no idea that anything like path exists. And there is also no way how a player could realise that it is called "Path" without seeing the technical details, so why do you complain? If you add more nodes to make the path smoother, it's your problem. Nobody forces you to use this if you don't like it. However, there is a way to handle this correctly - via scripting.

Creating an abstract Movement Behaviour might be a good idea. There could be also movement behaviours which don't use anything such as nodes.

**Comment by Alasdairbugs** [comment]
This should be removed. Unordered paths are unfair, inconsistent, and annoying. What if tux gets stuck at some ledge and the unordered path takes like 5 minutes to get back to him? This doesn't create fun, it creates frustration.

The same goes for zeekling speed and snowball pilots. They're annoying when they're random, not fun. This game should focus on consistency, and regularity, not weird mechanics that don't work every different time you open a level.

**Comment by HybridDog** [comment]
> […] , so why do you complain?

It is unintuitive/confusing for developers and level creators.

> Nobody forces you to use this if you don't like it.

If many people don't like it, it can be considered a rare edge case. As I mentioned before, it should be possible to pregenerate a long path so that players perceive it as random while in reality it is just so long that they cannot discern it from a true (pseudo-) random movement.

> What if tux gets stuck at some ledge and the unordered path takes like 5 minutes to get back to him?

As far as I know, the level creator can avoid such a situation, for example by adding an additional alternative non-randomly moving platform.

**Comment by Hume2** [comment]
> This should be removed. Unordered paths are unfair, inconsistent, and annoying. What if tux gets stuck at some ledge and the unordered path takes like 5 minutes to get back to him? This doesn't create fun, it creates frustration.

Then it's poor level design. If the randomness doesn't fit the situation, simply don't use it. Are the developers responsible of people designing their levels poorly? If it was really so, we would have to remove everything. Give me a single example of feature which can't be used wrongly.

> The same goes for zeekling speed and snowball pilots. They're annoying when they're random, not fun. This game should focus on consistency, and regularity, not weird mechanics that don't work every different time you open a level.

Then don't use it ;)

> It is unintuitive/confusing for developers and level creators.

What is so confusing about this? Even if it was really so confusing for level creators, they should at least test the level before they deploy it. And if they feel so confused about this, they shouldn't use it.

> As I mentioned before, it should be possible to pregenerate a long path so that players perceive it as random while in reality it is just so long that they cannot discern it from a true (pseudo-) random movement.

As I mentioned before, this doesn't work anyway. It doesn't fix the three-state elevators. If you have three nodes, you call platform.goto_node(1) and then platofrm.goto_node(0), it should advance to node 1 and then return back to 0. In your solution, it would travel through all nodes before reaching the node 0 again.

Alternative suggestion: Make the unordered path work as circular or any other deterministic path but with the exception that platform.goto_node will make the platform go directly to that node

**Comment by HybridDog** [comment]
> What is so confusing about this? Even if it was really so confusing for level creators, they should at least test the level before they deploy it. And if they feel so confused about this, they shouldn't use it.

The name is confusing. The level creators and source code readers would waste their time if they think about it before deciding to ignore it.

> As I mentioned before, this doesn't work anyway. It doesn't fix the three-state elevators.

Sorry, I misunderstood the topic description: I didn't know that it is possible to explicitly adjust the platform movement.

> Alternative suggestion: Make the unordered path work as circular or any other deterministic path but with the exception that platform.goto_node will make the platform go directly to that node

I think this would be a Dynamic Walk, i.e. a [walk](https://en.wikipedia.org/wiki/Path_(graph_theory)) where the edges can be defined during play time.

As far as I know, formally, in a path each node is visited at most once. If a platform moves back and forth, thus visits the same nodes multiple times, it does not move along a path but along a walk.

**Comment by Hume2** [comment]
> As far as I know, formally, in a path each node is visited at most once. If a platform moves back and forth, thus visits the same nodes multiple times, it does not move along a path but along a walk.

Well, by that logic, the paths pingpong and circular aren't paths because each node is being visited over and over. I can define a path as an ordered n-tuple of nodes and then unordered path means that the order doesn't matter. Using this definition, everything is fine.

Another alternative suggestion: Add a command platform.goto_node_direct which makes the platform go directly to given node without visiting the nodes in between.

**Comment by Semphriss** [comment]
Considering there hasn't been anything new here in a bit, and considering that the to-be-merged Bezier curves for paths would render randomly-ordered paths barely implementable, I'll close this issue.
