### ISSUE TITLE
Can't use multiple scripted switches?

### ISSUE THREAD

**Issue by YonathanYeager** [SuperTux/supertux#1442]
**SuperTux version:     0.6.1.1**
**System information:    Linux Mint 19.2 Tina, kernel is 5.4.0-37**
##### Actual behavior:
If I put the script all in one switch, everything will work fine. If I create a second switch and script it, the second will not work, even though the script seems right. The first switch still will do what is supposed to do.

##### Steps to reproduce actual behavior:
Uploading the level file, this will work for you, right?
The first switch that moves the tilemaps BttmTrp1, TT1, and TST1 works.
The second switch is scripted but doesn't have any linked tilemaps(Because I couldn't get it to work.).
The third switch is supposed to move BTR2 tilemap, but wont(Then I decided to come on here and ask for help.).
The fourth switch has nothing done yet.

I double and triple checked my script and tilemap name spellings, the tilemap settings, & tried deleting both the un-working switches and tilemaps and re-doing them.

[level12.txt](https://github.com/SuperTux/supertux/files/4810372/level12.txt)

**Comment by tobbi** [comment]
The error that occurs is "newline in constant".

`if !("ddr1pos` <--- You did not put any closing `"` there.

**Comment by tobbi** [comment]
@YonathanYeager Can you please confirm the fix?

**Comment by YonathanYeager** [comment]
I am sorry for taking so long to get back to you, real life has been eventful. :S
Yes, you spotted the error, and thank you for your time, and sorry for wasting it.

I thought I had checked it over and over, since I know that kind of stuff makes the whole difference.
