### ISSUE TITLE
Idea: World select menu

### ISSUE THREAD

**Issue by Alzter** [SuperTux/supertux#1452]
I think it'd be beneficial to have a world select menu for Story mode, since currently it takes a while to travel from world to world.

Concept:
![image](https://user-images.githubusercontent.com/22513909/86504679-e0dacd00-bdfe-11ea-87b9-cf1785042c29.png)

**Comment by weluvgoatz** [comment]
You already made this issue.  Closing.

**Comment by Ordoviz** [comment]
#1036 is the issue weluvgoatz means.
