### ISSUE TITLE
Sprites with 1 loop don't work in laggy zones

### ISSUE THREAD

**Issue by weluvgoatz** [SuperTux/supertux#1453]
The loops attribute of sprites allows for an action to be played only once (like the buttjump or jumpy) and it works fine normally, but in laggy areas of the game this seems to be thrown out the window and they loop indefinitely, making things like buttjump and jumpy look super weird.  If someone can fix this that'd be great.  I'm on Windows 10 and playing 0.6.2 nightly.

**Comment by HybridDog** [comment]
I can confirm this on Lubuntu 18.04; here's a video: [vid-2020-07-07_18.03.01.mkv.zip](https://github.com/SuperTux/supertux/files/4885905/vid-2020-07-07_18.03.01.mkv.zip)
How I got the low framerate: `export LIBGL_ALWAYS_SOFTWARE=true`

**Comment by HybridDog** [comment]
I've noticed another problem in the newest version: The backflip animation loop does not work; it always shows the same frame.
![fot_2020-07-12-10:37:18_415597799](https://user-images.githubusercontent.com/3192173/87242317-e605d080-c42b-11ea-82bd-e50e3543347f.jpg)

**Comment by HybridDog** [comment]
After testing several versions, I noticed that your commit has introduced the backflip problem: https://github.com/SuperTux/supertux/commit/6f938bcf5

**Comment by Ordoviz** [comment]
@weluvgoatz said [this][1] about the backflip problem:

> Tux is planned to have a new backflip animation eventually anyway that isn't rotated.

[1]: https://github.com/SuperTux/supertux/pull/1407#issuecomment-636292818
