### ISSUE TITLE
Add sound for Jumpy

### ISSUE THREAD

**Issue by Savsish** [SuperTux/supertux#148]
Hume2 has added sound for Jumpy, but the commit disappeared for unknown reason. Someone who is good at making sounds, please add a nicer sound for Jumpy and provide me with a code on how to add sound for Jumpy.

**Comment by mahboi** [comment]
Hmm... I thought the bouncing armored snowball was Jumpy. I do think a bounce sound would be nice, but it would become annoying really quickly if the sound was loud or there were too many Jumpys in one area.

**Comment by sydneyjd** [comment]
Im also against this. If we do this its very easy for supertux to be drowned-out by too many different sounds. So im closing this PR at that.
