### ISSUE TITLE
update super tux in computer of the Argentine government

### ISSUE THREAD

**Issue by charla-con-galo** [SuperTux/supertux#1483]
Maybe you do not have control over this but at least I inform you, the Argentine government incorporated version 0.4 of super tux into their computers, and NO in the new batches. so if you are in control please ask the government to incorporate 0.6.2 (or the latest version when you read it) on new computers, thanks.

**Comment by Alzter** [comment]
what

**Comment by weluvgoatz** [comment]
what

**Comment by charla-con-galo** [comment]
seriously, surprising and probably illegal, but true.

**Comment by GKart** [comment]
Pues no encuentro el prque es ilegal
dudo que tengan control sobre ello
Y a la gente que le interese el juego no creo que le seria tan complicado escribir SuperTux ultima version descsrgar y su respectivo SO.

**Comment by charla-con-galo** [comment]
claro, pero ya sabes. es lindo que venga para que mas gente lo conosca

**Comment by Zwatotem** [comment]
There's nothing we can do about it. If you want government computers to incorporate newer version of SuperTux contact them yourself.

**Comment by Alzter** [comment]
That's like asking the children's court to update their version of Milestone 2 from 0.4, lol.

**Comment by charla-con-galo** [comment]
I will inform the authorities of my scope if it can be updated.
