### ISSUE TITLE
CMake is a mess

### ISSUE THREAD

**Issue by erratic-c-programmer** [SuperTux/supertux#1485]
**SuperTux version:**
0.6.2
**System information:**
Linux

The CMakeLists.txt is very messy, with 1000+ lines of odd CMake syntax.
The generated Makefile is 13000+ lines long.

Perhaps use a normal Makefile?
Portability may be an issue, but people who can be bothered to build Supertux by themselves probably won't be troubled by the need to install gmake.

CMake Makefile builds took 5:32
My handwritten Makefile builds took 6:13
The difference should be negligible.
Both were run as `make -j4`

**Comment by maxteufel** [comment]
See https://github.com/SuperTux/supertux/pull/1486#issuecomment-667261278.
