### ISSUE TITLE
mod support

### ISSUE THREAD

**Issue by charla-con-galo** [SuperTux/supertux#1488]
Something that would be very interesting would be a support for mods along with a tool to create them. I say this because mods (especially texture packages) are intrusive in files, which means that several copies of the game have to be created to be able to install mods at will.

**Comment by Grumbel** [comment]
SuperTux already has mod support. Both simple level packs and file replacements (images, music, etc.) are possible. Users can access it under the "Add On" menu and mods can be installed non-destructivly.

Some (slightly outdated) documentation and examples can be found at:

* https://github.com/SuperTux/addons-src

* http://supertux.lethargik.org/wiki/CreatingMods
