### ISSUE TITLE
Walking enemies look like doing nothing when Tux is defeated by them

### ISSUE THREAD

**Issue by CodingJellyfish** [SuperTux/supertux#1491]
(As this is an enhancement not a bug, I don't think i need to provide too much information.)
Although enemies in Super Mario don't have such animation either, as a more elegant platform game, it is better to add animations like kicking Tux when Tux collides them, because it can make the enemies more vivid.

**Comment by Alzter** [comment]
nah

**Comment by Guih48** [comment]
I think enemies' Tux-hurting/killing animation is a good idea but especially I would more interested in some technical changes, for example: if a (walking) enemy hurts Tux, it could turn back, as in many mario games (to make this mechanic uniqe, this could happen only if Tux is tunning/fanibg to or not to the enemy, or the enemy is facing to or not to Tux)(and its also can have a special animation) What do you think?

**Comment by Rusty-Box** [comment]
This is not planned. We might add that someday but right now we will not - Closing this.
