### ISSUE TITLE
Hebrew letters didn't appear [status: awaiting merge]

### ISSUE THREAD

**Issue by omeritzics** [SuperTux/supertux#1492]
**SuperTux version: v0.6.2**
**PC information: A 64-bit PC running Windows 10 and Linux.**

##### Expected behavior
The Hebrew and English/Latin characters both are displayed well.
##### Actual behavior
The Hebrew characters are not displayed in language auto-detect, And the English/Latin characters are not displayed when choosing Hebrew (non auto-detect).

*I found a better Hebrew supporting font than Yehuda and Noto Sans, and it supports English/Latin characters. Link: http://hebrew-font-shuneet.com/font/index.html.

**Ideal steps to reproduce actual behavior**
1. Merge the Hebrew font (Shuneet or Yehuda CLM) into SuperTux-Medium.ttf.
2. Modify resources.cpp.

**Alternative steps to reproduce actual behavior**
*There is an pending pull request with theese steps. Link: #1520.
1. Use Shuneet font instead of Yehuda CLM.
2. Modify resources.cpp if needed.

**Comment by omeritzics** [comment]
I submitted a pull request to fix this issue, please merge it.
Link: https://github.com/SuperTux/supertux/pull/1495

**Comment by Zwatotem** [comment]
@omeritzics Does https://github.com/SuperTux/supertux/commit/583adad770ae2fb86ee7d28bc6e2f1f8f03bced3 solve the issue listed?
Note, that some texts in Hebrew are missing due to incomplete translation. We rely on community translating the game to different languages.

**Comment by omeritzics** [comment]
I don't think this solve the issue. I recommend to merge Yehuda CLM into SuperTux-Medium.ttf (as in PR https://github.com/SuperTux/supertux/pull/1495) and remove the return to the Hebrew font in the resources file.

**Comment by omeritzics** [comment]
Hello, FontForge crashes almost every time I open SuperTux-Medium.ttf, and I found bugs while trying to merge Hebrew into SuperTux-Medium. Is there another way to merge it?

**Comment by omeritzics** [comment]
Hello, pull request #1520 may solve the issue, Please check it out.
