### ISSUE TITLE
New moveset for Tux

### ISSUE THREAD

**Issue by LizzyBach** [SuperTux/supertux#1494]
SuperTux 0.6.2

Currently, tux can only do a limited amount of things like run, jump, crouch, back-flip, ground-pound, grab/attack and swimming. There should be more moves like wall-jump, crouch-walk, triple-jumps/double-jumps and more. There should be something like an assist move like the twirl in Nsmbwii/Nsmbu. It can be useful for beginners as it can correct a poorly timed jump or simply act as something with which you can cross larger gaps. And triple-jumps, they behave like some kind of move with you can get a little bit more height than a back-flip. Or something like the spin-jump from Smw. Because as of now, enemies like Spikies and jumpys are are impossible to be stepped on. And crouch-walking, it could be pretty useful and as a side note, why does tux take damage when he's not ducking in a one block tight gap as big?  I don't expect all of these moves to be added but if they do end up in the game, then this will become my most favourite game. What do you think?

**Comment by papb** [comment]
If double/triple-jumps are added, the existing levels will get much more easier, right? I don't like that. Perhaps double and triple jumps could be available via a power-up instead of being automatically available?

**Comment by Rusty-Box** [comment]
Also, a triple jump would make the backflip feel kinda pointless, imo.

**Comment by serano01** [comment]
In my eyes that would be way too much. Crouching for Big Tux would be a good idea, but the other mentioned abilities would make Tux overpowered.

**Comment by Rusty-Box** [comment]
Aside from sliding (which may or may not be added to the game), walljumping on special tiles and crouch-walking I can imagine to be added

**Comment by LizzyBach** [comment]
Actually, I only wanted the triple jumps/double jumps and some kind of assist move because they're my favourite moves. Triple/double jumps would've worked like this - you need to be running at full speed and they'll require a lot of space to do so and they'll give you 6 blocks high jump. And the assist move would've worked like this - You can do only 1, 2 or 3 of those, depending upon your fall height. And they can increase your distance covered by 1, 2 or maybe 3 blocks depending upon the number of those moves that you'll do. Maybe, you can have a separate power-up which will give you these and let's face it, SuperTux has only 5 power-ups and one of them is the egg. What do you think about that?

**Comment by serano01** [comment]
I also think that those power-ups already in the game are more than sufficient. More would be overkill. When the planned redesign (new looks for Tux instead of hats) is added I'm satisfied.

**Comment by LizzyBach** [comment]
> I also think that those power-ups already in the game are more than sufficient. More would be overkill. When the planned redesign (new looks for Tux instead of hats) is added I'm satisfied.

Yes, you're totally right.

**Comment by LizzyBach** [comment]
Hopefully, crawling will be added because, it can be really annoying when you accidentally get stuck in a 1 block tight gap as big tux.

**Comment by LizzyBach** [comment]
The rest of the moves, except for wall-jumping using special tiles would be unnecessary and way to op.

**Comment by LizzyBach** [comment]
> Aside from sliding (which may or may not be added to the game), walljumping on special tiles and crouch-walking I can imagine to be added

Sliding on slopes will be amazing and fun. Maybe what about if you get enough speed, you can belly slide on top of water for a few seconds.

**Comment by Ordoviz** [comment]
I don’t see a problem adding triple jumps:

Triple jumps don’t require new buttons like the spin jump or twirl. In the story levels, triple jumps should always be optional. New players do not need to learn this movement technique, thus SuperTux remains accessible to kids and new players.

> a triple jump would make the backflip feel kinda pointless

You can only use triple jumps in large, open areas, whereas the backflip is useful in tight areas. If triple jumps get added, I would still use backflips a lot because it quickly gives me a max height jump.

Triple jumps make jumping around in an empty level more fun. But walljumping and crouch-walking have higher priority.

**Comment by LizzyBach** [comment]
> I don’t see a problem adding triple jumps:
> 
> Triple jumps don’t require new buttons like the spin jump or twirl. In the story levels, triple jumps should always be optional. New players do not need to learn this movement technique, thus SuperTux remains accessible to kids and new players.
> 
> > a triple jump would make the backflip feel kinda pointless
> 
> You can only use triple jumps in large, open areas, whereas the backflip is useful in tight areas. If triple jumps get added, I would still use backflips a lot because it quickly gives me a max height jump.
> 
> Triple jumps make jumping around in an empty level more fun. But walljumping and crouch-walking have higher priority.

You're the only one who gets my point. Triple jumps will not be that hard to implement. It will also make playing a level much more fluid and fun. Maybe triple jumps can give you a six blocks jump so that the backflip doesn't feel that pointless and at the same time triple jumps will more space to pull so that it doesn't feel too op. Though crawling and wall-jumping are more important than triple jumps they'll still be fun and make a stage much better to navigate through. They're quite fun and satisfying to pull off. Hopefully someday, it'll be added because it's my favourite move.

**Comment by Alasdairbugs** [comment]
I suggested this a while ago. There's actually a lot of unique tux movement already here, for example:

Backflips, 1-frames, Duck Jump Cancels, Duck Jumps, neutral bounces, variable bounces, unvariable bounces. There's also kaizo jumping, and such. I do however think we need a triple jump, or some form of spin jump or something cool that gives a different feature from the backflip. The backflip can be useful in areas where you cant build any speed to get enough height with a jump, and therefore is used to reach high areas.

I suggest we make a spin jump only possible when tux has a certain amount of speed, but if his speed is too high, he will fail the spin jump, and is his speed is too low he wont spin. This will allow for a nice middle-ground between the two, because otherwise Tux can just full-speed jump, or just backflip, making a spin-jump worthless and only beneficial visually.



> Also, a triple jump would make the backflip feel kinda pointless, imo.

Wrong. Backflips are used in areas where tux cannot build enough speed to jump high enough. Otherwise the backflip is always useless, a triple jump could be useful where you can build up a lot of speed, but, irregardless of what you decide to add as a new jump, Backflips will always remain useful.

**Comment by LizzyBach** [comment]
> I suggested this a while ago. There's actually a lot of unique tux movement already here, for example:
> 
> Backflips, 1-frames, Duck Jump Cancels, Duck Jumps, neutral bounces, variable bounces, unvariable bounces. There's also kaizo jumping, and such. I do however think we need a triple jump, or some form of spin jump or something cool that gives a different feature from the backflip. The backflip can be useful in areas where you cant build any speed to get enough height with a jump, and therefore is used to reach high areas.
> 
> I suggest we make a spin jump only possible when tux has a certain amount of speed, but if his speed is too high, he will fail the spin jump, and is his speed is too low he wont spin. This will allow for a nice middle-ground between the two, because otherwise Tux can just full-speed jump, or just backflip, making a spin-jump worthless and only beneficial visually.
> 
> > Also, a triple jump would make the backflip feel kinda pointless, imo.
> 
> Wrong. Backflips are used in areas where tux cannot build enough speed to jump high enough. Otherwise the backflip is always useless, a triple jump could be useful where you can build up a lot of speed, but, irregardless of what you decide to add as a new jump, Backflips will always remain useful.

You're totally right. But, I know that Tux can do a lot of things but what I meant was normal moves that beginners can pull off. I've been playing this game for over 2 to 3 years now, but I still can't do most of the complex stuff you mentioned above. I do think that triple jumps should give you more height than a backflip so that they don't feel exactly the same. And sliding, crawling and wall-jumping should be added. And the spin jump, it could be like the one in Nsmbwii, that could allow you to spin jump on spikies, jumpies, and instantly kill an ice cube, or the Spin move from 3d world, but it only allows you to correct your jump. What do you think about that?

**Comment by MrIceblock** [comment]
I honestly disagree for all but the crouch-walk, they make the game too easy and more for babies.

**Comment by Alasdairbugs** [comment]
> > I suggested this a while ago. There's actually a lot of unique tux movement already here, for example:
> > Backflips, 1-frames, Duck Jump Cancels, Duck Jumps, neutral bounces, variable bounces, unvariable bounces. There's also kaizo jumping, and such. I do however think we need a triple jump, or some form of spin jump or something cool that gives a different feature from the backflip. The backflip can be useful in areas where you cant build any speed to get enough height with a jump, and therefore is used to reach high areas.
> > I suggest we make a spin jump only possible when tux has a certain amount of speed, but if his speed is too high, he will fail the spin jump, and is his speed is too low he wont spin. This will allow for a nice middle-ground between the two, because otherwise Tux can just full-speed jump, or just backflip, making a spin-jump worthless and only beneficial visually.
> > > Also, a triple jump would make the backflip feel kinda pointless, imo.
> > 
> > 
> > Wrong. Backflips are used in areas where tux cannot build enough speed to jump high enough. Otherwise the backflip is always useless, a triple jump could be useful where you can build up a lot of speed, but, irregardless of what you decide to add as a new jump, Backflips will always remain useful.
> 
> You're totally right. But, I know that Tux can do a lot of things but what I meant was normal moves that beginners can pull off. I've been playing this game for over 2 to 3 years now, but I still can't do most of the complex stuff you mentioned above. I do think that triple jumps should give you more height than a backflip so that they don't feel exactly the same. And sliding, crawling and wall-jumping should be added. And the spin jump, it could be like the one in Nsmbwii, that could allow you to spin jump on spikies, jumpies, and instantly kill an ice cube, or the Spin move from 3d world, but it only allows you to correct your jump. What do you think about that?

those are all very good suggestions and i'm on board with all of these.

Additionally, crouch-walking is a MUST have for this game. Currently, if you have a 1 wide area you cannot go under it with tux without taking 10 years to duck jump through it.

**Comment by LizzyBach** [comment]
> I honestly disagree for all but the crouch-walk, they make the game too easy and more for babies.

Don't forget that that this game is also for children.
And in my opinion, they do make the game a tiny bit easy, in some cases; But, I think they'll just make moving around much more fluid, fun and just overall make the game more fun.

**Comment by LizzyBach** [comment]
> > > I suggested this a while ago. There's actually a lot of unique tux movement already here, for example:
> > > Backflips, 1-frames, Duck Jump Cancels, Duck Jumps, neutral bounces, variable bounces, unvariable bounces. There's also kaizo jumping, and such. I do however think we need a triple jump, or some form of spin jump or something cool that gives a different feature from the backflip. The backflip can be useful in areas where you cant build any speed to get enough height with a jump, and therefore is used to reach high areas.
> > > I suggest we make a spin jump only possible when tux has a certain amount of speed, but if his speed is too high, he will fail the spin jump, and is his speed is too low he wont spin. This will allow for a nice middle-ground between the two, because otherwise Tux can just full-speed jump, or just backflip, making a spin-jump worthless and only beneficial visually.
> > > > Also, a triple jump would make the backflip feel kinda pointless, imo.
> > > 
> > > 
> > > Wrong. Backflips are used in areas where tux cannot build enough speed to jump high enough. Otherwise the backflip is always useless, a triple jump could be useful where you can build up a lot of speed, but, irregardless of what you decide to add as a new jump, Backflips will always remain useful.
> > 
> > 
> > You're totally right. But, I know that Tux can do a lot of things but what I meant was normal moves that beginners can pull off. I've been playing this game for over 2 to 3 years now, but I still can't do most of the complex stuff you mentioned above. I do think that triple jumps should give you more height than a backflip so that they don't feel exactly the same. And sliding, crawling and wall-jumping should be added. And the spin jump, it could be like the one in Nsmbwii, that could allow you to spin jump on spikies, jumpies, and instantly kill an ice cube, or the Spin move from 3d world, but it only allows you to correct your jump. What do you think about that?
> 
> those are all very good suggestions and i'm on board with all of these.
> 
> Additionally, crouch-walking is a MUST have for this game. Currently, if you have a 1 wide area you cannot go under it with tux without taking 10 years to duck jump through it.

10 out of 10, can relate. LOL

**Comment by Guih48** [comment]
I think double/triple jumps are not needed boeause backflip replaces that, and if crouching  is added, small-tux gates is no more possible, but wall-jumping (only on special tiles!!!) is a good idea. 
And spinjump is a good idea too, but I think ground-pound replaces it, so spinjump could be included in a state (a starred-like super state?) that disables ground-pound, so this is only good if we have only ground-pound OR spinjump (Who has ever seen a Mario game in which both spinjump and Ground-Pound were possible?). 
Sliding is a good idea, but it can't be too easy, so it could reqire running speed (or maybe it could exclusive to mini-tux?)

And finally i don't like this auto-running system, it would be nice, if would be a setting, in controls, that dosables auto-running, and you could run with action button (like in milestone 1)(or up arrow???).
_Sorry for my bad English_

**Comment by ixPost** [comment]
There already is wall jumping. The tile for it is at the bottom of bonus + blocks and you a edge of the tiles on where you want tux to wall jump.

**Comment by ixPost** [comment]
There already is wall jumping. The tile for it is at the bottom of bonus + blocks and you a edge of the tiles on where you want tux to wall jump.
![Uploading Wall Jumping in Editor.png…]()

**Comment by weluvgoatz** [comment]
Closing because Tux (without powerups)'s moveset has been completed as of the addition of sliding and crawling.
