### ISSUE TITLE
Game Crash (Segmentation Fault) on erasing an object with a Path Node in a custom level

### ISSUE THREAD

**Issue by SlackySlackereon** [SuperTux/supertux#1498]
**SuperTux version: 0.6.1.1**
**System information: Ubuntu 20.04** 

##### Expected behavior
Object with path node should be erased

##### Actual behavior
Segmentation Fault (Game Crash)

##### Steps to reproduce actual behavior
Erase the object with a path node in a custom level

##### Additional debugging information
Only says this

TIME                            PID   UID   GID SIG COREFILE  EXE
Wed 2020-08-12 15:54:35 +08   15934  1001  1001  11 present   /usr/games/supertux2

**Comment by Zwatotem** [comment]
Good news is this was a known problem and is already solved in development builds. Thanks for the report.
