### ISSUE TITLE
"Unsaved Changes" pops up when exiting a custom level that hasn't changed.

### ISSUE THREAD

**Issue by SlackySlackereon** [SuperTux/supertux#1499]
**SuperTux version: 0.6.1.1**
**System information: Ubuntu 20.04 LTS** 

##### Expected behavior
Don't pop up when nothing is done
##### Actual behavior
Pops up when nothing is done
##### Steps to reproduce actual behavior
Edit a Custom Level without doing anything, and then exit the level
##### Additional debugging information
I don't think this is a bug.

**Comment by Semphriss** [comment]
Investigating on this, and I found a related error : When opening a level and performing multiple actions, undoing only the last of them then quitting will not ask for save, despite multiple changes having been made.

I'm currently working on fixing this.

**Comment by Semphriss** [comment]
Alright, I managed to fix the original bug : a freshly loaded level no longer asks to save before quitting.

On the related bug I found, it seems as a single undo resets the entire stack (somehow). I'm still investigating to fix this issue.
