### ISSUE TITLE
Addons showing unintended behaviour.

### ISSUE THREAD

**Issue by brmbrmcar** [SuperTux/supertux#150]
Namely Fiona's World.

**Comment by tobbi** [comment]
Please be more specific.

**Comment by brmbrmcar** [comment]
I will try to take a screenshot. There are loops in  switches. Colour doesn't change when meant to.

**Comment by Karkus476** [comment]
...? This is kinda ridiculous. I can't go off and fix 'unintended behaviour'

**Comment by brmbrmcar** [comment]
In Colour Cave, changes of colour don't always work.

**Comment by Karkus476** [comment]
Do you mean it sometimes skips colours? Or sometimes changes to the wrong colour?

**Comment by brmbrmcar** [comment]
It doesn't change at all.

**Comment by mahboi** [comment]
That's likely a bug in the switch's script, although I'm not very sure. You should contact the add-on author or check yourself. I don't quite know what you're talking about with color changes, as the last time I was playing that add-on it was on an Android tablet with poor OpenGL drivers where lights were broken.

**Comment by brmbrmcar** [comment]
There is no actual switch to press.

**Comment by Karkus476** [comment]
He is talking about a bug in the code that switched the colours

**Comment by mahboi** [comment]
Whoops... Well, I'm going to go see what I can find about this issue.

**Comment by mahboi** [comment]
Well, after playing with it, it seems perfectly fine to me. The colors change as expected.

**Comment by brmbrmcar** [comment]
Do they do it immediately?

**Comment by mahboi** [comment]
Yes. Was the change supposed to be gradual?

**Comment by LMH0013** [comment]
The color change should occur after a slight delay - the goal was to give enough time for a small child to read the message before the color changed.  If the color is not changing at all, then something bad is going on.  Otherwise, a delay in the color change is intentional.

**Comment by brmbrmcar** [comment]
OK. But what abount the switches?

**Comment by LMH0013** [comment]
Can you be more specific? I am not sure what you are asking.

**Comment by brmbrmcar** [comment]
In Castle drawbridge, pressing the switch  once does the intended operation. Flipping it again reverses it Is it intended? It seems easy to accidentally flick it twice.

**Comment by tobbi** [comment]
From the code, it looks intended.

**Comment by LMH0013** [comment]
Indeed, it is intended that the switch works both ways. Just a personal preference that actions are reversible, it satisfies my OCD.
I surmise that it is safe to say that all behavior is intentional and the issue may be closed?




---- On Tue, 29 Sep 2015 07:02:31 -1000 notifications@github.com wrote ---- From the code, it looks intended.

**Comment by brmbrmcar** [comment]
Closed.
