### ISSUE TITLE
Level going back to start screen

### ISSUE THREAD

**Issue by brmbrmcar** [SuperTux/supertux#151]
Sometimes, after finishing a contributed level, instead of going onto the worldmap it goes to the start screen.

**Comment by tobbi** [comment]
Which version of SuperTux are you using?

**Comment by brmbrmcar** [comment]
0.4.0, but it was last updated 9 weeks ago.

**Comment by tobbi** [comment]
Please see https://github.com/SuperTux/supertux/issues/87 

I believe, I have fixed that with the referenced revision.

**Comment by brmbrmcar** [comment]
Have that exact problem; sorry for bringing it up.

**Comment by tobbi** [comment]
No problem, please try to compile the latest git revision, and test it yourself.
