### ISSUE TITLE
Will-O-Wisp not exposed to scripting anymore

### ISSUE THREAD

**Issue by Ordoviz** [SuperTux/supertux#1510]
**SuperTux version:** since d5a5b62ebfd0f8250cac2432c7f59dc44dbdb4bd (found with `git bisect`)

##### Expected behavior

Will-O-Wisps are scriptable.

##### Actual behavior

    Error running script: Squirrel error: Couldn't start script (the index 'willy' does not exist)
    [SCRIPTING] AN ERROR HAS OCCURRED [the index 'willy' does not exist]

##### Steps to reproduce actual behavior

Place a Will'O'Wisp and call it _willy_. Open the [console][1] and type `sector.willy`.

[1]: https://github.com/SuperTux/supertux/wiki/Console

**Comment by tobbi** [comment]
Do you have any idea as to why me exposing badguy class to scripting would cause something like this?

**Comment by Ordoviz** [comment]
Maybe because the Will o’ Wisp had its own scripting interface and, being a badguy, inherited another interface, which interferes somehow.

**Comment by Semphriss** [comment]
Related: I'm currently encountering the exact same bug with rain particles, which I attempt to expose to its own template of ``ExposedObject`` while it inherits ParticleSystem, which has its own template of ``ExposedObject``.

Also related: the Dispenser is in the same situation. I wanted to test it, but I couldn't find the dispenser from the editor toolbox.

I will look into this and report any progress/solution I can find about this problem.
