### ISSUE TITLE
Use the language names translated into the default language (idea)

### ISSUE THREAD

**Issue by omeritzics** [SuperTux/supertux#1522]
Hello, using the language names translated into the default language can be an alternative to use the local name of every language.
Examples for option 1:
If the selected language is English: English, Spanish, French, Arabic, Hebrew, etc.
If the selected language is Spanish: Inglés - English, Español - Spanish, Francés - French, Árabe - Arabic, Hebreo - Hebrew, etc.
If the selected language is French: Anglais - English, Espagnol - Spanish, Français - French, Arabe - Arabic, Hébreu - Hebrew, etc.
If the selected language is Arabic: الإنجليزية - English, الإسبانية - Spanish, الفرنسية - French, العربية - Arabic, العبرية - Hebrew, etc.
If the selected language is Hebrew: אנגלית - English, ספרדית - Spanish, צרפתית - French, ערבית - Arabic, עברית - Hebrew, etc.

Examples for option 2:
If the selected language is English: English (en), Spanish (es), French (fr), Arabic (ar), Hebrew (he), etc.
If the selected language is Spanish: Inglés (en), Español (es), Francés (fr), Árabe (ar), Hebreo (he), etc.
If the selected language is French: Anglais (en), Espagnol (es), Français (fr), Arabe (ar), Hébreu (he), etc.
If the selected language is Arabic: الإنجليزية (en), الإسبانية (es), الفرنسية (fr), العربية (ar), العبرية (he), etc.
If the selected language is Hebrew: אנגלית (en), ספרדית (es), צרפתית (fr), ערבית (ar), עברית (he), etc.

**Comment by tobbi** [comment]
My problem with this is that this is gonna make it harder to switch back to some other language once you've accidentally set a language that you can't read.

**Comment by omeritzics** [comment]
Hello, I updated the idea and the examples with the solution of this.
