### ISSUE TITLE
Problems with the Hebrew font

### ISSUE THREAD

**Issue by omeritzics** [SuperTux/supertux#1523]
#1681  fixes this issue, please check it out.

**Comment by omeritzics** [comment]
Pull request https://github.com/SuperTux/supertux/pull/1524 may solve this issue, please check it out.

**Comment by Zwatotem** [comment]
Does https://github.com/SuperTux/supertux/commit/e6094875d346157d5169aeb7864f96b12fb851b4 solve this issue? 
Please test, by downloading appropriate version from https://download.supertux.org/ (auto-locale-font branch). I can't test myself, since none of my devices are in Hebrew.

**Comment by omeritzics** [comment]
Hello, this doesn't solve the issue. Replacing `    return "fonts/shuneet3-medium.otf";
  return "fonts/SuperTux-Medium.ttf"; with `    return "fonts/shuneet3-medium.otf";
 } 
else
{
 return "fonts/SuperTux-Medium.ttf";`
may solve it.

**Comment by omeritzics** [comment]
Hello, https://github.com/SuperTux/supertux/commit/1ef369a0a6cf815b03231efa09d3c10943f48679 solved this issue, but there is a problem with Shuneet in SuperTux.

**Comment by omeritzics** [comment]
> Hello, I tried the last nightly build and the problem is solved, but there is a problem with Shuneet in SuperTux somehow.

This issue is back.

**Comment by omeritzics** [comment]
Hello, pull request solves this issue and also adding the Devanagari letters to SuperTux Medium. Link: #1534

**Comment by omeritzics** [comment]
Hello, PR https://github.com/SuperTux/supertux/pull/1534 is waiting for review, and it fixes a missing-glyph problem in Devanagari too.

**Comment by omeritzics** [comment]
PR #1681 is waiting for review and provides a better solution for Hebrew and Devanagari by replacing the fonts.
