### ISSUE TITLE
Checkpoints' sprites cannot be changed as of 0.6.2 and above in nightly builds

### ISSUE THREAD

**Issue by PungentZeus0** [SuperTux/supertux#1529]
**SuperTux version:** 0.6.2-367-g9cd827faf

I remember in 0.5.1 you were able to change the sprite(s) of the checkpoints. However, I've noticed in 0.6.2 and above in nightly builds, the game gives no option to do so. Is this intentional? (To give context, I was going to re-add back in the old bell sprites used from 0.3.0 to 0.5.1 for a levelset I was making in the nightly builds.)

Thanks for your time!

**Comment by serano01** [comment]
I think it has to do with this commit: https://github.com/SuperTux/supertux/pull/1128

**Comment by Mathnerd314** [comment]
That seems unlikely. The actual game works fine, e.g. "Castle of Light and Darkness" has torch and purple-bell checkpoints. It is only the option to edit the sprite in the editor that is missing.

**Comment by Mathnerd314** [comment]
I think it's this commit: https://github.com/SuperTux/supertux/commit/e1a3d4fe8a05df7a16a098a39204a4075791da60
It should be MovingSprite in Firefly::get_settings instead of MovingObject.

**Comment by tobbi** [comment]
Since no one wanted to work on this, I decided to fix it myself.

**Comment by PungentZeus0** [comment]
oof
