### ISSUE TITLE
SuperTux Milestone 2 release date

### ISSUE THREAD

**Issue by Savsish** [SuperTux/supertux#153]
SuperTux Milestone 2 will be officially released in December 20, 2015

**Comment by sydneyjd** [comment]
This is not an issue, And no it won't. ;) The date is for the Dev team to know and you to not. Thats the fun of it.

**Comment by brmbrmcar** [comment]
The Supertux Dev team know little more than we do about the release date. It is planned. It may be changed if not stable enough by December.

**Comment by Karkus476** [comment]
SuperTux Milestone 2 will be released on Sunday 20th December
