### ISSUE TITLE
Build failure with RELRO due to squirrel being statically built

### ISSUE THREAD

**Issue by ffontaine** [SuperTux/supertux#1536]
**SuperTux version:** 0.6.0
**System information:** buildroot

##### Expected behavior
Build should succeed

##### Actual behavior
Build fails on:

```
/home/peko/autobuild/instance-0/output-1/host/opt/ext-toolchain/bin/../lib/gcc/x86_64-buildroot-linux-musl/8.3.0/../../../../x86_64-buildroot-linux-musl/bin/ld: CMakeFiles/sq_static.dir/sq.c.o: relocation R_X86_64_32 against `.rodata.str1.8' can not be used when making a PIE object; recompile with -fPIC
/home/peko/autobuild/instance-0/output-1/host/opt/ext-toolchain/bin/../lib/gcc/x86_64-buildroot-linux-musl/8.3.0/../../../../x86_64-buildroot-linux-musl/bin/ld: final link failed: nonrepresentable section on output
collect2: error: ld returned 1 exit status
```

##### Steps to reproduce actual behavior
Build supertux with RELRO

##### Additional debugging information

Full debug log available here: http://autobuild.buildroot.org/results/46e/46e8f5e622ce450a89bc6d70f4bfd38182557901/build-end.log

The issue is raised by external/squirrel which is **always** built statically by supertux on Linux.
As a short term solution, I made a patch to build external/squirrel as a shared library however this is probably not the best solution: https://patchwork.ozlabs.org/project/buildroot/patch/20200914203329.3432074-1-fontaine.fabrice@gmail.com/
What is your feedback on this issue? Especially, what is the rationale for building squirrel statically on Linux and dynamically on Windows?

**Comment by tobbi** [comment]
@maxteufel Can you shed some light on this?

**Comment by tobbi** [comment]
Or maybe @maths22 if you have the time? (You're both more versed at build systems than I am).

**Comment by tobbi** [comment]
According to @maxteufel : 
> I know what the rationale is for linking squirrel statically on Linux and dynamically on Windows (on Linux, putting our custom version in the usual locations would conflict with possibly distro-distributed squirrel versions. On Windows we can easily put the dlls next to the binary without bothering other applications)

**Comment by ffontaine** [comment]
Thanks for your feedback, we don't have squirrel on buildroot so this is not an issue for us but I understand your point. What would be the proper way to fix this issue? I could send a PR to upstream squirrel to disable build of sq binary upon user request however it seems that you're using an "old" squirrel version (the submodule has not been updated for more than 2 years) so it is probably not a valid option.
