### ISSUE TITLE
Current Action key (Alt) conflicts with system shortcuts

### ISSUE THREAD

**Issue by MrIceblock** [SuperTux/supertux#1537]
**SuperTux version:** 0.6.2
**System information:** *Ubuntu 20.04*

Hello, I have found that the default Action key for me (Alt) conflicts with some system shortcuts (Example: Alt+Space opens the window menu), so I'd suggest changing it, I know changing keyboard controls exist, but again, I'd suggest that you change the default Action key.

Note: Sorry for the kinda bad English here, English is not my first language.

**Comment by szborows** [comment]
I encountered the same problem on my daughter's PC (Linux + Gnome 3). Alt+Space brings some menu up.

This is not SuperTux fault at all, but it makes playing game cumbersome, as @MrIceblock mentioned - you have gun pointed to your head and only option you have is to change game controls.

Would it be possible to change Action key to e.g. Ctrl?

If there's no will to make such a change, then "NO" answer will also be okay.

I can offer my help in changing it. Just let me know.
