### ISSUE TITLE
Using SuperTux as a RL environment

### ISSUE THREAD

**Issue by AD2605** [SuperTux/supertux#1538]
Hello all, 
Firstly I am sorry as this might be an unusual issue and not an issue in the truest sense. I wanted to train my reinforcement learning agents to play SuperTux and I was wondering if there is any way if there is a function to start a level, 
For example 
```
start_level(string level_name)
The objective of this function is to start a said level and continuously return the rendered RGB frame. 
```
Thanks a Lot

**Comment by Ordoviz** [comment]
You can give a path to a level file when starting SuperTux from the commandline, e.g. `supertux2 /usr/share/games/supertux2/levels/world1/welcome_antarctica.stl`. Inside SuperTux you can use `load_level(string filename)` via the [scripting interface](https://github.com/SuperTux/supertux/wiki/Scripting_reference).

**Comment by AD2605** [comment]
Thanks a lot, @Ordoviz for replying, I will try it out...

**Comment by tobbi** [comment]
I'm gonna close this since the question was answered.
