### ISSUE TITLE
Particle-based fluid animation for powdersnow

### ISSUE THREAD

**Issue by HybridDog** [SuperTux/supertux#1539]
It could be possible to use [fluid animation](https://en.wikipedia.org/wiki/Fluid_animation) algorithms in SuperTux to simulate powdersnow. 
Here is a real-time fluid simulation in webgl which uses the PIC/FLIP method: http://david.li/fluid/
In SuperTux it would probably require less computation because it is only 2D instead of 3D.
I don't know how to implement it but I think that realistic or fancy fluid animations can be an interesting graphics feature. Treating powdersnow as an incompressible fluid may be a bit unrealistic, but it should be possible to adjust the algorithms so that it does not look bad.

**Comment by Semphriss** [comment]
I'm currently working on a custom particle system, and I have plans to implement fluid dynamics (though I'd have to check the feasability of the latter).

To me, fluid animation looks like a quite complex and heavy feature if it's intended to serve only for powdersnow. Do you think general features like custom particles and/or fluid dynamics would do the job?

**Comment by weluvgoatz** [comment]
Why does this issue even exist (fluid dynamics for liquids and custom particles would be a truly great set of features but this particular issue seems pretty worthless to me)

**Comment by HybridDog** [comment]
> Do you think general features like custom particles and/or fluid dynamics would do the job?

Yes, powdersnow is only an example use case. The fluid animation code could be used to create realistic looking flowing water, waterfalls and water splashes, flowing lava and more.

> Why does this issue even exist (fluid dynamics for liquids and custom particles would be a truly great set of features but this particular issue seems pretty worthless to me)

I think that powdersnow could be an interesting feature because snow plays a big role in SuperTux. It's not an essential feature, so I have set the low priority label.

**Comment by Semphriss** [comment]
> The fluid animation code could be used to create realistic looking flowing water [...]

Little opinion, I'm not really fond of the realistic appearance argument. SuperTux doesn't aim to be realistic, but rather enjoyable to play and look at. I however do agree though that a new fluid system would make it look plain better (regardless of whether or not it is realistic).

Generally speaking, I wouldn't support adding such a complex feature for a single use case; fortunately, your suggestion is close to an already-planned feature, fluid dynamics, which includes many use cases which I will showcase at a later time (when I'll have a first draft). I'll investigate at a later time how I will proceed, but I intend to make the fuild system as simple as possible to prevent overloading the users' CPUs.

If you believe fluid dynamics, as currently planned, would be appropriate for your intended use, you may close this issue.

**Comment by HybridDog** [comment]
> Little opinion, I'm not really fond of the realistic appearance argument. SuperTux doesn't aim to be realistic, but rather enjoyable to play and look at.

In my opinion it should be realistic enough to be enjoyable to look at. For example, a fluid should not just flow downwards and sideways and fill empty areas but it should have splashes flying around in the air and visible waves when some object quickly falls into it.

> I intend to make the fuild system as simple as possible to prevent overloading the users' CPUs.

The powdersnow should be an optional feature which is just for visual effects and can be disabled by a setting.
