### ISSUE TITLE
[SUGGESTION] Tux should not play the death animation when falling offscreen

### ISSUE THREAD

**Issue by MrIceblock** [SuperTux/supertux#1545]
**SuperTux version:** SVN .appimage
**System information:** Ubuntu 20.04 LTS Focal Fossa

##### Expected behavior
Just fall off the screen, play a sound (Additional), restart the level after that

##### Actual behavior
Tux bounces and plays his death animation when falling off-screen,

##### Steps to reproduce actual behavior
Fall off the screen

##### Additional debugging information

You guys should make Tux just fall off-screen when doing so (Like in Pre-Milestone 1), since it seems weird to me for Tux to bounce and play his death animation when falling off-screen. I don't have any extra info, this is just a suggestion. Close this if unwanted.

**Comment by Alzter** [comment]
You should rename the title to something more like, "Tux should not play the death animation when falling offscreen", currently it sounds like you want him to not die at all when falling off the screen.

Anyway I think the animation's fine, but that's just my opinion

**Comment by Semphriss** [comment]
Considering this hasn't been brought up again by anyone else, I'll close this issue.
