### ISSUE TITLE
[SUGGESTION] Auto-Save for the level editor (Should be off by default to prevent accidental changes to the level we're editing)

### ISSUE THREAD

**Issue by MrIceblock** [SuperTux/supertux#1551]
**SuperTux version:** SVN via .appimage
**System information:** Ubuntu 20.04 LTS Focal Fossa

Hello, I would like an auto-save system for the level editor that's off by default (In case we don't want accidental changes to the level we're editing), since the game crashed while I'm doing unsaved changes to my level, and now I lost my work. The auto-save system for the level editor may be useful in-case I'm lazy to hit CTRL+S, or even a crash, so can you add this feature?

**Comment by Semphriss** [comment]
That could indeed be a cool feature to have; I'll discuss with the rest of the team about it.


<sub>Small detail, IMHO an auto save system that's off by default kind of defeats the point of its existence, as it's there to serve when the users think about it the least. Fortunately, there's an alternative: Save to a file with a different name (for example, `levelname.stl` would be auto-saved as `~levelname.stl`).</sub>


I'll add that to my to-do list, it shouldn't be too long to implement. Do you think it would be more useful to have it save at regular intervals (say, each 10 minutes), or each time the level gets tested? (The latter is much, much easier to implement, but indeed it does require that you test your level once in a while)


----------


Also, do you know why your game crashed? If it's a reproducible crash, I can try and see if I can fix it so it no longer happens :stuck_out_tongue:

**Comment by MrIceblock** [comment]
> Do you think it would be more useful to have it save at regular intervals (say, each 10 minutes), or each time the level gets tested? (The latter is much, much easier to implement, but indeed it does require that you test your level once in a while)
Maybe should be a preference.

> Also, do you know why your game crashed? If it's a reproducible crash, I can try and see if I can fix it so it no longer happens 
I don't know, it just randomly crashed, I don't think any crash files were dumped since I'm using the SVN .appimage.

**Comment by MrIceblock** [comment]
+ Maybe we should make a new project board named "Level Editor Improvements", since I would think the level editor needs some or more improvements. If not, then that's okay.
