### ISSUE TITLE
Backflip sprite isn't rotating anymore (Close if it's under maintenance) 

### ISSUE THREAD

**Issue by MrIceblock** [SuperTux/supertux#1553]
**SuperTux version:** The SVN .appimage
**System information:** Ubuntu 20.04 LTS Focal Fossa

##### Expected behaviour  
Rotate when doing a backflip.

##### Actual behavior
Tux will backflip, but he doesn't look like he is backflipping anymore.

##### Steps to reproduce actual behavior
Do a backflip, press [DOWN KEY]+[JUMP KEY].

In the stable non-nightly builds, doing a backflip will rotate Tux's sprite, but now in the nightly builds, it won't rotate. This seems weird, should we fix this? If not, then that's okay, but I recommend you to fix it if the backflip sprite is not under maintenance. I don't have much info as this is simply just a bug.

**Comment by Ordoviz** [comment]
The team is aware of this. In https://github.com/SuperTux/supertux/pull/1407#issuecomment-636292818 weluvgoatz said:
> Tux is planned to have a new backflip animation eventually anyway that
isn't rotated.

**Comment by MrIceblock** [comment]
> The team is aware of this. In [#1407 (comment)](https://github.com/SuperTux/supertux/pull/1407#issuecomment-636292818) weluvgoatz said:
> 
> > Tux is planned to have a new backflip animation eventually anyway that
> > isn't rotated.

Okay, I'm going to close this issue.
