### ISSUE TITLE
A coin explosion box stuck to a ceiling will blow up the sound manager (OOM error)

### ISSUE THREAD

**Issue by Semphriss** [SuperTux/supertux#1555]
**Steps to reproduce:**
1. Preferably, enable developer mode or launche the game from command line.
2. Open any level in the editor.
3. Place a coin explosion bonus block (not coin rain, coin explosion)
4. Directly above the bonus block, place some ceiling (make sure it's several blocks thick)
5. Test the level.
6. Activate the bonus block.
   - You should see the coins getting stuck in the ceiling then going down for a few seconds as they attempt to crawl down to escape the ceiling.
   - Your ears should also suffer a bit ;)
   - If you enabled developer mode or launcher the game from command line, your console should be flooded with Out-Of-Memory error messages.
7. Attempt to pause the game.
   - The game will crash.

The reasons for this are: 
- The coin spawn their "bling" sound every frame, and there are many of them;
- There is no limit on how many sounds can be created, letting the flood happen freely;
- An object unsuccessfully created will remain existen, but in an erronous state; attempting to stop the sound (which is what pausing does) will throw an error, which is uncaught and results in a fatal error and a crash.

**Comment by MrIceblock** [comment]
Doing step 7 after doing all of the previous steps results in a Couldn't pause audio source: Invalid Name error, hmm... Did you know that?

**Comment by Semphriss** [comment]
> Doing step 7 after doing all of the previous steps results in a Couldn't pause audio source: Invalid Name error, hmm... Did you know that?

Yes, that's what's causing the crash apparently.

**Comment by Alzter** [comment]
I can only imagine how painful that'd be to listen to. Impressive work finding out why the crash happens

**Comment by tobbi** [comment]
Can you upload a test level, @Semphriss ?

**Comment by Semphriss** [comment]
@tobbi You can try with this: [level2.zip](https://github.com/SuperTux/supertux/files/5448974/level2.zip)

Make sure your sound is enabled. Also, I strongly advise you turn your *system* volume down while trying, or even take your headphones off beforehand.

Play the level and activate the trigger box. Look at your console. Attempting to pause the game should result in a crash.

By the way,
**Known workaround:** If you disable sound effects in the options, the error will not happen. I just tested it by accident (I have sounds off by default).
