### ISSUE TITLE
Gold Bombs doesn't play any squish.wav when squished

### ISSUE THREAD

**Issue by MrIceblock** [SuperTux/supertux#1556]
**SuperTux version:**
**System information:** *(details about your kernel, operating system, or distribution)*

##### Expected behavior
Play the squish sound

##### Actual behavior
Just get squished without playing any squish sound

##### Steps to reproduce actual behavior

1. Go to the level editor
2. Go to any world, and any level
3. Place a Gold Bomb anywhere that Tux should be able to reach
4. Test the level
5. Try to squish the Gold Bomb. Did you hear any squish.wav?  
  
While editing my level, I have found out that Gold Bombs doesn't play any squish.wav when squished. Squishing a Mr. Bomb plays the regular squish.wav. Can you fix this?

**Comment by MrIceblock** [comment]
I did a mistake while making this issue, the programming style is kinda the same, Gold Bombs just won't play any squish.wav for some reason.

**Comment by serano01** [comment]
Solved: https://github.com/SuperTux/supertux/commit/9d2a28f1fe90c79277ec1a9516bad779ec34118c
