### ISSUE TITLE
Lock to red "click-to-add" tool when an object is selected

### ISSUE THREAD

**Issue by MrIceblock** [SuperTux/supertux#1559]
**SuperTux version:**
**System information:** *(details about your kernel, operating system, or distribution)*

##### Expected behavior
The green selection tool spreads the objects.

##### Actual behavior
The green selection tool will only spit out one object.

##### Steps to reproduce actual behavior
1. Go to the level editor
2. Edit a level
3. Select an object
4. Choose the green selection tool
5. Try to spread an object

**Comment by Semphriss** [comment]
The spread and fill tools are not relevant when placing objects, since objects aren't meant to be placed in batches like tiles do.

I propose we lock the tool icon when the selected element is an object.

**Comment by MrIceblock** [comment]
> I propose we lock the tool icon when the selected element is an object.

Okay, then I'll be changing this issue to lock the selection tool.

**Comment by Guih48** [comment]
I think, this isn't problem, but it could solved if the green-sqare/red-sqare/bucket and the one-tux/two-tux buttons automatically appear and disappear depending our selection (tile or object). And by this method we also get an extra button place too!
