### ISSUE TITLE
Frozen sleepy spiky = Frozen normal spkiy

### ISSUE THREAD

**Issue by brmbrmcar** [SuperTux/supertux#156]
Not a massive issue, but should hopefully be resolved in the future.

**Comment by Karkus476** [comment]
I quote the code : "if we get hit while sleeping, wake up :)"

**Comment by brmbrmcar** [comment]
Ok, I'll close it.

**Comment by brmbrmcar** [comment]
This should be looked into.

**Comment by tobbi** [comment]
No, it's intended behaviour.
