### ISSUE TITLE
SuperTux crashes due to invalid locale when locale is set to C.UTF-8

### ISSUE THREAD

**Issue by Newbytee** [SuperTux/supertux#1564]
**SuperTux version:** 0.6.2
**System information:** postmarketOS Edge (Alpine Linux Edge) Phosh. Linux 5.9.1 (megi's branch). PinePhone.

##### Expected behavior
SuperTux runs fine when locale is set to C.UTF-8.
##### Actual behavior
SuperTux crashes when locale is set to C.UTF-8.
##### Steps to reproduce actual behavior
Run SuperTux either on a postmarketOS Phosh installation or Alpine Linux with the locale set to C.UTF-8.
##### Additional debugging information
Setting locale to C by setting `LC_ALL=C` makes the game run.

**Comment by kk6mrp** [comment]
I am running the latest version on Alpine Linux and still need to export LC_ALL=C before starting Supertux. Is this supposed to be required? I have other applications that require UTF-8.

**Comment by Newbytee** [comment]
> I am running the latest version on Alpine Linux and still need to export LC_ALL=C before starting Supertux. Is this supposed to be required? I have other applications that require UTF-8.

There hasn't been a new release since this issue (hopefully) was fixed.

**Comment by kk6mrp** [comment]
Thanks for the the fix! I can confirm that it works as expected now.
