### ISSUE TITLE
Feature Request: Level progress information when pausing

### ISSUE THREAD

**Issue by ScriptForAll** [SuperTux/supertux#1570]
Showing information about the level. namely coins collected, time played, badguys killed, and secrets found, in the pause menu would be a good way to give feedback to the players about their playing.
A good use case for this would be when players reach the end goal but don't know if they have collected all the coins or killed all the badguys. Having missed a coin to then repeat the whole level just to have a perfect completion seems a bit too punishing since the player doesn't have a way to know about their progress.

**Comment by serano01** [comment]
Cool idea, while I'd prefer not only in pausing, but also in-game, too. In Crash Bandicoot, pressing triangle shows the status of boxes in the level and how many are already cleared.

**Comment by ScriptForAll** [comment]
I've thought about that possibility too. Both ways are good options but I reckon that your suggestion would be less annoying to the player since it doesn't force them to stop their gameplay every time they wants to check the level's progress.

**Comment by Zwatotem** [comment]
I'll add to that: maybe add a monostable key bind for showing the statistics, so that you can glance at them without stopping, and they don't obstruct the screen.

**Comment by Ordoviz** [comment]
Showing the statistics in the pause menu would make this feature more discoverable and would avoid the need to remember an additional button. You typically only need this at the end of a level to check whether you collected everything; so pausing is not too inconvenient.

**Comment by ScriptForAll** [comment]
I believe that depends on how you play, some people would like to know how much time elapsed during their gameplay (e.g. speedrunners) while others don't. Other example that supports having a monostabble key bind/toggleable setting is when a player doesn't like back tracking when collecting coins.

I agree that having the statistics displayed at the pause menu makes it a discoverable feature. My suggestion is making this feature's (and its key binding) disabled by default.
