### ISSUE TITLE
MrBomb Bug

### ISSUE THREAD

**Issue by SalomonDFanSuperTux** [SuperTux/supertux#1574]
SuperTux version: 0.6.2
This bug it's a little bit strange, one day i was playing SuperTux and i was creating levels and when killed a spiky and mrbomb togeter and the metal corpse of spiky slide in platform xD

This happens with the new recoil of the bomb
![Bug](https://user-images.githubusercontent.com/74196506/98558922-c6b96b80-2284-11eb-91f2-08a1c56ad421.PNG)
PD: The spiky was not there

Hope you can fix this bug in a future update =)

**Comment by LizzyBach** [comment]
What do you mean?

**Comment by Ordoviz** [comment]
Possible duplicate of #1227

**Comment by SalomonDFanSuperTux** [comment]
Yeah

**Comment by Semphriss** [comment]
If it is a duplicate of another issue (which is closed! :tada:), I will close this.
