### ISSUE TITLE
Waffelwüste - no map 

### ISSUE THREAD

**Issue by matstr-hue** [SuperTux/supertux#1579]
It's been a while after installing nightly download and noticed Waffelwüste has no map. The map had also lost all paths and I can move only to first spot.
![No map](https://user-images.githubusercontent.com/74267729/98728936-72081480-239a-11eb-9ee7-682535598b25.png)

**Comment by mrkubax10** [comment]
I have the same issue.

**Comment by serano01** [comment]
It seems to work if all files are copied in the main directory. Might be a workaround until I find an better solution.

**Comment by Busybody64** [comment]
You should reboot after enabling the addon.

I think that works.

**Comment by Vankata453** [comment]
Seems like the `worldmap.strf` tileset, this addon's worldmap uses, conflicts with the main tileset, which makes none of the tiles able to load. Renaming the tileset inside of the addon to `worldmap_desert.strf` (for example), and referencing the new tileset name in the map fixes the issue.

I would fix this, but I'm still confused as to which repository exactly is used to download addons from, and where I have to make the appropriate changes.
