### ISSUE TITLE
Wiki Pull Request: TODO page changes

### ISSUE THREAD

**Issue by Karkus476** [SuperTux/supertux#158]
If only GitHub would add wiki pull requests...
Link(to the only page I've changed): https://github.com/Karkus476/supertux/wiki/TODO

**Comment by Karkus476** [comment]
Does anyone object to me adding these changes?

**Comment by Hume2** [comment]
Did you changed all pages or only some of them?
If only some of them, then please thell me which, it will be much easier then.

**Comment by Karkus476** [comment]
The TODO page is the only page I've changed.

**Comment by Hume2** [comment]
It looks well, but I'd be careful about that and I'll wait for other opinions.

**Comment by Karkus476** [comment]
Sure.
