### ISSUE TITLE
Where a I?

### ISSUE THREAD

**Issue by matstr-hue** [SuperTux/supertux#1582]
In fortress level in Yeti's Revenge map after getting through epilepthic section you get to foggy area, but I don't know where I am nor see any living soul here or object, so you must get through this section blindly. In older updates you could at least see something.

Not only this! In secret boss level, where you fight a sea monster, the game crashes when you survive monsters attacks and allies drop Giga Crusher on the monster.
![Where am I](https://user-images.githubusercontent.com/74267729/98732616-ad591200-239f-11eb-9dde-6ac5569fa28d.png)

**Comment by Ordoviz** [comment]
You can find the mentioned level [here](https://github.com/SuperTux/addons-src/blob/master/niso-yetis-revenge/levels/yetis_revenge/Alls%20Well%20That%20Ends%20Well.stl). When I open it in the level editor or play it from the main menu, I can see lanterns in that section.
