### ISSUE TITLE
Make the `null` renderer effectively disable all video

### ISSUE THREAD

**Issue by Semphriss** [SuperTux/supertux#1583]
At the moment, SuperTux has the option to launch using multiple rendering engines, namely OpenGL 2.0, OpenGL 3.3, SDL, and one special `null`renderer, which is meant to disable vthe video system.

However, the `null` renderer only cancels _rendering_ operations; it will still attempt to e. g. create a window, resize it, etc.

Considering the arrival of networking, it makes sense to consider running SuperTux instances in headless environments (servers).

It would be useful to either adapt the null renderer to completely disable all video, or to add another option like `no-video` which would effectively disable any video-related operation.

**Comment by Zwatotem** [comment]
Yes, that could be benefitial for example for automated testing, and possibly for server-side Supertux in the future. As for implementation I think this should be its own thing, leaving null renderer as is.

**Comment by Semphriss** [comment]
Networking now has a `--headless` option which disables video completely and enables running on servers without GUI; I'm closing this issue now.
