### ISSUE TITLE
libretro port?

### ISSUE THREAD

**Issue by DartPower** [SuperTux/supertux#1596]
Hi there, i have a idea, you want to port to libretro?
This is will be cool, really :)

Check this also please :)
https://www.libretro.com/index.php/mission/
https://docs.libretro.com/development/cores/developing-cores/
https://www.libretro.com/index.php/powered-by-libretro/
https://docs.libretro.com/development/cores/opengl-cores/

**Comment by strikersh** [comment]
Supertux heavily rely on boost which isn't part of libretro-deps we will need a port of boost or support for c++20. Same goes for ports outside of Windows/Mac/Linux/BSD.

You could fork it and replace the boost dependencies 

see #1602

**Comment by Semphriss** [comment]
I'll close this issue as this isn't handled by us.
