### ISSUE TITLE
support for Korean translation and font setting error 

### ISSUE THREAD

**Issue by sooyeon73** [SuperTux/supertux#1597]
Hello,
In order to help Korean users use the supertux, I have completed additional modifications to the translation of .md files and incomplete Korean translation.

In addition, to solve the problem of broken fonts when setting the language to Korean on superertux, I have completed the addition of the Korean font file and the modification of the resources.cpp 

I'd appreciate if you check my repository : https://github.com/sooyeon73/supertux
thanks.

**Comment by Semphriss** [comment]
Normally, it should be fixed by #1963; closing, please open a new issue if the error persists.
