### ISSUE TITLE
New startup icon

### ISSUE THREAD

**Issue by brmbrmcar** [SuperTux/supertux#160]
The current one hasn't really been updated for a long time. It looks kinda old. And also, Tux is big before he has to go out saving Penny. Here is a potential updated version:
![supertux-256x256](https://cloud.githubusercontent.com/assets/14400196/10076997/411cb126-62d6-11e5-9b8b-8e6325d618ec.png)
It would need discussion.

**Comment by sydneyjd** [comment]
Yes, the logo is old, but its our trademark. Also, we are not going to even consider replacing it unless someone comes up with a new graphic themself. 
The way our team is atm, if you want it changed/fixed, you "fix" it yourself and open a pull request.
I’m not meaning to be rude, but that’s the position the we are in now.
