### ISSUE TITLE
Make swimming toggle-able?

### ISSUE THREAD

**Issue by erratic-c-programmer** [SuperTux/supertux#1607]
**SuperTux version:** 0.6.2 built from current remote master
**System information: Current Arch Linux**
##### Expected behavior
You should be able to toggle swimming

##### Actual behaviour
You can't

**Comment by erratic-c-programmer** [comment]
One irritating consequence is that you can't kill icecubes or anything that needs buttjumping underwater as once you jump underwater, you start swimming, and you can't buttjump anymore

**Comment by Rusty-Box** [comment]
I don't think it is mandatory to have them be beatable underwater via buttjump since they are still killable with a fireflower.
It would be different if there would be no other possible way to beat them aside buttjumping. Which is not the case here.

**Comment by erratic-c-programmer** [comment]
But what if Tux has an ice/air/earth/no flower? The some normally easily-beatable badguys (e.g. mrtree, *bomb,) would be harder to defeat and it would also be impossible to kick a snail.

**Comment by serano01** [comment]
To be honest, we're really in need of some underwater badguys, because Mr. Tree and co. shouldn't be used in swimming areas.

**Comment by Rusty-Box** [comment]
> But what if Tux has an ice/air/earth/no flower? The some normally easily-beatable badguys (e.g. mrtree, *bomb,) would be harder to defeat and it would also be impossible to kick a snail.

While depended on the level maker, usually there should be a fire flower available in levels that also feature swimming. Also, swimming in water already is toggle-able, since you can just place your water in a not-solid tilemap

**Comment by serano01** [comment]
I thought he meant toggle-able by the player, e.g. you're swimming, then you decide you don't want to, etc.

**Comment by Semphriss** [comment]
It seems logical to me to not include buttjumping underwater because it doesn't really make sense to groundpound underwater with the current physics we have.

A good alternative would be to make buttjumping the equivalent of Tux swimming at a certain speed; that is, when Tux accelerates up to a certain threshold underwater, collision with enemies are handled the same way as buttjumping.

**Comment by Semphriss** [comment]
I wouldn't encourage adding a button to not swim underwater, as it would be rather counterintuitive, would defeat the purpose of water, and would encourage poor level designs (we don't want LDers to design underwater sections made to be passed in non-swimming mode).

**Comment by erratic-c-programmer** [comment]
> It seems logical to me to not include buttjumping underwater because it doesn't really make sense to groundpound underwater with the current physics we have.
> 
> A good alternative would be to make buttjumping the equivalent of Tux swimming at a certain speed; that is, when Tux accelerates up to a certain threshold underwater, collision with enemies are handled the same way as buttjumping.

Ok, closing
