### ISSUE TITLE
Tux can climb sideways/upside-down

### ISSUE THREAD

**Issue by erratic-c-programmer** [SuperTux/supertux#1608]
**SuperTux version: 0.6.2 compiled from remote master**
**System information: Arch Linux**

##### Expected behavior
Tux should climb the ladder facing upwards

##### Actual behavior
When climbing after jumping out of the water, the angle is not reset

##### Steps to reproduce actual behavior
1. Go into the water
2. Jump out, and while flying out of the water press up on a ladder to climb it
3. ![Get this](https://user-images.githubusercontent.com/56342471/102075399-25a07080-3e41-11eb-8ded-5889813a2399.png)

**Comment by weluvgoatz** [comment]
Oh this was fixed a while ago, gonna close!
