### ISSUE TITLE
[Intel GPUs] [Intel UHD Graphics] Windows 10 - Not usable Graphic Output

### ISSUE THREAD

**Issue by samtrot** [SuperTux/supertux#1623]
**SuperTux version:**
0.6.2 64bit

**System information:** *(details about your kernel, operating system, or distribution)*
Windows 10
Intel Pentium 5405U
12GB RAM
Intel(R) UHD Graphics 610

##### Expected behavior
SuperTux runs with default configuration

##### Actual behavior
![grafik](https://user-images.githubusercontent.com/15930932/103215676-56d67180-4914-11eb-8774-bd582c043915.png)

##### Steps to reproduce actual behavior
Start from start menu

##### Additional debugging information
I read https://github.com/SuperTux/supertux/issues/1557 - I can start ST using "supertux2.exe --renderer sdl". Different to that issue, ST doesn't crash when using the default config.

**Comment by Semphriss** [comment]
This is a known bug - every few weeks we get various funny visual glitches with SuperTux running on OpenGL. To my knowledge, all cases involve Intel Graphics, although your system should support OpenGL 4.5 and SuperTux uses 3.3 core.

The usual tip is to make sure your drivers are up-to-date and update them if necessary. I'm not very positive it'll be enough, but just in case...

If that isn't enough, you may try with any device that has a non-Intel GPU. We aim to fix this issue with Intel Graphics, but don't wait after us, we've been searching around that for ages and haven't found anything yet.

**Comment by tobbi** [comment]
I've contacted Intel support regarding this problem. Relevant forum thread is here: https://community.intel.com/t5/Graphics/OpenGL-Graphics-issues-affecting-SuperTux-on-Intel-UHD-Graphics/m-p/1241832#M92938

**Comment by tobbi** [comment]
Intel Support has replied to my bug report. Could you please follow their instructions here?

https://community.intel.com/t5/Graphics/OpenGL-Graphics-issues-affecting-SuperTux-on-Intel-UHD-Graphics/m-p/1242165/emcs_t/S2h8ZW1haWx8dG9waWNfc3Vic2NyaXB0aW9ufEtKQlozRFQ5S01XNjBZfDEyNDIxNjV8U1VCU0NSSVBUSU9OU3xoSw#M92970


If possible, create an Intel Community account and reply to their request directly stating that you're one of the affected users.

**Comment by tobbi** [comment]
@samtrot Or, if you don't feel like creating an extra account for this, please reply here and I'll paste your answers into the thread.

**Comment by samtrot** [comment]
I am very sorry. I have created all the reports Intel requested. While creating the screen video, I noticed the issue does not last anymore. 

I have had a "functional update" of Win10. Maybe it is related to that.

**Comment by tobbi** [comment]
I'm gonna close the issue because a solution has been found. I contacted the other user suffering from this problem about it, but they weren't responsive so far.
