### ISSUE TITLE
Squirrel: Accessing the `Level` object throws an error

### ISSUE THREAD

**Issue by Semphriss** [SuperTux/supertux#1638]
**SuperTux version:** Latest @ master
**System information:** Ubuntu 18.04.3 LTS Linux 4.15.0-130-generic

---------------------------------------------------------

Playing any cutscene level to the end will print this error:

```Error waking VM: the index 'Level' does not exist```

And the level will fail to exit by itself.

**Comment by mrkubax10** [comment]
Tried to reproduce this issue in level "A New Location" but everything works normally.

**Comment by Semphriss** [comment]
Can't reproduce the error on `master` anymore; closing.
