### ISSUE TITLE
What is MenuStorage.cpp for?

### ISSUE THREAD

**Issue by Semphriss** [SuperTux/supertux#1646]
`src/supertux/menu/menu_storage.*pp`

This file is a singleton-like class to... instantiate menus. Does it have a purpose? Why doesn't the code just instantiate the menus directly, instead of using an enum and passing through a singleton?

**Comment by Grumbel** [comment]
It hides some implementation details of constructing a Menu and allows `MenuManage::set_menu()` to take a simple ID. But for most part it's simply an refactoring artifact, the Menu code started out with a bunch of lose global variables along time ago and that was just a class to bundle them up.

**Comment by Semphriss** [comment]
@Grumbel Is it fine if I remove it? I think it'd be cleaner to instantiate those menus directly (my recently added "ParticleEditorSaveAs" menu requires an argument), but I wanted to check if there was a need to keep it before I remove it, just in case...

**Comment by Grumbel** [comment]
I am not strictly opposed to it, but I don't see an immediate need for removing it either and it would be `Menu::add_submenu(const std::string& text, int submenu, int id)` uglier. You already have `MenuManager::set_menu() that takes a `std::unique_ptr<Menu>`  if necessary.

There are other aspects of the `Menu` code that I would consider in more need of improvement, e.g. `Menu::menu_action()` and the `MNID_` could all be replaced by lambdas and std::function.

**Comment by Semphriss** [comment]
I remember I once tried to implement a custom button with a callback, but I don't remember where, I only remember that I abandoned because the result was unstable.

Anyways, I'll add that on my to-do list, with the other code cleanups I planned doing sometime. I probably won't do it right away, but I'll try to see what's the cleanest way I could do it. I'll at least change `MenuStorage::create(MenuId menu_id)` to a static function :^)
