### ISSUE TITLE
The controls depend on the keyboard layout

### ISSUE THREAD

**Issue by andyun29** [SuperTux/supertux#1652]
**SuperTux version: 0.6.2. Installing from Flatpak.
**System information: Linux Mint 18.3 Sylvia

Expected behavior
The game automatically switches the keyboard to the layout in which the control keys were assigned.

Actual behavior
The controls depend on the keyboard layout. If I don't switch it before starting the game, then control is lost.

**Comment by tobbi** [comment]
I believe that switching the keyboard layout when starting SuperTux is much more confusing to the user than having keys map to their equivalent in a different layout. This isn't an issue for many users because keyboard layout is switched pretty rarely for most of them.
