### ISSUE TITLE
Revenge in Redmond tiles look wrong

### ISSUE THREAD

**Issue by HybridDog** [SuperTux/supertux#1654]
**SuperTux version:** supertux2 v0.6.2-605-g2edc75a88
**System information:** Lubuntu 18.04

##### Expected behavior

The snow tiles in Revenge in Redmond levels  are tileable and aligned

##### Actual behavior

![revenge_redmond](https://user-images.githubusercontent.com/3192173/105637030-802ee280-5e6b-11eb-8d9a-d9cd6c00b4e0.jpg)

##### Steps to reproduce actual behavior

Play the first level in Revenge in Redmond

**Comment by serano01** [comment]
Solved. https://github.com/SuperTux/supertux/commit/03063f628298cad6e5db9bfdc70981eebf7e54a0

**Comment by HybridDog** [comment]
Thanks
