### ISSUE TITLE
Falls block can't kill Tux on void

### ISSUE THREAD

**Issue by AndrePinheiroPT** [SuperTux/supertux#1657]
*Sorry for my bad english*

Hello developers.
Currently, I was doing a level when accidentally a find bug. The bug consists of the falling block that prevents Tux's death when he falls into the void.  Here is the video where I demonstrate the bug and the game version (nightly version).

[Video](https://youtu.be/DDSs_HrS8B8)

Thank you for your understanding.

**Comment by Semphriss** [comment]
This looks a lot like my swimming death-by-fallout prevention code. I'll investigate
