### ISSUE TITLE
Music doesn't always pause when level is paused

### ISSUE THREAD

**Issue by Vankata453** [SuperTux/supertux#1661]
**SuperTux version:** SuperTux v0.6.2
**System information:** Windows 10, Dell OptiPlex 980, Intel Core-i7 Processor (old generation), 12GB RAM, NVIDIA GeForce GT 730.

##### Expected behavior
When I pause a level at any time, the music pauses too.

##### Actual behavior
When a level is paused, the music sometimes pauses, sometimes it glitches out and it doesn't. [Demo](https://youtu.be/EL0jvh8KD6s)

##### Steps to reproduce actual behavior
Try to pause a level with music many times.
____________________________________________________________________________________________________________________________________

If other people have experienced this before and don't have a problem with it, then it's OK. This is just a suggestion of mine about a little detail I've personally experienced when playing the game. Can't wait to see more from SuperTux in the future! :)

**Comment by Semphriss** [comment]
I confirm this has happened to me too a lot of times. In fact, sometimes I tried to intentionally cause it to happen so I could just listen to the music :laughing: 

I'll investigate on that issue.
