### ISSUE TITLE
Path-following tilemaps cannot be enabled in the level editor

### ISSUE THREAD

**Issue by HybridDog** [SuperTux/supertux#1664]
**SuperTux version:** latest (b26de477e)
**System information:** Lubuntu 18.04

##### Expected behavior

The running checkbox should not be ignored for tilemaps.

##### Actual behavior

I check the "Running" checkbox in the tilemap settings and then click on "Ok". When I open the tilemap settings again, the checkbox is unchecked.
![tmp_screenshot_smaller](https://user-images.githubusercontent.com/3192173/107067503-a8a9cb80-67df-11eb-8719-6e0d7a026b22.png)

##### Steps to reproduce actual behavior

* Enter the level editor
* Add a tilemap, enable path-following in its settings and add a path for it
* Enable the "Running" checkbox in its settings

**Comment by Zwatotem** [comment]
Oh, so it's not me not knowing, how to do moving tilemap, it's actually a bug preventing me from doing so...

**Comment by Semphriss** [comment]
Problem source identified. For whatever reason, the Tilemap object has a duplicate m_running variable, instead of using the PathObject's walker variable. Will make a fix for it soon.
