### ISSUE TITLE
Ghosttree's root broadcast is above ground

### ISSUE THREAD

**Issue by SaintSynful** [SuperTux/supertux#1674]
SuperTux 0.6.2-657
Windows 10 Home, build 19041.804

##### Expected behavior
I'm assuming that the intended design was for Ghosttree's root attack to have a short broadcast underground before spiking upwards.

##### Actual behavior
It seems to be broadcasting above ground, and the hitbox of the broadcast kills the player before the attack ever happens. The root broadcast can also spawn entirely above ground wherever there are dips in terrain.

##### Steps to reproduce actual behavior
Play Ghosttree's Challenges level

**Comment by Busybody64** [comment]
I'm surprised this bug hasn't been fixed yet.

They could at least make it so it's harmless until the root actually pokes out.

**Comment by HybridDog** [comment]
On Apr 21, 2019, @Rusty-Box wrote "The ghost tree will be totally remade especially the way of how to defeat it.":
https://github.com/SuperTux/supertux/issues/1083#issuecomment-485249567

**Comment by weluvgoatz** [comment]
I'm pretty sure I fixed this in a recent commit, so I will close it now.
