### ISSUE TITLE
Screen goes white when tux gets coin (bullseye i686 SDL)

### ISSUE THREAD

**Issue by enigma9o7** [SuperTux/supertux#1676]
Just installed debian bullseye testing (Linux 5.10.3) on HP d530 Pentium 4 with integrated Intel 82865G GPU.  One reason I installed this distro so is for this newer supertux version, not many other distros fully supporting 32-bit software, and this game is one of the reasons to keep this old machine around.

Supertux 0.62 starts and appears to run fine, but when I jump to get a coin as soon as his head hits a coinbox, everything goes white. The same happens when touching a loose coin. Until a monster comes along and kills him (or I hit Esc), then all returns to normal.  Only OpenGL up to 1.3 is supported by this gpu so no other renderer to try besides the detected sdl.  

I tested with -renderer sdl on a virtual machine of same OS and it works fine, so it's something to do with the actual hardware or driver or something.  But didn't happen with older supertux version from ubuntu 18.04.

**Comment by Semphriss** [comment]
SuperTux only supports OpenGL 2.0 and 3.3, unfortunately. (The "opengl" option is actually OpenGL 3.3; you can see it on the main menu in the bottom-right corner of the screen)

If your system supports only up to OpenGL 1.3, only the SDL renderer will work properly.

**Comment by enigma9o7** [comment]
All of that is understood (and addressed in original post).  

If there's any further info or testing I can do or logs I should provide  provide I will.  But this is 100% repeatable and obviously makes game unplayable and I'm looking for solution...  

The only thing I can think to try myself is see if I can try an older version under this OS. I will look into that, perhaps I can figure out exactly what version it first broke or something if that would be helpful...

**Comment by Semphriss** [comment]
Unfortunately, rendering problems are a [well](https://github.com/SuperTux/supertux/issues/1531)-[known](https://github.com/SuperTux/supertux/issues/1623) [issue](https://github.com/SuperTux/supertux/issues/1557), in addition to problem concerning [lag](https://github.com/SuperTux/supertux/issues/1542) [getting](https://github.com/SuperTux/supertux/issues/1361) [significantly](https://github.com/SuperTux/supertux/issues/416) [greater](https://github.com/SuperTux/supertux/issues/1301) [in](https://github.com/SuperTux/supertux/issues/1147) [latest](https://github.com/SuperTux/supertux/issues/1145) [releases](https://github.com/SuperTux/supertux/issues/1051).

Problems tend to point towards the rendering engine; it will be revamped at some point.

**Comment by enigma9o7** [comment]
Thanks for the reply.  I took a look at the other issues you linked and the major difference I can tell is they were all on newer hardware attempting to use autodetected ogl3.3 all able to avoid their issues by switching to gl2 or sdl (which I assume is using gl1).  The only thing I can see in common with some of those threads is Intel made their CPU/GPU (like the majority of pcs) and they had some type of video problem and posted about it here ;)   

In my case, I started with sdl autodected, thus I am already using the legacy renderer and yet still having a problem.  I am not having any speed issues, as long as I don't get any coin boxes, everything is fast and responsive.  By the sounds of it in fact I assume it remains fast when I do hit the coinbox, but since the entire screen is white, I'm not 100% sure!

**Comment by Semphriss** [comment]
The error happens with the SDL renderer?

**Comment by enigma9o7** [comment]
Yes, note the topic or the original post where I state the machine only supports open gl 1.3.   I mentioned there is no other renderer available for this hardware to try.  I'm not sure how to state this any clearer.   Also note the topic mentions SDL, that is also a hint this is in regards to the sdl renderer.

**Comment by Zwatotem** [comment]
@enigma9o7 I had the same issue and remember that turning off the vsync helped, please try it and tell me, whether this worked for you.

**Comment by enigma9o7** [comment]
I just tried all three vsync settings, no difference.  I also spent a little more time playing to make sure it was just coinboxes, and its also regular coins too (and I will edit above to reflect that).  Any time he gets a coin the screen goes white; can restore video by hitting Esc.

**Comment by enigma9o7** [comment]
I booted back to old ubuntu 18.04 based os and installed Supertux 0.62 from ppa.  It doesn't have this issue.

So argh!  It's not the specific version number, its something about the bullseye package on my computer.  I will look forward to trying the nightly i386 appimage when it works, so far I've tried and first time was script error line #1, second time was exec format error....

**Comment by enigma9o7** [comment]
I was just about to post if I should email the bullseye package maintainer (since bullseye is about to release) but then I realized what I should so is actually build supertux from source myself and see if I have the same problem before I blame the packager.   Its just so weird it works under ubuntu but not bullseye to me.    So I'm gunna try building myself, wish me luck.

**Comment by Semphriss** [comment]
@enigma9o7 Any news about it? Did you succeed building SuperTux?

**Comment by enigma9o7** [comment]
Thanks for checking with me, I got back to it today.  Just built from git and works fine, does not have this issue.  only the debian bullseye package version.  Dunno.  This works for me, but perhaps other people on old hardware under debian i386 might run into this too?

![shot-2021-03-05_11-08-49](https://user-images.githubusercontent.com/30579733/110162650-dca6eb00-7da3-11eb-8ad6-535acad0d1f6.png)

**Comment by Semphriss** [comment]
Unfortunately we have no power on the Debian packages, only on the source code. But hey, glad it works :)
