### ISSUE TITLE
Change appearance of forest rocks

### ISSUE THREAD

**Issue by mbernard2** [SuperTux/supertux#1685]
Lately we decided to make rock tiles non-solid (#1609).

I found that confusing as they still looked solid to me (perhaps I was still used to playing this game with rocks being solid). The black border around the rock and the fact that it's somewhat bulky made me think it was something we could jump on :
![stone1](https://user-images.githubusercontent.com/14836881/110026977-6486e980-7cff-11eb-946b-1cdc47a9a821.png)

So I and thought maybe if we change their appearance to make them more "background-ish", like maybe remove the black halo or just re-draw them from the beginning since they're not really good looking after all...

But then I looked in `data/images/forest` and found a file named `rocks-forest.png` with much better-looking rocks. And none of them is currently used is any World 2 level !

In my opinion, they look much nicer than those old pixelated rocks.

I tried them out in _Walking Leaves_, to see how it turns out, and it looks good to me:
(I'm not a graphic designer so maybe they're not at the best possible place, but at least, it's an improvement.)

Before | After
--- | ---
![screenshot000005](https://user-images.githubusercontent.com/14836881/110027809-71580d00-7d00-11eb-800b-8a068e22138b.png) | ![screenshot000001](https://user-images.githubusercontent.com/14836881/110027824-774dee00-7d00-11eb-891a-92e15f4f9718.png)
![screenshot000006](https://user-images.githubusercontent.com/14836881/110027846-7e74fc00-7d00-11eb-924e-38563b7b6ceb.png) | ![screenshot000002](https://user-images.githubusercontent.com/14836881/110027863-82a11980-7d00-11eb-8b8f-ed8f30d188d3.png)
![screenshot000008](https://user-images.githubusercontent.com/14836881/110027882-8af95480-7d00-11eb-8f7a-979e56185f48.png) | ![screenshot000003](https://user-images.githubusercontent.com/14836881/110027902-90569f00-7d00-11eb-853a-65d4b90fc899.png)
![screenshot000009](https://user-images.githubusercontent.com/14836881/110027912-96e51680-7d00-11eb-86c2-bcc5ad3ce5f8.png) | ![screenshot000004](https://user-images.githubusercontent.com/14836881/110027925-9b113400-7d00-11eb-9223-7a548696f71e.png)

***

So, what do you think ? Should we change all levels to use the other rock variant ? And then delete the old sprite, or at least move it somewhere to make it clear it's deprecated so people won't use it by accident ?

**Comment by Semphriss** [comment]
This is exactly what these rocks were made for (graciously from @weluvgoatz :slightly_smiling_face:).

If you (or anyone else) would like to replace the old rocks with the new ones, go ahead!

**Comment by Alzter** [comment]
> This is exactly what these rocks were made for (graciously from @weluvgoatz 🙂).
> 
> If you (or anyone else) would like to replace the old rocks with the new ones, go ahead!

I'm all for making these rocks the utilized ones, I just thought I'd clarify that Jason (BlasterMaster) from the FreeGameDev forums made the sprites for these, not @weluvgoatz .

**Comment by weluvgoatz** [comment]
Yes, I only did the moss and snow textures, the rest of these very nice rocks are from Jason/BlasterMaster. ☺

**Comment by Rusty-Box** [comment]
These old rocks will get replaced by the new ones in the updated forest world levels. To not waste time we will keep the current rocks the way they are.
