### ISSUE TITLE
UndoManager generates excessive amounts of lag in the editor

### ISSUE THREAD

**Issue by Semphriss** [SuperTux/supertux#1688]
Currently, whenever a key or a mouse button is released, the UndoManager saves the entire level, regardless of whether or not something has actually changed.

With big levels, this can generate a small lag that significantly deteriorates the user experience, in addition to needlessly filling the undo manager with versions that contain no change at all.

I propose to change this to make it so it only the changes are pushed in the undo manager. The event would be called whenever an object is added, deleted or edited, and it would make sure something has changed before pushing on the undo stack. This will increase performance, reduce memory consumption and give and overall better experience.

**Comment by tobbi** [comment]
Problem is that I think the undo manager should also save property changes, which increases the variety of things the undo stack needs to hold.

**Comment by Semphriss** [comment]
I consider changes anything that calls non-const functions on any object inside the sector, on the sector, or on the level (though it might be less relevant to involve level and sector settings in the undo manager).

I haven't yet started redoing the undo manager, so I'm still open for any new thought, idea, suggestion, complaint, or tomato.

**Comment by tobbi** [comment]
🍅
