### ISSUE TITLE
"A fork in the road" 

### ISSUE THREAD

**Issue by Mathnerd314** [SuperTux/supertux#1694]
**SuperTux version:** 0.6.2-616-gdd472a4a1
**System information:** NixOS-unstable updated within the past few weeks

##### Expected behavior

Completing "A Fork in the Road" with one of the paths, then completing the other levels around the loop in a counter-clockwise direction, allows returning to "A Fork in the Road" from the other direction.

##### Actual behavior

Tux gets stuck on the road and doesn't return to "A Fork in the Road".

![image](https://user-images.githubusercontent.com/322214/110262762-f007b100-7f71-11eb-9918-ef27faab039d.png)

##### Steps to reproduce actual behavior

worldmapfinish() in the console, complete the lower path in "A Fork in the Road", try to circle around.

##### Proposed solution

The easiest way to fix this is to hide the whole road, so that Tux doesn't exit from the map. But then we need special unexplored-road tiles to show that a path exists.

**Comment by Semphriss** [comment]
That one's my bad.

As a short-term resolution, I might add boulders over the path of the closed routes to signify barring the road.

However, we should discuss about this as a team regarding how we handle splitting paths, whether we keep them at all, and how we organize our worldmaps.
