### ISSUE TITLE
Ambient sound persists after dying

### ISSUE THREAD

**Issue by HybridDog** [SuperTux/supertux#1703]
**SuperTux version:** supertux2 v0.6.2-695-gfee7bc58e
**System information:** Lubuntu 18.04

##### Expected behavior

The sound stops after dying

##### Actual behavior

When dying the ambient sound does not disappear.

##### Steps to reproduce actual behavior

In Toufik's Longway bridge level, enter the door, hear the saws and then die.
After respawning, the saw sound is still hearable. After entering the door now, two saw sounds are hearable.
Here's the level: [longway bridge.stl.zip](https://github.com/SuperTux/supertux/files/6149281/longway.bridge.stl.zip)

**Comment by Semphriss** [comment]
Analysis data: AmbientSounds also do not stop when pausing the game.

General information for whoever might want to repair AmbientSounds: they also have poor scripting capabilities and no option to disable looping.
