### ISSUE TITLE
Suggestion: Improve customisation of Dispensers

### ISSUE THREAD

**Issue by Semphriss** [SuperTux/supertux#1706]
Right now, dispensers can only dispense certain badguys to their default settings. It would be cool to allow dispensers to automatically set certain properties of what they dispense. For example, the list of badguys available from the submenu could display this badguy's properties.

Since it is possible to add multiple badguys of the same type in the list (I guess it's related to the likeliness of a certain badguy to spawn), it would be easy to make it so a certain badguy can spawn with different settings.

For the `name` property exposing objects to Squirrel, it could be interesting to expose to the name not an object, but an array of the objects that will be created. Each badguy in the list could have different names or all have the same name. The list would contain all the badguys currently alive in the game, in order from oldest to youngest,

**Comment by dantronik-markus** [comment]
The issue I'm having with this is that the dispenser takes only a list of badguy names. Customizing that to include different badguys could be difficult. Unless, maybe if we had template badguys that we included in that level and gave a name with their specific settings that don't get counted and then add those names to the dispenser settings.

**Comment by Semphriss** [comment]
Don't worry, I've done worse in my SuperTux development experience :^)

**Comment by tobbi** [comment]
The issue I'm having with this is that the dispenser takes only a list of badguy names. Customizing that to include different badguys could be difficult. Unless, maybe if we had template badguys that we included in that level and gave a name with their specific settings that don't get counted and then add those names to the dispenser settings.

**Comment by Busybody64** [comment]
This would be cool, yet VERY hard to code.

We should just start with allowing enemies to spawn with custom sprites, then we could try to allow it to spawn enemies that trigger scripts on death. (Which would DEFINITELY be buggy as heck, but would still be usable at least)
