### ISSUE TITLE
I cannot open the scripting console

### ISSUE THREAD

**Issue by HybridDog** [SuperTux/supertux#1715]
**SuperTux version:** latest (supertux2 v0.6.2-715-g2ddc09084)
**System information:** Lubuntu 18.04

##### Expected behavior

I start supertux2 with --developer, go into some level and then press `^`, `~` and `` ` `` on a German keyboard. According to the wiki, the scripting console should appear: https://github.com/SuperTux/supertux/wiki/Console

##### Actual behavior

Nothing happens when I try the suggested keys. The Cheat Menu works, so I assume that I set the --developer flag correctly.
A long time ago I had problems in the Level Editor where I couldn't easily write a number because the console appeared, so there was or is a way to open the console.

**Comment by Semphriss** [comment]
From the Main Menu, go in Options, then in Setup Keyboard, then check the value next to "Console".

![image](https://user-images.githubusercontent.com/66701383/113001975-59c54600-913f-11eb-9bb2-4549093b796b.png)

You can change the key the same way you change any other, by clicking and pressing a new key.

**Comment by HybridDog** [comment]
Thanks; I'm not sure why I overlooked this.
