### ISSUE TITLE
Feedback and suggestions for swimming

### ISSUE THREAD

**Issue by Narre** [SuperTux/supertux#1716]
The current swimming is really buggy, but the not-yet-pulled improved version in weluvgoatz's fork is fantastic, the hitbox is well centred, the controls feel great and the sprites aren't stuttering all over the place. However, I still want to give some feedback, and share my experiences with trying this mechanic out.

Firstly, I must say I would not change the sprites (I mean their behaviour, not necessarily the images) or the hitbox anymore, they seem near perfect as they are now (in the improved version)

**Some tweaks I would make** (but aren't strictly bugs)**:**

- Tux should only enter swimming mode if his entire hitbox is underwater (but exit only when none of it is), otherwise just walking in a few pixels deep water can produce some really funny (not in a good way) behaviour.
![shallowdance](https://user-images.githubusercontent.com/14074789/113198045-b9b60c80-9265-11eb-8a89-ad95a705eddd.gif)
- Powerups from top-bumped bonusblocks should fall downwards (like outside of the water) for consistency, and maybe even to the sides (if the space isn't occupied, of course).
![powerupbump](https://user-images.githubusercontent.com/14074789/113198071-c5093800-9265-11eb-95ca-29c662ee28bc.gif)
- Fire/ice bullets should shoot in the direction Tux is facing - not just left/right, but they should be calculated from Tux's rotation.
- Tux should bump off of bonusblocks when he empties them from below, otherwise he hits the block a bazillion times per second, making a horrendous noise.
![bonusbump](https://user-images.githubusercontent.com/14074789/113198132-d3efea80-9265-11eb-80a6-52df50076321.gif)
- Similarly, Tux should always jump at least a few pixels out of water when he reaches the top, otherwise just holding 'UP' will produce a buggy-looking behaviour and a horrendous noise.
![surfacedance](https://user-images.githubusercontent.com/14074789/113198163-e1a57000-9265-11eb-9410-2fbc25179dcf.gif)
- Tux should NOT revert to walking physics if at the bottom of a water patch, walking underwater just doesn't feel right, besides, it introduces problems with movement meant for out-of-water that doesn't do what it's supposed to underwater (e.g. backflipping or jumping) It also glitches out when big Tux touches the floor in a 1-high area.
- The current speed swimming system (holding JUMP) feels a lot like running used to in SuperTux 0.3.0 and prior. This is more of a subjective preference, but I think it would be better if JUMP only sped Tux up for about half a second, meaning that the player would have to tap JUMP repeatedly to maintain the high speed (kinda like JUMP = propel Tux), which makes sense since it is a similar [foot] movement to jumping. (edit: On second thought, I think I'm kinda starting to like it this way. It might just be because the system I described - which is implemented on master - is quite buggy, but I definitely think Tux moves too fast. Maybe this 'hyperspeed' should be reduced, so Tux would only be able to move this fast with an airflower, and only for a limited time - depending on the number of stacked flowers).

**A** (what I think is a) **bug:**

- For some reason, backflip sprite rotation stopped working when swimming was implemented. On master, the rotating will resume if Tux enters ghost mode while backflipping, on weluvgoatz/swimmingremake, it doesn't even do that. I'm not sure if this was intentional, but it certainly looks weird when Tux doesn't rotate.

**What is definitely a bug:**

- When Tux collects a powerup underwater, his hat dances all over the place. This is fixed by leaving and re-entering the water or just turning around.
- I'm not sure if this is the case in the current version of swimming on master (Tux's entire sprite kinda dances there), but it is definitely the case on weluvgoatz/swimmingremake.
![hatdance](https://user-images.githubusercontent.com/14074789/113198340-174a5900-9266-11eb-8d2a-4515359d6e8d.gif)

**Other suggestions** (not necessarily a part of the swimming mechanic, but closely related)**:**

- All flowers (aside from Earthflower, that can work the same as out of water), should behave slightly differently underwater as their out-of-water behaviour doesn't make sense in water. Suggestions:
- _-**fire** and **ice** flower_**:**
-Can work as normal, but the bullets should not.
-Ice bullets should melt after a few seconds, and so should frozen enemies (as liquid water is always above freezing).
-Fire bullets should be extinguished by water and enemies shouldn't burn (to prevent the fireflower from becoming completely useless underwater, I suggest the bullets can still be used to spam-kill enemies - something like 3 non-burning bullets in quick succession could kill the enemies).
-Under lava, icebullets shouldn't exist at all, and firebullets can work the same as in water because fire enemies that could potentially swim in lava would be fire-resistant anyway.
-Bullets that are shot outside of water but fall into it should do the same.
-Firebullets shot in water that fly out of it should not reignite as it wouldn't make any sense.
-Icebullets shot in water that fly out of it should not melt if they leave the water in time.
- _-**air**flower_**:**
-As far as I can tell, the airflower does NOT currently have any effect whatsoever underwater.
-Its increased speed should work similarly to out-of-water, but the gliding makes no sense (edit: or it could work the way I described higher up, in the other edit).
-Instead, the player should be able to use the airflower to make Tux jump out of water a lot higher, opening possibilities for shortcuts and secret areas using this mechanic.
- _-**earth**flower_**:**
-As I already wrote, the earthflower should work the same under and above water, however, the turning into stone mechanic currently only works if Tux is standing still. I think a way should be found so that Tux can also turn into stone while swimming (and possibly while in mid-air [discussed in #1527], which could work similarly)

**-Enemies:**

- Some underwater enemies are definitely needed, as land enemies don't make much sense underwater and the only usable obstacles are hurting tiles like spikes.
- Fish should not be removed as a lot of older levels use them, and they shouldn't just stay 'deprecated' forever. I suggest their behaviour be tweaked so that they don't disappear once underwater but rather swim about until it's time to jump out again. That way they will at least not be a pain in the butt to kill from within the water patch. Two possibilities I can think of right now are:
-The fish just goes a few tiles down (if possible), and propels itself upwards to make another jump.
-The fish generates a (random?) path through the neighbouring water tiles and swims it in a predetermined time.
- I won't brainstorm ideas for new underwater enemies, I'm sure there are people with better ideas than mine, and I think that, at least for the time being, a few underwater sprites for existing enemies would suffice (for example, I think someone creative could make a good underwater sprite for the Flying Snowball, the Ghoul or the Flame).
- On the note of creating new enemies by just changing sprites, I think it should be possible to determine whether an enemy is freezable/flammable in the sprite rather than deep in the game code.

So these are my thoughts and suggestions about swimming and related subjects. I'm not sure how easy or difficuly some of these things would be to implement (as even though I can code in C quite well, C++ is still pretty much uncharted territory for me). I hope I'm not spamming too much and that this feedback will come in useful.

**Comment by weluvgoatz** [comment]
I think the sprite bug is present in Tux as a whole, the hat sprite should either be set to the same frame as the body sprite or the body sprite should be reset when collecting a powerup I think.

**Comment by Narre** [comment]
You're actually right, funny I've never noticed that before :D. It's not that obvious when Tux is walking as opposed to swimming.

**Comment by weluvgoatz** [comment]
@Narre: I have made a few of your requested changes: powerups coming from bonus blocks are now consistent, the horrendous bonus block noise should be fixed, and bullets now shoot in the direction Tux faces! 

I still plan to make a few more changes, including fixing that hat bug and handling shallow water/water edges better.  Thank you for your feedback!

**Comment by Rusty-Box** [comment]
I think this issue can be closed?

**Comment by Narre** [comment]
I think so, as the swimming revamp is now done and the small mostly off-topic suggestions can be discussed anywhere when the time is right. I'm closing this now.
