### ISSUE TITLE
Investigate travis build issue of glbinding on clang

### ISSUE THREAD

**Issue by tobbi** [SuperTux/supertux#172]
When we try to build glbinding using clang on the travis build machines, there's a compiler error, mainly because, for some reason, it can't find the header files.

Build log:
http://pastebin.com/Uy0uGcUR (sorry for the bad formatting)

building glbinding works fine using GCC.

**Comment by tobbi** [comment]
travis.yml code:
https://github.com/SuperTux/supertux/blob/master/.travis.yml#L57

**Comment by tobbi** [comment]
@scheibel Would you know, by any chance, why this yields a build error? You can view the complete log here (not sure for how long, though)
https://s3.amazonaws.com/archive.travis-ci.org/jobs/83451300/log.txt

**Comment by tobbi** [comment]
This is very likely fixed with a recent commit that I made. It can now find glbinding on all configurations and build with it.

**Comment by scheibel** [comment]
Seems like I'm a bit late but I had a look at the two logs anyway.
The logs shows that the compilation process tries to compile the source files using c instead of c++(11) which is pretty strange.

**Comment by tobbi** [comment]
Hmm, no problem. We keep getting a different error now:
https://travis-ci.org/SuperTux/supertux/jobs/95462116#L2069

It only occurs on clang, that's why I am a bit confused. Any idea?
