### ISSUE TITLE
Suggestion: Groundpounding on trampolines should do a high jump

### ISSUE THREAD

**Issue by Semphriss** [SuperTux/supertux#1724]
### The issue

Trampolines require holding the jump key to perform high bounces. With the air flower, this clashes with the gliding ability, which often triggers right above the trampoline, delaying the excepted bounce by a short but annoying amount of time, which becomes an even greater problem when moving horizontally at the same time and Tux ends up missing the platform.

### The proposed solution

Groundpounding on trampolines should also result in a high jump, similar to holding space. This seems intuitive enough (more force downwards on a trampoline will give more momentum upwards) and easy to execute. This would be in addition to holding space, as I see no need to remove that way of working.

I'm leaving this issue open as a request for comments, feedback, concerns, propositions and other thoughts from both the team and the public.

**Comment by Alzter** [comment]
I like this idea as buttjumping on trampolines currently feels underwhelming

**Comment by Guih48** [comment]
This is a good idea, but it's makes many levels too easy, so i would suggest a new trampoline (or just bump block?) type that if you ground-pound it launches you high.

**Comment by mrkubax10** [comment]
Added in #1772
