### ISSUE TITLE
Weird bug with Krosh

### ISSUE THREAD

**Issue by brmbrmcar** [SuperTux/supertux#173]
When two Kroshes are placed like this, Tux vibrates violently.
![screenshot from 2015-10-04 16 42 04](https://cloud.githubusercontent.com/assets/14400196/10268665/870d65a2-6ab7-11e5-81e4-789e347d6088.png)

**Comment by Hume2** [comment]
This is now considered as poor level design, because fixing this bug caused another bug. Valid topic: https://github.com/SuperTux/addons/issues/17
