### ISSUE TITLE
Rotate Tux sprite according to slope's angle degree

### ISSUE THREAD

**Issue by CeIestiaI** [SuperTux/supertux#1734]
Suggestion: When tux goes up a steep slope, he is angled to the slope's angle degree, basically diagonal, when he goes up it, same for other badguys, same when he goes down a slope. it may require alot of frames though

**Comment by Semphriss** [comment]
![image](https://user-images.githubusercontent.com/66701383/116004335-47b8b500-a5d0-11eb-81fa-29ef50b6fe61.png)

Doesn't look very natural imo... Standing like this, he looks like he should be falling...

Plus, how would it look like when Tux jumps? Would he jump at an angle? (Which I advise against, it's difficult to handle and kinda counter-intuitive) Would he still jump upwards? If so, what would happen to its sprite? Would it rotate instantly?

**Comment by tobbi** [comment]
https://user-images.githubusercontent.com/583169/116005470-553d6180-a607-11eb-9145-03898bd0967c.mp4

**Comment by Mathnerd314** [comment]
Penguins always are mostly upright, regardless of whether they're on a slope. What really changes are the bent ankles and a slight lean *towards* the slope (i.e. in the opposite direction from the picture in https://github.com/SuperTux/supertux/issues/1734#issuecomment-826366194). With a really steep slope they might start using the beak - in the video it doesn't look like it works, but it would be interesting to add an animation for it.

[BBC Penguins climbing video](https://www.youtube.com/watch?v=uh_jsNL6d_c)

**Comment by Rusty-Box** [comment]
Closing this as this is not going to happen.
