### ISSUE TITLE
version numbers missing on macOS

### ISSUE THREAD

**Issue by core-code** [SuperTux/supertux#1745]
i've downloaded version 0.6.2 but when selecting it in the Finder it didn't display any version information

both the `CFBundleVersion` and the `CFBundleShortVersionString` entries in your `Info.plist` file are missing

all macOS apps are expected to contain version information

<img width="249" alt="Screenshot 2021-05-06 at 17 49 54" src="https://user-images.githubusercontent.com/1261954/117328159-a8c76f00-ae93-11eb-8069-0f89a2e5ec71.png">

**Comment by core-code** [comment]
this is a regression. version numbers were present at least in your 0.1.3, 0.3.0 and 0.3.1 releases.

**Comment by tobbi** [comment]
Finally fixed with a6f7b48e2ccf7d3084820a53a694251bac274552

**Comment by core-code** [comment]
thanks!
