### ISSUE TITLE
New worldmaps should use 0 as their default tile

### ISSUE THREAD

**Issue by Rusty-Box** [SuperTux/supertux#1751]
When you create a new worldmap its tilemaps generate with the tile ID 9. This is due to the fact that it still useses the deprecated `worldmap.strf` as default instead of `ice_world.strf`. There the tile ID 9 is used for the blue water which is why it was chosen.

Worldmaps should always use `ice_world.strf` by default and generate new tilemaps with tile ID 0.

**Comment by Laksh61** [comment]
[1760](url)

**Comment by Laksh61** [comment]
[#1760](url)

**Comment by Laksh61** [comment]
[#1760 ](url)

**Comment by tobbi** [comment]
You do mean *.strf, right?

**Comment by Rusty-Box** [comment]
> 
> 
> You do mean *.strf, right?

Oh snap! Yeah you're right. My bad :P

**Comment by Busybody64** [comment]
I think it should still be the water instead of ID 0, So you don't have to manually add the water yourself.

I get your point, though.

**Comment by Rusty-Box** [comment]
@Busybody64 Uhm, I’d be against this for the fact that a worldmap only starts with one solid tilemap which is more relevant to pathing so you would have to add a new layer and fill the water in there anyways

**Comment by Busybody64** [comment]
... Oh yeah, I forgot about that! Sorry about that.

**Comment by Rusty-Box** [comment]
Actually, who said worldmaps only get one tilemap when firstly created… levels don’t so why not worldmaps too

**Comment by Guih48** [comment]
> Actually, who said worldmaps only get one tilemap when firstly created… levels don’t so why not worldmaps too

Yes the two wordmap tilesets is very confusing and time constuming switching they. Why we can't merge theese (in game's directory the two tilemap can stay for backwards compatibility but for new worldmaps would be good if could use the merged one for default)?

**Comment by Semphriss** [comment]
Fixed with #1925; closing
