### ISSUE TITLE
GLM changes cause compilation errors, this time on Windows

### ISSUE THREAD

**Issue by weluvgoatz** [SuperTux/supertux#1754]
**SuperTux version:** Current master commit
**System information:** Windows 10

##### Expected behavior

GLM doesn't cause an error in my compilation of the game.

##### Actual behavior

It errors like this (I was running a similar command to the person who reported a similar issue earlier):

`CMake Error at C:/Users/[User]/vcpkg/scripts/buildsystems/vcpkg.cmake:454 (_add_executable):                                         
Target "supertux2" links to target "glm::glm" but the target was not found.                                                                  
Perhaps a find_package() call is missing for an IMPORTED target, or an                                                                       
ALIAS target is missing?

Call Stack (most recent call first):
CMakeLists.txt:891 (add_executable)`

GLM is also reported as found an installed.

The only reason I am reporting this as a separate issue is because the changes of PR #1753 do not work when I use them, but that PR was made for a different operating system, so separate changes will likely be needed.  If this issue becomes redundant or too similar to the other one feel free to close it.

**Comment by Grumbel** [comment]
Fixed in 182dd5f3c0a1145a37963a6c5cd63f5d0777d622
