### ISSUE TITLE
 issue with badguys 

### ISSUE THREAD

**Issue by Laksh61** [SuperTux/supertux#1760]
**SuperTux version:0.6.2 not the nightys**
**more information:** *(note:it is badguy issue )*

##### behavior:
badguy liveing in lava

##### Guidelines for reporting issues

- [x] I have read <https://github.com/SuperTux/supertux/blob/master/CONTRIBUTING.md#bug-reports>.
- [x] I verified this isn't an issue that's already been reported.
- [x] This report only includes details about **one** (1) issue, feature request or topic.
- [x] I am not creating supertux ,I am supertux player
- [ ] If I make a mistake while submitting this report I will use the edit feature instead of closing this issue and opening a new one.
- [ ] This issue is **not** about wrong translations (use Transifex for those), or anything unsupported (e.g. third-party add-ons).
- [x] Once you're done, please remove the section 'Guidelines for reporting issues', the 'Additional debugging information' if it is empty, and any text in *italic font*.
![47585432982qw](https://user-images.githubusercontent.com/83761365/121497740-609eed80-c9f9-11eb-9cd7-56970e22f22d.jpg)
- [x] Once you're done, check for new

**Comment by Laksh61** [comment]
when the badguy is in the lava it is not dead!

**Comment by Laksh61** [comment]
this is true

**Comment by Laksh61** [comment]
this issue is in supertux version: 0.6.2

**Comment by Laksh61** [comment]
I use windows

**Comment by Laksh61** [comment]
fix it

**Comment by Laksh61** [comment]
> guys?where are you all?

**Comment by Laksh61** [comment]
****guys?where are you all?

**Comment by Laksh61** [comment]
**guys?where are you all?**

**Comment by Laksh61** [comment]
### guys?where are you all?

**Comment by Laksh61** [comment]
_gi

**Comment by Laksh61** [comment]
![screenshot000076](https://user-images.githubusercontent.com/83761365/121358193-09910e00-c950-11eb-8416-19f4ea99f4c3.png)
@Laksh61

**Comment by Laksh61** [comment]
![screenshot000092](https://user-images.githubusercontent.com/83761365/121360939-79a09380-c952-11eb-990c-cf98eae76189.png)
y levels

**Comment by Laksh61** [comment]
the issue
![issue](https://user-images.githubusercontent.com/83761365/121361812-3db9fe00-c953-11eb-8798-97adced4cfb3.jpg)

**Comment by Laksh61** [comment]
after tux kills a badguy,then it only kill it
![Uploading 47585432982qw.jpg…]()

**Comment by Laksh61** [comment]
https://github.com/SuperTux/supertux/issues/1760#issuecomment-857689411

**Comment by Laksh61** [comment]
after tux kills a badguy,then it only kill it
![47585432982qw](https://user-images.githubusercontent.com/83761365/121362912-1b74b000-c954-11eb-9d89-8b87eacb7a69.jpg)

**Comment by Laksh61** [comment]
https://github.com/SuperTux/supertux/issues/1760#issuecomment-857597153

**Comment by Rusty-Box** [comment]
Have you set the tilemap that includes the lava tiles to solid?

**Comment by Laksh61** [comment]
yes

**Comment by Laksh61** [comment]
but fix the badguy please.

**Comment by Laksh61** [comment]
- [ ] but fix the badguy please.

**Comment by Laksh61** [comment]
lava tiles are solid

**Comment by Laksh61** [comment]
yes

**Comment by Laksh61** [comment]
the lava is soild

**Comment by Laksh61** [comment]
> 
> 
> the lava is soild

go and read it

**Comment by Laksh61** [comment]
the issue is in all badguys!

**Comment by Laksh61** [comment]
I will send you a viido

**Comment by Laksh61** [comment]
### please wait ......

**Comment by Laksh61** [comment]
**you can look at this and fix it**
https://github.com/SuperTux/supertux/issues/1760#issuecomment-857686703

**Comment by Laksh61** [comment]
https://github.com/SuperTux/supertux/labels/help%20wanted

**Comment by Laksh61** [comment]
sorry I am trying to send vidos

**Comment by Laksh61** [comment]
`ty`

**Comment by Laksh61** [comment]
if you have the same issue you can fix it

**Comment by Laksh61** [comment]
or you close it

**Comment by Laksh61** [comment]
- it is open

**Comment by Laksh61** [comment]
- [ ] keep it open if you have the same issue you can fix it only if you have it or you just close it is only if you don't have the issue

**Comment by Laksh61** [comment]
- [ ] If I make a mistake I will close this issue

**Comment by Laksh61** [comment]
1. fix it and notify me
2. go and close it without doing a comment
and it's done!

**Comment by Laksh61** [comment]
> ?
the lava is soild

**Comment by Laksh61** [comment]
`the lava is soild`

**Comment by Laksh61** [comment]
_the lava is soild_

**Comment by Laksh61** [comment]
> 
> 
> **SuperTux version:0.6.2 not the nightys**
> **more information:** _(note:it is badguy issue )_
> ##### Expected behavior:
> 
> I don't know
> ##### behavior:
> 
> badguy liveing in lava
> for more information click 1761
> #1761 1
> ##### Guidelines for reporting issues
> 
>     * [x]  I have read https://github.com/SuperTux/supertux/blob/master/CONTRIBUTING.md#bug-reports.
> 
>     * [x]  I verified this isn't an issue that's already been reported.
> 
>     * [x]  This report only includes details about **one** (1) issue, feature request or topic.
> 
>     * [ ]  If I make a mistake while submitting this report I will use the edit feature instead of closing this issue and opening a new one.
> 
>     * [ ]  This issue is **not** about wrong translations (use Transifex for those), or anything unsupported (e.g. third-party add-ons).
> 
>     * [x]  Once you're done, please remove the section 'Guidelines for reporting issues', the 'Additional debugging information' if it is empty, and any text in _italic font_.
>       ![47585432982qw](https://user-images.githubusercontent.com/83761365/121497740-609eed80-c9f9-11eb-9cd7-56970e22f22d.jpg)
> 
>     * [x]  Once you're done, check for new

- check also abut these

**Comment by Laksh61** [comment]
I can show you:
![walk-6](https://user-images.githubusercontent.com/83761365/121519391-4b34be00-ca0f-11eb-8e32-049ccde98bce.png)
![walk-5](https://user-images.githubusercontent.com/83761365/121519391-4b34be00-ca0f-11eb-8e32-049ccde98bce.png)

**Comment by Laksh61** [comment]
![buttjump-0](https://user-images.githubusercontent.com/83761365/121520257-56d4b480-ca10-11eb-9539-8b1e6c6672b7.png)
![buttjump-1](https://user-images.githubusercontent.com/83761365/121520257-56d4b480-ca10-11eb-9539-8b1e6c6672b7.png)
![buttjump-3](https://user-images.githubusercontent.com/83761365/121520257-56d4b480-ca10-11eb-9539-8b1e6c6672b7.png)
![buttjump-4](https://user-images.githubusercontent.com/83761365/121520257-56d4b480-ca10-11eb-9539-8b1e6c6672b7.png)

**Comment by Laksh61** [comment]
- [x] don't touch hidden comment.

**Comment by Laksh61** [comment]
Sorry my son by mistake has send the email.

**Comment by Laksh61** [comment]
no spam

**Comment by Laksh61** [comment]
[tux strikes back 2.zip](https://github.com/SuperTux/supertux/files/6637989/tux.strikes.back.2.zip)
and the link.but keep in mend so leves are lost.

**Comment by Laksh61** [comment]
use level editer and click on senrol world you'll get levels ,click on small castle.

**Comment by Laksh61** [comment]
![left-0](https://user-images.githubusercontent.com/83761365/121681404-67506200-cad8-11eb-817a-cd17f59e5a28.png)
see I don't use nighty builds.

**Comment by Laksh61** [comment]
see I don't use nighty builds.
![gmelting-0](https://user-images.githubusercontent.com/83761365/121681794-daf26f00-cad8-11eb-833e-ebadd13fa82f.png)
![walking-0](https://user-images.githubusercontent.com/83761365/121681794-daf26f00-cad8-11eb-833e-ebadd13fa82f.png)

**Comment by Laksh61** [comment]
if you don't find it tell me

**Comment by Laksh61** [comment]
https://githu.com/SuperTux/supertux/issues/1760#issuecomment-859536829

**Comment by Laksh61** [comment]
👍 all best?

**Comment by Laksh61** [comment]
if you want cheats:then go in users then go to whatever your name is then go to appdata then go to supertux you will find config click on it and open with notepade.this is for people who don't use cheat of supertux

**Comment by weluvgoatz** [comment]
What are you asking now? I still don't understand your issue...

**Comment by Laksh61** [comment]
the issue isin badguys see
![47585432982qw](https://user-images.githubusercontent.com/83761365/121763593-ea1a0100-cb5a-11eb-89c0-9a9185647188.jpg)

**Comment by Laksh61** [comment]
you can go to @Laksh61

**Comment by Laksh61** [comment]
@SuperTux-bot

**Comment by Laksh61** [comment]
> 
> 
> Can you please submit a test level for this?
> And don't spam this issue, please?

### done tobbi

**Comment by tobbi** [comment]
Which of the levels is the Small Castle level?

**Comment by Laksh61** [comment]
level 73

**Comment by Laksh61** [comment]
done?

**Comment by RandomPenguin1778** [comment]
This might be a glitch .

**Comment by RandomPenguin1778** [comment]
is this a glitch ?

**Comment by weluvgoatz** [comment]
This is the most commented issue now...
