### ISSUE TITLE
supertux not responing

### ISSUE THREAD

**Issue by Laksh61** [SuperTux/supertux#1761]
**SuperTux version:**
**System information:** *(windows user ,useing 64 bit)*

##### Guidelines for reporting issues

- [x] I have read <https://github.com/SuperTux/supertux/blob/master/CONTRIBUTING.md#bug-reports>.
- [ ] I verified this isn't an issue that's already been reported.
- [ ] This report only includes details about **one** (1) issue, feature request or topic.
- [x] If I make a mistake while submitting this report I will use the edit feature instead of closing this issue and opening a new one.
- [ ] This issue is **not** about wrong translations (use Transifex for those), or anything unsupported (e.g. third-party add-ons).
- [x] Once you're done, please remove the section 'Guidelines for reporting issues', the 'Additional debugging information' if it is empty, and any text in *italic font*.

**Comment by Laksh61** [comment]
it is not at all responding

**Comment by Laksh61** [comment]
please fix it

**Comment by Laksh61** [comment]
> 
> 
> **SuperTux version:**
> **System information:** _(details about your kernel, operating system, or distribution)_
> ##### Actual behavior not responing
> ##### Steps to reproduce actual behavior
> ##### Guidelines for reporting issues
> 
>     * [x]  I have read https://github.com/SuperTux/supertux/blob/master/CONTRIBUTING.md#bug-reports.
> 
>     * [ ]  I verified this isn't an issue that's already been reported.
> 
>     * [ ]  This report only includes details about **one** (1) issue, feature request or topic.
> 
>     * [ ]  If I make a mistake while submitting this report I will use the edit feature instead of closing this issue and opening a new one.
> 
>     * [ ]  This issue is **not** about wrong translations (use Transifex for those), or anything unsupported (e.g. third-party add-ons).
> 
>     * [ ]  Once you're done, please remove the section 'Guidelines for reporting issues', the 'Additional debugging information' if it is empty, and any text in _italic font_.

**Comment by mrkubax10** [comment]
You didn't provide informations about for example: when it's not responding, console output, system information, SuperTux version

**Comment by Laksh61** [comment]
when I click a level some levels their don't respond ,these levels show black screen.

**Comment by Laksh61** [comment]
console dose not help me to get out of the issue!

**Comment by Laksh61** [comment]
[1760](url)

**Comment by Laksh61** [comment]
also when I click a some levels their don't respond ,these levels show after some minuites those levels frezze then I prees ctri+alt+delete to close it

**Comment by Laksh61** [comment]
@Rusty-Box 
@tobbi 
please fix

**Comment by mrkubax10** [comment]
please stop spamming

**Comment by Laksh61** [comment]
ok

**Comment by Laksh61** [comment]
ok
