### ISSUE TITLE
Locale not being set causes game to crash

### ISSUE THREAD

**Issue by 1sra3l** [SuperTux/supertux#1768]
**SuperTux version:**
0.6.2
**System information:** *(details about your kernel, operating system, or distribution)*
GNU Arch Linux (up to date)
5.12.12-arch1-1 kernel
##### Expected behavior
To play a rad video game
##### Actual behavior
It crashes instantly with a vague indication of locale being unset as the reason for failure
##### Steps to reproduce actual behavior
On a new system do not set your locale via running locale-gen, etc..
install and run supertux
**CRASH**
run locale-gen and try again.
play for hours.
##### Additional debugging information
This might be in this code:
https://github.com/SuperTux/supertux/blob/master/src/supertux/main.cpp#L153
particularly in the `else` portion, though I am unfamiliar with all your libraries you are using
```
// OOPS we set it to BLANK!?!?!?!?!?
tinygettext::Language language = tinygettext::Language::from_spec( locale->lang?locale->lang:"", locale->country?locale->country:"", locale->variant?locale->variant:"");
```
I think choosing some sort of English as a generic default would stop the random crash and fix this bug, though again I am unfamiliar with your libraries.

**Comment by mrkubax10** [comment]
Could you replace line 162 with `tinygettext::Language language = tinygettext::Language::from_spec( locale->lang?locale->lang:"en", locale->country?locale->country:"US", locale->variant?locale->variant:"UTF-8");` and check if it is still crashing? I would do this myself but I don't have access to fresh Arch Linux installation.

**Comment by 1sra3l** [comment]
Ok, I remembered I had a broken laptop I could use for it!  I installed arch without generating the correct locale, installed all the build stuff, and edited the line...

Now I am encountering an error
`X connection to :0 broken (explicit kill or server shutdown)`
I am not sure what I am missing
```
$env
DISPLAY=:0
XAUTHORITY=/tmp/xauth-1000-_00
```
I am absolutely running X (KDE plasma).  I've even tried running it using Dolphin's built-in terminal.  Can you help me find out what code checks for this, or what cmake compile flags/env variables I may need to get this building on Arch

**Comment by mrkubax10** [comment]
I think this error is not related to locale issue

**Comment by 1sra3l** [comment]
yes @mrkubax10 but I need to be able to get it to run after compiling it, in order to test the fix, so the game can be patched.
I need to know what **source code files** to look in.

Or, if I am missing some sort of `cmake` flag (your CmakeLists.txt is over 1200 lines long), or if I need to configure it some other way to fix this issue, I'd be ready to test the fix.

Sorry if I was confusing the first time.

Linux uses kernel modules for graphics, and mine uses the latest Kernel available.  All modules are built for that specific Kernel, I am not sure it is possible to have 'out of date' drivers in this manner, since the drivers are rebuilt for the kernel release.


It could be I need some specific X11 library that I need to install, or something else perhaps?  I have looked at the [WIKI](https://github.com/SuperTux/supertux/wiki/Building#dependencies) and see nothing related to X as a dependency at all.  Where in the code are you looking for X in the first place?  If I could look at the code, I might be able to figure out why it is not running now...

**Comment by 1sra3l** [comment]
@mrkubax10 if you don't have any ideas, I'd say that you might as well give sane defaults, I personally think it is the best way to go either way.

**Comment by mrkubax10** [comment]
You don't need any additional CMake flags. You can try starting with `--renderer=sdl`

**Comment by 1sra3l** [comment]
@mrkubax10 thank you so much!  That was what I needed to get it to run!
The game ran without issue, that definitely fixes the issue!  If you commit that minor fix this error will be taken care of!  Thanks for your hard work!
