### ISSUE TITLE
SuperTux text story level not working !

### ISSUE THREAD

**Issue by ghost** [SuperTux/supertux#1773]
Hi , I wanted to make a text story level . i did as the SuperTux instructions said to make a scrolling text story level . but after i launched the level in SuperTux and it exits . 

Operating System : Microsoft Windows 20 20H2

**Comment by mrkubax10** [comment]
Could you send video showing issue?

**Comment by RandomPenguin1778** [comment]
Ok

**Comment by RandomPenguin1778** [comment]
Link for video - https://drive.google.com/file/d/134pn4rHu60TYTEEZ-kLPecVfHYTKX1R1/view?usp=sharing

**Comment by mrkubax10** [comment]
Maybe empty name is problem here

**Comment by RandomPenguin1778** [comment]
Ok, Thanks

**Comment by Semphriss** [comment]
It seems that this issue was resolved; if not, please open a new issue with the details.
