### ISSUE TITLE
Implement objects sticking to solids

### ISSUE THREAD

**Issue by weluvgoatz** [SuperTux/supertux#1782]
In the recent improvements to moving objects, the movement from the moving object is applied to those who stand on it. It would be interesting to add a similar thing but for the sides and bottom of the moving object.  This would only apply to objects with a set "sticky" attribute, and would simulate sticking objects to things.
  This could apply to dart traps, bumpers, levers, the upcoming crystal shards, and other objects who currently do not stick to the sides of solids and instead simply stand by themselves, which produces unexpected behavior.

**Comment by mrkubax10** [comment]
My idea to implement this is have struct:
```cpp
struct StickedObject
{
  MovingSprite* m_sprite;
  Vector m_point;
}
```
and then additional field `std::vector<StickedObject> m_sticked_objects` in `MovingSprite` then iterate over this vector and update `MovingSprite`s position this way (pseudocode):
`m_sticked_objects[i].m_sprite->set_pos(get_pos()+m_sticked_objects[i].m_point)`
