### ISSUE TITLE
Need more oranges !!!

### ISSUE THREAD

**Issue by Misterjo** [SuperTux/supertux#1784]
**SuperTux version:**
**System information:** *(details about your kernel, operating system, or distribution)*

##### Additional debugging information

*If available, please attach a backtrace of a crash (you can get one using GDB or another debugger), or a core dump. If you're on GNU/Linux and your distro is using systemd, it's highly likely that a core dump is available using `coredumpctl(1)`.
If the issue only occurs in a custom level, please attach that too.*

##### Guidelines for reporting issues

n0megalul

**Comment by SaschaAlex** [comment]
![image](https://user-images.githubusercontent.com/36684458/124818734-6543bc80-df39-11eb-9651-a80b154cb33a.png)

**Comment by Misterjo** [comment]
![](https://cdn.discordapp.com/attachments/862410074600243240/862417317530566696/image0.png)

**Comment by Rusty-Box** [comment]
Please do not use issues for jokes and such! That is not what they are for.

**Comment by Misterjo** [comment]
> Please do not use issues for jokes and such! That is not what they are for.

Thank you very much for fixing this grave issue :)
