### ISSUE TITLE
I can't download supertux nightly version !

### ISSUE THREAD

**Issue by RandomPenguin1778** [SuperTux/supertux#1793]
Dear SuperTux team,

I decided to check the nightly version of supertux . so i gone to download.supertux.org and clicked the download link .  but it bring an xml file saying that the access is denied . please help

**Comment by Semphriss** [comment]
It is a known issue, the nightly downloads for Windows are broken.

In the meantime, you can download nightlies directly from GitHub:
1. Go in the "Code" section: 

![image](https://user-images.githubusercontent.com/66701383/126044751-3f86256a-eea5-446f-9058-34f851910021.png)

----------

2. Just below, click on the red "X" (Or the green check):

![image](https://user-images.githubusercontent.com/66701383/126044768-e478e709-a025-4b67-8ce5-3dd717627fd9.png)

----------

3. Find any that starts with "main" and click "details":

![image](https://user-images.githubusercontent.com/66701383/126044790-51df677e-538d-474b-849e-774872d256e2.png)

----------

4. Look at the top, and towards the right, click "Artifacts" (ignore the number if it's different):

![image](https://user-images.githubusercontent.com/66701383/126044802-59077221-4823-4537-9478-9df93b1feb66.png)

----------

5. Find the link that starts with "windows-**x64**-Release" if you are on **64-bit**, or "windows-**x86**-Release"" if you are on **32-bit**.

![image](https://user-images.githubusercontent.com/66701383/126044850-8d63e3f9-0e05-4375-9f69-3f8eabb9043b.png)

----------

6. Your download will start:

![image](https://user-images.githubusercontent.com/66701383/126044873-357240d4-36a3-47ac-97b6-b7275f6077c0.png)

**Comment by RandomPenguin1778** [comment]
thanks !
