### ISSUE TITLE
No audio supertux

### ISSUE THREAD

**Issue by isidoro-80** [SuperTux/supertux#1803]
Hello i have raspbian e retropie 4.7 in raspberry 4 4 gb. I install supertux but i haven't audio. I post error. Version supertux 0.6.0

![FB_IMG_1628257054544](https://user-images.githubusercontent.com/75086284/128519137-fb95b72f-5f35-4cbd-98c5-ac42b09c2e5a.jpg)

**Comment by tobbi** [comment]
Does this help? https://github.com/mickelson/attract/issues/681

**Comment by isidoro-80** [comment]
I try but i haven't audio. Now in photo the error
![Uploading 16284239951006044247964852670900.jpg…]()
