### ISSUE TITLE
Traduction of text messages not work!

### ISSUE THREAD

**Issue by SalomonDFanSuperTux** [SuperTux/supertux#1808]
Hi!
i was working on my world and i wanted to traducted the messages of text's in spanish (Si soy español Lel)...
But... not work...
Here are the pictures
![error1](https://user-images.githubusercontent.com/74196506/129798447-6a5b6e28-9408-4851-8c76-b27f89d5be4f.PNG)
![error2](https://user-images.githubusercontent.com/74196506/129798467-3ed5a7e1-8a22-4ac1-91a6-49e1abdf7f1c.PNG)

I need help!

**Comment by Semphriss** [comment]
You must use [Transifex](https://www.transifex.com/arctic-games/supertux/) to do translations; they will be updated in the repo next release.

**Comment by Semphriss** [comment]
![image](https://user-images.githubusercontent.com/66701383/129815759-20d11da6-ba59-4f67-85ef-16b2f723f83a.png)

You wrote "cas**lt**e" in the text editor, but in the game you wrote"cas**tl**e", perhaps that is the problem?

**Comment by Semphriss** [comment]
Since this does not seem to be an issue with SuperTux, I'll close this. If you need more help, please open a new issue.
