### ISSUE TITLE
Circular platforms don't carry you properly

### ISSUE THREAD

**Issue by Rusty-Box** [SuperTux/supertux#1811]
Standing on a circular platform causes you to slide off of it making those platforms pretty much unusable.

**Comment by Zwatotem** [comment]
Do you mean moving platforms or does it happen on static platforms as well?

**Comment by mrkubax10** [comment]
@Zwatotem It only happens on moving platform, it seems like Tux is not moving with it which makes effect of sliding from platform

**Comment by mrkubax10** [comment]
Here is video:
Uploading 2021-08-30 12-28-03.mp4…
