### ISSUE TITLE
Object + Wind interaction

### ISSUE THREAD

**Issue by Alasdairbugs** [SuperTux/supertux#1826]
SuperTux-v0.6.2-829-g63a326685
Windows 10

Wind should interact with springs, and other solid objects, lamps, etc, much like how it interacts with enemies. This would open doors to multiple new puzzles, since wind can be enabled or disabled with switches. The possibilities once we start combining mechanics with each other are endless.

This should mark the beginning of these object-object interaction ideas.

**Comment by weluvgoatz** [comment]
I like this idea.  Water, slick tiles, trampolines and bumpers should also treat all objects/enemies like how they treat the player.
