### ISSUE TITLE
Use spritesheets instead of separate files

### ISSUE THREAD

**Issue by Karkus476** [SuperTux/supertux#183]
This would be a bit of a pain, but textures/sprites that are used a lot/ are not going to be changed could be put into spritesheets. One could be Antarctica Spritesheet, another for forest, another for badguys etc. This would speed up loading times as desired for #182

**Comment by Grumbel** [comment]
Putting all the graphics in a .zip might be a better way to attack this. Reduces the I/O just as well, but could be done for `free` at install time and wouldn't lose any flexibility. We already do it for the addons.

**Comment by weluvgoatz** [comment]
The graphics are changing a lot, so it might be tedious to emplace the sprites in their grids every single time.  So closing this for now as not currently planned.
