### ISSUE TITLE
Keyboard Layout Settings Per Profile

### ISSUE THREAD

**Issue by Karkus476** [SuperTux/supertux#184]
Rather than for all users.
In fact, all settings could be included in this scope.
[This is the config file I am talking about.](http://pastebin.com/5nT7HMDL)

**Comment by Karkus476** [comment]
I will try to make a judgement on what to include or exclude

**Comment by Karkus476** [comment]
Moving this back to post 0.4.0, this will appear immediately afterwards, I hope

**Comment by maxteufel** [comment]
Postponed per meeting decision.

@Karkus476 In case you're still (intending to work) working on this, open a pull request as soon as you're done with the work.

**Comment by Vankata453** [comment]
It was decided against this feature, because it may become confusing and unintuitive, since profiles currently act a lot like separate saves.
