### ISSUE TITLE
Rework worldmap for "Rubberducks levels"

### ISSUE THREAD

**Issue by tobbi** [SuperTux/supertux#185]
The worldmap for the above levelset still needs improving. Currently:
- Paths leading nowhere
- A lot of straight paths
- Not a lot of different tiles.

**Comment by maxteufel** [comment]
I think in the future issues like this should be reported to the SuperTux/addons repo and levelset/worldmap authors should be @ -mentioned if they're on GitHub (maybe that should be a requirement?).

**Comment by Karkus476** [comment]
@maxteufel agreed. To submit to the addons repo they must be able to make an issue/pull request regarding it.

**Comment by sydneyjd** [comment]
I can do it if everyone is ok with me doing it.

**Comment by brmbrmcar** [comment]
I like not having to do the level before to get to the next level.

**Comment by sydneyjd** [comment]
@tobbi You brought this up, what do you think?

**Comment by tobbi** [comment]
It could at least be more squiggly...

**Comment by Mathnerd314** [comment]
From [rubberduck](http://forum.freegamedev.net/viewtopic.php?f=67&t=4582&p=47295#p47295), author, in 2013:
> when i made it, i wanted to make my own "world", the worldmap is oly a "collection" of all playable levels, so i don't have a "real" worldmap now
> i don't want to make a worldmap now, you can make one, you also can improve the levels, if some aren't so good

So the worldmap is just a placeholder; it should definitely be replaced if someone is willing to do the work.

Seems he had an account on a GitHub clone: https://notabug.org/rubberduck. I don't think he's https://github.com/rubberduck though, so @-mentioning is not possible.

Also, the level names are in German, maybe a certain someone who speaks German should do an English translation...

**Comment by tobbi** [comment]
I could do the translation work.

**Comment by brmbrmcar** [comment]
Look at my one in my fork of supertux. See if  it is any good.

**Comment by tobbi** [comment]
I checked in your worldmap changes, sydney.
