### ISSUE TITLE
Stalactite sometimes refuses to fall

### ISSUE THREAD

**Issue by weluvgoatz** [SuperTux/supertux#1858]
Sometimes the stalactite will refuse to fall even when under the proper conditions.  This seems to happen at random, but the stalactite in the same level can suddenly work perfectly fine in another level if placed in the same way.  I heard someone say this had something to do with moving tilemaps?

**Comment by tobbi** [comment]
The second issue is that the collision system checks the tiles present in the tilemap... and if the vector is outside bounds, it'll return the last tile present in the tilemap in each direction. I'll fix it.

**Comment by tobbi** [comment]
I am not sure if the first issue is something we should fix. The stalactite appears "stuck" in a solid part of the tilemap. But if you think otherwise, do tell me.

**Comment by Narre** [comment]
I don't mind the first issue either way. Maybe ask what the team thinks?

**Comment by Zwatotem** [comment]
@weluvgoatz can you confirm this being fixed and close?

**Comment by Busybody64** [comment]
I honestly agree with keeping the first "issue."

Would probably have to make sure it wouldn't hurt you if you walked on top of the unisolid tile it's underneath, though.

**Comment by weluvgoatz** [comment]
Seems to be fixed, reopen if isn't.
