### ISSUE TITLE
MAC nightly doesn't work.

### ISSUE THREAD

**Issue by Busybody64** [SuperTux/supertux#1861]
The latest nightly build doesn't have an icon, and it said there isn't a software that can run supertux.

**Comment by tobbi** [comment]
Working fine here.

**Comment by tobbi** [comment]
Which version of OS X do you use?

**Comment by Busybody64** [comment]
Version 10.15.7

**Comment by tobbi** [comment]
Can you try with the latest nightly?

**Comment by Busybody64** [comment]
Yep, the latest nightly works!

It might've been a compile error or something...
