### ISSUE TITLE
SuperTux freezes when using 0% speed option from Debug menu. 

### ISSUE THREAD

**Issue by Busybody64** [SuperTux/supertux#1867]
It seems completely pointless, and it just causes the game to freeze in such a way that prevents even TASK MANAGER from closing the program.

You have to reboot the COMPUTER to close the game if you set the speed to 0%.

(Like, come on, guys... Who thought it was even remotely ok to put that option there?)

**Comment by tobbi** [comment]
What version of SuperTux?

**Comment by Busybody64** [comment]
Current nightly, but it was in the game since 0.6.0 at least.

**Comment by tobbi** [comment]
No debug symbols, but here we go:
```
(lldb) bt
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGSTOP
  * frame #0: 0x00000001004a57db supertux2`Sprite::update() + 139
    frame #1: 0x00000001004a599a supertux2`Sprite::draw(Canvas&, glm::vec<2, float, (glm::qualifier)0> const&, int, unsigned int) + 106
    frame #2: 0x0000000100841db1 supertux2`worldmap::Tux::draw(DrawingContext&) + 1937
    frame #3: 0x00000001005fb01a supertux2`GameObjectManager::draw(DrawingContext&) + 298
    frame #4: 0x0000000100849955 supertux2`worldmap::WorldMap::draw(DrawingContext&) + 533
    frame #5: 0x000000010085f4c5 supertux2`worldmap::WorldMapScreen::draw(Compositor&) + 69
    frame #6: 0x000000010072e4ad supertux2`ScreenManager::draw(Compositor&, ScreenManager::FPS_Stats&) + 141
    frame #7: 0x000000010072f724 supertux2`ScreenManager::loop_iter() + 788
    frame #8: 0x000000010072fb8a supertux2`ScreenManager::run() + 74
    frame #9: 0x0000000100648087 supertux2`Main::launch_game(CommandLineArguments const&) + 6823
    frame #10: 0x000000010064974b supertux2`Main::run(int, char**) + 1275
    frame #11: 0x0000000100007ccd supertux2`main + 93
    frame #12: 0x00007fff7ac743d5 libdyld.dylib`start + 1
```

**Comment by Busybody64** [comment]
Um, what is this code used for? I don't really know what this means.

**Comment by tobbi** [comment]
> Um, what is this code used for? I don't really know what this means.

Good!

**Comment by Busybody64** [comment]
> > Um, what is this code used for? I don't really know what this means.
> 
> Good!

???

Are you trying to troll me?

**Comment by tobbi** [comment]
> > > Um, what is this code used for? I don't really know what this means.
> > 
> > 
> > Good!
> 
> ???
> 
> Are you trying to troll me? 
No, looks like I succeeded.

> Can you please explain what this has to do with the debug speed option?
That is where SuperTux gets stuck when it hangs.

**Comment by Busybody64** [comment]
Oh, that makes a lot more sense! Thank you!

I think the easiest way to fix this would be to make it so you can't set the speed lower than 10/25% (or whatever the slowest speed before 0% is right now)

**Comment by erratic-c-programmer** [comment]
To be fair, it *is* debug mode, and you should know what you're doing there-- here be dragons ;)

**Comment by Busybody64** [comment]
Good point, but we don't want a debug mode that forces you to restart your computer. That's just impratical.

**Comment by Busybody64** [comment]
I think I accidentally closed this... Oops!

**Comment by tobbi** [comment]
In 0.6.3, SuperTux does not freeze anymore. Instead, I'm hitting this assert:
```Assertion failed: (false), function active_update, file supertux/src/badguy/walking_badguy.cpp, line 134.
Abort trap: 6```

**Comment by tobbi** [comment]
You cannot set 0% as the speed anymore.
