### ISSUE TITLE
???

### ISSUE THREAD

**Issue by SalomonDFanSuperTux** [SuperTux/supertux#1873]
Hi everyone!
I wanted to report this rare bug.

Look, i was doing my level of ghostforest, i tested it and when i died, this happen:
https://drive.google.com/file/d/1kiZiCbZpK2M9KiQEv0b8Psb7T6-0obGt/view?usp=sharing
(I swear that im not lying, please, see the controller and see that im not changing the level's speed. This bug happens on v0.6.2)

I just, don't know what happen, but when i restart level (from pause) it still freeze
I think that developers can repair this bug ;)

Greetings,
SuperTuxFan

**Comment by Semphriss** [comment]
Please include a more verbose title and description to help searching this issue for others who might have the same issue. Also, you can upload videos directly on GitHub; please do so to make it easier for us.

**Comment by Busybody64** [comment]
What.

This is such a weird glitch!

You might have to re-enter the entire level to fix this.
