### ISSUE TITLE
Go through old bugtracker

### ISSUE THREAD

**Issue by tobbi** [SuperTux/supertux#188]
The old bugtracker has some old issues that might be of relevance, still.

We should go through the open ones and see what to do with them. Here's a permalink:
http://supertux.lethargik.org/bugs/search.php?project_id=1&status_id[]=10&status_id[]=20&status_id[]=30&status_id[]=40&status_id[]=50&sticky_issues=1&sortby=last_updated&dir=DESC&hide_status_id=-2

**Comment by cooljeanius** [comment]
I think I had some bugs on the old tracker over a decade ago; unfortunately that link seems to be broken because it displays this when clicked upon: 


    APPLICATION ERROR #400
    --
    Database connection failed. Error received from database was #0: PHP Support for database is not enabled.
    Please  use the "Back" button in your web browser to return to the previous  page. There you can correct whatever problems were identified in this  error or select another action. You can also click an option from the  menu bar to go directly to a new section.

**Comment by tobbi** [comment]
Yeah, it appears there's nothing we can do about this issue anymore.

**Comment by cooljeanius** [comment]
> Yeah, it appears there's nothing we can do about this issue anymore.

There's no archive backed up anywhere?

**Comment by tobbi** [comment]
https://web.archive.org/web/20160305175737/http://supertux.lethargik.org/bugs/my_view_page.php would work
