### ISSUE TITLE
Icecrusher Bug List

### ISSUE THREAD

**Issue by weluvgoatz** [SuperTux/supertux#1880]
Here I am going to keep track of icecrusher bugs that I have discovered so that someone or me can fix them in the future:

- Rocks placed atop icecrushers cause it to bounce oddly on the floor.
- Icecrusher doesn't return to exact original position and gets a little offset each time.

Feel free to append any of your own, if you have found any.

**Comment by Busybody64** [comment]
Pictures would be nice.

That first one seems quite odd, honestly. It sounds like it still thinks there's a platform underneath it.
The second one isn't really as much a bug, as it is an inconsistency. It would be nice if they only broke one crate at a time.
I dunno what to even say about the third one.

**Comment by weluvgoatz** [comment]
#2254 fixes most of these, for those who care.
