### ISSUE TITLE
Application crash 

### ISSUE THREAD

**Issue by ubiratanprojeto** [SuperTux/supertux#1882]
**SuperTux version: 0.6.1**
**System information:** *OS: Fedora Linux 35 (Workstation Edition), Kernel: 5.14.16-301.fc35.x86_64, Shell: bash 5.1.8, DE: GNOME 41.1, CPU: Intel i3-9100F (4) @ 4.200GHz, GPU: NVIDIA GeForce GT 710, Xorg*

##### Expected behavior

I installed from Flatpak. There was no installation problem. It opened normally. It showed the history of the game and when the first phase started. The bug has occurred. 

##### Actual behavior

The game closes and drops the gnome session. Returning to login screen. 

##### Steps to reproduce actual behavior

1 - Install from fedora 35 Workstation store;
2 - Install the flatpak version of supertux2 version 0.6.1
3 - Open the game in the Xorg session
4 - When passing the opening story, the bug occurs, the screen goes black and goes back to the fedora 35 login screen. 

##### Additional debugging information

![Captura de tela de 2021-11-11 14-17-52](https://user-images.githubusercontent.com/94130386/141342939-9013174e-0403-4105-a3c6-c7b953b3218f.png)
![Captura de tela de 2021-11-11 14-30-25](https://user-images.githubusercontent.com/94130386/141342947-40c169bc-041c-4a54-a176-3dce9aeb5de0.png)

**Comment by mrkubax10** [comment]
Could you try with latest version (0.6.2)?

**Comment by ubiratanprojeto** [comment]
I reported the bug as a result of using it on Xorg. No Wayland so far has not appeared. but still thanks for the tip. :)

**Comment by Busybody64** [comment]
This is an outdated version, so I dunno if this should remain up, unless it also happens on 0.6.2.

**Comment by tobbi** [comment]
@ubiratanprojeto Is it fixed in the latest version?

**Comment by Semphriss** [comment]
Assuming fixed; closing. If this bug (or similar) happens, please verify if the problem arises from the distributor or from the game itself, and if it comes from the game, please open a new issue.
