### ISSUE TITLE
Sideways Chain tiles are unisolid when placed in a solid tilemap

### ISSUE THREAD

**Issue by Alasdairbugs** [SuperTux/supertux#1883]
v0.6.2-894-ge82f5e396
win10

sideways chains when placed in solid tilemaps should not act as unisolid tiles. the reason for this is because the other chain tiles dont act solid or unisolid, so why are the sideways ones unisolid? this makes no sense. plus, if you wanted it to be unisolid you could use the actual unisolid tiles that are available in the editor which is what all unisolids currently SHOULD use. The reason for changing this is clearer when you want to use unisolid tiles in cutscenes, with moving tilemaps. moving tilemaps having to suffer with this means having to make more moving tilemaps to create a certain object, because you cant put the chains in solid tile. silly.

imagine having to make a new path node collection for a new moving tilemap because the game decided to make the tiles you were using unisolid

**Comment by tobbi** [comment]
According to @Rusty-Box, the tiles have changed and are no longer unisolid. I'm gonna close the issue now
