### ISSUE TITLE
0.6.2: Broken characters of string

### ISSUE THREAD

**Issue by gnh1201** [SuperTux/supertux#1885]
**SuperTux version:** 0.6.2
**System information:** Lubuntu 20.04 LTS

##### Expected behavior

No broken characters of string

##### Actual behavior

It showing the broken characters of string: https://i.imgur.com/F0q4jBh.jpg

**Comment by Semphriss** [comment]
What language is it?

**Comment by gnh1201** [comment]
Korean (ko) #1597

**Comment by tobbi** [comment]
I agree, we should merge the code changes from #1597 (not so much the text file changes, since I'd rather keep those .md files as they are).

**Comment by gnh1201** [comment]
Any update?

**Comment by tobbi** [comment]
@gnh1201 Would you be able to do a pull request to our repository? And pick the ones that we need (not the .md changes)

**Comment by gnh1201** [comment]
Ok. I'll try it.

**Comment by Semphriss** [comment]
Normally, it should be fixed by #1963; closing, please open a new issue if the error persists.
