### ISSUE TITLE
Walking in cramped space unexpectedly incurs hits/death

### ISSUE THREAD

**Issue by ghost** [SuperTux/supertux#1892]
**SuperTux version:** SuperTux_2-v0.6.2-933-g5e5e1378a.glibc2.29-x86_64

##### Expected behavior

Getting the fire bonus and walking off the block shouldn't kill Tux.

##### Actual behavior

Walking off the block to the right hurts Tux, ultimately killing him.

##### Steps to reproduce actual behavior

1. Play 'Going Underground' (Forest World).
2. Go underground and hit the first bonus block as big Tux.
3. Jump on top of the block from left side and keep walking right.

##### Additional debugging information
![GIF showing Tux dying](https://user-images.githubusercontent.com/44826203/141688962-cd0f5e42-bc70-47d5-9c32-dae04d198e69.gif)

The collision box for the wall pushes Tux downward into the bonus block, which causes Tux to take a hit. If Tux was only big (and didn't have any powerup), he would now be small and wouldn't die. However, here he just got the fire powerup and therefore only loses that while remaining big. Continuing to push further right therefore kills him.

![image](https://user-images.githubusercontent.com/44826203/141689047-e506e25f-6404-49d8-a0c1-788a930953f4.png)

**Comment by plonibarploni** [comment]
Perhaps this is related to #990?

**Comment by Busybody64** [comment]
This seems to happen because it thinks tux is getting crushed to death. Can't really blame them. It kinda does look like that.

**Comment by pelya** [comment]
Can we force Tux to crouch instead of taking damage, if he's in the cramped area? So he cannot stand up until he leaves the cramped area.
