### ISSUE TITLE
Replace arrow selectors with too many choices with a better selection menu

### ISSUE THREAD

**Issue by Rami-Slicer** [SuperTux/supertux#1894]
They are good for situations where there are few options to choose from but some have way to many options
Here's an example from the dispenser object's settings:
![This image](https://user-images.githubusercontent.com/40865625/142081031-af96a6b1-acbc-473d-8048-19e433a5a585.png) 
The widget's options include every single badguy in the game and is annoying to use.

**Comment by Busybody64** [comment]
It could be more like the owl, I think.
It'd probably have to be converted for retrocompatability, tho, and it might break many old addons.

**Comment by mrkubax10** [comment]
This is about interface change so I doesn't have anything to compatibility.

**Comment by Alasdairbugs** [comment]
it could have a drop-down menu like there is for when you select tiles and it shows snow, snow background, etc.

**Comment by Alasdairbugs** [comment]
oh yeah this also goes for choosing path node easing
