### ISSUE TITLE
Rocks and wind interaction bugs

### ISSUE THREAD

**Issue by weluvgoatz** [SuperTux/supertux#1899]
I've noticed that rocks seem to respond weirdly to having their x-velocities being set by wind (actually, mostly everything in SuperTux reacts weirdly when their x-velocities are set by wind, but this one is especially weird because the rock seems to take on a mind of its own and walk around the map.)

**Comment by Semphriss** [comment]
I struggle to reproduce this; do you have a video showing the problem?

**Comment by Alasdairbugs** [comment]
reproduced. when you activate a wind that pushes a spring or rock or whatever into a wall as its falling from the momentum of the wind, the recurring bounce gives the object a momentum that is unstoppable. it can bounce off another wall with a rebound momentum smaller, but still has a mind of its own.

interestingly, if you use a wind tile to shoot it up, it SKYROCKETS up, and then just keeps gliding in that first trajectory it has.

**Comment by Alasdairbugs** [comment]
this also occurs with lanterns, and any kind of object. It makes the recent feature semphris added, that wind can interact with objects, obselete, so its important to fix! :)

**Comment by Narre** [comment]
I managed to reproduce this bug

https://user-images.githubusercontent.com/14074789/146102187-928ba242-7437-46c9-8938-b2d36a1b39cd.mp4

It works even with more sensible wind attributes, but making it this "extreme" makes it more consistently reproducible:
[wind_object.zip](https://github.com/SuperTux/supertux/files/7715665/wind_object.zip)

**Comment by Narre** [comment]
Update:
Thanks to @Alasdairbugs, I updated the test level to use more sensible acceleration and speed, no need for any extreme values to reproduce this bug consistently.
[wind_object.zip](https://github.com/SuperTux/supertux/files/7715784/wind_object.zip)
