### ISSUE TITLE
Bomb explosion push no longer works

### ISSUE THREAD

**Issue by weluvgoatz** [SuperTux/supertux#1900]
In the newer builds, the explosion push that bombs and shortfuses would inflict on the player seems to be missing.  It should be added back, or a fix should be created to make it work properly again.

**Comment by Rami-Slicer** [comment]
This problem seems to be caused by something Tobbi added a few weeks ago:
https://github.com/SuperTux/supertux/blob/ced4ff6e1a9e0df3fac69422fb782416802439f9/src/object/explosion.cpp#L87-L88

Removing those lines allows objects to be pushed again.
