### ISSUE TITLE
fish is mising in water

### ISSUE THREAD

**Issue by irsyadprisadi** [SuperTux/supertux#1904]
**SuperTux version:** 0.6.2
**System information:** ubuntu 18.04.6

##### Expected behavior
you can see fish in the water
##### Actual behavior
you cant see the fish in the water 
##### Steps to reproduce actual behavior
place a fish in the water the. Fish jumps out of water wait till the fish came back to the water

**Comment by mrkubax10** [comment]
Swimming fish will be added in future.

**Comment by Alasdairbugs** [comment]
did you make the water tilemap solid?

**Comment by irsyadprisadi** [comment]
I already make it solid but still, strange It disappear when coming back to the water then appear after jumping out of the water

**Comment by Alasdairbugs** [comment]
next time be clearer in your first message. you should indicate if its a bug or just an inconsistency.
