### ISSUE TITLE
Jumping off a climbable object is still inconsistent

### ISSUE THREAD

**Issue by Alasdairbugs** [SuperTux/supertux#1905]
Tux should consistently jump ~3 tiles off a climbable object. this is not always the case though

roughly half the time you do not make a full jump, instead, you get a very small jump, sort of like a ladder ejection than a jump, and the difference in height makes a *lot* of difference.

make a climbable object and jump off of it, notice how tux's jump height varies.

**Comment by Semphriss** [comment]
Reproduced with the following steps:
- Find a climbable zone with land below it
- Start jumping
- Before reaching the jump apex, release the jump button then immediately press up
- Climb a bit, and attempt doing a high jump; it should fail.

I believe it is the code that handles jumping that forgets to reset the early apex, which cancels Tux jumping.
