### ISSUE TITLE
Story mode worldmap does not persist ambient light

### ISSUE THREAD

**Issue by Semphriss** [SuperTux/supertux#1906]
In the few levels preceding the cave zone in Icy Island, the ambient light adjusts to create an evening/night/dawn light atmosphere. Leaving and re-entering the worldmap will reset the lighting to its default value.

**Comment by serano01** [comment]
Strangely, this seems not to be the case for Bonus-Island III, which uses an night light atmosphere as well.

**Comment by Rusty-Box** [comment]
Was the script put in a special tile object or runs from the .nut file?

**Comment by Narre** [comment]
The ambient light isn't saved anywhere in world1. I guess saving the ambient light should be implemented to be done automatically in the .stsg savegame file just like tilemap alphas, otherwise saving it in a squirrel global (state) variable is the only option.

**Comment by Semphriss** [comment]
Just to make things clearer: that's a feature I added a while ago; this isn't an engine flaw or anything, I just forgot to make it save the ambient light settings. I opened this issue so I wouldn't forget about it and so other people would be aware that it's a known problem.
