### ISSUE TITLE
Autoscrolling doesn't crush Tux against walls anymore

### ISSUE THREAD

**Issue by 165your4** [SuperTux/supertux#191]
I was making an autoscrolling level in the editor and noticed that Tux is free to move outside of the camera. It wasn't like this in 0.1.3. This goes against the conventional "rules" of autoscrolling and feels weird. Is it a bug or intentional?

**Comment by tobbi** [comment]
For reference:
http://supertux.lethargik.org/bugs/view.php?id=475
http://supertux.lethargik.org/bugs/view.php?id=44

**Comment by Hume2** [comment]
The problem of autoscroll is that the screen size is variable, so the level difficulty varies by screen size.
I agree with WolfgangB that there should be something that really looks dangerous instead of just being crushed by the camera.

**Comment by Hume2** [comment]
Maybe there could be something that would cause the tiles on the left fall, so it would create the same effect.

**Comment by brmbrmcar** [comment]
Levels are designed differently now. It should stay put.

**Comment by sydneyjd** [comment]
Im labeling this as post 4.0.

**Comment by sydneyjd** [comment]
Unless we think its a bug, of course.

**Comment by brmbrmcar** [comment]
It's not.

**Comment by Karkus476** [comment]
No I think this is a bug, tux should never be off the screen unless he's dead. The solution to this is to create a moving wall (invisible) which will crush Tux against other tiles just like in the Super Mario games

**Comment by Karkus476** [comment]
I also think this should be 0.4.0, as the player being off the screen is never a good thing.

**Comment by Hume2** [comment]
We have a sollution: delete autoscroll

**Comment by brmbrmcar** [comment]
I don't like autoscroll much. But it cannot be deleted.

**Comment by Hume2** [comment]
The same for me. Since we can add a real moving danger, there's no need for autoscroll.

**Comment by brmbrmcar** [comment]
I'd keep it the same for now.

**Comment by Hume2** [comment]
Philosophical question: Why should be Tux killed by the edge of camera? Just because we can't see him? Or is there something so scary and dangerous, so we can't see it?

**Comment by brmbrmcar** [comment]
The answer is no.

**Comment by sydneyjd** [comment]
Honestly, i think its fine the way it is. Most people who are playing autoscrolling levels are not worried about going back, but staying towards the front of the movement. 
It also doesn't seem right to kill a player thats behind the visual autoscroll. What if he fell behind and is right on the edge?

Just some thoughts. :)

-Sydney

**Comment by Karkus476** [comment]
@sydneyjd The player should always be able to see tux, else they may become confused.

**Comment by sydneyjd** [comment]
I know its confusing when they go behind the "curtian", but i don't belive that a reason to kill them. Especially if its slightly behind.

**Comment by Karkus476** [comment]
This is the reason auto scrolling levels exist

- Karkus

**Comment by Hume2** [comment]
Yes, but the bigger screen you have, the easier it is.
And a real moving danger could serve the same way.

**Comment by Karkus476** [comment]
Hmmm, that is a problem.

- Karkus

**Comment by brmbrmcar** [comment]
Also: isn't the camera scripted in the same way as to show what happens when you hit a switch or something? There would need to be a separate autoscroll script.
