### ISSUE TITLE
Short fuse explosion push broken

### ISSUE THREAD

**Issue by cnub66** [SuperTux/supertux#1911]
**SuperTux version:** Latest nightly

Short fuses used to launch Tux very high when he jumped on them but now they do not launch Tux higher than if he jumped on any other badguy, rendering them pointless as an enemy. This changed at least within the past year, I have a nightly dated 7th Nov 2020 on my laptop where the issue is not present.

**Comment by mrkubax10** [comment]
Does this still happen with latest nightly?

**Comment by cnub66** [comment]
No longer occurs as of (at latest) 0.6.3 beta 1
