### ISSUE TITLE
[Don't fix!] Tux dying and falling down will not go below the sector and will instead start floating up

### ISSUE THREAD

**Issue by Semphriss** [SuperTux/supertux#1912]
# Please do not fix this bug!
**I know where the issue is, but I have some other things to check with that part of the code. Given this, I'd like to take it upon myself to correct the code to avoid having more issues.**

------------------

Reproduction steps:
- Play Crystal Mine at the end of Icy Island in story mode.
- Let Tux die at the beginning of the level, at a place where there is water below.
- Look at Tux fall down, and notice that upon reaching the bottom of the screen, Tux starts to float upwards.

Cause of the issue:
- When implementing the swimming floor push, I forgot to check if the player is dying or dead. I cannot fix it immediately because there are other issues surrounding this bug, notably a related PR that would create conflict with fixing this issue.

I apologize for clinging to this and asking people to wait; I hope the explanation sounds reasonable. I expect to be able to fix this by the end of December at most.

**Comment by Alasdairbugs** [comment]
This also happens when ghost mode is activated on the same frame tux dies at the bottom of the screen.
