### ISSUE TITLE
Black background/sky in new sectors

### ISSUE THREAD

**Issue by weluvgoatz** [SuperTux/supertux#1918]
In newly created sectors, the back sky will be black instead of colored.  This can be fixed by making the game add a gradient behind the background when a sector is made.

**Comment by tobbi** [comment]
What colours should the background gradient have?

**Comment by Semphriss** [comment]
I suppose the default colors when adding a gradient would be fine.

**Comment by weluvgoatz** [comment]
This only fixes the issue if a new sector is created in an already-existing level; the issue still exists if a new sector is created as a result of making a new level.
