### ISSUE TITLE
Autotile unexpectedly turns on and off when testing and saving level

### ISSUE THREAD

**Issue by Narre** [SuperTux/supertux#1923]
**SuperTux version:** current git version (as of commit cf60131)
**System information:** LMDE4 64bit, kernel 4.19.0-18-amd64

Note: I have noticed this a while ago (it gets really frustrating when creating levels) but then I forgot to create an issue for it because I was using a tileset with no autotiles.

It seems that Autotile mode in the editor turns on/off unexpectedly when pressing Ctrl+S and Ctrl+T (aka save and test level).
As far as I can tell, *saving and then testing* will turn it **on** while *testing and then saving* will turn it **off** (but it could be more random than that).

Autotile should never turn on or off on its own.

https://user-images.githubusercontent.com/14074789/145453024-28131c9b-6dfc-4ae4-ab1e-af9160fe1b78.mp4

**Comment by Semphriss** [comment]
Please enable autotile help to see the real-time changes to the autotile mode.

**Comment by Narre** [comment]
https://user-images.githubusercontent.com/14074789/145640106-95f9050c-b384-41a7-b78d-8548e550425e.mp4

**Comment by Semphriss** [comment]
> Autotile should never turn on or off on its own.

Ctrl is the hotkey to toggle autotile mode. This might be playing.

> As far as I can tell, saving and then testing will turn it on while testing and then saving will turn it off (but it could be more random than that).

Can't fully reproduce; the only issue I observed is that the autotile mode will be erroneous upon returning from testing a level. Hitting Ctrl once will revert to what its status was before testing the level.

Apart from that, the autotile mode will indeed toggle twice while performing any keyboard input involving Ctrl, but it should cancel out as pressing Ctrl and releasing Ctrl both perform a toggle. Unless you are placing tiles at the same moment you are invoking a save/test with the keyboard, it shouldn't have any significant impact.

**Comment by Alasdairbugs** [comment]
i havent come across this issue personally, its just a matter of holding ctrl

**Comment by Narre** [comment]
Just pressing Ctrl after a level test seems to be all that's really needed as a workaround. It's still a bit annoying though.
