### ISSUE TITLE
libc6 version problem

### ISSUE THREAD

**Issue by eluuk** [SuperTux/supertux#1924]
**SuperTux version:**

0.6.2

**System information:**

Distributor ID:	Ubuntu
Description:	GalliumOS 2.1
Release:	16.04
Codename:	xenial

##### Expected behavior

The game should run

##### Actual behavior

Running the flatpak installation:

`./supertux2: relocation error: /var/lib/flatpak/runtime/org.freedesktop.Platform/x86_64/20.08/93f5faa8492c933e9ed7dfee9824302af357101680a4df1f72d02ed26a0ab7e5/files/lib/x86_64-linux-gnu/libc.so.6: symbol _dl_exception_create, version GLIBC_PRIVATE not defined in file ld-linux-x86-64.so.2 with link time reference
`
Running the appimage:

```
supertux2: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by supertux2)
supertux2: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by /tmp/.mount_SuperTRliAuL/usr/lib/x86_64-linux-gnu/libSDL2-2.0.so.0)
supertux2: /lib/x86_64-linux-gnu/libz.so.1: version `ZLIB_1.2.9' not found (required by /tmp/.mount_SuperTRliAuL/usr/lib/x86_64-linux-gnu/libpng16.so.16)
supertux2: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /tmp/.mount_SuperTRliAuL/usr/lib/x86_64-linux-gnu/libgnutls.so.30)
supertux2: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.27' not found (required by /tmp/.mount_SuperTRliAuL/usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2)
supertux2: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.27' not found (required by /tmp/.mount_SuperTRliAuL/usr/lib/x86_64-linux-gnu/libpulsecommon-11.1.so)
supertux2: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /tmp/.mount_SuperTRliAuL/lib/x86_64-linux-gnu/libbsd.so.0)
supertux2: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /tmp/.mount_SuperTRliAuL/lib/x86_64-linux-gnu/libsystemd.so.0)
supertux2: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.27' not found (required by /tmp/.mount_SuperTRliAuL/lib/x86_64-linux-gnu/libsystemd.so.0)
supertux2: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /tmp/.mount_SuperTRliAuL/lib/x86_64-linux-gnu/libcrypt.so.1)
```

##### Additional debugging information

```
>$ apt-cache policy libc6
libc6:
  Installed: 2.23-0ubuntu11.3
  Candidate: 2.23-0ubuntu11.3
  Version table:
 *** 2.23-0ubuntu11.3 500
        500 http://ee.archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages
        500 http://security.ubuntu.com/ubuntu xenial-security/main amd64 Packages
        100 /var/lib/dpkg/status
     2.23-0ubuntu3 500
        500 http://ee.archive.ubuntu.com/ubuntu xenial/main amd64 Packages
```

As you see, the libc6 version on my sys is too old and I'm not sure if anything could be done about it other than installing a new distro (I'm planning to do this but being not the sole user of the sys it'll take some time). Is there a workaround (e.g. copying a couple of newer library files somewhere, using a bit older version --- I'm currently using 0.4.0, which doesn't have newer levels --- the reason for wanting 0.6.2 in the first place) or is it just the case that newer versions cannot be run on Ubuntu 16.04

**Comment by Semphriss** [comment]
SuperTux requires glibc >=2.27.

Try checking if your distribution/package manager(s) provide a newer version of glibc.

If not, you can try compiling SuperTux from source, which will produce a binary compatible with your standard C library.

**Comment by arrowgent** [comment]
ubuntu 16.04 xenial is unfortunately far out of support range

you can check the releases for an older version or recompile the build yourself
building yourself should work fine.

https://github.com/SuperTux/supertux/releases
