### ISSUE TITLE
Going off a moving platform too early hurts Tux.

### ISSUE THREAD

**Issue by brmbrmcar** [SuperTux/supertux#193]
It hurts him.

**Comment by brmbrmcar** [comment]
Do you need a screenshot?

**Comment by brmbrmcar** [comment]
![screenshot from 2015-10-20 16 04 14](https://cloud.githubusercontent.com/assets/14400196/10611483/3f1dc586-7744-11e5-8833-622d5811514a.png)

**Comment by brmbrmcar** [comment]
I left down at the blocks.

**Comment by sydneyjd** [comment]
Thats because you got pinched in-between the platform and the blocks. We cannot help that, its the players fault.

**Comment by brmbrmcar** [comment]
It happened before  it went up. Bad example.

**Comment by brmbrmcar** [comment]
I has happened in other levels, but it is really hard to screenshot.

**Comment by maxteufel** [comment]
> It happened before it went up.

That's what @sydneyjd means.

**Comment by brmbrmcar** [comment]
It didn't used to happen.

**Comment by sydneyjd** [comment]
Stand on the middle of the platform when going up. That will solve this.

**Comment by brmbrmcar** [comment]
I know. That's probably the best that can be done right now.

**Comment by maxteufel** [comment]
If you believe this didn't happen before, can you try to find the last good commit?

**Comment by Hume2** [comment]
When does it happen? The platform goes down and you try to go left past the solid blocks and then you get hurt. Right?

**Comment by brmbrmcar** [comment]
Yes.

**Comment by Hume2** [comment]
Definitely a bug.

**Comment by sydneyjd** [comment]
@Hume2 Can you take a peek into fixing it then?

**Comment by Hume2** [comment]
@sydneyjd It's a bug of how SuperTux handles collisions. I didn't manage to solve it so far, but we should. Maybe I shoud give it the high priority.

**Comment by tobbi** [comment]
"Maybe I should give it the high priority" -> It's your project now!

**Comment by tobbi** [comment]
@brmbrmcar Please attach the test level.

**Comment by brmbrmcar** [comment]
How?

**Comment by brmbrmcar** [comment]
Idon't have permission.

**Comment by tobbi** [comment]
@brmbrmcar Upload it somewhere else, then post a link here.

**Comment by brmbrmcar** [comment]
http://www.fileconvoy.com/gf.php?id=g632bf87048533af5999737685.783822b09520f18d0a2e9a&sts=1445361010212140122164b677c3395090d330bb46d7b2752df139
