### ISSUE TITLE
Coins being able to bind into non-existing paths.

### ISSUE THREAD

**Issue by bruhmoent** [SuperTux/supertux#1932]
SuperTux version: 0.6.3 - 1
You can bind a coin's node into a non-existing node, resulting in a continuous crashes, when trying to delete or open the level.

https://user-images.githubusercontent.com/69918580/146048949-2b10173f-eb25-42f6-aee9-0c8c307533cb.mp4

**Comment by tobbi** [comment]
Latest nightlies can be downloaded [from here](http://download.supertux.org)
