### ISSUE TITLE
Level : The Escape ... Impossible to continue to next level

### ISSUE THREAD

**Issue by lesouriciergris** [SuperTux/supertux#194]
Hello, 

in super tux 2, 0.3.4 (Ubuntu), I beat the yeti man and I'm now in the Escape Level. 

I finish this level it but I can't go to the next level. Only the previous levels are available.

Thanks.

**Comment by brmbrmcar** [comment]
There is currently no level after that. In the future, the forest world will be there.

**Comment by lesouriciergris** [comment]
Le 20/10/2015 17:23, brmbrmcar a écrit :
> There is currently no level after that. In the future, the forest world
> will be there.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SuperTux/supertux/issues/194#issuecomment-149600964>.
>
Thank you very much.

**Comment by Karkus476** [comment]
Hmm, just wondering what that did...
