### ISSUE TITLE
Shrinking a tilemap while using a negative offset looses tiles

### ISSUE THREAD

**Issue by Semphriss** [SuperTux/supertux#1945]
Discovered while investigating a fix for #1943

https://user-images.githubusercontent.com/66701383/146117642-0c0c2b8e-2f6b-42fe-960f-f552acb9527f.mp4

The created empty lines at the bottom are not empty lines added by offset; if you check the horizontal line of snow tiles and count the number of tiles between it and the bottom of the tilemap, it will become apparent that the 5 empty lines at the bottom should have kept the base of the block.

**Comment by Semphriss** [comment]
Consideration for anybody coming across this issue: Inverting the steps of displacing the tiles and resizing the tilemap isn't enough, as it would spawn another bug, this time happening when *growing* the tilemap.

[Details here](https://github.com/SuperTux/supertux/pull/1960#pullrequestreview-833366278)

https://user-images.githubusercontent.com/66701383/146259858-c338a9b9-767a-45e8-a768-340c6b8766cc.mp4

**Comment by mrkubax10** [comment]
More fixing awaits
