### ISSUE TITLE
get locked back

### ISSUE THREAD

**Issue by irsyadprisadi** [SuperTux/supertux#1949]
**SuperTux version:** 0.6.3 beta 1
**System information:** ubuntu 20.04.6 LTS

##### Expected behavior
you can get back to the first level
##### Actual behavior
you cannot get back
##### Steps to reproduce actual behavior
I dont know how this actually happen
##### Additional debugging information

https://user-images.githubusercontent.com/92800815/146135521-9755f312-9f15-479d-9385-b40f7cb269f9.mp4

**Comment by mrkubax10** [comment]
Could you send your savegame?

**Comment by irsyadprisadi** [comment]
[world1.txt](https://github.com/SuperTux/supertux/files/7717071/world1.txt)
this one?

**Comment by Semphriss** [comment]
I'm on it. I'm the culprit for that one

**Comment by Semphriss** [comment]
Basically: there's a new feature (that I'm responsible for) that does it so when you pick one exit in A Fork in the Road, it unlocks only the corresponding path. Thing is, I didn't code anything if the player comes back from behind on either path. I'm gonna code that now.
