### ISSUE TITLE
Stop credit music starting again right at the very end

### ISSUE THREAD

**Issue by brmbrmcar** [SuperTux/supertux#195]
I would fix this, but am not sure what should be done. It isn't natural to restart on the very last sentence. It didn't happen in Milestone 1 (because they could get away with only playing it once).

**Comment by Karkus476** [comment]
I really don't think anything needs to be changed. It's a good point, but you can scroll up and down in the credits.

**Comment by Karkus476** [comment]
Best idea evar: The credits are a level much like [in super mario bros. wii](https://youtu.be/1gDzHncTHwY?t=1m4s), which would make it really fun I think.

**Comment by brmbrmcar** [comment]
That would be alright though, because there is more of the music to play.

**Comment by Karkus476** [comment]
What I'm saying is, this is a temporary issue and it's requirements (in theory) are changing constantly so we cannot consider it as something that needs fixing.

**Comment by brmbrmcar** [comment]
Yeah. But i was just thinking about how big a release 0.4.0 will be...
