### ISSUE TITLE
How do I go back to Title screen in android?

### ISSUE THREAD

**Issue by UniqueName12345** [SuperTux/supertux#1978]

**Comment by mrkubax10** [comment]
Android port is outdated and unsupported.

**Comment by UniqueName12345** [comment]
> Android port is outdated and unsupported. 

Why?

**Comment by Grumbel** [comment]
Android 'Back' button worked the last time I tried, but that has been a while ago.

**Comment by UniqueName12345** [comment]
Thank you. It did work!
