### ISSUE TITLE
Certificate error when downloading extensions in version 0.6.3-beta.1

### ISSUE THREAD

**Issue by JerareYoshi** [SuperTux/supertux#1979]
**SuperTux version: 0.6.3-beta.1**
**System information:** openSUSE Leap 15.3 x86_64 **

![Screenshot_20211219_152315](https://user-images.githubusercontent.com/39435726/146678453-58cdd7ed-7c3a-41a5-beb3-5f7aa9e31df0.png)

**Comment by bruhmoent** [comment]
For me, when downloading an addon works perfectly.

**Comment by tobbi** [comment]
I feel like this is an error with your OS. Can you contact the openSUSE support channels?

**Comment by Semphriss** [comment]
@JerareYoshi Any news about this?

**Comment by JerareYoshi** [comment]
The problem does not appear on Tumbleweed but is still on Leap 15.3 because of the ca-certificate package. https://opensuse.pkgs.org/15.3/opensuse-oss-x86_64/ca-certificates-2+git20210309.21162a6-2.1.noarch.rpm.html

**Comment by mrkubax10** [comment]
Maybe try using package from Tumbleweed

**Comment by mrkubax10** [comment]
Closing due to problem being related to OS
