### ISSUE TITLE
Contributing Images and Sprites

### ISSUE THREAD

**Issue by DevynCJohnson** [SuperTux/supertux#198]
I would like to contribute by submitting new sprites, backgrounds, tile-sets, etc. I do not know how to easily upload images to GitHub Pull-requests. What is the best method for contributing images to the SuperTux project?

**Comment by tobbi** [comment]
Can you do a pull request? (Do you know how to create pull requests, if not, see https://help.github.com/articles/using-pull-requests/)

**Comment by maxteufel** [comment]
Pull request containing the changes are one option, another way is to attach the picture in an issue/another pull request using drag-and-drop (or look at the bar on the bottom of the comment box).

![github_attach_file](https://cloud.githubusercontent.com/assets/6442985/10709461/f7f015da-7a2f-11e5-817c-57f73ca4c38a.png)

**Comment by DevynCJohnson** [comment]
I know how to do a pull-request and I have done it before with other projects. However, I was unaware that I could drag and drop images in the box. Thanks for pointing that out. I was not sure if that was the proper method.

Thanks @maxteufel
