### ISSUE TITLE
Translation isn't shown for 'Are you sure?'

### ISSUE THREAD

**Issue by adem4ik** [SuperTux/supertux#1982]
**SuperTux version:** SuperTux-v0.6.3-beta.2-win64
**System information:** Windows 10 x64

##### Expected behavior
Exit dialog should have translated title - "Вы уверены?"

##### Actual behavior
Exit dialog has English title
![image](https://user-images.githubusercontent.com/4707112/146684267-7ee6867f-5d05-4f1b-ad64-9290ea84bea5.png)

##### Steps to reproduce actual behavior

1. Switch to Russian language
2. Start any level
3. Press Esc
4. Select 'Abort level' and wait for confirmation dialog

##### Additional debugging information

That string is translated as in Transifex as in ru.po https://github.com/SuperTux/supertux/blob/master/data/locale/ru.po#L2634 , but for some reason it's not translated in the game. Same thing can be reproduced in any other language.

**Comment by Semphriss** [comment]
Reproduced; a similar issue can be seen in the "Integrations and Presence" menu, in the description of the field:
![image](https://user-images.githubusercontent.com/66701383/146685892-bc6baff6-b49f-40bb-8efa-ffddbda7dd21.png)

**Comment by Semphriss** [comment]
Reason found: The string is translated before the translation settings are loaded.
![image](https://user-images.githubusercontent.com/66701383/146685950-106a10f8-1845-49f2-bf16-fd93dd4f003b.png)

Static variables are initialized before main() is run, which means that the translation function won't work.

Fix coming soon.
