### ISSUE TITLE
(WEB VERSION) Some textures wont load.

### ISSUE THREAD

**Issue by bruhmoent** [SuperTux/supertux#1983]
**SuperTux version: 0.6.3 - beta -2 **
**System information:** *Web Version by Semphris*

##### Expected behavior
![image](https://user-images.githubusercontent.com/69918580/146686075-d09dd316-2e99-4e21-81ca-04d398f0eb2d.png)

##### Actual behavior

![image](https://user-images.githubusercontent.com/69918580/146686169-b42b5b5a-c942-4c27-89d0-05745a19f6ac.png)

More: Forest, Halloween World, Narre's Land, more.

**Comment by Semphriss** [comment]
Issue is on me.

All images that don't load are JPEG images. At the time of doing the Emscripten port, I forgot we had JPEGs and thought images were all PNGs, so I told Emscripten to compile only PNG support. I'll do the fix ASAP.
