### ISSUE TITLE
Dev pics are missing

### ISSUE THREAD

**Issue by AndrePinheiroPT** [SuperTux/supertux#1994]
**SuperTux v0.6.3 beta 2**
**https://supertux.semphris.com/play/** *windows 10*

##### Expected behavior
The pictures of orginial devs are appearing correctly

##### Actual behavior
The pictures don't appear.
![Capturar](https://user-images.githubusercontent.com/62772813/146762965-f8881c58-3b84-423b-ad3d-fd10e3289d2a.JPG)
##### Steps to reproduce actual behavior
1. Go to the credits using menu.

**Comment by Zwatotem** [comment]
Closing due to being duplicate. Sorry for the chaos.
