### ISSUE TITLE
Problem with tinytext library

### ISSUE THREAD

**Issue by spider2016** [SuperTux/supertux#200]
```
-rwxr-xr-x 1 chaos chaos   159784 окт 21 08:32 libtinygettext.so
-rwxr-xr-x 1 chaos chaos 10471216 окт 21 09:19 supertux2
```

And when i tryed to oper supertux2:
```
$ ./supertux2 
./supertux2: error while loading shared libraries: libtinygettext.so: cannot open shared object file: No such file or directory
```

I compiled library tinygettext via https://github.com/tinygettext/tinygettext but i can see error and supertux2 is not working.
I think? that problem with 64/32 bit versions. Please make 64bit version of libtinygettext.so

```
$ ldd ./supertux2  | grep tiny
libtinygettext.so => not found
 ibnssutil3.so => /lib64/libnssutil3.so (0x0000003334800000)
```

**Comment by brmbrmcar** [comment]
I think it wants Supertux/tinygettext.

**Comment by maxteufel** [comment]
Is this (`supertux2`) built from the git repository? If so, please get the submodules and cmake will automatically use them upon compilation.

What's happening is that `libtinygettext.so` isn't in your library path (no wonder when the `supertux2` binary is in the same directory, I have **no** idea how you got this), it has nothing to do with 64-bit versions.

It would be great if you'd provide more information.

**Comment by spider2016** [comment]
git:
http://paste.fedoraproject.org/283204/14456861/
cmake
http://paste.fedoraproject.org/283205/45686432/

**Comment by spider2016** [comment]
about libtinygettext.so i only usee clone git and cmake tinytext library

**Comment by maxteufel** [comment]
> about libtinygettext.so i only usee clone git and cmake tinytext library
> them make and make install in local directory. This scheme worked one year

tinygettext is included as a submodule (once for simplicity, and also because we've [forked it](https://github.com/SuperTux/tinygettext)).

Not using the standard procedure for building (or at least you should use <https://github.com/SuperTux/tinygettext>) isn't supported and renders this issue invalid. If building as described in [INSTALL.md](https://github.com/SuperTux/supertux/blob/master/INSTALL.md) doesn't work, open another issue.

**Comment by spider2016** [comment]
Hello again! I have new error!
Please tell me? what i did wrong?
I'm doing the same as six months ago. Everything worked six months ago.
1)git clone --recursive https://github.com/SuperTux/supertux
directory has directory with tiny library and squirel library.
2)  cd directory supertux
and after that:
git submodule update --init --recursive ./ 
i see empy at the screen.
3) mkdir build; cd build
4) cmake ../ -DCMAKE_INSTALL_PREFIX=/home/chaos/T9/
5) make
Without any errors and warning!!!
6) make install
after that I see error:

$ ./supertux2 
./supertux2: error while loading shared libraries: libtinygettext.so: cannot open shared object file: No such file or directory
Than i try to add this library:
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib/
ldd supertux2  | grep tiny
libtinygettext.so => /usr/local/lib/libtinygettext.so (0x00007f5ed1d8b000)
And now I can see new error:
./supertux2: undefined symbol: _ZN11tinygettext17DictionaryManagerC1ESt10unique_ptrINS_10FileSystemESt14default_deleteIS2_EERKSs

**Comment by maxteufel** [comment]
> And now I can see new error:
> `./supertux2: undefined symbol: _ZN11tinygettext17DictionaryManagerC1ESt10unique_ptrINS_10FileSystemESt14default_deleteIS2_EERKSs`

That is because you installed to `/home/chaos/T9/` (as seen below), but now are trying to use another, (older/newer) version of `libtinygettext.so` located in `/usr/local/lib`. Using a library version different to the one the binary is linked to can and will cause problems.
