### ISSUE TITLE
Arabic not displayed correctly in 0.6.3 Windows builds

### ISSUE THREAD

**Issue by tobbi** [SuperTux/supertux#2011]
**SuperTux version:** 0.6.3
**System information:** Windows, x64

##### Expected behavior
Arabic not displayed properly

##### Actual behavior
Arabic displayed properly

##### Additional debugging information
The Arabic text direction is not properly set on Windows. It appears that we're  installing, but not detecting libraqm during the CI build. Check https://github.com/SuperTux/supertux/runs/4612250458?check_suite_focus=true for a log file.

**Comment by Semphriss** [comment]
(Changing the tag because this isn't an issue with translations, but an issue with our rendering engine)

**Comment by tobbi** [comment]
Fixed by https://github.com/SuperTux/supertux/commit/72d76ef23d7f0945942805b4300154c05884f598
