### ISSUE TITLE
¿Why The path of secret level of Ice Island is deleted?

### ISSUE THREAD

**Issue by SalomonDFanSuperTux** [SuperTux/supertux#2013]
SuperTux Version: 0.6.3
I was super excited of the new update of the game, and because of that i wanted to see every new thing that the creators put.
And when i wanted to see the secret level of Ice island, i noticed that the path is deleted, but ¿why?
Only i can acced to the level with cheats, and when i check with a cheat all path of the worldmap...

![bruh](https://user-images.githubusercontent.com/74196506/147266367-fa631d2c-670f-4ee8-8a1c-5788fed883a9.JPG)

I don't know if this is an error of design, or if they do it because yes (Probably not).
Hope in the new update they fix this...

Sign,
SuperTuxFan SalomonD

**Comment by weluvgoatz** [comment]
You have to find the secret exit in Icy Valley, which will unlock the path.
