### ISSUE TITLE
Untranslated strings

### ISSUE THREAD

**Issue by Narre** [SuperTux/supertux#2015]
**SuperTux version:** 0.6.3 (one of the commits right after it)
**System information:** not applicable

I compiled a list of strings in the game that aren't on Transifex and are therefore not translated in any language. I set the game to Czech and tried to check everything I could, but I might have easily missed something. If you know of any other strings missing in the translations, please share them here.

The following strings aren't translated (Czech is 100% transated on Transifex, these are all missing from there):

- half of the particle editor(see images below)
- the titles of Halloween Special and Community Island (the strings on Transifex are "Halloween 2014" and "Community Island 2016", but the titles have been changed in game to "Halloween Special" and "Community Island")
- the entirety of "Christmas Special" and "Revenge in Redmond"
- the descriptions (the text box at the bottom of the screen) for these: *both entries in the "Integrations and Presence" menu; *every single official contrib worldmap (Bonus Islands, RiR, Christmas, Community, Haloween)
- the forest intro cutsene ("A New Location") and the Tower of Ghosts cutscene (there are typos there BTW - " an Tropical " instead of " a Tropical ", and " Noloks' " instead of " Nolok's " )
- names of languages (probably fine in the language selection menu but should be fixed in the credits)

![untranslated1](https://user-images.githubusercontent.com/14074789/147290330-4f871aaf-23bb-4551-a6f5-0f9bbb5f0fc5.png)
![untranslated2](https://user-images.githubusercontent.com/14074789/147290332-06b04fa5-d57d-4804-a96c-c3d8f17672ef.png)
![untranslated3](https://user-images.githubusercontent.com/14074789/147290335-069da17f-ba88-40ef-a89a-700c1f0bb3e2.png)
![untranslated4](https://user-images.githubusercontent.com/14074789/147290339-75209ef4-d8d7-42f5-96cc-34f26562e7ee.png)
![untranslated5](https://user-images.githubusercontent.com/14074789/147290347-36c9791c-8000-422c-b32e-887acbe3fec5.png)
![untranslated6](https://user-images.githubusercontent.com/14074789/147290895-e22c9b82-e655-4472-ac80-222a21dc84cb.png)

**Comment by Semphriss** [comment]
Already fixed for the Discord integration strings, looking for the others

**Comment by serano01** [comment]
https://github.com/SuperTux/supertux/commit/e0408467073cf0589174986713549e19dbb4a03d

I have fixed the spelling errors in the "Tower Of Ghosts"-Cutscene.
