### ISSUE TITLE
Opening the particle configuration the game closes in windows 10 (11).

### ISSUE THREAD

**Issue by jojocarlos** [SuperTux/supertux#2024]
In the new stable version of SuperTux 0.6.3 and older night builds:
When I open a particle file, the game closes. Or after having loaded the particle when opening the particle editor it closes. But if you copy a one-level particle file, it doesn't close. This one after loaded does not execute the loaded particle but sparkles all over the screen.

**Particle setting after opening, which does not work:**
```
(particles-custom-file
      (texture
        (surface "/images/engine/editor/sparkle.png")
        (color_r 1)
        (color_g 1)
        (color_b 1)
        (color_a 1)
        (likeliness 1)
        (scale_x 1)
        (scale_y 1)
      )
      (z-pos -90)
      (file "generic\\leaves.stcp")
    )
```
**Setting the particle that works:**

    (particles-custom-file
      (texture
        (surface "particles/generic/leaf.png")
        (color_r 1)
        (color_g 1)
        (color_b 1)
        (color_a 1)
        (likeliness 1)
        (scale_x 1)
        (scale_y 1)
      )
      (texture
        (surface "particles/generic/leaf.png")
        (color_r 1)
        (color_g 1)
        (color_b 1)
        (color_a 1)
        (likeliness 1)
        (scale_x 0.75)
        (scale_y 0.75)
      )
      (z-pos -95)
      (name "leaves")
      (file "generic/leaves.stcp")
    )

**Comment by Semphriss** [comment]
Can you upload the `console.err` file? You can find it in `C:\Users\[you]\AppData\Roaming\supertux2`.

I believe I already know what's going on; PhysFS does not support backslashes in file names. Normally, it should be fixable temporarily by manually changing `(file "generic\\leaves.stcp")` to `(file "generic/leaves.stcp")`.

**Comment by jojocarlos** [comment]
> Can you upload the `console.err` file? You can find it in `C:\Users\[you]\AppData\Roaming\supertux2`.
> 
> I believe I already know what's going on; PhysFS does not support backslashes in file names. Normally, it should be fixable temporarily by manually changing `(file "generic\\leaves.stcp")` to `(file "generic/leaves.stcp")`.

[console.zip](https://github.com/SuperTux/supertux/files/7777095/console.zip)

Sorry for closing the thread, I was wrong I'm not used to using this.

**Comment by tobbi** [comment]
@jojocarlos Did you try the fix that @Semphriss suggested (changing the escaped backslashes to forward slashes)?

**Comment by jojocarlos** [comment]
Yes, I did. It worked perfectly, the particle editor opened well.
As mentioned above, this must be an error.
