### ISSUE TITLE
Icecrushers don't propagate movement on some objects

### ISSUE THREAD

**Issue by weluvgoatz** [SuperTux/supertux#2038]
A bug I noticed is that the icecrusher will not propagate movement on frozen badguys, rocks, or scripted objects.  It should be noted that icecrushers and these objects are all movingstatics (in COLGROUP_MOVING_STATIC), and that other movingstatics that I *assume* would be loaded before the icecrushers due to their alphabetic placement (falling blocks, dispensers) or recency in creation (frozen enemies are created and loaded after icecrushers since they can't be instantly created at the start of the level) allow the icecrusher to propagate their movement perfectly fine.  And objects of other colgroups (specifically COLGROUP_MOVING), such as players, powerups, etc. also allow icecrusher propagation, and other COLGROUP_STATIC objects that propagate objects propagate them all.  So maybe this was an oversight with movingstatics when movement propagation was added?

**Comment by Zwatotem** [comment]
So you're saying, that if there's a frozen enemy under an icecrusher, it'll land 1-3 tiles higher than it should?

**Comment by Alasdairbugs** [comment]
I think you can basically throw stuff at ice crushers and it will move them is what this PR is saying. unless im misunderstanding it

**Comment by weluvgoatz** [comment]
What I mean is that you can throw a rock at a moving icecrusher and it pushes the icecrusher down quickly, which looks really weird and jarring because the rock is so much smaller than a tough icecrusher, and it breaks the opportunity for some puzzles involving rocks (and similar objects) and icecrushers.
