### ISSUE TITLE
Bonus islands 1+2 levels have no licenses specified

### ISSUE THREAD

**Issue by brmbrmcar** [SuperTux/supertux#204]

**Comment by Hume2** [comment]
There are two options:
1) Manipulate the license
2) As of I'm the restaurator of those levels, we can say that I am the author of these levels. Therefore I can specify the license.

Choose what you want, but the result is the same.

**Comment by sydneyjd** [comment]
Might as well just change the licence. This is not a big deal though.

**Comment by Hume2** [comment]
@sydneyjd option 1 or 2?

**Comment by sydneyjd** [comment]
Probably Option 2.

**Comment by brmbrmcar** [comment]
Yes, but doesn't everyone have a big deal about it having to be licensed under GPL.

**Comment by brmbrmcar** [comment]
Sorry about typo...

**Comment by Hume2** [comment]
@brmbrmcar please test the pull request #126 if you can. If you can't, it doesn't matter. After that update, each level will be restaured, so the original authors will have no claim to them. And then option 2.

**Comment by brmbrmcar** [comment]
I like the changes a lot.

**Comment by Hume2** [comment]
I have to do some chenges though. But Thank you. Now I can say that someone has tested it.

**Comment by brmbrmcar** [comment]
I like the way you made the first Bonus Island 2 level easier. It is a much better difficulty now.
