### ISSUE TITLE
Credits As A Seperate Level

### ISSUE THREAD

**Issue by Karkus476** [SuperTux/supertux#205]
The credits would be a level much like [in super mario bros. wii](https://youtu.be/1gDzHncTHwY?t=1m5s), which would make it really fun I think. It's a silly idea, but here's a place to put any ideas for what the level could be like, too, rather than copy Nintendo if we decide to implement this.

**Comment by sydneyjd** [comment]
This woudl be cool, but honestly i would find it slightly annoying. What does everyone else think?

**Comment by brmbrmcar** [comment]
Awesome.

**Comment by brmbrmcar** [comment]
Allow the player to play though.

**Comment by brmbrmcar** [comment]
The music is a bit too sad for it though.

**Comment by Karkus476** [comment]
@brmbrmcar Yes, I believe if this was implemented a music change would be essential. Quite why the music is sad anyway is a bit odd. Should be happy music, it's not like the developers have died!

**Comment by brmbrmcar** [comment]
Yes! I got a bit scared of it because of the music.

**Comment by maxteufel** [comment]
@SuperTux/level-designers Ideas and or proposals are welcome!

**Comment by weluvgoatz** [comment]
I am currently working on this issue! :D

**Comment by Rusty-Box** [comment]
This has now been implemented. I am closing this.
