### ISSUE TITLE
Star powerup music doesn't pause on level pause

### ISSUE THREAD

**Issue by Vankata453** [SuperTux/supertux#2057]
**SuperTux version:** 0.6.3
**System information:** Windows 10

##### Expected behavior
When a player gets the star powerup and pauses the level, the powerup's music pauses too.
##### Actual behavior
When a player gets the star powerup and pauses the level, the powerup's music continues to play, which also makes it out of sync when playing the level.
##### Steps to reproduce actual behavior
Get the star powerup in a level, then pause. Unpause a few seconds after.
***
Another issue is that the beginning sound, before the star powerup's music plays, stops playing altogether, when the level is paused.

**Comment by Semphriss** [comment]
I fixed this in #2043 as the code has been edited there; if there isn't a pressing need to fix this issue, I would like to request that it doesn't get fixed again on master to avoid complexity when rebasing the PR.
