### ISSUE TITLE
Poll: Which Wiki?

### ISSUE THREAD

**Issue by Karkus476** [SuperTux/supertux#208]
Vote here on which wiki we should use for information on the supertux game
1) Only [The Old Wiki](http://supertux.lethargik.org/wiki/Main_Page)
2) Only [The GitHub Wiki](https://github.com/SuperTux/supertux/wiki)
3) Both 1 & 2
4) Other (please specify)
Any vote which does not clearly state 1 - 4 may not be counted
This poll should remain open until 2016 at a minimum

**Comment by sydneyjd** [comment]
Why did you open this?  We have been relying on both wiki's untill everything gets transfered over to Github's wiki. Currently that is far from beign finished. 
Also, very few of us have write access to the old wiki.

**Comment by Karkus476** [comment]
But neither wiki is complete, and I like the old wiki more than the new wiki. If this decision has already been made I apologise, I was just unsure as to what the intention was exactly concerning the wikis. If this is the case, a strong effort needs to be made to transfer the data across

**Comment by Karkus476** [comment]
Can we not get access to the old wiki?

**Comment by sydneyjd** [comment]
Its possible, but not easy. We had made up our minds to use the github wiki when we transfered to github,  and still plan on it, but no one has gotten around to transfering stuff.

I will close this issue then.

**Comment by sydneyjd** [comment]
Also, the old wiki's server could go down at any time, since its not really maintained anymore.

**Comment by brmbrmcar** [comment]
Old one.

**Comment by Karkus476** [comment]
@sydneyjd Please can we just see what people think?

**Comment by brmbrmcar** [comment]
How can this thing be opened?

**Comment by Karkus476** [comment]
I can open it, but I've been explicitly told not to, so I won't

**Comment by brmbrmcar** [comment]
By who?

**Comment by Karkus476** [comment]
@sydneyjd

**Comment by brmbrmcar** [comment]
What if you open it?

**Comment by sydneyjd** [comment]
@tobbi what do you think? :)

**Comment by brmbrmcar** [comment]
Old one!

**Comment by tobbi** [comment]
I think that transferring the wiki pages is quite a lot of work... So, maybe we should have both of them coexist.

**Comment by Karkus476** [comment]
I think that both wikis should exist for the time being, but ultimately the GitHub wiki should be based around development of SuperTux and actually getting the game running. The old wiki can be used for gameplay, as it is not updated as frequently. We should keep a backup of the old wiki in a SuperTux repo. Therefore I vote 3

**Comment by Hume2** [comment]
Option 2.
The old wiki contains many hoaxes, so it should be rewritten anyway. I'd recommend to throw the old one away and make a brand new.

**Comment by brmbrmcar** [comment]
Option 1.

**Comment by Hume2** [comment]
I changed my opinion to 1. The github wiki seems me not suitable, because the sidebar displays all pages and the sidebars and footers are the same in all pages, so after the github wiki gets all the content from the old wiki, everyone will be just lost in all those pages. So I recommend  using the old wiki. There's just one problem: I can't access locked pages because of Giby.

**Comment by brmbrmcar** [comment]
And you just deleted your user page on there.

**Comment by Hume2** [comment]
It was outdated. I'd like noone see what was there.

**Comment by brmbrmcar** [comment]
OK.

**Comment by brmbrmcar** [comment]
very few of us have write access to the old wiki.

Really?

**Comment by sydneyjd** [comment]
@brmbrmcar Yes really.

**Comment by brmbrmcar** [comment]
???

**Comment by Karkus476** [comment]
@sydneyjd It is okay, @tobbi and @LMH0013 are 2 examples of people who can edit the wiki and, if they should wish, give others the ability to edit it too.

**Comment by brmbrmcar** [comment]
I have an account.

**Comment by maths22** [comment]
@sydneyjd Since the wiki server is apparently not currently maintained, if there is interest, I have access to a server it could be transferred to (it is used for hosting some other open source projects' pages and such).  Also, if people are interested, I could work on spam prevention with the existing wiki so that it access could be less restricted (A combination of well-used spam filters and captchas for new contributions is extremely effective at reducing spam.)

**Comment by sydneyjd** [comment]
I still wish to use github for our wiki, since everything else we have is there. We honestly don't need another server. What we have is dated and Barely supported/works, but it still does the job.

**Comment by Karkus476** [comment]
Hmmm as far as I know, media wiki is well supported still, and is a solid base for a good wiki. I prefer the look of it over the disorganised GitHub wiki. Not our fault though, GitHub does not allow the flexibility in markdown.

**Comment by symvizan** [comment]
Gamepedia.

**Comment by Karkus476** [comment]
@symvizan I don't think so. We are trying to keep our resources in one place, with the website, old wiki, GitHub and the forums everything is becoming spread loosely

**Comment by Karkus476** [comment]
We should move as much as possible over to GitHub.

**Comment by Karkus476** [comment]
This was discussed in the meeting, and an alternative solution was agreed upon.
