### ISSUE TITLE
Music Stops During Gameplay

### ISSUE THREAD

**Issue by Karkus476** [SuperTux/supertux#209]
Sometimes the music will stop randomly while I am playing, only to continue if I pause and unpause. I'm on Linux Mint 17.2, if you need more info just ask.

**Comment by brmbrmcar** [comment]
It happens to me occasionally.

**Comment by tobbi** [comment]
Does reverting 8e52a5b000d732e96b1cc461163c4778b434dc27 fix it?

**Comment by brmbrmcar** [comment]
I cannot compile Supertux.

**Comment by tobbi** [comment]
Error message?

**Comment by brmbrmcar** [comment]
For what?

**Comment by tobbi** [comment]
What problems do you have while compiling?

**Comment by brmbrmcar** [comment]
I don't have any SDL stuff. I can't compile it successfully.

**Comment by Karkus476** [comment]
I cannot right now as I have not got my laptop, but when I get the chance I will revert and test without that. The trouble is, I cannot really confirm as it does not always happen.

**Comment by Karkus476** [comment]
But idk how to fix the conflicts :/

**Comment by maxteufel** [comment]
Please reopen if you can reproduce it.

**Comment by PrinceRilian** [comment]
OK, I caught the bug in the act!  I have the backtrace attached to this message.

[WinDbg_Backtrace_Music_Stopped_when_Tux_Died.txt](https://github.com/SuperTux/supertux/files/1079515/WinDbg_Backtrace_Music_Stopped_when_Tux_Died.txt)
