### ISSUE TITLE
The size of the menu is not constant.

### ISSUE THREAD

**Issue by tdadela** [SuperTux/supertux#2100]
SuperTux version: 0.6.3, 0.6.2, possibly earlier
System information: GNU/Linux Ubuntu 21.10, kernel: 5.13.0

##### Expected behavior
While using, I expect a menu to not change a width.

##### Actual behavior
The size of the menu is not constant.
When I move down from the "Window resizable" to the "Window resolution", the menu widow gets wider.
The change occurs just one time. If I reopen the menu, the menu stays fixed in size.
There is no difference between using the down arrow ↓ or mouse. 
I recorded the bug:
https://www.youtube.com/watch?v=bE_RTmVWtZE
I set a small resolution just for recording. With higher resolution and normal window size, a change in size is larger (than in recording).

##### Steps to reproduce actual behavior
1. Open SuperTux (It's important to use freshly opened application).
2. Go to Options.
3. Click the arrow down ↓ four times.

##### Additional debugging information
I tried the latest available SuperTux Snap, APT, AppImage, built from the source versions on Ubuntu 21.10 with Xfwm4 window manager and the latest Pacman version on Manjaro ARM with i3 window manager.
The problem is always precisely the same – one change in menu size.

**Comment by Zwatotem** [comment]
Does this occur only in this one particular scenario and no other?

**Comment by tdadela** [comment]
Case 0:
open SuperTux → open Options → go down 4 times → BUG → go up/down a few times → NO BUG → close Options → open Options → go down 4 times → NO BUG → close Options → click Start Game → play one level → return to the main menu → open Options → go down 4 times → NO BUG

Case 1:
open SuperTux → open Options → go down 4 times → BUG
Case 2:
open SuperTux → open Options → close Options → open Options→ go down 4 times → NO BUG
Case 3:
open SuperTux → Start Game → play one level → return to the main menu → open Options → go down 4 times → BUG
Case 4:
open SuperTux → Start Game → play one level → return to the main menu → open Options → close Options → open Options→ go down 4 times → NO BUG

**Comment by Semphriss** [comment]
Is this bug really specific to GNU/Linux? This seems to me like a code logic issue more than a platform issue.

**Comment by Vankata453** [comment]
I think this bug appears in the level editor menu too. The platform isn't a factor, since it's an issue with the menus themselves.

**Comment by Zwatotem** [comment]
Confirmed on Windows as well (and macOS). I suppose it appears in places, where there is this `Name        <value>` control.

**Comment by Semphriss** [comment]
I suppose automatic resizing is an expected behavior. Supposing there is a text flied, someone filling the text field should make the menu resize to adapt to its contents.

**Comment by tdadela** [comment]
> I suppose automatic resizing is an expected behavior. Supposing there is a text flied, someone filling the text field should make the menu resize to adapt to its contents.

Resizing happens without content change.

**Comment by Semphriss** [comment]
> Resizing happens without content change.

It does happen on user interaction, though.

**Comment by Grumbel** [comment]
There are two issues at play here. First is the menu size changing when the selected item changes. That's not necessarily a bug, but a little ugly. Calculating the size based on the largest items seems more sensible.

The other issue is an actual bug, the size changes when you hover over the item. This shouldn't happen and is caused by the size calculation returning different results depend on if the highlighted text surface is cached or hasn't yet been generated.

#2101 fixes both of them.
