### ISSUE TITLE
Blue Rock Forest Images don't load

### ISSUE THREAD

**Issue by L-UwU-13** [SuperTux/supertux#2108]
SuperTux version: 0.6.3
I use Windows 11 Pro

On 0.6.2 the images worked verry well 

Now everything is replaced by dummy texture ![BlueRock_Forest_Test](https://user-images.githubusercontent.com/97864334/149703752-4af42ad1-386e-4591-996a-2b6e5fdea7dd.png)

When you select BlueRock Forest Textures (Top, middle, and bottom)

- [x] I have read <https://github.com/SuperTux/supertux/blob/master/CONTRIBUTING.md#bug-reports>.
- [x] I verified this isn't an issue that's already been reported.
- [x] This report only includes details about **one** (1) issue, feature request or topic.
- [x] If I make a mistake while submitting this report I will use the edit feature instead of closing this issue and opening a new one.
- [x] This issue is **not** about wrong translations (use Transifex for those), or anything unsupported (e.g. third-party add-ons).
- [x] Once you're done, please remove the section 'Guidelines for reporting issues', the 'Additional debugging information' if it is empty, and any text in *italic font*.

**Comment by tobbi** [comment]
@L-UwU-13  Is this still an issue with the builds from https://download.supertux.org/ ?

**Comment by L8558** [comment]
> @L-UwU-13 Is this still an issue with the builds from https://download.supertux.org/ ?

Sorry, I wasn't able to find my old account. No, in recent nightly download versions, this doesn't happen. I don't know if it keeps happening now, but back then it was an error only on the Steam version.

**Comment by Vankata453** [comment]
I believe this involves missing JPEG loading support on the Steam build.

**Comment by tobbi** [comment]
Was this fixed?

**Comment by tobbi** [comment]
I believe #2292 is about the same issue. Can I close this as duplicate?

**Comment by Vankata453** [comment]
@tobbi Yes.
