### ISSUE TITLE
Change email on Google Play SuperTux app listing

### ISSUE THREAD

**Issue by pelya** [SuperTux/supertux#2109]
**SuperTux version:** 0.6.3
**System information:** Android

##### Expected behavior

The email here should belong to someone like Semphris:

https://play.google.com/store/apps/details?id=org.lethargik.supertux2&hl=en_US&gl=US

##### Actual behavior

The listing still contains my email

##### Steps to reproduce actual behavior

Go to https://play.google.com/store/apps/details?id=org.lethargik.supertux2&hl=en_US&gl=US

**Comment by Semphriss** [comment]
I updated everything, asked for the team's email, got the team's email, and forgot to update it.

Thanks for the catch! :smile:
