### ISSUE TITLE
AppImage not working on NixOS

### ISSUE THREAD

**Issue by davidak** [SuperTux/supertux#2112]
**SuperTux version:** latest steam linux version

![Screenshot from 2022-01-22 18-32-05](https://user-images.githubusercontent.com/91113/150649305-78baf482-8ed6-4b0b-8d99-a0210f1b6b53.png)

**System information:** NixOS 21.11.335130.386234e2a61, Kernel 5.10.90, glibc 2.33

##### Expected behavior

games on steam should just work

##### Actual behavior

game does not start

##### Steps to reproduce actual behavior

Use Steam on NixOS.

##### Additional debugging information

This is what steam outputs to the terminal when i start the game:

```
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
GameAction [AppID 1572920, ActionID 2] : LaunchApp changed task to DownloadingDepots with ""
GameAction [AppID 1572920, ActionID 2] : LaunchApp changed task to DownloadingDepots with ""
GameAction [AppID 1572920, ActionID 2] : LaunchApp changed task to ProcessingInstallScript with ""
GameAction [AppID 1572920, ActionID 2] : LaunchApp changed task to SynchronizingCloud with ""
GameAction [AppID 1572920, ActionID 2] : LaunchApp changed task to SynchronizingControllerConfig with ""
GameAction [AppID 1572920, ActionID 2] : LaunchApp changed task to SiteLicenseSeatCheckout with ""
GameAction [AppID 1572920, ActionID 2] : LaunchApp changed task to CreatingProcess with ""
GameAction [AppID 1572920, ActionID 2] : LaunchApp waiting for user response to CreatingProcess ""

GameAction [AppID 1572920, ActionID 2] : LaunchApp continues with user response "CreatingProcess"
Could not connect to X session manager: None of the authentication protocols specified are supported
Could not connect to X session manager: None of the authentication protocols specified are supported
GameAction [AppID 1572920, ActionID 2] : LaunchApp failed with AppError_28 with "/home/davidak/.local/share/Steam/steamapps/common/SuperTux/SuperTux.AppImage"
GameAction [AppID 1572920, ActionID 2] : LaunchApp changed task to Failed with ""
```

Distro issue: https://github.com/NixOS/nixpkgs/issues/155278

Like with other steam linux issues, the most elegant and portable solution seem to be to target the steam linux runtime.

Related to https://github.com/SuperTux/supertux/issues/2083

**Comment by pazkero** [comment]
https://github.com/AppImage/pkg2appimage/blob/master/excludelist

Try checking if some of these libraries are missing on Nix for now; There's not much documentation about this class of error.

Try also running it outside Steam, if possible with a debugger

**Comment by Grumbel** [comment]
Launching the appimage manually from command line like this works for me on NixOS:

    appimage-run ./SuperTux.AppImage

Launching it through Steam however gives the same error:

    dlopen(): error loading libfuse.so.2

**Comment by necrophcodr** [comment]
Did you try setting the launch parameters for the Steam game to `appimage-run %command%`? This might work around your current issue, even if it is not a solution.

**Comment by tobbi** [comment]
The linked distro issue was closed as completed. I've asked the maintainer what's up with that, so maybe this can get closed as well.

**Comment by tobbi** [comment]
Closing as per https://github.com/NixOS/nixpkgs/issues/155278#issuecomment-2278631075
