### ISSUE TITLE
Frozen bomb drops straight down when thrown

### ISSUE THREAD

**Issue by ztianyang** [SuperTux/supertux#2113]
**SuperTux version:** supertux2 v0.6.3-209-g70226f163
**System information:** Ubuntu 20.04.3

##### Expected behavior
Throwing frozen bomb is like throwing rocks or trampolines.

##### Actual behavior
Frozen bomb drops straight down when thrown.

##### Steps to reproduce actual behavior
Freeze a bomb with ice bullet, then throw the frozen bomb.

https://user-images.githubusercontent.com/59285502/150665633-f792a882-c2a1-4b78-bd8f-455baa8595c2.mp4

**Comment by Semphriss** [comment]
Related to #683

Many badguys can't be carried at all in frozen form, including haywires and jumpys.

**Comment by Alasdairbugs** [comment]
bombs should not be thrown like ice cubes

**Comment by ztianyang** [comment]
Fixed in nightly
