### ISSUE TITLE
Segfaults on some modified levels

### ISSUE THREAD

**Issue by elf-sisungo** [SuperTux/supertux#2114]
**SuperTux version:** 0.6.3
**System information:** *Arch Linux, 20220123 latest, Linux 5.16.2-arch1-1*

##### Expected behavior
Working normally

##### Actual behavior
Signal 11(SIGSEGV) received, then it exits

##### Steps to reproduce actual behavior
1. Play a special-modified level
2. Reach a specified point

##### Additional debugging information
    Error: signal 11:
    /usr/bin/supertux2(_ZN12ErrorHandler17print_stack_traceEv+0x30)[0x55d41851ead0]
    /usr/bin/supertux2(_ZN12ErrorHandler12handle_errorEi+0x3f)[0x55d41851eb6f]
    /usr/lib/libc.so.6(+0x3cda0)[0x7f48e2d63da0]
    /usr/bin/supertux2(+0x42e63d)[0x55d4186be63d]
    /usr/bin/supertux2(_ZN7SkyDive6ungrabER12MovingObject9Direction+0x5f)[0x55d4185aca8f]
    /usr/bin/supertux2(_ZN3Owl9kill_fallEv+0xdc)[0x55d4185a536c]
    /usr/bin/supertux2(_ZThn120_N9Explosion9collisionER10GameObjectRK12CollisionHit+0x82)[0x55d418606e42]
    /usr/bin/supertux2(_ZNK15CollisionSystem16collision_objectEP15CollisionObjectS1_+0x1af)[0x55d41846a94f]
    /usr/bin/supertux2(+0x1def42)[0x55d41846ef42]
    /usr/bin/supertux2(_ZN6Sector6updateEf+0xae)[0x55d41843cbce]
    /usr/bin/supertux2(_ZN11GameSession6updateEfRK10Controller+0x5e0)[0x55d418538de0]
    /usr/bin/supertux2(_ZN13ScreenManager16update_gamelogicEf+0x60)[0x55d41843b360]
    /usr/bin/supertux2(_ZN13ScreenManager9loop_iterEv+0x1b9)[0x55d41843fd29]
    /usr/bin/supertux2(_ZN4Main11launch_gameERK20CommandLineArguments+0xcc9)[0x55d418411949]
    /usr/bin/supertux2(_ZN4Main3runEiPPc+0x5ac)[0x55d418412b3c]
    /usr/bin/supertux2(main+0x85)[0x55d4183ec745]
    /usr/lib/libc.so.6(__libc_start_main+0xd5)[0x7f48e2d4eb25]
    /usr/bin/supertux2(_start+0x2e)[0x55d4183f06fe]

**Comment by mrkubax10** [comment]
Could you attach level that is crashing?
