### ISSUE TITLE
The RTL text is reversed

### ISSUE THREAD

**Issue by omeritzics** [SuperTux/supertux#2123]
**SuperTux version:** 0.6.3
**System information:** N/A

##### Expected behavior
The RTL text should not reverse.

##### Actual behavior
The RTL text has reversed. Additionally, the Arabic letters are not connected.

##### Steps to reproduce actual behavior
Use SuperTux with an RTL localization (Hebrew, Arabic, ...).

##### Screenshots
Arabic:
![supertux-arabic](https://user-images.githubusercontent.com/66558205/151213596-e997bf0d-7b83-4e39-a763-f5efce30c7a9.png)

Hebrew:
![supertux-hebrew](https://user-images.githubusercontent.com/66558205/151213686-15a88133-b844-4f3a-b063-69ba38c30d6b.png)

How the Hebrew version should be like:
![109401513-e5d52980-7957-11eb-8e54-11cae3f096b2](https://user-images.githubusercontent.com/66558205/151213753-2c7181f1-23fb-45b0-b687-ee109fa733e0.png)

##### Additional information
I'm sorry about my past 'contributions' on Github - which were more spamming than helping - from when I just started using Github; I'm also sorry about my English, which was not clear enough and made misunderstandings sometimes. Hope to make real contributions in the future.

**Comment by Semphriss** [comment]
I've checked the CI builds and it seems Windows builds don't pickup libraqm; I believe this might be a Windows-only problem, although not OS-related.

Do you have a macOS/Linux device to verify if this issue also happens on other OSes?

**Comment by tobbi** [comment]
I believe I've already fixed this, but after 0.6.3.

Please check the nightlies from http://download.supertux.org

**Comment by omeritzics** [comment]
Hi, I'm sorry for the late response.
Unfortunately, I cannot verify that this bug has happened on other OSes, but this bug has been fixed, as Tobby wrote.

Thank you!!
