### ISSUE TITLE
Add sprite for butt-jumped Iceblock and frozen spiked enemies

### ISSUE THREAD

**Issue by brmbrmcar** [SuperTux/supertux#215]
Instead of falling off the screen.

**Comment by Karkus476** [comment]
Also enemies hit from underneath should spin of the screen rather than just dropping. It startles me

**Comment by Hume2** [comment]
We have already something for butt-jumped frozen enemies. May I apply this animation for all fall-of-screen deaths?

**Comment by Karkus476** [comment]
@Hume2 What are you talking about? The squish animation?

**Comment by Hume2** [comment]
Freeze a jumpy and then butt-jump. That's what I'm talking about. It's commit https://github.com/SuperTux/supertux/commit/f9b0133338e790a8286c0a948576782790b43040

**Comment by tobbi** [comment]
I don't really like the shatter animation. It definitely needs to be reworked.

**Comment by Rusty-Box** [comment]
This has been implemented for frozen enemies. I am closing this.
