### ISSUE TITLE
Retro Music does not work when editing custom level

### ISSUE THREAD

**Issue by Zwatotem** [SuperTux/supertux#2150]
_(Original report on IRC)_

**SuperTux version:** Found in 2022-02-03 nightly
**System information:** Originaly reported on Linux, reproduced on Windows

##### Expected behavior

Music added from any subcatalog if music plays in the editor for custom level.

##### Actual behavior

Music from `retro` and `tropical` catalogs do not play. Instead there is a console message:
```
[WARNING] D:\a\supertux\supertux\src\audio\sound_manager.cpp:330 couldn't play music file
'retro\classic.music': Couldn't open file 'retro\classic.music': filename is illegal or insecure
```

##### Steps to reproduce actual behavior

1. Open Level editor
2. Create new World
3. Create new Level
4. Put blocks under Tux' feet
5. Change music to anything in `retro` or `tropical` catalogs
6. Test level

##### Additional debugging information
N/A

**Comment by Semphriss** [comment]
PhysFS does not support backslashes. Replacing the backslash with a forward slash should fix it.
