### ISSUE TITLE
Jump key press is no longer being registered after releasing up key

### ISSUE THREAD

**Issue by ztianyang** [SuperTux/supertux#2152]
**SuperTux version:** supertux2 v0.6.3-222-g536cac780
**System information:** Ubuntu 20.04.3

##### Expected behavior
The jump key press is still being registered by the game.

##### Actual behavior
The jump key press is no longer being registered.

##### Steps to reproduce actual behavior
1. Enable jump with up in keyboard settings.
2. Hold down the jump key.
3. Press the up key.
4. Release the up key.

https://user-images.githubusercontent.com/59285502/154414035-2a8f9365-aed9-4a9f-889e-f1c86e5d0e35.mp4

**Comment by mrkubax10** [comment]
I can't reproduce this issue, does it still happen on latest master?

**Comment by ztianyang** [comment]
Yes, it still happens on latest master.


https://user-images.githubusercontent.com/59285502/174696162-cc571d1e-36b5-4844-91cc-1a9200c3feb7.mp4
