### ISSUE TITLE
Changing the user directory doesn't affect console output files

### ISSUE THREAD

**Issue by Vankata453** [SuperTux/supertux#2158]
**SuperTux version:** 0.6.3
**System information:** Windows 10

##### Expected behavior
When the game's user directory gets changed for a session, using the `--userdir` parameter, the console output files get saved there as well.

##### Actual behavior
Everything else gets stored in the given directory, only the console output files are left in the default `supertux2` one.

##### Steps to reproduce actual behavior
Start the game in a different user directory (with the `--userdir` parameter) and notice where the console output files are saved.

![image](https://user-images.githubusercontent.com/78196474/156547298-5cbab274-08f0-457e-9253-97d309b26abd.png)
![image](https://user-images.githubusercontent.com/78196474/156547405-e6c050c0-6c7f-4f99-9caf-3271cf42d185.png)

**Comment by Semphriss** [comment]
Expected behavior. This happens because stdout/stderr must be redirected before anything is initialized, including the CLI arguments. I don't think this is fixable without breaking something else.

**Comment by mrkubax10** [comment]
It is fixable but argument parsing errors will appear in console instead of file which I think is actually better

**Comment by Semphriss** [comment]
Disagreement. Error messages location should be consistent. The output files aren't game files, they're debugging files, so it doesn't matter where they are.
