### ISSUE TITLE
Image recompression is overly agressive

### ISSUE THREAD

**Issue by Grumbel** [SuperTux/supertux#216]
Haven't looked into the details, but this last recompression of images was overly aggressive and lead to image formats that are no longer easily modifiable. This one for example:

    ./data/images/background/halloween/fog.png

Will show up in Gimp as indexed image with 1bit alpha, instead RGB with 8bit alpha channel. It still renders correctly in other viewers. So this might be a bug in in Gimp, either way, I would suggest to not convert into formats that are outside the normal 24bit RGB or 32bit RGBA to avoid that kind of trouble or better yet just not convert anything at all in the source directory. Make it an optional part of the build process if you have to.

-------

commit 8be7d1bee94ee53bdba7942db0a374c3e0d6bd83
Author: Tobias Markus <tobbi@mozilla-uk.org>
Date:   Sat Sep 12 21:07:50 2015 +0200

    Re-compress image files with latest ImageOptim
    [ci skip]

**Comment by brmbrmcar** [comment]
How about reversing the affected images for now, and deal with it after  0.4.0?

**Comment by Grumbel** [comment]
Original Image:

    ./data/images/background/halloween/fog.png...
      Image Width: 1280 Image Length: 256
      Bitdepth (Bits/Sample): 8
      Channels (Samples/Pixel): 4
      Pixel depth (Pixel Depth): 32
      Colour Type (Photometric Interpretation): RGB with alpha channel 
      Image filter: Single row per byte filter 
      Interlacing: No interlacing 
      Compression Scheme: Deflate method 8, 32k window
      Resolution: 2835, 2835 (pixels per meter)
      FillOrder: msb-to-lsb
      Byte Order: Network (Big Endian)
      Number of text strings: 1 of 9
        Comment (xTXt deflate compressed): Created with GIMP

-----
Recompressed image:

    ./data/images/background/halloween/fog.png...
      Image Width: 1280 Image Length: 256
      Bitdepth (Bits/Sample): 8
      Channels (Samples/Pixel): 1
      Pixel depth (Pixel Depth): 8
      Colour Type (Photometric Interpretation): PALETTED COLOUR with alpha (201 colours, 201     transparent) 
      Image filter: Single row per byte filter 
      Interlacing: No interlacing 
      Compression Scheme: Deflate method 8, 32k window
      Resolution: 0, 0 (unit unknown)
      FillOrder: msb-to-lsb
      Byte Order: Network (Big Endian)
      Number of text strings: 0 of 0

**Comment by tobbi** [comment]
Maybe we should revert the changes. I'm sorry, but there's no way for me to modify the compression parameters easily as I'm using a GUI tool called ImageOptim.

**Comment by brmbrmcar** [comment]
How much difference in size was there?

**Comment by Karkus476** [comment]
Unless anyone objects, this is Post 0.4.0

**Comment by tobbi** [comment]
Nope. I am pushing a fix right now.

**Comment by Karkus476** [comment]
Right :)
