### ISSUE TITLE
Add high resolution icon

### ISSUE THREAD

**Issue by deveee** [SuperTux/supertux#218]
Current icon doesn't look good i.e. under Gnome, which displays icons in 128x128 resolution by default.

I was always using this icon:
![supertuxportable_128](https://cloud.githubusercontent.com/assets/5108558/11011519/0b351190-84e9-11e5-8db3-b073947af72d.png)
which looks quite good. Unfortunately it was found somewhere in the web and I can't say anything about an author and license :(

**Comment by Karkus476** [comment]
In which case we probably can't use it. Please try to find a source, as this is a good idea

**Comment by tobbi** [comment]
Source: http://www.deviantart.com/art/Supertux-Dock-Icon-176711771

License: CC-BY-SA 3.0

**Comment by deveee** [comment]
It looks like here is the original icon:
http://sarrel.deviantart.com/art/Supertux-Dock-Icon-176711771
Created by Sarrel, under CC BY-SA 3.0 license

**Comment by tobbi** [comment]
Actually we have a 256px icon in the repository:
https://github.com/SuperTux/supertux/blob/master/data/images/engine/icons/supertux-256x256.png

**Comment by Karkus476** [comment]
@tobbi But this one's better I think.

**Comment by sydneyjd** [comment]
How about i make us a logo?

**Comment by sydneyjd** [comment]
icon*

**Comment by brmbrmcar** [comment]
Why not someone make a good vector graphic of the current one and allow up to 512x512?

**Comment by sydneyjd** [comment]
Here is what i have so far, its no beauty yet though
![4](https://cloud.githubusercontent.com/assets/8949851/11015437/18dc3dde-852d-11e5-999c-ca0a3e30a9e8.png)

**Comment by deveee** [comment]
My three years old son said:
- this one is strange:
https://cloud.githubusercontent.com/assets/8949851/11015437/18dc3dde-852d-11e5-999c-ca0a3e30a9e8.png
- this one is ugly:
https://raw.githubusercontent.com/SuperTux/supertux/master/data/images/engine/icons/supertux-256x256.png
- and this one is nice:
http://sarrel.deviantart.com/art/Supertux-Dock-Icon-176711771
:PPP

**Comment by brmbrmcar** [comment]
The one in the repository is better.

**Comment by brmbrmcar** [comment]
How was every part of the original made? Get back to the graphics of Tux, scale it back and stick it on the background.

**Comment by Karkus476** [comment]
@devee Your three-year-old son was correct

**Comment by sydneyjd** [comment]
Yes he was.. ;(

**Comment by brmbrmcar** [comment]
I think that the one in the repository should be used.

**Comment by sydneyjd** [comment]
Here is an updated version... Opinions? Im no great artist to say the least... 
![6](https://cloud.githubusercontent.com/assets/8949851/11021660/9955212a-8617-11e5-84dc-8290747dd76e.png)

**Comment by brmbrmcar** [comment]
Pretty good.

**Comment by Karkus476** [comment]
@sydneyjd It's still not right. Someone probably needs to redo this.

**Comment by sydneyjd** [comment]
I agree, and i feel im not the one to do this.

**Comment by brmbrmcar** [comment]
Keep the repo one.
Do a vote.

**Comment by sydneyjd** [comment]
Ok, for now we will keep our current logo. 
Reason one is that the "new" logo doesn't match our game style.
Reason two is that i would prefer that the icon designer would come to us directly with it, not making us go find the icon than seek the author so we can get a propper licence. Its a PITB.
Also, i will just close this issue unless someone decides else or makes a decent looking one that fits our style.

**Comment by Karkus476** [comment]
@sydneyjd True, but we can't expect this to be resolved unless a request is placed somewhere for a new one to be created

**Comment by sydneyjd** [comment]
True...

**Comment by Karkus476** [comment]
I don't know how to go about requesting graphics, though

- Karkus

**Comment by sydneyjd** [comment]
Just ask on the forum if someone would be willing to make a new icon.

-Sydney

**Comment by agertudici** [comment]
Hey so I logged into my old devart account and someone had messaged me about this! That's exciting. I added a note to the description to the effect of "you can use it however you like." If you've any further questions feel free to contact me here or again on my deviantart page (I check on it once a month or so for nostalgia's sake).

**Comment by Karkus476** [comment]
@agertudici Thanks! Personally, though, I don't think it's the right style. Too cartoon-y.
