### ISSUE TITLE
Icecrusher hitting owl carrying mriceblock freezes and crashes the game

### ISSUE THREAD

**Issue by CeIestiaI** [SuperTux/supertux#2187]
SuperTux version 0.6.3

Expected behavior:| Icecrusher should kill `owl` and mriceblock should be let go and move around instead of freezing the game and crashing.

Actual behavior:| As soon as icecrusher touches `owl`, the game freezes and crashes.

Steps to reproduce actual behavior:|
Put an owl and set the carry to `mriceblock`, then place an icecrusher, test the level, go into ghost mode, trigger the icecrusher to hit the owl, and the game will freeze and crash. (basically what is in the video below)

Additional debugging information:|

https://user-images.githubusercontent.com/83178674/160298214-ede50acd-609e-4775-9e72-343f6b22eb41.mp4

I don't know if this is considered a duplicate of another issue that was very similar, that issue included tux hitting the owl, not an icecrusher. Let me know if this is a duplicate.

**Comment by Frostwithasideofsalt** [comment]
i'm very interested in how you find stuff like this lol

**Comment by CeIestiaI** [comment]
i do testing lol

**Comment by mrkubax10** [comment]
Seems that it is fixed on latest master

https://user-images.githubusercontent.com/63350514/160623184-abb7c032-bc55-4b9b-a6c6-03a375133ad3.mp4
