### ISSUE TITLE
Weekly/Fortnightly Releases

### ISSUE THREAD

**Issue by Karkus476** [SuperTux/supertux#219]
Each Week/Fortnight, the game could be built for each platform and put on the downloads repo

**Comment by brmbrmcar** [comment]
Awesome!

**Comment by maxteufel** [comment]
Windows/OS X builds could be a bit hard (unless it's possible to build ST using MinGW); additionally we'd need a CI server (Jenkins/nightly builds would be a bit too much for my 1G VPS) - find a sponsor or someone from the team paying for a server is probably the only solution right now.

**Comment by Karkus476** [comment]
@maxteufel I intentionally did not say nightly. It's too much fuss. MinGW works doesn't it?

**Comment by brmbrmcar** [comment]
Minutely releases!

**Comment by Karkus476** [comment]
Fortnightly is not too often to be done manually

**Comment by Karkus476** [comment]
@brmbrmcar exactly :D

**Comment by maxteufel** [comment]
Well, nightly, fortnightly, weekly doesn't make much difference. If you have resources to automatically provide weekly builds, nightly should work too. But if someone wants to provide builds, why not? I guess I could also upload weekly manual builds for Arch Linux (but only x86_64).

**Comment by Karkus476** [comment]
Thinking of the resources we have, we should be able to do OSX and Debian. Windose however...

**Comment by brmbrmcar** [comment]
Linux only!

**Comment by tobbi** [comment]
Does anyone know suitable sponsors that would be willing to pay for things like that?

**Comment by brmbrmcar** [comment]
Where will they be put?

**Comment by sydneyjd** [comment]
I have a server i could do this on, i just don't have a clue on how to build the builds. :)

**Comment by Karkus476** [comment]
I think we should call them 'snapshots'

**Comment by Karkus476** [comment]
In a GitHub repo, I hope

- Karkus 
You can't unsubscribe from this.
