### ISSUE TITLE
Carryable objects and doors

### ISSUE THREAD

**Issue by Rusty-Box** [SuperTux/supertux#2191]
At the moment, when going through a door while carrying an object ,like lantern, trampolines etc. Tux will come out the other side with empty hand and the object slowly floating towards him and back into his hand. This looks very odd looking and very tedious at long distances.

Carryable objects should immediately teleport alongside Tux and remain in his hand when using doors.

**Comment by Semphriss** [comment]
This will be difficult to work if doors move Tux across sectors, as it imply moving an object from a sector to another and I'm not sure to what extent the game supports that. An easier fix would be to forbid carrying objects through doors entirely for consistency, and make Tux drop any carried object when teleporting.

**Comment by Rusty-Box** [comment]
Doesn't Tux himself count as somekind of object?

**Comment by Semphriss** [comment]
Tux is indeed an object, but he isn't "transported" across sectors; there is always a Tux that is created whenever a sector is, and the only information carried over is the command to make Tux spawn at a certain location. Carried objects can't really use the same mechanic.

**Comment by CeIestiaI** [comment]
an animation where if tux goes through a door that if he is carrying an object or enemy that he opens the door he went through and picks it up then closes the door? just an idea
