### ISSUE TITLE
Climbing does not work on levels created with the level editor.

### ISSUE THREAD

**Issue by chomwitt** [SuperTux/supertux#2193]
**SuperTux version:**  Latest development version
**System information:**
Distro: Devuan GNU/Linux 5 (daedalus/ceres)
Kernel: 5.16.0-6-amd64

##### Expected behavior
In level editor if i put rope tiles and  climb tiles on top i'd expect when testing the level to be able to grap and climb. (in 0.6.3 ι could grap but not climb unless i kept jumping).  
##### Actual behavior
I cant grab the rope and if i do i cant climb.

##### Steps to reproduce actual behavior
In level editor create the tile layout displayed in the link:
https://pixelfed.eu/i/web/post/420906796997243475

**Comment by Rusty-Box** [comment]
The same happens with script triggers. In general a lot of these types of areal objects become randomly broken! Sometimes they work sometimes they don't. Sometimes they work once but then never again in the same play session.

I can't confirm it but part of me suspects the multiplayer commits to have broken something.
