### ISSUE TITLE
Plants and totems do not behave properly when placed on rocks that are atop of trampolines

### ISSUE THREAD

**Issue by CeIestiaI** [SuperTux/supertux#2194]
SuperTux version:| 0.6.3

Expected behavior:| Totems and plants should be able to walk on rocks like other enemies can.

Actual behavior:| The plant in the video below appears to clip into the rocks after the falling rocks and comes back out, and it seems to be in its moving animation/position even though it itself isn't moving. The totem touches the rock(s) and doesn't move around; instead it acts glitchy by repeating its left and right walking animations constantly / consistently.

Steps to reproduce actual behavior:|
Video below

Additional debugging information:|

https://user-images.githubusercontent.com/83178674/164649289-54f11452-b9b8-4497-b9ab-a24e6ae18023.mp4

**Comment by AidenIsik** [comment]
They also appear to behave like this even without the trampolines.

I’m looking into this bug now.

**Comment by AidenIsik** [comment]
It’s a problem with the might_fall function. Smartball does this too, and commenting out that function call fixes it, but also causes them to fall (obviously). It seems to not recognise rocks as solid.

**Comment by AidenIsik** [comment]
Fixed. Making a PR..
