### ISSUE TITLE
Allow changing the current renderer from "Options"

### ISSUE THREAD

**Issue by Vankata453** [SuperTux/supertux#2199]
Having an option to change the renderer between "OpenGL" and "SDL" from the "Options" menu in-game would definitely be way simpler for a wide range of users. Display issues and in-game slowdowns can easily be fixed by anybody, if the issue relies on the current renderer.

If it's not possible to change the renderer while the game is running, an idea is to have a dialog, which appears after changing the option, saying that the game needs to be restarted for the changes to take effect.

Of course, the startup option to change the renderer (``--renderer``) should always be available, in case the renderer couldn't be changed from the graphical interface.

**Comment by mrkubax10** [comment]
Technically it should be possible without restarting game because Pingus has such option and it works like that.

**Comment by Vankata453** [comment]
That is good news. Another reason why having such option would be useful. :)
