### ISSUE TITLE
SuperTux nightly error

### ISSUE THREAD

**Issue by Explosion-Scratch** [SuperTux/supertux#2204]
On the [download page for SuperTux nightly](https://download.supertux.org/) I am getting this error:
```
Fatal error: Uncaught PDOException: could not find driver in /usr/web/supertux.org/view.php:18 Stack trace: #0 /usr/web/supertux.org/view.php(18): PDO->__construct('mysql:host=127....', 'root', '', Array) #1 {main} thrown in /usr/web/supertux.org/view.php on line 18
```

**Comment by Semphriss** [comment]
The repository for the add-ons website is here: https://github.com/SuperTux/addons-website

Please transfer the issue to that repository.

**Comment by Semphriss** [comment]
Nevermind that last comment - I mixed up the add-ons and the nightlies websites, which are separate, and for which the latter does not seem to have the source code available.

**Comment by Explosion-Scratch** [comment]
Wait, I didn't know about the addons website, not to get off topic but could you send a link to that?

**Comment by Vankata453** [comment]
https://github.com/SuperTux/addons-website

Not sure if it's functional though.

**Comment by Explosion-Scratch** [comment]
> https://github.com/SuperTux/addons-website
> 
> Not sure if it's functional though.

Yeah, I meant the _website_ not the GH repo

**Comment by Semphriss** [comment]
I don't believe it is available to the public, unfortunately. The [forums](https://forum.freegamedev.net/viewforum.php?f=66) are currently used to share add-ons.

**Comment by Vankata453** [comment]
> > https://github.com/SuperTux/addons-website
> > 
> > Not sure if it's functional though.
> 
> Yeah, I meant the _website_ not the GH repo

Oh, I haven't understood you correctly. I don't think it exists as a website currently. Addons are being downloaded from https://github.com/SuperTux/addons currently. This website, as far as I know, has been an attempt to simplify maintaining those addons.

**Comment by tobbi** [comment]
Nightly website is available again.

**Comment by Explosion-Scratch** [comment]
Thanks!
