### ISSUE TITLE
Tux wont move on  a path in a worldmap created with the editor in a windows version.

### ISSUE THREAD

**Issue by chomwitt** [SuperTux/supertux#2209]
**SuperTux version:** 0.6.3
**System information:** Windows 10

##### Expected behavior
In worldmap editor in testing a worldmap i want Tux to be able to move on a path that i have laid out .

##### Actual behavior
Tux cant move with keys or gamepad.
(in 0.6.3 in a linux box i  can move the tux but only with a gamepad).

##### Steps to reproduce actual behavior
Create a worldmap like the one in the image below and try to move tux.
![image](https://user-images.githubusercontent.com/1383580/168443604-019150bd-bb9f-4ba6-9d51-77700101ebc1.png)

**Comment by Vankata453** [comment]
Is the path put on a tilemap with a "z-pos" of 0?

**Comment by Semphriss** [comment]
Have you checked if the tilemap is marked as solid?

**Comment by Semphriss** [comment]
> Is the path put on a tilemap with a "z-pos" of 0?

As far as I'm aware, the z-pos has no impact on how the game handles interactions with the object; it's a visual-only feature.

**Comment by Vankata453** [comment]
> > Is the path put on a tilemap with a "z-pos" of 0?
> 
> As far as I'm aware, the z-pos has no impact on how the game handles interactions with the object; it's a visual-only feature.

Oh, alright. 👍

**Comment by chomwitt** [comment]
'Solid' option proposed from @Semphriss  worked.

I set the 'path' tilemap with Z-pos = 1 as it was adviced to me in a [reply](https://forum.freegamedev.net/viewtopic.php?f=67&t=18638&sid=420f93efdda18be5cd64445e10275261) in the  freegamedev forum.

**Comment by Semphriss** [comment]
Good! Closing this then.
