### ISSUE TITLE
Can not compiled actual supertux

### ISSUE THREAD

**Issue by spider2016** [SuperTux/supertux#221]
You can see begin of issue here:
https://github.com/SuperTux/supertux/issues/200
What i do wrong?
I tried with submodel, so i use clone without recursive and i can use git submodel update --init --recursive, but after complilled i can see error :-(
./supertux2: error while loading shared libraries: libtinygettext.so: cannot open shared object file: No such file or directory

**Comment by brmbrmcar** [comment]
Does anyone know where libtinygettext.so is actually meant to be kept?

**Comment by maxteufel** [comment]
You need to have all required libraries somewhere in your dynamic linker's path. If it already is, then try to run `ldconfig(8)`

**Comment by Karkus476** [comment]
@maxteufel You've closed this. Are you sure this fixed his problem?

**Comment by brmbrmcar** [comment]
I have no idea. Re-open.

**Comment by spider2016** [comment]
Karkus476  have you this problem too? ldconfig don't help me.
so, submodule for maxteufel :
 git submodule update --init --recursive ./
Submodule 'external/squirrel' (https://github.com/SuperTux/squirrel.git) registered for path 'external/squirrel'
Submodule 'external/tinygettext' (https://github.com/SuperTux/tinygettext.git) registered for path 'external/tinygettext'
Cloning into 'external/squirrel'...
remote: Counting objects: 83, done.
remote: Total 83 (delta 0), reused 0 (delta 0), pack-reused 83
Unpacking objects: 100% (83/83), done.
Checking connectivity... done.
Submodule path 'external/squirrel': checked out 'c05cd012c0999b48798974667cedb41e99e18ccf'
Cloning into 'external/tinygettext'...
remote: Counting objects: 1506, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 1506 (delta 0), reused 0 (delta 0), pack-reused 1502
Receiving objects: 100% (1506/1506), 323.39 KiB | 575.00 KiB/s, done.
Resolving deltas: 100% (986/986), done.
Checking connectivity... done.
Submodule path 'external/tinygettext': checked out '8163668511c6a0481e540cbc80eee0605fc8985b'

**Comment by Karkus476** [comment]
@spider2016 Are you on Linux?

**Comment by maxteufel** [comment]
> @maxteufel You've closed this. Are you sure this fixed his problem?

I've closed this. This issue tracker is definitively not for general Linux/UNIX support.

As of the current commit in the master branch, I can not reproduce this. The libraries are getting installed to the path where they are supposed to be (and the version they are supposed to be). If an individual system configuration introduces a *bug*, we can't really fix this because `ld(1)` is doing what it's supposed to be doing.

**Comment by brmbrmcar** [comment]
Fedora.

**Comment by Karkus476** [comment]
@brmbrmcar Have you had this issue?

**Comment by maxteufel** [comment]
To actually clarify what `ld(1)` does:

* the `supertux2` binary says 'look for `libtinygettext.so`'
* `ld(1)` looks in its configuration files and environment variables for possible locations for `libtinygettext.so`
* `ld(1)` looks in all those directories and takes the first that contains `libtinygettext.so` (the order is specified in the configuration)

If `ld(1)` can't find `libtinygettext.so`, the above will happen. If it finds another version the binary is not linked to and that version is incompatible with the actual version being linked to, `supertux2` can't start as well.

**Comment by brmbrmcar** [comment]
@Karkus476 No. I was telling you his OS.

**Comment by spider2016** [comment]
My OS is Russian Fedora 22
I tried to include a local library and supertux WORKED .So library from https://github.com/tinygettext/tinygettext is not WORKED. This is my main problem, I used bad library!!!
so for worked supertux your need:
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/chaos/T58/lib/ where /home/chaos/T58/ is a local directory, where you installed your supertux.

**Comment by maxteufel** [comment]
That is expected as well, because we're using <https://github.com/SuperTux/tinygettext>.

**Comment by brmbrmcar** [comment]
He used that this time.

**Comment by spider2016** [comment]
So, I don't know:
ls -lh /usr/local/lib/libtinygettext.so /home/chaos/T58/lib/libtinygettext.so 
-rwxr-xr-x 1 chaos chaos 161K ноя  9 08:52 /home/chaos/T58/lib/libtinygettext.so
-rwxr-xr-x 1 root  root  157K окт 21 09:07 /usr/local/lib/libtinygettext.so

different size!
But i repeat again, in May, i have not problem with compiled and running supertux.

**Comment by maxteufel** [comment]
> different size!

Yeah, because they're different versions.

> But i repeat again, in May, i have not problem with compiled and running supertux.

There were some changes in the build infrastructure since May. You can't expect any software to keep the same build infrastructure and not breaking anything (especially in snapshots/betas like 0.3.z).

**Comment by spider2016** [comment]
maxteufel, 0.3.z cool  version. This version differ than 0.3.5a
May be you will be interesting a lot of warnings:
tinygettext: levels/incubator/ru.po:21: warning: unknown Plural-Forms given: 
tinygettext: levels/bonus3/ru.po:21: warning: unknown Plural-Forms given: 
tinygettext: levels/bonus2/ru.po:22: warning: unknown Plural-Forms given: 
tinygettext: levels/bonus1/ru.po:21: warning: unknown Plural-Forms given:

**Comment by tobbi** [comment]
These tinygettext warnings should be removed so they don't spam to the log output.

**Comment by Karkus476** [comment]
This _needs_ it's own issue

- Karkus
