### ISSUE TITLE
Worldmap: Adding level dots misconfigures the level's file path

### ISSUE THREAD

**Issue by Semphriss** [SuperTux/supertux#2213]
**SuperTux version:** Latest @ master

##### Expected behavior

When adding a level dot in a worldmap, and selecting the level file for that level dot, the game should automatically fill in the correct path.

##### Actual behavior

When adding a level dot in a worldmap, and selecting the level file for that level dot, the game duplicates the path folder. For example, for a level located in `/levels/myworldmap/level1.stl`, the game will put `/levels/myworldmap//levels/myworldmap/level1.stl`.

##### Steps to reproduce actual behavior

1. Create a new world.
2. Create a level in that world.
3. Create a worldmap for that world.
4. Edit the worldmap and add a level dot.
5. Edit that level dot, and set its "Level" property to the level created at step 2.
6. Position Tux over the level dot, or add a path on a solid tilemap between Tux and the dot.
7. Any of the following:
  - Test the worldmap
  - Save the worldmap, quit, and re-=open the worldmap from the "Contrib levels" menu.
8. Navigate to the level, and attempt to play it. The game will kick you out to the last screen, complaining that it can't find the level.

**Comment by Semphriss** [comment]
After investigating, I noticed that this isn't a problem at saving time; it saves the full path of the level. It's when loading the level that the game seems to expect a relative path starting from the worldmap directory and automatically prepends its paths to the level path.

I believe saving the levels' full path is the new feature that breaks the lot, and currently all level paths in worldmaps are stored relatively. Fixing this will take a bit of time.

**Comment by mrkubax10** [comment]
It may be little offtopic for this issue but in my opinion level paths should be always relative to worldmap folder and in result making it impossible for worldmaps to have levels outside of it's folder otherwise it will quickly become messy.
