### ISSUE TITLE
Local 2+ Player Multiplayer

### ISSUE THREAD

**Issue by Karkus476** [SuperTux/supertux#224]
A few steps to this:
- [ ] Format
  -  Split Screen
  -  [One Screen](https://youtu.be/pipMu0HXiU0?t=50s)
- [ ] Second player (with sprites)
  - Penny?
- [ ] New control configs for new player
- [ ] Play campaign?

**Comment by brmbrmcar** [comment]
Nice.

**Comment by Karkus476** [comment]
Here is an (outdated) diff which may serve as inspiration. https://github.com/SuperTux/supertux/commit/764b8411d0d67d2877761a119a399fe5b647937c

**Comment by brmbrmcar** [comment]
Multiplayer should be just Tux and Penny for now.

**Comment by tobbi** [comment]
We need proper sprite assets first...On the other hand: The story features Penny being abducted by Nolok. So she probably can't be played...

**Comment by Karkus476** [comment]
I am working to update this so the diff does work, after which we can have polls etc. regarding this. After M2 is the ideal time to implement it too, I would love to be able to play with others.

**Comment by Karkus476** [comment]
Is it agreed that this should be one screen (rather than split-screen)? That's what I'd prefer.

**Comment by brmbrmcar** [comment]
Nolok can just be like a "boss". Don't keep the same story.

**Comment by Karkus476** [comment]
No. I want to be able to play through the story too, with 2 players.

- Karkus

**Comment by brmbrmcar** [comment]
But that would have to wait, because there is no other player in the storyline. And also, what about once Penny is freed?

**Comment by tobbi** [comment]
So far we've been avoiding that ;)

**Comment by Karkus476** [comment]
It's not that complex, we just need a new character.

**Comment by brmbrmcar** [comment]
But to the story line? There was this one character that could jump high, who was that?

**Comment by Karkus476** [comment]
They are just another hero, who wants to help Tux

**Comment by brmbrmcar** [comment]
Fluffy. http://supertux.lethargik.org/wiki/Fluffy

**Comment by Karkus476** [comment]
I don't think the characters should be different at all.

**Comment by brmbrmcar** [comment]
What do you mean?

**Comment by Karkus476** [comment]
Fluffy would have different abilities to Tux, which is unfair, and wouldn't work

**Comment by brmbrmcar** [comment]
It is like that in virtually every multiplayer game. You just have to modify the levels to make it fair.

**Comment by Karkus476** [comment]
Nah, I say we keep them the same, otherwise the slower would be left behind.

**Comment by brmbrmcar** [comment]
You see how difficult this is?

**Comment by Karkus476** [comment]
Only because there is a disagreement. This is why I opened this issue, so we could make some decisions now rather than later

**Comment by brmbrmcar** [comment]
Yes, but the point is it is impossible to meet all this criteria.

**Comment by Karkus476** [comment]
Great idea, let's give up before we've even begun?

**Comment by brmbrmcar** [comment]
No.  Just something has to be sacrificed.

**Comment by Karkus476** [comment]
You?

**Comment by brmbrmcar** [comment]
No, part of the criteria.

**Comment by brmbrmcar** [comment]
A new character is the best bet, but I am a bit unsure.

**Comment by Karkus476** [comment]
[Notable page](http://supertux.lethargik.org/wiki/User_ideas/Multiplayer) on the old wiki.

**Comment by maxteufel** [comment]
I'd agree with @Karkus476 that this should be one screen (the camera can just zoom out so both players are always visible). The other ideas are not important for now, fixing the two-player-objects patch is more important.

**Comment by CadenMitchell** [comment]
What if we there is just another open-source character used? Like Tux is linux, what about Suzanne for Blender, or something like that? Kind of like Super Tux Kart used multiple open-source characters.

**Comment by christ2go** [comment]
There are some design decisions to be made.

- [ ]  What happens, when one player dies? (Does it matter if it is the secondary player?)
- [ ]  Should the camera have a maximum zoom, at which point a marker (similiar to when Tux is above the screen) would be displayed.

**Comment by ildar** [comment]
I've seen Nintendo Mario two player game on YouTube. I don't remember about
deaths but zoom was dynamic.

**Comment by weluvgoatz** [comment]
My ideas and thoughts: 

Adding/Removing second player: Should be a menu from within the game level that says: Add second player. Adding will spawn Player 2 wherever Player 1 is.  Then, from the menu, the second player can be removed from the same menu where they were inserted.  If the player exits to the menu or to the worldmap, Player 2 will disappear.

Controls: Most likely WASD for arrow keys, maybe something like J for jump and S for action?  Pressing the pause button will still pause the game and both players can use the same menu.

Format: For simplicity, should follow Player 1 and if Player 2 goes outside the camera zone you can't see them until Play 1 catches up with them.

Second Player: Should be Penny, but also multiple other characters. They all have the same power as Tux.  Needs a menu for 2nd Player player sprite selection, but Player 1 will always be Tux. 

If one player dies: Respawns wherever the other player is.  It would add an advantage to having two players ;)

Powerups and Coins: Coins will be for both players collectively. Each player will have separate powerups though.

Collectibles and Enemies: Coins can only be picked up once, enemies can only be killed once, etc.

I hope you guys enjoy my ideas! :)

**Comment by brmbrmcar** [comment]
Surely controls would be defined by the players?

**Comment by weluvgoatz** [comment]
Yes, hopefully... I'm just suggesting default controls.
