### ISSUE TITLE
Pressing Left, Rshift and Click disables grid snapping in editor

### ISSUE THREAD

**Issue by Alasdairbugs** [SuperTux/supertux#2242]
v0.6.3-548-g81809dd5e
win10

press left, Rshift and click, it should disable grid snapping. might work with other directions. this shouldn't be a thing. Rshift is useful for navigating a level in the editor quickly, as it is also close to the arrow keys, so you can use one hand for movement and the other for the mouse.

**Comment by mrkubax10** [comment]
Apparently this is intended key shortcut. Hold one of shift keys (left or right) then move object with mouse. I propose this change: right shift should be used to move quicker with arrows and left shift to disable grid snapping.
