### ISSUE TITLE
All my wanted Console commands

### ISSUE THREAD

**Issue by brmbrmcar** [SuperTux/supertux#225]
I will try and implement the following:
- [x] Level restart.
- [x] X, Y level spawning.
- [ ] Profile switch.
- [ ] Fix of showing all the commands.

**Comment by Hume2** [comment]
Level restart and XY level spawning could be useful and I don't see any problem with that.
Profile switch when playing a level is problematic and I don't know any good usage in levels. Could you think any?
Fix of showing all the commands. If you want to fix a bug, then report it and don't suggest to fix it.

**Comment by brmbrmcar** [comment]
The profile one is a good test of whether or not your worldmap works perfectly.

**Comment by brmbrmcar** [comment]
X,Y level spawn required other stuff,  I did not implement it.

**Comment by tobbi** [comment]
I'd rather not give scripts the ability to modify which profile is being used. Otherwise, we'll have people complain about "data loss" (when they see levels not being solved that should be solved).

**Comment by Karkus476** [comment]
@brmbrmcar After https://github.com/SuperTux/supertux/commit/0ea80d4ebf3f908d52ec5b099681add7b1abea83 , if you're running a level file directly, --spawn-pos 4,5 will spawn tux at X:4 Y:5.

**Comment by maxteufel** [comment]
> - [ ] Level restart.

Why would you want to script that?

**Comment by Grumbel** [comment]
It might be possible to export certain functions only to the console, but not to the level scripting, but that's probably not worth the effort as we already have a cheat menu for the worldmap (Ctrl-F2 to activate developer mode, F1 to show cheat menu). If more debug functionality is needed, it should go in there. not the console.

**Comment by tobbi** [comment]
Closing as per https://github.com/SuperTux/supertux/issues/225#issuecomment-167328159
