### ISSUE TITLE
add lua scripting and better script editor

### ISSUE THREAD

**Issue by IniKiwi** [SuperTux/supertux#2252]
the actually script language is bad, lua is modern and popular
example:
```lua
local badguys = {}
table.insert(badguys, BadGuy:New("SnowBall","snowball1", 20, 30))
local tileset1 = Sectors:Get("platform1")
tileset:SetTile(1,1,70)
local pos = Objects:Get("snowball1"):GetPos()
Log(pos)
```

(sorry for my english, I am french)

**Comment by mrkubax10** [comment]
I'm aware that Squirrel is not very popular and has werid syntax sometimes but I think that there are no plans for changing scripting language.

**Comment by mrkubax10** [comment]
Closing because this is very unlikely to happen

**Comment by Kolbxyz** [comment]
Yeah, lua would probably be be better for a game like that and it is very easy & modern as @IniKiwi said.
