### ISSUE TITLE
Run Console Commands From Another Process

### ISSUE THREAD

**Issue by Karkus476** [SuperTux/supertux#226]
Put simply, I want Flexlay to be able to call console commands for its SuperTux subprocess. This may already be possible.

**Comment by brmbrmcar** [comment]
OK, it will have to change both Flexlay and Supertux, but it should be quite simple. What commads are you thinking of running?

**Comment by Karkus476** [comment]
Flexlay is not a part of this issue. Any and all of them.

**Comment by brmbrmcar** [comment]
So Flexlay supports it, but Supertux doesn't?

**Comment by Karkus476** [comment]
This could be useful for a number of reasons, but would have to be security concious. No, Flexlay doesn't support this, but the issue is concerning SuperTux. If the changes are made to SuperTux, I would close this

**Comment by brmbrmcar** [comment]
Maybe we could develop a mode for this to be enabled.

**Comment by Karkus476** [comment]
@brmbrmcar Yes, that would probably be needed

**Comment by brmbrmcar** [comment]
Where do we start?

**Comment by Karkus476** [comment]
We need to decide how the processes will communicate

**Comment by brmbrmcar** [comment]
That's where I know absolutely nothing.

**Comment by Karkus476** [comment]
Here's where we need to start I guess <https://en.wikipedia.org/wiki/Inter-process_communication>

**Comment by brmbrmcar** [comment]
Do you know how to do it?

**Comment by maxteufel** [comment]
On UNIX mostly files/FIFO, [D-Bus](https://en.wikipedia.org/wiki/D-Bus) or some other socket-based communication (TCP socket, file socket).

**Comment by Karkus476** [comment]
@brmbrmcar I do not :D

**Comment by brmbrmcar** [comment]
Who does?

**Comment by Karkus476** [comment]
@maxteufel I am thinking sockets

**Comment by maxteufel** [comment]
I'd prefer FIFO, because it's not that bloated.

**Comment by Karkus476** [comment]
@maxteufel I do not know anything about this. First in first out... of what?

**Comment by maxteufel** [comment]
https://en.wikipedia.org/wiki/Named_pipe

**Comment by Karkus476** [comment]
@maxteufel This is a two-way thing, right?

**Comment by Karkus476** [comment]
I worry this may harm portability...

**Comment by Karkus476** [comment]
I'm closing this because I do not think it is necessary. A possibility to be considered in the future, though

**Comment by brmbrmcar** [comment]
You marked it as post 0.4.0, why close?

**Comment by maxteufel** [comment]
Reopening for further discussion after the 0.4.0 release.

**Comment by Karkus476** [comment]
An agreement was reached: there is too little value to adding this feature.
```
<Karkus> Also, I closed this https://github.com/SuperTux/supertux/issues/226 because I thought the security implications were too great considering the little value that could be taken from adding the feature
<mt> Oh you can close it again, then
<Karkus> Unless you can see some value in it?
<mt> nope, not enough value
<mt> considering the work and the security part
<Karkus> Agreed
```
