### ISSUE TITLE
Rock tux's idle position + crouch position appear when trying to stand up under stationary object

### ISSUE THREAD

**Issue by CeIestiaI** [SuperTux/supertux#2260]
SuperTux version:| 0.6.3

Expected behavior:| Earth tux shouldn't be able to solidify under a stationary object that is 1 position above a tile. Instead, tux should only be able to crouch and move around while under a stationary object that is 1 position above a tile.

Actual behavior:| Earth tux can solidify under a stationary object and show 2 different positions with both being inside of each other, one being crouching with the earth hat and the other position being idle standing without the earth hat, which looks strange. 

Steps to reproduce actual behavior:| Place any stationary object 1 position above any tile and test the level using earth tux, then crouch under the stationary object as earth tux and solidify.

Additional debugging information:| video

https://user-images.githubusercontent.com/83178674/180323729-fa441d85-dfd5-4869-adf6-c0ef541bd389.mp4

**Comment by ixPost** [comment]
How do you solidify anyway?
