### ISSUE TITLE
[Tileset PR] New snow slope tiles might still have unintended attributes assigned

### ISSUE THREAD

**Issue by Alasdairbugs** [SuperTux/supertux#2261]
0.6.3-574-g11899ba2d
win10

![image](https://user-images.githubusercontent.com/41154567/180609917-c9f81b46-254b-414d-a1f3-cd2d74eb0d73.png)

Here, this tile, upon electrocution when submerged in solid water from lightning, turns into part of a rain cloud:

![image](https://user-images.githubusercontent.com/41154567/180609961-98206f54-d2b9-4229-9005-1802b03f3222.png)

This is for Rusty's PR, #2136. might have some unintended attribute assigned? thought im not sure what tile changes (other than water) to a different tile upon being shocked.

**Comment by Alasdairbugs** [comment]
This also occurs with other snow slope tiles that meet a wall:

![image](https://user-images.githubusercontent.com/41154567/180610177-a2189195-5466-4962-8e75-3e3636fad120.png)

**Comment by Rusty-Box** [comment]
From my understanding this is a hardcoded behavior since I have no special attribute signed to these tiles.
@Semphriss, @Zwatotem or @weluvgoatz, could one of you look into this please?

These are the tile-ids in question are: 3427 - 3434

**Comment by NickerAbanTRY23F** [comment]
that also happened the same as me, but now not anymore

**Comment by NickerAbanTRY23F** [comment]
> From my understanding this is a hardcoded behavior since I have no special attribute signed to these tiles. @Semphriss, @Zwatotem or @weluvgoatz, could one of you look into this please?
> 
> These are the tile-ids in question are: 3427 - 3434

here is not the same discord put @

**Comment by NickerAbanTRY23F** [comment]
> > From my understanding this is a hardcoded behavior since I have no special attribute signed to these tiles. @Semphriss, @Zwatotem or @weluvgoatz, could one of you look into this please?
> > These are the tile-ids in question are: 3427 - 3434
> 
> here is not the same discord put @

idk

**Comment by mrkubax10** [comment]
@NickerAbanTRY23F what are you doing?

**Comment by NickerAbanTRY23F** [comment]
> @NickerAbanTRY23F what are you doing?

me? nothing..
i was just looking at comments
