### ISSUE TITLE
Windows flowerhat stops working

### ISSUE THREAD

**Issue by Hazel99x** [SuperTux/supertux#2266]
**SuperTux version:**
**System information:** *(details about your kernel, operating system, or distribution)*

##### Additional debugging information

*If available, please attach a backtrace of a crash (you can get one using GDB or another debugger), or a core dump. If you're on GNU/Linux and your distro is using systemd, it's highly likely that a core dump is available using `coredumpctl(1)`.
If the issue only occurs in a custom level, please attach that too.*

##### Guidelines for reporting issues

- [ ] I have read <https://github.com/SuperTux/supertux/blob/master/CONTRIBUTING.md#bug-reports>.
- [ ] I verified this isn't an issue that's already been reported.
- [ ] This report only includes details about **one** (1) issue, feature request or topic.
- [ ] If I make a mistake while submitting this report I will use the edit feature instead of closing this issue and opening a new one.
- [ ] This issue is **not** about wrong translations (use Transifex for those), or anything unsupported (e.g. third-party add-ons).
- [ ] Once you're done, please remove the section 'Guidelines for reporting issues', the 'Additional debugging information' if it is empty, and any text in *italic font*.

Version 0.6.3 Win64
Windows 10, Core i5 8gb ram
After leaving world and then returning to game later, flowerhat no long fires fireballs.  Gaining a new flower hat in addition makes no difference.  Basically fireballs only work if you don't close the game ever!

**Comment by Hazel99x** [comment]
First post on here - sorry if I've submitted anything incorrectly.  Basically issue is 

Version 0.6.3 Win64
Windows 10, Core i5 8gb ram
After leaving world and then returning to game later, flowerhat no long fires fireballs. Gaining a new flower hat in addition makes no difference. Basically fireballs only work if you don't close the game ever!  Really frustrating.

**Comment by Semphriss** [comment]
@Hazel99x Have you checked your key bindings?

Go in Options -> Keyboard, and try setting "Action" to a different key.

**Comment by Hazel99x** [comment]
Thank you.  Couldn’t work out how to do that but I did find the fireballs had moved to the alt key - so I have them back but strangely it switched from control key to alt key after closing the game the first time.

Sent from my iPhone

On 4 Aug 2022, at 15:12, Semphriss ***@***.***> wrote:

﻿

@Hazel99x<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FHazel99x&data=05%7C01%7C%7Ce679f87c559a48f5cfe408da76236d4c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637952191777758607%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=JI%2BI885HPwOht2i%2BDCDAm2Zw8K92%2FI2SDuTdVKyeozA%3D&reserved=0> Have you checked your key bindings?

Go in Options -> Keyboard, and try setting "Action" to a different key.
