### ISSUE TITLE
Extremely loud sound(s) when standing atop of bonusblock

### ISSUE THREAD

**Issue by CeIestiaI** [SuperTux/supertux#2269]
SuperTux version:| 0.6.3

Expected behavior:| The sound shouldn't be loud / distorted.

Actual behavior:| The sound is loud / distorted.

Steps to reproduce actual behavior:| Place a bonus block with bricks above it on the left and right sides, then set the item to fireflower and the count to 2147483647. Then, underneath the bonus block, place a brick with a trampoline and a rock above it. Place a solid square snow tile before you place the bonus block. Wait until the FPS drops a bit like in the video. If this is unclear, you can take a look at the video.
Note: this is similar to #2253, but it isn't the exact same setup.

https://user-images.githubusercontent.com/83178674/181135514-c8fc2042-b539-4cdc-b524-d4fe6aa764c4.mp4

**Comment by Laksh61isback** [comment]
Its so loud it bursts my ears

**Comment by mrkubax10** [comment]
I consider this as valid behaviour, rock is bouncing of trampoline then hitting bonus block and then this repeats
