### ISSUE TITLE
Supertux is Bugggy in old computers

### ISSUE THREAD

**Issue by Laksh61isback** [SuperTux/supertux#2273]
**SuperTux version:**
**System information:** *(details about your kernel, operating system, or distribution)*

##### Additional debugging information

*If available, please attach a backtrace of a crash (you can get one using GDB or another debugger), or a core dump. If you're on GNU/Linux and your distro is using systemd, it's highly likely that a core dump is available using `coredumpctl(1)`.
If the issue only occurs in a custom level, please attach that too.*

##### Guidelines for reporting issues

- [x] I have read <https://github.com/SuperTux/supertux/blob/master/CONTRIBUTING.md#bug-reports>.
- [ ] I verified this isn't an issue that's already been reported.
- [ ] This report only includes details about **one** (1) issue, feature request or topic.
- [ ] If I make a mistake while submitting this report I will use the edit feature instead of closing this issue and opening a new one.
- [ ] This issue is **not** about wrong translations (use Transifex for those), or anything unsupported (e.g. third-party add-ons).
- [ ] Once you're done, please remove the section 'Guidelines for reporting issues', the 'Additional debugging information' if it is empty, and any text in *italic font*.

**Comment by mrkubax10** [comment]
Some details maybe?

**Comment by Laksh61isback** [comment]
ok here:Make alot of snow and alot of rain and badguys.

**Comment by Laksh61isback** [comment]
it crashes in 2003 old computer

**Comment by mrkubax10** [comment]
> ok here:Make alot of snow and alot of rain and badguys.
That is expectable after adding too many objects that have to be updated every frame.
I don't consider this as an issue
