### ISSUE TITLE
Make language add-ons work without a restart

### ISSUE THREAD

**Issue by tobbi** [SuperTux/supertux#228]
I doubt we'll make this in time for 0.4.0, but it's definitely something to think about.

Unfortunately, all my efforts towards resolving this issue have been fruitless so far. Adding strings to the dictionary might work after screen switch (after it gets a chance to load the strings again), however, removing the language add-on does nothing until probably after restart.

Any idea how to resolve this?

**Comment by Karkus476** [comment]
@tobbi Sehr bunt

**Comment by Karkus476** [comment]
@tobbi Also, what do you need to discuss, and with whom?

**Comment by tobbi** [comment]
I'd like to discuss implementation details with the rest of the team. I don't know how to figure out how to do this on my own. So if anyone wants to take a shot at this, go right ahead.

**Comment by tobbi** [comment]
Basically, tinygettext loads the language files and updates the cache when a new dictionary gets loaded in, however, that doesn't make the UI update. I believe in order to make the UI update, additional steps are needed.

**Comment by tobbi** [comment]
Closing, since language add-ons have been phased out in favour of placing the .po files inline.
