### ISSUE TITLE
Stop doors fom blacking out the screen when they aren't being used

### ISSUE THREAD

**Issue by brmbrmcar** [SuperTux/supertux#229]
It is extremely annoying in some levels where there is a door near a jump, and you cannot see what you are doing, making the jump very difficult.

**Comment by Hume2** [comment]
Agreed.

**Comment by brmbrmcar** [comment]
So remove it?

**Comment by Hume2** [comment]
I'm not so sure.
It happens only when you have jumping with up.
Let's see what the other will say.

**Comment by brmbrmcar** [comment]
Oh yes, I use jump with up (co-ordinating with the space bar is too hard for me).

**Comment by Hume2** [comment]
The jump key has been the up key since 0.1.2. It was changed to spacebar in 0.1.3 and there are separate up and jump actions since 0.3.0. The jump with up it there since 0.3.3.
Just some facts to start with.

**Comment by brmbrmcar** [comment]
I know that much.

**Comment by Karkus476** [comment]
Please could I have a screenshot, I may be a very simple person, but I cannot understand

**Comment by Karkus476** [comment]
@brmbrmcar Please could I have a screenshot, I may be a very simple person, but I cannot understand

**Comment by Karkus476** [comment]
@SuperTux/developers We need a door entering/leaving animation. Anyone willing to create or request one?

**Comment by Karkus476** [comment]
Please could someone confirm that the changes I have made are suitable for inclusion (pull request #426). The play is hidden and unable to move after they open the door. This will look better if new open and close animations with tux involved are created for the door.

**Comment by Karkus476** [comment]
Okay, we need to make the action key configurable (changable), and remove the option to "jump with up"

**Comment by brmbrmcar** [comment]
Jump with Up is a good option.

**Comment by Karkus476** [comment]
@brmbrmcar I don't think one key should perform two possible actions.

**Comment by brmbrmcar** [comment]
I think they should all be possible to do multiple actions, and even have two keys for one action.

**Comment by Karkus476** [comment]
@brmbrmcar I strongly disagree. No wonder there is confusion over this issue, because the game is being told to do two things at once. I consider that a fault of design. It's perfectly simple to change to use a different key, since you use the Up key far less. What's the requirement that the same key is used?

**Comment by brmbrmcar** [comment]
I guess so, but can't we just remove the screen blackout thing?That's all that is necessary.

**Comment by Karkus476** [comment]
I guess.

**Comment by brmbrmcar** [comment]
Any fix?  I'd do it if I knew where this feature comes from...

**Comment by maxteufel** [comment]
This seems to be an edge case, we'll postpone this until someone comes up with a good solution.

**Comment by Rusty-Box** [comment]
A solution could be to have Tux be deactivated so he cannot be moved when opening a door. If one does not want to use a door they simply avoid pressing up when standing right in front of a door.

**Comment by Semphriss** [comment]
I don't know which commit introduced this, but doors don't black the screen out anymore; I'll close this issue now.
