### ISSUE TITLE
Missing available languages in the Steam store page

### ISSUE THREAD

**Issue by galaipa** [SuperTux/supertux#2300]
Recently Steam [added](https://store.steampowered.com/news/group/4145017/view/3325361214990632478) a bunch of new languages to select when indicating which languages do the games support. The updated list of available languages can be found [here](https://partner.steamgames.com/doc/store/localization/languages).

It might sound like a small thing, but this is very important for languages like Basque were only a few games are available. That's why I would like to kindly ask you to update the supported languages list.

Currently Supertux has the following languages listed in the Steam page: English, French, German, Spanish-Spain, Czech, Polish, Protuguese-Brazil, Russian

By checking Supertux's [Transifex](https://explore.transifex.com/arctic-games/supertux/) (I might be looking in the wrong place?) I assume there are a lot that have to be added. I don't know which is the threshold for a translation to be added to the game, so that's why I didn't list which one in particular are missing. But if necessary I can take care of that.

Thank you in advance

**Comment by Semphriss** [comment]
@galaipa Steam requires the threshold to be 100%, unfortunately. I had to discard many languages that were very close to 100%, like Bulgarian, Galician or Portuguese.

If you have some free time, try translating the game as much as you can. There's no fixed date for the next release, so I can adjust the updates to include an extra translation, if you believe you will have the time and the energy to invest into this. If not, any help you can provide, no matter how large or small, would be a great thing to make the game progress.

Thanks for your support!

**Comment by galaipa** [comment]
Understood. I will consider contributing to the project, but unfortunately I don't have much free time at the moment.

That said, I'm closing the issue. Thank you very much for your time.
