### ISSUE TITLE
Recent tileset changes broken

### ISSUE THREAD

**Issue by maxteufel** [SuperTux/supertux#2306]
The tileset changes from 2022-10-06 are seemingly broken:

![screenshot cleaned](https://user-images.githubusercontent.com/6442985/194546395-e92094c9-b5c2-4892-b787-5dbebdc277c5.png)

**Comment by pazkero** [comment]
![Known bug](https://files.catbox.moe/iaiuac.png)

“Known bug”

**Comment by Rusty-Box** [comment]
This is less of the tiles being "broken" and more of a "tile-IDs have changed" situation. We are aware of this fact and are already at work of rebuilding most important levelsets/worldmaps with those changes!

For the main game, these include:
_All Story Mode Worlds, Bonus Island I + II, Revenge In Redmond, Christmas + Halloween Special_

Everything that does not come with the game (pre-installed) will be in the hands of their original creators or people from the community who wish to restore those older contrib. levels for v0.7+!

**Comment by Grumbel** [comment]
> This is less of the tiles being "broken" and more of a "tile-IDs have changed" situation. We are aware of this fact and are already at work of rebuilding most important levelsets/worldmaps with those changes!

That sounds broken to me. Tile ids should never ever under any circumstances change. Once assigned they should be considered permanent. Anything else is just a colossal waste of time, especially when you want to support addons.

On the art side: The tiling pattern in the new tileset looks *way* to obvious.

**Comment by JoniG59** [comment]
Why is this issue closed? It's not fixed in master branch
