### ISSUE TITLE
Make set_bonus work again

### ISSUE THREAD

**Issue by brmbrmcar** [SuperTux/supertux#231]
It is extremely useful.

**Comment by LMH0013** [comment]
Is "set_bonus" different from "add_bonus"?  The "add_bonus" script works just fine, perhaps that is what you're looking for.

**Comment by brmbrmcar** [comment]
set_bonus is different. It is good because you can have none, and if in the future more lives were implemented this would come in good use.

**Comment by Hume2** [comment]
I've just added this function. Remind me if it works and I'll close it.
