### ISSUE TITLE
Windows: Link Shouldn't Be Inside a Folder in the Start Menu

### ISSUE THREAD

**Issue by marc280492** [SuperTux/supertux#233]
Hello, I would like to propose something. When install the program on your computer with Windows, a folder is created in the Start menu, in the list of apps. Inside this folder there is only one direct access to enter the game. Would not it be better to put the program directly without folders? At least,  in Windows 10 it is much better.

![sense titol](https://cloud.githubusercontent.com/assets/11487343/11312751/7f20520a-8fd8-11e5-92ac-00de8e2c4de1.png)

PD: I can not open the version 0.4.0. There is an error message informing me that I haven't the file libeay32.dll in my computer. I have Windows 10 x64.

Thanks!

**Comment by brmbrmcar** [comment]
That will be fixed later.

**Comment by sydneyjd** [comment]
4.0 has not been released, so when did this naming start?

**Comment by brmbrmcar** [comment]
Nightly builds

**Comment by marc280492** [comment]
Download: http://forum.freegamedev.net/viewtopic.php?f=67&t=6630

**Comment by sydneyjd** [comment]
Ah. :-)

**Comment by sydneyjd** [comment]
@marc280492 We just started releasing the nightly builds, so not all the bugs have been wrinked out.
@maths22 Is this something you can fix?

**Comment by Hume2** [comment]
Windows 10 is a spyware.
...that doesn't have to be an excuse, but I'd like to.

**Comment by brmbrmcar** [comment]
What about innocent Wine?

**Comment by maths22** [comment]
Nightly builds are currently still a work in progress.  I will fix the DLL issue.  I will also see if it is possible to not create a start menu folder.

**Comment by Karkus476** [comment]
@maths22 For some reason, I am unable to assign this issue to you.

**Comment by maxteufel** [comment]
You can't assign issues to people who aren't organization members.

**Comment by Karkus476** [comment]
@maxteufel Ah. I thought maths22 was a member

**Comment by tobbi** [comment]
I will add him

**Comment by maths22** [comment]
Start menu behavior has been improved.  However, since we use CPack to generate our installers, we must generate this folder in the start menu.
