### ISSUE TITLE
text not show, ? instead

### ISSUE THREAD

**Issue by LeiYangGH** [SuperTux/supertux#2347]
**SuperTux version:**  SuperTux-v0.6.3-win64.msi
**System information:** *(details about your kernel, operating system, or distribution)*
主机名:           DESKTOP-1SLBP5D
OS 名称:          Microsoft Windows 11 专业版
OS 版本:          10.0.22623 暂缺 Build 22623
OS 制造商:        Microsoft Corporation
OS 配置:          独立工作站
OS 构建类型:      Multiprocessor Free
注册的所有人:     LeiYang
注册的组织:
产品 ID:          00331-20300-00000-AA690
初始安装日期:     2022/8/27, 18:04:13
系统启动时间:     2022/12/2, 20:05:42
系统制造商:       Intel(R) Client Systems
系统型号:         NUC8i7HVK
系统类型:         x64-based PC
处理器:           安装了 1 个处理器。
                  [01]: Intel64 Family 6 Model 158 Stepping 9 GenuineIntel ~3096 Mhz
BIOS 版本:        Intel Corp. HNKBLi70.86A.0064.2020.1028.1438, 2020/10/28
##### Expected behavior
show text in localized or english
##### Actual behavior
show ???
##### Steps to reproduce actual behavior
just run it 
##### Additio

**Comment by LeiYangGH** [comment]
![image](https://user-images.githubusercontent.com/5386998/205308889-c7c253e2-a780-4a88-be3e-0adb66c6a041.png)

**Comment by Vankata453** [comment]
This issue is fixed in latest `master`.
