### ISSUE TITLE
SuperTux works in Cheat Engine for TAS'ing and libTAS, but Hourglass not,

### ISSUE THREAD

**Issue by juanroman74454811** [SuperTux/supertux#2365]
**SuperTux version: 0.13 and 0.6.3
**System information: Windows 10

##### Expected behavior
Hourglass TAS tool working with SuperTux 0.13
##### Actual behavior
Game doesnt load when loaded with Hourglass
##### Steps to reproduce actual behavior
Get hourglass and set up SuperTux, then load the game with Hourglass,
Thats really all i got to say for this, just add compatibility for TAS tool,

**Comment by mrkubax10** [comment]
It is very unlikely that support for this tool will be ever added to 0.1.3

**Comment by mrkubax10** [comment]
Sorry but we cannot support every tool, please use tools that are supported.
