### ISSUE TITLE
Tux's feet can be seen under the igloo at the end of a level

### ISSUE THREAD

**Issue by Grumbel** [SuperTux/supertux#24]
Original [issue 13](https://code.google.com/p/supertux/issues/detail?id=13) created by SuperTuxTeam on 2012-05-27T07:14:48.000Z:

<b>What steps will reproduce the problem?</b>
Finish a level

<b>What is the expected output? What do you see instead?</b>
Should not see tux begin exitfg.png (foreground)

<b>Please provide any additional information below.</b>
Just increased the height of exitbg.png and exitfg.png from 192 to 195 pixels correct the problem. (using gimp for instance)

**Comment by sydneyjd** [comment]
If anyone sees this again, feel free to let us know, otherwise i consider it closed.
