### ISSUE TITLE
Unable to build with older boost

### ISSUE THREAD

**Issue by theofficialgman** [SuperTux/supertux#2406]
seems to be a known issue (since recent comments reflect build errors)

https://github.com/SuperTux/supertux/commit/bf459d4d12dd3ed5f9a4921e2af5fbdcbf95b5a9
https://github.com/SuperTux/supertux/commit/30ae6f58d4f0535d04a7ae0927c61b48a7daa6fc
```
/home/zjc/supertux/src/util/file_system.cpp: In function ‘void FileSystem::copy(const string&, const string&)’:
/home/zjc/supertux/src/util/file_system.cpp:77:62: error: ‘boost::filesystem::copy_options’ has not been declared
   fs::copy_file(source_path, target_path, boost::filesystem::copy_options::overwrite_existing);
```

**Comment by tobbi** [comment]
Thanks. I had inverted logic in the if statement.
