### ISSUE TITLE
Manual joystick settings not preserved when using a generic controller

### ISSUE THREAD

**Issue by LMH0013** [SuperTux/supertux#241]
Every time I start up SuperTux since SDL2 my generic controller does not work until I go into options and select manual configuration.  Once manual configuration is selected, the controller works fine.  Ideally, SuperTux would do this automatically on startup.

**Comment by solarjoe** [comment]
I still have this issue with the current nightly AppImage (2018-01-26 20:45) also with 0.4.0 and 0.5.1 The automatic control does not detect my iBuffaloClassic USB Gamepad. When I configure it manually it works like a charm, but the settings are load after a restart of SuperTux.
