### ISSUE TITLE
Put old SuperTux songs

### ISSUE THREAD

**Issue by Paulo-Tux** [SuperTux/supertux#2410]
**SuperTux version:0.6.3

Hello, I had a good idea which was to put old songs in newer versions. I'm European Portuguese in case you're asking. Here are some examples below. Hope this helps.

[Super Tux old musics.zip](https://github.com/SuperTux/supertux/files/11080956/Super.Tux.old.musics.zip)

**Comment by ScriptForAll** [comment]
That could be interesting to create an old SuperTux aesthetic in some level. However, if I'm not mistaken, some of those old musics have a license that clashes with GPL.

P.S.: Mais um tuga! :portugal:

**Comment by Paulo-Tux** [comment]
Agradeço essa informação, porem seria interessante criarem a versão 0.1.3 no 0.7.0 ou em versões mais recentes. (Thank you for this information, but it would be interesting to create version 0.1.3 in 0.7.0 or more recent versions.)

**Comment by MatusGuy** [comment]
Wtf mais dois tugas

**Comment by Paulo-Tux** [comment]
> Wtf mais dois tugas

E o que é que tens a haver com isso, bacano?

**Comment by Vankata453** [comment]
Please use English. Also no unneeded discussions.

**Comment by Vankata453** [comment]
Regarding the topic, old SuperTux music and sounds could be re-used with upcoming "Texture pack" add-ons but they will not be re-added to the main game.

**Comment by Paulo-Tux** [comment]
> Regarding the topic, old SuperTux music and sounds could be re-used with upcoming "Resource pack" add-ons but they will not be re-added to the main game.

I'm sad to hear about it. 😥😥😥

**Comment by ScriptForAll** [comment]
> upcoming "Resource pack" add-ons
Where was this discussed?

**Comment by Vankata453** [comment]
> > upcoming "Resource pack" add-ons
> 
> @Vankata453, where was this discussed?
> 
> 

Pull request #2357.

**Comment by Paulo-Tux** [comment]
@Vankata453, so I can just replace the original music with my own music, is that it?

**Comment by Vankata453** [comment]
@Paulo-Tux Yes. Either by putting it in the system, or userdata folder.

**Comment by Paulo-Tux** [comment]
So this issue is marked as completed, even though it is marked as unplanned in your case. Thank you.
