### ISSUE TITLE
Quem é a Gown? (Who is Gown?)

### ISSUE THREAD

**Issue by Paulo-Tux** [SuperTux/supertux#2411]
Encontrei este video e a namorada do Tux  chama-se 'Gown' em vez de 'Penny'. (I found this video and Tux's girlfriend is called 'Gown' instead of 'Penny'.)
[https://www.youtube.com/watch?v=5A9U3GGb2fY](url)

**Comment by Vankata453** [comment]
Please use "Issues" to report actual issues related to the game.

**Comment by Paulo-Tux** [comment]
Só queria saber quem era. (I just wanted to know who it was.) 😢

**Comment by Paulo-Tux** [comment]
Não faz mal, descobri há duas semanas quem é a Gown e inventei uma história por causa disso (a história está em português de Portugal, por isso traduzem para inglês, por favor, obrigado (mais um problema marcado como concluído, mesmo que esteja marcado como não planejado no vosso caso)).
[A história do Tux.docx](https://github.com/SuperTux/supertux/files/11414339/A.historia.do.Tux.docx)
