### ISSUE TITLE
Icy island secret level seems to be unreachable

### ISSUE THREAD

**Issue by diogovasconcelos99** [SuperTux/supertux#2417]
**SuperTux version: 0.6.3**
**System information:** Kubuntu 22.04.2 LTS (Jammy Jellyfish), kernel version: 5.19.0-38-generic

##### Expected behavior
After unlocking the level Icy Valley on the Icy Island, the secret path to the bonus level should be unlocked and reachable

##### Actual behavior
For instance, in the Forest Island you can reach the bonus 'Ancient Ruins' level from the 'Crumbling Path' level when you complete the latter. The secret path from Icy Valley to the bonus level isn't available

##### Steps to reproduce actual behavior
Complete the 'Icy Valley' level on the Icy Island and try to make the secret path

**Comment by Vankata453** [comment]
"Icy Valley" has a secret exit you have to finish the level from to unlock the secret path.
