### ISSUE TITLE
Tux doesn't shine

### ISSUE THREAD

**Issue by Paulo-Tux** [SuperTux/supertux#2430]
**SuperTux version: SuperTux-v0.6.3-699-gcfae5b81b-win32**
##### Expected behavior
Tux's body glows
##### Actual behavior
Tux's body doesn't glow
##### Steps to reproduce actual behavior
Play any level with low light and turn Tux into earth Tux with the cheat code (if necessary and if you have it) to see what happens.

**Comment by Alasdairbugs** [comment]
You need to elaborate a lot more on your issues. Like what does this even mean.

**Comment by Paulo-Tux** [comment]
I disagree, the earth flower gives Tux the ability to turn into a stone version of himself for a short amount of time. When turned to stone, Tux is invulnerable to all types of damage, but cannot move during that time.

**In dark areas the earth flower will also provides a small cone of light.**

**Comment by tulpenkiste** [comment]
@Paulo-Tux that section of the wiki is based on the current stable release of SuperTux.
In the nightlies, the Earth Flower works drastically different (rather than turning into stone, he instead turns into rock that rolls across the ground).
So it is, in fact, working as intended.

**Comment by Paulo-Tux** [comment]
I was wrong about the rock part, but Tux's body could also produce light in dark areas (like in 0.6.3)... I'll give you an example, in version 0.6.3, earth Tux has a miner's hat which gave it a cone of light (as everyone knows), and in version 0.7.x, earth Tux has its glowing body.

**Comment by tulpenkiste** [comment]
Given the fact that tux doesn't have the miners hat anymore, it wouldn't make sense for him to just glow

**Comment by Paulo-Tux** [comment]
Well, if the flower of the earth doesn't go, the flower of fire goes... I say.

**Comment by mrkubax10** [comment]
>  I mean, I could be wrong about this part but I believe that Tux will have his body glowing in the dark parts, be it whichever way.

Uranium Tux?

**Comment by mrkubax10** [comment]
Closing because glowing Tux doesn't make much sense to me, additionally some levels may be intended to be played in complete darkness and this change would break them.

**Comment by Paulo-Tux** [comment]
But there's one thing I still don't understand, how is Tux going to get through a level with 0% brightness without flashlights, glow blocks and glow in the dark things (not to mention the fire flower because of the fireballs)?
