### ISSUE TITLE
Error when playing the game and then quickly pausing

### ISSUE THREAD

**Issue by Paulo-Tux** [SuperTux/supertux#2435]
I ran into another error playing the game and then quickly pausing.

https://user-images.githubusercontent.com/126248752/231891415-cef18063-f145-43fa-89d1-fa07519e92de.mp4

**Comment by mrkubax10** [comment]
Which version is that?

**Comment by Vankata453** [comment]
> Which version is that?

Judging by the window title, it's 0.6.3.

**Comment by tobbi** [comment]
Please try the latest nightly from https://download.supertux.org/

**Comment by Paulo-Tux** [comment]
It still gives that error.

https://user-images.githubusercontent.com/126248752/235299988-dbddc575-3569-42a1-86bf-3679a7938261.mp4

**Comment by Vankata453** [comment]
Pausing the game too quickly when starting is the result of the game not having enough time to process the correct sprite for Tux, hence it uses the alphabetically first sprite action. I wouldn't consider this an issue, nor a bug.

**Comment by Paulo-Tux** [comment]
Incidentally, I hadn't noticed that.
