### ISSUE TITLE
Question about world map

### ISSUE THREAD

**Issue by Harchvertelol** [SuperTux/supertux#2439]
On the world map, some green dots (level entrances) flash yellow. What does it mean? I can't understand at all. Couldn't find info anywhere. Thank you!

**Comment by Semphriss** [comment]
It means that you maxed the level's stats: killed all badguys, collected all coins, found all secrets and beat the level in less time than the target time for the level. You can see the best scores you have for any level on the worldmap by looking at the bottom right corner of the screen, and during gameplay by pressing pause and looking in the bottom right corner.
