### ISSUE TITLE
Frozen Mole

### ISSUE THREAD

**Issue by Paulo-Tux** [SuperTux/supertux#2442]
https://user-images.githubusercontent.com/126248752/233831045-2cba9049-75d4-404c-b765-5f680c477f23.mp4

**Comment by mrkubax10** [comment]
Closing because I'm not even sure what this issue is supposed to mean, also this refers to old ice flower mechanic. Next time please provide more information in submitted issues.

**Comment by Paulo-Tux** [comment]
I'm sorry, I didn't remember that the Ice Flower works differently in version 0.7.
