### ISSUE TITLE
Buttjump in trampolines

### ISSUE THREAD

**Issue by Paulo-Tux** [SuperTux/supertux#2443]
https://user-images.githubusercontent.com/126248752/233831491-d9b2ecd8-95ab-4606-9b4c-b260b12b5380.mp4

**Comment by bruhmoent** [comment]
Could you please provide a description for this issue? I don't understand what is the meaning of this issue.

**Comment by Paulo-Tux** [comment]
I put Tux in the middle of two trampolines then I jumped and tried to buttjump to see what happened and I came to the conclusion that he dies if he buttjumps and in my opinion Tux shouldn't die.

**Comment by Alasdairbugs** [comment]
this is a collision issue, when tux has high momentum and is squeezed into areas smaller than a tile it usually damages him/ kills him.

**Comment by Alasdairbugs** [comment]
personally i think these situations are avoided by designing levels properly to ensure that these scenarios, where tux gets squished into areas like this, does not occur.

**Comment by Rami-Slicer** [comment]
This issue is pretty ancient, I remember dying like this in this exact sort of spot years ago.

**Comment by weluvgoatz** [comment]
Closing because it is derivative of #1892.
