### ISSUE TITLE
badflower

### ISSUE THREAD

**Issue by Paulo-Tux** [SuperTux/supertux#2444]
Please put this powerup, for the Corrupted Forest of course.
[badflower.zip](https://github.com/SuperTux/supertux/files/11303361/badflower.zip)

**Comment by tobbi** [comment]
Isn't this from Mattie's World?

**Comment by Paulo-Tux** [comment]
Yes, I thought you wanted to put this powerup in the Corrupted Forest.

**Comment by Alasdairbugs** [comment]
Where did you get that idea? Did a dev mention they wanted to add it??

Anyway, why are you still making issues for suggestions? You were already asked to use discussions for this. If you continue to ignore this simple request, you won't be posting here anymore altogether.

**Comment by Paulo-Tux** [comment]
I was just giving an idea and I just wanted to know if it was a good idea to put that powerup in the game but that's ok. You don't, I'm not upset about it either.
