### ISSUE TITLE
Timer doesn't reset with no-checkpoints death

### ISSUE THREAD

**Issue by GamerOn117** [SuperTux/supertux#2448]
**SuperTux version:**0.6.3-714-ga7aa8a8ba
**System information:** Windows 11

##### Expected behavior
When you die, the remaining time timer resets
##### Actual behavior
When you die, the remaining time timer continues where it was before you died
##### Steps to reproduce actual behavior
Die in a level with a timer

**Comment by Paulo-Tux** [comment]
This error also appears in... "New Super Mario Bros" for example, but nobody cares about it... I think.

**Comment by Vankata453** [comment]
This is the intended behaviour, as discussed in #2060.

**Comment by GamerOn117** [comment]
> 

There's just one problem: even if you didn't get any checkpoints, it still continues
