### ISSUE TITLE
Iceoverlay sprites do not line up.

### ISSUE THREAD

**Issue by Paulo-Tux** [SuperTux/supertux#2450]
##### Expected behavior
![Captura de ecrã 2023-04-29 150825](https://user-images.githubusercontent.com/126248752/235307163-985955df-398a-41a4-ad5e-1c89844c90e9.png)
##### Actual behavior
![Captura de ecrã 2023-04-29 150131](https://user-images.githubusercontent.com/126248752/235306851-bee320a3-b091-423e-8f7f-40ab3be7e283.png)

**Comment by mrkubax10** [comment]
Again, you are not providing enough information. Which version alongside with commit hash?

**Comment by RBUK123** [comment]
I noticed that the bag's iceoverlay should be flush with the bag and not slightly off to the side. This error must also happen to some badguys (not all).

**Comment by tobbi** [comment]
> A lot of badguys got new sprites and thus new hitboxes. Iirc. ice overlay positions are set within the repsective .cpp file of a badguy so they probably need to be updated. If that's the case, I may be able to do that myself but don't quote me on that.

**Comment by MatusGuy** [comment]
Tobbi... 😭 😭 😭

**Comment by Rusty-Box** [comment]
This got fixed by #2835 - Closing this.
