### ISSUE TITLE
Setting game speed to 0 breaks the game

### ISSUE THREAD

**Issue by Paulo-Tux** [SuperTux/supertux#2452]
https://user-images.githubusercontent.com/126248752/235312472-faedfed1-4d51-4527-abe9-1fbc732b0ce5.mp4

**Comment by Rusty-Box** [comment]
We really should imit how high/low you can set this setting.

**Comment by Paulo-Tux** [comment]
Agree, setting the game speed to a very low number (5%) breaks the game as well.

**Comment by Paulo-Tux** [comment]
Something similar happens on the world map as well.
https://user-images.githubusercontent.com/126248752/235318322-47a76d81-8a34-4236-8c49-32b43b88864b.mp4
