### ISSUE TITLE
SuperTux 2 closes automatically

### ISSUE THREAD

**Issue by KiciaPuma** [SuperTux/supertux#2456]
**SuperTux version: 0.6.3**
**System Information:** *(Kernel: 6.1.10-arch1-1; OS: Linux; Distribution: Arch Linux; System: Native; Desktop environment: GNOME v43.2; version gdm: 43.0;)*

I wish SuperTux 2 didn't turn off automatically.
Currently, when copying part of a level in the level editor, SuperTux 2 will sometimes automatically shutdown and thus I lose what I have done. I tried running SuperTux2 from the terminal and it shut down automatically again one time. The terminal was showing that a memory protection violation had occurred. I would like you to check that there is no error in the code that would cause such symptoms or that SuperTux2 is well compiled on Arch Linux.

Thank you for fixing the error.

**Comment by Vankata453** [comment]
Please provide the full stack trace.

**Comment by KiciaPuma** [comment]
> 

This is all the information at the moment. If I know anything more, I'll let you know.

**Comment by KiciaPuma** [comment]
> Please provide the full stack trace.

[WARNING] /usr/src/debug/supertux/SuperTux-v0.6.3-Source/src/supertux/level.cpp:95 Level saved as levels/Computer_s_world/level6.stl.
[WARNING] /usr/src/debug/supertux/SuperTux-v0.6.3-Source/src/supertux/level.cpp:95 Level saved as levels/Computer_s_world/level6.stl.
/usr/include/c++/12.2.1/bits/stl_vector.h:1123: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](size_type) [with _Tp = unsigned int; _Alloc = std::allocator<unsigned int>; reference = unsigned int&; size_type = long unsigned int]: Assertion '__n < this->size()' failed.

Error: signal 6:
supertux2(_ZN12ErrorHandler17print_stack_traceEv+0x30)[0x55a2ad9dcf30]
supertux2(_ZN12ErrorHandler12handle_errorEi+0x3c)[0x55a2ad9dcfcc]
/usr/lib/libc.so.6(+0x39ab0)[0x7f2120562ab0]
/usr/lib/libc.so.6(+0x8926c)[0x7f21205b226c]
/usr/lib/libc.so.6(gsignal+0x18)[0x7f2120562a08]
/usr/lib/libc.so.6(abort+0xd7)[0x7f212054b538]
/usr/lib/libstdc++.so.6(+0xdd3b2)[0x7f21208dd3b2]
supertux2(+0x2b539c)[0x55a2ad93039c]
supertux2(_ZN19EditorOverlayWidget4drawER14DrawingContext+0x128)[0x55a2ad917688]
supertux2(_ZN6Editor4drawER10Compositor+0x68)[0x55a2ad8fe9f8]
supertux2(_ZN13ScreenManager4drawER10CompositorRNS_9FPS_StatsE+0x2f)[0x55a2ad8acd5f]
supertux2(_ZN13ScreenManager9loop_iterEv+0x1c8)[0x55a2ad8ad338]
supertux2(_ZN13ScreenManager3runEv+0x28)[0x55a2ad8ad5c8]
supertux2(_ZN4Main3runEiPPc+0x4b3)[0x55a2ad871bc3]
supertux2(main+0x68)[0x55a2ad8418a8]
/usr/lib/libc.so.6(+0x23850)[0x7f212054c850]
/usr/lib/libc.so.6(__libc_start_main+0x8a)[0x7f212054c90a]
supertux2(_start+0x25)[0x55a2ad848d95]

And then it says that there is a memory violation and displays the supertux2 --developer command.
