### ISSUE TITLE
Graphics not running correctly 

### ISSUE THREAD

**Issue by pedrootaviorm** [SuperTux/supertux#2461]
I use 0.6.3, but I've tried other versions, I don't know what's happening, because I play other games normally. I use Windows 10, and AMD Radeon HD 4650. 
![supertux](https://user-images.githubusercontent.com/132627748/236359309-4595dfba-ee8e-47b6-a637-3562ab923ef4.png)

**Comment by Semphriss** [comment]
I'll presume this is the same as in #1531 - try following the steps given there.

**Comment by mrkubax10** [comment]
Feel free to reopen if issue persists
