### ISSUE TITLE
Question about levels with 0% light

### ISSUE THREAD

**Issue by Paulo-Tux** [SuperTux/supertux#2466]
There's one thing I still don't understand, if Tux's body won't shine, how is he going to get through a level with 0% brightness without flashlights, glow blocks and glow in the dark things (not to mention the fire flower because of the fireballs)? #2430.

**Comment by Alasdairbugs** [comment]
Dont make levels that are entirely dark if you're not going to provide light. simple as. stop asking about this.

**Comment by RBUK123** [comment]
... (sigh) That's ok.
