### ISSUE TITLE
Update check for SuperTux

### ISSUE THREAD

**Issue by tobbi** [SuperTux/supertux#248]
Currently, it is not possible to check whether a new version of SuperTux was released on the website. In order to get people up-to-date, adding an update check would make sense.

**Comment by Karkus476** [comment]
This could check a file in the downloads folder

**Comment by maxteufel** [comment]
The main problem is that Linux distros don't always keep the packages updated (and often you can't download and replace the files w/o root permissions).

A solution to this could be adding a compile flag enabling or disabling this behavior.

**Comment by maths22** [comment]
That would make sense.  My thought is that this behavior makes sense on Windows and OS X (where this is common behavior), but not for Linux.

**Comment by Karkus476** [comment]
I think @tobbi just means notify the user on the homescreen when outdated, not actually update.

**Comment by maxteufel** [comment]
> I think @tobbi just means notify the user on the main menu when outdated, not actually update.

Yeah, but even then. Linux distros don't always ship the latest release (see Debian).

**Comment by Karkus476** [comment]
But we do

**Comment by maths22** [comment]
We should then only have it enabled for builds from our repos, not for the ones that go in dist repos.

**Comment by Karkus476** [comment]
I think we should direct them to here, we have a downloads page

**Comment by maxteufel** [comment]
That might make some users wonder why 'the download and installation way changed'.

And fwiw, we'd have to provide statically linked binaries.
