### ISSUE TITLE
Check for language pack updates during main queue, after the program has loaded

### ISSUE THREAD

**Issue by tobbi** [SuperTux/supertux#249]
Currently, we check for language pack updates before the main loop has started to run, maybe we should change that.

**Comment by tobbi** [comment]
Sorry, my approach worked but automatically opened the add-ons manager, which might irritate people.

**Comment by maxteufel** [comment]
Postponed.

**Comment by tobbi** [comment]
Language packs have been phased out. Therefore I'm closing this.
