### ISSUE TITLE
Make Skull Tiles an option/type of Unstable Tiles

### ISSUE THREAD

**Issue by Rusty-Box** [SuperTux/supertux#2502]
Since the **Skull Tile** behaves almost identical to an **Unstable Tile**, minus the fact that they don't respawn (which they should) and don't break immediately, fusing both into one wouldn't be such a bad idea. Let's say when placing an unstable tile you have setting for "Break immediately" (Y/N) or something along those lines or make the Skull Tile a type of the Unstable Tile objects.

Alternatively, if we don't wanna do that, give Skull Tiles a more neutral name based on what it does. Skull Tile as a name only works when it is using skulls as a sprite :/

**Comment by tobbi** [comment]
If we use both, then they probably have different names in level files. We would have to convert one to another. We can not just abandon one thing

**Comment by Vankata453** [comment]
@tobbi Maybe we could add a "backward compatibility" entry for it in the `GameObjectFactory`?

**Comment by tobbi** [comment]
Maybe
