### ISSUE TITLE
Tilemaps + Platforms on a path do not function.

### ISSUE THREAD

**Issue by tylerandari13** [SuperTux/supertux#2506]
**SuperTux version:**
nightly (v0.6.3-745-g8d86c7c30)

**System information:** *(details about your kernel, operating system, or distribution)*
Linux Mint 21.1

##### Expected behavior
Moving Tilemaps and Moving Platform go to node 0 when sector loads

##### Actual behavior
Both moving platforms and moving tilemaps stay in the corner, breaking a lot of levels.

##### Steps to reproduce actual behavior
enter a new sector *through a door*, tilemaps on paths world fine when loading a sector through the editor

##### Additional debugging information
when loading the sector it gives the error `[WARNING] /home/runner/work/supertux/supertux/src/supertux/game_object_manager.cpp:70 GameObjectManager: name resolve for 'gen16860769533166231903360' failed`

**Comment by tobbi** [comment]
@tylerandari13 I assume this got fixed by ab1386570271106d3515ab0f8883c4a44499dd4b 

Please retest!

**Comment by Vankata453** [comment]
The issue was indeed fixed by the mentioned commit.
