### ISSUE TITLE
Nightly build  "SuperTux-v0.6.3-744-gbfb4106d8.glibc2.29-x86_64" (latest so far) has a problem

### ISSUE THREAD

**Issue by Up1504** [SuperTux/supertux#2507]
**Nightly build SuperTux-v0.6.3-744-gbfb4106d8.glibc2.29-x86_64:**
**System information:** *(Linux, ubuntu)*

##### Actual behavior: I downloaded lates nightly knowing it will work perfectly, same wanting the new backgrounds etc
well, it didnt do so, it crashes 80% of the levels you make. Im not sure if someone has already reported this bug, there is nothing wrong with my levels because they work perfect with the previous nightlies, but this new one, as i said, have crashed almost 10 levels already. Im pretty dissapointed that i lost so many hard worked hours because of this bug. 

##### Creating new sector, using automatically scrolling camera, using manual camera, etc are making this happen. But normal basically done simple level can break too. 

[END_SCENE.zip](https://github.com/SuperTux/supertux/files/11905181/END_SCENE.zip)

**Comment by MrGaming-18113** [comment]
This is already reported, most of problems should be for TilesID changes, missing backgrounds or decals.
I'm so sorry for your time spended on your levels, but currently i'm not sure how to fix it.

**Comment by Up1504** [comment]
TilesID changes, missing backgrounds or decals are a common levels crashing thing, but this is not the reason for this bug, i have made the levels on the latest one, and as i said, creating new sectors, editing camera or just making a new simple level are making this happen for me.

**Comment by MrGaming-18113** [comment]
> TilesID changes, missing backgrounds or decals are a common levels crashing thing, but this is not the reason for this bug, i have made the levels on the latest one, and as i said, creating new sectors, editing camera or just making a new simple level are making this happen for me.

Then i guess its a saving file bug, because this already happened on older nighly builds and it should be fixed right now.

**Comment by Up1504** [comment]
> 

This is latest nightly, isnt it?

**Comment by MrGaming-18113** [comment]
> This is latest nightly, isnt it?
I've already searched your current nighlty and it isn't, you should download the latest version. 
![image-9](https://github.com/SuperTux/supertux/assets/74196506/066f8a9d-d306-4621-9153-74a33dc49705)

**Comment by Up1504** [comment]
> > This is latest nightly, isnt it?
> > I've already searched your current nighlty and it isn't, you should download the latest version.
> > ![image-9](https://user-images.githubusercontent.com/74196506/249762455-066f8a9d-d306-4621-9153-74a33dc49705.png)

Oh yeah, ill try that, thanks

**Comment by Up1504** [comment]
> > > This is latest nightly, isnt it?
> > > I've already searched your current nighlty and it isn't, you should download the latest version.
> > > ![image-9](https://user-images.githubusercontent.com/74196506/249762455-066f8a9d-d306-4621-9153-74a33dc49705.png)
> 
> Oh yeah, ill try that, thanks

**Comment by Up1504** [comment]
Bro thanks, it works! 😄
