### ISSUE TITLE
Horrible problems in the latest nightly with the converter

### ISSUE THREAD

**Issue by Up1504** [SuperTux/supertux#2511]
**Nightly build from github SuperTux-v0.6.3-753-g0f594e1fa.glibc2.30-x86_64.AppImage**
**System information:** * Linux, ubuntu

Hi. As you might know im thankful you guys work on this awesome game and i have a problem.

I downloaded your latest nightly from the supertux github.

My levels had worked perfect on the latest on on your website btw.

Well, First of all a few levels crashed, thankfully some levels the editor opened and converted, but a lot of levels the editor does not even open. Also all the castle tiles have i quess accidentally turned
into unsolid ones, (even if i have sold on).

I have an 90% ready addon taken many hundreds of hours, i sure hope you guys can help me with this (since you decided to mess with the tile IDs and make a converter)

ST team member! If you want to take a look at the addon levels and be fair to me by helping me out of this jam, please text me on discord!

**Comment by Vankata453** [comment]
Fallbacks for missing sprites have been added to the game in 47f349f. Additionally, the tile converter is still WIP (Work-In-Progress), and hasn't been merged into `master` yet. These issues would be fixed for the final version.
