### ISSUE TITLE
Leafshot is hardcoded in the Kamikaze Snowball code!?

### ISSUE THREAD

**Issue by Rusty-Box** [SuperTux/supertux#2517]
I just learned that Leafshot's code is within `kamikazesnowball.cpp` which makes it currently impossible to change their sprite. They should be either their own separate object as they also have a different speed value and are also freeze-able.

**Comment by Vankata453** [comment]
Maybe object types should be used here instead? Would prevent code duplication.

**Comment by Rusty-Box** [comment]
> Maybe object types should be used here instead? Would prevent code duplication.

Would that still allow us to have a seperate instace of them in the editor menu? Otherwise having only one instance named Kamikaze **Snowball** may not really make it clear that it is them who has the forest variant as a object type. Either that or we rename the object to something more generic, like we did for Crusher.

**Comment by Rami-Slicer** [comment]
I think it would be best to rename them to something generic like "Flying Badguy" and simply allow their sprites to be switched.

**Comment by Vankata453** [comment]
I believe this should have been fixed on latest master.

@Rusty-Box Want to check?

**Comment by Rusty-Box** [comment]
The issue of Leafshot's sprite not being change-able is fixed which was the inital reason for this issue. Closing this.
