### ISSUE TITLE
Review credits

### ISSUE THREAD

**Issue by maxteufel** [SuperTux/supertux#252]
As mentioned in #243, the credits should be updated to include contributors after 0.3.5a, but also those who were forgotten to be added in the previous releases.

To get a list of all git authors ever, you can run `git log --pretty=format:"%aN %aE" | sort -u` in the git repo (taken from revision e6ed7b1, expires in 1 month: <https://zerobin.net/?9d1b88226b83076e#DXnbF/Bl4KTi3QIE+qTrVfTGrc+uiu2hWKOYjfqlk5w=>)

This list should be reviewed and the contributors should be mentioned in some way appropriate to their contributions (possibly: bigger contributions -> big mention, at least one commit: small mention in a category: "Other contributors").

**Comment by tobbi** [comment]
Fixed with 113c001
