### ISSUE TITLE
Downloading on Ubuntu Switch Error

### ISSUE THREAD

**Issue by Kratzy** [SuperTux/supertux#2521]
I downloaded Ubuntu and tried downloading supertux via megascript and it had an make error 2  or something like that, the guys from L4T Megascript told me to report an tell the devs to use this
https://github.com/PrismLauncher/PrismLauncher/commit/c520faed6d0e5e9472622f848ad8512b6c71c8e0
https://github.com/gulrak/filesystem

**Comment by Semphriss** [comment]
I don't think we currently have the means to support a non-standard system setup, since we don't have a switch running Ubuntu to test on. If toolchain-specific modifications are needed, it would be better to let the maintainers of the toolchains, or volunteers, provide maintenance for their port.

What is the build error in question? Perhaps there's a simpler way to fix it.

**Comment by Kratzy** [comment]
Im new to this but here are logs from the error
[sterror.odt](https://github.com/SuperTux/supertux/files/11995464/sterror.odt)

**Comment by Semphriss** [comment]
Your compiler (GCC 7.5.0, according to the logs) is too old and does not support the required C++17 features (specifically, the filesystem API). Please try with a more recent compiler, if you have one available. Note that, if I trust the compiler version, it would seem that you are using Ubuntu 18.04; if you could use Ubuntu 20.04 or 22.04 instead, that would give you easy access to a newer compiler. If not, you may try [compiling a modern GCC compiler manually](https://gcc.gnu.org/releases.html), using the version of GCC you are provided with.

If you do not have a more recent compiler, and do not want to install a newer version of GCC, you may try replacing `#include <filesystem>` with `#include <experimental/filesystem>` and `std::filesystem::*` with `std::experimental::filesystem::*`. Note that this is not tested though, and may not work as expected.

In any case, given that C++17 is required for many essential features in SuperTux, I don't think the team would be willing to backport the game to an older C++ standard. If you'd like to make a port, you may have to maintain it manually.
