### ISSUE TITLE
Moles having gravity has unintended consequences

### ISSUE THREAD

**Issue by Narre** [SuperTux/supertux#2526]
**SuperTux version:** Current git version (as of 11. 07. 2023 00:00 CEST)
**System information:** LMDE 5 64bit (not that it makes a difference)

As an unintended consequence of #2519, Moles now follow gravity even when they shouldn't - on levelflip. Since molehills are a part of the ground, they get flipped with it, but now, the flipped molehill falls to the ceiling. Moles' gravity should be reversed on levelflip. Not to mention that due to their hitbox, the moles fall way too low (to the point where they're barely visible). There's nothing inherently wrong with their hitbox, on tiles that do not have a "top cover" (like grass or snow) - for example blocks, they fall to the proper position, but on forest tiles, which are covered in grass, the molehills basically hide in the grass almost completely. That is, unless they're meant to be rendered in front of the grass, but that a) looks strange and b) they wouldn't have a z-pos of -50 if they were.

PS. Yes, I still exist. I just don't think my motivation for SuperTux will recover until the tile ID fiasco is solved for good.

**Intended behaviour:**

https://github.com/SuperTux/supertux/assets/14074789/e0eebf06-0d87-4300-abb4-b2a62a9501e3

**What actually happens:**

https://github.com/SuperTux/supertux/assets/14074789/80a60aba-dab7-4be9-b2c9-0b571c825988

**Comment by MatusGuy** [comment]
Thank you for noticing this. I'll get right to it
