### ISSUE TITLE
Integrate sprites from reTux

### ISSUE THREAD

**Issue by tobbi** [SuperTux/supertux#253]
xref: http://forum.freegamedev.net/viewtopic.php?f=68&t=6631

[retux_tux_sprites.tar.gz](https://github.com/SuperTux/supertux/files/54194/retux_tux_sprites.tar.gz)

**Comment by Karkus476** [comment]
These are dismembered Tux sprites. Do you want to create a set of frankenstein images first?

**Comment by tobbi** [comment]
According to onpon4, these can just be layed over the original sprites.

**Comment by onpon4** [comment]
Put a better way, paste the arms onto the respective bodies. Simple as that. They're the same size, so they don't even need to be repositioned. For example:

* Open tux_arms_run-0.png in KolourPaint
* Ctrl-A
* Ctrl-C
* Open tux_body_run-0.png in KolourPaint
* Ctrl-V

And that would give you the first frame of the run animation.

**Comment by misterhat** [comment]
A little faster than that:

```bash
for i in {0..14}; do
    convert "tux_body_run-$i.png" "tux_arms_run-$i.png" -gravity center -composite "run-$i.png";
done
```

I've attached a tarball of the sprites: [run.zip](https://github.com/SuperTux/supertux/files/74579/run.zip)

**Comment by tobbi** [comment]
These still look kind of fake. If anyone could tell me why they're not looping correctly, I'd be glad to accept a pull request.

**Comment by onpon4** [comment]
There are 16 frames in the animation, not 15. The last frame is missing from what misterhat posted.

**Comment by misterhat** [comment]
Not sure how I missed the last one. Here it is:
![run-15](https://cloud.githubusercontent.com/assets/1313483/12066470/db34714e-afad-11e5-8b30-f142e9333bc2.png)

**Comment by tobbi** [comment]
Can people check whether this looks good now?

**Comment by maxteufel** [comment]
This seems to work, the issue with bigtux and flowertux seems to be resolved as well.

**Comment by tobbi** [comment]
Okay, closing as per #issuecomment-168426530 and per confirmation on IRC.

**Comment by tobbi** [comment]
@onpon4 What fps for the run animation?

**Comment by onpon4** [comment]
ReTux adjusts the FPS based on how fast Tux is moving. It's one frame every 10 pixels. So if Tux was moving 100 pixels per second, it would be animated at 10 frames per second.
