### ISSUE TITLE
Earth Tux Animation Bug

### ISSUE THREAD

**Issue by z-Tux** [SuperTux/supertux#2533]
**SuperTux version:Last nightly for windows**
**System information:** *(details about your kernel, operating system, or distribution)*

##### Expected behavior
When taking an earth flower while pressing ACTION and DOWN, you should have the grow animation and THEN the roll animation
##### Actual behavior
It's making both
##### Steps to reproduce actual behavior
Take an earth flower while pressing ACTION and DOWN.
##### Additional debugging information
[https://youtu.be/NK-FQMNIi9M](url)

**Comment by NickerAban** [comment]
It's weird how you're like this?
