### ISSUE TITLE
Error with sectors

### ISSUE THREAD

**Issue by Chiquinho7788** [SuperTux/supertux#2536]
**SuperTux version:**v0.6.3-765-g3234bacd1-win32

##### Expected behavior

when testing should appear in both sectors the objects that manage to move

##### Actual behavior

The latest development versions have a problem, if you create a level that has 2 sectors in the level editor and put objects that can be moved when testing one of the sectors  eliminates those objects!
##### Additional debugging information

In version v0.6.3-win64 it works

**Comment by Vankata453** [comment]
Could you re-clarify the issue, or attach a video?

**Comment by tobbi** [comment]
Can you please test the latest development version?
