### ISSUE TITLE
yu

### ISSUE THREAD

**Issue by Thiagoq4803R** [SuperTux/supertux#2543]
**SuperTux version:**
**System information:** *(details about your kernel, operating system, or distribution)*

##### Additional debugging information

*If available, please attach a backtrace of a crash (you can get one using GDB or another debugger), or a core dump. If you're on GNU/Linux and your distro is using systemd, it's highly likely that a core dump is available using `coredumpctl(1)`.
If the issue only occurs in a custom level, please attach that too.*

##### Guidelines for reporting issues

- [ ] I have read <https://github.com/SuperTux/supertux/blob/master/CONTRIBUTING.md#bug-reports>.
- [ ] I verified this isn't an issue that's already been reported.
- [ ] I verified this isn't a [discussion](https://github.com/SuperTux/supertux/discussions), but an actual issue ─ that is, the game did something not intended such as crashing or giving error messages.
- [ ] This report only includes details about **one** (1) issue, feature request or topic.
- [ ] If I make a mistake while submitting this report I will use the edit feature instead of closing this issue and opening a new one.
- [ ] This issue is **not** about wrong translations (use Transifex for those), or anything unsupported (e.g. third-party add-ons).
- [ ] Once you're done, please remove the section 'Guidelines for reporting issues', the 'Additional debugging information' if it is empty, and any text in *italic font*.

**Comment by Frostwithasideofsalt** [comment]
ok

**Comment by Rusty-Box** [comment]
Hilarious. 10/10, idiot

**Comment by Frostwithasideofsalt** [comment]
![video](https://github.com/SuperTux/supertux/assets/60326522/017fad5a-7930-46ff-b182-e2c303fc0e84)

**Comment by Narre** [comment]
This seems like a serious problem that should be tackled as soon as possible. However, you seem to have created the issue in the wrong repository, as this is not a problem with SuperTux, but rather your brain. Please, contact the maintainers of your brain for further troubleshooting. Thank you.

**Comment by Thiagoq4803R** [comment]
I created a halloween 2023 map

**Comment by tylerandari13** [comment]
This is a very 🚀 moment.

**Comment by Vankata453** [comment]
@Thiagoq4803R This isn't the place to share maps (you can do that either at the [forums](https://forum.freegamedev.net/viewforum.php?f=69), or in the [Discord server](https://discord.gg/AcvtHWz)). Please do not make unwanted comments/issues here.
