### ISSUE TITLE
The command Effect.fade_out(2); doesn't work in my cutscene.

### ISSUE THREAD

**Issue by Linusintro** [SuperTux/supertux#2563]
0.6.3
Linux Mint, 5.15.0-78-generic

The command Effect.fade_out(2); should work just fine.

The command Effect.fade_out(2); does work on it's own but not in my cutscene.

I don't know.

None

- [x] I have read <https://github.com/SuperTux/supertux/blob/master/CONTRIBUTING.md#bug-reports>.
- [x] I verified this isn't an issue that's already been reported.
- [x] I verified this isn't a [discussion](https://github.com/SuperTux/supertux/discussions), but an actual issue ─ that is, the game did something not intended such as crashing or giving error messages.
- [x] This report only includes details about (1) issue, feature request or topic.
- [x] If I make a mistake while submitting this report I will use the edit feature instead of closing this issue and opening a new one.

https://github.com/SuperTux/supertux/assets/138787774/095f8d55-4ce3-4bd1-94cc-abdbad432022

**Comment by Linusintro** [comment]
The level can't be uploaded because of "Something went really wrong, and we can't process that file. Try again."

**Comment by tobbi** [comment]
Try putting it in a ZIP file.

**Comment by Linusintro** [comment]
> Try putting it in a ZIP file.

I did.

**Comment by tobbi** [comment]
> > Try putting it in a ZIP file.
> 
> I did.

... And attach it to this issue

**Comment by Linusintro** [comment]
> > > Try putting it in a ZIP file.
> > 
> > 
> > I did.
> 
> ... And attach it to this issue

Didn't work.

**Comment by tobbi** [comment]
Why not?

Linusintro ***@***.***> schrieb am Fr., 18. Aug. 2023, 17:33:

**Comment by Linusintro** [comment]
I made a mistake.

**Comment by Linusintro** [comment]
This wasn't an issue of the game it was an issue of me.
