### ISSUE TITLE
font can't show

### ISSUE THREAD

**Issue by gaboolic** [SuperTux/supertux#2571]
**SuperTux version:**
supertux's version: v0.6.3

**System information:** *(details about your kernel, operating system, or distribution)*
![image](https://github.com/SuperTux/supertux/assets/3831173/e4a2f440-5048-4ebd-8135-148013c81389)
Now I use linux mint, and I couldn't display it with ubuntu 22.04LTS before.

##### Expected behavior
Expected the font can show correctly.

##### Actual behavior
![image](https://github.com/SuperTux/supertux/assets/3831173/f0cadf52-d8a6-4f03-ad05-c08a3228ff40)

##### Steps to reproduce actual behavior
Open the game, then can see the font can't show

##### Additional debugging information

*If available, please attach a backtrace of a crash (you can get one using GDB or another debugger), or a core dump. If you're on GNU/Linux and your distro is using systemd, it's highly likely that a core dump is available using `coredumpctl(1)`.
If the issue only occurs in a custom level, please attach that too.*

I use `apt install supertux` to install.
supertux's version: v0.6.3

Now I use linux mint, and I couldn't display it with ubuntu 22.04LTS before.

**Comment by Vankata453** [comment]
@gaboolic Could you test this on the latest Nightly builds? https://download.supertux.org

**Comment by gaboolic** [comment]
> @gaboolic Could you test this on the latest Nightly builds? https://download.supertux.org

It works! 
![image](https://github.com/SuperTux/supertux/assets/3831173/dac2d92d-6358-49e8-8503-f6c8e8a3c79a)

**Comment by Vankata453** [comment]
Alright, nice! I will close this.

**Comment by gaboolic** [comment]
> Alright, nice! I will close this.

It's a development version, how can I play the release version?

**Comment by gaboolic** [comment]
> @gaboolic This is broken in the release version. To play the release version, you should change the language from the options menu.

That's Ok. Actually I wanna change language to English at the begining, but I can't recognize the broken fonts.
Now I can modify language against this image.

**Comment by olivertzeng** [comment]
> Could you test this on the latest Nightly builds? [download.supertux.org](https://download.supertux.org)
@Vankata453  could you make the AUR package for Nightly builds as well? thanks!
