### ISSUE TITLE
Text inputs will treat letters like navigation controls when using WASD for example

### ISSUE THREAD

**Issue by MatusGuy** [SuperTux/supertux#2577]
**SuperTux version: gb1844bd2c**
**System information:** Windows 10

##### Expected behavior
Text inputs should not treat letters like navigation controls and should let you edit without interruptions.

##### Actual behavior
They do.

##### Steps to reproduce actual behavior
- Set your keybindings to W - Up, A - Left, S - Down, D - Right. (or any letters)
- Go to any text input. This can be a script edit or a name input.
- Type W. As you can see, cursor moves up.

**Comment by tobbi** [comment]
This will probably only apply to up and down keybindings

**Comment by MatusGuy** [comment]
What?

**Comment by MatusGuy** [comment]
:pray:
