### ISSUE TITLE
Ice, air and earth Christmas hats

### ISSUE THREAD

**Issue by brmbrmcar** [SuperTux/supertux#258]
The hats are single-coloured, which I could change, but it would seem more traditional to just have one.
It is very weird to just have a hat for fire tux.
Air:
![stand](https://cloud.githubusercontent.com/assets/14023329/11850690/d93eae78-a426-11e5-8f1f-382ca6c71153.png)
Earth:
![stand](https://cloud.githubusercontent.com/assets/14023329/11850699/eb708486-a426-11e5-8189-ac2aac346128.png)
Ice:
![stand](https://cloud.githubusercontent.com/assets/14023329/11850708/f63881ac-a426-11e5-97c9-b1748810f1d5.png)

[Download zip](https://drive.google.com/open?id=0BzQ95zbrEQrhbmVQanVHVWRoTG8)

**Edit by @Karkus476  16/12/2015**: Sample images (note that some are omitted) added, shortened link.

**Comment by Karkus476** [comment]
Can you please just drag them into the GitHub comment box? Stupid file convoy thing is stupid.

- Karkus

**Comment by brmbrmcar** [comment]
Here: (it's a lot)

![backflip](https://cloud.githubusercontent.com/assets/14400196/11709987/e95a061c-9f13-11e5-8fbe-51b6e2859a2e.png)
![duck](https://cloud.githubusercontent.com/assets/14400196/11709986/e95a0d6a-9f13-11e5-999b-57eb2e18df8d.png)
![skid](https://cloud.githubusercontent.com/assets/14400196/11709985/e958f6c8-9f13-11e5-8b7f-ad4c2a340627.png)
![stand](https://cloud.githubusercontent.com/assets/14400196/11709989/e95e2a30-9f13-11e5-947c-c44baa0d98d8.png)
![walk-0](https://cloud.githubusercontent.com/assets/14400196/11709988/e95d6942-9f13-11e5-8004-2ac52f7794da.png)
![walk-1](https://cloud.githubusercontent.com/assets/14400196/11709990/e95eb63a-9f13-11e5-840d-b014c70e6c06.png)
![backflip](https://cloud.githubusercontent.com/assets/14400196/11709996/f0926d02-9f13-11e5-80c9-aff4113816a1.png)
![duck](https://cloud.githubusercontent.com/assets/14400196/11709999/f0957dda-9f13-11e5-971e-7cefdf0c458a.png)
![skid](https://cloud.githubusercontent.com/assets/14400196/11709995/f090fae4-9f13-11e5-8cf0-ecc746fd5460.png)
![stand](https://cloud.githubusercontent.com/assets/14400196/11709997/f0935348-9f13-11e5-8284-da529a85be5a.png)
![walk-0](https://cloud.githubusercontent.com/assets/14400196/11709994/f08b1b2e-9f13-11e5-9952-212c85d44bf7.png)
![walk-1](https://cloud.githubusercontent.com/assets/14400196/11709998/f09404fa-9f13-11e5-93c8-cac2c3f96441.png)
![backflip](https://cloud.githubusercontent.com/assets/14400196/11710005/f6f8e3ce-9f13-11e5-8eeb-89ef2165dcab.png)
![duck](https://cloud.githubusercontent.com/assets/14400196/11710004/f6f80a26-9f13-11e5-9f2d-97a3a57219a7.png)
![skid](https://cloud.githubusercontent.com/assets/14400196/11710003/f6f71c88-9f13-11e5-800a-170e1604ce72.png)
![stand](https://cloud.githubusercontent.com/assets/14400196/11710007/f72a6c6e-9f13-11e5-9e71-573ac5343cc5.png)
![walk-0](https://cloud.githubusercontent.com/assets/14400196/11710006/f7286b6c-9f13-11e5-811f-eaab1ab23c6f.png)
![walk-1](https://cloud.githubusercontent.com/assets/14400196/11710008/f72b54d0-9f13-11e5-954a-41f472c1f024.png)

**Comment by Karkus476** [comment]
@brmbrmcar There - I've organised it for you.

**Comment by Hume2** [comment]
The colours of those hats should correspond with the colours of actual hats. And we'd also like some source files like .xfc, .psd, .kra or whatever.

**Comment by brmbrmcar** [comment]
I haven't used those source files because they take up too much space. I could improve the colours to make them correspond though.

**Comment by brmbrmcar** [comment]
How should I improve these first?

**Comment by Hume2** [comment]
Closing for lack of support.
If you redraw these hats, please open a topic on the forum.
