### ISSUE TITLE
Remove BSD workflows

### ISSUE THREAD

**Issue by MatusGuy** [SuperTux/supertux#2585]
BSD workflows take around 2 weeks to even start running + nobody uses BSD. It's not worth continuing to maintain BSD workflows. Please remove them so we can have those juicy checkmarks next to commits appear again

**Comment by tylerandari13** [comment]
Also I dont think you can access the builds under the Summary tab until the BSD builds fail, so removing them would let us get our Summary builds faster.

**Comment by tobbi** [comment]
https://github.com/SuperTux/supertux/pull/2366 <-- currently stalled due to an issue on the VM's side. I'd much rather keep them (but disable them)

**Comment by MatusGuy** [comment]
Sure, disable them then.

**Comment by tobbi** [comment]
I've disabled them. Gonna close the issue
