### ISSUE TITLE
`CameraConfig` provides an obscure way to configure the camera

### ISSUE THREAD

**Issue by Vankata453** [SuperTux/supertux#2602]
`Camera` has an instance of the `CameraConfig` class, which sets various properties for the camera. The file, used for configuration, is `camera.cfg`, in the root directory.

This is very obscure. Ideally, it would either be made available via the config, configurable through the `Camera` object itself, or removed as a configuration feature altogether.

**Comment by mrkubax10** [comment]
In my opinion this feature should be removed. It's so obscure that almost no one knows about this and no one ever proposed such feature because there is no need for it.
