### ISSUE TITLE
Show correct type of Tux and direction when going off the screen

### ISSUE THREAD

**Issue by brmbrmcar** [SuperTux/supertux#262]
Currently, Tux just faces right and has no powerup.

**Comment by Hume2** [comment]
Levels should be designed so Tux shouldn't be able to go above the screen any way, so extending all those levels is a possible fix too.

**Comment by Karkus476** [comment]
@Hume2 That is true, but wouldn't actually fix the problem. For now, leave the levels as they are.

**Comment by LMH0013** [comment]
I'd suggest going back to using a generic indicator to show Tux's position above the screen.  The original was too small that players complained about missing it, but the current image matches too much with the character sprite making it appear confused.  What if the we just used a large arrow/triangle that changed color?  Make it clear and different from Tux himself.

**Comment by Hume2** [comment]
Big arrow, why not, but why the disco?

**Comment by LMH0013** [comment]
Lol.  I figure a dynamic image is easier to spot than a static one.  One could imagine a background that the arrow blended into, then the player might have trouble spotting it.  Add a little flash, and it will catch the eye.

**Comment by Rusty-Box** [comment]
Is this still something we consider fixing?
I personally don't see a need for Tux to be displayed in his current state for an offscreen marker. Its only purpose is to show you were you are. I would assume a player knows what powerup they had seconds ago.

**Comment by Rusty-Box** [comment]
Since this does not seem to be considered I will close this.
