### ISSUE TITLE
Tux malfunction

### ISSUE THREAD

**Issue by Chiquinho7788** [SuperTux/supertux#2623]
In supertux when the tux is big and crouched, it cannot jump to the right, but it can crouch jump to the left.

This problem has existed for a long time.

In the mobile version this problem no longer occurs

https://github.com/SuperTux/supertux/assets/139497254/70a560a8-068e-4f9c-84ec-752f812ca290

**Comment by tobbi** [comment]
Can you create a video of the behaviour?

**Comment by mrkubax10** [comment]
@tobbi Probably problem with keyboard limitation. Certain keyboards support only limited number of pressed keys at the same moment.

**Comment by Alasdairbugs** [comment]
@mrkubax10 is correct. An Anti-ghosting keyboard is required. This is a hardware limitation. This should probably be closed.

**Comment by Chiquinho7788** [comment]
@mrkubax10 I played tux with the arrow keys on the keyboard, and I changed it to "w,a,s,d" and this problem no longer happens!
