### ISSUE TITLE
Ability to get internal pointer from an object option

### ISSUE THREAD

**Issue by MatusGuy** [SuperTux/supertux#2632]
for example i want to get the contents of a ScriptObjectOption and i dont see any way to do this

**Comment by tobbi** [comment]
If ObjectOption was generic, that would help a lot.

**Comment by Vankata453** [comment]
We could add getters to an `ObjectOption` when needed.

**Comment by tobbi** [comment]
The syntactically correct option would be to make it generic.

**Comment by MatusGuy** [comment]
> If ObjectOption was generic, that would help a lot.

it'd also be pretty cool if the contents weren't edited via some add_to_menu function. i don't think that's where that function belongs

**Comment by Vankata453** [comment]
Why? It is one of an option's main features.

**Comment by MatusGuy** [comment]
wouldn't it be better if the menu would add the option instead of the option adding itself into the menu?

**Comment by Vankata453** [comment]
No, that'd be more of a hassle. It's not the menu's job.

**Comment by MatusGuy** [comment]
then why isn't this the case in ObjectSettings
