### ISSUE TITLE
Stable 0.6.3, story mode: bugs in some levels' designs which prevent getting 100% in them

### ISSUE THREAD

**Issue by bfg01** [SuperTux/supertux#2634]
Hello.

First I'd like to mention, excellent work so far with SuperTux.
Even more with the addition of the -almost complete- World 2; it's got some tricky parts and feels as challenging -frustrating- as the classic Nintendo Super Mario games.
Eagerly looking forward the other 2 worlds.

I just finished story mode, procuring to get 100% in all levels.
As far as I could see, most of them are pretty clearable with 100%, and without taking damage (given the skill enough of course...); but some few have bugs which completely prevent the 100%, and I'd like to mention them, in case it's possible to fix for future version 0.7.0.
Also, I'd like to share notes regarding a couple of levels that, while still quite possible to get 100%, they're *particularly tricky*.

**"Buggy" levels (100% not possible)**:

Entrance to the cave:

The curve of coins right beside the bouncer. Fixed in commit #2164 but only for the nightlies, not current stable

Penguins don't grow on trees:

The airflower is needed to access second secret in level (unless a flying dragon passed by that point to bounce upon or something), but then it's no longer possible to get 100% badguys since spiky bouncing foes can no longer be beaten.

Owls's skydive commando:

Not possible to beat all flying owls since several of them fly just too high and bouncing upon foes is not enough

**"Tricky" levels (100% still possible)**:

The owls again... :

One flying owl flies too high and must be lured to a previous area of level (backtracking and making a difficult jump at a point) to a point high enough to hit it.

Ghouls' lair:

A complicated level:
---**Imperative** to do the upper path first
---In upper path, in the first long drop, don't kill flying octopuses since they're needed to be able to go back up when backtracking
---**Don't** drop in the long drop with purple blocks
---After backtracking to do lower path of level, throw red lantern to the other side of the spikes (the left side) and on the red blocks to be able to do that other part later
---Along the way of lower path of the level, spare at least two flying octopuses; they're needed to be lured for bouncing to reach last 2 coins in upper ledge right beside the end of level

Thanks beforehand for your attention.

**Comment by mrkubax10** [comment]
Could you check if issue is still present in latest development version (can be found at https://download.supertux.org)?

**Comment by bfg01** [comment]
Which issue? All in general?

And if by "development version" you mean latest nightly, as much as almost impossible to play due to being full of graphic glitches, I think all issues are still present except for Entrance to the cave because it was fixed in that mentioned commit.

**Comment by Alasdairbugs** [comment]
Hi, it is possible to 100% all these stages. https://youtu.be/AtQ2q5O0RE4?si=UCiADcxvZBQBq41i and https://youtu.be/cpfIFgL182E?si=DMUSUqibjCLmFwg7 will answer ur questions.

Regardless, while some solutions are non-obvious, all levels are being reworked for 0.7. These will consider the 100% variable to a higher degree than previous, not only making them easier requirements, but not require specific powerups like before.

**Comment by bfg01** [comment]
@Alasdairbugs :
I watched your videos; but, please correct me if wrong, what do we understand by "getting 100% in a level"?
For me, it is "getting all coins (including penguin bonuses), all foes, and all secrets, *all in a single level go*".

Your videos are full of skill, but they seem more like speedruns with no 100% necessary...
Again, please correct me if wrong.

As for requiring specific powerups for foes and/or secrets, I actually don't think it's bad idea; though I do understand that it would probably require more complex/effort in level design for, say, all requirements be possible to be fulfilled in one go, but requiring for example a powerup from previous level and doing stuff in current level *in a given needed order*.

As long as it was made possible, it would make it very interesting, but yes, probably the idea is making the levels "simpler".

Thanks.
