### ISSUE TITLE
My ideas

### ISSUE THREAD

**Issue by Gorilli09** [SuperTux/supertux#2641]
### Discussed in https://github.com/SuperTux/supertux/discussions/2636

<div type='discussions-op-text'>

<sup>Originally posted by **Gorilli09** September 14, 2023</sup>
Worlds
1. The North
2. Desert
3. Small
4. Big
5. Jungle
6. Cloud
7. Lava
8. Space

Steam
1. Steam Trading Cards
2. Steam Workshop support
3. Steam Deck support

Controller
1. Hide mouse cursor when using controller
2. Controller vibration
3. Switchable controller buttons icons: Xbox 360 Controller, DualShock 3, Xbox Wireless Controller, DualShock 4, DualSense, Nintendo Switch Pro Controller, Steam Controller, Steam Deck, and Vanilla Generic Controller. I recommend Xelu's Free Controller Icons.
4. Peek with Right Stick

Editor
1. Controller support for Steam Deck users
2. MP3 and FLAC file support
3. Custom tilemap support
4. SDK
5. Custom content in Documents folder

Other
1. Cutscenes don't time-consume
2. Power-up Shop
3. Achievements
4. Entering pipes
5. Enemy encounters in world map (similar to Hammer Bros. in Super Mario Bros. 3)
6. Switching level planes (switching from foreground to background)
7. Lava instantly kills
8. Time attack
9. Online leaderboards
10. Mute on focus lost
11. Secondary bindings
12. Razer Chroma support</div>

**Comment by Vankata453** [comment]
Will close this, since it's best fit as a discussion, which it originally was.
