### ISSUE TITLE
Lack of unisolid hitboxes for GameObjects

### ISSUE THREAD

**Issue by MatusGuy** [SuperTux/supertux#2644]
I know the collision system is at a quite... weird state... not sure if we can add major features properly. But...

The current system lacks unisolid hitboxes for `GameObject`s.
This could be used, for example, in #2635, to add the ability to stand on top of the Granito.

**Comment by Vankata453** [comment]
The collision system only performs unisolid checks for tiles with the respective attribute, indeed.

However, I don't see why not add a property to `CollisionObject` which would indicate it's unsolid and according to that, only apply constraints/movement on top collision with the object.

**Comment by MatusGuy** [comment]
yeah this sounds like a good solution.

**Comment by Vankata453** [comment]
Do you want to work on this, or should I self-assign it?

**Comment by MatusGuy** [comment]
yeah you can self assign
