### ISSUE TITLE
Invincibility frames after using a door/teleport

### ISSUE THREAD

**Issue by Rusty-Box** [SuperTux/supertux#2649]
It is always quite annoying and unfair if you enter a door but an enemy is right in front of the exit door, getting Tux hurt. You could build a level to prevent that from ever happening, however, i see this as more trouble some and believe an even better solution would be to grant Tux a short moment of "invincibility" so that players have time to move away from an enemy should they be right in front of the door.

**Comment by Vankata453** [comment]
Even with invincibility frames, this is a design issue. If invincibility is given, wouldn't that only cover up the design issue, instead of fix it?

**Comment by Rusty-Box** [comment]
> Even with invincibility frames, this is still a design issue. If invincibility is given, wouldn't that only cover up the design issue, instead of point towards fixing it?

I wouldn’t say that. Yes you can attempt avoiding enemy presence near doors but in the process you limit the areas and ways you can place doors. Keep in mind, enemies that are not smart variants like Vicious Ivy can sometimes end up in all sorts of places or a snail you kicked near a door intentionally or by accident. To avoid all these cases most doors must be excluded from all places with even the slightest potential enemy presence. Invincible frames would give you a greater wiggle room. Levels should still attempt to prevent enemy groups near doors but should an enemy still slip in on or offscreen it would make much less frustrating

**Comment by Vankata453** [comment]
Fair, I see what you mean. Just wonder how many frames that invincibility should take up.

**Comment by Rusty-Box** [comment]
Not many. It should be just enough to get away from the spawn the door teleports you. A second should be just fine, I think. Not sure how many Tux gets from getting hurt but maybe try the same amount for teleporting?
