### ISSUE TITLE
Tux goes behind secret areas that haven't been revealed when dying

### ISSUE THREAD

**Issue by bplx** [SuperTux/supertux#2657]
**SuperTux version:** SuperTux-v0.6.3-946-g5dd39ca20.glibc2.29-x86_64
**System information:** KDE Neon, Linux 6.2.0-32-generic

##### Expected behavior
Tux does not go behind secret areas that have not been revealed when dying

##### Actual behavior

Tux clips behind secret areas while he's dying

##### Steps to reproduce actual behavior

Die above a secret area

##### Additional debugging information

Here's a video with it happening:

https://github.com/SuperTux/supertux/assets/74569315/f319e694-6cb6-48c5-8848-9b34b86f1fd4

**Comment by mrkubax10** [comment]
Even though this might look like an issue it gives visual hint where secret area is located.

**Comment by Vankata453** [comment]
I agree we should fix this, because this is a visual inconsistency, and secrets shouldn't be revealed like this. What we need is to draw Tux on a more front-most layer, when playing the death animation.

**Comment by tobbi** [comment]
Didn't I already fucking do this?

**Comment by tobbi** [comment]
@bplx Can you start supertux in debug mode by passing `--debug` and post the output here?

**Comment by tobbi** [comment]
I should have been more clear. Start with that flag and load the level. It should say something re calculated badguy falling layer.

**Comment by tobbi** [comment]
`[DEBUG] /home/runner/work/supertux/supertux/src/supertux/sector.cpp:339 Calculated baduy falling layer was: 101`

@Rusty-Box That's not correct, is it?

I'll fix the typo in a second.

**Comment by tobbi** [comment]
I thought this was an issue with the way I calculated the foremost layer. Turns out it wasn't.
