### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by symvizan** [SuperTux/supertux#266]
Hey!
I think the current SuperTux website is a bit old, and everything is at another place: the website itself is at hosting, the forum is at open source game forums and the wiki is at GitHub.
My friend is a webdesigner and if I would ask him I think he would make you an all-in-one website for free if you want it.

**Comment by sydneyjd** [comment]
We gave our website a makeover just a couple months back. Yes it looks oldish, but not many of us on the team like these all JS-no info websites that are popping up everywhere nowadays. Also, github is hosting the wiki(which we are still working on transfering over from our old wiki) and the website.

**Comment by Karkus476** [comment]
@symvizan Thanks for the offer! I doubt we would be able to accept it though, as @syndeyjd explained. The main problem is with hosting. We don't host much ourselves, and as a result all our resources are split up over what free 'canned' hosting there is.

- Karkus

**Comment by symvizan** [comment]
My friend has paid servers.

**Comment by Karkus476** [comment]
@symvizan We'd love to see what your friend can come up with. We're not promising to accept it though, and it may take some discussion among us to make a decision, but you can tell him we're interested. Also, it'd be far better if you could as them to join us here on GitHub though, so we can give them feedback directly.

**Comment by Hume2** [comment]
I'm closing this because this thread is dead.
If your friend makes something, then tell me to reopen it.
