### ISSUE TITLE
Light Block disguised as Bonus Block

### ISSUE THREAD

**Issue by Rusty-Box** [SuperTux/supertux#2670]
Placing a Light Block (a Bonus Block that emits light when hit) always looks identical to the other Bonus Blocks before hit once. This should be changed as it makes more sense to tell the player immediately which of these blocks is one that emits light. In dark areas/levels this is vital information!

Light Blocks already have an "off"-sprite which should be the default when placed in levels rather than looking like a normal Bonus Block.

**Comment by Miner34dev** [comment]
Fixed. Is it ok if i open a PR?

**Comment by Vankata453** [comment]
@Miner34dev Yes, you can go ahead!
