### ISSUE TITLE
The radius image of a flame is static.

### ISSUE THREAD

**Issue by bruhmoent** [SuperTux/supertux#2677]
Instead of it being an image with pre-determined height and width, it should be calculated in code to showcase the actual radius of a flame.

**Comment by MatusGuy** [comment]
I have a similar suggestion: #2640

**Comment by bruhmoent** [comment]
Similar, but not as related ;;;

**Comment by Alasdairbugs** [comment]
I suggest a kind of heat distortion effect. Much like that seen in a heatwave, you can see light being bent and therefore the stuff behind the flame would look wobbly and blurry.

**Comment by tylerandari13** [comment]
> I suggest a kind of heat distortion effect. Much like that seen in a heatwave, you can see light being bent and therefore the stuff behind the flame would look wobbly and blurry, in a ring the radius of the flame. This would probably follow the tail of the flame, and not show the outline fully, but could be a better visual indicator to prepare people

This is a cool idea, but i believe they were referring to the ring that appears in the editor, not ingame.
