### ISSUE TITLE
Throwing an Iceblock while mid-air or running kills Tux

### ISSUE THREAD

**Issue by MrIceblock** [SuperTux/supertux#2679]
**SuperTux version:** The latest Nightly Build
**System information:** Windows 11 22H2

##### Expected behavior
Tux should not die when throwing an Iceblock while either running or in mid-air.
##### Actual behavior
Tux dies when throwing an Iceblock under any of these conditions.
##### Steps to reproduce actual behavior
Throw an Iceblock while running or in mid-air. This was tested in Via Nostalgica.

**Comment by Rusty-Box** [comment]
This should get fixed asap!
