### ISSUE TITLE
Implement different format for text styling

### ISSUE THREAD

**Issue by maxteufel** [SuperTux/supertux#268]
Trying to update `data/credits.txt`, I have noticed some problems when trying to format the new content.

The format used to format text could be changed to something like Markdown.

**Comment by Hume2** [comment]
Could be, but we'd have to change all intros and extros as well.

**Comment by maxteufel** [comment]
Changing all text would be the smallest problem I guess.

**Comment by maxteufel** [comment]
This has been addressed by SuperTux/supertux@c0ceee20a8d0082f4d021bbefca8957b33d98b64 a long time ago already.
