### ISSUE TITLE
Textscroller without file property still "runs" in the background and closes game when done

### ISSUE THREAD

**Issue by Miner34dev** [SuperTux/supertux#2685]
**SuperTux version:** 0.6.3-956
**System information:** Garuda Linux

##### Expected behavior
Finish execution of script
##### Actual behavior
Close/Finish level
##### Steps to reproduce actual behavior
- Create a new level
- Add a script trigger
- Make it one shot
- Add a script
- Test the level
- Wait some time
- See the level fading out
##### Additional debugging information
On the terminal it outputs nothing about this.

**Comment by Miner34dev** [comment]
Tested up some things, and it seems the level crashes by itself, without the need of a script trigger.
Here is the worldmap to try to reproduce: [test.zip](https://github.com/SuperTux/supertux/files/13467716/test.zip)

**Comment by tobbi** [comment]
It's not the script trigger but the text scroller that causes the level to close after some time. Despite the fact that you didn't add a file to it, it still displays "something" (actually, nothing).

**Comment by Vankata453** [comment]
https://github.com/SuperTux/supertux/labels/status%3Aneeds-discussion ?
