### ISSUE TITLE
Earth Tux rolling ability can interact with climbable triggers

### ISSUE THREAD

**Issue by MrGaming-18113** [SuperTux/supertux#2693]
SuperTux Version: SuperTux v0.6.3-959-gea58eb298

Behaviour: Recently discovered today, while testing Earth flower ability i noticed that when Tux is on his Rock 'n Roll ability, it can interact with those climbable things like ropes or hand-stairs and i don't find any sense since Tux on the Rock mode doesn't have any hands or something for climbing. GoObY GoObEr bUg

https://github.com/SuperTux/supertux/assets/74196506/ac38f64e-f0ff-4e33-ad39-91b2719fa399

**Comment by MatusGuy** [comment]
Lmao
