### ISSUE TITLE
tinygettext translations with a %s substitution are displaying in English, not the specified language

### ISSUE THREAD

**Issue by jamescdericco** [SuperTux/supertux#2700]
**SuperTux version:**
SuperTux master commit ab557017188f4d141e8c96d8e031ae89a31c88ae

**System information:**
Fedora Linux 38 (Container Image), kernel 6.6.3-200.fc39.x86_64.

##### Expected behavior
Running `LANG=es ./supertux2 --help` should display "Uso: " on the first line of output.

##### Actual behavior
Running `LANG=es ./supertux2 --help` actually displays "Usage:", it does not display the Spanish translation as it should.

##### Steps to reproduce actual behavior
Run `LANG=es ./supertux2 --help`

##### Notes
This affects translations throughout SuperTux, not just the command line usage printout. For example, the level intro "contributed by" sentence is also affected by this issue, since its code uses "%s" substitution in the .po files.

**Comment by tobbi** [comment]
Fixed by e803444
