### ISSUE TITLE
[CI] MacOS builds sometime fail when using glbinding

### ISSUE THREAD

**Issue by tulpenkiste** [SuperTux/supertux#2704]
**SuperTux version:** master or any fork
**System information:** CI (macOS-11, Debug/Release, ON)

##### Expected behavior
Compiles without problems.

##### Actual behavior
```
...
In file included from /usr/local/include/glbinding/gl/gl.h:8:
/usr/local/include/glbinding/gl/types.h:10:10: fatal error: 'KHR/khrplatform.h' file not found
#include <KHR/khrplatform.h>
```
##### Steps to reproduce actual behavior
1. Start workflows.
2. Wait for macOS CIs to start

**Comment by tobbi** [comment]
Is this intermittent? Might be a problem with Github CI.

**Comment by tulpenkiste** [comment]
> Is this intermittent? Might be a problem with Github CI.

I've seen the problem occur randomly on any PR. I think maybe Github CI isn't doing dependencies properly

**Comment by tobbi** [comment]
Can you maybe report this here? https://github.com/actions/runner-images/issues

**Comment by tobbi** [comment]
Now I did.
