### ISSUE TITLE
cannot make canonical path: No such file or directory

### ISSUE THREAD

**Issue by ztianyang** [SuperTux/supertux#2706]
**SuperTux version:** commit 96682c1
**System information:** Arch Linux

##### Expected behavior
The game runs after compiling.

##### Actual behavior
The game doesn't run at all.

##### Steps to reproduce actual behavior
1. Download the latest source code archive from [https://download.supertux.org](https://download.supertux.org) and extract it.
1. Compile and run the game.

```
mkdir build
cd build
cmake .. -DENABLE_DISCORD=ON
make -j$(nproc)
./supertux2
```

##### Additional debugging information

```
$ ./supertux2
[FATAL] /home/tianyang/games/supertux/builds/supertux_nightly/src/supertux/main.cpp:746 Unexpected exception: filesystem error: cannot make canonical path: No such file or directory [/home/tianyang/games/supertux/builds/supertux_nightly/build/data]
```

There is no data directory in the build directory

```
$ ls
CMakeCache.txt           external            physfs                   supertux2
CMakeFiles               libLibPartioZip.a   physfs_project-prefix    supertux2.desktop
cmake_install.cmake      libLibSavePNG.a     SDL2_ttf                 tinygettext
config.h                 libLibSexp.a        SDL2_ttf_project-prefix  tinygettext_project-prefix
CPackConfig.cmake        libsupertux2_lib.a  squirrel                 version.h
CPackSourceConfig.cmake  Makefile            squirrel_project-prefix
```

**Comment by ztianyang** [comment]
I have to create the data directory manually for the game to run.

**Comment by mrkubax10** [comment]
You are supposed to run game from within directory containing data folder or by specifying it using `--datadir` command line argument.

**Comment by Vankata453** [comment]
> You are supposed to run game from within directory containing data folder or by specifying it using `--datadir` command line argument.

Perhaps the error message could provide this info as a potential solution?

**Comment by tobbi** [comment]
Why bother? We could create a data directory if it doesn't exist

**Comment by tobbi** [comment]
Please try again once the next nightly package is built
