### ISSUE TITLE
Improving + balancing the "Chasing Fish" Enemy

### ISSUE THREAD

**Issue by Rusty-Box** [SuperTux/supertux#2711]
Here are some proposed tweaks that should be done to the enemy "Chasing Fish" as it can be a bit annoying to deal with right now.

- Slightly decreasing the **Losing Distance** for easier avoidance
- No longer detect Tux when Fish is not facing Tux, allowing a bit of "stealth"
- Ease into max speed rather than switching from 0 to a 100 in an instant
   - If need be even decrease **Chasing Speed** ever so slightly
- Abort chasing when Tux is no longer in water or its view is obstructed by a solid wall
- Make **Tracking, Loosing** and **Chase Speed** no longer adjustable to prevent inconsistencey

**Comment by Rusty-Box** [comment]
Another thing:

- Chase Fish should kill other badguys while in chase mode (like Haywire)
  - Useful when luring them into a Dive Mine to defeat themselves

**Comment by weluvgoatz** [comment]
I agree with the easing aspect, as well as the aborting of chasing when Tux isn't in water, and the fish killing others while in chase mode, however I do disagree with some of the others:
- While designing, having the losing distance being slightly shorter significantly affected the gameplay in my opinion as the fish would stop chasing Tux almost immediately.  However, we should definitely still look into this.
- I prefer having the tracking, loosing, and chase speed be adjustable so that in different circumstances (such as a winding tunnel or a large open area) the fish can still be a threat.  
Also, the one asking so that the fish can't detect Tux if he's not facing it is weird, because then wouldn't that mean that the fish would stop chasing Tux as soon as he starts swimming away?

**Comment by Rusty-Box** [comment]
>       Also, the one asking so that the fish can't detect Tux if he's not facing it is weird, because then wouldn't that mean that the fish would stop chasing Tux as soon as he starts swimming away?

This only goes for initializing the chase. once they are in "chase mode" they will not be affected by this. This is purely to give the player the chance to avoid getting chase altogether if playing carefully around them!

**Comment by weluvgoatz** [comment]
Oh ok, thanks for clarifying

**Comment by Brockengespenst** [comment]
I had a look a this issue yesterday and already played around a bit on the following branch: https://github.com/Brockengespenst/supertux/tree/improve_chasing_fish
I added the following:

- No longer detect Tux when Fish is not facing Tux, allowing a bit of "stealth"
    -  Feels indeed more natural that chasing fish only spots Tux when it is facing
- Abort chasing when Tux is no longer in water
    - I considered the "water jump" as being in water so that chasing fish still continues to chase while jumping in water or out of water. When Tux is back on solid ground, chasing fish stops the chase. Feels more natural, except that chasing fish right now stays right below the surface. Maybe making him dive a bit deeper in such case would be better (though I would need to figure out what would be the best way to implement this).
- Chase Fish should kill other badguys while in chase mode (likeHaywire)
    - Also makes totally sense in my opinion. While adding this, I noticed that dive bomb does not explode when calling kill_fall, so I added this. Feels also pretty good and I guess that was what you intended.

Issues with the current state:
- Missing detection for obstructed view. This leads to chasing fish spot tux if he is in range and in water, but a solid wall is in between (See screenshot). For solving this, I would need to dive a bit deeper in the code and check how to do this.
<img width="602" alt="ChasingFishInWater" src="https://github.com/SuperTux/supertux/assets/155102424/fe206354-5c19-4400-8e5f-bf95689738e6">

@weluvgoatz: If you want to work on this issue, feel free to use changes from my branch or if you have better ideas for this, this is also fine.

**Comment by Brockengespenst** [comment]
I added the check for obstacles in the way and added a period of 0.2 sec with linear acceleration up to the maximum chase speed. Feel free to check and leave comments.
