### ISSUE TITLE
Improve Haywire jumping

### ISSUE THREAD

**Issue by Rusty-Box** [SuperTux/supertux#2716]
As far as I know, while chasing, Haywire will jump depending on Tux's y-position, relative to their own - If Tux is above Haywire as they approach a gap, Haywire will attempt a jump. If Tux is below Haywire, they will not jump and instead simply drop.

I suggest to have Haywire always attempt a jump when approaching a gap (such is the case with enemies like Captain Snowball), as often times Haywire will not jump even though they should, making them a pain to use for things such as luring them from point A to point B.

**Comment by bruhmoent** [comment]
Just ran into this problem and i fully agree

**Comment by Brockengespenst** [comment]
I created a PR that should adjust the behavior as mentioned. I have tested this in a small, self created level and it seems to work as expected. However, I did not test all levels that contain haywires, so not sure if this breaks any level design that intentionally relied on the old behavior.
