### ISSUE TITLE
Editor Decisions [Poll - vote now!]

### ISSUE THREAD

**Issue by Karkus476** [SuperTux/supertux#272]
Some big decisions need to be made regarding the situation of level editing in SuperTux.

It has been decided that @Hume2 's [in-game level editor](https://github.com/SuperTux/supertux/pull/269) (composed partly of code from and) based around the old in-game level editors will be added for 0.5.0. But what should we have as an external level editor (for more complex things like scripting)? 

**Here are some options (make a comment if you've got any ideas):**

1) Use *only* @Hume2 's in-game editor. Add features like scripting anyway, and possibly rethink the SuperTux GUI? Of course, when considering the two options below, we assume that @Hume2 's editor will be included too.
2) Use [Tiled](http://www.mapeditor.org/) by creating a SuperTux plugin for s-expressions (the SuperTux level format) and squirrel scripting, as well as many, many other things.
```
<Karkus> Is there any way to create plugins for Tiled? A plugin API?
<o11c> Karkus: yes, at least for input/output
<o11c> Karkus: but really it's best just to use the standard formats
```
3) Use [Flexlay](https://github.com/supertux/flexlay). This is already partially developed by myself  ( @Karkus476 ) and @Grumbel , with SuperTux level editing in mind.
4) Use [the c#/mono editor](https://github.com/SuperTux/supertux-editor). It's already very able, and has been used to develop features in the past. It has also suffered from some portability issues, and interest has been decreasing over time. It is not actively being developed, but has potential

*Here are some pros and cons for each option, I have attempted to be as unbiased as possible:*

**Pros**|**Cons**
-----------|-----------
_Option 1_ - Only Ingame Editor | _Option 1_ - Only Ingame Editor
No-one would have to download the SuperTux editor. Everything would be contained within the game. There would be no questions asking how to and where to download the editor. | The SuperTux GUI isn't capable of this kind of complexity. It would take literally years of work to get anything done, and we'd likely have to redesign SuperTux's GUI system, or use an externally developed GUI manager
_Option 2_ - Tiled Editor plugin | _Option 2_ - Tiled Editor plugin 
As it's externally developed, we wouldn't have to worry so much about the UI, and other more visible parts of the editor, we could simply create a plugin which worked as a backend to the editor which would create SuperTux .stl and .stwm files. This could make the editor far more stable, and we might have to worry less about portability | There would still be a huge amount of work to be done, and we would be starting from scratch. Some more impressive features like script editing may take longer to implement.
This may bring more people into the project, and if people recognize the name "Tiled", they may be interested in trying level editing. | Some features in Tiled may be incompatible with SuperTux's level format. This could overload the issues page, when people complain
Some publicity may be gained through Tiled (website coverage) and developers may be attracted to the project. | Suddenly working with a huge codebase may make development slow and hard
_Option 3_ - Flexlay Level Editor | _Option 3_ - Flexlay Level Editor
Developed especially for this purpose, Flexlay is already halfway to becoming a decent editor. It can already be used to develop SuperTux levels (albeit somewhat limited in this regard) and I have planned to include a built-in scripting API and editor and many other features | Although well developed, some code is going out of date and needs updating (PyQt4 -> PyQt 5?, I've already rewritten worldmap loading!) This could take time, but not so much as complete reimplementation
Written in Python 3 with PyQt, it is a versatile codebase which will be able to very quickly produce new (SuperTux specific) features and grow into a SuperTux-oriented development environment. | <b>
_Option 4_ - C# Level Editor | _Option 4_ - C# Level Editor
An already functional SuperTux level editor, what more do we need? | There have been some portability issues and is based around C# (Microsoft, ugh!)
It has most of the features currently implemented in SuperTux, and has been used to create levels in the past. | Except, no-one's developing it now, and I haven't seen anyone around who's still interested in developing it. Can it keep up with improvements to the normal game (which I'm sure will happen someday)

**Comment by Karkus476** [comment]
My vote goes to 2 or 3, as I personally don't want to work on 4 (C#), and 1 (fullt-fledged in-game) is not practical *at all*

**Comment by FuzzyToothpaste** [comment]
I like option 3. Flexlay looks appealing.

**Comment by brmbrmcar** [comment]
I have to go for 4. The built-in level editor will come anyway, as a good thing. Flexlay is just to hard to develop, making it much slower than it could be, and is still several steps behind.

**Comment by brmbrmcar** [comment]
And, I could develop it. Please don't say noone is interested, because you have asked people not to develop it any more.

**Comment by alketii** [comment]
I vote either for in-game editor or for Tiled. Flexaly looks great, but it still needs some work, but if those issues are fixed, then there is no need for tiled.

**Comment by Grumbel** [comment]
As for the build-in editor, I would like to have it, but I would much prefer it when that editor would be kept as simple as possible. It should be something I can use with a gamepad on a couch and it should be something easy enough that a five year old can build levels with it. Right now the build in editor just replicates the functionality of the external editor, I don't find that all that useful.

As for Tilted, last time I looked at it, it wasn't really flexible enough. It's not a bad editor when you want to start a new game, but it is kind of hard to retrofit into SuperTux without losing a lot of functionality already present in the C# editor.

The C# editor is still the most complete editor around, but the use of Gtk+ and C# makes it rather unappealing these days. Python and Qt would be much nicer to work with, but pragmatically speaking the C# editor works right now and if I would want to build more levels that editor would do the job just fine. Adding new objects and stuff to it is pretty easy. As for portability, as anybody actually tried compiling it on other OSs? What are the show stoppers?

PS: The switch from Qt4 to Qt5 is pretty trivial, just a couple of lines of code. The Flexlay code was kept at Qt4 for easier portability, as none of the Windows Python .exe tools supported Qt5 when I wrote it.

**Comment by bjorn** [comment]
I'm interested to hear more about the features missing in Tiled for editing SuperTux levels.

Flexlay does indeed look quite nice, but on the surface it also looks very similar to Tiled. Personally I'd very much welcome you to look at contributing to Tiled instead. In the few minutes of clicking around in Flexlay I've already seen some things that would be nice to have in Tiled as well!

**Comment by Karkus476** [comment]
@bjorn There are tons of features in Tiled which would work great for SuperTux levels, but what we really need is flexibility. Will it be easy to implement other features that appear only in SuperTux level creation? Will it be easy to keep that code separate from the rest of the Tiled code? Flexlay, although still only quite young (talking about the new Python 3 one at https://github.com/supertux/flexlay) in terms of development is designed specially for the purpose of being flexible. In theory, you could use it to edit any level, with a bit of work. I worry Tiled would be limiting in terms of what features we could create and what formats to use. Of course, this may be a false assumption, and I would love to have a more stable and widely known level editor!

**Comment by bjorn** [comment]
@Karkus476 I think the answer is, right now it's not easy, but we could work together to make the things you need possible. I'd love for Tiled to be more extensible and this is very much already part of its future roadmap, for example by adding support for scripting (to extend Tiled in many ways), projects (for project-specific settings) and an object library.

**Comment by maxteufel** [comment]
I'd suggest keeping Flexlay and an in-game editor. Reasons:

- in-game editor will allow players to create their own simple level
- if they want they can learn more about flexlay
- flexlay is written in Python, which is easy to learn and contribute to
- and it's portable, as is Qt
- C# is too much of a mess

**Comment by Jake41** [comment]
I am using the C# level editor and it works fine for level layout and scripting. As for Tiled, it just doesn't seem to be meant for supertux level creation, And Flexay will not work on my machine. 

I would recommend that you start up development on the Mono/C# Editor, unless in-game editor supports scripting in the future

**Comment by Karkus476** [comment]
@Jake41 What is your machine's OS?

**Comment by Jake41** [comment]
@Karkus476  I am running Elementary OS Freya 3.2 

   https://elementary.io/

**Comment by Karkus476** [comment]
@Jake41 didn't it ask you to select your supertux data directory?

**Comment by Jake41** [comment]
@Karkus476 It says:

<h5>No Data Directory Found.</h5>

Press OK to select your Supertux directory

**Comment by Karkus476** [comment]
@Jake41 Then you click OK, and select it right?

**Comment by Jake41** [comment]
@Karkus476 Yes, I select my supertux directory and click ok.
Then, it asks me for my supertux birnary. I then select that and also clik ok, and it says:

 FileNotFoundError: [Errno 2] No such file or directory: '/usr/images/tiles.strf'

**Comment by Karkus476** [comment]
@Jake41 Please could you make a detailed issue at <https://github.com/SuperTux/flexlay/issues>?

**Comment by Jake41** [comment]
@Karkus476  Just got Flexlay to work, I had typed the path wrong.

**Comment by Karkus476** [comment]
@Jake41 Okay, great! Don't forget that what exists now is just an example of what can and hopefully will exist in the future :smile:

**Comment by Mathnerd314** [comment]
@bjorn I mentioned some things that were missing from Tiled on IRC (~ a year ago); here's an updated list, roughly in priority order:
* The s-expr format (SuperTux already has a C++ library for the text part, but Tiled makes a lot of format assumptions)
* Object palette (https://github.com/bjorn/tiled/issues/432 -ish)
* Property editors for (types of) objects (https://github.com/bjorn/tiled/issues/818, https://github.com/bjorn/tiled/issues/205)
* The distinction between tilesets, tilegroups (categories), and tile images
* Linked polyline + image object for things that move on paths (kind of like https://github.com/bjorn/tiled/issues/707, but more limited)
* Handling sectors (kind of like https://github.com/bjorn/tiled/issues/1038)
* Moving tilemap platforms (these break a lot of Tiled's assumptions)
* Missing tile editing tools: the replace tool (https://github.com/bjorn/tiled/issues/866), rectangle (https://github.com/bjorn/tiled/issues/268), and the tile brush (https://github.com/bjorn/tiled/issues/974 -ish, the C# editor has a completely different solution though)
* Parallax layers (https://github.com/bjorn/tiled/issues/1071) - the C# editor doesn't do this either though

**Comment by bjorn** [comment]
@Mathnerd314 Many thanks for the detailed list and even linking to all the related Tiled issues! It's hard to say how much work these things are, but it gives a very good overview. Indeed, Tiled could still be extended in many ways to be more useful in general, though I also clearly see the need for allowing more game-specific extensions since often it is necessary to limit the level designer to what the game can deal with.

I think the s-expr format would be on your side to solve, though I'd like to know what "format assumptions" are causing problems there. The rest I could work on as time allows, but it will be a slow process of course. Many of those things I'll be doing anyway, whether you decide to use Tiled for SuperTux levels or not.

**Comment by Karkus476** [comment]
Closing, this poll has been finished. I will announce statistics soon.
Side-note: It's important to understand that by voting 2,3 or 4 we still want the in-game editor as well.
