### ISSUE TITLE
Positional audio exaggerated

### ISSUE THREAD

**Issue by qubodup** [SuperTux/supertux#274]
As far as I can tell, sounds are positional, relative to the sound source and the player character position.

However the impression you get from listening is disassociated with what you see. This is best demonstrated when using headphones and melting an enemy while standing on its left side, then walking to the right of the enemy. it moves a sound source - that feels close to the right ear - so that it feels close to the left ear. I tried to illustrate the issue (see attachment).

Demo video: https://youtu.be/3ocUr1Z464Q

Again: this should be tested with headphones.

I'm not familiar with the code but if this could be solved by changing some values/formulas, I might be able to try to come up with a solution if you could point me to the right file(s) and expressions to look for.
![hearsee](https://cloud.githubusercontent.com/assets/18312/11929222/856e85f0-a7d9-11e5-9943-5f7bbb0b6d7c.png)

**Comment by Hume2** [comment]
Yes, this is quite buggy. All sounds are relative to the top left corner of the screen, not to Tux.

**Comment by qubodup** [comment]
Would you happen to know which code determines this?

If you put on headphones and watch https://youtu.be/3ocUr1Z464Q you will notice that the sound position changes from one ear to the other when you walk over a melting enemy. So even if code-wise the sound is relative to a window corner, what you hear still appears to depend on where tux is and where the sound source is.

**Comment by tobbi** [comment]
Is this http://supertux.lethargik.org/bugs/view.php?id=637 ?

**Comment by Hume2** [comment]
It looks as it is.

**Comment by brmbrmcar** [comment]
I hear this even with laptop speakers.

**Comment by brmbrmcar** [comment]
Is it an issue with the sound files themselves?

**Comment by Hume2** [comment]
No, there's something with OpenAL.

**Comment by brmbrmcar** [comment]
Are the sound effects stereo?

**Comment by qubodup** [comment]
> Are the sound effects stereo?

You can use soxi (sox package) or Audacity to get that info and keep the discussion shorter.

    $ for i in *wav *ogg; do echo `soxi -c $i` $i; done

some sounds are stereo, some are mono http://codepad.org/tputpOAs .

> Is this http://supertux.lethargik.org/bugs/view.php?id=637 ?

As far as I can tell, it's different

> While a bomb is ticking, it makes a hissing sound. This sound seems to play entirely in the left channel, entirely in the right channel, or equally in both channels depending on the position of the player compared to the bomb. I would expect the volume in each channel to change continuously as a function of the position.

For other sounds like melting I can say that if it melts closely to tux on the right it does not play on one channel only (It's just too strong on right and/or too weak on left). If it melts on the right edge of the screen, it's much more quiet.

So as opposed to the original bug report, the audio does not seem to only have 3 states like

* 100% left 0% right or
* 50% left 50% right or
* 0% left 100% right

but seems to be somewhat flexible.

**Comment by Mathnerd314** [comment]
Sound_manager uses OpenAL's positioning/listener API: https://github.com/SuperTux/supertux/blob/master/src/audio/sound_manager.cpp#L374. 
Maybe we could just add a z-coordinate.

**Comment by tobbi** [comment]
<Tobbi> Hey. I'm trying to get stereo panning right. However, once I set the position of my mono source, it either plays on the right channel, the left channel or (if it's directly in the middle) on both channels.
<Tobbi> I want smooth playing on both, if that's possible.
<KittyCat> rotate the source in a circle
<KittyCat> something like: x = pan, y = 0, z = -sqrt(1.0 - pan*pan), where 'pan' goes from -1 to +1

**Comment by tobbi** [comment]
Please test the fix I just committed. Nightly builds available from http://download.supertuxproject.org/download/ once the build finished.

**Comment by Hume2** [comment]
I've just noticed that the hissing bomb is audible at nearly the same volume all trough the level. Fortunately, I've managed to fix it in my PR.
