### ISSUE TITLE
Sound Object plays sounds of all sectors at once

### ISSUE THREAD

**Issue by Rusty-Box** [SuperTux/supertux#2744]
**Example:**
A level with 3 sectors - each of which has one Sound Object present, playing a sound - will play all of these three sounds at the same time in one sector instead of only playing the sound from the Sound Object in that specific sector.

Another thing (since I forgot about it last time), you can hear the sound of the Sound Objects during the level intro screen, which should be fixed also!

**Comment by mrkubax10** [comment]
I can self-assign this.

**Comment by mrkubax10** [comment]
After little bit of debugging I can say this probably is another bug of openal-soft. We definitely should replace OpenAL with SDL2 audio capabilities.
