### ISSUE TITLE
Couldn't mount levels from the user directory '/home/web_user/.local/share/supertux2/' to PhysFS searchpath: not found

### ISSUE THREAD

**Issue by enderandrew** [SuperTux/supertux#2758]
**SuperTux v0.6.3-1056-g169decf38 WASM**
**Debian Unstable x86_64:** *(details about your kernel, operating system, or distribution)*

##### Expected behavior
Unsure. Does this error suggest there would be persisted storage for add-ons or profile saves that isn't working?

##### Actual behavior
VM111:79 [WARNING] /home/runner/work/supertux/supertux/src/supertux/main.cpp:287 Couldn't mount levels from the user directory '/home/web_user/.local/share/supertux2/' to PhysFS searchpath: not found

##### Steps to reproduce actual behavior
Console / Developer mode starting the game in WASM in Chrome and Edge

##### Additional debugging information
VM111:79 [WARNING] /home/runner/work/supertux/supertux/src/supertux/main.cpp:287 Couldn't mount levels from the user directory '/home/web_user/.local/share/supertux2/' to PhysFS searchpath: not found
(anonymous) @ VM111:79
put_char @ supertux2.js:1
write @ supertux2.js:1
write @ supertux2.js:1
doWritev @ supertux2.js:1
_fd_write @ supertux2.js:1
$func12090 @ supertux2.wasm:0x58b078
$func1855 @ supertux2.wasm:0xa55c1
$func804 @ supertux2.wasm:0x28745
$func11908 @ supertux2.wasm:0x580d7c
$func3651 @ supertux2.wasm:0x208bad
$func2330 @ supertux2.wasm:0xea895
invoke_iii @ supertux2.js:1
$func437 @ supertux2.wasm:0xb959
$func6540 @ supertux2.wasm:0x3a42f5
invoke_vii @ supertux2.js:1
$Zg @ supertux2.wasm:0x30f91f
Module._main @ supertux2.js:1
callMain @ supertux2.js:1
doRun @ supertux2.js:1
(anonymous) @ supertux2.js:1
setTimeout (async)
run @ supertux2.js:1
runCaller @ supertux2.js:1
removeRunDependency @ supertux2.js:1
finish @ supertux2.js:1
finish @ supertux2.js:1
(anonymous) @ supertux2.js:1
callUserCallback @ supertux2.js:1
(anonymous) @ supertux2.js:1
setTimeout (async)
safeSetTimeout @ supertux2.js:1
audioPlugin_handle @ supertux2.js:1
(anonymous) @ supertux2.js:1
FS_handledByPreloadPlugin @ supertux2.js:1
processData @ supertux2.js:1
FS_createPreloadedFile @ supertux2.js:1
finish @ supertux2.js:1
onload @ supertux2.js:1
processPackageData @ supertux2.js:1
(anonymous) @ supertux2.js:1
xhr.onload @ supertux2.js:1

##### Guidelines for reporting issues

- [ ] I have read <https://github.com/SuperTux/supertux/blob/master/CONTRIBUTING.md#bug-reports>.
- [ ] I verified this isn't an issue that's already been reported.
- [ ] I verified this isn't a [discussion](https://github.com/SuperTux/supertux/discussions), but an actual issue ─ that is, the game did something not intended such as crashing or giving error messages.
- [ ] This report only includes details about **one** (1) issue, feature request or topic.
- [ ] If I make a mistake while submitting this report I will use the edit feature instead of closing this issue and opening a new one.
- [ ] This issue is **not** about wrong translations (use Transifex for those), or anything unsupported (e.g. third-party add-ons).
- [ ] Once you're done, please remove the section 'Guidelines for reporting issues', the 'Additional debugging information' if it is empty, and any text in *italic font*.

**Comment by Vankata453** [comment]
It's not an error, it's a warning. It appears because no levels have been created or modified yet.

To not confuse users with developer mode on, I believe this warning can be disabled by checking whether that directory exists before attempting to `PHYSFS_mount()` it ([src/supertux/main.cpp:285](https://github.com/SuperTux/supertux/blob/master/src/supertux/main.cpp#L285)).
