### ISSUE TITLE
Issues with gradients and camera zoom

### ISSUE THREAD

**Issue by Frostwithasideofsalt** [SuperTux/supertux#2770]
I'll add more to this when i can, im just making the issue just so i don't forget.

When the camera zooms out, the background gradient doesn't properly scale with the camera, resulting in a rectangle gradient showing up in the top left of the screen, with black visible around the gradient 

This issue also applies to the screen fade out effect

**Comment by Frostwithasideofsalt** [comment]
![image](https://github.com/SuperTux/supertux/assets/60326522/6f5a1b9e-d2d4-4751-b64e-532dd85a7202)

**Comment by tobbi** [comment]
Is this really https://github.com/SuperTux/supertux/labels/priority%3Ahigh ?

**Comment by mrkubax10** [comment]
It's just a visual bug so I wouldn't say that it's high priority.

**Comment by Vankata453** [comment]
I believe it is high priority because it only takes to have a gradient in a level and zoom in it to have it show improperly. Perhaps rather medium priority?

**Comment by mrkubax10** [comment]
> Perhaps rather medium priority we can put it then?

Yes.
