### ISSUE TITLE
Crash when switching to new world within a world map

### ISSUE THREAD

**Issue by iahung2** [SuperTux/supertux#2774]
**SuperTux version:** SuperTux Nightly 2024-02-05 16:50 Windows (64 bit)
**System information:** Windows 8.1 64 bit, Intel i5-4460 integrated graphics

##### Additional debugging information

I playing SuperTux for very long but have never read the document. So, I could get the terminology wrong. But, it's basically that. For example, in Mattie's World world map, switch to DOOM Preview crashed the game.

Not happening with previous Nightly or stable.

**Comment by iahung2** [comment]
One additional information: also not happening on my own build of SuperTux from source on MSYS2 CLANG64, so, it's specific to the Nightly build provided by you.

**Comment by komaros1** [comment]
This happens to me with other worldmaps like industrial island
