### ISSUE TITLE
windows 0.6.3 font is ？

### ISSUE THREAD

**Issue by xingwozhonghua126** [SuperTux/supertux#2790]
SuperTux version: 0.6.3

System information: Windows

Expected behavior
I expect the Chinese font to display correctly in the game.

Actual behavior
The Chinese font appears as question marks or other symbols instead of displaying properly.

Steps to reproduce actual behavior
Launch the game on a Windows machine.
Navigate to a screen or level with Chinese characters.
Observe the display of the Chinese font.
Additional debugging information
I have not been able to find a solution to this issue.
![image](https://github.com/SuperTux/supertux/assets/18661883/93f8fc61-5459-4483-ad00-a15d1649a8da)

**Comment by Vankata453** [comment]
To solve this, download a [development version](https://download.supertux.org/) (make sure it's from the `master` branch).

**Comment by xingwozhonghua126** [comment]
![image](https://github.com/SuperTux/supertux/assets/18661883/dc224f9e-a7c1-4c96-a0df-9bcd41e309b6)
