### ISSUE TITLE
Add subtitles for Tux rap

### ISSUE THREAD

**Issue by tobbi** [SuperTux/supertux#2808]
I think it would be fun to create some subtitles for the Tux rap scene so everyone knows what he's rapping about. Here's an example:

```
I'm a penguin and I like fish,
fish, yo, is my favorite dish.
Do you see that big-ass rock,
It's almost as big as my... igloo.

Did you know you are a bird,
And the bird is the word.
Also your plumage is so nice,
that's why I'm rapping here in the ice.
```

**Comment by MatusGuy** [comment]
nahh who let bro cook

**Comment by tulpenkiste** [comment]
We tanking the supertux approval rating with this one :fire: :speaking_head:

**Comment by Vankata453** [comment]
But... subtitles of some sort on the rap scene would probably actually be cool to have?

**Comment by Frostwithasideofsalt** [comment]
Tobbi how many hours has it been since you last slept

**Comment by tulpenkiste** [comment]
> But... subtitles of some sort on the rap scene would probably actually be cool to have?

I think it would be best to leave it to the players imagination... if the "Tux rap" even gets added, that is.

**Comment by Vankata453** [comment]
> I think it would be best to leave it to the players imagination... if the "Tux rap" even gets added, that is.

Fair. Just wanna give this an opportunity to be discussed, regardless of the joke.

**Comment by rapic45** [comment]
Bro cooking in the studio 🔥 🔥

**Comment by rapic45** [comment]
But i think it will be a cool idea to have subtitles for that scene
