### ISSUE TITLE
Question: is there a Beta (test) for the current development state of the next world and levels?

### ISSUE THREAD

**Issue by Lulu-Games** [SuperTux/supertux#2818]
I want to play the next world (dessert) and maybe see the Changes.

**Comment by komaros1** [comment]
No only if you are a play tester I think.The closest to this are the Nigthly Builds which can  be found here https://download.supertux.org

**Comment by Lulu-Games** [comment]
> No only if you are a play tester I think.The closest to this are the Nigthly Builds which can be found here https://download.supertux.org

I'm using these versions. Because i like the new Tux sprites
