### ISSUE TITLE
Make small Tux a little bit bigger

### ISSUE THREAD

**Issue by GNUAn** [SuperTux/supertux#2829]
Small Tux is so small, that he can't catch money with his head, he needs to jump to get it

**Comment by MatusGuy** [comment]
Intended. Also we're not making tux bigger because that means we'd have to recreate every sprite

**Comment by GNUAn** [comment]
I've meant hitboxes and sprite size

**Comment by MatusGuy** [comment]
Yes and a bigger hitbox implies drawing a new sprite
