### ISSUE TITLE
cmake rules fail to find libvorbis when it isn't linux

### ISSUE THREAD

**Issue by yurivict** [SuperTux/supertux#283]
See how it fails to find -lvorbis: http://pastebin.com/erawMfrp

It is installed in /usr/local. I am pretty sure cmake's own rules in general set all the right paths.

**Comment by devnexen** [comment]
Works perfectly fine under OpenBSD though (it seems you re running under FreeBSD ?), same thing third party softwares are installed under /usr/local.

**Comment by yurivict** [comment]
Yes, I am on FreeBSD.

**Comment by maxteufel** [comment]
Could that be a compiler difference? OpenBSD uses gcc, FreeBSD uses clang these days, right?

**Comment by yurivict** [comment]
Could be, but there are a lot of cmake ports in FreeBSD, and they overwhelmingly detect libraries fine.

**Comment by devnexen** [comment]
Should work I have tested under FreeBSD 10.2 (from source not the port but all dependencies, hence vorbis came from the ports) to compare performance with OpenBSD and it worked out of the box, with clang as I was under x86/64 hardware ... It should have anything to do with the compiler ... it seems a linker problem. One of the reasons (and I m not saying it is this one...), your port system believe verbs is installed whereas it is not, so ports database "rotten" ... Was supertuxkart from ports ?

**Comment by yurivict** [comment]
It was games/supertux, vorbis is installed, it fails because it doesn't supplu -L/usr/local/lib:
```
/usr/bin/clang  -O2 -pipe -fno-omit-frame-pointer  -fstack-protector -fno-strict-aliasing -DCHECK_FUNCTION_EXISTS=vorbis_bitrate_addblock    CMakeFiles/cmTC_6677d.dir/CheckFunctionExists.c.o  -o cmTC_6677d  -lvorbis /usr/local/lib/libvorbisfile.so /usr/local/lib/libvorbis.so /usr/local/lib/libogg.so -Wl,-rpath,/usr/local/lib
/usr/bin/ld: cannot find -lvorbis
```

**Comment by yurivict** [comment]
With gcc it passes vorbis, but still fails on iconv problem (another  bug# here).

**Comment by devnexen** [comment]
Odd ... ok I have a FreeBSD box running anyway, could try.

**Comment by devnexen** [comment]
In my case the current package is 0.3.5 ... for the devel version ... Much older for the "normal" port. Did you update manually the port version ?

**Comment by yurivict** [comment]
Yes, I updated PORTVERSION=0.4.0

**Comment by devnexen** [comment]
Careful with this, I submit ports updates myself :) but the thing is some patches are sometimes applied for the ports. And it seems there is a patch for the Cmake process ... maybe then it fails to apply this patch for 0.4.0 ? Just a guess.

**Comment by devnexen** [comment]
You might need to "remake" properly the patch for 0.4.0 (if necessary, it should not be hard) and submit your update to the maintainer.

**Comment by yurivict** [comment]
Will try remaking them.

**Comment by maxteufel** [comment]
As long as the patches don't affect other platforms we'll be happy to merge the by the way.

**Comment by devnexen** [comment]
ah yes might be better :)

**Comment by yurivict** [comment]
In this case patch only affects data paths, xml. Both problems will still remain after patch.
ths, xml. Both problems will still remain after patch.

That's why I reported both bugs, so that upstream can fix this. cmake is supposed to work out of the box. All paths in cmake itself are correct.

Look what they do with iconv:
```
double iconv(iconv_t cd,  char **inbuf, size_t *inbytesleft, char **outbuf, size_t *outbytesleft);
```
iconv *never* returns double. There should be no need to try double return. It is just wrong.

**Comment by devnexen** [comment]
Yes you re right for the patch but for the sake of the curiosity I ve tried myself to update for 0.4.0 and did not get your issue with vorbis.

**Comment by yurivict** [comment]
Just updating to 0.4.0 isn't enough though, you need to bundle with these:
```
GH_TUPLE+=      SuperTux:supertux:v0.4.0
GH_TUPLE+=      SuperTux:squirrel:2941f9a:squirrel
GH_TUPLE+=      SuperTux:tinygettext:6b4bc8d:tinygettext
GH_TUPLE+=      google:googletest:release-1.7.0:googletest
```
I think I picked versions from git submodules.

**Comment by devnexen** [comment]
Is HAVE_SDL make variable set to true works better for you ? Normally in your case it is set to false.

**Comment by yurivict** [comment]
Adding 
```
link_directories(/usr/local/lib)
```
to mk/cmake/FindOggVorbis.cmake solved problem with vorbis.
But I am still sure this is a bug in cmake scripts, because standard library path is set in cmake package, FindOggVorbis.cmake doesn't read it from the right variable somewhere.

Now there is still this double iconv(iconv_t ... problem.

**Comment by yurivict** [comment]
In the current problems seem to be fixed. So I submitted the FreeBSD port update:
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=205686
