### ISSUE TITLE
Some issues with frozen enemies

### ISSUE THREAD

**Issue by weluvgoatz** [SuperTux/supertux#2832]
Playing based on the latest nightly, these issues came up some time after I had implemented the frozen enemy rework.

- [ ] Frozen fish don't fall into the void properly and just kinda glitch out at the bottom of the sector.
- [ ] When an enemy is frozen and thrown onto spikes on top of slick tiles, the enemy doesn't die and just glitches out forever.
- [ ] The sprite hitboxes for the frozen enemies are all messed up now.

**Comment by Vankata453** [comment]
> Frozen fish don't fall into the void properly and just kinda glitch out at the bottom of the sector.ow.

Perhaps because of #2801?
