### ISSUE TITLE
0.4 crashes on startup on Mac OS X 10.7

### ISSUE THREAD

**Issue by JMLas** [SuperTux/supertux#284]
The new supertux release crashes on startup on my admitedly older 2006 intel iMac. I have not found any requirements for versions, so I do not know whether this is expected.

What can I do to help debug the problem?

**Comment by tobbi** [comment]
Do you have any crash log (anything in the system console messages) that you can get us?

**Comment by JMLas** [comment]
I'll do it as soon as I have a few moments at home. Shall I use some debug flag?

**Comment by tobbi** [comment]
I assume you can't compile with -DCMAKE_BUILD_TYPE=Debug, can you? 
You can start with --debug, that could show us at which stage it crashes. 

Do you know how to use a debugger, such as GDB?

**Comment by JMLas** [comment]
Le 22/12/2015 11:04, Tobias Markus a écrit :
> I assume you can't compile with -DCMAKE_BUILD_TYPE=Debug, can you?
> You can start with --debug, that could show us at which stage it crashes.

I'd rather avoid to install all the dependencies to compile, if 
possible. But I can compile if it proves necessary.

> Do you know how to use a debugger, such as GDB?

Yes.

**Comment by tobbi** [comment]
So, it would be great if you could get a stacktrace (for the debug version is preferred) since that will show line numbers etc.

**Comment by tweissin** [comment]
+1 on failing to start.

However, if I launch from a Terminal, it starts up.
> /Applications/SuperTux.app/Contents/MacOS/SuperTux

**Comment by JMLas** [comment]
I see nothing in console.app when running the app normally.

When running from command line, I get

     Gino: ./Desktop/SuperTux.app/Contents/MacOS/SuperTux
     Segmentation fault: 11

With gdb, I launch directly supertux2:

     Gino: gdb 
/Users/jmarc/Desktop/SuperTux.app/Contents/Resources/games/supertux2
     file: compiled magic version [522] does not match with shared 
library magic version [524]
     file: compiled magic version [522] does not match with shared 
library magic version [524]
     GNU gdb 6.3.50-20050815 [blah blah]
     (gdb) run
     Starting program: 
/Users/jmarc/Desktop/SuperTux.app/Contents/Resources/games/supertux2
     warning: The target crashed on startup, maybe the shell is crashing.
     "Try set start-with-shell 0" to workaround.
     Abort trap: 6


Using "set start-with-shell 0" does not help and setting 
`DYLD_FALLBACK_LIBRARY_PATH` like the wrapper does not either.

The warning about magic version may point to bad system shared library.

**Comment by JMLas** [comment]
If the problem is with incompatible dylibs, I do not know how to determine which one is bad.

I suspect that the problem would be solved by rebuilding the program, but I have no time for that right now.

**Comment by JMLas** [comment]
Here is the crash log obtained by the apple crash reporting utility. I am not sure it is useful...
[crash.txt](https://github.com/SuperTux/supertux/files/71698/crash.txt)

I could try to rebuild, but it looks like a big job. What is the right way of packaging for MacOS X?

**Comment by maxteufel** [comment]
The probably easiest way to build and install it is using [Homebrew](http://brew.sh): `brew install homebrew/games/supertux`

The crash log probably isn't helpful since it doesn't contain a backtrace, but it could be a CPU problem. Might it be possible that you're running this in a 32-bit environment but the executable was built for 64-bit computers?

**Comment by tobbi** [comment]
iirc, a universal binary was built.

**Comment by JMLas** [comment]
I did not know that it was already available in homebrew. I will have a look.

I also noticed using otool that it wants to load the system c++ libraries libstdc++.6.dylib and libc++.1.dylib. Since OX X 10.7 still uses gcc as compiler and the binaries have probaly been built with clang, this is a good recipe for a crash IMO.
[otool.txt](https://github.com/SuperTux/supertux/files/71728/otool.txt)

**Comment by maxteufel** [comment]
Might be but that still doesn't explain why it works fine from the command line.

**Comment by JMLas** [comment]
It does not work from the command line in my case. There might be two different issues.

**Comment by JMLas** [comment]
I am not very good at mac application versioning, but one can specify what SDK version is used, right? Do you know what the settings were in this case?

**Comment by maxteufel** [comment]
Please reopen if you can reproduce it.

**Comment by JMLas** [comment]
Well, 0.5 still crashes for me on Mac OS X 10.7.5. Same symptoms AFAICS. 

What can I do to help?

**Comment by tobbi** [comment]
Hey, can you try version 0.5.1 just to be sure that this isn't fixed in the meantime? Also, does the version from Homebrew work by any chance?

**Comment by JMLas** [comment]
I just tried it, and it still crashes.

This is a macport machine, but I could indeed get rid of that and install homebrew instead for the sake of it.

**Comment by tobbi** [comment]
I will try to setup a VM with OS X 10.7.5 and try it there.

**Comment by tobbi** [comment]
Also, @maxteufel suggested that linking with the newer C++ stdlib, like we do, could indeed be the culprit here.

**Comment by tobbi** [comment]
I couldn't find a suitable OS X 10.7 iso for installation on Virtualbox and I don't feel like trying out setting up a new machine. Can you please try the latest alpha from https://github.com/SuperTux/supertux/releases/tag/v0.6.0-alpha.3

**Comment by JMLas** [comment]
I am sorry, this particular machine was put to rest now, I do not have a way to test anymore.

**Comment by tobbi** [comment]
No problem. Unless otherwise stated, I'm gonna assume it's fixed. Closing.
