### ISSUE TITLE
SuperTux 0.4 doesn't run on some Windows 10 machines

### ISSUE THREAD

**Issue by laol** [SuperTux/supertux#285]
When I click supertux2.exe, nothing happens. Running as administrator doesn't help. Using Start menu too. Windows 10, Intel HD Graphics Family. Pegatron's DNS-branded desktop.

**Comment by tobbi** [comment]
Do you have an stdout.log file in the directory supertux2.exe resides?

**Comment by maths22** [comment]
stdout.log does not exist with the current version of SuperTux.

**Comment by laol** [comment]
@tobbi, no

**Comment by maths22** [comment]
@laol Once issue #290 is fixed, I will post a link to a binary that logs stdout/stderr.  In the meantime, can you check if Event Viewer shows any events for the supertux2.exe binary?

**Comment by watchmakerful** [comment]
I have the same issue. Win10 x64 build 10586, Intel graphics on Core i5-4670k. No logs and no events at all.

**Comment by watchmakerful** [comment]
It runs!!! But only in Win98 compatibility mode.

**Comment by laol** [comment]
@maths22, there is only infos about successfull installation, failed configuration, configuration changing and successful configuration. When I start superux2.exe, no new events appearing. @watchmakerful's method with Win98 compatibility mode isn't working on my computer.

**Comment by maxteufel** [comment]
Can't reproduce this, Windows 10 Home x86_64 build 10586, default settings on an AMD FX-7500 (+ built-in Radeon R7 GPU). As @maths22 mentioned, could you please wait on us getting #290 fixed so we can debug this issue?

**Comment by watchmakerful** [comment]
Yes, of course. This bug seems to be Intel HD specific.

2015-12-26 11:09 GMT+02:00 Max Teufel <notifications@github.com>:

**Comment by maxteufel** [comment]
@laol @watchmakerful a fix for #290 landed two weeks ago, could you try the nightly builds: <http://download.supertuxproject.org/download/> and get us information about the output?

@maths22 could you tell these people where the logs are stored?

**Comment by maths22** [comment]
IIRC, the logs can be found at %appdata%/SuperTux/supertux2/console.err

(I'll correct this once I have SuperTux running on my fresh Windows install
if I am wrong)

**Comment by maxteufel** [comment]
Please reopen this issue if it's not been fixed yet in the [latest nightly builds](http://download.supertuxproject.org/download/).
