### ISSUE TITLE
New behaviors and changes of totem for Tropical Paradise

### ISSUE THREAD

**Issue by VincentAraneo** [SuperTux/supertux#2861]
These changes can be used for the boss totem master, depending on the development of the game

(1) The totem would be invulnerable with fireballs or just kill it in the generic way with all enemies in the game. The way to kill them is to make a buttjump on top of them, since they are made of stone, they would be very hard. but with exaggerated force, it can be destroyed.

(2) More Variations

(3) The totems will be able to camouflage themselves. What do I mean by this? is that if there is a level that has totem decoration, one of them wakes up and starts walking. Basically, a mechanic of camouflaging oneself to the environment.

(4) Have a jump animation to climb on top of the other totem. since the old one didn't have that animation and there was only that of walking

(5) See an option in the editor that totems can break bricks

I decided on these ideas because I saw that the totem is very outdated. So I decided to give these ideas so that the 0.8.0 has a new behavior and original changes.

**Comment by MatusGuy** [comment]
We are not supporting the totem in the 0.7.0 release. It will be picked up again in a later release.
