### ISSUE TITLE
Give a better name to nfo files

### ISSUE THREAD

**Issue by MatusGuy** [SuperTux/supertux#2863]
Right now, an nfo file in an addon requires the name of the zip to be in the name of the nfo file.

This can get in the way of automation scripts and things like that. So what if we provide an alternative name called `addoninfo` and use that instead?

**Comment by tobbi** [comment]
Do we *actually* do that still? 

https://github.com/SuperTux/supertux/blob/master/src/addon/addon_manager.cpp#L759-L782

**Comment by MatusGuy** [comment]
hoo wait what so it just looks for the first nfo file it finds?
