### ISSUE TITLE
translation

### ISSUE THREAD

**Issue by tux-girl** [SuperTux/supertux#2867]
Hi

I want to help translating supertux to Dutch language!
Can somebody explain me how this can be done and if this language still needs work?
I'm not a programmer.

**Comment by tobbi** [comment]
Thanks for your interest in translating SuperTux. Please register a Transifex account here first: https://www.transifex.com/

**Comment by tobbi** [comment]
Dutch is still not 100% translated in Dutch, so yeah, you can certainly help out!

**Comment by tux-girl** [comment]
Hi

Transifex says it's only for 15 day trial account. I don't want to pay!

**Comment by MatusGuy** [comment]
I think you can sign in using your github account.

**Comment by tux-girl** [comment]
I can't login :(
If I click github, it asks again the 15 day trial

![afbeelding](https://github.com/SuperTux/supertux/assets/165455617/872f5900-c78e-469b-87f3-10e73357bd31)

**Comment by tobbi** [comment]
I've accepted you. Welcome to the translator team!

**Comment by thetuxgirl** [comment]
Sorry I have autism and was a bit uncertain how to translate things and I deleted everything.
I want to try again: my username is now thetuxgirl

Can you add me again?

How can I see where a word to translate is inside the game?

**Comment by tobbi** [comment]
What did you delete?

**Comment by thetuxgirl** [comment]
> What did you delete?

My github account only. Nothing in the translations!!! :)
I want to give it a 2nd try.

How can I see where a word to translate is inside the game?

**Comment by tobbi** [comment]
I think you can download files manually and then replace them.

**Comment by thetuxgirl** [comment]
> I think you can download files manually and then replace them.

Do you now mean you don't accept me again on transifex? I'm not sure why you tell this

**Comment by tobbi** [comment]
I meant in order to test it you can download the translation files and replace the original ones of SuperTux with it.

**Comment by thetuxgirl** [comment]
> I meant in order to test it you can download the translation files and replace the original ones of SuperTux with it.

Ah sorry! I'm a total beginner.
Can you please tell me:
-where are the files on transifex so I can download them?
- where to copy them in supertux? I have windows and android versions. If you can tell me both folders
