### ISSUE TITLE
Bad performance in Windows10

### ISSUE THREAD

**Issue by Grumbel** [SuperTux/supertux#287]
Even so the game runs at around 66fps according to the FPS counter it feels pretty sluggish. I assume the issue is that the game isn't vsync'ing or something along the lines.

**Comment by OronDF343** [comment]
I can confirm that VSync is needed. There is visible tearing which makes some levels like "Oh no! More snowballs" painful to play

**Comment by tobbi** [comment]
@Grumbel I assume this can be closed, right?
