### ISSUE TITLE
translation: some strings not used?

### ISSUE THREAD

**Issue by ghost** [SuperTux/supertux#2870]
Hi

When translating to Dutch, I found translated strings but they are not used in supertux. Still English is used

For example "Save level as" in the level editor. Many more strings but I can't make a screenshot of it using printscreen button (I don't know why)

![afbeelding](https://github.com/SuperTux/supertux/assets/165606399/f6170bdd-1ec2-4f9d-ba70-27bf6a9ac773)

![afbeelding](https://github.com/SuperTux/supertux/assets/165606399/71d5224a-c980-494d-a2af-5324c6380f80)

**Comment by tobbi** [comment]
What version of SuperTux are you using?

**Comment by tobbi** [comment]
Can you find the strings in the nl.po file somewhere?

**Comment by tobbi** [comment]
It can be on transifex but not yet translated. You'd have to replace the file. Can you download the translation file from transifex yourself?

**Comment by tobbi** [comment]
The translation does not get updated every time something changed, so in order to test it it needs to be updated manually.

**Comment by tobbi** [comment]
No, because we don't update the source files on transifex every time something changed but only a few weeks before the release. 

Maybe it works make sense to do this automatically. And from what I know there's also an issue about this.
