### ISSUE TITLE
question: saved progress

### ISSUE THREAD

**Issue by thetuxgirl** [SuperTux/supertux#2871]
Hi

I want to know where saved progress of any level (or the story mode) is saved. In which folder (on windows)? (to make a backup)

**Comment by mrkubax10** [comment]
`%appdata%\SuperTux\profileX` (replace `X` with actual used profile number).

**Comment by tobbi** [comment]
Can you maybe use https://github.com/SuperTux/supertux/discussions for those kinda questions?

**Comment by Vankata453** [comment]
Moved to #2874.
