### ISSUE TITLE
idea: supertux OST

### ISSUE THREAD

**Issue by ghost** [SuperTux/supertux#2872]
Hi

I had an idea for supertux.
What about releasing on the website an official soundtrack of supertux? So it are just the OGG files found in the music folder.
People can download the soundtrack to play with their favorite music player.
It could also contain the files in lossless format, for example FLAC. Who has the original uncompressed files?

I hope you like my idea :)

**Comment by GNUAn** [comment]
Good idea

**Comment by thetuxgirl** [comment]
SUCK MY FUCKING DICK
