### ISSUE TITLE
Allow addons to be manually installed easily again

### ISSUE THREAD

**Issue by brmbrmcar** [SuperTux/supertux#288]
In =<0.3.4, addons could just be added into /.supertux2. But now they have to be added to a configuration files,with useless, confusing requests like the md5, and where it came from. This should be unnecessary, as it makes manual installation almost impossible.

**Comment by Grumbel** [comment]
AddOns are still manually installable. Dropping a .zip into `~/.supertux2/addons/` is enough, it will show up in the AddOn menu. There is no need to touch `repository.nfo`, that's only for the online syncing.

The enable-state of addons is tracked in `~/.supertux2/config`:

    (addon
      (id "rubberduck-levels")
      (enabled #t)
    )

By default AddOns are disabled when dropped into `.../addons/`, enabling them by default might be a good idea.

**Comment by brmbrmcar** [comment]
It still won't work on Ubuntu.

**Comment by Grumbel** [comment]
Does the addon contain a proper .nfo file?

**Comment by Grumbel** [comment]
Or are there naming conflicts with already installed addons?

**Comment by brmbrmcar** [comment]
No, it has a .nfo file.

**Comment by Grumbel** [comment]
When an .nfo file is missing or the .nfo can't get parsed the game will print a warning:

    [WARNING] /home/ingo/projects/supertux/trunk/supertux/src/addon/addon_manager.cpp:556 Couldn't find .nfo file for /home/ingo/.supertux2/addons/testaddon.zip

So that all seems to be working as expected.

**Comment by brmbrmcar** [comment]
Try http://addons.supertux.googlecode.com/git/Levels/christoph.zip then.

**Comment by Grumbel** [comment]
[WARNING] /home/ingo/projects/supertux/trunk/supertux/src/addon/addon_manager.cpp:568 Could not load add-on info for addons/christoph.zip: Problem when reading addoninfo '/christoph.nfo': Problem when parsing addoninfo: (id ...) field missing from addon description

The .nfo file is out of date and needs an id field.

**Comment by Karkus476** [comment]
@Grumbel This suggests that the addon *is* being loaded by the game. @brmbrmcar Can we close this issue?

**Comment by Grumbel** [comment]
Not yet, manually installed addons are right now disabled by default, I'd like to have them enabled by default.

**Comment by brmbrmcar** [comment]
But I swear modern addons still don't work.

**Comment by brmbrmcar** [comment]
I don't see errors at all.

**Comment by Grumbel** [comment]
The error message shows up on stdout and on the the in-game console. The in-game console however only seems to show up when developer mode is enabled (Ctrl-F2).

**Comment by brmbrmcar** [comment]
My console says nothing about it.

**Comment by brmbrmcar** [comment]
It seems to work on 0.4.0. I'll close this unless someone else has the same problem.

**Comment by semajD** [comment]
Hey, tried the above suggestions, but I can figure out how to play the contrib levels. For example, I wanted to add this https://github.com/SuperTux/addons/blob/master/Worldmaps-0_4_0/mattie_world_0_4_0.zip. I'm on a Mac, so is this even possible to do?

**Comment by tobbi** [comment]
Can't you simply download Mattie's World from the Addons menu?

**Comment by semajD** [comment]
Oh, got it, I was trying to do it the old fashion way, silly me. Sorry about that!

**Comment by tobbi** [comment]
@semajD I know you designed several add-on levels. Just in case you're interested in designing some more: We are always looking for more add-ons. Furthermore, the next major release is gonna get an in-game level editor... :)

**Comment by maxteufel** [comment]
Music is certainly welcome too (<http://forum.freegamedev.net/viewtopic.php?f=67&t=6687#p67190>; and of course other suggestions).
