### ISSUE TITLE
android 0.6.3: scroll large menus impossible

### ISSUE THREAD

**Issue by ghost** [SuperTux/supertux#2882]
**SuperTux version:**

0.6.3

**System information:** *(details about your kernel, operating system, or distribution)*

Android 12

##### Expected behavior

I would expect a way to scroll down using a touch screen.

##### Actual behavior

If a menu is larger then the screen, scrolling it down is impossible with a touch screen. This occurs when the menu is large on its own (e.g. the language menu) or when you used scaling higher then 100% and the menu becomes bigger by the scaling.
In addition, we also can't reach the 'back' button of this menu.

##### Steps to reproduce actual behavior

Open a menu larger then the screen's height or scale up until it's larger then the screen's height.

**Comment by mrkubax10** [comment]
Shouldn't on-screen controls work in this case?

**Comment by thetuxgirl** [comment]
SUCK MY FUCKING DICK

**Comment by Rusty-Box** [comment]
@thetuxgirl I will give you time to explain for this, before consequence arise

**Comment by gnugirly** [comment]
> Shouldn't on-screen controls work in this case?

I was the author. Yes it works!
You can close it
