### ISSUE TITLE
Slopes acting weird in some situations

### ISSUE THREAD

**Issue by Eauix** [SuperTux/supertux#2885]
SuperTux version:
build "SuperTux-v0.6.3-1154-g3c243e77d" from 2024-04-01 21:37

System information:
Windows 10, 64 bit

##### Expected behavior
Tux walks and slides normally on slopes

##### Actual behavior
Tux only acts normally if he's small and the level is not flipped.
Behavior 1 - Big Tux gets stuck in an inclinated crawling/ducking animation
Behavior 2 - Big Tux starts to jitter on the slope as if starting to fall multiple times
Behavior 3 - Tux swims as if the slope was full of water

##### Steps to reproduce actual behavior
Behavior 1 - Release the [Down] button while you are sliding on a slope
Behavior 2 - Walk off the slope after reproducing behavior 1 and then slowly walk over the slope again
Behavior 3 - Flip the level upside down
[Video with all behaviors being reproduced](https://www.youtube.com/watch?v=ZWePPJ35pGc)

**Comment by Brockengespenst** [comment]
At least for behavior 1 #2810 should provide a fix.
The other things look indeed very weird.

**Comment by Eauix** [comment]
One more thing, I found out that the swimming thing doesn't only happen when the level is upside down, it happens whenever the player hitbox is inside a slope hitbox, which is especially noticeable with the unisolid slopes

**Comment by Brockengespenst** [comment]
Regarding the slopes: I might be wrong, but I think the changes to the collision system in https://github.com/SuperTux/supertux/commit/c2cc19b688c2c57a75266097b6b4db2a415235e6#diff-c1529ab5a98940b5cd63f179a8ce537a83df9f7e19349fc16f78afdb22ec8097 seem to have a negativ impact on Tux' behavior on the slopes.
If I understand the change correctly, the logic of the function has been changed. If ```is_free_of_tiles()``` is called with ```tiletype = Tile:WATER```, the first check for ```tile.get_attributes() & tiletype``` will fail for a slope. In the old implementation, it would continue with the next tile. In the current implementation, the next checks are done as well, especially ```if (tile.is_slope ())```, and that might lead to ```if (collision::rectangle_aatriangle(&constraints, rect, triangle))``` returning true, which causes the whole function to return false (= it is not free of tiles type water). This should not happen, as we already know from the first check, that this tile is not water.

**Comment by MatusGuy** [comment]
i have reopened #2886
