### ISSUE TITLE
translation

### ISSUE THREAD

**Issue by ghost** [SuperTux/supertux#2893]
HI

Can you add me on transifex?
I want to translate again. I translated only 50 words, I want to complete everything!

![afbeelding](https://github.com/SuperTux/supertux/assets/166179075/cf529f84-9a7b-4dca-a3b8-3a7489bb40a9)

**Comment by gnugirly** [comment]
YOU REJECT ME?
FINE

TRANSLATE IT YOURSELF

FUCKONG LOSERS
