### ISSUE TITLE
Windows doesn't record stdout output

### ISSUE THREAD

**Issue by Grumbel** [SuperTux/supertux#290]
In old SDL1 you used to get a stdout.txt file that would contain everything written to stdout. In the current Windows version that is no longer the case. Running from cmd.exe doesn't produce output either (that's expected, as GUI apps don't get stdout in Windows).

**Comment by maths22** [comment]
See 438d5377f717bf9d1351783b6a4156fa13c78242  (SDL_GetPrefPath was preferred over PHYSFS_getPrefDir because PHYSFS is not yet initialized, and should not yet be initialized)  Suggestions/improvements welcome.

**Comment by maths22** [comment]
Fixed in 6ac6b4a9de76aa9a3a2410b3a7c87fcc9dd80739
