### ISSUE TITLE
Language names should be displayed in their language instead of in English

### ISSUE THREAD

**Issue by tobbi** [SuperTux/supertux#291]
Instead of showing German, English, French, I think it would make more sense to show

Deutsch, English, Français (?) so that people recognize their language.

Also, finding the language selection menu can get tedious when you selected a different language accidentally.

**Comment by maxteufel** [comment]
Affects `external/tinygettext/src/language.cpp`, we should possibly add a `const char* name_localized` to the `LanguageSpec` struct (and of course put the localized name in `languages[]`); Then use that in the menu.

**Comment by tobbi** [comment]
I had to back this out because we're still missing the glyphs for many of the languages. So, let's wait until SDL_ttf support finally lands.
