### ISSUE TITLE
Some fonts are unused

### ISSUE THREAD

**Issue by MatusGuy** [SuperTux/supertux#2918]
I'm not sure if we use all the fonts in data/fonts/, or if some are used by other languages. But I'm filing this issue because if some are unused, they might bloat our game.

**Comment by tylerandari13** [comment]
I opened the chinese translation of the game and any untranslated words were shown in English with this weird font. I think almost all if not all are used by translations, but i cant say for sure, nor can i say why we dont just use the normal font for untranslated words.

**Comment by MatusGuy** [comment]
using the normal font for untranslated words would add useless complexity. We use a different font for some languages because our default doesn't support all characters. I'm wondering if all of these fonts are used. Because, ValeraRound for example, only supports latin extended, so I'm guessing it's not really used.

**Comment by MatusGuy** [comment]
turns out all of these fonts are used. But this is yet another reason to pack translations as an addon in the repository. Then, we can package the fonts there.

**Comment by Vankata453** [comment]
If all the fonts are used, can we close this? Putting translations in a different repository might be better as a different issue.

**Comment by MatusGuy** [comment]
sure
