### ISSUE TITLE
Flying snowballs turn invincible, invisible, and infnititley tall whenever the game is unpaused and paused 

### ISSUE THREAD

**Issue by Frostwithasideofsalt** [SuperTux/supertux#2922]
Things of note;
-when this happens, the hitbox of the enemy is invisible, regardless if show hitboxes are turned on or not
-this also happens when a debug menu is opened and closed

https://github.com/SuperTux/supertux/assets/60326522/4dec4969-af81-47b6-86b6-499bc6646ada

https://github.com/SuperTux/supertux/assets/60326522/915d5eb5-2eab-41af-81ce-80e1c195e0c3

**Comment by tobbi** [comment]
I was not able to reproduce the issue on my latest master build.

**Comment by Frostwithasideofsalt** [comment]
seems to not happen anymore...?
