### ISSUE TITLE
Set worldmap music through script not preserved after exiting level

### ISSUE THREAD

**Issue by Chiquinho7788** [SuperTux/supertux#2932]
**SuperTux-v0.6.3-1210:**

In Worldmap, when the tux goes through a route that changes the music, when entering a phase and exiting the music returns to the first one, not the music you put in the script!!

**Comment by tobbi** [comment]
I like trains.

**Comment by Chiquinho7788** [comment]
Do You realised the problem I posted?

**Comment by tobbi** [comment]
Yes, I created a fix for the issue?
