### ISSUE TITLE
Large crushers don't activate bonus blocks

### ISSUE THREAD

**Issue by Frostwithasideofsalt** [SuperTux/supertux#2935]
### SuperTux Version

supertux v0.6.3-1217-g620decc9

### System Information

Windows 10 64 bit

while the crusher *should* hit the block, instead it does this.

https://github.com/SuperTux/supertux/assets/60326522/5737d16d-8b8e-40f5-9d3a-47000debbaa8

https://github.com/SuperTux/supertux/assets/60326522/59072c50-f9c5-4ac3-ac58-90d6f1fc3466

**Comment by Rusty-Box** [comment]
Yeah, this bug is currently breaking a couple levels for v0.7 so... uh, coders please fix asap! 🙏

**Comment by MatusGuy** [comment]
does this happen with bricks?

**Comment by Rusty-Box** [comment]
They all break, heavy crates and normal crates that is. So these appear to work fine

**Comment by tobbi** [comment]
Fixed with f5aa7a2e0a985a381fbabfc119a15cd2d0db7ed0 apparently.
