### ISSUE TITLE
Generate release builds as `RelWithDebInfo`

### ISSUE THREAD

**Issue by tobbi** [SuperTux/supertux#2945]
In order for the stacktrace in the crash reporter to have line numbers, we need to generate builds with debug symbols. Unfortunately, builds generated as `Release` do not contain that info. I'd advise generating builds as `RelWithDebInfo` instead.

In order to do that, all the CI files need to get changed accordingly.

**Comment by tobbi** [comment]
I was wrong about RelWithDebInfo generating debug symbols (line numbers). So IDK how to proceed here?

**Comment by Vankata453** [comment]
> I was wrong about RelWithDebInfo generating debug symbols (line numbers). So IDK how to proceed here?

Just Windows then?

**Comment by tobbi** [comment]
IDK anymore.

**Comment by Vankata453** [comment]
Personally, on debug reports, I wouldn't necessarily care about the line numbers, as I would be able to see them by reproducing the crash on my own `-ggdb` debug build. Stacktraces in reports could serve as more of a general map of things, we could gather the details ourselves.

**Comment by MatusGuy** [comment]
> Just Windows then?
Perhaps we can keep it for all platforms. Shouldn't matter that much.

**Comment by Vankata453** [comment]
> Shouldn't matter that much.

But what if it does? I'm not aware of the consequences of `RelWithDebInfo`.

**Comment by MatusGuy** [comment]
The only thing that could possibly be worrying is bigger file size i think. As long as Windows has it, it doesn't matter
