### ISSUE TITLE
Add these enemies again.

### ISSUE THREAD

**Issue by chris1357924680** [SuperTux/supertux#2950]
In the future versions of SuperTux you can add the industrial enemies like the industrial crusher and the industrial stalactite.
![krosh](https://github.com/SuperTux/supertux/assets/170481307/28066ffa-50f1-40ba-8b33-f12e9d642c03)                              ![falling](https://github.com/SuperTux/supertux/assets/170481307/233aa111-d1d3-4b07-bb26-8dde57ab0987)

**Comment by NickerAban** [comment]
well I don't want to know anything, and with my life..
