### ISSUE TITLE
Change and add these enemies

### ISSUE THREAD

**Issue by chris1357924680** [SuperTux/supertux#2951]
It would be good to remake Angrystone, the Cherry Bombs, Flam Fish, Seasonal Snowball, Kugelblitz, Tumbleweed, Plant and bring back Mr Fluffy and the Dummyguy and add a behavior to them, you can either change all there behaviors to something much better. Please add them again.

Kugeldlitz can move left and right without diapering, the tumbleweed can roll left and right jumping on tux, the cherry bomb must be in water, the plant can we the tropical version of spiky,the dummyguy can walk jump and swim like tux. the flam fish can only be in lava and mr fluffy can fall in shallow holls but not deep holls.

**Comment by bruhmoent** [comment]
There's no need to add an iteration of the same issue.
