### ISSUE TITLE
[Bug]: Tux dies in "Find the bigger fish!" jumping into the secret after using a door

### ISSUE THREAD

**Issue by rubberduck9999** [SuperTux/supertux#2959]
### SuperTux Version

v0.6.3-1251-g1fa2a76c8

### System Information

Linux 64-bit

### Expected Behavior

Tux should never die by just jumping into the secret area in "Find the bigger fish!", even after using a door

### Actual Behavior

When I was hunting to get all secrets, coins and badguys in "Find the bigger fish!", I suddenly died jumping into the secret.
After a bit testing I found out it happens after I went into one of these doors at the bridge. Even after restarting the level, or if you get killed elsewhere and respawn, I suddenly died when jumping down. Only when I then aborted the level and started all over, I was able to get into the secret area.

### Steps To Reproduce Actual Behavior

1. Start the level from story mode and play until you reach the door to go through
2. Go back to the secret area and go down. Tux will die
3. try it again after your first death, it happens again, the same if you restart, no matter if tux is big or small, or if you were in before.
4. go back to the worldmap, re-enter the level, now restart the level or get killed before going into the door, tux won't die when going into the secret, only after you entered a door once

### Additional Information

I guess it is another bug related to the following
https://github.com/SuperTux/supertux/issues/2956
https://github.com/SuperTux/supertux/pull/2957

### Guidelines For Reporting Issues

- [X] I have read <https://github.com/SuperTux/supertux/blob/master/CONTRIBUTING.md#bug-reports>.
- [X] I have verified this isn't an issue that's already been reported.
- [X] I have verified this isn't a [discussion](https://github.com/SuperTux/supertux/discussions), or an issue about a crash or a feature request, but rather an actual bug ─ that is, the game did something not intended.
- [X] I have verified this issue is **not** about wrong translations (use Transifex for those), or anything unsupported (e.g. third-party add-ons).
- [X] In this report, I have only included details about **one** (1) bug.
- [X] If I make a mistake while submitting this report, I agree to use the "Edit" feature to correct it, instead of closing this issue and opening a new one.

**Comment by tobbi** [comment]
I tried reproducing the issue with latest nightly but was unable to do so. @Rusty-Box Can you try to confirm?

**Comment by Rusty-Box** [comment]
Can confirm, there's already someone working on a fix via #2957

**Comment by tobbi** [comment]
Sorry, I definitely can't read instructions properly.

**Comment by Brockengespenst** [comment]
I can confirm that #2957 fixes this issue. As the bug prevents the respawn from Level.spawn() script to be executed successfully after using the door, you fall out of the level in that case.
Sorry, that was introduced by my door rework.
