### ISSUE TITLE
[Feature Request]: Outback World

### ISSUE THREAD

**Issue by Tim79000** [SuperTux/supertux#2974]
### Feature Details

A world themed around the Australian Outback, I think this would be an interesting idea as the biome isn't represented in many games, plus since Australia is near Antarctica, it makes thematic sense.

### Feature Purpose

Bump the world count up to 5

It's cool

A desert world would be cool, but an outback is more unique!

### Guidelines For Reporting Issues

- [x] I have read <https://github.com/SuperTux/supertux/blob/master/CONTRIBUTING.md#bug-reports>.
- [X] I have verified this isn't a request that's already been submitted as an issue.
- [X] I have verified this isn't a [discussion](https://github.com/SuperTux/supertux/discussions), or an issue with the game, but rather an actual feature request - a currently non-existent, but desired feature.
- [X] In this request, I have only included details about **one** (1) desired feature.
- [X] If I make a mistake while submitting this request, I agree to use the "Edit" feature to correct it, instead of closing this issue and opening a new one.

**Comment by weluvgoatz** [comment]
I do genuinely like this idea! However, I think we're pretty set on having the currently planned 4 worlds. If you want, though, you can always make your own version, or some add-on/extra world of it can be attempted by anyone (similar to the Halloween world).

**Comment by Tim79000** [comment]
Started work on tiles, the add-on/extra idea will, work! Thanks for the suggestion.
