### ISSUE TITLE
Bug in "Bad Guys Stink"

### ISSUE THREAD

**Issue by alketii** [SuperTux/supertux#298]
Bug in "Bad Guys Stink"
![Image Alt](https://lut.im/2ZCzNxlGfU/Z67U3jKXCakSeJfY.png)

**Comment by maxteufel** [comment]
Did someone test d270ba3? If so, we can merge this into master.

**Comment by Hume2** [comment]
@maxteufel It must work, but there were already two foreground tilemaps and you made a third one.

**Comment by alketii** [comment]
As of latest git commit (2103bda7bb17acd7732a11ce495aa3ddaed050c6) its not fixed.

**Comment by alketii** [comment]
in fix/298 branch its fixed but with a minor bug, tux can be visible on the first tile.
