### ISSUE TITLE
Climbing ladder underwater weirdly offsets Tux

### ISSUE THREAD

**Issue by weluvgoatz** [SuperTux/supertux#2981]
If you, for whatever reason, press up on a ladder that is underwater, Tux will be pushed to the left or right for whatever reason.

**Comment by MatusGuy** [comment]
You should just not be able to climb underwater, right?

**Comment by weluvgoatz** [comment]
Correct

**Comment by Brockengespenst** [comment]
Climbing while swimming should already be blocked. A quick test in a self created level with the latest git state did not show any weird behavior, maybe a special setup is needed to reproduce this? Does this happen in an official level or could you provide a test level to reproduce the behavior?

**Comment by Brockengespenst** [comment]
Ah Ok, I see. There is some code in Climbable that affects Tux as well. I'll create a PR that should prevent this.
