### ISSUE TITLE
[Bug]: Changing z-pos doesn't work for some particles and objects

### ISSUE THREAD

**Issue by Eauix** [SuperTux/supertux#2989]
### SuperTux Version

v0.6.3-1277-g72553fe82

### System Information

Windows 10, 64-bit

### Expected Behavior

The objects appear in front of a tilemap with z-pos lower than the z-pos you set into the object.

### Actual Behavior

The objects appear only in front of a tilemap with z-pos lower than 0, -99 in case of the door, 60 in case of hay and ice, or 51 in case of bricks, info and bonus blocks

### Steps To Reproduce Actual Behavior

Place a door, a conveyor, a rain particle, a spotlight, a bonus block, an info block, a brick, a heavy brick, a meltable ice block, a hay block or a custom particle and try to change its z-pos to appear behind or in front of a tilemap, it won't do anything.

### Additional Information

![image](https://github.com/SuperTux/supertux/assets/145238217/54157151-3dec-4a63-aa3c-c51e60c5632a)

- Every object and particle shown in this image have their z-positions set to 999, they should appear in front of all 4 tilemaps, yet, they appear behind some of them.

- Doors seem to be stuck at z-pos -99 regardless of you changing it or not.
Rain particles, Custom particles and Conveyors seem to be stuck at z-pos 0 regardless of you changing it or not.

- Rain and particles only change their z-pos visually in editor, but not when playing the level.

- Custom particles don't change their z-pos.

- Update: Bonus Blocks, Info Blocks, Bricks and Heavy Bricks are also unable to change z-pos, they are stuck to z-pos 51 even tho it is set to 999

![image](https://github.com/user-attachments/assets/d4bb1e1d-ad29-402f-b1f6-ed5d7230f1bd)

- Update 2: Hay and Meltable ice blocks are stuck to z-pos 60, Spotlights are stuck to z-pos 0

---
- All objects except for these ones seem to work properly when changing their z-positions.

- Cloud and Snow particles work properly when changing their z-pos

### Guidelines For Reporting Issues

- [X] I have read <https://github.com/SuperTux/supertux/blob/master/CONTRIBUTING.md#bug-reports>.
- [X] I have verified this isn't an issue that's already been reported.
- [X] I have verified this isn't a [discussion](https://github.com/SuperTux/supertux/discussions), or an issue about a crash or a feature request, but rather an actual bug ─ that is, the game did something not intended.
- [X] I have verified this issue is **not** about wrong translations (use Transifex for those), or anything unsupported (e.g. third-party add-ons).
- [X] In this report, I have only included details about **one** (1) bug.
- [X] If I make a mistake while submitting this report, I agree to use the "Edit" feature to correct it, instead of closing this issue and opening a new one.

**Comment by tobbi** [comment]
I looked and those objects have their z-position / layer hardcoded to some value. Someone'd have to change that in order for the setting to work.

**Comment by Vankata453** [comment]
Should be fixed by commit c12c2bb8aa12fd01ce8c83da59ab0cf252ab59b0. Please test!
