### ISSUE TITLE
Add 64 bit installer for SuperTux 0.4

### ISSUE THREAD

**Issue by Savsish** [SuperTux/supertux#299]
The 32 bit version does not run on 64 bit versions of Windows Vista, 7, 8, 8.1 and 10.
Oddly enough the game does run with Windows 98/Me compatiblity mode.

**Comment by maxteufel** [comment]
It does for me (maybe you're affected by #285), however it still might be a good idea to provide 64-bit builds for Windows (even if we didn't do that until 0.3.5a).
