### ISSUE TITLE
[Bug]: Moving platforms/coins don't appear in level editor

### ISSUE THREAD

**Issue by epicguy2222** [SuperTux/supertux#3008]
### SuperTux Version

v0.6.3-1304-g00a307005

### System Information

Windows 10 64-bit

### Expected Behavior

The moving platforms/coins appear and move normally like the previous versions

### Actual Behavior

The moving platforms/coins disappears

### Steps To Reproduce Actual Behavior

Step 1: Make a platform moves in editor
Step 2: Test the level and the moving platform will disappear

### Additional Information

Error messages I think they might help:
<img width="271" alt="Screenshot 2024-07-07 212048" src="https://github.com/SuperTux/supertux/assets/168249975/e9476c4f-93e6-4646-a11f-c066ce748ec2">

<img width="960" alt="Screenshot 2024-07-07 212857" src="https://github.com/SuperTux/supertux/assets/168249975/38f21312-5040-46b0-9038-fad2e76284d9">

### Guidelines For Reporting Issues

- [X] I have read <https://github.com/SuperTux/supertux/blob/master/CONTRIBUTING.md#bug-reports>.
- [X] I have verified this isn't an issue that's already been reported.
- [X] I have verified this isn't a [discussion](https://github.com/SuperTux/supertux/discussions), or an issue about a crash or a feature request, but rather an actual bug ─ that is, the game did something not intended.
- [X] I have verified this issue is **not** about wrong translations (use Transifex for those), or anything unsupported (e.g. third-party add-ons).
- [X] In this report, I have only included details about **one** (1) bug.
- [X] If I make a mistake while submitting this report, I agree to use the "Edit" feature to correct it, instead of closing this issue and opening a new one.

**Comment by weluvgoatz** [comment]
This was due to PR #2991 and has since been reverted.
