### ISSUE TITLE
Bug in Secret area of Bonus Island III

### ISSUE THREAD

**Issue by marc280492** [SuperTux/supertux#301]
Yesterday I discovered the secret of the island bonus III, and every time I open the general world appears misconfigured.

![captura](https://cloud.githubusercontent.com/assets/11487343/12020125/df4b03c4-ad78-11e5-8005-947216bfb6a6.JPG)

But when I click on some key appears correctly.

![captu4ra](https://cloud.githubusercontent.com/assets/11487343/12020187/a8bc60cc-ad79-11e5-9295-8033acc7b4bc.JPG)

**Comment by brmbrmcar** [comment]
I have always had the same issue. I'll look into it.
