### ISSUE TITLE
Update SuperTux Wiki

### ISSUE THREAD

**Issue by MarcCeleiro** [SuperTux/supertux#302]
Please, update SuperTux Wiki :+1:

http://supertux.lethargik.org/wiki/Main_Page

**Comment by maxteufel** [comment]
Old wiki, we're using GitHub's now.

Still leaving this open for someone else to fix this.

**Comment by Karkus476** [comment]
Not to be forgotten: #208

**Comment by Grumbel** [comment]
As it turns out, git comes with a plugin to import mediawiki into a git repository:

    git clone mediawiki::http://supertux.lethargik.org/wiki/

lethargik is really slow, so this conversion is taking a while, but if that succeeds we could take the old Wiki offline and switch the Wiki over to Github completely.

**Comment by Grumbel** [comment]
The old Mediawiki has now been switched to ReadOnly mode.

The Mediawiki pages along with history have been important into the `mediawiki` branch of the [Github Wiki](https://github.com/SuperTux/supertux.wiki.git).

I also copied the `images/` subdirectory into the Wiki.

I think that should be all the old data, it's not usable in it's current form and needs some further cleanup and conversion before it can be merged into `master` wiki.

**Comment by Grumbel** [comment]
Currently only the main namespace of the mediawiki is imported, Talk and Template namespaces are missing, see:

https://github.com/moy/Git-Mediawiki/issues/10

**Comment by Rusty-Box** [comment]
I think this can be closed. Inactivity for 6 years and the current wiki seems pretty up-to-date
