### ISSUE TITLE
Sideways Crusher should not insta-kill players

### ISSUE THREAD

**Issue by Rusty-Box** [SuperTux/supertux#3024]
A normal Crusher when crushing the player will only hurt them. Sideways Crushers on the other hand kill the player instantaneously when they get crushed at a wall. This is rather unfair as well as inconsistent amongst Crushers thus should be changed

TL;DR - When a player gets hit/crushed by a sideways Crusher, instead of dying instantly, they should only get hurt (i.e. loose a powerup and only die when hit as small Tux)

**Comment by tobbi** [comment]
You could argue that any other thing crushing tux horizontally shouldn't kill tux, like moving tilemaps, no?

**Comment by Rusty-Box** [comment]
Not really. Crushers are enemies of which none should really have a one hit insta kill move. Second of all, a tilemap doesn't behave neccesarily like a crusher. A crusher goes back to it orignal state. A tilemap depending on how the path is set up will literally crush you as it will not leave room or go back to where it was. In that case you would either get pushed into the ground/wall or get pushed into the tilemap in question.

So if you ask me, those two cannot be compared here really
