### ISSUE TITLE
SuperTux Path-related Level Editor Crash

### ISSUE THREAD

**Issue by EggsAndBakey** [SuperTux/supertux#3028]
### SuperTux Version

v0.6.3-1318-gd63d4798e

### System Information

Windows x64

### Steps To Reproduce Crash

There are 2 versions of these steps
1. Go To the Level Editor
2. Make a new level
3. Put a path-controlled object in the level (I used the metal flying platform thing, however I also changed it's sprite to the flag in the decals (flag.sprite) after step 7 but before step 8)
4. Edit the path, for this specific crash, it was 2 points or something?? the object starts in the middle, goes up and goes down.
5. Put a few tiles
6. Make a tilemap be controlled by the same path of the flying object
7. Probably edit the path more
8. Undo using CTRL-Z
9. The game crashes.

The 2nd version of these steps, more simple but slightly different. Leads to the same crash, I think, so this doesn't count as a 2nd crash in one crash report.
1. Go to the level editor
2. Make a new level
3. Put a path-controlled object in the level (I still used the metal flying platform thing)
4. Edit the path
5. Put a few tiles
6. Undo using CTRL-Z
7. The game crashes. 

### Debugging Information (Stacktrace)

```shell
- 0x0
 - 0x0
seh_filter_exe - 0x7ffdcaf50cc0
seh_filter_exe - 0x7ffdcaf50cc0
_C_specific_handler - 0x7ffdbd56e530
_chkstk - 0x7ffdcd8d2810
RtlRaiseException - 0x7ffdcd8820d0
KiUserExceptionDispatcher - 0x7ffdcd8d1410
KiUserExceptionDispatcher - 0x7ffdcd8d1410
KiUserExceptionDispatcher - 0x7ffdcd8d1410
KiUserExceptionDispatcher - 0x7ffdcd8d1410
KiUserExceptionDispatcher - 0x7ffdcd8d1410
KiUserExceptionDispatcher - 0x7ffdcd8d1410
KiUserExceptionDispatcher - 0x7ffdcd8d1410
KiUserExceptionDispatcher - 0x7ffdcd8d1410
KiUserExceptionDispatcher - 0x7ffdcd8d1410
KiUserExceptionDispatcher - 0x7ffdcd8d1410
KiUserExceptionDispatcher - 0x7ffdcd8d1410
KiUserExceptionDispatcher - 0x7ffdcd8d1410
KiUserExceptionDispatcher - 0x7ffdcd8d1410
KiUserExceptionDispatcher - 0x7ffdcd8d1410
BaseThreadInitThunk - 0x7ffdcba47360
RtlUserThreadStart - 0x7ffdcd87cc70
```

### Additional Information

I know this is somewhat similar to one of the other issues that is also a crash caused by the undo feature in the SuperTux level editor, however, this one has a consistent way to reproduce it.
Sorry if this crash report is messy.

### Guidelines For Reporting Issues

- [X] I have read <https://github.com/SuperTux/supertux/blob/master/CONTRIBUTING.md#bug-reports>.
- [X] I have verified this isn't an issue that's already been reported.
- [X] I have verified this isn't a [discussion](https://github.com/SuperTux/supertux/discussions), or an issue about unintended behavior or a feature request, but rather an actual crash ─ that is, the game closed unexpectedly.
- [X] I have verified this issue is **not** about wrong translations (use Transifex for those), or anything unsupported (e.g. third-party add-ons).
- [X] In this report, I have only included details about **one** (1) crash.
- [X] If I make a mistake while submitting this report, I agree to use the "Edit" feature to correct it, instead of closing this issue and opening a new one.

**Comment by bruhmoent** [comment]
Reproduced the second version

**Comment by tobbi** [comment]
Can I get a real stacktrace?

**Comment by bruhmoent** [comment]
Is this what you need?

```
[Inline Frame] supertux2.exe!std::_Hash<std::_Uset_traits<CollisionObject *,std::_Uhash_compare<CollisionObject *,std::hash<CollisionObject *>,std::equal_to<CollisionObject *>>,std::allocator<CollisionObject *>,0>>::_Find_last(const CollisionObject * &) Line 1566 C++
[Inline Frame] supertux2.exe!std::_Hash<std::_Uset_traits<CollisionObject *,std::_Uhash_compare<CollisionObject *,std::hash<CollisionObject *>,std::equal_to<CollisionObject *>>,std::allocator<CollisionObject *>,0>>::_Erase(const CollisionObject * &) Line 1109 C++
[Inline Frame] supertux2.exe!std::_Hash<std::_Uset_traits<CollisionObject *,std::_Uhash_compare<CollisionObject *,std::hash<CollisionObject *>,std::equal_to<CollisionObject *>>,std::allocator<CollisionObject *>,0>>::erase(const CollisionObject * &) Line 1136 C++
supertux2.exe!TileMap::notify_object_removal(CollisionObject * other) Line 618 C++
supertux2.exe!CollisionSystem::remove(CollisionObject * object) Line 66 C++
supertux2.exe!Sector::before_object_remove(GameObject & object) Line 437 C++
[Inline Frame] supertux2.exe!GameObjectManager::flush_game_objects::__l3::<lambda_dc38d5a9b4dfca11d1d8a135be56a3ea>::operator()(const std::unique_ptr<GameObject, std::default_delete<GameObject>> &) Line 249 C++
[Inline Frame] supertux2.exe!std::remove_if(std::_Vector_iterator<std::_Vector_val<std::_Simple_types<std::unique_ptr<GameObject, std::default_delete<GameObject>>>>>) Line 2242 C++
supertux2.exe!GameObjectManager::flush_game_objects() Line 243 C++
supertux2.exe!Editor::update(float dt_sec, const Controller & controller) Line 293 C++
supertux2.exe!ScreenManager::update_gamelogic(float dt_sec) Line 315 C++
supertux2.exe!ScreenManager::loop_iter() Line 628 C++
supertux2.exe!ScreenManager::run() Line 672 C++
supertux2.exe!Main::launch_game(const CommandLineArguments & args) Line 656 C++
supertux2.exe!Main::run(int argc, char * * argv) Line 741 C++
supertux2.exe!SDL_main(int argc, char * * argv) Line 35 C++
supertux2.exe!main_getcmdline() Line 80 C
```

**Comment by tobbi** [comment]
Thanks. I hope I can find the time to look into it.

**Comment by EggsAndBakey** [comment]
I tried reproducing this crash (the 2nd version of the steps that lead to this crash, at least) in the latest nightly as of this comment (SuperTux v0.6.3-1324-gd70028891) and I think it might have been fixed so i think it's good to close this issue now

**Comment by tobbi** [comment]
Nothing on master indicates that this was fixed. @bruhmoent Can you check latest master, please?
