### ISSUE TITLE
Problems with non-ASCII characters

### ISSUE THREAD

**Issue by Wuzzy2** [SuperTux/supertux#305]
SuperTux 0.4.0 seems to have problems with some non-ASCII characters. It just does not show them correctly.

For example, the German translation of the level name “'... or is it just me?'” uses the German quotation marks („ and “) but in the game those characters look like “T”s.
Note that this is just an example, there are other characters where this is happening as well (e.g. ellipsis  (“…”), n-dash (“–”), m-dash (“—”), etc.)

Maybe is there some problem with the font or somethiing? I have no idea.

**Comment by Karkus476** [comment]
Relevant: #130

**Comment by Hume2** [comment]
Check out whether they use UTF-8 correctly.

**Comment by Hume2** [comment]
It's because those chars aren't in SuperTux fonts.

**Comment by giby** [comment]
… is, 
– and — Never noticed... 
„ and “ I'll cheack :p

**Comment by maxteufel** [comment]
This will be fixed by #386, which is schedule for post-0.5.0 release.

**Comment by tobbi** [comment]
As SuperTux now uses vector fonts, this should be fixed.
