### ISSUE TITLE
[Feature Request]: flashcards to advance in the game and learning mode

### ISSUE THREAD

**Issue by westurner** [SuperTux/supertux#3054]
### Feature Details

Users can load a deck of questions to be presented at various points in the game. If ~'learning mode' is on, display an on screen indicator indicating that must_answer_to_advance=True for the given workstation.

- Output: Card contents
- Input: Answer
- Input: {0,1,2,3} if config.spaced_repetition
- Output: Correct / Incorrect
- Parameter: config.spaced_repetition : bool
- Parameter: config.must_answer_to_advance : bool
- Parameter: config.learning_mode : bool 
  - config.must_answer_to_advance=True
  - show the on-screen learning mode indicator

Tasks:

- [ ] ENH: config schema and GUI: config.spaced_repetition, config.must_answer_to_advance, config.learning_mode
- [ ] ENH: Scheduler of cards with optional spaced repetition recall self-scoring
- [ ] ENH: quizq: read existing flashcard decks natively or an existing library
- [ ] ENH: quizq: TuxMath -style math questions if there's no deck loaded
- [ ] ENH: on-screen idk "learning mode" indicator 

### Feature Purpose

Learning, Education

### Guidelines For Reporting Issues

- [X] I have read <https://github.com/SuperTux/supertux/blob/master/CONTRIBUTING.md#bug-reports>.
- [X] I have verified this isn't a request that's already been submitted as an issue.
- [X] I have verified this isn't a [discussion](https://github.com/SuperTux/supertux/discussions), or an issue with the game, but rather an actual feature request - a currently non-existent, but desired feature.
- [X] In this request, I have only included details about **one** (1) desired feature.
- [X] If I make a mistake while submitting this request, I agree to use the "Edit" feature to correct it, instead of closing this issue and opening a new one.

**Comment by westurner** [comment]
- SuperMemo SM-2 (Open Source; Attribution)
  - https://en.wikipedia.org/wiki/SuperMemo#Description_of_SM-2_algorithm
  - https://en.wikipedia.org/wiki/SuperMemo#Non-SuperMemo_implementations
- Mnemosyne (AGPL, BSD)
  - https://github.com/mnemosyne-proj/mnemosyne/blob/master/mnemosyne/libmnemosyne/scheduler.py
  - https://github.com/mnemosyne-proj/mnemosyne/tree/master/mnemosyne/libmnemosyne/card_types
- Anki (AGPL, GPL, BSD)
  - https://github.com/ankitects/anki/blob/main/pylib/anki/scheduler/v3.py
   - CardStates: AGAIN, HARD, GOOD, EASY
  - https://github.com/topics/anki
  - https://github.com/tianshanghong/awesome-anki
  - https://github.com/ashlinchak/mdanki converts Markdown to Anki cards

**Comment by Vankata453** [comment]
SuperTux is not a "learning game" by design, so I believe this is not suitable for the main game.

However, I believe that using scripting, the user could be prompted with questions. That would allow for creating an add-on to focus around this gimmick. Additionally, modding the game to fit the desired use case is always an option too.

**Comment by komaros1** [comment]
wtf

**Comment by westurner** [comment]
; to gamify flashcards because TuxMath && SuperTux

**Comment by westurner** [comment]
:+1:
