### ISSUE TITLE
Springs may push falling coins into the ground

### ISSUE THREAD

**Issue by Wuzzy2** [SuperTux/supertux#306]
I can remember a bug in SuperTux 0.4.0 but I don't know for sure if it can be reproduced 100%. I also forgot the level I was playing, but it was a custom one.

The basic idea is this:
Get a transportable spring and falling coins (e.g. from an orange bomb). Now just drop the spring on any fallable coin on the floor and the coin will be pushed into the ground and permanently makes collision sounds until it leaves the level entirely. I am not 100% sure about this bug, maybe it only works if you drop a spring on an orange bomb (and killing it).

Maybe it helps if you create a quick and dirty test level to try to reproduce this. Please reply to tell me whether you were able to successully reproduce this.

**Comment by Karkus476** [comment]
[issue306.stl.txt](https://github.com/SuperTux/supertux/files/73953/issue306.stl.txt)
This is very easy to reproduce
