### ISSUE TITLE
Why you don't rellased supertux 0.7.0??

### ISSUE THREAD

**Issue by hello-loti** [SuperTux/supertux#3064]
you said that supertux 0.7.0 will be relesed august 2024 but now September 2024 WHY????

**Comment by idkwhoisthisimlost** [comment]
They delayed it to December I think.

**Comment by MatusGuy** [comment]
We delayed it to christmas but we still need help with coding so if whoever's reading this wants to contribute then join the discord and tell us

**Comment by hello-loti** [comment]
> We delayed it to christmas but we still need help with coding so if whoever's reading this wants to contribute then join the discord and tell us

really? Oh all autumn? Eh...
