### ISSUE TITLE
[Bug]: if you take damage and shrink to small tux while crawling as big tux, you stay crawling

### ISSUE THREAD

**Issue by SusDTSteve** [SuperTux/supertux#3069]
### SuperTux Version

v0.6.3-1368-gs2baa1216

### System Information

windows 11 64 bit

### Expected Behavior

stop crawling when you shrink to small tux while crawling as big tux

### Actual Behavior

stay as crawling big tux even while being small

### Steps To Reproduce Actual Behavior

1. be big tux (no powerup)
2. be crawling
3. take damage, but still be crawling
4. you are crawling as big tux but you arent big

### Additional Information

this game is LITTERALY unplayable with this bug

### Guidelines For Reporting Issues

- [X] I have read <https://github.com/SuperTux/supertux/blob/master/CONTRIBUTING.md#bug-reports>.
- [X] I have verified this isn't an issue that's already been reported.
- [X] I have verified this isn't a [discussion](https://github.com/SuperTux/supertux/discussions), or an issue about a crash or a feature request, but rather an actual bug ─ that is, the game did something not intended.
- [X] I have verified this issue is **not** about wrong translations (use Transifex for those), or anything unsupported (e.g. third-party add-ons).
- [X] In this report, I have only included details about **one** (1) bug.
- [X] If I make a mistake while submitting this report, I agree to use the "Edit" feature to correct it, instead of closing this issue and opening a new one.

**Comment by MatusGuy** [comment]
> this game is LITTERALY unplayable with this bug
Is it reall

**Comment by MatusGuy** [comment]
> this game is LITTERALY unplayable with this bug

Is it really? Can't you just uncrawl?

**Comment by SusDTSteve** [comment]
i was FREAKING kidding

**Comment by swagtoy** [comment]
- remove txu

**Comment by MatusGuy** [comment]
- remove txu

**Comment by komaros1** [comment]
remove txu
