### ISSUE TITLE
Translation updates

### ISSUE THREAD

**Issue by mol-1** [SuperTux/supertux#308]
Hello everybody,
French translations had been improved recently on transifex, correcting some huge mistakes, could anybody update this file : https://raw.githubusercontent.com/SuperTux/addons/master/langpacks/langpack-fr.zip ?

Thanks in advance !

**Comment by mol-1** [comment]
Tiny more issue : 
This chain in bonus island 2 seems a bit outdated ...

"-Congratulations!↩⏎
↩⏎
#You successfully made it through↩⏎
#Bonus Island II↩⏎
↩⏎
↩⏎
⇥featuring levels contributed by↩⏎
⇥Kevin↩⏎
⇥Jason Kleinemas↩⏎
⇥Denilson↩⏎
⇥Tobe Deprez↩⏎
⇥Big C↩⏎
⇥Thomas Nilsen↩⏎
⇥Torfi Gunnarsson↩⏎
⇥Daniel Alston↩⏎
⇥Nilrok↩⏎
⇥Corlin Heydman↩⏎
↩⏎
↩⏎
#Once again, we'd like to thank↩⏎
#everyone who contributed to this↩⏎
#release. We hope that you enjoyed↩⏎
#it, and that it made waiting for↩⏎
#Milestone 2 a little easier. :-)↩⏎
↩⏎
↩⏎
The end of the ice age is near..."

**Comment by maxteufel** [comment]
@mol-1 Merci d'aider avec la traduction du SuperTux. Est-ce que tu pourrais ouvrir un nouveau *issue* pour le problème avec le texte qui parle d'attendre *Milestone 2*?

**Comment by mol-1** [comment]
When I open supertux, and try to update the french localisation reinstalling it, I got following errors and "french" get wiped out from the list of languages : 


leo@leo-aspire5720Z:~/supertux-0.4.0$ build/supertux2 
[WARNING] /home/leo/supertux-0.4.0/src/addon/addon_manager.cpp:567 Could not load add-on info for addons/langpack-fr.zip: Problem when reading addoninfo '/langpack-fr.nfo': file is not a supertux-addoninfo file.
[WARNING] /home/leo/supertux-0.4.0/src/supertux/menu/addon_menu.cpp:378 Enabling add-on failed: Couldn't find installed Addon with id: langpack-fr
leo@leo-aspire5720Z:~/supertux-0.4.0$ build/supertux2 
[WARNING] /home/leo/supertux-0.4.0/src/addon/addon_manager.cpp:567 Could not load add-on info for addons/langpack-fr.zip: Problem when reading addoninfo '/langpack-fr.nfo': file is not a supertux-addoninfo file.
[WARNING] /home/leo/supertux-0.4.0/src/addon/addon_manager.cpp:567 Could not load add-on info for addons/langpack-fr.zip: Problem when reading addoninfo '/langpack-fr.nfo': file is not a supertux-addoninfo file.
[WARNING] /home/leo/supertux-0.4.0/src/supertux/menu/addon_menu.cpp:378 Enabling add-on failed: Couldn't find installed Addon with id: langpack-fr
[WARNING] /home/leo/supertux-0.4.0/src/addon/addon_manager.cpp:567 Could not load add-on info for addons/langpack-fr.zip: Problem when reading addoninfo '/langpack-fr.nfo': file is not a supertux-addoninfo file.
[WARNING] /home/leo/supertux-0.4.0/src/supertux/menu/addon_menu.cpp:378 Enabling add-on failed: Couldn't find installed Addon with id: langpack-fr
[WARNING] /home/leo/supertux-0.4.0/src/addon/addon_manager.cpp:567 Could not load add-on info for addons/langpack-fr.zip: Problem when reading addoninfo '/langpack-fr.nfo': file is not a supertux-addoninfo file.
[WARNING] /home/leo/supertux-0.4.0/src/supertux/menu/addon_menu.cpp:378 Enabling add-on failed: Couldn't find installed Addon with id: langpack-fr
[WARNING] /home/leo/supertux-0.4.0/src/addon/addon_manager.cpp:567 Could not load add-on info for addons/langpack-fr.zip: Problem when reading addoninfo '/langpack-fr.nfo': file is not a supertux-addoninfo file.
[WARNING] /home/leo/supertux-0.4.0/src/supertux/menu/addon_menu.cpp:378 Enabling add-on failed: Couldn't find installed Addon with id: langpack-fr
[WARNING] /home/leo/supertux-0.4.0/src/addon/addon_manager.cpp:567 Could not load add-on info for addons/langpack-fr.zip: Problem when reading addoninfo '/langpack-fr.nfo': file is not a supertux-addoninfo file.
[WARNING] /home/leo/supertux-0.4.0/src/supertux/menu/addon_menu.cpp:378 Enabling add-on failed: Couldn't find installed Addon with id: langpack-fr
leo@leo-aspire5720Z:~/supertux-0.4.0$ 

Maybe that's because the langpack-fr file isn't complete ? It is lighter than previous version and don't include some files as "World 1" for example ...

Maybe we should re-open this issue ?

**Comment by tobbi** [comment]
Please re-download the add-on index file (Check for updates), then try again. My script to create langpacks is still fairly experimental and works on my OS only.

**Comment by mol-1** [comment]
Thanks, I'll try it right now

**Comment by mol-1** [comment]
I can download it but translation for main menu or world 1 is still missing. There are only some addons translations on the file "https://raw.githubusercontent.com/SuperTux/addons/master/langpacks/langpack-fr.zip", maybe that's the source of the issue ?

**Comment by mol-1** [comment]
@maxteufel : C'est fait :-)

**Comment by mol-1** [comment]
And ... It works ! Thanks guys :-)

**Comment by mol-1** [comment]
In fact, how often are updated translations as these ones ?(Because I just corrected two tiny mistakes on Transifex I notified while testing the game ...)

**Comment by tobbi** [comment]
These are updated manually. We could actually have a cronjob for those things. But that needs to be decided at a later point.

**Comment by maxteufel** [comment]
I guess if we get a notice that there were big changes. Or shortly before a release. Or possibly we'll do 1 month translation update cycles.

**Comment by mol-1** [comment]
Ok thanks
