### ISSUE TITLE
Iceblock loses apon all momentum when it hits the ground after being thrown 

### ISSUE THREAD

**Issue by Frostwithasideofsalt** [SuperTux/supertux#3086]
https://www.youtube.com/watch?v=b04ZbwfIQLs

**Comment by MatusGuy** [comment]
I've noticed the iceblock hit objects and not solid tiles - Does this occur when you throw one into solid tiles?

**Comment by bruhmoent** [comment]
I tried it and it also happened on a normal surface (randomly)

**Comment by MatusGuy** [comment]
Does this also happen while not airborne?
