### ISSUE TITLE
Always prefer langpack strings over strings contained in packaged PO files

### ISSUE THREAD

**Issue by tobbi** [SuperTux/supertux#309]
Langpack strings are most likely more recent than the ones contained in the PO files contained within the game.

However, currently, these are being ignored as it is. We should probably change tinygettext in that aspect.

**Comment by Karkus476** [comment]
@tobbi Langpacks are being ignored, or PO files are being ignored?

**Comment by tobbi** [comment]
From what I can tell, translations are ignored if a translation for the given string already exists in the database.

**Comment by tobbi** [comment]
xref #360
