### ISSUE TITLE
Check Translating of Messages in Climbable Objects

### ISSUE THREAD

**Issue by Karkus476** [SuperTux/supertux#311]
We need to test if this works. (Will ``(_ "...")`` be needed? )

**Comment by maxteufel** [comment]
Works, I think `(_ "message here")` will be needed inside the `.stl` files in order mark the string as translatable for the script extracting the strings (if it would mark all strings as translatable we'd end up with different scripts for every language; it's also required for the names of levels). What I'm not sure is if we need `_(message)` in the code, but...

**Comment by Karkus476** [comment]
@maxteufel I saw your code, which was why I asked. If it works, though, shouldn't be a problem.
