### ISSUE TITLE
Frozen then thawed dispensers cannot be frozen again

### ISSUE THREAD

**Issue by mark-otaris** [SuperTux/supertux#313]
If Tux throws an iceball (with the iceflower) at a dispenser, badguys will stop coming out of it. If Tux then throws a fireball at it, badguys will start coming out again. One would expect that the dispenser can be frozen again, and that if this is done badguys will stop coming out.

Steps to reproduce (works with all [types of dispensers](http://supertux.lethargik.org/wiki/Dispenser), in all levels):

1. Open level “Freezing test” (in contrib levels, test collection).
2. Get the iceflower powerup.
3. Freeze one of the three dispensers in the level with an iceball.
4. Get the fireflower powerup. (It is not in the level, but can be obtained from the console with `sector.Tux.add_bonus("fireflower")`.)
5. Thaw the dispenser with a fireball. The appearance of the dispenser will not change if it is a trap door or a rocket launcher, but will change if it is a cannon, however  badguys will start appearing again regardless.
6. Get the iceflower powerup once more.
5. Freeze the dispenser with an iceball.

Expected result:

* The appearance of the dispenser should change when it is thawed, and when it is frozen again after that.
* When the dispenser is frozen after being thawed, it should stop sending out badguys.

Actual result:

* The appearance of the dispenser only changes when it is frozen the first time, and when it is thawed if (and only if) it is a cannon.
* Once dispensers have been frozen and thawed, they cannot be frozen again.

**Comment by brmbrmcar** [comment]
Test level: https://paste.kde.org/pk0d75nmn

**Comment by Karkus476** [comment]
@mark-otaris Thank you for a very thorough bug report.

**Comment by brmbrmcar** [comment]
Can you squish them also now? That was an issue.
