### ISSUE TITLE
Sleeping Mr Spikey's need thier own melting sprite

### ISSUE THREAD

**Issue by n3rdopolis** [SuperTux/supertux#315]
It seems to use the melting sprite for the normal one when melting a sleeping spikey, which makes it look like it has to stand up as it's being melted. I can verify with the one in the beginning of "The Journey Begins"

**Comment by Karkus476** [comment]
@n3rdopolis Maybe sleeping spikys can be invincible while asleep? (Unless frozen)

**Comment by n3rdopolis** [comment]
That's actually probably a better idea.

**Comment by maxteufel** [comment]
Sleeping enemies should be easier, not harder to attack.

**Comment by Karkus476** [comment]
@maxteufel When sleeping, they appear to sit in their shell, protected...

**Comment by maxteufel** [comment]
Also depends if the fire is hot enough to melt the shell

**Comment by Karkus476** [comment]
@maxteufel According to @Hume2's melting animation, it's not.
