### ISSUE TITLE
Burning Should Be a Particle Effect

### ISSUE THREAD

**Issue by Karkus476** [SuperTux/supertux#316]
And freezing should be a special filter.
This saves developers and artists tons of time making lots of new images for these simple animations.
I'd be especially impressed if we could figure a way to generalize the melting effect, but I seriously doubt that is going to happen.

**Comment by Karkus476** [comment]
There should also be the option to create your own burning effect as well.

**Comment by Hume2** [comment]
Previously it had to, but Tobbi didn't like it.

**Comment by maxteufel** [comment]
Not really a bugfix. Changing Milestone to 0.5.0.

**Comment by tobbi** [comment]
What I didn't like about the particle effect on badguys was that there were so many flames spawned all over the badguy that it just looked fake.

**Comment by Karkus476** [comment]
@tobbi So, you prefer how it is now?

**Comment by tobbi** [comment]
I do, in my opinion it looks better. I would like to model the current approach into a particle effect (have one growing flame as a particle) but not sure if that's possible with the current setup.

**Comment by Karkus476** [comment]
@tobbi What I am proposing is a change of the current setup :smiley:

**Comment by tobbi** [comment]
Ah, if that's possible, sure.

**Comment by Karkus476** [comment]
@Hume2 The burning animation should probably emit light, too.

**Comment by Karkus476** [comment]
This was discussed in the meeting: #292
Removing needs-discussion.

**Comment by Savsish** [comment]
Yes i don't get the tobbi likes but burning must be a particle effect. Why would modders creating their own badguy bother making burning animation for each badguy and that would cosume a disk space and resources.

**Comment by maxteufel** [comment]
From #292:
> Burning must emit light, but will stay as is.

I guess this means we can we can close this.

@Karkus476 If that's not the case, please reopen this issue.
