### ISSUE TITLE
Always in start position on map

### ISSUE THREAD

**Issue by dacrhu** [SuperTux/supertux#318]
If end of level the tux is in start position on map always.
Screenshot:
http://imgur.com/gsQvYEY

**Comment by tobbi** [comment]
Please start supertux with the --debug switch and paste the debug output here.

**Comment by Karkus476** [comment]
@dacrhu https://pastebin.com

**Comment by maxteufel** [comment]
It would probably be interesting to see an strace or similar that logs what's written to disk.

**Comment by dacrhu** [comment]
--debug output:
http://pastebin.com/v1xSGamM

**Comment by maxteufel** [comment]
```
[DEBUG] /builddir/build/BUILD/supertux-0.4.0/src/worldmap/worldmap.cpp:1088 Not loading worldmap state: Squirrel error: failed to get 'worlds' table entry (the index doesn't exist)
```

Didn't we already have that here?

**Comment by maxteufel** [comment]
Yes, that already seems to have appeared in #199. Please try with a clean `userdir` (see `supertux2 --help`) and if that's still broken, try building from the official source tarball and test that, again using a clean `userdir`.

If the latter also doesn't work, that's a bug in SuperTux. If it does, it's most likely a bug with your distro's packaging (seems to be Fedora, as in #199).

**Comment by dacrhu** [comment]
Yes I have Fedora 23. Thank you for information, I close this ticket and I use official release.

**Comment by maxteufel** [comment]
Please confirm this works with a separate `userdir` or the official build; reopen if it doesn't.

**Comment by dacrhu** [comment]
[dacr@dacr ~]$ supertux2 --userdir ./stuser/
[SQUIRREL] [DEBUG] Underground state initialized
[WARNING] /builddir/build/BUILD/supertux-0.4.0/src/video/texture_manager.cpp:192 Couldn't load texture '/images/objects/resetpoints/bell-m.png ' (now using dummy texture): Couldn't open '/images/objects/resetpoints/bell-m.png ': No such file or directory
[WARNING] /builddir/build/BUILD/supertux-0.4.0/src/video/texture_manager.cpp:192 Couldn't load texture '/images/objects/resetpoints/bell-m.png ' (now using dummy texture): Couldn't open '/images/objects/resetpoints/bell-m.png ': No such file or directory
[WARNING] /builddir/build/BUILD/supertux-0.4.0/src/supertux/sector.cpp:585 [levels/misc/menu_final.stl] Tried spawning Tux in solid matter. Compensating.

Don't save state.

I will build from source, please patient.

**Comment by dacrhu** [comment]
I built from source and working fine. I send this bug to Fedora package maintainer.
Thank you everything, have a nice day!
