### ISSUE TITLE
Magic blocks do not respond to some light elements

### ISSUE THREAD

**Issue by LMH0013** [SuperTux/supertux#319]
Recent changes to magic blocks have caused them to quit functioning is certain circumstances.  Specifically, if a bonusblock contains the "light" bonus or if the livefire enemy is anywhere near the magic block it will not turn solid.  I think this is because the threshold for turning solid was changed.  This could possibly be corrected by tweaking the light sprites.  Alternatively the threshold could be changed again, but I don't know the backstory for the original change and would hate to introduce/re-introduce other bugs.

I don't think this affects any of the core game, only potentially a couple of levels in the addons.  However, it does render these features useless for their original intent.

**Comment by Hume2** [comment]
Put grey magic blocks instead. It should work.

**Comment by brmbrmcar** [comment]
Not sure if this is relevant, but I can't even get magic blocks to go non-solid.

**Comment by LMH0013** [comment]
@Hume2: Good idea, I forgot that only the lanterns were locked to specific colors.  I'll give it a try as a workaround.  Probably should still fix the underlying issue though.

@brmbrmcar: Change the ambient light.  If your level is too bright, then they will always be solid.

**Comment by brmbrmcar** [comment]
@LMH0013 Thanks.

**Comment by Hume2** [comment]
Lanterns aren't locked to specific colours and never were. We can only say that they are locked to 16777216 colours.

**Comment by Karkus476** [comment]
It might be useful to identify the commit which introduced the change, so we can see what was implemented then, and maybe the reasons too

**Comment by Hume2** [comment]
I remember that I implemented 16777208 colours of magic blocks, but the trigger value was 1.0 even before that commit.

**Comment by LMH0013** [comment]
I bet the fixed colors for lanterns is an editor thing, not that it's pertinent to the conversation, sorry for the confusion.  I had already lost the ability to spend a lot of time on the project when the change occurred, so I couldn't tell you when the it happened.  Looking at the commit history for magic blocks wasn't very helpful, so I really am at a loss for when the change actually happened.

**Comment by Hume2** [comment]
Mono/C# editor approximates the colours to the closest extreme, but SuperTux doesn't. I really don't know why this was implemented in the editor.

**Comment by tobbi** [comment]
Can anyone get a regression range for this?

**Comment by tobbi** [comment]
I *assume* that this error is caused by the lisp parser changes. Taking a look at the commits, this seems to be related.

**Comment by Hume2** [comment]
This is an intended behaviour, since it was (maybe accidentally) in a stable release.
I've tweaked the Mattie's World, so it no longer appears here. It doesn't appear in any other levels.

**Comment by LMH0013** [comment]
So was it intended to break the normal behavior or was it done accidentally?  Because I'm pretty sure those are opposites.  Or is this just a dodge to fix someone's sloppy change because it happened to make it into a "stable" release (which, let's be honest here, has less to do with stability rather than an arbitrarily predefined date needed to breathe life back into the project).

Furthermore, just tweaking the level where the bug was first apparent is a workaround for that level, not a fix to the problem (btw it does appear in at least one other level, but not to the same level of severity).  Livefire and bonusblocks containing light still do not behave as intended when interacting with magic blocks.  Anyone who makes a level with the mono editor is going to run into the same problem and be unable to fix it without manually tweaking the level file.  Which makes it a major pain to keep using the editor.  The use of gray magic blocks is very non-intuitive and should be considered an advanced technique and not the expected norm- actually, it should be completely unnecessary for almost all applications.

If we want to just remove these elements from the game for lack of use, then fine.  But if we're going to keep them then they need to be usable without making bizarre tweaks every time a magic block is involved.

**Comment by Hume2** [comment]
I managed to tweak the Mono editor for myself that it supports more colours. I haven't pushed it so far, but I could.

Also changing back this behaviour, whether intended or not, would cause another change of the behaviour, making it even more unstable, so the levels created in 0.4.0 wouldn't work in the next version the same.

If it is important to change the behaviour in another level, feel free to post here a list of those levels.

**Comment by LMH0013** [comment]
No need to keep tweaking levels when the error comes up- I've pushed a change that should take care of the actual issue without compromising whatever change that caused it.  Keep in mind that when you tweak addons that they end up being flagged as a new version in the addon manager.  When this is done as just a workaround you'll give people a false impression that a newer version of the addon is available.  This is also highly inefficient.  Better to fix the issue instead and avoid filling the repo with needless extra versions with minor changes that just take up space.
