### ISSUE TITLE
Crushing a burning badguy resets the sprite

### ISSUE THREAD

**Issue by LMH0013** [SuperTux/supertux#321]
Shooting most badguys and dropping a block on top of them results in bizarre behavior.  This is most easily observed when a badguy burns, but if you're quick you can see it with a melting badguy as well.  Often the badguy will be pushed into the ground where their sprite will change to the default walking.  While they appear to be alive, they are not and do not cause harm to Tux.  It is however very unsightly.

I suspect that this is because all the death animations are done by sprites, so this is going to require some coding to fix.  I know a similar problem existed for the badguy livefire, I think the fix was to change what group the badguy belongs to upon death.  I'm not sure what level the death animations were implemented on (does every badguy need to be fixed individually or can it be done in just badguy).  I think the code for livefire can be used as a template to figure it out though.

This may be a good argument for non-sprite death animations.  For example melting badguys could be replaced with a water object(s) which could then be more dynamic with the environment.  Judicious use of flame particles could handle buring especially if we can leave behind an ash silhouette of the original badguy.  While this would be more work than simply fixing the current bug, I think the end result would be much better.

**Comment by Karkus476** [comment]
I can confirm that I have seen this bug.

- Karkus
