### ISSUE TITLE
Game objects move explosions

### ISSUE THREAD

**Issue by LMH0013** [SuperTux/supertux#322]
Lanterns, rocks, portable trampolines can be thrown into an explosion to nudge it to the side.  This shouldn't happen.

**Comment by tobbi** [comment]
Can you please test the fix, @LMH0013

**Comment by LMH0013** [comment]
@tobbi  It looks like the fix largely works, however, it does look like there is a slight nudge that occurs very momentarily before the explosion returns to the original position.  Not sure how often it will crop up in real gameplay, but it did look odd on a test level with rocks on top of haystacks suspended above bombs.

**Comment by tobbi** [comment]
Can you attach the test level here? (file extension .txt should work)

**Comment by LMH0013** [comment]
How's that?  Just shoot the hay and you should observe the nudge.

[rockpush.txt](https://github.com/SuperTux/supertux/files/149467/rockpush.txt)
