### ISSUE TITLE
Butt jumping should do more damage to certain enemies

### ISSUE THREAD

**Issue by misterhat** [SuperTux/supertux#324]
The enemies that separate or change when damaged could be killed with just one butt jump instead:
- [x] Snowman
- [x] Mr Tree

**@Karkus476 Edited 9th Jan 2016 - Changed to checklist**

**Comment by brmbrmcar** [comment]
The should all have sprites, and so should the Mr Iceblock.

**Comment by Hume2** [comment]
@SuperTux/developers May I implement this?

**Comment by Hume2** [comment]
Done. Someone test it please.
