### ISSUE TITLE
Allow custom tiles for levels

### ISSUE THREAD

**Issue by Grumbel** [SuperTux/supertux#325]
In reference to 057aa7dbf6257d5b4bd697b4080b25ef352cc1d9

Removed support for multiple Tilesets inside a level file, i.e. the (tilesets ...) tag

Neither the official nor addon levels make use of this feature, it
isn't support by any of the editors either. Addons that use custom
tilesets are just defining a new tileset, instead of mixing them in
the level file, so the ability to use custom tilesets inside a addon
is still available.

If there is any demand for this feature it should be brought back as
function inside the .strf files, not the .stl files, i.e. something
like:

```
(supertux-tiles
   (import-tileset
      (file "tilesetname.strf")
      (start 0)
      (end   2153)
      (offset 0))

   ;; custom tiles go here

   ...))
```

The .stl file would then refer to a single tileset file, instead of multiple as once. Thus allowing sharing of tilesets between level files without the need to duplicate the imports in every .stl

**Comment by Karkus476** [comment]
@Grumbel However, conflicting IDs could be a problem.

**Comment by Grumbel** [comment]
Ids are only valid in the context of a single .strf, if tiles from another .strf are imported their ids get remapped to the specified range:

    for old_id in range(start, end):
        new_id = old_id + offset

`start`, `end` ensure that conflict don't arise when the old .strf grows, `offset` says where they get remapped to.
