### ISSUE TITLE
ACTION key setup needs improving

### ISSUE THREAD

**Issue by brmbrmcar** [SuperTux/supertux#326]
Currently, even if the ACTION key is not set to control, it can still be used for ACTION but you cannot jump with it on without Jump with Up.

**Comment by Karkus476** [comment]
@brmbrmcar The only key which I can trigger an action with is the key I choose. Jumping is a different key to action.

**Comment by brmbrmcar** [comment]
@Karkus476 I probably confused you with the jumping. It is only the ACTION key at fault.

**Comment by brmbrmcar** [comment]
Unless anyone thinks this needs to change,I will keep this closed.
