### ISSUE TITLE
Scripting interface is not safe from memory access violations

### ISSUE THREAD

**Issue by Grumbel** [SuperTux/supertux#327]
How to crash the game:

* start a level
* open the console
* grab a game object and assign it to a variable `a <- sector.Text` 
* leave the level thus freeing the memory associated with the object
* now access the object in the console `println(a.get_pos_x())`

    Program received signal SIGSEGV, Segmentation fault.
    0x000000000085cbdd in scripting::wrapper::Text_get_pos_x_wrapper (vm=0x1b892c0) at    /home/ingo/projects/supertux/trunk/supertux/src/scripting/wrapper.cpp:2531
    2531	    float return_value = _this->get_pos_x();

We should use handles in the scripting interface, not raw pointers.

Not sure if this is triggerable by level files themselves or if their scripting VM/namespaces are isolated from each other and thus don't allow to reuse variables between levels.

**Comment by Grumbel** [comment]
Rewrote the code to not use multi-inheritance in f805791, next step would be to replace the raw pointers in the wrapper classes with std::weak_ref or some other kind of handle.

**Comment by Grumbel** [comment]
A NULL check won't help, as the problem isn't the validity of the scripting object, but the parent pointer inside the scripting objects. Karkus476 has a patch in the works that replaces the raw parent pointer with a weak_ref, that should fix it.

**Comment by tobbi** [comment]
Ah, alright, thanks for the info.

**Comment by Karkus476** [comment]
@Grumbel I think you mean someone else. I wouldn't know where to start with this one...

**Comment by tobbi** [comment]
What's the difference between null-checking the pointers inside the script objects and using weak_ref? We'd still have to write some checks.

**Comment by Grumbel** [comment]
The pointer never goes NULL, it just goes invalid. You can't detect that from a raw pointer.

**Comment by tobbi** [comment]
I cannot reproduce the issue in a recent nightly. Can you try with the latest code, please, grumbel?

**Comment by maxteufel** [comment]
While I can reproduce this on SuperTux v0.4, the game doesn't crash on current master. Please re-open this if it is still an issue for you, @grumbel.

Switching to `std::weak_ref` could be a new issue, targeted at a post-0.5.0 release.
