### ISSUE TITLE
xgettext warnings

### ISSUE THREAD

**Issue by MiroslavR** [SuperTux/supertux#328]
# Information

Step to reproduce: Run makepot.sh.
SuperTux version: git 17d7ef9
OS: Linux (Debian Testing)
# Xgettext warnings

**Empty msgids**

<pre>
data/levels/incubator/let_us_snow.stl:339: warning: Empty msgid.  It is reserved by GNU gettext:
                                                    gettext("") returns the header entry with
                                                    meta information, not the empty string.
</pre>

The "Let us snow!" level contains infoblocks with empty messages, used to create walls outside of map boundaries. I'm assuming this is the fault of the editor marking zero-length strings as translatable.

**Windows line endings**

<pre>
data/levels/incubator/Missingno.stl:535: warning: internationalized messages should not contain the '\r' escape sequence
</pre>

I'm assuming that either the editor saves maps with Windows line endings on Windows, or that particular map has been edited with a text editor which disregards Unix line endings.

**Comment by MiroslavR** [comment]
@Hume2 How about the other warning about Windows line endings?

**Comment by Hume2** [comment]
Well, you're right. Something should be done with this to prevent future issues with it.

**Comment by tobbi** [comment]
Okay, what we could do is run sed to prevent those kind of issues.

**Comment by tobbi** [comment]
I can't reproduce that issue anymore. I'm gonna close it. If it happens again, it can get reopened.
