### ISSUE TITLE
Haywire bomb game crash 

### ISSUE THREAD

**Issue by IndianaTux** [SuperTux/supertux#334]
SuperTux Version 0.4.0  Windows 7 64bit
After stomping on a Haywire bomb shooting an iceball at the Haywire will crash the game. This glitch doesn't happen in SuperTux 0.3.5a with the same OS.

**Comment by tobbi** [comment]
For crashes, please provide a stacktrace, if you can.

**Comment by brmbrmcar** [comment]
Is it specific to Windows?

**Comment by Narre** [comment]
I guess it hapens on Windows only. I have no problems with this on Linux (Ubuntu 14.04 64bit).

**Comment by brmbrmcar** [comment]
I'm on Ubuntu too.

**Comment by IndianaTux** [comment]
I don't know how to get a stacktrace, but I noticed that just before the game crashes, the Haywire does get frozen by the iceball.

**Comment by tobbi** [comment]
Does this issue also occur with a recent nightly build? See http://download.supertuxproject.org/download/

**Comment by IndianaTux** [comment]
@tobbi 
The issue doesn't occur with the recent nightly build on windows 7 64bit.

**Comment by tobbi** [comment]
Okay, so I'll assume this is fixed. Please do continue testing in case this creeps up again.

**Comment by tobbi** [comment]
I just tested the fix for this issue myself in Wine and it appears to be working. If you want to test it yourself, go ahead and use a nightly build from http://download.supertuxproject.org/download/

**Comment by IndianaTux** [comment]
Thanks for the nightly build. This issue is fixed in Windows 7.
