### ISSUE TITLE
Invalid Worldmap Boat Animation

### ISSUE THREAD

**Issue by IndianaTux** [SuperTux/supertux#342]
This bug is about the wrong animation being displayed on the worldmap.

After exiting a worldmap while Boat Tux is moving in the water, entering back the worldmap will display a still regular worldmap Tux. Going on land and back in to the water will display the correct Tux animation.   

SuperTux 0.4.0  Windows 7 64-bit  
I also saw this glitch happen in Windows 10 64-bit.

**Edit by Hume2**
- [x] Save Tux's current sprite
- [x] Save SpriteChanges' actions

**Comment by brmbrmcar** [comment]
Do you mean air/earth Tux? I don't know what you mean by Boat Tux.

**Comment by Hume2** [comment]
Indeed this happens. The boat was supposed to be in-development, so that's why it's so buggy. This should be fixed until the next milestone.

**Comment by tobbi** [comment]
We have special SpriteChange tiles...however, after entering the water again, these sprite change tiles don't have any effect, since those have never been triggered in the first place.

**Comment by tobbi** [comment]
We should save the current Tux's sprite in the savegame files. If anyone would be willing to do that, go ahead.

**Comment by MiroslavR** [comment]
> We should save the current Tux's sprite in the savegame files. If anyone would be willing to do that, go ahead.

We should also save the visibility of SpriteChange objects, no? The boat shouldn't reappear when it's already been taken.

**Comment by MiroslavR** [comment]
As for the second goal, serializing SpriteChange objects presents a problem. They don't seem to have a unique property that could be used to identify them, besides their index in the vector they are stored in. Is identification via index reliable enough? What if the editor saves the objects in a different order?

**Comment by Hume2** [comment]
@MiroslavR That is not reliable enough. The order of the lisp tags doesn't carry any info, so the sprite changes can be saved in any order by the editor. I personally don't know any better sollution than saving all positions of sprite changes those are on/off. I didn't know any better sollution and didn't want to apply this.

**Comment by tobbi** [comment]
I'm sorry, but I had to back out the fix. It caused several issues and squirrel warnings. I am not exactly sure what's wrong. Gonna postpone it until 0.6.0 or 0.5.1. Until then, I am willing to get a PR up with the commits for others to take a look at it and spot bugs.

**Comment by tobbi** [comment]
*Apparently* the issue was NULL values in the savegame file. I handled that in a better way in 03fedba and reverted the reverting commit in 8a6a65a.
