### ISSUE TITLE
Add translations for help messages in 

### ISSUE THREAD

**Issue by Savsish** [SuperTux/supertux#348]
Milestone 2 is now released but translations for the help messages in some languages are now removed and they call it a stable release. Why the players would bother reading English text when their language is set to x.y.z and this can cause trouble for forgien players figuring on how to play the game if they can't read English. Please fix this nasty bug for now and release 0.4.1 as a bugfix release for forgien players sake.

**Comment by Savsish** [comment]
Milestone 2 is now released but translations for the help messages in some languages are now removed and they call it a stable release. Why the players would bother reading English text when their language is set to x.y.z and this can cause trouble for forgien players figuring on how to play the game if they can't read English. >:(

**Comment by maxteufel** [comment]
Showing English text when there is no localization should be an intended behavior, as it is better than showing no text or explanation at all.
