### ISSUE TITLE
Warn user when a localization is incomplete

### ISSUE THREAD

**Issue by brmbrmcar** [SuperTux/supertux#349]
I would have commented elsewhere, but it was locked. Basically, there should be some sort of indication by a language with less translations.

**Comment by tobbi** [comment]
afaik, missing translations just use the English source strings, right? Also, we only include translations with more than 50 %, anyway.

**Comment by brmbrmcar** [comment]
Correct.

**Comment by tobbi** [comment]
What do other open-source projects do for cases like these? I am afraid that showing a warning might be a bit overkill.

**Comment by huftis** [comment]
@tobbi I haven’t seen a project which shows a warning for incomplete localisation. And I don’t think showing such a warning is very useful for the user. What projects typically do, is have a percentage cut-off for a localisation to be included in the *released* product, e.g. > 80%. For projects that consists of different parts, e.g. a main application and several add-ons, the cut-off usually only applies to the main application, or different parts of the application have different cut-offs.

**Comment by tobbi** [comment]
Closing as per #issuecomment-314834662
