### ISSUE TITLE
[RFC] Localization policies

### ISSUE THREAD

**Issue by maxteufel** [SuperTux/supertux#351]
During an IRC discussion, the idea of a policy for new and old translations came up. The goal of these policies is to ensure quality of the translations.

#### Translation requests
Require the person requesting the new translation to provide a `.po` file with translations for 100 % of the main resource strings and 70 % of other strings (add-ons, ...).

#### Existing translations
Existing translations should be removed when less than 90 % of the main resources and 50 % of the other resources are translated and the translation has not been updated for 3 months.

**Comment by maxteufel** [comment]
###### Meeting decisions (#435)

> - Translation policy RFC (#351)
>   - For newly requested languages: Submitted in .po form to the projects maintainers, 85 % of main game and mainlevels translated, 25 % of the add-ons
>     - :+1: @Hume2, kneekoo, @tobbi, @giby, @maxteufel
>     - Result: PASS
>   - Remove them from the game when less than 75 % of the main game and main levels and 20 % of the addons are translated, and the translation has not been updated for 3 months. Keep them on Transifex. (Add them back once they reach the requirements)
>     - :+1: @Hume2, kneekoo, @tobbi, @giby, @maxteufel
>     - Result: PASS

**Comment by maxteufel** [comment]
This needs some better documentation than this issue.

**Comment by kneekoo** [comment]
Hey, guys! That kneekoo is me. :)

**Comment by maxteufel** [comment]
@kneekoo Updated it!

**Comment by kneekoo** [comment]
Thank you. :)
