### ISSUE TITLE
Hitbox bug - Flip and climb

### ISSUE THREAD

**Issue by Narre** [SuperTux/supertux#352]
I've noticed this bug today. When largetux is climbing from a flip, the hitbox is not correct (is like smalltux's hitbox):
[https://youtu.be/XtCNav5iS-w](url)

**Comment by Narre** [comment]
Sorry, wrong link, issue here: https://github.com/SuperTux/supertux/issues/353

**Comment by maxteufel** [comment]
You should have been using the edit buttom to fix this issue. Leaving this as-is now, but that possibility has been clarified in `CONTRIBUTING.md` (see 4e1a451).
