### ISSUE TITLE
Get rid of old and ugly dispenser

### ISSUE THREAD

**Issue by tobbi** [SuperTux/supertux#354]
Instead of having this ugly dispenser sprite, we can have a dispenser area...so something that drops badguys and is like a secret area trigger. That way, you can use any sprite to cover it.

Or we should update the dispenser sprite, but finding a generic dispenser sprite could be difficult.

**Comment by brmbrmcar** [comment]
I disagree. The old dispensers should still be there. However, more sprites could be added.

**Comment by Hume2** [comment]
I think that it doesn't have to be an area, it could be just one point. I just don't know whether this should be still the "dispenser" factory or another factory.
