### ISSUE TITLE
Use separate text domains for translation of worlds

### ISSUE THREAD

**Issue by MiroslavR** [SuperTux/supertux#360]
It seems SuperTux uses PO files from ALL directories in data/levels (including those that lack the "info" file), not just the current world's directory, which should be the case. Every world should have its own text domain, mainly to prevent conflicts.

There is another issue, which relies on this behavior and thus will need to be addressed as well: The add-on worlds "CT's Domain" and "Race to Penny" share the same resource (data/levels/CTW/&lt;lang&gt;.po).

**Comment by tobbi** [comment]
I am assuming that the PR that added precedence to search paths should fix this issue. If not, it can be re-opened.
