### ISSUE TITLE
Bug with moving tilemaps

### ISSUE THREAD

**Issue by brmbrmcar** [SuperTux/supertux#362]
http://paste.ubuntu.com/14967841/

**Comment by Hume2** [comment]
So if I got it well, the bug is in that you glitch trough the tilemap when it's moving too fast. What do you need it for?

**Comment by brmbrmcar** [comment]
I'm just reporting that it is there. How do you even change the speed of it?

**Comment by Hume2** [comment]
You incerase the time in the node. It says how long it should travel towards the next node.

**Comment by brmbrmcar** [comment]
I don't see that anywhere.

**Comment by Hume2** [comment]
Click on the node in the editor and it appears in the bottom menu.

**Comment by brmbrmcar** [comment]
Ah. I missed that.  I thought it needed to be in the script.

**Comment by Hume2** [comment]
This bug occurs because the tilemap is moving about 32px per update. I'm not sure whether this really deserves a fix.

**Comment by brmbrmcar** [comment]
Changing the speed does not work. It travels at the same speed.

**Comment by Hume2** [comment]
When you want lower speed, you have to increase the time.

**Comment by brmbrmcar** [comment]
I did just that.

**Comment by Hume2** [comment]
Maybe you modified wrong node.

**Comment by brmbrmcar** [comment]
I did it to both.

**Comment by Hume2** [comment]
Then set the time to I dunno, 500000.

**Comment by Hume2** [comment]
This is not going to be fixed, because proper calculation of collisions of objects moving extremely fast are too slow, so it has not the worth of fixing that. That you can't use the editor is another thing.

**Comment by brmbrmcar** [comment]
I can use the editor!
