### ISSUE TITLE
Documentation on debugging

### ISSUE THREAD

**Issue by maxteufel** [SuperTux/supertux#369]
Provide some links for users to guides that explain how to e.g.: get a stacktrace when the game crashes and then add that information to `CONTRIBUTING.md` or make it visible using GitHub's new issue template feature.

Ref: #334

**Comment by tobbi** [comment]
We added a function that allows posting stack traces to github recently. I think this issue can be closed.

**Comment by Vankata453** [comment]
Yeah, #2908 and #2934 fix this.
