### ISSUE TITLE
Add ISSUE_TEMPLATE file

### ISSUE THREAD

**Issue by tobbi** [SuperTux/supertux#370]
In order to make bug reports more concise, Github offers an ISSUE_TEMPLATE file that is used as a template for new issues.

Check https://help.github.com/articles/creating-an-issue-template-for-your-repository/ 

What do we want issue reporters to specify?

**Comment by Hume2** [comment]
I'd suggest:

- What happens
- How to reproduce it
- Used OS
- Other info

**Comment by brmbrmcar** [comment]
I don't like the idea. Lots of issues would not work to a template.

**Comment by maxteufel** [comment]
> - Command line output

Only if it makes sense. For stuff like feature requests it absolutely doesn't, even though feature requests would actually fit into a template:

What happens? - *current behavior*
What's expected? - *proposed behavior*

**Comment by maxteufel** [comment]
Fixed in 36105b3807922f7e62f698b72f92ee5f3636a476.
