### ISSUE TITLE
SuperTux Milestone 3 (0.5.0) will be more complete and stable than Milestone 2 (0.4.0)

### ISSUE THREAD

**Issue by Savsish** [SuperTux/supertux#371]
SuperTux Milestone 2 (0.4.0) is now released and for me it's still looks like a crappy beta version with bugs than even don't happen in 0.3.5a (skipping 0.3.6 was a bad idea enough), incomplete translations, unfinished levels, etc. Version 0.4.1 will probably fix some bugs and finish translations but still. The forest world will be likely finished in Milestone 3 (0.5.0).

**Comment by maxteufel** [comment]
> Milestone

We don't have milestones anymore now, we use SemVer.

> skipping 0.3.6 was a bad idea enough

Nope, declaring 0.4.0 as stable was a great idea that made people actually report bugs.

> incomplete translations

This has been fixed by adding support for translations that can be updated (using the add-on manager).
