### ISSUE TITLE
Tux dies when jumping on top of gap between block and terrain

### ISSUE THREAD

**Issue by tobbi** [SuperTux/supertux#373]
Check this out:
https://youtu.be/xhzMElVeFew?t=1m25s

This shouldn't happen!

**Comment by brmbrmcar** [comment]
I can't reproduce.

**Comment by Hume2** [comment]
It happens generally when he jumps into a narrow vertical gap.

**Comment by PrinceRilian** [comment]
I'm pretty sure that is happening when the gap is 31 or less pixels wide.

**Comment by PrinceRilian** [comment]
Here is a similar issue that I believe has the same cause.  If Tux throws a block, lantern, or Mr. Ice Block directly upward and waits there... or attempts to catch it after moving sideways under as much as its edge, he gets injured!  As long as the dimension x indicated below in figure 4 is **at least one pixel**, he will get injured.  (Tux is okay if he does not move sideways at all, and can catch any object he threw directly upwards with a press of Ctrl.)  _It does not appear that any enemies can get injured by falling blocks, enemies, or lanterns, however.  They just get pushed off to the side and do not sustain any damage._

![supertux2 debug--building block issue--fig 1](https://user-images.githubusercontent.com/28693061/27148709-d8c25222-5106-11e7-848b-fb4218e44d51.jpg) ![supertux2 debug--building block issue--fig 2](https://user-images.githubusercontent.com/28693061/27148710-d8cb5ba6-5106-11e7-93a1-effa9114b6d2.jpg) ![supertux2 debug--building block issue--fig 3](https://user-images.githubusercontent.com/28693061/27148711-d8d40daa-5106-11e7-879c-586661966410.jpg) 
![supertux2 debug--building block issue--fig 4](https://user-images.githubusercontent.com/28693061/27149511-8496b82a-5109-11e7-9188-f6d58edd897d.jpg) ![supertux2 debug--building block issue--fig 5](https://user-images.githubusercontent.com/28693061/27148713-d8ddb7ec-5106-11e7-94bf-ff7cdcc0d7e0.jpg)

**Comment by tobbi** [comment]
I just tried to reproduce the issue but was unsuccessful.

I'm gonna close this.
If it's not fixed, feel free to reopen.

**Comment by PrinceRilian** [comment]
Actually, it had been fixed for some time already, as the error was not
present in the 2018 Main Release Version.
