### ISSUE TITLE
re: SuperTux 0.5.0 will be more complete and stable than current stable release (0.4.0)

### ISSUE THREAD

**Issue by Savsish** [SuperTux/supertux#374]
Sorry for possible repeat but i played the current stable version 0.4.0 and i kind of liked but i'm bit disappointed at same time as it looks a beta version mixed with finished and unfinished features and it has an annoying crash bug that does not even happen in 0.3.5a like if you shoot haywire bomb with an ice ball the game closes. I might wait some more time and give an try on 0.5.0 seeing it will be more polished and stable than 0.4.0.

**Comment by maxteufel** [comment]
If you want to report any actual bugs, please report serious issues, and don't spam the bugtracker.
