### ISSUE TITLE
Remove all pre exiting po files and replace them with language packs

### ISSUE THREAD

**Issue by Savsish** [SuperTux/supertux#379]
Not really an issue but i think since we now have support for adding language packs, all the pre existing po files (at least the level ones) should be removed from data dir now. This makes the users having to install the languages that they really looking for and i sure this would save loading time.

**Comment by tobbi** [comment]
I'd say this is a wontfix. I can assume that a lot of people is playing SuperTux without an active internet connection. We don't want to force those people to download langpacks.

**Comment by Savsish** [comment]
And update all language packs to change literal \r\n to \n

**Comment by maxteufel** [comment]
@Savsish: please read <https://github.com/SuperTux/supertux/blob/master/CONTRIBUTING.md#bug-reports>. It says:

> - Separate issues and feature requests. Don't put all in the same issue.
