### ISSUE TITLE
Adding support for GIF images for level backgrounds

### ISSUE THREAD

**Issue by IndianaTux** [SuperTux/supertux#385]
I tried putting a GIF image in the background of an random level but it didn't work. It would be cool that GIF images can work in level backgrounds because GIF images have short animations. 
Example: In tropical island the background can have palm trees that move because of the wind.

**Comment by brmbrmcar** [comment]
Can there be APNG support?

**Comment by IndianaTux** [comment]
@brmbrmcar I think APNG can be better than GIF but the game doesn't support it either.

**Comment by brmbrmcar** [comment]
I'd like both, with truecolour support on the gifs.

**Comment by maxteufel** [comment]
My comment about this on IRC:

> 16:53:25 <+mt> I'd prefer implementing support for Ogg Theora/WebM backgrounds instead of GIFs, lol

In other words: No this probably isn't going to happen. In fact, we already have special background objects that are animated (rain, snow, ghosts), and using that for making the given example happen is much better than implementing support for an outdated, bloated image file format.

**Comment by brmbrmcar** [comment]
Yes, but there are problems. Firstly, more image types should be accepted anyway, and secondly, these video backgrounds are likely to be hard to implement and very untidy and confusing.

**Comment by maxteufel** [comment]
GIF being an outdated, bloated file format is still true, as such that won't happen. About other file formats, what are you going to propose next? Is PNG not enough?

It is enough, and a game doesn't have to accept just any image format just because one person wants to do some silly stuff.
