### ISSUE TITLE
No invisible block to get into secret area in "Into the Stars"

### ISSUE THREAD

**Issue by GlowingApple** [SuperTux/supertux#388]
I'm playing 0.4.0 on Mac OS X.  In "Into the Stars" I can't get into the secret area.  At first I thought I just couldn't find it so I made a post at [http://a062.apm.etc.tu-bs.de/forums/viewtopic.php?pid=5454](http://a062.apm.etc.tu-bs.de/forums/viewtopic.php?pid=5454).  According to one of the comments there should be an invisible block that I can't seem to find.

I've enabled the console and ran debug_draw_solids_only (to uncover the hidden area) and debug_collrects (which should show any invisible tiles).

There doesn't seem to be an invisible block anywhere:
[http://i.imgur.com/4BI34ZO.png?1](http://i.imgur.com/4BI34ZO.png?1)

Is this a bug? Or am I just missing something?

**Comment by Hume2** [comment]
Small Tux bounces more when he jumps on those little bombs, so only small Tux can reach this secret area. I have already put there an invisible block, that allows big Tux to reach this secret area too. For now, it's only in the nightly builds, but should be in 0.4.1.

**Comment by brmbrmcar** [comment]
If there is a invisible block, it shouldn't be possible to still use the bombs to get up.

**Comment by brmbrmcar** [comment]
Why not just move it down so big tux can reach it? Then remove the block?

**Comment by tobbi** [comment]
@brmbrmcar: I will personally ask Github staff to prevent you from using reactions if you don't use them responsibly! As far as Github reactions are concerned, the only reaction you're entitled to is complete, utter silence and neutrality which (luckily, I might add) can't be expressed through GitHub reactions.

**Comment by tobbi** [comment]
@Hume2: Which commit is this fix in? Please write the commit SHA1 here and close it then.

**Comment by brmbrmcar** [comment]
Then go away

**Comment by Hume2** [comment]
881de130ba2ae6767776a187f7fbb9233e050f4d

**Comment by GlowingApple** [comment]
Thanks! I never realized that small tux bounces higher off short fuse than big tux.  I tried the level again and am able to reach it as small tux!

**Comment by GlowingApple** [comment]
Thanks! I never realized that small tux bounces higher off short fuse than big tux.  I tried the level again and am able to reach it as small tux!
