### ISSUE TITLE
Ice in the Hole secret path is too easy

### ISSUE THREAD

**Issue by brmbrmcar** [SuperTux/supertux#393]
_0.4.0_

##### Actual/intended behaviour
_The level becomes much easier to pass, perhaps to easy._

##### Steps to reproduce actual behaviour
_Go into the first secret, then go up onto a wall afterwards._

See [here](https://youtu.be/J998DmqMFzc?t=15s) or [here](http://mcmic.haxx.es/speedrun/supertux_iceinthehole.webm) at around 14 seconds.

**Comment by brmbrmcar** [comment]
I don't know the platform used on the second link.

**Comment by Hume2** [comment]
OK, this should be changed. Thanks for report.

**Comment by brmbrmcar** [comment]
I can pull request a fix, or you can do it.

**Comment by Hume2** [comment]
It would be better if I did it.

**Comment by brmbrmcar** [comment]
I did a version in it, but it has a small glitch.

**Comment by brmbrmcar** [comment]
That pull request should work...

**Comment by brmbrmcar** [comment]
I don't mean to be rude here, but the door method just looks horrible. The distance between them is too far, and the tiles look nasty.

**Comment by brmbrmcar** [comment]
The invisible blocks are badly placed, and the door is in a bad position. That style seems not fit in Icy Island. I don't want to rant, but it is worse that before in my opinion.

**Comment by Hume2** [comment]
Please go to the forum for such discussion.

**Comment by brmbrmcar** [comment]
Why has there been no improvement to that commit despite the community wanting an improvement?
