### ISSUE TITLE
menu.stl being installed as menu.stl.in

### ISSUE THREAD

**Issue by n3rdopolis** [SuperTux/supertux#394]
**master**
**System information:** *Linux, self compiled*

I am not sure why, but /opt/share/games/supertux2/levels/misc/menu.stl.in
I don't see anything interesting in the output for make install...

My compile options are 
cmake .. -DCMAKE_INSTALL_PREFIX=$INSTALLDIR -DCMAKE_PREFIX_PATH=$INSTALLDIR  -DGLBINDING_ENABLED=ON -DCMAKE_BUILD_TYPE=RELEASE

**Comment by tobbi** [comment]
This is weird. cmake should have configured that file https://github.com/SuperTux/supertux/blob/master/CMakeLists.txt#L651

**Comment by maths22** [comment]
Is  /opt/share/games/supertux2/levels/misc/menu.stl installed as well?  I'm going to fix up some of how we handle the data dir, so that should prevent menu.stl.in from getting installed in the future.

**Comment by brmbrmcar** [comment]
I actually had an issue like this with a nightly build, but I have deleted long ago.
