### ISSUE TITLE
Stacked Objects "Jitter"

### ISSUE THREAD

**Issue by LMH0013** [SuperTux/supertux#395]
Something has changed in how objects collide with each other.  This is evident when objects are stacked atop each other, as some of the objects are continually nudged up and down.  This is most prominent when stacking objects that Tux can carry such as rocks, trampolines, and lanterns (see attached test file).  If Tux is carrying something and drops it on top of another object directly in front of him you can reliably observe the effect.  This also occurs with scripted objects.  I am surprised this hasn't been already reported as it appears in 0.4.0 and causes myriad instances of ugly behavior.

[jitter_block.zip](https://github.com/SuperTux/supertux/files/191195/jitter_block.zip)

**Comment by sydneyjd** [comment]
I can verify this as well. I see it all over, and especially with stackable blocks.
I don't know how we missed this in 4.0, but we did...

 There is also an issue that every great oncei n a while when an egg comes out of its block and you hop onto the block it jitters and moves sporatically,  but im not sure if it is related. It is hard to reproduce.
-Sydney

**Comment by tobbi** [comment]
The issue is a Y velocity value of 15.625. This has also been the cause for the Tux jittering issue.

**Comment by tobbi** [comment]
Revision causing this bug is: 

[d311ef1f74f07080510a8675fc5c99cec37361ef] Fixed some collision-related bugs fixes #193 Fixes mantis #482, mantis #505 Partial fix of mantis #101

@Karkus476: Do you confirm?

**Comment by tobbi** [comment]
@Hume2: Since you wrote the code above, can you take a look?

**Comment by tobbi** [comment]
I had to back out my fix for causing unwanted behaviour.

**Comment by Hume2** [comment]
I have currently no idea how to fix this or whether this is actually fixable in the way we handle the collisions. Maybe I'll come with something later.

**Comment by HybridDog** [comment]
Maybe it's because of that: https://github.com/SuperTux/supertux/blob/ff4eff8b10b5ad80962689d427555a8b497d95f5/src/collision/collision_system.cpp#L303-L305

**Comment by weluvgoatz** [comment]
Rocks are very jittery, please fix
