### ISSUE TITLE
SuperTux crashes with "Not a valid Win 32 application" on Windows XP

### ISSUE THREAD

**Issue by tobbi** [SuperTux/supertux#396]
***Note:*** This was reported here: https://twitter.com/jakubtalich/status/708907822952669185

**SuperTux version:** 0.4.0
**System information:** *(details about your kernel, operating system, or distribution)*
Apparently: Windows XP

##### Expected behavior
SuperTux should work properly, even on Win XP

##### Actual behavior
SuperTux 0.4.0 crashes with "Not a valid Win 32 application" on Windows XP

##### Steps to reproduce actual behavior
Start SuperTux 0.4.0 on Win XP

**Comment by maths22** [comment]
We made the decision not to support Windows XP a while back.  If this error
occurs on other versions of Windows, I'll look into it, but I know that
Windows XP does not work, and will not ever work in the future.

**Comment by tobbi** [comment]
Alright! Thanks for the clarification. I probably forgot about the decision we made a while back. We should probably specify the supported OS variants on the download page.
