### ISSUE TITLE
Allow portable trampolines to be placed inside object bonus blocks

### ISSUE THREAD

**Issue by brmbrmcar** [SuperTux/supertux#399]
Currently, this is only possible with fixed ones. This would be useful where more than one trampoline would be needed to access something like a secret.

**Comment by brmbrmcar** [comment]
I believe this may be possible, but only when using a custom object.

**Comment by Hume2** [comment]
There's a bonusblock with a portable trampoline in the default tileset too, it's in the tilegroup "blocks" and looks like bonus block with a trampoline over it in the editor. It's the tile on the right of the fixed-trampoline-bonusblock. Here: http://imgur.com/TN73Tkb

**Comment by brmbrmcar** [comment]
I knew about that one. I'm talking objects. Scriptable ones.

**Comment by Hume2** [comment]
Setting the custom object to trampoline should work, I didn't tested it.

**Comment by brmbrmcar** [comment]
I know that... I mentioned it. I meant it should be used more easily.

**Comment by Hume2** [comment]
The contents are quite outdated. We can't have bazilion different contents, one for each type of object.

**Comment by brmbrmcar** [comment]
They were updated for air and earth powerup.

**Comment by brmbrmcar** [comment]
What would it be called in portable mode? trampoline-portable?

**Comment by Zwatotem** [comment]
Can this be closed?

**Comment by HybridDog** [comment]
> Can this be closed?

Yes, the bonus block already exists.
