### ISSUE TITLE
Moving platforms - behaviour bug

### ISSUE THREAD

**Issue by Narre** [SuperTux/supertux#401]
Tux's behaviour is different on object platforms, moving solid tiles, and moving unisolid tiles. It appears in both 0.4.0 and current version on branch master

Object platforms work fine, but moving tilemaps cause strange jumping behaviour of Tux.

https://youtu.be/bye-VqU7wGE

**Comment by HybridDog** [comment]
I think the second one looks best.

**Comment by tobbi** [comment]
I'm not sure if you still have the example level for this bug, but it would be great if you do, @Narre

**Comment by Narre** [comment]
Sorry for the late reply,
no, I don't have it anymore but I've quickly created another one so you can try for yourself, @tobbi 
[platform_test.zip](https://github.com/SuperTux/supertux/files/4466715/platform_test.zip)

The difference between the object and solid tiles is negligible, but the unisolid platforms should probably be looked into.

**Comment by tobbi** [comment]
Fixed by #1514
