### ISSUE TITLE
On the start screen, it states to see LICENSE rather than LICENSE.txt

### ISSUE THREAD

**Issue by brmbrmcar** [SuperTux/supertux#403]
**SuperTux version:**
SuperTux 0.4.0

Not a major issue, but it could cause confusion.

**Comment by Hume2** [comment]
I'm not sure about this, because Windows explorer doesn't show suffixes by default. However, I think, it should match anyway. Feel free to tell what you think.

**Comment by brmbrmcar** [comment]
It should be the same always. File viewers that don't show suffixes by default are silly and should not have to be dealt with.

**Comment by brmbrmcar** [comment]
It would also be useful if the file was also available under the top level directory of an install. Most people have never seen the source code.

**Comment by maxteufel** [comment]
So users get thousands of LICENSEs from all packages they've got installed in their `/usr`? We'd have many package maintainers complain.

It's the package maintainers responsibility for declaring a package's license, either through a license flag on the package itself (i.e. Arch's `license=('GPL')`) or installing the provided `LICENSE.txt` in the location appropriate for the distro (i.e. Arch's `/usr/share/doc/${package}/LICENSE`)

**Comment by Hume2** [comment]
I think that most of the people wouldn't read the license anyway and if still, they wouldn't understand it. It's pure administrative stuff, not anything for normal people.

**Comment by brmbrmcar** [comment]
The license is in a hard-to-reach location normally. You shouldn't have to understand the whole computer's file system to access the file. Why can't here just be on in data?

**Comment by maxteufel** [comment]
Because if it was, it would be unclear that the contents of the root would be GPL. Furthermore, it's enough for users to know it's GPL, they can just search for it on the internet.

**Comment by tobbi** [comment]
What about rewording it to "check the license file"?
