### ISSUE TITLE
Bonus Blocks and coins don't work

### ISSUE THREAD

**Issue by 165your4** [SuperTux/supertux#406]
**SuperTux version:** Latest Git revision
**OS:** Xubuntu 14.04

It seems that bonus blocks and coins don't work in the latest git revision. If Tux hits a bonus block from below, nothing happens - the block doesn't become empty and no powerup/coin comes out. Coins can't be collected either - it's as if they've been placed on the background layer rather than the interactive layer. This happens across every level I've tried.

**Comment by brmbrmcar** [comment]
This should be urgent priority. Can anyone else reproduce it? (I have not the space to compile SuperTux).

**Comment by Hume2** [comment]
Check out whether you don't have an outdated tiles.strf stuck somewhere in the userdir. Also what addons do you have installed?

**Comment by 165your4** [comment]
My tiles.strf is 100% up-to-date and I have no addons installed at all.

**Comment by Hume2** [comment]
And what everything do you have in your userdir?

**Comment by 165your4** [comment]
The only relevant things in my userdir were a bunch of old, outdated versions of Supertux. I removed them all, so the only tiles.strf file left on my computer was the current one, but the bug still persists.

**Comment by tobbi** [comment]
This *could* be an OS-specific issue, though I currently don't understand how something like that can be OS-specific. Does it work if you move your userdir to a backup location and let SuperTux re-create your settings and everything?

**Comment by Hume2** [comment]
@165your4 Is your data submodule up-to-date by the way? Use "git submodule update --init --recursive" and then "cmake .." again. If the bug is still here, then do:

1. Backup tiles.strf
2. Write "(((((" on the beginning, so you'll create errorous syntax.
3. Does SuperTux crash now?

**Comment by 165your4** [comment]
@Hume2 When I type "git submodule update --init --recursive" this comes up:

`fatal: reference is not a tree: ff3c57a24475655595e2cc8001e5d26b36db92df
Unable to checkout 'ff3c57a24475655595e2cc8001e5d26b36db92df' in submodule path 'external/tinygettext'`

And when I type "cmake ..":

`CMake Error: The source directory "/home/____/supertux3" does not appear to contain CMakeLists.txt.`

And, no that directory doesn't contain CMakeLists.txt, because my CMakeLists.txt is in _/home/____/supertux3/supertux_ - but that's exactly where I'm running these commands from, so why is it looking one folder up?

**Comment by Hume2** [comment]
I forgot to tell you that you should call the command "cmake .." inside the directory "build". And also type it after you change the tiles.strf. The submodules should check out in alphabetic order, so you must have checked out the data. Also try "git submodule sync".

**Comment by 165your4** [comment]
In the end I just reinstalled Supertux and the problem went away. Nevertheless, thanks @tobbi and @Hume2 for the help.
