### ISSUE TITLE
Compress add-ons using LZMA

### ISSUE THREAD

**Issue by tobbi** [SuperTux/supertux#409]
LZMA is way better than the ZIP algorithm in terms of smaller files. I recall us talking about using it. 

Of course, this change needs to be done for 0.5.0 to not break anything.

PhysFS can handle LZMA just fine!

**Comment by brmbrmcar** [comment]
The problem I see is that many systems cannot extract these files. This would make addons hard to make and edit.

**Comment by Hume2** [comment]
Well, the only archive that Windows can extract without 3rd-party software is .zip. Also we don't have so many addons so far, so we can recompress it ourselves.

**Comment by maxteufel** [comment]
Could we make it compatible for both types of archive?

**Comment by Hume2** [comment]
Also please let this decision for a meeting. I think, we should decide properly what all archives shall we support and not make on-spot decision, because the opinion about what is the most-suitable archive for us changes rapidly, as I've noticed.

**Comment by maths22** [comment]
@Hume2 I would agree that we should wait to decide on an archive format.
@maxteufel We almost certainly could do so, and I think adding that support can happen prior to a meeting.

**Comment by maxteufel** [comment]
Postponing this to after 0.5.0 since it was decided the editor should be the last major change to 0.5.0.

**Comment by Grumbel** [comment]
.zip isn't used because the most compressed, but because it's the most accessible. So no to this one, keep zip.
