### ISSUE TITLE
What's wrong with the Linux nightly builds?

### ISSUE THREAD

**Issue by tobbi** [SuperTux/supertux#410]
Hey, I am not really informed about our automatic build system. Sorry about that...

I just noticed that the linux nightly builds are behind 10 commits.

Any idea why?

I want translators to test the localizations I checked in.

**Comment by maths22** [comment]
Fixed for Debian/Ubuntu
Fedora fix on its way

**Comment by tobbi** [comment]
@maths22 While we're at it: What about the Windows nightlies? Last revision: 363.

**Comment by maxteufel** [comment]
This seems to be fixed (I guess Windows builds will also be fixed when we re-enable AppVeyor).
