### ISSUE TITLE
Should we enhance our worldmaps with RPG map symbols?

### ISSUE THREAD

**Issue by tobbi** [SuperTux/supertux#413]
There are some public domain RPG map symbols available here:
https://openclipart.org/search/?query=rpg%20map%20symbols

Do they fit our style? Should we use some of them (obviously only the friendly ones, not the gallows and stuff) to enhance our worldmaps?

**Comment by brmbrmcar** [comment]
Maybe they could be modified. They would then look good.

**Comment by tobbi** [comment]
In what way would you modify them?

**Comment by brmbrmcar** [comment]
They should probably be darkened slightly.

**Comment by 165your4** [comment]
They're a bit too clip-arty to be honest, and most of them are isometric, which doesn't really fit with the bird's eye view used in ST worldmaps.

**Comment by Hume2** [comment]
I think, the idea is good, but we need to redraw them. And yes, SuperTux worldmaps use another perspective.

**Comment by tobbi** [comment]
Maybe we should have a look at openclipart.org to find more suitable ones? They are all under CC0.

**Comment by 165your4** [comment]
> openclipart.org

looks great

can we add this one as a level icon???
![jesus-christ](https://cloud.githubusercontent.com/assets/8019640/15099871/42e6bce0-155a-11e6-8dfe-b7abb00a00a6.png)
https://openclipart.org/detail/194969/jesus-christ

**Comment by tobbi** [comment]
Uh, no?

Are you serious?

**Comment by 165your4** [comment]
Tobbi: i am serious i love jesus

i also think the icon should be as big on the worldmap as it is on this page

**Comment by tobbi** [comment]
I am sorry for all the religious folks out there, but I'd rather keep religion out of a game like this. I once had an issue similar to this one, with political signs.

**Comment by 165your4** [comment]
@Tobbi: it's fine, i was joking.

**Comment by tobbi** [comment]
I'm actually very relieved you were :)

**Comment by MarkkusCraft** [comment]
> They're a bit too clip-arty to be honest, and most of them are isometric, which doesn't really fit with the bird's eye view used in ST worldmaps.

@165your4 Yes. If we were to use these symbols, the design of the worldmaps would have to be redone. 

_Maybe we can stop the worldmaps from being *EVEN LAGGIER* than the levels themselves._
I'm kidding. We can live with that.

**Comment by tobbi** [comment]
I guess most of the RPG map symbols don't match our graphics style. I am closing this.
