### ISSUE TITLE
Do we want credits to be translatable?

### ISSUE THREAD

**Issue by tobbi** [SuperTux/supertux#414]
It is possible to translate credits. A pot file is created but not yet on transifex. 

I just tested the translation and it appears to be working.

Advantage is that people can understand even the credits (and the call for contributors at the end as well).

**Comment by brmbrmcar** [comment]
They should be translated.They weren't already? This seems ridiculous.

**Comment by tobbi** [comment]
@mt What Do you trink?

**Comment by Hume2** [comment]
I think, we should translate them.

**Comment by tobbi** [comment]
Credits are being translated now.
