### ISSUE TITLE
Jump key set to space, first level instructs otherwise

### ISSUE THREAD

**Issue by kneekoo** [SuperTux/supertux#417]
**SuperTux version:** supertux2 git.0.4.0
**System information:** Linux Mint 17.3 64-bit, kernel 4.2.0-35-generic
##### Expected behavior

Jump as instructed in the screenshot.
##### Actual behavior

The default jump key is "space".
![supertux2-jump-bug](https://cloud.githubusercontent.com/assets/566306/15152107/5f549066-16d4-11e6-8732-d5693d2fad42.jpg)

**Comment by brmbrmcar** [comment]
Isn't the default left/right/up/down now a/d/q/s now?

**Comment by kneekoo** [comment]
Fresh install, fresh config - not inherited from an older game version:
![supertux2-default-keys](https://cloud.githubusercontent.com/assets/566306/15158715/72d5971c-16f1-11e6-93fa-7de53f66460e.jpg)

**Comment by brmbrmcar** [comment]
OK, this should probably be fixed then. The only problem is that there is no easy way to handle every single keyboard arrangement in a picture.

**Comment by kneekoo** [comment]
How else can I help?

**Comment by 165your4** [comment]
@brmbrmcar we only have to cater to arrow key + space bar users. it is objectively the best way to play tux and everyone who uses wSAD (get it, cause its sad) is wrong

**Comment by brmbrmcar** [comment]
I don't use it! I was just mentioning that I thought it was the new default!

**Comment by maxteufel** [comment]
> it is objectively the best way to play tux and everyone who uses wSAD (get it, cause its sad) is wrong

You cannot objectively judge this. There's quite a few people using vi (and other applications) with the hjkl keys. Some even say that's the way they're able to type fastest.

The best way to fix this is to use the default keymap and add a note below that depending on the user's keymap, this might be different.

**Comment by 165your4** [comment]
i was joking... yet again

**Comment by weluvgoatz** [comment]
![billboard-backflip](https://user-images.githubusercontent.com/39805490/146723146-6bd21d06-2f61-4dcc-8947-d6bc79c6b5d4.png)

Does this suffice?
