### ISSUE TITLE
Change credits theme to Alligatoah - Du bist schön

### ISSUE THREAD

**Issue by tobbi** [SuperTux/supertux#418]
The current credits theme is not very meaningful, it being instrumental and everything.

I propose the following, more meaningful, credits theme: 
Alligatoah - Du bist schön

Although mainly catering to our German-speaking user base, the other people around the world will definitely like the tune.

Most important excerpt from the song lyrics:
Du bist schön, aber dafür kannst du nichts
Weder Lesen, noch Schreiben, noch was anderes
Du bist schön, aber dafür kannst du nichts
Du kannst nicht mal was dafür, dafür kannst du nichts

English translation:
You're beautiful, but totally incompetent.
You don't know reading, nor writing nor other things.
You're beautiful but totally incompetent.
It's not even your fault, you don't know stuff.

Youtube video: https://www.youtube.com/watch?v=dlvStoOyEzE

**Comment by brmbrmcar** [comment]
Is this a joke?

1. It is copyrighted.
2. How will it be done anyway?
3. I hate the tune, like a lot of other people.
4. The lyrics are not suited to the credits.

Just keep it instrumental. I'd like a less depressing piece of music, but not like this...

**Comment by tobbi** [comment]
> Is this a joke?

Very obviously!

**Comment by brmbrmcar** [comment]
Why so many joke issues on here?

**Comment by tobbi** [comment]
I only count 2: My Schroedinger's Box PR and this.

**Comment by 165your4** [comment]
i propose we make it this:
https://www.youtube.com/watch?v=2dbR2JZmlWo
(not safe for work, or home really)

**Comment by brmbrmcar** [comment]
That was too far.
