### ISSUE TITLE
Unfitting / Inappropriate sound when tux catches an egg

### ISSUE THREAD

**Issue by cbungau** [SuperTux/supertux#419]
**SuperTux version:**
0.4.0
**System information:** *(details about your kernel, operating system, or distribution)*
MacOSX 10.11  &  Ubuntu 16.04 (64bit)
##### Expected behavior
Tux used to make a sound (in the distant past) “Excellent” when it caught a magnifying snowball. Then it made a happy “wee-pee or similar” sound after the same snowball encounter. 
##### Actual behavior
But now there is no sound from Tux when the snowball is caught (just the background music of the given level). This happens both on my MacOSX 10.11, as well as on my Ubuntu 16.04 (64-bit). I used the standard installers, not the source code… so I did not compile any source code...

**Comment by brmbrmcar** [comment]
By snowball, do you mean the egg powerup?

**Comment by Hume2** [comment]
Apparently you mean the egg. When you turn off musics in the settings and you let sounds being on, do you hear any sound then? The sound was changed in 0.3.3.

**Comment by 165your4** [comment]
I say we bring back the "excellent" sound, but make the volume 500% louder.

**Comment by brmbrmcar** [comment]
But it becomes hard if you don;t know what excellent means.

**Comment by cbungau** [comment]
OK, egg powerup then... it did look to me like a large snowball...

I can confirm that even if I turn off the music, but leave the sound on, there is no sound when the egg powerup is caught...

Bringing back the "excellent" sound would be great...

**Comment by Hume2** [comment]
When you play the sound separately in data/sounds/grow.ogg, do you hear anything?

**Comment by cbungau** [comment]
It is a short about 1 second sound which I can indeed here during the game when the egg power up is caught. It's not easy to describe, certainly not a sound tux would make or a word, it is similar to a water going down the drain maybe, a short sound anyway. And as I said, the sound is played fine during the game at the corresponding moments. And it is a good sound choice to describe the "growing in size" effect. But Tux opens his "mouth" as if trying to say something like "whee..." for example. That sound is missing...

**Comment by maxteufel** [comment]
@cbungau: You seem to be talking about <https://raw.githubusercontent.com/SuperTux/data/e5c8d87fb9b1b3773580787579743875edf12824/sounds/grow.ogg>.

**Comment by cbungau** [comment]
@maxteufel - well, that was the sound I was asked to listen to by @Hume2 (see above)

**Comment by maxteufel** [comment]
@cbungau: No, it is different from the current sound (<https://raw.githubusercontent.com/SuperTux/data/master/sounds/grow.ogg>).

**Comment by Hume2** [comment]
@cbungau Then please don't say "no sound", when you mean "unappropriate sound", when you can hear the sound and you think that there should be another sound. I don't know about audio much, but it seems like there was a reason to change this.

**Comment by brmbrmcar** [comment]
Can the title be changed to Inappropriate sound when Tux catches egg?

**Comment by Hume2** [comment]
Yes, I'm just not sure whether it's really this.

**Comment by brmbrmcar** [comment]
Why no needs information or similar labels?

**Comment by cbungau** [comment]
@Home2 Point taken... Sorry, I meant "no sound comes out of Tux mouth which if you look closely moves as if Tux is saying something, but no appropriate sound is produced, hence the no sound label. The "growing" sound is there, as well as the background melody...

Sorry to make so much fuss about this, please feel free to close this issue - I can live perfectly with the way things are at the moment - great game overall...

**Comment by maxteufel** [comment]
I'll close this since it seems to be silly to discuss where from this sound originates and whatever. If the sound indeed annoys more people, we can consider reopening this issue - but not now.

**Comment by Hume2** [comment]
Also there's the forum for discussing this kind of stuff.

**Comment by cbungau** [comment]
The sound does not annoy me or anyone else. The sound is MISSING...

There is the background melody, fine, and there is the growing sound, fine, but Tux used to say Yuppie!!! when going up in size, but now no sound is produced. Before Yuppie there was the "Excellent" sound, also gone/missing now...

Tux moves the mouth as to say Yuppie, but the Yuppie sound is missing.

Probably too complicated, so forget it...

**Comment by Hume2** [comment]
Please use the forum for such discussion.
