### ISSUE TITLE
Forest Improvements

### ISSUE THREAD

**Issue by 165your4** [SuperTux/supertux#422]
I've improved a bunch of forest levels, removing ugliness and adding some new stuff where appropriate. I also added some forest tiles/backgrounds that were previously missing, because you can never have enough tiles.

To install, you just have to extract the .zip file below into supertux/data.
[improvements.zip](https://github.com/SuperTux/supertux/files/276472/improvements.zip)

**Comment by tobbi** [comment]
Can you create a pull request to the data repository?

**Comment by 165your4** [comment]
ok, just a second

**Comment by maxteufel** [comment]
In that pull request, please also describe details of the changes.
