### ISSUE TITLE
Errors in the tiles.strf file

### ISSUE THREAD

**Issue by 165your4** [SuperTux/supertux#423]
I accidentally messed up the tiles.strf file with my "Forest improvements" commit. I'm a bit too busy to make a pull request right now, but I've attached a fixed version that actually works.
[tiles.zip](https://github.com/SuperTux/supertux/files/278053/tiles.zip)

**Comment by tobbi** [comment]
Is this a duplicate of Supertux/data#9 ?

**Comment by brmbrmcar** [comment]
It was designed to fix this issue.

**Comment by maxteufel** [comment]
Fixed by SuperTux/data#9 or SuperTux/data@d637b48210839796f078ee4cecd8fec80ca597c1.
