### ISSUE TITLE
Glitchy r6694 Level Editor

### ISSUE THREAD

**Issue by IndianaTux** [SuperTux/supertux#428]
I have SuperTux 0.4.0, r6694-fixed level editor, Windows 7 64bit and the level editor glitches up so much that I can't even use the level editor. It's hard to explain so I made a screen capture (GitHub doesn't accept mp4 so the mp4 is in the .zip file).
[test1.zip](https://github.com/SuperTux/supertux/files/292365/test1.zip)

**Comment by Hume2** [comment]
Please, report the issue to the correct repository.
Moved to https://github.com/SuperTux/supertux-editor/issues/4
