### ISSUE TITLE
Butt jump sprites don't look quite right

### ISSUE THREAD

**Issue by MrNonSequitur** [SuperTux/supertux#429]
**SuperTux version:** 0.40
The sprite for butt jump looks odd upon close inspection; there's a big uniform patch of grey on tux's bottom that isn't in any of the other sprites. Furthermore, he loses his tail (though it would look strange to keep the tail).

Also, the butt jump sprite for big tux has angry red eyes, while other tuxes (like fire tux) do not.
![buttjump-0](https://raw.githubusercontent.com/SuperTux/data/d637b48210839796f078ee4cecd8fec80ca597c1/images/creatures/tux/fire/buttjump-0.png)![buttjump-0](https://raw.githubusercontent.com/SuperTux/data/d637b48210839796f078ee4cecd8fec80ca597c1/images/creatures/tux/big/buttjump-0.png)

**Comment by maxteufel** [comment]
Postponing this to after 0.5.0 release since this is a minor change.

**Comment by brmbrmcar** [comment]
What if someone has the fixes? I don't see how it would take much time to merge a pull request.

**Comment by maxteufel** [comment]
@brmbrmcar Go ahead if you want to fix! :+1:

**Comment by brmbrmcar** [comment]
How about the below?
![buttjump-0](https://cloud.githubusercontent.com/assets/14400196/15806770/2aa44a90-2b43-11e6-8e12-3df6ba461b5c.png)![buttjump-0](https://cloud.githubusercontent.com/assets/14400196/15806746/a95499a4-2b42-11e6-9b15-a8d96ece9fa6.png)

**Comment by maxteufel** [comment]
@brmbrmcar can you make a pull request on the SuperTux/data repository?

**Comment by brmbrmcar** [comment]
OK, I'll just set up git...

**Comment by maxteufel** [comment]
@brmbrmcar If you'd like to avoid that, I'll open a pull request

**Comment by brmbrmcar** [comment]
OK, I'm setting it up anyway, so I think I can do it...

**Comment by brmbrmcar** [comment]
Actually, can you? I stupidly copied over whole folders to up date, and git saw it, so now it says there are about ten files changed when they are the same and I cannot go back.
