### ISSUE TITLE
SuperTux Death sound is too jaring

### ISSUE THREAD

**Issue by Grumbel** [SuperTux/supertux#43]
Original [issue 32](https://code.google.com/p/supertux/issues/detail?id=32) created by SuperTuxTeam on 2013-11-09T19:43:03.000Z:

I find that the death sound is quite loud and startling. 

In 0.3.4, it was improved as there is a separate &quot;hurt&quot; sound.

I modified the hurt sound, playing around with it in Audacity.

I attached my candidate as a wav file, and my Audacity project

Attachments:
- [kill.tar](https://storage.googleapis.com/google-code-attachments/supertux/issue-32/comment-0/kill.tar)
- [kill.wav](https://storage.googleapis.com/google-code-attachments/supertux/issue-32/comment-0/kill.wav)

**Comment by Hume2** [comment]
It resembles me playing SuperTux on my old laggy computer.

**Comment by Karkus476** [comment]
I think it is startling at times too. It would be nice if it were something less sudden.

**Comment by sydneyjd** [comment]
Is this a wontfix? We could try to fix it if someone could find/make a new kill sound.

**Comment by n3rdopolis** [comment]
I tried to make my own sound, and posted it on the first google code page that's linked... I guess it wasn't accepted though.

**Comment by qubodup** [comment]
The current sound is too loud. The suggested sound in the original post is too loud as well.

It appears that it is policy to normalize all sounds. Unless this is changed, it appears that solving this issue will require implementation of volume settings for individual sound files, similar to the lisp `.music` files for music.

**Comment by makeamericagreatagain** [comment]
America is great.

**Comment by weluvgoatz** [comment]
We should *maybe* change the death sound to Tux yelling "Noooooo" or Tux screaming (cutely).
