### ISSUE TITLE
Frozen Mole Bug

### ISSUE THREAD

**Issue by IndianaTux** [SuperTux/supertux#430]
SuperTux 0.4.0
Windows 7 64-bit
If you jump on a frozen mole there is a half-tile amount of space between the mole and Tux. 
![bluecanon 002](https://cloud.githubusercontent.com/assets/16748782/15730348/d5440c40-2839-11e6-962e-7d442abaf6e6.JPG)

**Comment by brmbrmcar** [comment]
It seems to be a sprite issue. I will try to fix it.

**Comment by brmbrmcar** [comment]
I'm sorry, but I am seemingly unable to fix it... :(

**Comment by IndianaTux** [comment]
It's alright if the bug doesn't fix. But here is an idea, the mole can become squish-able when it's frozen then the bug will be fixed.

**Comment by Y-st** [comment]
What if the frozen mole sprite was encased in ice? The ice could be high enough to meet Tux's feet.

**Comment by brmbrmcar** [comment]
Well, there is no picture for the frozen mole. Even that seems not to work.

**Comment by IndianaTux** [comment]
Making the mole unfreezable would not be logical since other forest enemies can get frozen. To bad Y-st's idea doesn't work. What about my idea, does it work?

**Comment by tobbi** [comment]
The game assumes the complete height of the mole (aka, when the mole emerged completely).

**Comment by Savsish** [comment]
Actually the mole and ice flowers weren't supposed to be in 0.4.0 release (considering that a lot of stuff was removed for 0.3.0 unstable release) but i surprised how these experimental features got into 0.4.0 and the developers mostly likely forgot to remove them for this stable release.

**Comment by brmbrmcar** [comment]
Why does the visible size of the mole increase anyway?

**Comment by Y-st** [comment]
The visible size increases because the mole comes up out of the hole.

It would take an engine change, but maybe the solution is to add either an option that allows an enemy to specify what frame needs to be frozen (allowing the mole to freeze in the emerged position) or specify a collision box to use when frozen (so that the hill is the part stood on).

**Comment by maxteufel** [comment]
```
16:00:03 <@maxteufel> Make the mole visible as-is when it's out of the hole, and freeze it in that status
16:00:19 <@maxteufel> that also makes it easier to see the mole is frozen
16:00:43 <@maxteufel> and it's a nice way to fix the issue without much coding stuff
```

What do you think?

**Comment by brmbrmcar** [comment]
I think it should freeze at where the mole is. I believe it is a general backend bug with automatic freezing.
