### ISSUE TITLE
Icecrusher Bug

### ISSUE THREAD

**Issue by IndianaTux** [SuperTux/supertux#431]
SuperTux 0.4.0
Windows 7 64-bit

Once the icecrusher hits the ground throwing a portable rock on the icecrusher and after removing it the icecrusher doesn’t go back up and return to normal behavior.  
The icecrusher should go back up and return to normal behavior after removing the portable rock on top of it. (By portable rock I mean those blocks in 'Tux The Builder' level.)

**Comment by maxteufel** [comment]
@IndianaTux do you know a level where we can test this behavior easily?

**Comment by Hume2** [comment]
This happens since I fixed #173 . Therefore only one of those bugs can be fixed at once. In my opinion, the reason of #173 is poor level design and therefore should not be considered as a code bug.

**Comment by maxteufel** [comment]
@Hume2: :+1:, let's fix the level design than breaking this stuff.

**Comment by IndianaTux** [comment]
If you still need a level to test this bug there is Decrepit Castle in Mattie's world. I also found out that this behavior can also occur in mid-air (the icecrusher gets stuck in mid-air).

**Comment by maxteufel** [comment]
At the meeting (see #435), it was decided that this should be resolved as @Hume2 suggested. Revert the fix for #173. Additionally, the level design guidelines should be updated to make it clear for level designers not to use this kind of poor level design.
