### ISSUE TITLE
[Community issue] brmbrmcar's perceived authority of the SuperTux team

### ISSUE THREAD

**Issue by tobbi** [SuperTux/supertux#439]
From the previous discussion:

**Tobbi**
@brmbrmcar We have made a team decision to block you, unless you immediately stop getting on our nerves. We are not against you, so stop complaining about the perceived fact. If you want to work on SuperTux properly, then tell me and stop the tomfoolery. Furthermore, your overuse of Github emotions is getting annoying. Yes, we use emotions for fun as well, but in contrast to you, we work on SuperTux properly.

All you do is make a load of joke issues anyway. Go on, block me!
**brmbrmcar**

**Comment by tobbi** [comment]
Okay, let's continue the discussion here...

**Comment by tobbi** [comment]
Yes, we do make joke issues, but only a few, and I think I have granted myself that right when 95% of the work I put into SuperTux is meant seriously.

**Comment by tobbi** [comment]
Also, previously:
**brmbrmcar**
As for the rule "No discussion of topics not included in the final meeting agenda," it shows how unfair the system on #supertux is. Someone else might, in the discussion, want to discuss a new idea they want whilst in there.

**Comment by tobbi** [comment]
Okay, so that rule is not meant to be too strict, I think. It's only a guideline. The thing is: We decided that 0.5.0 will contain the editor, that is the most mature of the features we worked on...

**Comment by maxteufel** [comment]
I'd say that rule should be mostly enforced (as long as it's not at the end of the meeting when nothing else is to be discussed). This is not a community meeting, but a release preparation meeting.

**Comment by tobbi** [comment]
As per second comment on https://www.youtube.com/watch?v=N2xcHsfTRI4 

"THE FIGHT: https://github.com/SuperTux/supertux/issues/439﻿"

I assume that @brmbrmcar is not willing to participate further in this discussion.

Fine with me, I have given you the chance. Closing.
