### ISSUE TITLE
Compile miniswig files with modern C++ support

### ISSUE THREAD

**Issue by tobbi** [SuperTux/supertux#442]
We're currently compiling our miniswig stuff with old C++ support. Thus, we get warnings during compilation.

This should be changed.

Unfortunately, I don't know enough about CMake to make the changes myself.

**Comment by tobbi** [comment]
@maths22 You know more about CMake than I do. Can you please take a look?

**Comment by maths22** [comment]
Fixed in commit fbbda1f
