### ISSUE TITLE
Problems with compiling on Windows

### ISSUE THREAD

**Issue by BlaCoiso** [SuperTux/supertux#443]
**SuperTux version**: 0.4.0-677-g8f727f5 editor branch
**System information:** Windows 10 64-bit with Visual Studio 2015 Community Edition

##### Expected behavior
The game executable would run.

##### Actual behavior
The game executable doesn't run and it says sqstdlib.dll, squirrel.dll and physfs.dll are missing.

##### Steps to reproduce actual behavior
Compile the game on the compiler mentioned above.

**Comment by Hume2** [comment]
Did you try to download and install these dlls?

**Comment by BlaCoiso** [comment]
Well, when I compile supertux, squirrel and physfs get compiled but instead of being linked to the "supertux2.exe" executable, they get compiled into separate dlls and don't go to the main folder (/build/Release)

**Comment by BlaCoiso** [comment]
So the current workaround is to go to these folders and copy the files to the main build folder and then I can run it.

**Comment by maxteufel** [comment]
@maths22 any updates?

**Comment by maths22** [comment]
Resolved in 8fc41bb0d9357b87d4d5e2f3928d3980e01a50e2
