### ISSUE TITLE
Crash of editor branch: Missing  'images/engine/editor/objects.stoi'  

### ISSUE THREAD

**Issue by giby** [SuperTux/supertux#450]
**SuperTux version:**
Last editor branch
**System information:** 
OSX 10.11.5 (15F34)
MacBook Pro (Retina 13 pouces, début 2015)

##### Expected behavior
Not crashing
##### Actual behavior
crach
##### Steps to reproduce actual behavior
Turn on ST and choose level editor, then it crash 
##### Additional debugging information

Eventually something useful is asked! 

Last login: Sat Jun 18 21:37:08 on ttys001
Machin-chose-de-Benjamin:build benjamin$ ./supertux2 
[WARNING] /Users/benjamin/Code-source/supertux/src/video/texture_manager.cpp:201 Couldn't load texture '/images/engine/editor/rubber.png' (now using dummy texture): Couldn't open '/images/engine/editor/rubber.png': not found
[WARNING] /Users/benjamin/Code-source/supertux/src/video/texture_manager.cpp:201 Couldn't load texture '/images/engine/editor/select-mode0.png' (now using dummy texture): Couldn't open '/images/engine/editor/select-mode0.png': not found
[WARNING] /Users/benjamin/Code-source/supertux/src/video/texture_manager.cpp:201 Couldn't load texture '/images/engine/editor/move-mode0.png' (now using dummy texture): Couldn't open '/images/engine/editor/move-mode0.png': not found
[WARNING] /Users/benjamin/Code-source/supertux/src/video/texture_manager.cpp:201 Couldn't load texture '/images/engine/editor/settings-mode0.png' (now using dummy texture): Couldn't open '/images/engine/editor/settings-mode0.png': not found
[FATAL] /Users/benjamin/Code-source/supertux/src/supertux/main.cpp:504 Unexpected exception: Couldn't open file 'images/engine/editor/objects.stoi': not found

*If available, please attach a backtrace of a crash (you can get one using GDB or another debugger), or a core dump. If you're on GNU/Linux and your distro is using systemd, it's highly likely that a core dump is available using `coredumpctl(1)`.
If the issue only occurs in a custom level, please attach that too.*

##### Guidelines for reporting issues

- [ ] I have read <https://github.com/SuperTux/supertux/blob/master/CONTRIBUTING.md#bug-reports>.
- [ ] I verified this isn't an issue that's already been reported.
- [ ] This report only includes details about **one** (1) issue, feature request or topic.
- [ ] If I make a mistake while submitting this report I will use the edit feature instead of closing this issue and opening a new one.
- [ ] This issue is **not** about wrong translations (use Transifex for those), or anything unsupported (e.g. third-party add-ons).
- [ ] Once you're done, please remove the section 'Guidelines for reporting issues', the 'Additional debugging information' if it is empty, and any text in *italic font*.

**Comment by maxteufel** [comment]
You haven't read the guidelines for reporting issues.

**Comment by Hume2** [comment]
git submodule update --init --recursive
