### ISSUE TITLE
Generic Linux (nightly) builds

### ISSUE THREAD

**Issue by brmbrmcar** [SuperTux/supertux#451]
I was told to put this here.

Basically, I cannot get the Windows builds in Wine to work, with some Wine error, which seemed unhelpful. The Ubuntu packages all wanted some other dependency to run.

I would like to see a working generic Linux binary with all dependencies on there.

**Comment by brmbrmcar** [comment]
I got the Wine one working!

**Comment by tobbi** [comment]
Great, me too. Can this be closed?

**Comment by maxteufel** [comment]
@tobbi No, generic Linux builds are actually a valid issue.

**Comment by maxteufel** [comment]
Ref: #648 ("Please provide an AppImage for SuperTux")

**Comment by maxteufel** [comment]
A preliminary test build is now available at <https://transfer.sh/ajpum/SuperTux_2-v0.5.0-230-g8aa1f1766-glibc2.14.glibc2.14-x86_64.AppImage> (SHA256: 74d1b981d87d06362d0df786aa90b198582257f1e583aeb4f5d639603334a4a2). Please note that this link will expire in about two weeks.
