### ISSUE TITLE
In-game Level Editor Game Crash 

### ISSUE THREAD

**Issue by IndianaTux** [SuperTux/supertux#454]
SuperTux 0.4.0.725 Nightly Build
Windows 7 64-bit
The game crashes whenever I click something in the level editor menu. The bug freezes then closes the game. This bug doesn't occur so often.

**Comment by Hume2** [comment]
What do you click? Also what do you imagine by the "level editor menu"?

**Comment by IndianaTux** [comment]
The bug mostly occurs when I click level subset properties and when choosing a tilegroup.

**Comment by Hume2** [comment]
I can't reproduce this issue. I just needed to know that you mean the sidebar on the right, because everyone can use another terminology.

**Comment by IndianaTux** [comment]
I meant the main menu, when first entering the level editor I chose a level subset then clicked level subset properties right under the create level button resulting the bug.

**Comment by Hume2** [comment]
Got what you mean. Now I can reproduce it.

**Comment by tobbi** [comment]
0   libc++.1.dylib                	0x00007fff9d30d254 std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::basic_string(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) + 4
1   supertux2                     	0x000000010b1c996c World::get_basedir() const + 28 (world.cpp:163)
2   supertux2                     	0x000000010b04729b EditorLevelsetMenu::EditorLevelsetMenu() + 955 (editor_levelset_menu.cpp:42)
3   supertux2                     	0x000000010b047bd5 EditorLevelsetMenu::EditorLevelsetMenu() + 21 (editor_levelset_menu.cpp:51)
4   supertux2                     	0x000000010b067526 MenuStorage::create(MenuStorage::MenuId) + 7558 (menu_storage.cpp:148)
5   supertux2                     	0x000000010ae64d17 MenuManager::push_menu(int) + 71 (menu_manager.cpp:250)
6   supertux2                     	0x000000010ae388cb ItemGoTo::process_action(MenuAction) + 123 (item_goto.cpp:37)
7   supertux2                     	0x000000010ae4a545 Menu::process_action(MenuAction) + 1013 (menu.cpp:392)
8   supertux2                     	0x000000010ae4bcac Menu::event(SDL_Event const&) + 620 (menu.cpp:543)
9   supertux2                     	0x000000010ae644d9 MenuManager::event(SDL_Event const&) + 249 (menu_manager.cpp:195)
10  supertux2                     	0x000000010b16a953 ScreenManager::process_events() + 163 (screen_manager.cpp:243)
11  supertux2                     	0x000000010b16c4a0 ScreenManager::run(DrawingContext&) + 368 (screen_manager.cpp:418)
12  supertux2                     	0x000000010b01c405 Main::launch_game() + 12773 (main.cpp:442)
13  supertux2                     	0x000000010b01cef7 Main::run(int, char**) + 1111 (main.cpp:498)
14  supertux2                     	0x000000010ad3d499 main + 41 (main.cpp:23)
15  libdyld.dylib                 	0x00007fff901145ad start + 1
