### ISSUE TITLE
Invisible walls no longer work

### ISSUE THREAD

**Issue by brmbrmcar** [SuperTux/supertux#459]
Don't start at me for this.

Where there is one of those black invisible wall objects, Tux now falls straight through them.

**Comment by maxteufel** [comment]
Can't reproduce this. Test level?

**Comment by brmbrmcar** [comment]
I've got http://paste.ubuntu.com/17900884/. With some of my other levels, Tux and other objects just fall through.

**Comment by maxteufel** [comment]
What revision are you using?

**Comment by brmbrmcar** [comment]
718 in the Nightlies 32 bit in Wine.

**Comment by maxteufel** [comment]
@brmbrmcar can you reproduce it with the current nightlies (729)?

I can't, even, with your test level.

**Comment by brmbrmcar** [comment]
OK, I'll try later.

**Comment by brmbrmcar** [comment]
The bug still occurs.

**Comment by Hume2** [comment]
I can't reproduce this as well.

**Comment by brmbrmcar** [comment]
It is reproducible with http://paste.ubuntu.com/17904494/?

**Comment by maxteufel** [comment]
It works as expected.

**Comment by brmbrmcar** [comment]
OK. For me everything falls, the same with the older build, but not 0.4.0.

**Comment by tobbi** [comment]
Screencast this, please.

**Comment by brmbrmcar** [comment]
https://www.youtube.com/watch?v=vEimMYkGblI

**Comment by qwertychouskie** [comment]
Maybe it is a Windows-only bug?  Or maybe a Wine bug?

**Comment by brmbrmcar** [comment]
It doesn't happen  for me any more. I till think it is valid, though.

**Comment by tobbi** [comment]
If it doesn't happen anymore, what makes you say it is still valid?

**Comment by brmbrmcar** [comment]
Because it could still occur, and it seemed random as only I could reproduce it.

**Comment by tobbi** [comment]
Can we decide on closing the issue and you can reopen it (or tell us here) if it still occurs?
