### ISSUE TITLE
Editor: specify exact version of default CC-BY-SA

### ISSUE THREAD

**Issue by maxteufel** [SuperTux/supertux#461]
Editor should specify an exact version of the CC-BY-SA license it proposes, now preferably [CC-BY-SA 4.0 International](https://creativecommons.org/licenses/by-sa/4.0/legalcode).

**Comment by brmbrmcar** [comment]
It should be like the C# editor, where it explains that it allows sharing and modification of the level.

**Comment by maxteufel** [comment]
Indeed. It should say what it allows, say that user should review it exactly, and then change it if they don't agree with that.
