### ISSUE TITLE
In-game level editor crash with some ambient objects

### ISSUE THREAD

**Issue by IndianaTux** [SuperTux/supertux#462]
SuperTux 0.4.0.731 Nightly Build
Windows 7 64-bit

I placed an ambient object (secret area) on a level then erased it and without moving the cursor I clicked on it again which led to freezing and crashing the game. The same thing happens with some other ambient objects.

**Comment by Hume2** [comment]
Try whether https://github.com/SuperTux/supertux/commit/36be0363034a09214906bf2a092f3c8a01d2e5c5 hasn't fixed it by chance

**Comment by IndianaTux** [comment]
The bug doesn't happen anymore with any ambient object.

**Comment by Hume2** [comment]
OK, thanks for report, closing.
