### ISSUE TITLE
Object attributes

### ISSUE THREAD

**Issue by maxteufel** [SuperTux/supertux#464]
Use bitwise operations to create object attributes - instead of using variables and enums.

**Comment by HybridDog** [comment]
What are object attributes used for?

**Comment by Semphriss** [comment]
What is the idea and how would it be executed? The way I understand it now would make maintenance much harder...

**Comment by tobbi** [comment]
I can't make sense of this. @maxteufel Do you remember what you meant by this?

**Comment by mrkubax10** [comment]
@tobbi We already have something like this, it is called `RegisteredObjectParam`: https://github.com/SuperTux/supertux/blob/master/src/supertux/object_factory.hpp#L52. It is used for querying objects by certain parameter.

**Comment by tobbi** [comment]
I'm gonna close this preliminarly. Once OP reappears, we can re-open.
