### ISSUE TITLE
Should other forest badguys burn when they run into one that's already burning?

### ISSUE THREAD

**Issue by J-128** [SuperTux/supertux#467]
Because forest badguys burn, it seems to me that other (forest) badguys should burn when they run into a burning one, much the same way that bombs used to work in Milestone 1. What do you think?

**Comment by Hume2** [comment]
This would make the fire flower far more overpowered than it is now.

**Comment by J-128** [comment]
Hmm... That is true. I didn't think of that.

**Comment by maxteufel** [comment]
The flame (and generally all flames) could hurt Tux.

**Comment by J-128** [comment]
Good idea!

**Comment by Hume2** [comment]
Well, the levels aren't designed for this, so this might break current levels.

**Comment by maxteufel** [comment]
This doesn't really make sense for now. Enabling burning animations didn't really change anything to the gameplay and behavior, while this does, in a rather extreme way. Closing for now until someone brings up a good reason to add this behavior.
