### ISSUE TITLE
In-game level editor crash with ItemIntField

### ISSUE THREAD

**Issue by IndianaTux** [SuperTux/supertux#470]
SuperTux 0.4.0.733 Nightly Build (win32.msi version)
Windows 7 64-bit
If you type in a number that has 11 digits or more into the count of a bonus block the game will crash.

**Comment by tobbi** [comment]
@Hume2 Integer overflow. Please check numbers against +- INT_MAX.

**Comment by Hume2** [comment]
I'll fix that.
I just changed the title to make it more obvious, I know that you couldn't know how to name it correctly.
