### ISSUE TITLE
Problems with CMake 3.4 and Visual Studio 2015 on Windows 7

### ISSUE THREAD

**Issue by Savsish** [SuperTux/supertux#472]
Since  3edbfc30c600a94d1c141bbb039a88378458803c when i try to configure supertux with CMake 3.4 and Visual Studio 2015, CMake throws some errors messages:

`CMake Error at CMakeLists.txt:247 (GET_FILENAME_COMPONENT):`
  `get_filename_component called with incorrect number of arguments`

`CMake Error at CMakeLists.txt:255 (LIST):`
  `list index: 2 out of range (-2, 1)`

`CMake Error at CMakeLists.txt:256 (LIST):`
  `list index: 3 out of range (-2, 1)`

However if i comment or remove these lines, it configures just fine.

**Comment by tobbi** [comment]
Did the syntax of get_filename_component change since 3.4? Do we require a new minimum post-3.4?

**Comment by maths22** [comment]
I'll fix this, and no, the syntax did not change, but I need better if clauses.

**Comment by tobbi** [comment]
Thanks!

**Comment by maths22** [comment]
Fixed in 3c2187324c100c03316e7452deb4b4761d63deb6
