### ISSUE TITLE
Sleeping Spikeys don't melt when hit with a fireball

### ISSUE THREAD

**Issue by J-128** [SuperTux/supertux#476]
While playing SuperTux, I noticed this problem. The sleeping spikeys used to melt when you hit them with a fireball, but they don't anymore. 
I use the latest git version of SuperTux.

**Comment by maxteufel** [comment]
This is intended behavior, introduced in SuperTux/supertux@2580bf128a0664f896e9b7ea5768c4d6109eaab6 in order to fix issue #315.
