### ISSUE TITLE
Worldmaps should have unique filenames

### ISSUE THREAD

**Issue by Savsish** [SuperTux/supertux#477]
Currently worldmaps are all named worldmap.stwm. Would be nice if worldmap files have unique filenames e.g. world1.stwm, bonusisland1.stwm, bonusisland2.stwm etc.

**Comment by maxteufel** [comment]
For what reason?

Also, worldmaps can have names different from `worldmap.stwm`. However, upon opening an add-on, `worldmap.stwm` is expected. In any case, compatibility for this behavior won't be dropped.

**Comment by maxteufel** [comment]
@Savsish I hope you realize we see when you edit stuff. You could just post that in a comment, too. Otherwise people are going to miss it anyway.

**Comment by Savsish** [comment]
Notice that this change is present in 0.1.3 release but not in current development versions.

**Comment by maxteufel** [comment]
That's not a reason.

If we changed this, how would we figure out where to find the worldmap? We'd have to look up its filename in another file, with a pre-defined filename.

**Comment by BlaCoiso** [comment]
@maxteufel Maybe if the worldmap had the same name as the folder, so a worldmap in the folder "world123" would be called "world123.stwm"

**Comment by Hume2** [comment]
This is completely redundant, since the worldmap name doesn't affect game functionality in any way.

Please, put community ideas to the forum. Pull-requests with implementation are OK. You should visit our forum at: http://forum.freegamedev.net/viewforum.php?f=66&sid=7d271ca537028e81027e0b3cdab4f0ca
