### ISSUE TITLE
Burned fishes (and possibly snails) re-appear after some time

### ISSUE THREAD

**Issue by maxteufel** [SuperTux/supertux#488]
**SuperTux version:** master, as of 2016-07-16

##### Expected behavior
Burned fishes and snails don't re-appear.

##### Actual behavior
Burned fishes (and possibly snails) re-appear.

##### Steps to reproduce actual behavior

1. Use an appropriate level (e.g. "Bouncy Coils" for the fishes)
2. Burn some fishes
3. Leave the area so that the place where they were disappears from screen
4. Wait a bit (dunno how long, but about 30 to 60 seconds)
5. Re-enter that area
6. Burned fishes should be visible again

**Comment by maxteufel** [comment]
Working on this now.

**Comment by tobbi** [comment]
Shouldn't the code rather be in one of the cases in Badguy::ignite()?
