### ISSUE TITLE
Problems with the editor 0.3.4

### ISSUE THREAD

**Issue by Grumbel** [SuperTux/supertux#49]
Original [issue 38](https://code.google.com/p/supertux/issues/detail?id=38) created by SuperTuxTeam on 2014-05-10T01:12:52.000Z:

Hi SuperTux Team, I'm Pedro Cuadra again, I've been reviewing editor 0.3.4 with the latest version of Mono. At first, all good (first image), but when I open or make a new level, the editor remains as in the second image.

Attachments:
* [problem3.png](https://storage.googleapis.com/google-code-attachments/supertux/issue-38/comment-0/problem3.png)
* [problem4.png](https://storage.googleapis.com/google-code-attachments/supertux/issue-38/comment-0/problem4.png)

**Comment by ToufikLevels** [comment]
Hi grumbel , ok i will try to explain you : 
When i start the editor 0.3.4 in windows 7 it works normally.
But in windows 8 there is an error.

**Comment by Hume2** [comment]
Let's hope that the editor upcomming in 0.4.1 won't have this problem...

**Comment by brmbrmcar** [comment]
0.4.1? That won't be released for ages!

**Comment by Hume2** [comment]
0.4.0 should be released in december 2015. The editor should be finished since then, but the 0.4.0 won't contain it. SuperTux should contain that editor right after the 0.4.0 will be released.

**Comment by tobbi** [comment]
I have decided to postpone the editor until after 0.4.0. 0.4.0 is a stable release and I'd rather only have tested code in it.

**Comment by brmbrmcar** [comment]
Thanks for clearing that up.

**Comment by Karkus476** [comment]
As Flexlay was voted for in a poll and agreed upon in the meeting, this cannot be considered a valid issue to have here. If you wish this issue to exist, please reopen it in https://github.com/SuperTux/supertux-editor/issues
