### ISSUE TITLE
Editor: Show currently selected tool at mouse position

### ISSUE THREAD

**Issue by tobbi** [SuperTux/supertux#491]
I often find myself confused which tool is currently selected and whether I am in tile select or object select mode.

I think it would be good if we could show the currently selected tool near the mouse pointer.

**Comment by Karkus476** [comment]
Should this be 0.5.0? Some may argue no, but I think it is a small useful change, not a "feature"

**Comment by maxteufel** [comment]
Useful change, 0.5. Optionally, make that behavior toggle-able in a general editor options menu.

**Comment by Karkus476** [comment]
@maxteufel IMO, no need for toggle, the new sprites are unlikely to be more obnoxious than the penguin cursor
