### ISSUE TITLE
Lispwriter not writing entire config file; crashes on exit or selection of certain options

### ISSUE THREAD

**Issue by obsequiousnewt** [SuperTux/supertux#493]
**SuperTux version:** supertux2 0.4.0-766-gb80715c. Note that running ./supertux -v also causes the crash
**System information:** Kubuntu 14.04 x86

##### Expected behavior
The game writes the config file and doesn't crash.
##### Actual behavior
Upon closing the game, it crashes, dumping core, and the config file that it writes is incomplete (attached.) Additionally, if the fullscreen, sound, or music options are changed in the options menu, the game will crash immediately.
##### Steps to reproduce actual behavior
Quit the game.
##### Additional debugging information

Console output:
zeb@geonia:~/git/supertux/build$ ./supertux2 
[WARNING] /home/zeb/git/supertux/src/util/writer.cpp:49 Not all sections closed in lispwriter
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_S_construct null not valid
Aborted (core dumped)
zeb@geonia:~/git/supertux/build$

If the fullscreen option is changed, it will print the first warning twice.

gdb output:
zeb@geonia:~/git/supertux/build$ gdb ./supertux2 
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "i686-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./supertux2...done.
(gdb) r
Starting program: /home/zeb/git/supertux/build/supertux2 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/i386-linux-gnu/libthread_db.so.1".
[New Thread 0xb45afb40 (LWP 14314)]
[New Thread 0xb36a7b40 (LWP 14315)]
[Thread 0xb36a7b40 (LWP 14315) exited]
[New Thread 0xb36a7b40 (LWP 14316)]
[New Thread 0xaecffb40 (LWP 14317)]
[Thread 0xaecffb40 (LWP 14317) exited]
[Thread 0xb36a7b40 (LWP 14316) exited]
[Thread 0xb45afb40 (LWP 14314) exited]
[WARNING] /home/zeb/git/supertux/src/util/writer.cpp:49 Not all sections closed in lispwriter
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_S_construct null not valid

Program received signal SIGABRT, Aborted.
0xb7fdccb0 in ?? ()
(gdb) bt
#0  0xb7fdccb0 in ?? ()
#1  0x676f6c3a in ?? ()
#2  0x655f6369 in ?? ()
#3  0x726f7272 in ?? ()
#4  0x00000000 in ?? ()
(gdb)

**Comment by obsequiousnewt** [comment]
[config.txt](https://github.com/SuperTux/supertux/files/368151/config.txt)

Copy of the incomplete config file generated.

**Comment by tobbi** [comment]
Backtrace: http://pastebin.com/R30b6dXg
