### ISSUE TITLE
Rules

### ISSUE THREAD

**Issue by Hume2** [SuperTux/supertux#494]
##Since now there were no written rules. It was OK, but we have to write the rules, because some people though that there are no rules at all. Therefore:

* No spamming, No off-topic posts, you know right.
* No flaming. This is a forum and not a flamewar.
* Representing the majority or the development team is strictly forbidden.
* Please don't ask for help about unrelated topics (e.g. git). If you're told to look for external resources on such a topic, please do so.

This "issue" will be closed after 30 days or after it gets to the second page.

**Comment by Karkus476** [comment]
These rules have been added to the wiki, and this issue now has no purpose, closing...
