### ISSUE TITLE
No way to change level length/height in the editor?

### ISSUE THREAD

**Issue by 165your4** [SuperTux/supertux#497]
There doesn't seem to be any way to change a level's length/height in the editor. Sure, you can change the length/height of each individual tilemap but things like gradients rely on the actual dimensions of the level rather than the dimensions of the tilemaps it contains.

**Comment by maxteufel** [comment]
Duplicate of #484, where this is being worked on.

**Comment by tobbi** [comment]
An option to resize the whole sector is in #484.

A whole level consists of different sectors, but I still think resizing one sector only should be enough.

**Comment by 165your4** [comment]
Oops! Sorry.

**Comment by maxteufel** [comment]
Resizing all sectors at once would break things anyway, most likely (depends on the configuration of the sectors, but you know).

**Comment by Hume2** [comment]
The thing you can actually do is reviewing #484 .

**Comment by tobbi** [comment]
Since this is now merged with master, I'm gonna close it.
