### ISSUE TITLE
Supertux editor group selector

### ISSUE THREAD

**Issue by OperationGT** [SuperTux/supertux#498]
**SuperTux version:**
**System information:** *(details about your kernel, operating system, or distribution)*

##### Additional debugging information

*If available, please attach a backtrace of a crash (you can get one using GDB or another debugger), or a core dump. If you're on GNU/Linux and your distro is using systemd, it's highly likely that a core dump is available using `coredumpctl(1)`.
If the issue only occurs in a custom level, please attach that too.*

##### Guidelines for reporting issues

- [ ] I have read <https://github.com/SuperTux/supertux/blob/master/CONTRIBUTING.md#bug-reports>.
- [ ] I verified this isn't an issue that's already been reported.
- [ ] This report only includes details about **one** (1) issue, feature request or topic.
- [ ] If I make a mistake while submitting this report I will use the edit feature instead of closing this issue and opening a new one.
- [ ] This issue is **not** about wrong translations (use Transifex for those), or anything unsupported (e.g. third-party add-ons).
- [ ] Once you're done, please remove the section 'Guidelines for reporting issues', the 'Additional debugging information' if it is empty, and any text in *italic font*.

**Comment by OperationGT** [comment]
In the super tux editor 0.4.7, i have found an issue with the group selector (the green square selector). I was able to group together blocks from the far left and place them down together, it will only place the top-right block down. IT might just be me, but does anybody have any ideas on how to fix this issue?

**Comment by maxteufel** [comment]
@OperationGT You didn't read the 'Guidelines for reporting issues'. Please review them, edit your issue, and reopen it.

**Comment by OperationGT** [comment]
dont worry i found out how to fix it :)
