### ISSUE TITLE
Updated Czech translation

### ISSUE THREAD

**Issue by Grumbel** [SuperTux/supertux#50]
Original [issue 39](https://code.google.com/p/supertux/issues/detail?id=39) created by SuperTuxTeam on 2014-11-22T15:25:16.000Z:

Hi, I updated czech translation of levels and added translation to &quot;*NEW*&quot; in contrib menu.

Attachments:
* [translation.patch](https://storage.googleapis.com/google-code-attachments/supertux/issue-39/comment-0/translation.patch)

**Comment by maxteufel** [comment]
Do we still need this patch or can we close this? (Cc: @giby)

**Comment by giby** [comment]
Tcheck is complete, no need of it. @Hume2 can you proofread it?

**Comment by Hume2** [comment]
Wasn't that already solved????

**Comment by Hume2** [comment]
Yes, it was.
