### ISSUE TITLE
Import level / game loading animation upstream

### ISSUE THREAD

**Issue by tobbi** [SuperTux/supertux#506]
@pelya (Android port maintainer) has added a game / level loading animation in his fork. You can find it here: https://github.com/SuperTux/supertux/compare/master...pelya:level-loading-progress-bar

While I don't think we need the animation at level load, having an animation at game load could really be great, especially for weak systems who might get the impression SuperTux is slow to load.

**Comment by pelya** [comment]
That animation is needed only for Android version, where the tile renderer
will scan through map tile layers and combine all similar adjacent tiles
into big rectangles when loading the map, which are then drawn with a
single OpenGL call, using GL_REPEAT texture mode.

It takes considerable time to calculate that info, but speeds up rendering
2x in some places, like the water cave part of Tobgle Road level - it
reduces the amount of OpenGL texture draw calls from 2000 to 700, and FPS
also increases around twice.

I don't know about other phones, but on my Note 3 with Mali GPU the speed
bottleneck is definitely the amount of separate items to render, and it's
the same on Nexus 7 2012.

That loading screen is crude and has a bug, when it flashes one frame of
the previous screen before level intro. I am going to modify it so it won't
be black, but will first draw a current screen, and then draw a loading
indicator on top.

You frankly don't need any loading screens for PC version, SuperTux loads
quickly enough on anything that's not a phone.

**Comment by maxteufel** [comment]
>  You frankly don't need any loading screens for PC version, SuperTux loads quickly enough on anything that's not a phone.

I think this is more intended for the time required for reading tiles and so from disk - which actually takes quite a few seconds unless you have an SSD.

**Comment by pelya** [comment]
There's a better-looking animation in the latest Android update: https://github.com/pelya/supertux/blob/release/0.4/src/supertux/levelloadinganimation.cpp

**Comment by tobbi** [comment]
I feel like our level loading is smooth enough so that my initial reaction to have this loading animation is unwarranted now.
