### ISSUE TITLE
Level Editor: Doesn't save the y-speed value when the value is below 1

### ISSUE THREAD

**Issue by Rusty-Box** [SuperTux/supertux#509]
The Level Editor currently doesn't save the y-speed of a tilemap, when the value is below 1.
Instead, the Level Editor always set the y-speed of the tilemap back to 1, when you load a level or test it.

**Comment by Hume2** [comment]
From what I can see, it resets the value only when the y-speed is the same as x-speed. I'll correct it.

**Comment by Hume2** [comment]
Test it whether it's fixed or not.

**Comment by Rusty-Box** [comment]
@Hume2 It works now.
