### ISSUE TITLE
Level Editor: crash when viewing, modifying, or removing particles from a level

### ISSUE THREAD

**Issue by maxteufel** [SuperTux/supertux#510]
**SuperTux version:** git master as of 2016-07-28 13:34 UTC+2
**System information:** Arch Linux, Linux 4.6.4, Clang 3.8

##### Expected behavior

SuperTux doesn't crash.

##### Actual behavior

SuperTux crashes.

##### Steps to reproduce actual behavior

1. Place a level using rain particles into the override-data directory recently introduced (the one where menu.stl is placed in). Example: `${buildroot}/data/levels/world2/Going_Underground.stl`.
2. Open level in level editor.
3. Remove rain particles.

##### Additional debugging information

<https://gist.github.com/maxteufel/b52115034c5b8827058124d2d5c031e3>

**Comment by tobbi** [comment]
Please test the fix.

**Comment by maxteufel** [comment]
Still seems to be crashing in LayerIcon::get_zpos(), this time when removing/editing cloud particles: <https://gist.github.com/maxteufel/dc7feed40866779e5a48d6071794175e>

**Comment by Hume2** [comment]
I can't reproduce it.

**Comment by maxteufel** [comment]
@Hume2: it doesn't seem to be reproducible always. And it also happens with other particles (e.g. clouds).

Possibly this is related to the layer management in the editor. @tobbi suggested on our Slack that the layer could be deleted, but for some reason would still be set to a non-null value, which might cause LayerIcon::get_zpos() to crash.
