### ISSUE TITLE
Krush and Krosh don't go down a second time

### ISSUE THREAD

**Issue by tobbi** [SuperTux/supertux#515]
In the level "End of the crystal cave" by Toufik, you can see that Krush doesn't go down a second time after being at the initial position after going down once. 

[2016-07-29 21-02-29.mp4.zip](https://github.com/SuperTux/supertux/files/391177/2016-07-29.21-02-29.mp4.zip)

**Comment by Hume2** [comment]
It seems to be level-specific, because they seem to work fine in Icecrusher Test.

**Comment by Narre** [comment]
I don't think this is a bug - Icecrushers only don't attack second time when they can't reach their starting position (when they are trying to rise, but there's a solid block above). You can see how it works for me here: https://youtu.be/P48P1pPK0Xs

**Comment by Karkus476** [comment]
I agree with Narre, please fix the level.
