### ISSUE TITLE
Editor: Setting camera to autoscroll not working

### ISSUE THREAD

**Issue by tobbi** [SuperTux/supertux#516]
I believe the issue is that we're saving a bogus path entry in the level itself, thus the camera stays as it is all the time.

**Comment by Hume2** [comment]
I can't reproduce it. Did you set the path?

**Comment by maxteufel** [comment]
@Hume2 How is one supposed to set the path? It doesn't work the way it works usually for other objects.

**Comment by Hume2** [comment]
When you click the camera, it displays a path node in the top left of the level. The same as for the other objects.

**Comment by maxteufel** [comment]
@Hume2 It's barely visible and restricted due to that navigation thing. Also, when I select a path node from the object menu and click anywhere in the level, no path is added.

**Comment by Hume2** [comment]
@maxteufel To add a next node you have to click an exisiting node before.

**Comment by maxteufel** [comment]
Works for me, and apparently @Hume2 as well.
