### ISSUE TITLE
Please update de app

### ISSUE THREAD

**Issue by Grumbel** [SuperTux/supertux#52]
Original [issue 41](https://code.google.com/p/supertux/issues/detail?id=41) created by SuperTuxTeam on 2015-01-11T20:36:55.000Z:

Please, pass at normal to beta the version 0.3.4.

And Actualizad all languages (especially Catalan, I've updated)

**Comment by tobbi** [comment]
SuperTux 0.3.5 was released yesterday. Download from https://github.com/SuperTux/supertux/releases/tag/v0.3.5.
