### ISSUE TITLE
Allow Scripts to Preserve Data Through Restart

### ISSUE THREAD

**Issue by Karkus476** [SuperTux/supertux#530]
Worldmap scripts should have an API which allows them to save data on the player's computer.
This could result in serious security vulnerabilities, if care is not taken to ensure that the scripts are not given too much freedom.
I think the way this should be implemented is that the scripter can store_value("label", 50) and then retrieve_value("label") -> 50. (pseudocode over-simplification)The actual file data will be hidden from the script.

**Comment by tobbi** [comment]
So, we're actually talking about a scriptable preferences system, right?

**Comment by Karkus476** [comment]
@tobbi Yes, although this includes any data that needs to be preserved. Preferences, items, bonuses etc.

**Comment by christ2go** [comment]
@Karkus476 So it would be like a worldmap local key-value store for options. Which values should be storable? Only primitive data types or also lists etc?

**Comment by Karkus476** [comment]
@christ2go All types should be storable, although strict limits should be put in place.

**Comment by Hume2** [comment]
Doesn't already the "state" work like that? You can write it into state.whatever and then save_state().

**Comment by Semphriss** [comment]
The `state` variable does this job; considering this hasn't gotten any attention in 4 years, I'll close this.
