### ISSUE TITLE
Zeeklings: Curved flight path + screech

### ISSUE THREAD

**Issue by Karkus476** [SuperTux/supertux#533]
Zeeklings should curve down to be on the same level as the player, and then level off, to give the player more warning that they are coming. This should be accompanied by a screech as they attack, so that the player is not surprised.

**Comment by maxteufel** [comment]
@mandaltapesh / @tapeshmandal wanted to work on this (as said on IRC).

@Karkus476 proposed a parabolic curve, however I believe we should also consider hyperbolic (cosine) curves.

**Comment by Karkus476** [comment]
My main point on IRC
> I want the user to see that the zeekling is attacking, and be able to jump over it.
It shouldn't be easy, but it shouldn't be surprising and frustrating.

**Comment by Alzter** [comment]
I agree wholeheartedly. Zeeklings need some sort of strategy to be dealt with.
They shouldn't be so hard that you always have to be ready for a sudden Zeekling swoop.
I might resprite the Zeekling down the track for my Improved sprites mod thing.

**Comment by busybody42** [comment]
not a bad idea...

**Comment by tapeshmandal** [comment]
Hello everyone,

I am not working on this issue anymore. Sincere apologies for not notifying
earlier. Please feel free to pick it up.

Thanks.

Best regards,
Tapesh Mandal
