### ISSUE TITLE
Stone feature of earth bonus potentially too powerful

### ISSUE THREAD

**Issue by maxteufel** [SuperTux/supertux#537]
~~Any~~Most badguys can be killed by turning yourself into a stone while jumping (hold Ctrl, press down). This could be mitigated by only allowing turning into a stone `on_ground()`.

**Comment by maxteufel** [comment]
Please have a look at the commit linked to by GitHub above.

**Comment by Hume2** [comment]
Seems fine.

**Comment by Rusty-Box** [comment]
Sounds good.
