### ISSUE TITLE
Suggestion: End of Icy Island should have Tux and Penny re-uniting

### ISSUE THREAD

**Issue by SuicSoft** [SuperTux/supertux#542]
The ending of the last level, _No More Mr. Ice Guy_, is kind of meaningless and doesn't seem like a good way to end the game. Since the game is about Tux losing Penny and trying to find her, why isn't there anything about that in the end? We do not see Penny after going through all the levels.

**Comment by Rusty-Box** [comment]
The Yeti isn't the final boss of the game. After Icy Island, there is going to be a second world, which takes place in a forest. But since the second world is still in progress, you can not reach it in the story mode. But you can see the current progress in the contrib levels menu.

**Comment by SuicSoft** [comment]
@Rusty-Box Okay, thanks :) So there's no ending with Penny yet right? What happens after finishing the Forest World?

**Comment by Rusty-Box** [comment]
Yes there is currently no ending with Penny and after Forest World there will be more worlds. It is still unknown how many there are going to be. (The third world will probably be a Tropical Island.)

**Comment by SuicSoft** [comment]
@Rusty-Box Okay, I'll close this

**Comment by maxteufel** [comment]
There is nothing to close here. Adding some story is an actual issue that needs to be fixed for the 0.6.0 release.

**Comment by SuicSoft** [comment]
@maxteufel okay :)

**Comment by Karkus476** [comment]
@maxteufel I am closing this, as the problem at hand has been addressed. You are highlighting an important point, though, so I will open another issue to address it.
