### ISSUE TITLE
SuperTux Bonus Level Issue

### ISSUE THREAD

**Issue by SuicSoft** [SuperTux/supertux#543]
**SuperTux version:** Milestone 2 (0.4.0)
**System information:** *Windows 10 Pro x86 running on Intel 64bit Capable CPU*

**Expected behavior:**  The end of the Icy Island Bonus Level (blue dot) should end in the typical way

**Actual behavior:** Tux gets "stuck" in one position. I tried this many times, with Tux **always** getting stuck in the same location. Probably not related to lag because it always gets stuck in the same position

**Steps to reproduce actual behavior:** Open SuperTux Milestone 2 on Windows 10 and go to the bonus level (press the up arrow at _A Mysterious House of Ice_)
<br>
![screenshot 109](https://cloud.githubusercontent.com/assets/13938848/17589779/3b71c1aa-5ff4-11e6-8242-8483a9509669.png)

**Comment by maxteufel** [comment]
@SuicSoft This change will appear in the nightly builds when the data submodule has been updated.

**Comment by SuicSoft** [comment]
@maxteufel I'll check tommorrow and thanks :+1:

**Comment by maxteufel** [comment]
@SuicSoft I'm not sure if it will be there tomorrow. Definitely before the release though.

**Comment by SuicSoft** [comment]
@maxteufel When's the next release?

**Comment by maxteufel** [comment]
Soon(TM). But the answer is "when it's done". You can check <https://github.com/SuperTux/supertux/releases>.

**Comment by SuicSoft** [comment]
Right.
