### ISSUE TITLE
menu.stl.in gets configured in build dir's data subdir instead of the data/ dir of the current src

### ISSUE THREAD

**Issue by tobbi** [SuperTux/supertux#544]
When you build SuperTux in a build/ subdir, the menu.stl.in file gets configured in supertux/build/data/... while the rest of the data files results in $CMAKE_CURRENT_SOURCE_DIR/data which is supertux/data.

I *think* the solution should be to just swap all the variables, but I wanted to make sure.

**Comment by maxteufel** [comment]
@tobbi I think this is expected.
