### ISSUE TITLE
Ice Bonus Has No Value

### ISSUE THREAD

**Issue by Karkus476** [SuperTux/supertux#552]
Earth gives you a light, air allows you to traverse long gaps, and fire allows you to kill things.
Ice is no more interesting or unique than fire, and needs some objects, tiles and levels to interact with.

**Comment by Karkus476** [comment]
Also see @maxteufel's [idea](https://github.com/SuperTux/data/issues/57#issuecomment-240400940)

**Comment by SuicSoft** [comment]
Ice powerup can kill the fire bad guy while fireballs can't

**Comment by Hume2** [comment]
Yes, that's it. And having loads of ice flowers is commonly even better than having loads of fire flowers in the forest, because the ice bullet bounce more than fire flowers. And yes, they are very useful in the castle and underground levels, those contain fire enemies.

**Comment by Alzter** [comment]
You should expand on the ideas for the powerups.

Fire is just the Mario fire flower.

Ice is useless in World 1 and needs more functionality.

Earth is a light plus the Tanooki suit statue thing from Mario 3.
I think you should probably replace the statue thing. SuperTux is unoriginal enough.
(May I add that the ambient light gimmick is absolute crap?
Making levels difficult by obscuring what you can see is absolute trash.
The only real difficulty in M2 is just cheapness like that and bad level design.
The carryable lantern gimmick is okay, but kind of annoying)

Air is ok, but is kind of un-intuitive being not that useful/easy to use.
Maybe change it up?
