### ISSUE TITLE
Storyline???

### ISSUE THREAD

**Issue by Karkus476** [SuperTux/supertux#553]
@maxteufel Made an important point in #542 

> Adding some story is an actual issue that needs to be fixed for the 0.6.0 release.

I think we need to come to some agreement in a meeting or here as to what changes in SuperTux's story between Icy Island and the Forest World.

**Comment by Alzter** [comment]
Please, please, please fix the Icyisland cut-scene SuperTux Team.
It's so horrendously bad that it just comes off as blatantly lazy.

**Comment by weluvgoatz** [comment]
I have some cutscenes on the Supertux Forum in Contributions.

**Comment by Alzter** [comment]
> Please, please, please fix the Icyisland cut-scene SuperTux Team.
> It's so horrendously bad that it just comes off as blatantly lazy.

You know what? I might redo the intro myself in good time.

**Comment by Rusty-Box** [comment]
Issue can be closed as #984 and #985 added more cutscenes that further tell the story.
