### ISSUE TITLE
Updated Windows Build Instructions

### ISSUE THREAD

**Issue by Karkus476** [SuperTux/supertux#555]
The page "Building" on the wiki says this:

> Most SuperTux developers tend to work on UNIX-like operating systems such as Linux or macOS. While the code can be compiled on Windows, and automated (test) builds run for every commit on Windows, this document currently doesn't explain how to build on Windows. These details will be added later in a separate section of this document.

This needs adding to the document. Ideally both for MSVS and Cygwin/MinGW users if possible.

**Comment by maths22** [comment]
I can add MSVC instructions sometime soon.

**Comment by Karkus476** [comment]
@maths22 Okay thanks
