### ISSUE TITLE
Checkpoint Problems

### ISSUE THREAD

**Issue by Karkus476** [SuperTux/supertux#556]
You won't respawn at the checkpoint if you have <25 coins. Each time you respawn at checkpoint you lose either 10% or 25 coins, whichever is higher. I know this from the code. Players do not know this. It should be explained, and we need to discuss if it should be changed.

**Comment by tobbi** [comment]
The 10% or 25 coins thing is explained in the first level since https://github.com/SuperTux/data/commit/aaad57f96eeb8b3d053f4c830fb68ac9642839d4

**Comment by Karkus476** [comment]
The reason I made this issue is because we are a mario clone, not a sonic clone, and I cannot work [this](http://www.wolframalpha.com/input/?source=nav&i=log+base(9%2F10)(250%2Fx)%2B10) out in my head.

**Comment by qwertychouskie** [comment]
Why not just do a number of lives, as this is what most people are used to?

**Comment by Hume2** [comment]
This behaviour is good when levels of an author contain loads of coins, so Tux doesn't get loads of lives. It's exponential, so he becomes only a few lives extra.

**Comment by Rusty-Box** [comment]
It has been decided again the concept of lives as well as removing the link between coins and checkpoint respawning. See #1410
