### ISSUE TITLE
Scripting support for checking whether tux carries certain Portable

### ISSUE THREAD

**Issue by tobbi** [SuperTux/supertux#559]
Basically, I think level could consist of a script trigger that checks whether tux carries a certain portable object and then only allows access if this is the case.

Therefore, I am proposing the following:

Portable objects have names (don't they?)

We could have a scripting interface, like:
sector.Tux.is_carrying("my-portable-name"), which returns a boolean true / false.

**Comment by maxteufel** [comment]
> Portable objects have names (don't they?)

Nope. So the question is... do we want portable objects to have names?
