### ISSUE TITLE
Find out if tools/innosetup/ is still necessary

### ISSUE THREAD

**Issue by maxteufel** [SuperTux/supertux#566]
According to @maths22, `tools/innosetup/supertux??.iss` is not necessary anymore. The status of `tools/innosetup/supertux.ico` is still unknown and needs investigation.

`tools/innosetup/supertux.ico` seems to be referenced by `mk/msvc/icon_rc.template`, which is in turn being used by `CMakeLists.txt` (line 100).

**Comment by tobbi** [comment]
Fixed with 82f2979ef0aa4ea7acdd3825d08bf9920609de84
