### ISSUE TITLE
Resizable Sprites

### ISSUE THREAD

**Issue by christ2go** [SuperTux/supertux#569]
Sprites and Surfaces should be resizable. This is needed for the storage of powerups and items, because the user should be allowed to add his own collectible items and it's easier for the user to be able to use a Sprite in any resolution. 

It might be a good idea to resize the images, and store them in a specail directory, because else the images would have to be resized too often, and it will ensure that the game is fast. For avoiding storing too many images they should be kept and maybe deleted if they weren't used in a long time.
TODO
- [ ] Implement a scaling algorithm for PNGs
- [ ] Implement the resized image container
- [ ] Extend this to Sprites

**Comment by maxteufel** [comment]
Note that in this case, user probably means 'world designers'.

**Comment by christ2go** [comment]
Would it be ok to use a library for accessing/resizing the images?

**Comment by christ2go** [comment]
Closing this for now, level designers can just resize the sprites manually for now.

Closes #569
