### ISSUE TITLE
Update AppVeyor dependency package

### ISSUE THREAD

**Issue by tobbi** [SuperTux/supertux#570]
Through inspection of the SDL2 assembly, I noticed that it's version 2.0.3. SDL 2.0.4 is available which *might* fix #304 (not saying that it does, but might be worth a try).

While we're at it, we can check and update all the other dependencies as well.

**Comment by qwertychouskie** [comment]
#403?  I think you meant a different one, that one is already closed.

**Comment by tobbi** [comment]
Thanks, corrected!

**Comment by tobbi** [comment]
The build dependencies zip files were updated with the latest versions of all required libraries. Check https://download.supertuxproject.org/builddep/ for latest buildep package.
