### ISSUE TITLE
Keyboard shortcuts for navigating in editor

### ISSUE THREAD

**Issue by tobbi** [SuperTux/supertux#575]
Easier workflow for level designers. I'm thinking about the following (similar to Blender):

Press Tab: Switch between Object and Tile mode.
q, w, e, r  to switch between tools (delete, insert normal, insert rectangle, fill)
a, s, to switch between copy modes.

Some other shortcut for object properties etc.

**Comment by christ2go** [comment]
Also add shortcuts for testing the current level (or if it is already implemented mention it).

**Comment by SuicSoft** [comment]
Also the standard keyboard shortcuts such as the `delete`, `ctrl + c`, `ctrl + z` etc

**Comment by Rusty-Box** [comment]
We got some shortcuts in for certain things like "Undo", "Play Test Level", "Save Level", "Hide Grid" etc. Not as mayn as we should but we can always add more. I don't think this requires an open issue slot. Feel free to re-open if need be.
