### ISSUE TITLE
Worldmap music not playing

### ISSUE THREAD

**Issue by BlaCoiso** [SuperTux/supertux#583]
**SuperTux version:** 0.5.0 rc3
**System information:** Ubuntu 16.04 32bit *(details about your kernel, operating system, or distribution)*

##### Expected behavior
The worldmap music should play after exiting a level with the same music

##### Actual behavior
After exiting the level no music plays

##### Steps to reproduce actual behavior
Play a level with the worldmap music
Exit it without finishing it or picking up a star
When you exit the level and return to the worldmap, there's no music

**Comment by maxteufel** [comment]
Can you name such a worldmap and level?

**Comment by maxteufel** [comment]
I can confirm this issue. It only happens when exiting levels using the abort menu though, not when finishing them.
