### ISSUE TITLE
Tux "drags" himself during movement while testing in the Level Editor

### ISSUE THREAD

**Issue by SuicSoft** [SuperTux/supertux#589]
**SuperTux version:** 0.5 (Release Candidate)
**System information:** Windows 10 Pro, Insider Preview on Anniversary Update.

##### Expected behavior
Testing levels in the Level Editor should work as normal

##### Actual behavior
Tux "drags" himself during movement. 

##### Steps to reproduce actual behaviour

1. Start SuperTux.
2. Click "Level Editor" > "New Level Subset". 
3. Fill out the name and description and press "OK" > "Create Level".
4. Press "OK" again for the license notice.
5. Click "Background" (the 4th box at the bottom-left) and change _Top image_, _Image_, and _Bottom image_ to **castle_foreground.png**
6. Add tiles underneath the default spawn point.
7. Test the level.

![screenshot 38](https://cloud.githubusercontent.com/assets/13938848/18246862/21b41e1a-738c-11e6-9dd9-a66be59b80ca.png)

**Comment by maxteufel** [comment]
Please submit a test level.

**Comment by Karkus476** [comment]
@SuicSoft Thank you for a very detail issue.
This has nothing to do with the editor, the problem is that the background image has transparent sections.
The game does not render the usual background if there is a background image selected, so this means that there are areas of the screen which are not being redrawn each frame. This means each time Tux moves, the pixels last time he was drawn remain set.

@maxteufel Here is a test level.
[bug.stl.txt](https://github.com/SuperTux/supertux/files/454988/bug.stl.txt)

**Comment by brmbrmcar** [comment]
It is nothing to do with the editor. It happens on all completely black backgrounds or sometimes gradients.

**Comment by SuicSoft** [comment]
So...if I want to use the castle background **properly** (set as top, bottom and middle image). How would I accomplish it?

**Comment by maxteufel** [comment]
@SuicSoft You will need one more background/gradient behind the castle background that is not transparent.

**Comment by SuicSoft** [comment]
@maxteufel Where can I add another background? (sorry for the noob question)

**Comment by maxteufel** [comment]
@SuicSoft In the objects tool. This is not a support channel though. Ask that kind of question on IRC.

**Comment by SuicSoft** [comment]
@maxteufel OK and thanks :) Should I close this?

**Comment by maxteufel** [comment]
This is not a bug because there is simply nothing else to draw behind that last background. The last background/gradient layer in a level should always be non-transparent. Otherwise this is bad design, not a bug. The game is just doing what it's told to do.

**Comment by brmbrmcar** [comment]
Can't we just stick black at the very end?

**Comment by maxteufel** [comment]
That adds more code than necessary, and makes the assumption that the level author doesn't want this to happen in any case.
