### ISSUE TITLE
Remove English text from (untranslatable) images

### ISSUE THREAD

**Issue by xendez** [SuperTux/supertux#598]
I saw in SuperTux directory "C:\Games\SuperTux\data\images\help\" one image translated "_rockhowto2-zh.png_" and the original in english "_rockhowto2.png_". Can we translate these images to other languages? I'm thinking at least in the case more seen in SuperTux: "\SuperTux\data\images\tiles\signs\run.png", this one would be very nice to have translated in the game. By other words, can I make a image file translated "run-pt.png" (and "run-pt-BR.png" and may be others) and attach them to this post to be implemented in SuperTux?

**Comment by brmbrmcar** [comment]
It would use up a lot of space. I would suggest to developers not to put English or any other language in a bitmap image. It should be fixed.

**Comment by xendez** [comment]
Well, in that case, could be something like this and we wouldn't need translations:
![run_new](https://cloud.githubusercontent.com/assets/11544441/18562194/a16ce13c-7b7a-11e6-9373-0013ce594cd4.png)

**Comment by brmbrmcar** [comment]
Yes...

**Comment by Hume2** [comment]
Seems good, maybe it just shouldn't contain the snow to fit into the warmer themes.

**Comment by maxteufel** [comment]
We need the author(s) and licenses on this clarified, otherwise we can't use it btw.

**Comment by xendez** [comment]
Ok, here is a series of them. The middle one use the same support of the other ones in SuperTux, so probably we should choose the middle one. The last one is the same a bit stretched since this image is really tiny.
![run_new15](https://cloud.githubusercontent.com/assets/11544441/18592024/f28da896-7c2c-11e6-8f30-2e0d48724954.png) ![run_new13](https://cloud.githubusercontent.com/assets/11544441/18591873/5ee7b96a-7c2c-11e6-99fc-ee3ab84af3c1.png) ![run_new12](https://cloud.githubusercontent.com/assets/11544441/18591880/62bd455a-7c2c-11e6-8a9e-446b7863795b.png)

maxteufel: I didn't much on it, I've just used and made some changes on the images present in SuperTux installation, so I have to release these images in the same license of them (GPL?). What concerns to the tiny work I did in this images, I would release that part in CC0/Public domain/WTFPL/choose the license you want. But this must be released in the same license as originals, or something compatible.

After choosing one we need to change another using this one:
![billboard-runjump_new](https://cloud.githubusercontent.com/assets/11544441/18592391/aaa3df26-7c2e-11e6-845e-5b43d4621742.png)

Another thing, can somebody tell me if the following image is shown in SuperTux? It's in "C:\Games\SuperTux\data\images\help\"  I can try to make one without text in a big billboard like the image above.
![rockhowto2](https://cloud.githubusercontent.com/assets/11544441/18592459/ff6e7d36-7c2e-11e6-8d65-7eaa0d337994.png)

**Comment by maxteufel** [comment]
> Ok, here is a series of them. The middle one use the same support of the other ones in SuperTux, so probably we should choose the middle one. The last one is the same a bit stretched since this image is really tiny.

I like the middle one too. Otherwise we'd have to use more tiles. I like the style of the first one too, so maybe there could be alternative versions (are you an artist?). :)

> maxteufel: I didn't much on it, I've just used and made some changes on the images present in SuperTux installation, so I have to release these images in the same license of them (GPL?).

The code is clearly GPLv3, however it's a good question how the images are licensed. Quoting the [wiki](http://supertux.lethargik.org/wiki/Contributing#Licenses):

> For everything else (like levels, images, sounds, and new programs), make sure that you can release it under GPLv2 or later (yes, all contributions need to be released under GPL) and also CC-BY-SA for data files such as images, sounds, music, and levels. (Scripts count as parts of levels) 

I don't know if that also applies to the existing artwork. I'd strongly prefer dual licensed GPL/CC-BY-SA then.

> After choosing one we need to change another using this one:

Agreed.

> Another thing, can somebody tell me if the following image is shown in SuperTux? It's in "C:\Games\SuperTux\data\images\help\" I can try to make one without text in a big billboard like the image above.

Yes it is. In "Tux the Builder" on Forest Island.

**Comment by xendez** [comment]
Ok. Thank you for your feedback maxteufel. It seems all images are at least GPLv2 or later and some also CC-BY-SA according to http://supertux.lethargik.org/bugs/view.php?id=578#c1694 (which ones? any body knows? at least Tux, signs and billboard images, if these ones aren't dual-licensed I can't release them dual-licensed, only GPLv2+).

Before taking care of the last image of Tux the Builder on Forest Island that should be in a billboard, I played a bit with a billboard made from scratch. Don't know if the colors are right, was made in a uncalibrated monitor. It's an in-game screenshot:
![billboard-comparison](https://cloud.githubusercontent.com/assets/11544441/18602454/25fa6e24-7c61-11e6-9c76-298823bfb59e.png)

**Comment by xendez** [comment]
Here is the billboard with instructions (to replace images in \Games\SuperTux\data\images\help\) and the necessary changes in the level "Tux the Builder" on Forest Island. I've made also a billboard with a keyboard key but it was weird, so I left the instructions to press the key in the instructions block. Here's a screenshot testing the level:
![screenshot_test](https://cloud.githubusercontent.com/assets/11544441/18605368/1ed666a8-7c88-11e6-9608-7827ca24dd69.png)

Image:
![billboard-pickrock4](https://cloud.githubusercontent.com/assets/11544441/18605355/c77a3a06-7c87-11e6-8b71-aeda6c69326d.png)

Level: [Tux_Builder.zip](https://github.com/SuperTux/supertux/files/477939/Tux_Builder.zip)

Of course this is released in the same licenses as originals. Level: GPL2+/CC-BY-SA 3.0 (it's on level properties). Billboard Image: GPL2+ / CC-BY-SA (don't know if the originals are also licensed CC-BY-SA: the rock block, Tux, sign and billboard).
Please test the level and change the text message if needed. English is not my native language and I'm a novice in level editor... If this is implemented in SuperTux please let us translate this message on Transifex.

**Comment by Hume2** [comment]
This looks much better.

re: ![billboard-comparison](https://cloud.githubusercontent.com/assets/11544441/18602454/25fa6e24-7c61-11e6-9c76-298823bfb59e.png) Good idea, just I'd say that the wood is too much red, increase the hue by approximately 20 points. This wood seems to be a tropical wood.

**Comment by maxteufel** [comment]
I think both billboard types would work. The current one stays on Icy Island/Antarctica, and the new version can be used on Forest Island.

I agree with @Hume2 about the fact that this seems to red for this forest. It might find use elsewhere in the future. Also, it might be useful to have different types of billboards for ghost forest and underground as well (and some that hang down from clouds maybe), but please ask @SuperTux/level-designers for confirmation about that.

**Comment by brmbrmcar** [comment]
I don't like the new one. It needs a better border.
