### ISSUE TITLE
OS X binary of 0.3.5 fails to load because of missing /opt/local/lib/libSDL2-2.0.0.dylib

### ISSUE THREAD

**Issue by dusek** [SuperTux/supertux#60]
Steps:
1. Download and open https://github.com/SuperTux/supertux/releases/download/v0.3.5/SuperTux-0.3.5-osx-intel.dmg
2. Copy the SuperTux app bundle to /Applications
3. Launch SuperTux (e.g. using Spotlight)

Result:
Fails to launch with this information appearing (information in the end removed):
```
Process:               supertux2 [41083]
Path:                  /Applications/SuperTux.app/Contents/MacOS/supertux2
Identifier:            com.googlecode.supertux2
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           supertux2 [41083]
User ID:               501

Date/Time:             2015-04-12 15:12:25.264 +0200
OS Version:            Mac OS X 10.10.3 (14D131)
Report Version:        11
Anonymous UUID:        ****

Sleep/Wake UUID:       ****

Time Awake Since Boot: 78000 seconds
Time Since Wake:       1800 seconds

Crashed Thread:        0

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000002, 0x0000000000000000

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /opt/local/lib/libSDL2-2.0.0.dylib
  Referenced from: /Applications/SuperTux.app/Contents/MacOS/supertux2
  Reason: image not found

Binary Images:
    0x7fff6696e000 -     0x7fff669a4837  dyld (353.2.1) <65DCCB06-339C-3E25-9702-600A28291D0E> /usr/lib/dyld

Model: ...
...
```

**Comment by maxteufel** [comment]
@dusek: This is because we forgot to bundle the libraries in the binary.

To fix this, include the *.dylib files we need in the .app and modify the path in the binary using `otool(1)` and `install_name_tool(1)` (they take relative paths too). Due to my slow internet connection I can unfortunately not do this and upload the binary.

**Comment by dusek** [comment]
Thanks for the superfast response, will try that.

**Comment by maxteufel** [comment]
Well, unless you have those libraries installed somewhere else (e.g. by homebrew) you can't do that.

**Comment by dusek** [comment]
Seems to work this way:
1. Install sdl2 from Homebrew: `brew install sdl2`
2. Change the library name in SuperTux.app: `install_name_tool -change /opt/local/lib/libSDL2-2.0.0.dylib /usr/local/opt/sdl2/lib/libSDL2-2.0.0.dylib /Applications/SuperTux.app/Contents/MacOS/supertux2`

Now it stops complaining about libsdl2. However it starts to complain about libsdl2_image, and looking at output of `otool -L`, there seem other libraries that will need bundling:
* `/opt/local/lib/libSDL2_image-2.0.0.dylib`
* `/opt/local/lib/libvorbisfile.3.dylib`
* `/opt/local/lib/libphysfs.1.dylib`
* `/opt/local/lib/libGLEW.1.12.0.dylib`

Will try if I am successful with these and homebrew.

**Comment by tobbi** [comment]
I will take a look later this day. Thanks for notifying me.

**Comment by maxteufel** [comment]
### For everyone who downloaded the affected build

> However it starts to complain about libsdl2_image, and looking at output of otool -L, there seem other libraries that will need bundling

Exactly, that's why I wrote `the *.dylib files we need`.

> Will try if I am successful with these and homebrew.

This should work, at least if they're the same version.

If you prefer to avoid issues when the libraries are updated in homebrew, copy the files you need to `/Applications/SuperTux.app/Contents/lib/` and change the library path to a relative one (`../lib/$lib` from the `/Applications/SuperTux.app/Contents/MacOS/`). You could also point it to the absolute path but then it will only work if the app is in `/Applications`.

**Comment by tobbi** [comment]
I will delete the affected build for now.

**Comment by tobbi** [comment]
Can you please try the dmg here: https://www.dropbox.com/s/882pf938jh6pqa4/SuperTux-0.3.5-osx-intel.dmg?dl=0 It has all dependencies included into it.

**Comment by dusek** [comment]
> Can you please try the dmg here: https://www.dropbox.com/s/882pf938jh6pqa4/SuperTux-0.3.5-osx-intel.dmg?dl=0 It has all dependencies included into it.

It does not work. You probably forgot to include the `SuperTux.app/Contents/libs` directory as it is not present and it complains about:

```
dyld: Library not loaded: @executable_path/../libs/libSDL2-2.0.0.dylib
  Referenced from: /Applications/SuperTux.app/Contents/MacOS/supertux2
  Reason: image not found
Trace/BPT trap: 5
```

**Comment by tobbi** [comment]
I uploaded a new dmg file under the same path. Please re-download.

**Comment by dusek** [comment]
Yes, this works. Thanks :-)

**Comment by tobbi** [comment]
I uploaded a new dmg file to the downloads section. Can you please try that one as well?

**Comment by dusek** [comment]
It works as well (it unexpectedly quits on first launch when OS X asks whether or not to launch an app downloaded from internet; but on second attempt, it works; I tried this twice (deleted the app, recopied from dmg; I think this happened also with the previous download you put to dropbox). I guess most users will impatiently try to launch again and then they are set, so probably not a big deal.

**Comment by maxteufel** [comment]
> it unexpectedly quits on first launch when OS X asks whether or not to launch an app downloaded from internet

Could you anyway get a stacktrace (either from OS X's Crash Reporter or from gdb) and open another issue? Thanks.

**Comment by tobbi** [comment]
Yeah, please do open another issue. I will close this one as fixed for now.
