### ISSUE TITLE
Level Editor: Tilemap as Lightmap Option

### ISSUE THREAD

**Issue by Rusty-Box** [SuperTux/supertux#600]
I'm not sure, whether this is intended to be or not, but I noticed that in the external Editor you were able to choose, whether or not a tilemap should be a lightmap. But in the in game editor you can't.

**Comment by tobbi** [comment]
Needs support for a tilemap's draw-target option.
https://github.com/SuperTux/supertux/blob/e64a757736df4a13f7e9ae2deabab1847597b011/src/object/tilemap.cpp#L186

**Comment by maxteufel** [comment]
This will also involve a string change during a release cycle.
