### ISSUE TITLE
changes that could have the super tux

### ISSUE THREAD

**Issue by patinhas19** [SuperTux/supertux#602]
the game is very good, but could have more functions , for example the tux could swim in the water , could have a carnivorous plant that appears and hides in a vessel like the Super Mario games.

**Comment by tobbi** [comment]
Swimming is planned in #217 

We kinda have a carnivorous plant as well. Can't find the link quickly, at the moment, though.

**Comment by Hume2** [comment]
Please, put community ideas to the forum. Pull-requests with implementation are OK. You should visit our forum at: http://forum.freegamedev.net/viewforum.php?f=66&sid=7d271ca537028e81027e0b3cdab4f0ca
