### ISSUE TITLE
improvements that the new super tux could have (v0.5.0)

### ISSUE THREAD

**Issue by patinhas19** [SuperTux/supertux#603]
could have more bosses, for example in the ice island is the yeti, the haunted forest is the tree, but the normal forest has not. The island forest could have.

**Comment by Rusty-Box** [comment]
The ghost forest is just another area in the forest, so that means that the ghost tree is the boss of the whole forest.

**Comment by Hume2** [comment]
Please, put community ideas to the forum. Pull-requests with implementation are OK. You should visit our forum at: http://forum.freegamedev.net/viewforum.php?f=66&sid=7d271ca537028e81027e0b3cdab4f0ca
