### ISSUE TITLE
Walking into a frozen cannon unfreezes it

### ISSUE THREAD

**Issue by 165your4** [SuperTux/supertux#604]
Walking into a cannon frozen with the Iceflower seems to unfreeze it as soon as Tux touches the sprite. I noticed this in 0.5.0 rc4 so I'd imagine the bug is still around.

**Comment by christ2go** [comment]
I can reporduce the bug, and found a fix, but it still has to be asked if this isn't exspected behaviour and if it also affects other types of canons.

**Comment by SuicSoft** [comment]
I think this is expected behaviour. Jumping on a _frozen_ Mr. Bomb produces the same behaviour

**Comment by 165your4** [comment]
@SuicSoft Yes, but _walking into_ a frozen Mr. Bomb does not.
