### ISSUE TITLE
Switch ENABLE_BOOST_STATIC_LIBS to OFF by default on Linux

### ISSUE THREAD

**Issue by akien-mga** [SuperTux/supertux#610]
**SuperTux version:** 0.5.0
**System information:** Mageia 6 x86_64, kernel 4.7.4, boost 1.60.0
##### Expected behavior

Building from source should work out of the box with boost shared libraries + headers installed.
##### Actual behavior

The build defaults to `ENABLE_BOOST_STATIC_LIBS=ON`, which enforces the use of static libraries. Those are usually (and that's good) not included in development packages (and actually on Mageia they're not even packaged at all).

Turning the option OFF is relatively easy, but I think that it should be the default behaviour on Linux systems, as nobody would want to link against boost statically apart from the contributor who would do official static Linux binaries (and that contributor can then switch it on if need be).

**Comment by PandaJim** [comment]
So could you tell me how to turn off the option? I'm trying to build this release in Ubuntu, but I'm not a programmer

**Comment by akien-mga** [comment]
@PandaJim `cmake -DENABLE_BOOST_STATIC_LIBS=OFF`.

**Comment by maxteufel** [comment]
Needs information from @maths22 if there's a reason for that default. The option defaults to this value because before introducing the option, this behavior wasn't even configurable. There might have been a reason for that.

**Comment by maths22** [comment]
This is the default because it (appears) to emulate the behavior automatically used, although I may have only  tested it on Windows originally.  That said, changing this default for non-windows systems probably makes sense.

**Comment by maths22** [comment]
Closed as part of #706 (commit ebae41b10354bfd71d91de1dd503d9001c056f69)
