### ISSUE TITLE
"sound" and "music" disabled/grayed out?

### ISSUE THREAD

**Issue by Epitaphios** [SuperTux/supertux#613]
As the title suggests -- After I downloaded the latest build that fixed the crashing errors, the game now has no sound or music, and in the options both the sound and music options are disabled and grayed out.

**Comment by brmbrmcar** [comment]
Please delete that issue info and add a description.

**Comment by christ2go** [comment]
@Epitaphios Latest build means v. 0.5.0? Which operating system are you using?

**Comment by Epitaphios** [comment]
@christ2go Latest build means the recently updated build of v.0.5.0 that fixed the crashing issue for certain users. And i'm using Windows 7 x64.

**Comment by snadge** [comment]
I was able to resolve the issue by installing OpenAL from here: https://www.openal.org/downloads/

It looks like the same version of OpenAL32.dll gets installed, however when it is located in %windir%\system32 it seems to work.

**Comment by Epitaphios** [comment]
You're right, a quick install of this and the sound was immediately fixed on ST. Thanks!

**Comment by tobbi** [comment]
There's something wrong with the OpenAL deps (still).

**Comment by maths22** [comment]
Reverted to 0.5.1 since we should be installing the redist package, not bundling the DLLs directly

**Comment by maths22** [comment]
Actually, I'm ok with bundling the DLLs, so I'm closing this out

**Comment by qwertychouskie** [comment]
Why is this closed? The issue of no sound still has not been fixed...

**Comment by maths22** [comment]
Please re download the installer and reinstall SuperTux.  If you still have
no sound, please open a new issue describing your environment and specific
issue.
