### ISSUE TITLE
Integrate CMake changes from homebrew games upstream

### ISSUE THREAD

**Issue by tobbi** [SuperTux/supertux#614]
Homebrew games uses inreplace to change something inside our CMake file.

@maths22 I am not versed enough about CMake. Can you take a look at the change here and try to integrate it into our CMakeLists.txt file?

https://github.com/Homebrew/homebrew-games/pull/681/files#diff-fa4bb29ffcf25352095c86dec5423871R33

**Comment by maths22** [comment]
I'm inclined to instead add a flag that disables support for running from the build directory (which we would use when building releases, but not when building on our own machines)

**Comment by maths22** [comment]
Never mind the above commit.  The real issue is symlink passing to physfs

**Comment by tobbi** [comment]
Fixed with 47a353e29
