### ISSUE TITLE
Problem with the magnification option

### ISSUE THREAD

**Issue by Rusty-Box** [SuperTux/supertux#616]
Depending on which magnification you've selected, it can happen that some things that you need to see (e.g. **icecrusher** or **platforms** beneath the player, on which they have to land.) can not be seen.
That makes it sometimes difficult to create levels, but also cutscenes. Especially when using the script: `Camera.scroll_to();`

**Comment by patinhas19** [comment]
I agree

**Comment by Rusty-Box** [comment]
In case the magnification setting is going to be removed, we should use the magnification of 125% as default.

**Comment by Grumbel** [comment]
You can already look ahead with Home/End/Del/PgDn keys. Small viewing area will always be a little harder to play. As for cutscenes, just design them so that the important part is in the center of the screen.
