### ISSUE TITLE
SuperTux does not start when windows username in hebrew

### ISSUE THREAD

**Issue by yonizaf** [SuperTux/supertux#620]
**SuperTux version:** 0.5.0

**System information:** Windows 7 64 bit, Hebrew locale
##### Actual behavior

When the Windows username (or possibly user profile folder name) includes Hebrew letters, SuperTux does not start. 
##### Expected behavior

For SuperTux to launch.
##### Steps to reproduce actual behavior
1. Create a username using hebrew letters (maybe other uncommon languages has the same effect)
2. Log into the new user's desktop
3. Try to start SuperTux, it does not start, looks like nothing happens.
4.  On the same PC, create a user using just english letters, and the game works fine.
##### Additional debugging information

A folder named SuperTux gets created in %appdata%, but it's empty - no files in there.

**Comment by tiborbuzasi** [comment]
Hi!

I have the same problem too, although I am using the German locale, but my username contains the 'á' character. SuperTux version is 0.5.1 x64. Windows version is Windows 7 Professional x64. I could solve the problem by turning on the guest account, and it runs fine there.
