### ISSUE TITLE
Larger font size for TV needed

### ISSUE THREAD

**Issue by cweiske** [SuperTux/supertux#623]
**SuperTux version:** 0.4.0.16
**System information:** OUYA Android gaming console connected to a TV. Me 3 meters apart from it. SuperTux android port from http://libsdl-android.sourceforge.net/
##### Expected behavior

I can read the text without straining my eyes or bending forward
##### Actual behavior

Text is too small to be read from the couch when playing SuperTux on the TV
##### Steps to reproduce actual behavior
1. Connect computer to TV
2. Start SuperTux in fullscreen mode on TV
3. Try to read the main menu or the speech/help bubbles from the couch
##### Additional information

Might need #130 first since I think the bitmap font makes it impossible to make it larger without looking bad.

**Comment by maxteufel** [comment]
Yup. TTF support is being worked on and expected for 0.6.0/soon-ish, so we won't change anything bitmap font related for now.

**Comment by Hume2** [comment]
Well, tiles and Tux aren't much larger than font, so you'd have to stare your eyes anyway. I think that what you need is magnificating whole screen, so you can set magnification to 250% or such value.

**Comment by cweiske** [comment]
@Hume2: I could play the game fine, just reading the text was hard.

**Comment by Grumbel** [comment]
The font is already pretty large as is and if that's not enough there is a `Magnification` option in the option menu.
