### ISSUE TITLE
Don't blit each tile in one draw call

### ISSUE THREAD

**Issue by tobbi** [SuperTux/supertux#625]
We should create a texture / surface for each tilemap. That way, we can drastically reduce the draw calls, which in turn improves speed :)

Check TileMap::draw() here: https://github.com/SuperTux/supertux/blob/master/src/object/tilemap.cpp#L302

**Comment by Hume2** [comment]
Good idea, just keep in mind that the tilemap can be changed in the editor and also by scripting. So when the tilemap is changed, the surface must be updated as well.

**Comment by Grumbel** [comment]
Fixed in 5c25bdd07
