### ISSUE TITLE
ispy missing from SuperTux v0.5.0 editor

### ISSUE THREAD

**Issue by patinhas19** [SuperTux/supertux#628]
Super tux v0.5.0 the editor does not have the object ispy

**Comment by patinhas19** [comment]
Ideas for new Super tux in future
The map editor could have a script for TileMap fade when the tux is played. Type in the level editor in the secret area.

**Comment by patinhas19** [comment]
More super tux ideas in the future could have airship and tanks, with the camera still and they second opposite type super mario

**Comment by tobbi** [comment]
Can you create new issues for your other ideas, please?

**Comment by patinhas19** [comment]
OK sorry. He was referring to more tiles, because I think few


2016-10-03 0:39 GMT+01:00 Tobias Markus <notifications@github.com>:
