### ISSUE TITLE
supertux windows 64bit sound effect

### ISSUE THREAD

**Issue by amie1972** [SuperTux/supertux#632]
**SuperTux version:0.5.0
**System information:windows 10 pro 64bit *(details about your kernel, operating system, or distribution)*

in option menu,sound configurations are disabled.

**Comment by tobbi** [comment]
Please re-download the installer from https://github.com/SuperTux/supertux/releases/tag/v0.5.0 and re-run it. See if this fixes the problem

Where did you download the installer from in the first place?

**Comment by tobbi** [comment]
This is a duplicate of #613, anyway.

**Comment by amie1972** [comment]
By the way in issue #613,this is corrected.
