### ISSUE TITLE
Enemies which fall off the map do not count as kills

### ISSUE THREAD

**Issue by Wuzzy2** [SuperTux/supertux#64]
Enemies which fall off the map do not count as kills.
This is the case even for Mr. Iceblock (and similar enemies) if you actively knocked him away.

This is really counter-intuitive and probably not really intended anyways.

I used commit bc7fab7.

**Comment by Hume2** [comment]
Fixed.

**Comment by tobbi** [comment]
Fixed in commit 6314475. Thanks, Hume!

While I'm at it, one other thing: Please make sure you use 2 spaces for indentation and one spaces before the curly brackets, in accordance to our code style guide. Thanks.
