### ISSUE TITLE
theme.music doesn't loop correctly

### ISSUE THREAD

**Issue by Rusty-Box** [SuperTux/supertux#642]
When you're listening to the music in the main menu (menu.stl), I noticed that there is a gap of silence before the loop.

**Comment by danylopez123** [comment]
I would recomend they make the loops for the sample numbers, you know what im saying

**Comment by maxteufel** [comment]
> you know what im saying

no

**Comment by PrinceRilian** [comment]
I have not noticed that yet when listening to the music on the main menu.  However, I have noticed that the song "wisphunt.ogg" does not loop correctly when it was playing in one of the levels I created, while "wisphunt.music" _does_ loop correctly.  As such, I am noticing the same "gap" when "wisphunt.ogg" loops over.  Looks_ like that's another thing they'll need to fix!

**Comment by qwertychouskie** [comment]
The .music files are XML files that call the .oggs, but contain the information on how to loop correctly.  if the .music loops correctly, then that should be fine.

**Comment by PrinceRilian** [comment]
I was WONDERING what the difference between those two were!  That explains a lot.  So would it be better to use the .music files rather than the .ogg files?

**Comment by qwertychouskie** [comment]
Yep.

**Comment by maxteufel** [comment]
.ogg files will just loop like when you enable repeat in your favorite audio player (they do not contain and will not contain any information about loops), .music files contain information about a track-specific A-B-loop. That's not an issue, what is an issue is if levels do not use .music files when available or when the information in the .music files is wrong such as pointed out by @Rusty-Box.

**Comment by tobbi** [comment]
Closed in 0116c56
