### ISSUE TITLE
Support binary relocation

### ISSUE THREAD

**Issue by maxteufel** [SuperTux/supertux#649]
Paths shouldn't be hardcoded into the binaries.

Ref: #648 ("Please provide an AppImage for SuperTux")
Ref: probonopd/AppImages#113 ("Creating a SuperTux AppImage: Debian package uses the installation prefix /usr/local and it causes problems")

**Comment by probonopd** [comment]
See https://github.com/limbahq/binreloc for a library which makes this easy.

**Comment by maxteufel** [comment]
I doubt we need an entire library for that. But that's just the description that might be misleading. This seems to be more like a public domain snippet for use in a project, which is probably what we want in SuperTux (remove all the unnecessary parts of it).

**Comment by maths22** [comment]
We actually do support relocation-the only absolute path in the executable is the path to the development data directory (which we should probably support compiling without)

**Comment by probonopd** [comment]
@maths22 is the same also true for the dependencies?

**Comment by maths22** [comment]
@probonopd To the best of my knowledge, yes.

**Comment by probonopd** [comment]
You are right, it's what I'm using for [the AppImage](https://github.com/probonopd/AppImages/blob/master/recipes/meta/SuperTux2.yml). So I think this can be closed.
