### ISSUE TITLE
Use SQRat

### ISSUE THREAD

**Issue by christ2go** [SuperTux/supertux#650]
The use of a squirrel binding library like SQRat will lead to the exposed classes being first class squirrel citizens, e.g. you'll be able to change attributes values from squirrel. It will further reduce code complexity and less automatically generated code.

*Changed 3rd November 21:25: Use SQRat instead of SQPlus (it's not compatible with Squirrel version 3)*

**Comment by maxteufel** [comment]
@christ2go Can you tell us more about the status of this? Even if you didn't do a lot about this (or nothing at all), just tell us.

**Comment by tobbi** [comment]
Superseded by #2792
