### ISSUE TITLE
Auto-generated, hosted doxygen documentation

### ISSUE THREAD

**Issue by maxteufel** [SuperTux/supertux#652]
We should set up Travis to automatically build doxygen documentation when building, and then upload that to a separate repository hosted by GitHub pages.

**Comment by christ2go** [comment]
We could additionally also host the documentation at https://codedocs.xyz, it gets automatically generated from the master branch with every pull request ([an example from my fork](https://codedocs.xyz/christ2go/supertux/ ))

**Comment by tobbi** [comment]
Sounds like a good idea!

**Comment by tobbi** [comment]
codedocs.xyz documentation: https://codedocs.xyz/SuperTux/supertux/index.html You good with this?

**Comment by maxteufel** [comment]
Implemented via codedocs.xyz as mentioned in https://github.com/SuperTux/supertux/issues/652#issuecomment-400475346.
