### ISSUE TITLE
SuperTux is not working.

### ISSUE THREAD

**Issue by GumSkyloard** [SuperTux/supertux#657]
**SuperTux version: 0.5.1**
**System information:** *Windows 7 Ultimate, 64 bits.*

Hi.. I installed SuperTux, just so I could play and have a good time.. But yeah, it didn't go well..
I tried to open it. No results. Changed compatibility mode to Windows Server 2008 (that was the lowest one I could use.) Still not working. Tried to check the Task Manager and opened it. No life signal..
Tried to same with the 32-bit version of ST. Changed the compatibility mode to Win 95 (which was the lowest) and nothing. Task Manager, no life. Nothing.. 

Thanks for reading, and I hope you can help!

**Comment by maths22** [comment]
@GumSkyloard Please open the following directory `%appdata%\SuperTux\supertux2` (Windows key + r, then paste that path) and share your console.err file (you can attach it to this issue)

**Comment by GumSkyloard** [comment]
There is a problem.. there is nothing.
Nothing at all on that folder. It does exist, but it says that the folder is empty. 
This smells fishy.

**Comment by tobbi** [comment]
Do you have experience with using a debugger? If so, you could try and start SuperTux in it, then find out what's wrong.

**Comment by maxteufel** [comment]
Please reopen this issue if you have more details, @GumSkyloard.
