### ISSUE TITLE
Dispenser/Cannon: Collision behavior is broken

### ISSUE THREAD

**Issue by maxteufel** [SuperTux/supertux#659]
Jumping on top of a cannon and trying to jump back off it again exhibits broken collision behavior. This most likely happens since commit da2f100351241558e2d1dbaf0a78cfc5fffa336f and can be seen in levels like 'HMS Snowball Ahoy!' (see forum).

**Comment by Hume2** [comment]
I can't reproduce this.

**Comment by maxteufel** [comment]
Can't reproduce this anymore either.

**Comment by Hume2** [comment]
Makes sense, because that commit was supposed to fix this bug.
