### ISSUE TITLE
Reset Progress of Story Mode and Add-Ons in Game

### ISSUE THREAD

**Issue by Rusty-Box** [SuperTux/supertux#661]
It should be possible to reset the progress of the story mode and the different add-ons via the main menu, instead of having to delete the .stsg files manually.

**Comment by tobbi** [comment]
I'll assign this to myself, preliminarily. If I don't work on this within a reasonable timeframe, feel free to reassign this to someone else instead of nagging me about it.

**Comment by maxteufel** [comment]
Cheat menu contains code for resetting worlds, that might be helpful.

**Comment by ShadevKits** [comment]
Though the cheat menu would mean heading into the code anyways if it is not enabled.

**Comment by Rusty-Box** [comment]
There should also be a warning dialouge added when reseting one progress (except for doing it via the cheat menu) asking the player if they are sure to reset their prgress.
