### ISSUE TITLE
for the super tux v0.6.0 

### ISSUE THREAD

**Issue by supercookiemonster** [SuperTux/supertux#665]
The super tux v0.5.1 level editor does not have the ispy object.
The snow mountain is a bit difficult to fit the tiles.

**Comment by tobbi** [comment]
ispy was added after 0.5.0 and will be available in the next major (or bugfix) release. We forgot to include it in 0.5.1. See a53b351f0cef2e70991d4072a5a59c192ceb791c for the revision that fixed this.

As for the snowmountain tileset, yes: I know that it's very difficult to use sometimes. We'd need a graphic designer to fix this. If you know anyone who'd like to work on this for free (we don't have any funds), feel free to contact us.

**Comment by supercookiemonster** [comment]
As he had said the tiles snow mountain did not fit with each other. Like he said he needed designers. 
I decided to make other blocks almost equal, these fit, but they are not with a good design. 
But I hope I have helped.
![snow montain 1 no editor](https://cloud.githubusercontent.com/assets/24629244/21626273/13937062-d208-11e6-812d-5c4eb187e757.png)
![snow montain 1](https://cloud.githubusercontent.com/assets/24629244/21626277/152e41ae-d208-11e6-87c5-d784cc7f3570.png)
![snow montain 2](https://cloud.githubusercontent.com/assets/24629244/21626275/1475635a-d208-11e6-8fda-75d44227ca63.png)

**Comment by tobbi** [comment]
@maxteufel thoughts?

**Comment by Rusty-Box** [comment]
imo, it looks really great.

**Comment by maxteufel** [comment]
I like it too. What @Rusty-Box said, plus we could use some more slope tiles, decoration, etc.

**Comment by tobbi** [comment]
@supercookiemonster How much do you enjoy making graphics? If you're interested, you can join our ever-evolving team of highly-skilled graphics artists here at SuperTux and make creating graphics for the game your passion ;)

**Comment by supercookiemonster** [comment]
I really like making computer graphics. And I also know a little bit of 3D animation.
I would love to help.
The level of The Castle of Nolok on icyisland island
It's very empty, it needs parallels.
I would like to help with this.

**Comment by Rusty-Box** [comment]
@supercookiemonster  Maybe also some pillars as background tiles.

**Comment by supercookiemonster** [comment]
Here are more snowmontain tiles, and the same compounds. 
![snow montain 1](https://cloud.githubusercontent.com/assets/24629244/21693304/55962ede-d378-11e6-8dd9-48ed4820a7ab.png)
![snow montain 2](https://cloud.githubusercontent.com/assets/24629244/21693305/559a064e-d378-11e6-952e-bf67fbcb3399.png)
![snow montain 3](https://cloud.githubusercontent.com/assets/24629244/21693306/559d4a20-d378-11e6-8873-0f32e10df743.png)
![snow montain no editor](https://cloud.githubusercontent.com/assets/24629244/21693307/559e3e26-d378-11e6-985b-b6e3b635de1d.png)

As in the castle could give an idea of ​​lava fall. Like the images (Type waterfall).

![lava in castle](https://cloud.githubusercontent.com/assets/24629244/21693406/b933c258-d378-11e6-9f5b-514d1b1dd0f4.png)

![lava-1](https://cloud.githubusercontent.com/assets/24629244/21693357/7fe25f32-d378-11e6-9778-c22c73d68794.png)
![lava-2](https://cloud.githubusercontent.com/assets/24629244/21693356/7fdfd5a0-d378-11e6-8205-1f3642d611da.png)
![lava-3](https://cloud.githubusercontent.com/assets/24629244/21693359/7fe454ae-d378-11e6-96f8-12e44654d58c.png)
![lava-4](https://cloud.githubusercontent.com/assets/24629244/21693358/7fe3a702-d378-11e6-8551-fbe0244d14cd.png)

**Comment by Rusty-Box** [comment]
I don't think that using a lava fall in an ice castle is a smart idea (don't think that nolok is so stupid)
But this could be used in other castles. :)
And about the Mountain tiles: I can still see some tiny cut offs by the slopes and in the general stone pattern. Especially in the top right and the top left of the second screenshot. But it's getting better.
