### ISSUE TITLE
walk through walls

### ISSUE THREAD

**Issue by kompowiec** [SuperTux/supertux#667]
**SuperTux version:** 0.5.1
0.5.1 developent edition
**System information:**
Debian Stretch 9
##### Expected behavior
Not should walk through walls
##### Actual behavior
https://www.twitch.tv/kompowiec2/v/108697486
here is better visible: https://www.twitch.tv/kompowiec2/v/108702330
##### Steps to reproduce actual behavior
proably related with this bug: http://www.speedrun.com/st/guide/afj1z
##### Additional debugging information
i try used gdb but generation file have 143 MB and even can't run.... ;]

**Comment by brmbrmcar** [comment]
devs gonna shoot you

**Comment by tobbi** [comment]
@brmbrmcar If you keep posting this non-essential nonsense on bugreports, I am gonna block you from commenting, final warning!

**Comment by Rusty-Box** [comment]
Is this still an occuring issue or can this be closed?

**Comment by HybridDog** [comment]
It still happens: https://github.com/SuperTux/supertux/files/3257177/vid-2019-06-05_14.26.42.mp4.zip

**Comment by Semphriss** [comment]
I can confirm this issue still happens - do we still want to fix it though? It doesn't seem like it can easily happen by accident, it leaves a difficult but funny quirk for hardcore fans and speedrunners

**Comment by Semphriss** [comment]
Given inactivity, I'll close this.

**Comment by Alasdairbugs** [comment]
it is highly unlikely any casual player will come across this gimmick, given putting yourself in out of bounds is A: Subpixel precise (seriously) and B: you can only move UP once out of bounds... you cannot "walk" through walls like this issue suggests, pressing left or right instantly kills you.
