### ISSUE TITLE
SuperTux 0.3.5 - MSVCR120D.dll not found

### ISSUE THREAD

**Issue by crpradio** [SuperTux/supertux#68]
![tuxscreenshot](https://cloud.githubusercontent.com/assets/600632/7429579/00793292-f004-11e4-87d8-f8efaf8c8097.png)

**Comment by JanMiddelkoop** [comment]
I'm running into the same problem on Windows 7 64-bit.  SuperTux is looking for the MSVCR120D.dll file, but can't find it.  The "D" at the end of the filename seems to suggest the released .exe is compiled in debug mode, rather than release mode.

**Comment by Flakebi** [comment]
I'm sorry for that inconvenience, we will hopefully release a fixed version in the next days. :-)

Some background information:
SuperTux was compiled in release mode, unfortunately Visual Studio decided to link against the debug libraries too because `strdup` was used. Replacing that calls from the source code fixed it.

**Comment by tobbi** [comment]
Please check if the just-released version of 0.3.5a fixes it.

**Comment by crpradio** [comment]
Where can I find the version of 0.3.5a (exe file)?

**Comment by Flakebi** [comment]
You can find the installers [here](https://github.com/SuperTux/supertux/releases/tag/v0.3.5a)

**Comment by crpradio** [comment]
thx

**Comment by tobbi** [comment]
Can you verify that it worked?

**Comment by JanMiddelkoop** [comment]
I can.  It works, I do however see a debug console window with a warning from "supertux\src\addon\addon_manager.cpp", "120 parsing repository.nfo failed".  System cannot find the path specified.  Should I create that as a seperate issue?

**Comment by maxteufel** [comment]
Yes, that's a different issue.
