### ISSUE TITLE
Use different level name colors

### ISSUE THREAD

**Issue by Rusty-Box** [SuperTux/supertux#680]
How about giving "special" types of levels a different name color instead of just white?

Examples:
- Boss level names could be red
- Bonus level names are yellow

**Comment by ShadevKits** [comment]
I think those are implemented into Incubator Island, but otherwise aren't they already possible in v0.5.1?

**Comment by tobbi** [comment]
Does this need a manual assignment or an automatic one? I'd say manual because automatic might be too difficult. As @ShadevKits mentioned, we just need to assign the color variable properly. 

Instead of using colours, couldn't we use icons to depict the different level categories?

**Comment by Rusty-Box** [comment]
@tobbi We could use both. But I think it's a bit unnecessary to give every level name an icon. Since most of the level are the same type. Normal levels

**Comment by tobbi** [comment]
What about only highlighting bonus and boss levels in a specific way? Maybe apply a text effect to those?

**Comment by Rusty-Box** [comment]
@tobbi What kind of text effect do you have in mind?

**Comment by tobbi** [comment]
It was mostly a brain fart, but:
Boss levels look intimidating.

And bonus levels look "special". My thought was: Apply the Tux invincibility effect (with the stars) on the level name to indicate it's "special".

**Comment by Rusty-Box** [comment]
We shouldn't highlight level names too much. I think a color switch would be enough imo.

**Comment by tobbi** [comment]
Problem is that, since level / worldmap authors can define arbitrary colours for level names, the player has no way to rely on that information. I know it's only a minor problem, but still...

**Comment by ShadevKits** [comment]
Good point @tobbi . I do have an idea.

For each worldmap, possibly could they contain an index/info file readable from the game directly? It would be accessible when visiting the world for the first time, then if you wanted to see it again, you could simply press a button on the worldmap. Would that work?

**Comment by Rusty-Box** [comment]
Closing this. Letting this up for people to decide for their own. For the main game (story mode) bonus level names get colored yellow and bosses get a color fitting the boss (e.g. cold grey for the yeti).
