### ISSUE TITLE
SuperTux glitches out when minimized

### ISSUE THREAD

**Issue by Dumbbird1** [SuperTux/supertux#682]
**SuperTux version: 0.5.1
**System information: Windows 10 64 Bit
**Steps to reproduce actual behavior: Minimize and maximize SupTux.

Whenever I minimize Supertux and then maximize it, the window is glitched out.

**Comment by tobbi** [comment]
I thought I'd written a comment in this here, but can you please attach a screenshot of how it looks when it glitches out?

**Comment by ShadevKits** [comment]
I have the same problem, except it only occurs when I press Alt + Tab (Switches from application to application)

**SuperTux v0.5.1
**System info: Windows 8 64 bit
**Steps to reproduce behavior: Press Alt + Tab while in SuperTux.

**Comment by maxteufel** [comment]
Please post a comment here if you have detailed information. Closing for now due to inactivity.
