### ISSUE TITLE
Be able to grab frozen enemies

### ISSUE THREAD

**Issue by Rusty-Box** [SuperTux/supertux#683]
Tux should be able to grab frozen enemies and they should break once you throw them on other enemies and/or against a wall and on the ground. (Similar to new super mario bros wii)

**Comment by ShadevKits** [comment]
Great idea. However, since the game is based on Antarctica, then probably not frozen enemies should be able to be picked up. However, we still have the ice cube and bomb that can be picked up so far.

**Comment by Rusty-Box** [comment]
In case we're making frozen enemies grab able, I recommend changing the frozen sprites, to look like this:
![frozen](https://cloud.githubusercontent.com/assets/20615048/26829110/70d6d766-4ac4-11e7-86a2-bd633bc18c4d.png)

**Comment by tobbi** [comment]
Hey, good idea.

**Comment by Rusty-Box** [comment]
We must also edit the collisions a bit for that, I think.

**Comment by tobbi** [comment]
Would you be prepared to draw those sprites for all suitable enemies?

**Comment by Rusty-Box** [comment]
I can do that.

**Comment by weluvgoatz** [comment]
Assign this to me, I've decided to work on it again.

**Comment by LizzyBach** [comment]
That'll be really cool.

**Comment by mrkubax10** [comment]
Fixed by #1832
