### ISSUE TITLE
Improve climbing feature

### ISSUE THREAD

**Issue by Rusty-Box** [SuperTux/supertux#684]
The way of how the current climbing feature works, is pretty much useless for levels, since you can't really use it for much stuff, instead of going up and down.
Sure, that's what climbing is, however its current state makes it kind of hard to combine it with proper level design. So that's why I think, that it needs improvements.

Tux should be able to jump further, so that the climbing feature could be used for cliff jumping from robe to robe, for example and should (maybe) move a little bit faster while climbing in general.
Also, it might just happens to me, but Tux always directly switch to his climbing state.

**Comment by serano01** [comment]
At least the sprites should be completely redone, I think.

**Comment by Alzter** [comment]
Definitely. You don't gain any height when letting go of ladders, and the action button unnecessarily makes you let go. And the sprites are crap. I may redo them.

**Comment by tobbi** [comment]
@Rusty-Box Is this fixed now that #1313 is merged?

**Comment by Rusty-Box** [comment]
Yes, having a normal jump height from ladders makes them much more useable.
Closing this.
