### ISSUE TITLE
Ghost enemy sprites

### ISSUE THREAD

**Issue by patinhas19** [SuperTux/supertux#687]
I made a badguy for the ghost forest. 
I made a ghost that may have the zeekling sprite.
![burning-0](https://cloud.githubusercontent.com/assets/22308454/22981388/35a7a6f2-f394-11e6-850e-396078c275b8.png) ![burning-1](https://cloud.githubusercontent.com/assets/22308454/22981389/35a7ffbc-f394-11e6-8253-19f53a01facc.png) ![burning-2](https://cloud.githubusercontent.com/assets/22308454/22981391/35ac0b7a-f394-11e6-863e-8d6939342cac.png) ![burning-3](https://cloud.githubusercontent.com/assets/22308454/22981392/35ad4b5c-f394-11e6-8f2e-e47cc97f8a78.png) ![burning-4](https://cloud.githubusercontent.com/assets/22308454/22981390/35a9475a-f394-11e6-977e-d122ebdd3ae3.png) ![burning-5](https://cloud.githubusercontent.com/assets/22308454/22981387/35a61dbe-f394-11e6-848d-e4014ae5d20a.png) ![burning-6](https://cloud.githubusercontent.com/assets/22308454/22981393/361a6d2c-f394-11e6-92af-0929b61c4b6e.png) ![burning-7](https://cloud.githubusercontent.com/assets/22308454/22981395/3621fb28-f394-11e6-987d-e3b25cca412d.png) ![diving](https://cloud.githubusercontent.com/assets/22308454/22981394/361da2f8-f394-11e6-80b2-2455c1f7b04e.png) ![frozen](https://cloud.githubusercontent.com/assets/22308454/22981396/362667a8-f394-11e6-9aa8-19eb6b7df7c5.png) ![left-0](https://cloud.githubusercontent.com/assets/22308454/22981419/4931cab8-f394-11e6-823a-9a0c28854e53.png)
![left-1](https://cloud.githubusercontent.com/assets/22308454/22981416/492553c8-f394-11e6-8f28-f1d0f14932a0.png) ![left-2](https://cloud.githubusercontent.com/assets/22308454/22981418/4930f08e-f394-11e6-96ac-6e5ec8d3ee97.png) ![left-3](https://cloud.githubusercontent.com/assets/22308454/22981417/49278260-f394-11e6-913a-89808d550798.png) ![squished](https://cloud.githubusercontent.com/assets/22308454/22981420/49321108-f394-11e6-8197-73db475c111f.png)

Sprite:
; Ghost 
(supertux-sprite (action  (name "left")  (hitbox 8 19 31 30)  (images "left-0.png"   "left-1.png"  "left-2.png"   "left-3.png"))
 (action  (name "right")  (hitbox 25 19 31 30)  (mirror-action "left"))
 (action  (name "iced-left")  (hitbox 8 19 31 30)  (images "frozen.png"))
 (action  (name "iced-right")  (hitbox 25 19 31 30)  (mirror-action "iced-left"))
 (action  (name "squished-left")  (hitbox 8 19 31 30)  (images "squished.png"))
 (action  (name "squished-right")  (hitbox 25 19 31 30)  (mirror-action "squished-left"))
 (action  (name "diving-left")  (hitbox 6 20 31 30)  (images "diving.png"))
 (action  (name "diving-right")  (hitbox 27 20 31 30)  (mirror-action "diving-left") )
 (action  (name "burning-left")  (hitbox 8 19 31 30)  (fps 15)  (images "burning-0.png"   "burning-1.png"
   "burning-2.png"   "burning-3.png"   "burning-4.png"   "burning-5.png"   "burning-6.png"   "burning-7.png"))
 (action  (name "burning-right")  (hitbox 25 19 31 30)  (fps 15)  (mirror-action "burning-left"))
)

I hope you enjoy

**Comment by patinhas19** [comment]
I improved the ghosttree a little by taking out the scribbles and made a new root. I hope I have helped.
**The link to the zipped files is:** 
[https://www.dropbox.com/s/7dl0bhzp4aaijmq/new%20ghosttree.zip?dl=0]
# **Before**
![ghosttree](https://cloud.githubusercontent.com/assets/22308454/23467439/eff9feae-fe95-11e6-8089-9feece51de79.png)
![root](https://cloud.githubusercontent.com/assets/22308454/23467454/fbb7a228-fe95-11e6-974e-bcc776c97e05.png)

# **After**
![ghosttree](https://cloud.githubusercontent.com/assets/22308454/23467411/df2f0b50-fe95-11e6-9b0c-ef4127991cc6.png) 
![root](https://cloud.githubusercontent.com/assets/22308454/23467464/04ebe5e8-fe96-11e6-9e73-d920036fc565.png)

**Comment by maxteufel** [comment]
@Rusty-Box has also been working on similar sprites.

**Comment by patinhas19** [comment]
The ghosttree has the same sprites, so I do not have to make new ones because I think the ghosttree is good at everything. It was only the designer that had to be improved.

**Comment by patinhas19** [comment]
I have an idea that enemy nolok should be the final boss of everything. How did he kidnap the penny.

**Comment by Rusty-Box** [comment]
Since this is not considered to be used for the game as it is off from the games art style I am closing this.
