### ISSUE TITLE
Rock/Moss Crusher makes no sound when hitting the ground

### ISSUE THREAD

**Issue by Rusty-Box** [SuperTux/supertux#689]
Once the rock/moss crusher is hitting the ground, there is no sound playing.

**Comment by tobbi** [comment]
This is actually weird. Can anyone else reproduce this? I am hearing the sound just fine on my machine. Maybe I forgot to commit a file.

**Comment by tobbi** [comment]
For the record:
```
[WARNING] supertux\src\audio\sound_manager.cpp:195 Couldn't play sound sounds/thud.ogg: Couldn't fill audio buffer: Invalid Value
```

According to the OpenAL Programmers Guide located here:
https://www.openal.org/documentation/OpenAL_Programmers_Guide.pdf
the issue occurs when "the size parameter is not valid for the format specified, the buffer is in use, or the data is a NULL pointer".

**Comment by tobbi** [comment]
@Rusty-Box Can you please check that this works as expected? I can tell it works on my system.

**Comment by Rusty-Box** [comment]
@tobbi It works.
