### ISSUE TITLE
SuperTux crashes when opening a new level

### ISSUE THREAD

**Issue by sirtomato999** [SuperTux/supertux#695]
**SuperTux version:**
0.5.1
**System information:** *
Arch Linux 
`uname -a`
Linux matthew-arch 4.10.6-1-ARCH #1 SMP PREEMPT Mon Mar 27 08:28:22 CEST 2017 x86_64 GNU/Linux

##### Expected behavior
Add stuff to a new level
##### Actual behavior
SUPERTUX CRASHES
##### Steps to reproduce actual behavior
Create a level in level editor
##### Additional debugging information

I put in everything, i dont know what will be useful or not
```[matthew@matthew-arch ~]$ journalctl -xe
Hint: You are currently not seeing messages from other users and the system.
      Users in groups 'adm', 'systemd-journal', 'wheel' can see all messages.
      Pass -q to turn off this notice.
                                                      #6  0x00007f5429563fe8 n/a
                                                      #7  0x00007f5434e8c2e7 sta
                                                      #8  0x00007f543539354f __c
                                                      
                                                      Stack trace of thread 1165
                                                      #0  0x00007f5434e95296 do_
                                                      #1  0x00007f5434e95354 __n
                                                      #2  0x00007f5436e46bee n/a
                                                      #3  0x00007f5436e46d45 n/a
                                                      #4  0x00007f5436df57fc n/a
                                                      #5  0x00007f5436df543c n/a
                                                      #6  0x00007f5436e468e9 n/a
                                                      #7  0x00007f5434e8c2e7 sta
                                                      #8  0x00007f543539354f __c
-- Subject: Process 11656 (supertux2) dumped core
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- Documentation: man:core(5)
-- 
-- Process 11656 (supertux2) crashed and dumped core.
-- 
-- This usually indicates a programming error in the crashing program and
-- should be reported to its vendor as a bug.
lines 3106-3128/3128 (END)
                                                      #6  0x00007f5429563fe8 n/a (libpulsecommon-10.0.so)
                                                      #7  0x00007f5434e8c2e7 start_thread (libpthread.so.0)
                                                      #8  0x00007f543539354f __clone (libc.so.6)
                                                      
                                                      Stack trace of thread 11657:
                                                      #0  0x00007f5434e95296 do_futex_wait.constprop.1 (libpthread.so.0)
                                                      #1  0x00007f5434e95354 __new_sem_wait_slow.constprop.0 (libpthread.so.0)
                                                      #2  0x00007f5436e46bee n/a (libSDL2-2.0.so.0)
                                                      #3  0x00007f5436e46d45 n/a (libSDL2-2.0.so.0)
                                                      #4  0x00007f5436df57fc n/a (libSDL2-2.0.so.0)
                                                      #5  0x00007f5436df543c n/a (libSDL2-2.0.so.0)
                                                      #6  0x00007f5436e468e9 n/a (libSDL2-2.0.so.0)
                                                      #7  0x00007f5434e8c2e7 start_thread (libpthread.so.0)
                                                      #8  0x00007f543539354f __clone (libc.so.6)
-- Subject: Process 11656 (supertux2) dumped core
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- Documentation: man:core(5)
-- 
-- Process 11656 (supertux2) crashed and dumped core.
-- 
-- This usually indicates a programming error in the crashing program and
-- should be reported to its vendor as a bug.```


###

**Comment by maxteufel** [comment]
Hey @wozzes, can you use `coredumpctl list` to see if you still have the full coredump, then `coredumpctl gdb [THE NUMBER THAT IS IN THE PID COLUMN OF THE LIST]`, the copy the complete output of `bt full` here.

**Comment by PrinceRilian** [comment]
The level editor is crashing for me too as well, same release version (0.5.1).  However, I am using the Windows edition.  The crash always occurs upon pressing the "Test Level" button on the level editor.  I have also noticed that it crashes the program when selecting any level I saved with the level editor that shows up under the list of "Contrib Levels".  However, there is one notable exception.  _I have been able to play the levels_ I originally designed from the 2003 version of SuperTux on my Debian 8 Linux System after porting them over to Windows, modify the background music (as I noticed it always defaulted to "Mortimer's Chip Disko" for each level after the transfer to Windows, and I wanted a variety of background music specific to the levels I made), respecifying which enemies stay on platforms all over again (that too did not transfer over), and resaving the level.

**Comment by tobbi** [comment]
@PrinceRilian Can you try to get a backtrace of the crash using the steps mentioned here:
https://wiki.documentfoundation.org/How_to_get_a_backtrace_with_WinDbg 

You can skip the step about the debugging symbols. We do not provide debugging symbols. I wonder whether it's possible to do so (@maxteufel: Any ideas?)

Even the name of the function should give us some insight into what is wrong.

**Comment by PrinceRilian** [comment]
[backtrace.txt](https://github.com/SuperTux/supertux/files/1002100/backtrace.txt)

I have it right there.

**Comment by tobbi** [comment]
That looks like it exited normally. Can you try again to get one where it really crashes? The exit code shouldn't be 0.

**Comment by PrinceRilian** [comment]
Well, the program malfunctioned at that point, and it just plain shut
itself down nonetheless.  I will also mention that I didn't get any error
boxes when the malfunction happened.  I also have an update to the
situation: not long ago, I tested another level that I made myself on the
level editor, this one with a Forest theme rather than an Antarctic theme.
The level did not crash when tested.  But my original Antarctic themed
level still crashes when tested!  And, like before, it crashes both when
selected from my level set menu under "Contrib Levels" and when given a
test run in the Level Editor.  The Forest theme level works just fine for
some reason.

**Comment by tobbi** [comment]
Can you attach or pastebin the level that crashes so that I can take a look?

**Comment by PrinceRilian** [comment]
This is the one.

Terry

**Comment by tobbi** [comment]
Hey. This didn't work. I can't see the level.

**Comment by PrinceRilian** [comment]
I can see the level on my computer and am *still* trying to figure out why
you aren't seeing it.  Perhaps you should test the other level I was
working with?  That's the forest level.  That one didn't give me a
problem.  Let's see if it works for you.

**Comment by qwertychouskie** [comment]
When sending it though email, attachments are stripped.

**Comment by PrinceRilian** [comment]
OK, I sent it through GitHub this time--both of them.  Since I was using just my e-mail for the last week and did not actually log in to GitHub--I can see that my attachments for the levels themselves didn't go through.  Yes, that explains a lot!

[worldmap.zip](https://github.com/SuperTux/supertux/files/1038414/worldmap.zip)

**Comment by tobbi** [comment]
@PrinceRilian: The first one doesn't work because of this:
```
[FATAL] supertux/src/supertux/game_session.cpp:155 Couldn't start level: Couldn't find main sector
```

SuperTux levels must have a _main_ sector, otherwise, they won't start. I think I will change the behaviour towards starting the first sector available if no _main_ sector can be found.

**Comment by Rusty-Box** [comment]
@sirtomato999 Is this a still occuring issue?

**Comment by tobbi** [comment]
I'm gonna close this due to lack of response (and to decrease the size of our issues list). Feel free to comment should the issue ever occur again.
