### ISSUE TITLE
How do I install the latest version of supertux on debian7?

### ISSUE THREAD

**Issue by redapple0204** [SuperTux/supertux#700]
When I tried to install the latest version, I got a OpenGL error

**Comment by maxteufel** [comment]
Hi there, @redapple0204.

First, Debian 7 seems quite old for gaming, you might be better off upgrading to Debian 8.

Anyway, in order for us to help you, we need some more information like how you installed the latest version of SuperTux (from where?) and what exactly that error says. Details about your setup might be helpful too.

**Comment by redapple0204** [comment]
@maxteufel thank you for your reply!
When I installed version 0.5.1 on debian7, when I executed ./configure, I got this error
> -- Check if the system is big endian - little endian
CMake Error at /usr/share/cmake-2.8/Modules/FindBoost.cmake:1194 (message):
  Unable to find the requested Boost libraries.

>  Unable to find the Boost header files.  Please set BOOST_ROOT to the root
  directory containing Boost or BOOST_INCLUDEDIR to the directory containing
  Boost's headers.
Call Stack (most recent call first):
  CMakeLists.txt:121 (FIND_PACKAGE)


> -- Found PkgConfig: /usr/bin/pkg-config (found version "0.26") 
-- checking for one of the modules 'sdl2>=2.0.1'
CMake Error at /usr/share/cmake-2.8/Modules/FindPkgConfig.cmake:363 (message):
  None of the required 'sdl2>=2.0.1' found
Call Stack (most recent call first):
  CMakeLists.txt:134 (PKG_SEARCH_MODULE)


> -- checking for one of the modules 'SDL2_image>=2.0.0'
CMake Error at /usr/share/cmake-2.8/Modules/FindPkgConfig.cmake:363 (message):
  None of the required 'SDL2_image>=2.0.0' found
Call Stack (most recent call first):
  CMakeLists.txt:135 (PKG_SEARCH_MODULE)


> -- Could NOT find OpenGL (missing:  OPENGL_gl_LIBRARY) 
CMake Error at /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:97 (MESSAGE):
  Could NOT find OpenAL (missing: OPENAL_LIBRARY OPENAL_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:288 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-2.8/Modules/FindOpenAL.cmake:97 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:167 (FIND_PACKAGE)


> -- Configuring incomplete, errors occurred!

And then I tried to install the 0.3.x version (because I copied the archive from the windows only supports the lowest 0.3.x version), when I created a build directory and then follow the tips in the implementation of cmake inside, I You get another mistake

> -- Found Threads: TRUE  
CMake Error at /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:97 (MESSAGE):
  Could NOT find SDL (missing: SDL_LIBRARY SDL_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:288 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-2.8/Modules/FindSDL.cmake:172 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:69 (FIND_PACKAGE)


> -- Configuring incomplete, errors occurred!

In fact, I have a few times before upgrading debian8 have a mistake, so I did not want to upgrade.
But if it is not true, how to put my archive under windows (5.x version) on the 1.x version of it? I do not want to lose my progress.
thanks for your help

**Comment by maxteufel** [comment]
@redapple0204 You're supposed to read the [Building guide](https://github.com/SuperTux/supertux/wiki/Building) on our wiki before you try to do that! If you follow it (install the dependencies, use cmake), everything should work fine.

I'm closing this issue for now but if you have any problems with that process please tell us by adding another comment to this.
