### ISSUE TITLE
Issue when selecting multiple tiles

### ISSUE THREAD

**Issue by Rusty-Box** [SuperTux/supertux#708]
Something that I always forgot to mention, but this is a bit of a problem.
Since it was changed, that the tiles follow the grid when moving them around with the mouse, it became worse selecting multiple tiles which are placed in a level. (see screenshot)
The tiles often bug around which can be very annoying when trying to copy a "structure" of tiles to use it again.

![supertux2 2017-06-05 00-12-12-57](https://cloud.githubusercontent.com/assets/20615048/26765869/467ac1c0-4985-11e7-9edb-734168ea764e.png)

**Comment by tobbi** [comment]
This makes selecting tiles really unusable. @Rusty-Box Do you know, by any chance, when the change was introduced?

**Comment by Rusty-Box** [comment]
@tobbi Sadly I don't.

**Comment by Rusty-Box** [comment]
@tobbi Shouldn't this one be fixable without knowing when it was introduced?

**Comment by tobbi** [comment]
Yes, but it's easier finding the culprit by knowing when the issue was introduced.

Alright, I guess ``git bisect`` to the rescue.

**Comment by tobbi** [comment]
Something is wrong with this code:
https://github.com/SuperTux/supertux/blob/master/src/editor/input_center.cpp#L629

**Comment by tobbi** [comment]
Tilemaps that have a path attached to them still display that issue.
