### ISSUE TITLE
Please don't do point releases that are versioned below the currently releases version

### ISSUE THREAD

**Issue by svenstaro** [SuperTux/supertux#71]
You just released 0.3.5a which means 0.3.5alpha which and 0.3.5a < 0.3.5. As a package maintainer I would like to ask you to make incremental releases instead and do 0.3.5.1 or even 0.3.6 since semantically, the last digit is a patch release.

Hopefully this doesn't come across as smug. I just noticed this and it will causes an inconvenience for other package maintainers as well so I decided to give you a heads-up.

**Comment by maxteufel** [comment]
OpenSSL does the same, I don't expect that to cause big problems. (@svenstaro: You're the Arch packager, right? The openssl packager is actually doing a.b.c**.**d, which, in pacman, is > a.b.c)

Anyway, I think our versioning scheme is broken. Instead of doing releases like (0.3.5, 0.3.6), there should be 0.3.0 (0.3.x for patches) and then 0.4.x and so on.

**Comment by svenstaro** [comment]
Yeah OpenSSL isn't exactly following software engineering practices either. http://semver.org/ is excellent and should be followed. I know what our openssl package is using and I will have to use that with supertux as well but that's a bit of a pity because a patch version would totally have done this for you guys. Your use of versioning seems a bit arbitrary tbh :p

**Comment by maxteufel** [comment]
> http://semver.org/ is excellent and should be followed.

Exactly. I propose to use 0.4.0 for our next release, and then follow SemVer in the future.

**Comment by svenstaro** [comment]
Works for me then.

**Comment by tobbi** [comment]
looks okay to me, so, let's go ahead and do it this way.

**Comment by sydneyjd** [comment]
Looks ok to me also, even though it does seem like large number jumps. \o/
