### ISSUE TITLE
iOS version?

### ISSUE THREAD

**Issue by fnc12** [SuperTux/supertux#712]
**SuperTux version:**
**System information:** *(details about your kernel, operating system, or distribution)*

##### Additional debugging information

*If available, please attach a backtrace of a crash (you can get one using GDB or another debugger), or a core dump. If you're on GNU/Linux and your distro is using systemd, it's highly likely that a core dump is available using `coredumpctl(1)`.
If the issue only occurs in a custom level, please attach that too.*

##### Guidelines for reporting issues

- [ ] I have read <https://github.com/SuperTux/supertux/blob/master/CONTRIBUTING.md#bug-reports>.
- [ ] I verified this isn't an issue that's already been reported.
- [ ] This report only includes details about **one** (1) issue, feature request or topic.
- [ ] If I make a mistake while submitting this report I will use the edit feature instead of closing this issue and opening a new one.
- [ ] This issue is **not** about wrong translations (use Transifex for those), or anything unsupported (e.g. third-party add-ons).
- [ ] Once you're done, please remove the section 'Guidelines for reporting issues', the 'Additional debugging information' if it is empty, and any text in *italic font*.

**Comment by maxteufel** [comment]
Thanks for your feature request.

We have indeed thought about supporting mobile platforms, and there is also an unofficial port to Android. There are however, several limitations that we noticed: First of all, our game engine is quite complex and was not intended to support this kind of platform (in fact, most of it was probably written before the first iPhone was released, and/or shortly after that). That means it does not support any of the optimizations available for mobile platforms.

Second, it is Apple that greatly limits apps on their proprietary App Store, a non-free platform and thus not matching the spirit of SuperTux. Even if we would choose to put SuperTux on the App Store, we would face serious limitations. This includes having to pay Apple quite a lot to join the developer program and paying for test devices that we don't currently have, probably not being able to use some libraries we depend on heavily now and not SuperTux's license not working out with Apple's DRM (simply put: it would be illegal if we put SuperTux in the App Store).

Finally, I'd like to remind you of reading what you post online, which you clearly didn't do when submitting this issue.

**Comment by fnc12** [comment]
Ok. Can I create supertux version with cocos2d-x for iOS and Android? I'm a developer and I have a developer account.

**Comment by maxteufel** [comment]
Well, especially for the artwork that still depends on the license. However, I think it would be best if we talked about this. You can join our development chat root at <https://riot.im/app/#/room/#supertux:matrix.org> or send us an email at team at our website domain (the one ending with .org).

**Comment by fnc12** [comment]
Thanks. I've joined with `fnc12` nickname. What if artwork will be created by different artist?

**Comment by maxteufel** [comment]
@fnc12 See our answers.
