### ISSUE TITLE
Torch Problem

### ISSUE THREAD

**Issue by PrinceRilian** [SuperTux/supertux#714]
I have noticed that the torch graphics in the game (but not the candles) have a flaw.  _The sphere of light coming from the torch is not centered around the fire!_ 

![torch issue](https://user-images.githubusercontent.com/28693061/27309871-14d39618-551c-11e7-95ba-9e7594167949.jpg)

(Using SuperTux version 0.5.1 on a Windows 7 Home Premium SP 1 platform)

**Comment by tobbi** [comment]
This is due to bad bounding boxes on our part. The problem is that adjusting the bounding boxes will likely result in breakage (I think?). I'll investigate.
