### ISSUE TITLE
SuperTux 0.5.1 runs on Win10 x64 only in Win98 compatibility mode.

### ISSUE THREAD

**Issue by watchmakerful** [SuperTux/supertux#716]
**SuperTux version:**
0.5.1 stable
**System information:** *(details about your kernel, operating system, or distribution)*
Windows 10 x64, Asus laptop, Pentium N3710
##### Expected behavior
Normal start.
##### Actual behavior
No output at all on x64 version, the same on x86 unless it runs in Win98 compatibility mode, in this mode ot runs fine.
##### Steps to reproduce actual behavior
Install x86 version and try to run it, then open its compatibility settings and select Windows 98/Windows Millennium. 
##### Additional debugging information
No output even with --debug option.
*If available, please attach a backtrace of a crash (you can get one using GDB or another debugger), or a core dump. If you're on GNU/Linux and your distro is using systemd, it's highly likely that a core dump is available using `coredumpctl(1)`.
If the issue only occurs in a custom level, please attach that too.*

**Comment by tobbi** [comment]
@maths22 I know you are probably busy, but, do you have any idea what could be causing this?

**Comment by watchmakerful** [comment]
No ideas at all, I tried installing it on my friend's laptop and got this behavior.

**Comment by watchmakerful** [comment]
Confirmed also on my home desktop on Win10 x64 with all updates.

**Comment by tobbi** [comment]
Is the graphics driver up-to-date by the way? Not that this should have anything to do with it.

**Comment by watchmakerful** [comment]
All system updates are installed on Win10 automatically, including graphics drivers.

**Comment by watchmakerful** [comment]
Today I tried to install it (32-bit version) on a WinXP virtual machine. It doesn't start in any compatibility mode, displaying "supertux2.exe is not a Win32 application". WTF?

**Comment by tobbi** [comment]
Windows XP is not supported anymore.

**Comment by redblade7** [comment]
Same here with Win10 x64 and Supertux 64-bit, but even when using 32-bit and enabling 98 compatibility the program does not run.

This is a fresh install after many years so I can't provide any more information.

**Comment by tobbi** [comment]
@watchmakerful @redblade7 Can you please try the latest alpha release from https://github.com/SuperTux/supertux/releases/tag/v0.6.0-alpha.3 and see if this works better?

**Comment by adem4ik** [comment]
Both nightly SuperTux-v0.6.0-1019-gc78d73405-win32 & stable release of SuperTux-v0.6.0 run on Windows 10 x64 1909 w/o any troubles. No compatibility modes are needed. I think this issue isn't relevant anymore.

**Comment by tobbi** [comment]
Thanks for the input. Considering this issue is a year old and it might have been fixed, I'll close it. Should it appear again, it can get reopened.
