### ISSUE TITLE
Show level properties dialog when first creating level

### ISSUE THREAD

**Issue by tobbi** [SuperTux/supertux#719]
If I imagine the workflow of an add-on creator correctly, they first want to set a name for their level. Going into the level properties is one step too much IMO.

Am I correct?

**Comment by Rusty-Box** [comment]
I think it depends on whether or not people know, how they want to name it or what their level is about, so they can choose a fitting name.

**Comment by ShadevKits** [comment]
Unless I have a strong idea of what level I'll create, I normally name my levels after creating them.

**Comment by Rusty-Box** [comment]
@ShadevKits I guess many people do that. But I could be wrong.

**Comment by brmbrmcar** [comment]
There should be an option to skip it until later.

**Comment by tobbi** [comment]
If people don't think it's useful, then I just won't implement it.

**Comment by tobbi** [comment]
Closing since it doesn't seem to be what people want.
