### ISSUE TITLE
Divide official add-ons and user made levels in the main menu

### ISSUE THREAD

**Issue by Rusty-Box** [SuperTux/supertux#720]
While it is not really important, I just wanted to mention it:
I was thinking that we could maybe separate official add-ons and community level pack/worlds.
Currently both are located in the same place in the game (see **Contrib Levels** in the main menu)

My idea:
When selecting **Start Game** in the main menu, you can choose between **Story Mode**, **Add-ons** and **Community Levels**.
In **Add-ons** there are all official add-ons, like season specials, bonus islands etc. and in **Community Levels** there are all level packs/worlds that other people made, like Mattie's World, Yeti's Revenge etc.

And maybe we should rename the **Add-ons** button under the **Start Game** button to something like Community Levels, since all levels/worlds you can download there are made by other users.

**Comment by ShadevKits** [comment]
And maybe even divide maps made by the user.

**Comment by Rusty-Box** [comment]
@ShadevKits you mean divide user maps and user levels?

**Comment by ShadevKits** [comment]
What I mean is dividing levels between ones made by the client and downloaded/imported maps into the game.

**Comment by weluvgoatz** [comment]
I have decided to work on this, so if you want to assign it to me, that would be nice.

**Comment by tobbi** [comment]
@weluvgoatz Are you still willing to work on this?

**Comment by mrkubax10** [comment]
Added in #1790
