### ISSUE TITLE
Update translation templates automatically

### ISSUE THREAD

**Issue by tobbi** [SuperTux/supertux#721]
Only updating the .po templates occasionally might not be enough and our translators might get irate because they don't get changes quickly enough.

Finding a way to update translation files automatically would be good.

**Comment by maxteufel** [comment]
The easiest way is to generate them with builds (upon `make`) and then have contributors commit those with their string-changing changes.

However, this, as any other solution, would first require improving the script (proper cross-platform support, coding style, documentation) that generates the templates.

**Comment by tobbi** [comment]
I think #368 is a duplicate of this one (sorry, I couldn't remember having filed this in the meantime)

**Comment by tobbi** [comment]
I'm gonna close this issue. We currently have a shell script that can run on demand in a git workflow. This is probably as best as it gets. Doing this automatically would update the project version and timestamp entries all the time and lead to a lot of unneeded commits.
