### ISSUE TITLE
Game Crashes when hovering cursor over bottom bar in level editor.

### ISSUE THREAD

**Issue by Alzter** [SuperTux/supertux#726]
**SuperTux version: v0.5.1**
**System information:** *Windows 10*

When I drag the cursor over the bottom bar on the level editor with the "Mario's supposed to deal with this..." level in Bonus Island III, the game closes.

**Comment by tobbi** [comment]
Bonus Island 2, not 3, right?

**Comment by tobbi** [comment]
I just checked and I can't really reproduce the issue. Are you comfortable with a debugger?

**Comment by tobbi** [comment]
I was able to reproduce on the Windows build for 0.5.1.

**Comment by ShadevKits** [comment]
![image](https://user-images.githubusercontent.com/17533466/28896952-789734fe-7793-11e7-9601-a3e3cc01d276.png)

I was able to reproduce this as well. And maybe this part of the level code has something to do with it.

**Comment by tobbi** [comment]
Are you able to get me a backtrace? I have tried it using the wine debugger but got nothing useful.

**Comment by Alzter** [comment]
My system info is:
![image](https://user-images.githubusercontent.com/22513909/28904270-f7e055f6-784c-11e7-8b1e-f342ddefc145.png)

**Comment by ShadevKits** [comment]
I don't have a debugger, nor do I know how to debug; however, this is what comes up in the console:
`[TINYGETTEXT] levels/monde/en.po:15: error: expected 'msgid': ﻿#: levels/monde/info
[WARNING] C:\projects\supertux-o8t59\src\supertux\level_parser.cpp:125 [levels/bonus2/level1.stl] The level author "Kevin" did not specify a license for this level "Mario's Supposed to Deal With This...". You might not be allowed to share it.
[FATAL] C:\projects\supertux-o8t59\src\supertux\main.cpp:510 Unexpected exception: bad allocation`

**Comment by ShadevKits** [comment]
In the editor for 0.5, there are only two modes for the camera; manual and normal. It's trying to load the mode "autoscroll" but there is no specified mode in the editor for that.
Support for the autoscroll mode would probably help, or the level could just be modified to have an init script to scroll.

**Comment by tobbi** [comment]
We deliberately deprecated autoscroll mode because in our opinion it shouldn't be used anymore.

**Comment by Alzter** [comment]
Why remove it though? If you don't like it, maybe make a message when you select it saying that you shouldn't really use it.

**Comment by busybody42** [comment]
And the auto scroll test level was REALLY cool and original!

**Comment by Rusty-Box** [comment]
@Alzter Is this a still occuring issue?

**Comment by Alzter** [comment]
Seems to be fixed now by the look of things.
