### ISSUE TITLE
.music files linked to an mp3 file crashes game upon playing

### ISSUE THREAD

**Issue by vns-123** [SuperTux/supertux#731]
**SuperTux version:** supertux2 v0.5.1
**System information:** *Windows 10 x64, Intel Core i7-4765T Processor*

##### Expected behavior
Load a .music file in supertux2\music (with a mp3 associated with the music file) in the editor

##### Actual behavior
Editor immediately crashes upon clicking the .music file

##### Steps to reproduce actual behavior
1. Navigate to your supertux2 folder.
2. Create a folder named "music"
3. Place an mp3 in the folder, and make a music file for supertux to loop the song
4. Open the supertux editor and go to where you select the music for the level
5. Select that music file

(**EDIT:** As @qwertychouskie said, converting the mp3 to an ogg file fixed the bug.)

**Comment by qwertychouskie** [comment]
You probably need to convert it to an .ogg.

**Comment by tobbi** [comment]
Can you upload the music file and the mp3 here so that I have a test case?

**Comment by vns-123** [comment]
[music+mp3.zip](https://github.com/SuperTux/supertux/files/1237294/music.mp3.zip)

These are the files.

**Comment by maxteufel** [comment]
Hmm for me it does only crash when actually trying to launch the level, not when selecting the music file (which makes more sense because that's when it actually gets loaded, not in the editor).

(by the way, @vns-123, are you VNS on the forums? If so, have you gotten my forum mail?)

**Comment by vns-123** [comment]
Yes to both questions.

**Comment by maxteufel** [comment]
@vns-123 To clarify your change of the title, when does this actually crash for you? The way you described it in your original post, or the way I described it? Because the former would be certainly an issue, the latter is something we might actually want to prevent too but it's not too urgent.

**Comment by vns-123** [comment]
I changed the title because the original title was not the case of the crash.
