### ISSUE TITLE
Can't Install CPack-generated DEB on Ubuntu 16.04

### ISSUE THREAD

**Issue by RQWorldblender** [SuperTux/supertux#737]
SuperTux version: 0.5.0-71d4bc8eecc63ba9c728652e7309ec651e7a0c93
**System information:** *(details about your kernel, operating system, or distribution)*
Ubuntu 16.04, Linux 4.10.0-36-generic

##### Expected behavior
Package installs normally without errors
##### Actual behavior
Package installation fails due to lack of 'libopenal0a', which doesn't exist for this distro.
##### Steps to reproduce actual behavior
Enable .deb generation in CMakeCache.txt (if this file already exists) by toggling the line containing 'CPACK_BINARY_DEB:BOOL' from 'OFF' to 'ON'. Run `make package`, then use `dpkg -i` on the generated .deb package. 
##### Additional debugging information
Check the main CMakeLists.txt:839. This line has the CPACK_DEBIAN_PACKAGE_DEPENDS line, and what 'libopenal0a' should be is 'libopenal1'. Though I do mind about having this work for other distros, so I'm not sure if my solution is good enough.

**Comment by tobbi** [comment]
@maxteufel Is this a simple case of checking for Ubuntu 16.04 in CMakeLists.txt and then returning a different filename?

**Comment by maxteufel** [comment]
I do not think our setup is supposed to support CPack-generated distro packages. We have it for macOS stuff, Windows stuff, and source code. For Linux binaries there will be AppImages soon.

Any solution that supports multiple Linux distro package formats seems unfitting - it will most likely result in something different than what the distro guidelines say. For distro packaging, the package maintainers are the experts.

If you, for any other reason, you'd want to use this, then what you probably want to use is the AppImages that are provided in the future or a simple source build.

If you disagree, please comment again; if there are no comments in the next week or so I'll close it.

**Comment by RQWorldblender** [comment]
Ooh, AppImages are better than having to manually use `make install` to do the installation; saves me of having to manually clean up afterwards when I need to remove it. When are the AppImages going to come out?

**Comment by maxteufel** [comment]
See #648 and #709 for what we already have (essentially script and possible automation for generating the AppImages in the CI). See #711 for what's necessary to have that nicely uploaded for nightlies.

For all Linux Travis CI builds (check <https://travis-ci.org/SuperTux/supertux/builds>), AppImages are already uploaded to some temporary (2 week) file host. You select the build, select any Linux-based job, and scroll down to the line where it says `$ ../.travis/package.sh`. You make it show that section of the log, and scroll down to where you will find a download link (e.g. last line of <https://travis-ci.org/SuperTux/supertux/jobs/281658110#L2328-L2529>).

**Comment by maths22** [comment]
@RQWorldblender You can now download appimages here: https://download.supertux.org/
