### ISSUE TITLE
Better Lightning

### ISSUE THREAD

**Issue by Rusty-Box** [SuperTux/supertux#744]
When a lightning strikes in a level it should make the game flash in a bright light. And maybe we could use a more realistic and threatening sound, but that is just my personal opinion.

**Comment by tobbi** [comment]
Do you know the Lighthouse track in STK? Are you imagining it like that?

**Comment by busybody42** [comment]
Well, we should give a better warning when it strikes multiple times, which made me struggle with the level "shocking" and we should add a visible warning if you are playing with the volume off!
Also, do not make it flash TOO bright, because we don't want seizures, do we?

**Comment by Rusty-Box** [comment]
This was adressed by #2628 - Closing this.
