### ISSUE TITLE
Symbian 9.x port (for downloads archive)

### ISSUE THREAD

**Issue by Symbian9** [SuperTux/supertux#745]
**SuperTux version:** 0.10(5)
**System information:** *Symbian 9.x (S60v3, S60v5)*

##### Expected behavior
Please, add this port, that was made by *Lars 'Anotherguest' Persson* (that is member of Retroguru) on "Downloads" page:
* http://anotherguest.blogspot.com/2011/11/supertux-0105.html

> **Installation Instructions:**
> 1. Install PIPS (at least 1.3.0)
> 2. Install SISx file
> 3. Enjoy ! ;)
> 
> **Download:**
> * **PIPS**: https://sites.google.com/site/anotherguestpage/pips1.7.5.rar?attredirects=0&d=1
> * **SISx with data files**: https://sites.google.com/site/anotherguestpage/supertux_with_data_s60v3.sisx?attredirects=0&d=1
> * **SISx only** (if you already have data files (`e:\resource\apps\supertux\`): https://sites.google.com/site/anotherguestpage/supertux_s60v3.sisx?attredirects=0&d=1

Also, here is his *SuperTux source with Symbian updates*:
* http://www.embeddev.se/agroot/supertux_symbian_src.zip

##### REFERENCE
* http://anotherguest.blogspot.com
  * http://anotherguest.se
  * http://www.embeddev.se/agroot/
* http://www.retroguru.com/staff/

**Comment by tobbi** [comment]
Who do I best page about this? @maxteufel maybe?
