### ISSUE TITLE
Release SuperTux 0.3.6 before Milestone 2 (0.4.0)

### ISSUE THREAD

**Issue by Savsish** [SuperTux/supertux#75]
The site says that The SuperTux Development Team have put our heads together, and they are going to try to officially release Milestone 2 sometime in December. However that feels a way too rushed and will be full of bugs and/or missing features. Hey developers, please release SuperTux 0.3.6 first, so we will have more time to fix bugs, add new features etc.

**Comment by maxteufel** [comment]
As per #71, the next release will be 0.4.0 in order to change our versioning scheme to [SemVer](http://semver.org/), that means 0.4.0 would be the new 0.3.6. Anyway, the 0.3.x releases are pretty much a preview release of Milestone 2.

**Comment by Savsish** [comment]
Hey maxteufel Please release SuperTux 0.3.6 before Milestone 2 (0.4.0)

**Comment by Savsish** [comment]
If there was a version numbered 0.0.6, then why there will be no 0.3.6? and why not then held back Milestone 2 to 0.5.0 for example?
