### ISSUE TITLE
Documentation: Explain how to start SuperTux with Gatekeeper enabled on macOS

### ISSUE THREAD

**Issue by maxteufel** [SuperTux/supertux#755]
Add a small guide to the README or a similar place (maybe even the dmg background image, cc: @maths22) on how to run SuperTux when [Gatekeeper](https://en.wikipedia.org/wiki/Gatekeeper_(macOS)) is enabled on macOS. Since SuperTux is not code-signed, said security feature will block execution by default.

This has been a popular problem among people joining the IRC channel.

The workaround is to open SuperTux using the context menu (right click/control click), which bypasses Gatekeeper's restriction. A more invasive method is to disable Gatekeeper entirely, but we might not want to recommend that to users.

**Comment by maths22** [comment]
I'll get on this soon.  Sometime in the next year I may get a paid
developer apple account, and at that point we can start properly signing
our app, but until then that would be a good idea.
