### ISSUE TITLE
Update translations for SuperTux 0.4.0

### ISSUE THREAD

**Issue by Savsish** [SuperTux/supertux#76]
Please update all the translations and change the egg-0.png to egg.png in the string "Eggs The egg makes Tux grow larger. Tux can then smash wooden blocks with his head." for SuperTux 0.3.6, before Milestone 2 being officially released.

**Comment by Savsish** [comment]
And please make sure that the next release will be 0.3.6, so that there will be more time to fix bugs, add new features, update translations etc.

**Comment by maxteufel** [comment]
@Savsish did you actually read what I wrote in #75?

**Comment by Savsish** [comment]
Yes, but we just wanted to beg them to release another preview version (0.3.6) to help someone in development, instead of officially releasing Milestone 2 (0.4.0), so that version 0.4.0 will be delayed for uncertain date.

**Comment by maxteufel** [comment]
@Savsish 0.4.0 **will be** 0.3.6, it's just a different versioning. Instead of 0.3.{0...Infinity}({a...z}) we'll do 0.{4...Infinity}(.{0...Infinity}) and so on. Anyway, if there's more time needed to finish 0.4.0, it can always be delayed (the announcement on the web site is only a plan for the future). As always, feel free to help (search for bugs, fix existing bugs, translate, ...).

**Comment by Savsish** [comment]
No, the versioning should be 0.3.6 then 0.4.0 and so on. I think that's seems fine to me.

**Comment by giby** [comment]
Ok, I update… 

By the way, need attention: 
Albanian (sq) 25% 530 strings to translate
Chinese (China) (zh_CN) 25% 533 strings to translate
Slovenian (sl) 24% 539 strings to translate
Dutch (nl) 23% 548 strings to translate
Romanian (ro) 22% 549 strings to translate
Esperanto (eo) 19% 572 strings to translate
Lithuanian (lt) 19% 576 strings to translate
Estonian (et) 18% 577 strings to translate
Bulgarian (bg) 13% 616 strings to translate
Croatian (hr) 13% 613 strings to translate
Vietnamese (vi) 12% 626 strings to translate
Ukrainian (uk) 7% 662 strings to translate
Arabic (ar) 5% 676 strings to translate
Japanese (ja) 1% 701 strings to translate
Uzbek (uz) 1% 704 strings to translate
Azerbaijani (az) 0% 712 strings to translate
Hebrew (he) 0% 712 strings to translate
Hindi (India) (hi_IN) 0% 712 strings to translate
Khmer (km) 0% 712 strings to translate
Malayalam (ml) 0%

**Comment by maxteufel** [comment]
> No, the versioning should be 0.3.6 then 0.4.0 and so on. I think that's seems fine to me.

Well, in ticket number #71 (please **read it**) we decided (well, no one was against) to switch to the [SemVer Versioning Scheme](http://semver.org/) (please **read this as well if you're interested**). SemVer defines that minor updates increase the Y in X.Y.Z, bugfixes increase the Z in X.Y.Z. That way, the next release will be 0.4.0.

> Uzbek (uz) 1% 704 strings to translate
> Azerbaijani (az) 0% 712 strings to translate
> Khmer (km) 0% 712 strings to translate
> Malayalam (ml) 0% 

Do we really need such exotic languages?

**Comment by giby** [comment]
Well, some people started it... so… they are in ;)

**Comment by maxteufel** [comment]
> Well, some people started it... so… they are in ;)

Well, there should be some restriction to prevent "translation spam" with translations with just a few words translated (and then the players potentially complaining "yes why does it use English when my language is set to xyz?!?").

**Comment by giby** [comment]
anyway, empty languages are not pushed, are they?

**Comment by Savsish** [comment]
If there was a version numbered 0.0.6, then why there will be no 0.3.6? and why not then held back Milestone 2 to 0.5.0 for example?

**Comment by Karkus476** [comment]
Not really an issue. Translation will always be needed.

**Comment by Savsish** [comment]
Milestone 2 is now released but the some translations for help messages are now removed and they call it an stable release. Why the players would bother reading english text when their language is set to xyz.
