### ISSUE TITLE
Spotlight: expose to scripting API

### ISSUE THREAD

**Issue by maxteufel** [SuperTux/supertux#768]
Expose spotlights to the scripting API. That means:

- adding a name property
- starting, stopping the rotation using the scripting API
- enable or disable light emission from scripting API
- change speed and direction using scripting API
- change color using scripting API

**Comment by tobbi** [comment]
I'm bumping this off the 0.6.0 list, because it's not quite ready yet.

**Comment by Semphriss** [comment]
This was seemingly forgotten about, but fortunately I've already done it with #1689
