### ISSUE TITLE
I can run supertux as root, not as user

### ISSUE THREAD

**Issue by supertux12** [SuperTux/supertux#77]
Hello,

I can run supertux as root, not as user:
$ /usr/games/supertux
Datadir: /usr/share/games/supertux
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  154 (GLX)
  Minor opcode of failed request:  3 (X_GLXCreateContext)
  Value in failed request:  0x0
  Serial number of failed request:  26
  Current serial number in output stream:  27

Running Debian Stretch amd64 with nvidia graphic driver

Hope this helps.

Thanks!

**Comment by supertux12** [comment]
Seems a problem not related to supertux. Another OpenGL  program gives same error.

**Comment by Flakebi** [comment]
I don't know how debian handles this, but on other OSs you have to add yourself to the `video` group, otherwise you don't have access to your graphic driver (and the allocation of an OpenGL context fails).

**Comment by supertux12** [comment]
After adding myself to group 'video' there is no difference :(
Thanks anyway.

**Comment by supertux12** [comment]
After last update of Debian this issue is solved.
All GLX programs can be run again by user. 
I don't know which update is responsible.

Thanks
