### ISSUE TITLE
Invincible mode (star) deactivated if going through door

### ISSUE THREAD

**Issue by solarjoe** [SuperTux/supertux#770]
When walking through a door after just catching an invincible (star) the mode is immediately stopped.

SuperTux v0.5.0

Bug or feature?

**Comment by tobbi** [comment]
@maxteufel @SuperTux/level-designers What do you think? Is this something we should change?

**Comment by J-128** [comment]
I personally think it should be changed.  If you're like me, when you collect a star, you expect it to last the entire 15 seconds (or was it 20 seconds?), regardless of where in a level you go.  However, it seems that this could _potentially_ break some levels. (Although none come to mind right now.) That's just my opinion though.

**Comment by Rusty-Box** [comment]
@tobbi I would say that the star invincibility effect should go on even when the player entered a door.

**Comment by busybody42** [comment]
Actually, the same thing also happens when entering a pipe in Mattie's world. This is really easy to notice when you use the secret shortcut in the level 4.
