### ISSUE TITLE
Throwing bricks or lamps on Tux' head kills him. Bug or feature?

### ISSUE THREAD

**Issue by solarjoe** [SuperTux/supertux#771]
The title basically says everything :)

SuperTux v0.5.0

Bug or feature?

**Comment by maxteufel** [comment]
I'd say feature. Just like an icecrusher, or a moving platform that goes down on Tux' head crushes and eventually kills him.

@tobbi, @SuperTux/level-designers what do you think?

**Comment by tobbi** [comment]
https://github.com/SuperTux/supertux/blob/master/src/object/rock.cpp#L129

On there it says "Getting a rock on the head hurts. A lot". And lamps are basically rocks (they derive from the Rock class).

Thus, I'd say feature.
