### ISSUE TITLE
Climbing is broken

### ISSUE THREAD

**Issue by 165your4** [SuperTux/supertux#774]
**SuperTux version:** Latest revision

##### Expected behavior
The user can hold Up to ascend on climbable surfaces.

##### Actual behavior
When holding the Up button, the climbing animation begins but Tux instantly lets go. The user has to spam the Up button to make Tux move upwards.

**Comment by maxteufel** [comment]
Works for me as expected on `supertux2 v0.5.1-378-ge9ff5715f` using "A Fork in the Road" (Icy Island). Can you share a test level?

**Comment by 165your4** [comment]
oops, i was holding ctrl.
