### ISSUE TITLE
Windows 10 - Program just does not run

### ISSUE THREAD

**Issue by redblade7** [SuperTux/supertux#776]
After a fresh install of Supertux on Windows 10 64-bit (have used on Linux and older Windows computers in the past), I am unable to run SuperTux.

The program just does not run. There is no error, there is no message, the program just does not run.

Apparently the only thing that does happen is that the screen flashes if you set 640x480 in compatibility settings. So perhaps it is running but quitting.

I have uninstalled and reinstalled a dozen times, restarted my computer at various times due to other reasons, tried 0.5.0 and 0.5.1, 32-bit and 64-bit of each, tried Windows 98 compatibility settings with 32-bit as someone suggested, but the program just does not run, no message, no error.

**Comment by maxteufel** [comment]
Hm, I wonder what the problem is here. Can you try a development build from <https://download.supertux.org/>?

Also, @maths22, you might have an idea about this. You know more about the Windows stuff than @tobbi or I do.

**Comment by redblade7** [comment]
Same behavior with SuperTux-v0.5.1-383-ge11cdd367-win32.msi and SuperTux-v0.5.1-388-gcd6011a28-win64.msi, including switching when switching the Win32 version to Windows 98 compatibility

**Comment by maths22** [comment]
I'll investigate on my windows computer later tonight.

**Comment by maths22** [comment]
@redblade7 I was unable to reproduce on my windows computer.  If you could post the contents of `%appdata%/SuperTux/supertux2/console.err`, that would be appreciated.

**Comment by redblade7** [comment]
I had no idea there was an stderr file.

It's filled with messages such as:

[FATAL] C:\projects\supertux-o8t59\src\supertux\main.cpp:510 Unexpected exception: Couldn't initialize SDL: windib not available
[FATAL] C:\projects\supertux-o8t59\src\supertux\main.cpp:510 Unexpected exception: Couldn't initialize SDL: windib not available
[FATAL] C:\projects\supertux-o8t59\src\supertux\main.cpp:510 Unexpected exception: Couldn't initialize SDL: windib not available
[FATAL] C:\projects\supertux-o8t59\src\supertux\main.cpp:510 Unexpected exception: Couldn't initialize SDL: windib not available
[FATAL] C:\projects\supertux-o8t59\src\supertux\main.cpp:510 Unexpected exception: Couldn't initialize SDL: windib not available
[FATAL] C:\projects\supertux-o8t59\src\supertux\main.cpp:510 Unexpected exception: Couldn't initialize SDL: windib not available
[FATAL] C:\projects\supertux-o8t59\src\supertux\main.cpp:510 Unexpected exception: Couldn't initialize SDL: windib not available
[FATAL] C:\projects\supertux-o8t59\src\supertux\main.cpp:510 Unexpected exception: Couldn't initialize SDL: windib not available
[FATAL] C:\projects\supertux-o8t59\src\supertux\main.cpp:510 Unexpected exception: Couldn't initialize SDL: windib not available
[FATAL] C:\projects\supertux-o8t59\src\supertux\main.cpp:510 Unexpected exception: Couldn't initialize SDL: windib not available
[FATAL] C:\projects\supertux-9ml4d\src\supertux\main.cpp:510 Unexpected exception: Couldn't initialize SDL: windib not available
[FATAL] C:\projects\supertux-9ml4d\src\supertux\main.cpp:510 Unexpected exception: Couldn't initialize SDL: windib not available
[FATAL] C:\projects\supertux-9ml4d\src\supertux\main.cpp:510 Unexpected exception: Couldn't initialize SDL: windib not available
[FATAL] C:\projects\supertux-9ml4d\src\supertux\main.cpp:510 Unexpected exception: Couldn't initialize SDL: windib not available
[FATAL] C:\projects\supertux-9ml4d\src\supertux\main.cpp:510 Unexpected exception: Couldn't initialize SDL: windib not available
[FATAL] C:\projects\supertux-9ml4d\src\supertux\main.cpp:510 Unexpected exception: Couldn't initialize SDL: windib not available
[FATAL] C:\projects\supertux-9ml4d\src\supertux\main.cpp:510 Unexpected exception: Couldn't initialize SDL: windib not available
[FATAL] C:\projects\supertux-9ml4d\src\supertux\main.cpp:510 Unexpected exception: Couldn't initialize SDL: windib not available
[FATAL] C:\projects\supertux-9ml4d\src\supertux\main.cpp:510 Unexpected exception: Couldn't initialize SDL: windib not available
[FATAL] C:\projects\supertux-9ml4d\src\supertux\main.cpp:510 Unexpected exception: Couldn't initialize SDL: windib not available
[FATAL] C:\projects\supertux-o8t59\src\supertux\main.cpp:536 Unexpected exception: Couldn't initialize SDL: windib not available
[FATAL] C:\projects\supertux-o8t59\src\supertux\main.cpp:536 Unexpected exception: Couldn't initialize SDL: windib not available
[FATAL] C:\projects\supertux-o8t59\src\supertux\main.cpp:536 Unexpected exception: Couldn't initialize SDL: windib not available
[FATAL] C:\projects\supertux-o8t59\src\supertux\main.cpp:510 Unexpected exception: Couldn't initialize SDL: windib not available
[FATAL] C:\projects\supertux-9ml4d\src\supertux\main.cpp:510 Unexpected exception: Couldn't initialize SDL: windib not available
[FATAL] C:\projects\supertux-o8t59\src\supertux\main.cpp:536 Unexpected exception: Couldn't initialize SDL: windib not available
[FATAL] C:\projects\supertux-o8t59\src\supertux\main.cpp:536 Unexpected exception: Couldn't initialize SDL: windib not available
[FATAL] C:\projects\supertux-9ml4d\src\supertux\main.cpp:536 Unexpected exception: Couldn't initialize SDL: windib not available
[FATAL] C:\projects\supertux-9ml4d\src\supertux\main.cpp:536 Unexpected exception: Couldn't initialize SDL: windib not available
[FATAL] C:\projects\supertux-9ml4d\src\supertux\main.cpp:536 Unexpected exception: Couldn't initialize SDL: windib not available

**Comment by redblade7** [comment]
I don't know what windib is or why this was there, but in Environment Variables (User settings):

SDL_VIDEODRIVER was set to "windib"

If I removed the SDL_VIDEODRIVER line the program works. (Is this variable put there/required for another installed program?)

**Comment by tobbi** [comment]
The question is: Do we put that variable there ourselves at all?

**Comment by maths22** [comment]
No, the installer does not touch user environment variables, so that came from somewhere else.  Some other program may have been using that env var, not entirely sure.

**Comment by redblade7** [comment]
I will close the ticket.
