### ISSUE TITLE
Yeti spawns facing left, when it should be facing right

### ISSUE THREAD

**Issue by 165your4** [SuperTux/supertux#777]
**SuperTux version:** Latest revision

##### Expected behavior
In No More Mr. Ice Guy, The Yeti spawns on the left-most ledge, facing to the right (where Tux is). It then jumps down towards Tux.

##### Actual behavior
The Yeti spawns facing left instead, and jumps outside the level bounds immediately. Because the Yeti has been 'killed', the level finishes and Tux wins. This occurs in addons too, as their Yeti boss battles have been designed around the Yeti facing right at the start.

**Comment by maxteufel** [comment]
```
011980bffe13d4e6d58e2471159dde8b5500fb85 is the first bad commit
commit 011980bffe13d4e6d58e2471159dde8b5500fb85
Author: @tobbi
Date:   Sun Dec 10 21:15:05 2017 +0100

    Don't initialize Yeti's direction to right

:040000 040000 7604d939292e0afcca840f9cf29a1fe96832cdc4 dbff25564ba51f9b3fd685005ce1c6c1030268b4 M	src
```
