### ISSUE TITLE
Segmentation error (the memory stack is flushed to disk)

### ISSUE THREAD

**Issue by morteryler** [SuperTux/supertux#779]
**SuperTux version:**
supertux2 v0.5.1
**System information:** 
Linux arch 4.15.1-2-ARCH #1 SMP Sun Feb 4 22:27:45 UTC 2018 x86_64 GNU/Linux

##### Expected behavior
Launch and play

##### Actual behavior
Exit with segmentation error

##### Steps to reproduce actual behavior
Launching

##### Additional debugging information

Log gdb:
`(gdb) run
Starting program: /usr/bin/supertux2 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7ffff2254700 (LWP 13288)]
[New Thread 0x7fffec0ac700 (LWP 13289)]
[Thread 0x7fffec0ac700 (LWP 13289) exited]
[New Thread 0x7fffec0ac700 (LWP 13291)]
[New Thread 0x7fffec0ac700 (LWP 13292)]
[Thread 0x7fffec0ac700 (LWP 13291) exited]
[New Thread 0x7fffeaa2e700 (LWP 13293)]

Thread 1 "supertux2" received signal SIGSEGV, Segmentation fault.
0x00007fffed6ec7cb in ?? () from /usr/lib/dri/i915_dri.so`

**Comment by qwertychouskie** [comment]
Could you provide the full backtrace? (`gdb bt`)

**Comment by morteryler** [comment]
> Could you provide the full backtrace? (gdb bt)

Here, see
`#0  0x00007fffed6ec7cb in ?? () from /usr/lib/dri/i915_dri.so
#1  0x00007fffed6eb44f in ?? () from /usr/lib/dri/i915_dri.so
#2  0x00007fffed52dd8d in ?? () from /usr/lib/dri/i915_dri.so
#3  0x00007fffed52e4cb in ?? () from /usr/lib/dri/i915_dri.so
#4  0x00007fffed522c52 in ?? () from /usr/lib/dri/i915_dri.so
#5  0x00007fffed550fe9 in ?? () from /usr/lib/dri/i915_dri.so
#6  0x00007fffed50b466 in ?? () from /usr/lib/dri/i915_dri.so
#7  0x00007fffed50189a in ?? () from /usr/lib/dri/i915_dri.so
#8  0x00007fffed7097ab in ?? () from /usr/lib/dri/i915_dri.so
#9  0x00007fffed500b9d in ?? () from /usr/lib/dri/i915_dri.so
#10 0x00007fffed4e5e2b in ?? () from /usr/lib/dri/i915_dri.so
#11 0x00007fffed4e6128 in ?? () from /usr/lib/dri/i915_dri.so
#12 0x0000555555880528 in GLPainter::draw_surface(DrawingRequest const&) ()
#13 0x000055555567fcee in DrawingContext::handle_drawing_requests(std::vector<DrawingRequest*, std::allocator<DrawingRequest*> >&) ()
#14 0x000055555567ff76 in DrawingContext::do_drawing() ()
#15 0x0000555555663e19 in ScreenManager::draw(DrawingContext&) ()
#16 0x0000555555664b9f in ScreenManager::run(DrawingContext&) ()
#17 0x0000555555653436 in Main::launch_game() ()
#18 0x0000555555654eb8 in Main::run(int, char**) ()
#19 0x000055555564ee26 in main ()`

**Comment by tobbi** [comment]
This appears to be a driver issue.

**Comment by tobbi** [comment]
If you can still reproduce the issue, please open a bug report on Arch Linux's bug tracker and notify us here with a link to the bug you created. 

There seems to be nothing else we can do about this.
