### ISSUE TITLE
Get rid of "friend" overuse in editor code

### ISSUE THREAD

**Issue by tobbi** [SuperTux/supertux#786]
This is Bill. Bill does not use potentially unsafe usage of "friend" in modern C++ (such as we're using in SuperTux). Bill is modern. Be like Bill.

My brain hurts every time I see friend overuse. Let's use public getters and setters instead. That way we can decouple the editor subclasses as well.

This is up for grabs. I might do it once my brain is done hurting.

**Comment by busybody42** [comment]
Yeah...

**Comment by leper** [comment]
I fixed a few, two of which are ugly and need more work, and 3 are remaining in editor.{c,h}pp.

https://github.com/leper/supertux/tree/editor_has_no_friend_classes

**Comment by leper** [comment]
Now with no more friend classes for the editor. There are still quite a few interesting access patterns with quite a few public member variables that are accessed in a few places.
