### ISSUE TITLE
Adding a "Press Enter key" or "press Start button" to title screen

### ISSUE THREAD

**Issue by Knucklesfan** [SuperTux/supertux#788]
One thing I think that could significantly improve supertux's overall aesthetic apeal would be adding a press start button before reaching the main menu. This could mostly just help give supertux a smoother gui, and make it look much better.  One thing that could also be possible (might be a bit difficult however) is to make the supertux logo centered, and then when you press start, it moves up as the menu spreads out. It would make supertux look alot better in my opinion.

**Comment by Rusty-Box** [comment]
This idea actually sounds pretty neat. Especially the one with the logo moving up when pressing start

**Comment by brmbrmcar** [comment]
I personally don't see the benefit. It would just be an extra button to press that I'd personally find annoying.

**Comment by Knucklesfan** [comment]
> I personally don't see the benefit. It would just be an extra button to press that I'd personally find annoying.

Perhaps in the settings, an option could be added to turn it off (Maybe even include it in the menu transitions to lessen clutter of the options menu)

**Comment by busybody42** [comment]
I actually hate it, Just leave it the way it is, please! (Although we might be able to add the logo moving up part, but not the "press up" part)

**Comment by maxteufel** [comment]
I agree with @brmbrmcar. There is no benefit. It adds unnecessary complexity to the code which is a bad thing. It adds just another menu which is annoying to users, too (at least I would be *very* annoyed). I conclude therefore that there is no incentive for us to add this. I'd close this issue.

@tobbi, others, …: what do you think?

**Comment by Rusty-Box** [comment]
As I already said I personally like the idea but I must also agree with @maxteufel.
In the end I don't mind whether this gets added or not. So I'll let @maxteufel and/or @tobbi decide.

**Comment by qwertychouskie** [comment]
Personally I think this would be useless just for looks, it should only be added if it has a function (e.g. the gamepad that has it's button pressed first is used as the controlling gamepad).
