### ISSUE TITLE
Proposal: Physic Engine overhaul

### ISSUE THREAD

**Issue by christ2go** [SuperTux/supertux#799]
This is a proposal/list for/of changes involving the current physics code in order to improve our physics engine. 
Main goal is fixing the several physics bugs and increasing code readability. 

- [ ] Split up collision detection and resolution
- [ ] Move collision detection and resolution out of `sector.cpp`
- [ ] Add a body to every game object 
- [ ] Save information about collision (e.g. penetration depth, normal, tangent, etc.) in a structure (Manifold)
- [ ] Generate impulses after collisions (using the algorithm described [here](https://gamedevelopment.tutsplus.com/tutorials/how-to-create-a-custom-2d-physics-engine-the-basics-and-impulse-resolution--gamedev-6331))
- [ ] If above algorithm does not solve our jitter bugs, use Baumgarte Stabilization and other algorithms (outlined [here](http://allenchou.net/2013/12/game-physics-resolution-contact-constraints/)) or Box2D
- [ ] Add quadtree collision detection (#796)
- [ ] Add proper documentation to the wiki

**Comment by christ2go** [comment]
## Algorithm Overview: Collision detection and resolution regarding tiles 
1. The tiles will be decomposed into as large axis aligned rectangles as possible (this is necessary to protect against characters getting stuck).
This will not be computed for every tile in the sector, but only for tiles adjacent to GameObjects. Thus the tile regions for adjacent GameObjects will have to be merged.  
This will also need support for triangles (the require some specail attention for collision handling).
2. The then formed areas will be added to the Physic world as static bodies. 
3. The same algorithm is done for unisolid tiles, but they require a special collision handler (=> to disable the collision if tux is not moving down).
4. After that the physics engine will do collision detection. In a first broadphase step, all possible collisions will be generated. When the collisions are processed, it will be checked if the collision should be resolved by calling a _collision handler_ (i.e. a method like _collision_object()_ ). When a collision is disabled by **one** of the two colliding objects, it will not be processed further.
5. Collisions impulses will be generated and collisions will be resolved, this process will be iterated.
6. Move objects, reset forces and let the game loop 

### Generating the collision areas
An crucial step of above algorithm for handling solids is the generation of a set of tiles to check for collision. For every game object the rectangle containing all tiles it might collide with will be generated.
After that _overlapping rectangles_ will be merged to reduce duplication. Notice that overlapping rectangles basically induce an equivalence relation on the set of rectangles, because if A overlaps with B which overlaps with C (eventhough A and C do not overlap) they will have to be merged into a single component. Thus the sets can be constructed using a union-find-data structure. 
Note: This still needs a fast algorithm for rectangle overlapping.
## Extracting the bounding boxes from the collision areas 
The last step will be to determine the rectangles for a collision area. Consider a collision area 
. X . .
. X X .
. X X .
. X X .
(an X indicates a solid tile and a . a air/ not solid tile). A good partition would be 
. 1 . .
. 2 2 .
. 2 2 .
. 2 2 .
Because all shapes have to be rectangles is to first compute the length of every horizontal sequence of solid tiles ( for the example:
. 1 . .
. 1 2 .
. 1 2 .
. 1 2 .
But this still produces more rectangles than necessary: Some horizontally adjacent rectangles can be merged. The can be merged iff there they end and begin at the same x-coordinate (this can be checked by comparing the last entry of a segment and the next element in the array). 

Eventhough this algorithm should be fast in practice (shouldn't be slower than the current tile collision detection) it might benefit from caching or even precomputation for every level.

**Comment by Alzter** [comment]
Maybe fix Tux's physics while you're at it. His controls feel way too loose.

**Comment by christ2go** [comment]
Some of this already is in the PR. Most of it will require some serious rewrites, which we don't need.
