### ISSUE TITLE
Build failure on various big-endian archs

### ISSUE THREAD

**Issue by Vincent-C** [SuperTux/supertux#80]
Supertux 0.3.5a currently fails to build on Debian mips, powerpc, s390x, and sparc; tail of build log as follows:

```
[ 89%] Building CXX object CMakeFiles/supertux2.dir/src/audio/wav_sound_file.cpp.o
/usr/bin/c++    -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2  -std=c++11 -I/usr/include/GL -I/usr/include/AL -I/«PKGBUILDDIR»/obj-mips-linux-gnu -I/«PKGBUILDDIR»/src -I/«PKGBUILDDIR»/external/squirrel/include -I/«PKGBUILDDIR»/external/tinygettext/include -I/«PKGBUILDDIR»/external/findlocale -I/«PKGBUILDDIR»/external/obstack -isystem /usr/include/SDL2    -Wall -Wextra -Wno-unused-parameter -funit-at-a-time -fno-strict-aliasing -o CMakeFiles/supertux2.dir/src/audio/wav_sound_file.cpp.o -c /«PKGBUILDDIR»/src/audio/wav_sound_file.cpp
/«PKGBUILDDIR»/src/audio/wav_sound_file.cpp: In member function 'virtual size_t WavSoundFile::read(void*, size_t)':
/«PKGBUILDDIR»/src/audio/wav_sound_file.cpp:162:4: error: 'void*' is not a pointer-to-object type
   *buffer = tmp;
    ^
make[3]: *** [CMakeFiles/supertux2.dir/src/audio/wav_sound_file.cpp.o] Error 1
```

Full build logs available at [buildd.debian.org](https://buildd.debian.org/status/package.php?p=supertux&suite=sid) (links to [mips](https://buildd.debian.org/status/fetch.php?pkg=supertux&arch=mips&ver=0.3.5a-1&stamp=1433244784), [powerpc](https://buildd.debian.org/status/fetch.php?pkg=supertux&arch=powerpc&ver=0.3.5a-1&stamp=1433242853), [s390x](https://buildd.debian.org/status/fetch.php?pkg=supertux&arch=s390x&ver=0.3.5a-1&stamp=1433242298), [~~powerpc~~ sparc](https://buildd.debian.org/status/fetch.php?pkg=supertux&arch=sparc&ver=0.3.5a-1&stamp=1433258274)). Thanks for taking a look at this!

**Comment by KroArtem** [comment]
I'm not sure it was working at all. Probably you should try to directly cast tmp to void *, something like this:
```
*buffer = static_cast<void*>(tmp);
```

**Comment by tobbi** [comment]
@Vincent-C: Can you try to change the relevant lines to what @KroArtem said and see if that works? If it does, please provide a patch.

**Comment by Vincent-C** [comment]
@KroArtem, thanks! Unfortunately, a test powerpc build still fails with that change:

```
[ 94%] Building CXX object CMakeFiles/supertux2.dir/src/audio/wav_sound_file.cpp.o
/usr/bin/c++    -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2  -std=c++11 -I/usr/include/GL -I/usr/include/AL -I/home/vcheng/supertux/supertux-0.3.5a/obj-powerpc-linux-gnu -I/home/vcheng/supertux/supertux-0.3.5a/src -I/home/vcheng/supertux/supertux-0.3.5a/external/squirrel/include -I/home/vcheng/supertux/supertux-0.3.5a/external/tinygettext/include -I/home/vcheng/supertux/supertux-0.3.5a/external/findlocale -I/home/vcheng/supertux/supertux-0.3.5a/external/obstack -isystem /usr/include/SDL2    -Wall -Wextra -Wno-unused-parameter -funit-at-a-time -fno-strict-aliasing -o CMakeFiles/supertux2.dir/src/audio/wav_sound_file.cpp.o -c /home/vcheng/supertux/supertux-0.3.5a/src/audio/wav_sound_file.cpp
/home/vcheng/supertux/supertux-0.3.5a/src/audio/wav_sound_file.cpp: In member function 'virtual size_t WavSoundFile::read(void*, size_t)':
/home/vcheng/supertux/supertux-0.3.5a/src/audio/wav_sound_file.cpp:162:4: error: 'void*' is not a pointer-to-object type
   *buffer = static_cast<void*>(tmp);
    ^
```

**Comment by fabiangreffrath** [comment]
"buffer" is a void pointer, so de-referencing it is a bad idea. You might want to try
type-punning the *LHS* pointer by e.g.
'''
  *((char *)buffer) = tmp;
'''
Hope that helps,

Fabian

**Comment by fabiangreffrath** [comment]
Correction: You'll also need to dereference the tmp pointer, i.e.:
```
  *(char *)buffer = *tmp;
```

**Comment by tobbi** [comment]
@fabiangreffrath Can you make these changes, test them, then create a pull request against this repository. Make sure to include the necessary changes inside conditional #if statements so that they are only compiled for the required architectures.

**Comment by fabiangreffrath** [comment]
I can only confirm that it compiles fine on a PowerPC with these changes, as I have just checked my patch on a Debian porter box. I have no chance, however, to actually run the game and check if sound is alright on this box.

**Comment by tobbi** [comment]
Can anyone please take a look at whether this really works (compilation and the sound itself) and report back here?

**Comment by fabiangreffrath** [comment]
@Vincent-C If you could apply this patch to the Debian package and upload it, it would compile on all big-endian archs and we would get bug reports if the sounds were messed up.

**Comment by Vincent-C** [comment]
@tobbi @fabiangreffrath  I can confirm that with the patch, supertux now builds on big-endian ([powerpc build log](https://buildd.debian.org/status/fetch.php?pkg=supertux&arch=powerpc&ver=0.3.5a-2&stamp=1440064967) as an example). No idea whether sound works or not since I don't have a powerpc (or any other big endian arch) system of my own...on the bright side, at least this change has no regression potential (code in question is inside an ```#ifdef WORDS_BIGENDIAN``` block).
