### ISSUE TITLE
Add Confirm Dialog for Level Restart when a Checkpoint is reached

### ISSUE THREAD

**Issue by Ordoviz** [SuperTux/supertux#800]
Sometimes you accidentally restart the level because you are about to die. Then you realize that you pressed ESC DOWN and ENTER too fast without giving the fact that you reached a checkpoint before a thought. After that you are irritated by being back at the very beginning of the level and you think that would not have happened if there had been some kind of a confirmation dialog that asks you “Do you really want to start over?” and you can choose between “Start Over”, “Restart at latest checkpoint” and “Cancel”.

In my opinion this scenario is not that far-fetched and the extra button to press does not bother me in exchange for more safety. In addition, the option to restart from checkpoint is helpful in case you get soft-locked – this means you got trapped but also aren’t able to die.

**Comment by busybody42** [comment]
Yes! Please! I had to struggle with an annoying and hard level twice because it did not ask me to confirm a restart! Also, the level "reaching the peak" from yeti's revenge is WAY too hard and WAY too long!

**Comment by busybody42** [comment]
But what about the power ups, or if you did not hit a checkpoint yet?

**Comment by paezao** [comment]
Why not just add a restart level confirmation dialog (having or not hitting a checkpoint yet)? This could also warn about restarting from the beginning and not the checkpoint and give time for the player to think it through.

**Comment by Rusty-Box** [comment]
Fixed via #1128
