### ISSUE TITLE
Editor: disallow removal of main sector

### ISSUE THREAD

**Issue by maxteufel** [SuperTux/supertux#801]
The level editor must not allow changing the name of, or removing entirely, the `main` sector. This will lead to confused users otherwise.

**Comment by Ordoviz** [comment]
The problem with this is that you cannot mark any other sector as `main` if you have changed your mind later on (unless you edit the stl file manually). Therefore, I suggest radio buttons next to the level name so that the user sees that a `main` sector is needed.

**Comment by christ2go** [comment]
It would be possible to check whenever a level is saved if one (and only one) main sector exists. If no main sector exists the user will be presented with notification and will not be able to save the level until one sector has been named main.
