### ISSUE TITLE
Basque is not in instalable language packs list

### ISSUE THREAD

**Issue by urtzai** [SuperTux/supertux#802]
**SuperTux version:** 0.5.1
**System information:** Ubuntu 17.10

##### Expected behavior
Select basque language in the options and install it.

##### Actual behavior
I tried to install the basque language pack and there is not in the game's list

##### Steps to reproduce actual behavior
Select options, language packages.

**Comment by tobbi** [comment]
This is actually resolved, considering we don't have language packs for separate languages anymore but starting with 0.6.0 we do have one single language pack containing updated translation files.
