### ISSUE TITLE
Make AmbientSound actually work

### ISSUE THREAD

**Issue by tobbi** [SuperTux/supertux#806]
Our AmbientSound object doesn't actually work (also check out the test level pertaining to Ambient Sound). One should actually look into how it's supposed to work and why it doesn't.

**Comment by tobbi** [comment]
Okay, the test level is broken for some reason. AmbientSound as it is works, but only when you set distance factor / the other distance setting to 0. I don't know what the settings mean, though.

**Comment by Rusty-Box** [comment]
I personally think that the AmbientSound object is made unnecessarily complicated. It should only have a volume setting and a distance setting.

Additionally I would recommend, adding a sector setting where you can choose an ambient sound that plays throughout the entire sector. (e.g. rain)

**Comment by maxteufel** [comment]
So, plan for an update as discussed with @Rusty-Box is:

- The size of the AmbientSound object determines the area where the volume is at 100%
- A distance setting specifies, where compared to the center of the AmbientSound object, the volume drops to 0%
- We interpolate outside the specified area
- Additionally, an option to specify the base volume of the sound (in case the provided sound is too loud)

**Comment by Rusty-Box** [comment]
Considering the AmbientSound object is still rather messy regarding its editor settings: we should remove the "distance bias" setting, because honestly no one seems to know what it even does, and have the "distance factor" increase the area where the sound plays at 100% volume from the main object.

**Comment by Rusty-Box** [comment]
This was adressed by #2688 - Closing this.
