### ISSUE TITLE
Light off on Forest World ContraStream

### ISSUE THREAD

**Issue by batateika** [SuperTux/supertux#809]
**SuperTux version:** 2 0.5.1

**System information:** *(details about your kernel, operating system, or distribution)*
Ubuntu 18.04 LTS
Memory 3.1 G
Processor Intel Pentium (R) D CPU 3.2 Ghzx2
Graphic NVA8
Gnome 3.28.1
64 bit

##### Expected behavior
Light on

##### Actual behavior
Light off

##### Steps to reproduce actual behavior
Conversation from Ubuntu 16.04 to 18.04

##### Additional debugging information
The operating system was put on a clean (pre-erased) disk, the game was repeated.
At this level, there is darkness that prevents you from playing.
It was not on the previous operating system.

Photo from Youtube:
![2018-05-15 17-28-47](https://user-images.githubusercontent.com/39306831/40116654-f45e75be-591c-11e8-9c74-ea5a78b871b9.png)

Photo from my computer:
![2018-05-16 15-10-52](https://user-images.githubusercontent.com/39306831/40116655-f47e7116-591c-11e8-8035-a4dae105c803.png)

##### Guidelines for reporting issues

- [ ] I have read <https://github.com/SuperTux/supertux/blob/master/CONTRIBUTING.md#bug-reports>.
- [ ] I verified this isn't an issue that's already been reported.
- [ ] This report only includes details about **one** (1) issue, feature request or topic.
- [ ] If I make a mistake while submitting this report I will use the edit feature instead of closing this issue and opening a new one.
- [ ] This issue is **not** about wrong translations (use Transifex for those), or anything unsupported (e.g. third-party add-ons).
- [ ] Once you're done, please remove the section 'Guidelines for reporting issues', the 'Additional debugging information' if it is empty, and any text in *italic font*.

**Comment by christ2go** [comment]
I believe this was an intended change (the candles were placed there because of the now missing light). Anyway this level has been deprecated in the forest overhaul.
