### ISSUE TITLE
Fix all bugs before releasing SuperTux 0.4.0

### ISSUE THREAD

**Issue by Savsish** [SuperTux/supertux#81]
Please fix all bugs if possible before releasing SuperTux 0.4.0

**Comment by maxteufel** [comment]
Indeed, all [milestone 0.4.0 bugs](https://github.com/SuperTux/supertux/milestones/0.4.0) should be fixed/resolved before the release. Unfortunately there are some bug reports that are unusable (migrated from Google Code but not providing all information). Closing this as this report is pretty much unnecessary.
