### ISSUE TITLE
Bug: Fixed Trampolines are movable

### ISSUE THREAD

**Issue by Ordoviz** [SuperTux/supertux#813]
**SuperTux version:** 0.5.1 (and latest nightly AppImage)
**System information:** Arch Linux 4.16.9-1-ARCH x86_64

##### Expected behavior
Fixed trampolines, power-ups, scripted objects and dispensers shouldn’t be movable.
##### Actual behavior
In fact they are!
##### Steps to reproduce actual behavior
Place a rock (or any other transportable object) on the ground when you are standing a half block away from the fixed trampoline. The rock will just kick it away.

I suggest giving fixed trampolines the same abilities as unstable tiles for example since the don’t need to be affected by gravitation I think. In so doing we can bypass our problems with object physics.

**Comment by busybody42** [comment]
They are SUPPOSED to be affected by gravity! It is just the physics engine doing what it was made to do!

**Comment by Rusty-Box** [comment]
The fixed trampoline in fact can be grabed and moved. However this is not due to a bug. Additionally to changing the sprite of the trampoline the option "portable" must be set to false. If this is not the case the "fixed" trampoline can indeed still be moved.
