### ISSUE TITLE
Issues with Yeti's Revenge

### ISSUE THREAD

**Issue by Danfun64** [SuperTux/supertux#83]
Yeti's Revenge: A certain section of the level "All's Well That Ends Well" isn't particularly fun for epileptics, as it mainly consists of rapidly switching colored backgrounds and a continuous ringing of the 1-up sound. To make matters worse, the level immediately afterwards crashes the game.

**Comment by Dynamicwork** [comment]
Works Mobile - http://www.worksmobile.com
--------------------------------------------

dynamicwork@dynamicwork.org 님께 보내신 메일 <[supertux] Seizure Warning in addon level. (#83)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by tobbi** [comment]
I notified the author of "Yeti's Revenge" about this issue. Not sure if he's willing to work on it, but let's see...

**Comment by tobbi** [comment]
What about creating a stop button with a message box that says "Press only if you have problems with rapidly switching colours" ?

**Comment by Danfun64** [comment]
"and infinite 1-up sounds"

**Comment by tobbi** [comment]
Problem is that these serve a function in the level. The frequency of the flickers indicate certain places...

**Comment by Karkus476** [comment]
Is this solved?

**Comment by Danfun64** [comment]
If that's the case, the whole section of the level should be replaced!

**Comment by tobbi** [comment]
Actually, we could reduce the speed of the flickering...

**Comment by tobbi** [comment]
Luckily, this isn't bound to any release since it's an add-on. So, I'm putting this in post-0.4.0 for now.

**Comment by maths22** [comment]
This issue was moved to SuperTux/addons#16
