### ISSUE TITLE
Time attack mode in Supertux

### ISSUE THREAD

**Issue by andrew3600** [SuperTux/supertux#837]
version is 0.5.1
os is Windows 10

I have an idea for a time attack mode in Supertux. Basically it's a mode where you race against the clock in any level you choose to use the feature with. If you don't manage to beat the level in the time that's shown when you first enter a level [the level target time] within 1 second you die. If you succeed, you get 100 coins. If you beat your own time, you get 100 coins too.

**Comment by busybody42** [comment]
What about checkpoints? And that just seems too unfair when playing the level for the first time. Also, Mattie's world used target time for unlocking stuff in the shop.

**Comment by andrew3600** [comment]
Yes, I know. You can choose whether you want to beat the level within 1 second or a number that's up to 20 seconds.

**Comment by andrew3600** [comment]
And checkpoints already exist in ST.

**Comment by busybody42** [comment]
I meant would the player respawn at the last checkpoint they reached if they died?

**Comment by andrew3600** [comment]
Yes, they would respawn at the last checkpoint.

**Comment by Semphriss** [comment]
Closing, as this most likely won't be implemented in the base game.
