### ISSUE TITLE
Difficulty modes

### ISSUE THREAD

**Issue by andrew3600** [SuperTux/supertux#838]
I was really skeptic about this idea, for obvious reasons, but I thought about different difficulty modes in SuperTux. Easy, normal and hard. Easy would be an easier version of the levels we have now. Less baddies, different layouts, that sort of stuff. Normal would be just the levels we have now. And hard would be the levels we have now made a bit harder. Trickier layouts, more baddies, that sort of stuff. It'd require designing the same levels 2 times, and that's why I was skeptic, but still.

**Comment by busybody42** [comment]
Mattie's world did the same thing!! But good idea!

**Comment by andrew3600** [comment]
I know/

**Comment by 165your4** [comment]
Supertux's base game is easy enough as is. Rather than adding difficulty modes, I think it'd be better to make the existing levels a little harder, add more replay value (blue coins / fishboxes a la yeti's revenge), and trim both worlds down to 15 levels or so.

**Comment by busybody42** [comment]
So basically make the levels harder, and move some to a bonus island world?

**Comment by Grumbel** [comment]
This would basically be unmaintainable and provide little to no actual benefit. You'd be much better of simply designing extra difficult or extra easy island and Contrib Levels. And if that isn't enough you can always use cheat codes.
