### ISSUE TITLE
Something has to be done about 0.1.x custom levels like Tux Strikes Back.

### ISSUE THREAD

**Issue by Danfun64** [SuperTux/supertux#84]
At it stands, the supertux editor can't load these old levels. It's amazing that 0.3.x can load them at all. I suggest that certain measures be taken to solve this problem.

1. Improve 0.1.x map compatibility in the game itself. This would consist of windowboxing 0.1.x levels to the 640x480 resolution found in 0.1.x, perhaps with a super game boy style border. It would also require that backtracking wouldn't be allowed, and that enemies with changed behaviors act as they do in 0.1.x, for example, mr.bomb will use older graphics and won't explode when hit by an ice cube. In addition, the engine would redirect the music requests for .mod/.it/whatever to the respective .ogg files.

2. Allow importing of 0.1.x files in the supertux editor. The editor would convert the levels to the best of its ability, but some manual touchups will be required. The old mr. bomb would be selectable as an enemy. The conversion would be one way.

Original Post:While it doesn't have to be updated to Milestone 2 standards, it should at least get the Bonus Island/Bonus Island 2 treatment of making sure that the music is correct, there being enough blocks that there aren't any large black areas, the timer is set correctly, and the levels work right. "The Story" causes the game to CTD on my system, and Level 7 "Boxy World" is more difficult then it needs to be because of changes in the behavior of Mr.Bomb.

**Comment by Dynamicwork** [comment]
Works Mobile - http://www.worksmobile.com
--------------------------------------------

dynamicwork@dynamicwork.org 님께 보내신 메일 <[supertux] Tux Strikes Back needs an overhaul (#84)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by giby** [comment]
Many Bonus and addons need love... But as long as flexley isn't running properly, I cannot do anything...

**Comment by Dynamicwork** [comment]
Works Mobile - http://www.worksmobile.com
--------------------------------------------

dynamicwork@dynamicwork.org 님께 보내신 메일 <Re: [supertux] Addon campaign "Tux Strikes Back" needs an overhaul (#84)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by Danfun64** [comment]
Tux Strikes Back needs to be remade from scratch. The level editor finds the TSB levels too old.

**Comment by Danfun64** [comment]
I updated the description. The problem is worse than i thought.

**Comment by maxteufel** [comment]
> Allow importing of 0.1.x files in the supertux editor. The editor would convert the levels to the best of its ability, but some manual touchups will be required. The old mr. bomb would be selectable as an enemy. The conversion would be one way.

There are scripts to convert milestone 1 to 2 levels (see `tools/levelconverter-0.1.3_0.2.0.*`).

Also, feel free to fix any addons. Addons are addons because well, they're not necessarily supported by the main developers.

**Comment by Danfun64** [comment]
Neither script seemed to work.

**Comment by sydneyjd** [comment]
We currently don't have the manpower nor the will to do all those changes. As mt said, they are addons that we don't support. we just make them available to the player.

**Comment by tobbi** [comment]
Cross-referencing the forum thread here: http://forum.freegamedev.net/viewtopic.php?f=68&t=6436

**Comment by Hume2** [comment]
1: So what you're suggesting is dual SuperTux behaviour. Almost all of the milestone 1 behaviour has been tweaked, so each object needs an alternative behaviour for milestone 1 levels. I think, it's crap.

2: It's the editor issue. An ingame editor upcomming in 0.4.1 will be able to load them, but save only in the new format.

I've already tweaked the bonus islands, but Tobbi hasn't merged those changes to the master branch so far.

**Comment by brmbrmcar** [comment]
Tux Strikes Back doesn't even work  in 0.1.3.

**Comment by tobbi** [comment]
We don't care about 0.1.3 any longer. 0.4.0 will be released this year, and will be a new stable version. TSB has been updated in the add-on repository. I think we can close this, for this reason.
