### ISSUE TITLE
TextArray object

### ISSUE THREAD

**Issue by maxteufel** [SuperTux/supertux#840]
Implement a TextArray object. That is an object that stores multiple texts (can be more than one line per text and can include formatting) that allows the user to navigate through the text (next/previous text), skip the text (useful for intro levels if the user already knows them), and maybe this pauses game time and badguys as well.

**Comment by tobbi** [comment]
The TextArray should be timed as well, aka "after x seconds, display the next text". Also, skipping should be done using any of "tab/enter/space".

**Comment by g--o** [comment]
got pull request going

**Comment by tobbi** [comment]
Done in dd9be69

Thanks again, @g--o.
