### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by NuLogicSystems** [SuperTux/supertux#842]
The web site claims the next Linux release will be an appimage, but the last release was 2 years ago.
When will the next release be?
and
Will it be an appimage?

**Comment by maxteufel** [comment]
Til Forest Island has reasonably matured there will probably not be a stable release.

Yes it will be released in the form of AppImages using exactly the same process as the nightly AppImages. Unfortunately our nightly site at <https://download.supertux.org/> is currently broken.

Please do not use this issue tracker for support requests like this. Use other communication channels as documented on our website.
