### ISSUE TITLE
"Electrifier" should take a map of changing tiles

### ISSUE THREAD

**Issue by tobbi** [SuperTux/supertux#846]
Currently, we add one game object per tile that needs to be changed by the electrifier. This is not ideal.

The way I imagine it, it should take an std::map data structure that should look like this:
```
{
  tile_id_from_1: tile_id_to_1,
  tile_id_from_2: tile_id_to_2
  ...
}
```
This is the file that needs to be changed:
https://github.com/SuperTux/supertux/blob/master/src/object/electrifier.cpp and the corresponding header file.

So, add a constructor that takes a map. The old uint32_t, uint32_t constructor should be changed so that it calls the other constructor. Besides, all the calls to the Electrifier constructor should get changed so that they use the new syntax.

This work would help me with integrating the storm cloud graphics from #405

**Comment by maxteufel** [comment]
As seen in #848 this seems to make the code more complicated for little to no gain and even increases line count.
