### ISSUE TITLE
Enemies that never fall off platforms should avoid spikes and harmful things on their path

### ISSUE THREAD

**Issue by weluvgoatz** [SuperTux/supertux#851]
@tobbi told me to make an issue on this. Enemies like bombs, smartballs, walking leaves etc. should avoid things like spikes and vines (turns around). This should be a property of the enemy so levels still work, but it by default they should turn around.

**Comment by Nobelix** [comment]
Okay so I will try to work on this as my first issue cause I just finished  learning c++ basics

**Comment by weluvgoatz** [comment]
thanks!

**Comment by tobbi** [comment]
#870 is still open. So, this issue can't be closed yet.

**Comment by weluvgoatz** [comment]
No one has done anything substantial on this, so closing it.
