### ISSUE TITLE
Merge weekend

### ISSUE THREAD

**Issue by christ2go** [SuperTux/supertux#855]
Next weekend (6th, 7th, 8th July 2018) we plan to hold an official "SuperTux Merge weekend".

The goal is to merge as many open pull requests as possible (to make the first part of coding standard changes possible). So if you have open pull requests open, please try to get them "into good shape" to spare the team some work.

If you are not a member of the team and want to join us in our quest to merge as many pull requests as possible, the individual who submits most pull request fixes (and is not a member of the team) will get a small crystal prize.

**Comment by tobbi** [comment]
For this merge weekend, I suggest the following theme song: [Time Warp - Rocky Horror Picture Show] (https://www.youtube.com/watch?v=aizCMO-mI1Q) with the main lyrics adapted so that instead of saying "Let's do the time warp again", we sing "Let's do the merge thing again"

**Comment by weluvgoatz** [comment]
Will you merge pull requests from the addon repository and the wiki repository, too?

**Comment by christ2go** [comment]
As this merge weekend was done now (not as many merges as we hoped), I'm closing this.
