### ISSUE TITLE
Update Fire Tux and Ice Tux graphics to the @Alzter version

### ISSUE THREAD

**Issue by pelya** [SuperTux/supertux#857]
Tux with Fire and Ice hats still uses old single-frame graphics for butt jump

**Comment by weluvgoatz** [comment]
And when using the air and earth hats, they float above Tux temporarily.

**Comment by tobbi** [comment]
@Alzter Are you willing to draw the necessary sprites for this?

**Comment by Alzter** [comment]
Sure. Quick question though: Why does Fire Tux have his hat assembled and not as a separate image like air or earth tux?

**Comment by HybridDog** [comment]
I personally prefer the angry Tux butt jump texture.
![a](https://raw.githubusercontent.com/SuperTux/data/d637b48210839796f078ee4cecd8fec80ca597c1/images/creatures/tux/big/buttjump-0.png)
The new texture does not fit to the collision box:
![2019-03-11-163741_1920x1080_scrot](https://user-images.githubusercontent.com/3192173/54136470-2b6f5380-441c-11e9-92ff-695d8488f86c.png)
The old texture also looks better when doing a sudden butt jump, i.e. press Down shortly before touching the enemy. With the animation, the visuals now does not show what Tux actually does quickly enough in my opinion.

**Comment by Rusty-Box** [comment]
This issue was fixed. Closing this.
