### ISSUE TITLE
GitHub organization: reduce the number of owners

### ISSUE THREAD

**Issue by maxteufel** [SuperTux/supertux#859]
In the light of <https://wiki.gentoo.org/wiki/Github/2018-06-28> I would like to reduce the number of owners on the @SuperTux GitHub organization to reduce possible attack vectors. Based on recent lack of activity and lack of 2FA this would affect the following people:

- @Grumbel 
- @Hume2 
- @LMH0013 
- @Mathnerd314 
- @uafr 

Unless there are objections here, I would make this change next weekend on Sunday, 8th July. **Edit:** the mentioned people would continue to be organization members, only their owner privileges would be removed.

I would also strongly recommend everyone in the organization to enable 2FA on their account.

**Comment by Grumbel** [comment]
I have enabled 2FA now and my last commit is only a week old. So no need to remove me.

As for the rest, I quite like keeping old contributors around (helps with bus-factor), but requiring 2FA might be a good idea.

**Comment by maxteufel** [comment]
> As for the rest, I quite like keeping old contributors around (helps with bus-factor), but requiring 2FA might be a good idea.

Making 2FA mandotory will remove those without it, that is why I am hesitant to do so as well.

> I too have set up 2FA, but you will not hurt my feelings if you choose to demote me. Should I become active again, I imagine I can beg for access again.

I have done that for you now. As for the last thing, indeed. (Also, removing owner privileges won't remove commit access, so you can always commit something.)

**Comment by Hume2** [comment]
Feel free to remove my owner status, I hate Micro$oft©®™.

**Comment by Mathnerd314** [comment]
> This particular admin was not an active GitHub user and failed to enable [2FA] on github. His passwords for other sites leaked and there was a pattern in them that made it guessable from the leaked passwords.

My passwords are randomly generated, I doubt someone could guess them. Even enabling 2FA seems like overkill, nobody is going to hack into my email just to mess around with SuperTux.

**Comment by maxteufel** [comment]
> Feel free to remove my owner status, I hate Micro$oft©®™.

@Hume2 I have done so. We might do something about that last part.

> My passwords are randomly generated, I doubt someone could guess them. Even enabling 2FA seems like overkill, nobody is going to hack into my email just to mess around with SuperTux.

@Mathnerd314 2FA also protects you from other cases where your password might be leaked. For instance, Twitter and GitHub recently both had an issue where passwords were logged in plain text. Anyway, keeping you as an owner (for now).

**Comment by uafr** [comment]
Really short notice for such drastic change. Not even a warning on the mailing list. :-(

Anyway, I enabled 2FA which prevents me from using Github if I don't have my cellphone.

**Comment by maxteufel** [comment]
To make it clear, I have not and will not remove owner access from anyone who objected. Thank you for enabling 2FA on your accounts, if you did so.

Apparently, most of the affected people do not agree with this change, hence I will close this.

**Comment by uafr** [comment]
> Nobody seems to have an idea who's behind lethargik.org

IIRC that's Ryan's server.
