### ISSUE TITLE
Rename 0.3.5a to 0.3.6

### ISSUE THREAD

**Issue by Savsish** [SuperTux/supertux#86]
If they are following SemVer then the 0.3.5a release can be just renamed to 0.3.6

**Comment by Dynamicwork** [comment]
Works Mobile - http://www.worksmobile.com
--------------------------------------------

dynamicwork@dynamicwork.org 님께 보내신 메일 <[supertux] Rename 0.3.5a to 0.3.6 (#86)> 이 다음과 같은 이유로 전송 실패했습니다.

--------------------------------------------

받는 사람이 회원님의 메일을 수신차단 하였습니다. 


--------------------------------------------

**Comment by tobbi** [comment]
See #85. Not going to change the version number of an already released version.
