### ISSUE TITLE
Object name property parsing should be done in GameObject class

### ISSUE THREAD

**Issue by tobbi** [SuperTux/supertux#862]
Currently, we're parsing the name of a game object in the relevant sub-classes. Code-style-wise, this is inconsistent. We should add a ```GameObject``` constructor that takes a ```const ReaderMapping&``` and parse the name there. Then remove the various ```lisp.get("name", name);``` calls throughout the code.

Add constructor to this class:
https://github.com/SuperTux/supertux/blob/master/src/supertux/game_object.hpp

Remove the reader.get method from sub-classes (as shown in this example):
https://github.com/SuperTux/supertux/blob/master/src/badguy/willowisp.cpp#L55

...and initialize the GameObject constructor when calling the relevant constructors. For the above example, you can call the ```GameObject``` constructor from the ```Badguy``` class.

Please comment on this issue if something is unclear.

**Comment by paezao** [comment]
Only for the game property you mean, @tobbi ?

**Comment by tobbi** [comment]
I'm not sure I get what you mean? As opposed to what?

**Comment by paezao** [comment]
Ops for the name property, that was a mistype.

**Comment by tobbi** [comment]
Yup, the name property parsing should be done in the GameObject class. If we parse other properties that belong in their respective parent classes, feel free to move them as well.
