### ISSUE TITLE
Resizing tilemaps: x and y offset options?

### ISSUE THREAD

**Issue by 165your4** [SuperTux/supertux#871]
I miss this feature from the external editor. It'd be really useful.

**Comment by maxteufel** [comment]
Hm... if I understood it correctly then maybe #508 is (at least in part) doing what you want?

**Comment by 165your4** [comment]
Yes.

**Comment by maxteufel** [comment]
I have ported that change to latest master but have not tested it yet, see https://github.com/SuperTux/supertux/compare/61580c7f5f52%5E...10865ec606de in the [`feature/tilemap-resize-offset`](https://github.com/SuperTux/supertux/tree/feature/tilemap-resize-offset) branch.

You can either attempt to build it yourself or use the CI builds that should be available in about an hour. If I am not mistaken the builds should show up on https://download.supertux.org/, but make sure to download the build for the aforementioned branch.

Please test the change and tell us if something needs to be done.

**Comment by maxteufel** [comment]
@165your4 Did you test the build above? Please give an update on whether or not it works that way.

**Comment by 165your4** [comment]
@maxteufel I've downloaded the build but haven't had time to test it, I'll have a look tomorrow.

**Comment by 165your4** [comment]
@maxteufel I've tested it and can confirm that the feature works as expected.

**Comment by maxteufel** [comment]
The feature has been merged now (thanks to @Hume2 for implementing it back then!). At the time of the pull request, I had in particular concerns about the user interface for this. If there are any ideas on how to improve this, please suggest them in a new issue.
