### ISSUE TITLE
Windows 10 - does not open at all

### ISSUE THREAD

**Issue by sidboy** [SuperTux/supertux#872]
**SuperTux version:** 0.5.1 32bits or 64bits
**System information:** Windows 10 64bits Intel® Core™ i5-3337U 4GB RAM
##### Expected behavior
The game should run just fine. It runs on my PC with Intel core i5 3210M and 8GB.
##### Actual behavior
Tha game simply does not open at all, and the file console.err is not generated.
##### Steps to reproduce actual behavior
Install 32bits or 64bits and try to open it.
##### Additional debugging information
I don't know why but the game simply does not open at all, there is no error log ou error message. Simply does not open. I don't know what to do. Both computers uses the same anti-virus Panda Dome.
Also, I forgot to mention that both computers uses the same Intel HD Graphics 4000 and the save driver.

**Comment by stavrossk** [comment]
I have the same problem with the PortableApps version of the game. I'm on Windows 7 64-bit.

**Comment by busybody42** [comment]
Strange. I have a 64 bit Windows 10, yet Supertux works correctly on my computer! Did you get the wrong version?

**Comment by sidboy** [comment]
No, I din't. I downloaded from the official site.

**Comment by tobbi** [comment]
Does changing the compatibility mode to Windows 98 have any effect?

**Comment by tobbi** [comment]
@stavrossk @sidboy Please see my comment above!

**Comment by sidboy** [comment]
I can't test that because I don't have the notebook anymore.

**Comment by tobbi** [comment]
Hello everyone,

can you please try the new alpha / test build from and tell us whether that build works for you? https://github.com/SuperTux/supertux/releases/tag/v0.6.0-alpha.3

**Comment by lotharsm** [comment]
Update: beta 0.6 is affected too.

Error log:
`[FATAL] C:\projects\supertux-o8t59\src\supertux\main.cpp:601 Unexpected exception: Couldn't initialize physfs: 0`

**Comment by lucamosca1** [comment]
Hi there! OpenAL32.dll isa available in bin folder for both 32 and 64 bit version. Unluckily the game still doesn't start. :(

**Comment by RayKoopa** [comment]
I tried the 0.6.0 Alpha 3 aswell, does not run on my Windows 10 1809 x64 PC, only dumps the `Couldn't initialize physfs` message four times and then that's it.

In case it matters:
Intel i7-6700, AMD R9 390

**Comment by tobbi** [comment]
@lotharsm I have updated PhysFS to the latest version on the stable-3.0 branch. Please test it from

You want the latest build from https://download.supertux.org/ (it might take one or two hours for builds to be available, so please be patient)

**Comment by lotharsm** [comment]
@tobbi Thanks! Build SuperTux-v0.6.0-beta.1-37-gec86822f9-win64.msi
 fixed this issue for me.

**Comment by tobbi** [comment]
I'm going to close this issue for now. Should any of the issues persist with the latest beta or the soon-to-be-released 0.6.1, feel free to drop me a message.
