### ISSUE TITLE
CMake: explicitly specify list of source files

### ISSUE THREAD

**Issue by maxteufel** [SuperTux/supertux#881]
At the moment, we are using GLOB to collect a list of source files from our tree ([CMakeLists.txt](https://github.com/SuperTux/supertux/blob/master/CMakeLists.txt#L402-L406)). The CMake documentation says this is [bad practice](https://cmake.org/cmake/help/v3.12/command/file.html#glob):

> **Note:** We do not recommend using GLOB to collect a list of source files from your source tree. If no CMakeLists.txt file changes when a source is added or removed then the generated build system cannot know when to ask CMake to regenerate. [...]

We should manually specify lists of source files. This should probably be done using `CMakeLists.txt` files in every subdirectory containing code.

**Comment by qwertychouskie** [comment]
The other option is something like this: https://github.com/supertuxkart/stk-code/blob/master/sources.cmake

It usually just gets a space added to or removed from the comment whenever a file is added/removed.

**Comment by Grumbel** [comment]
Hell no. Specifying all source files manually is not only a shitton of extra work, it also ensures that your source tree will fill up with garbage as people will remove files from the `CMakeLists.txt`, but forget to remove them from the repository. It's a classic case of violating DNRY. Furthermore it makes people sloppy in organising the repository, e.g. keeping non-portable code mixed together with the portable ones as you can fix the mess in `CMakeLists.txt`, when that stuff really should go into their own directory and captured by a glob.

I have been through manually specifying all the files in the days of autotools, which didn't support glob, never again. Globs work a million times better.

**Comment by g--o** [comment]
@Grumbel just my two cents but if someone forget their files on the repo with glob it's much more harming - you keep compiling unnecessary stuff. Wouldn't it be better to use generated lists instead of going completely manual / completely glob?
This way you can see the diff (or lack of) in git, and so can cmake.

**Comment by Grumbel** [comment]
You don't forget files in the repo, since the repo is the only place where you have to remove them. Forgetting only happens when you have to update two places at once.

**Comment by g--o** [comment]
@Grumbel 
That's not always true, you often get rid of the usage first. e.g: libraries
