### ISSUE TITLE
something wrong when installing the game

### ISSUE THREAD

**Issue by KR4ZY2002** [SuperTux/supertux#884]
super tux version: 0.5.1 on windows 10
when i try to install this appears:

Error writing to file: C:/Program Files/SuperTux/bin/ucrtbades.dll.
Verify that you have access to that directory.

Pls help me.

**Comment by christ2go** [comment]
Can you give some more details? Are you an administrator on the PC? And what happens if you try to create any file in that directory? This seems to be an issue with you not having write permissions. Please provide us with some more information, else we won't be of much help.

**Comment by christ2go** [comment]
As @KR4ZY2002 hasn't responded, and this does not look like our fault, I'll close this issue for now. If more reports of this come up, or if more information is available, please reopen.
