### ISSUE TITLE
Spotlights and Walking Candles Don't Work

### ISSUE THREAD

**Issue by weluvgoatz** [SuperTux/supertux#890]
**SuperTux version:** 0.5.1.20, Android Port, but probably affects other versions as well

##### Expected behavior
Spotlights activate magic blocks when the spotlight matches the block's color and shines on it.

##### Actual behavior
The magic blocks stay unactivated, rendering some levels unbeatable.

##### Steps to reproduce actual behavior
Play "Eine Bunte Welt" (A Colorful World) in Rubberduck's levels. 

##### Additional debugging information
The lanterns seem to work fine, so it's probably not the magicblock's fault. This is NOT a duplicate of #835, as that issue has been fixed on the Android Version...

Thanks!

**Comment by tobbi** [comment]
Can you check whether this works on the latest nightly on Desktop SuperTux?

**Comment by weluvgoatz** [comment]
Nope. Sorry, my computer is broken for now. :(

**Comment by weluvgoatz** [comment]
I checked it on the latest nightly on Mac. Seems to be just an Android problem, and on Mac it works normal.

**Comment by tobbi** [comment]
It could be that this problem is gonna be fixed in the next release version of the Android port...or that it's an issue that only pertains to Android. Not sure which.

**Comment by weluvgoatz** [comment]
Well anyways, if the latest nightly build has a working spotlight I might as well close this.
