### ISSUE TITLE
Bonus Block Sprites reset themselves when going in and out of the game

### ISSUE THREAD

**Issue by weluvgoatz** [SuperTux/supertux#891]
I am using the Android Port, 0.5.1.20, but this might affect the other versions as well. When I change the sprite of a bonusblock, to the purple or orange sprites, they reset themselves to the blue bonus block sprite after some time. Very annoying!

**Comment by tobbi** [comment]
Can you reproduce the issue with the Windows version as well?

**Comment by Rusty-Box** [comment]
On the windows version it sometimes happens that when you change the sprite of a bonus block and play the level the block will reset its sprite to the original one

**Comment by tobbi** [comment]
@Rusty-Box Can you find steps to reproduce?

**Comment by weluvgoatz** [comment]
I can. Here's my results for what happened, in detail:

1. Change the sprite
2. Save
3. Exit Editor
4. Exit Game
5. Enter Game and enter level
6. Sprite is reset :(

It still works for me when I test the level, only when I exit.

**Comment by weluvgoatz** [comment]
This issue also happens on the latest Nightly on Mac.

**Comment by tobbi** [comment]
I can confirm the issue.

**Comment by tobbi** [comment]
@weluvgoatz Can you please try the latest nightly from http://download.supertux.org and see if it's fixed (I can't reproduce the issue anymore)
