### ISSUE TITLE
Mr Bomb explosion graphic is ugly

### ISSUE THREAD

**Issue by Savsish** [SuperTux/supertux#90]
No offense, but the new explosion graphics from Cheeseman looks ugly. I liked the older explosion graphics in the 0.3.3 release better. Please bring back old explosion graphics from 0.3.3

**Comment by brmbrmcar** [comment]
I disagree.

**Comment by 165your4** [comment]
Yeah. The new one looks too "real" for Tux.

**Comment by Hume2** [comment]
This is not Cheeseman forum.
This is not Cheeseman forum.

If you meant the explosion is SuperTux 0.3.4, then please don't bypass the problem over a branching game and say directly thet it's a bug of SuperTux 0.3.4.

**Comment by brmbrmcar** [comment]
They aren't even the same, anyway.

**Comment by Hume2** [comment]
Just please don't post it here because we are not Cheeseman development.
And as brmbrmcar has said, they are different from the SuperTux ones, so basically, it has nothing to do with SuperTux.
