### ISSUE TITLE
Change background in ‘Miyamoto Monument’, which looks like a swastika

### ISSUE THREAD

**Issue by Ordoviz** [SuperTux/supertux#907]
The background in ‘Miyamoto Monument’ could be misinterpreted as a Hakenkreuz (or swastika). You should change that. Look at the picture and decide for yourself what you see:
![miyamoto-swastika2](https://user-images.githubusercontent.com/37733333/44946899-272b0380-ae05-11e8-820d-1098ad4f9237.png)
SuperTux version 0.5.1

**Comment by hubotx** [comment]
Personally, I think it's only your imagination. In my opinion, this is a normal labyrinth, nothing else. Please stop shitpost and report issues based on your prejudices. I vote for closing this issue.

**Comment by tobbi** [comment]
Thanks for someone else saying that so I didn't have to. Closing as per https://github.com/SuperTux/supertux/issues/907#issuecomment-427641743
