### ISSUE TITLE
How can I disable the 68.0 fps limit?

### ISSUE THREAD

**Issue by HybridDog** [SuperTux/supertux#909]
**SuperTux version:** 0.5.1-1build2
**System information:** lubuntu 18.04

##### Expected behavior
No fps limit when vsync is disabled
##### Actual behavior
When vsync is disabled, I always have 68.0 fps. 

![2018-09-09-165155_1920x1080_scrot](https://user-images.githubusercontent.com/3192173/45266320-9fbf3f00-b459-11e8-84ed-d28bb292e70c.png)

##### Steps to reproduce actual behavior
Disable vsync in the supertux configuration and show fps, start supertux with `vblank_mode=0 supertux2` and see the fps not exceeding 68.0.

##### Additional debugging information

If I start supertux with `LIBGL_SHOW_FPS=1 vblank_mode=0 supertux2`, in the terminal it shows FPS = 66.9 although it's 68.0 in supertux.

**Comment by Grumbel** [comment]
The maximum framerate can be adjusted in `src/supertux/constants.hpp`:

    static const float LOGICAL_FPS = 64.0;

Current value is not much of a good choice.

**Comment by qwertychouskie** [comment]
IMO this should be above 144 as many high-end monitors run at 144Hz.  `150.0`?

**Comment by HybridDog** [comment]
Why do I get 68.0 FPS and not 64.0 FPS although LOGICAL_FPS is 64?
And why is the FPS shown in supertux bigger than the FPS shown by mesa debugging?

Maybe instead of using a constant timestep and skipping a frame when needed (#910), timestep can be set to `(elapsed_ticks / ticks_per_frame) / LOGICAL_FPS`.
https://github.com/SuperTux/supertux/blob/3c487bd8d98afae3ab06a52cb4b0e59ad3511229/src/supertux/screen_manager.cpp#L413-L424
However, when using a variable timestep the game may be less deterministic (I doubt this is a problem).

**Comment by HybridDog** [comment]
I've set LOGICAL_FPS to 256.0 and now the game runs very slowly if I don't explicitly disable vsync with vblank_mode=0.

**Comment by Grumbel** [comment]
I added vsync and framerate to the option menu, those are obviously not working quite right at the moment, but make it a little easier to experiment.

**Comment by HybridDog** [comment]
The framerate limit is caused by calling SDL_Delay when less than `ticks_per_frame` ticks are elapsed.
If a variable timestep is used, the framerate limit can be removed: https://github.com/SuperTux/supertux/issues/910#issuecomment-421929321

**Comment by brmbrmcar** [comment]
When frame rate increases, currently so does the game speed somewhat (not directly proportionally). It probably didn't need to be said, but it was a huge issue with disabling vsync for me.
