### ISSUE TITLE
Creature Tumbleweed

### ISSUE THREAD

**Issue by supercookiemonster** [SuperTux/supertux#911]
The creature Tumbleweed is not in the editor, or is it some existing script?

**Comment by supercookiemonster** [comment]
In the editor some scripts do not work.

**Comment by tobbi** [comment]
@supercookiemonster Please, don't create one github issue for two separate issues.

Tumbleweed can be added the following way: Add a bouncing snowball to the level, change its sprite through the editor options, set the sprite to tumbleweed / tumbleweed.sprite.

Which scripts do not work?

**Comment by supercookiemonster** [comment]
For example I created a world in which I put the 5 keys. With default.nut. I put in the level a script / add_key ("air"); and nothing happens. But playing outside the editor works perfectly.

**Comment by tobbi** [comment]
Swimming is not implemented, but it's planned, yes.

**Comment by supercookiemonster** [comment]
So can I help with the design?
What about the script?
And thanks for the attention, and sorry for the language I'm Portuguese and I'm translating for the translator.

**Comment by tobbi** [comment]
The reason I presume is that when loaded from the editor we do not add the includes necessary for that function.

**Comment by Rusty-Box** [comment]
Tumbleweed is only a forest variation of bouncing snowball and this can be placed in the editor by changing bouncing snowballs sprite to the tumbleweed sprite.
As long as tumbleweed doesn't require its own unique code it will stay that way.
