### ISSUE TITLE
Warning message when installing supertux-0.5.1 on Gentoo

### ISSUE THREAD

**Issue by fturco** [SuperTux/supertux#912]
Supertux 0.5.1
GNU/Linux distribution: Gentoo Linux.
Kernel 4.18.8.

When installing the `games-arcade/supertux-0.5.1` package with the Portage package manager under Gentoo I get the following warning message:

```
 * QA Notice: Package triggers severe warnings which indicate that it
 *            may exhibit random runtime failures.
 * /var/tmp/portage/games-arcade/supertux-0.5.1/work/SuperTux-v0.5.1-Source/src/gui/item_script_line.cpp:36:31: warning: ‘*<unknown>.ItemScriptLine::<anonymous>.ItemTextField::<anonymous>.MenuItem::id’ is used uninitialized in this function [-Wuninitialized]

 * Please do not file a Gentoo bug and instead report the above QA
 * issues directly to the upstream developers of this software.
 * Homepage: https://supertux.org/
```

[build.log](https://github.com/SuperTux/supertux/files/2402612/build.log)

**Comment by tobbi** [comment]
This was already fixed with https://github.com/SuperTux/supertux/commit/945983ac0fbbecb6508c3a90f361cfc56ac9db39 and will be resolved in version 0.6.0
