### ISSUE TITLE
Warning when exiting the editor with unsaved changes

### ISSUE THREAD

**Issue by manuel-st** [SuperTux/supertux#914]
This is more a feature request than an issue:

A confirmation dialog should appear when clicking on "Exit Level Editor" and there are unsaved changes in the level. It might be a bit silly to work really long on a level without saving it, but when it gets lost, it would be rally discouraging.

**Comment by manuel-st** [comment]
The same dialog should appear when selecting "Edit another level" or "Choose another level subset".

**Comment by tobbi** [comment]
Fixed in 85e9cfbf504c081bdf9b171fd171c07c911ef6fc
