### ISSUE TITLE
Messed up values for level statistics when opening new level

### ISSUE THREAD

**Issue by aldn** [SuperTux/supertux#917]
**SuperTux version:** supertux2 v0.5.1-1273-g9ba8320f7
**System information:** Mac OS X High Sierra 10.13.6 (17G65)
<img width="1392" alt="2018-10-17 01 22 23" src="https://user-images.githubusercontent.com/5281988/47052331-7ad48f00-d1b0-11e8-8acb-fcd476b61620.png">

##### Expected behavior
Displayed valid statistics values

##### Actual behavior
Observed statistics values look uninitialized

##### Steps to reproduce actual behavior
While on main map select an unvisited level, press button to go to the level, observe the loading screen

**Comment by aldn** [comment]
https://github.com/SuperTux/supertux/blob/9ba8320f7c9d344e03919bc42fc78d621c2aa723/src/supertux/statistics.cpp#L36

Oh, well, looks like it is "by design"

**Comment by Grumbel** [comment]
Fixed in 1d9074f9a
