### ISSUE TITLE
Finished level "7" on bottom fork, and my levels were erased.

### ISSUE THREAD

**Issue by MrsBokrony** [SuperTux/supertux#92]
I finished level 7 if you take the bottom fork in the game and it sent me back to the beginning, but I still had all my coins and my hat but I had to start at the beginning.

**Comment by maxteufel** [comment]
Can you reproduce this on a clean profile? If so, would it be possible to attach the game to a debugger to see what's going on?

**Comment by MrsBokrony** [comment]
What do you mean "clean profile"? I'll reinstall and see if i can reproduce it. I'll record what happens.

**Comment by tobbi** [comment]
Please find your profile folder, which should be called .supertux2 in your home directory (location depends on your operating system). Just move that folder somewhere else, and supertux should create new default settings.

**Comment by MrsBokrony** [comment]
I will try that, but the program doesn't save my progress. If i complete level one and close it, it doesn't remember it and keeps defaulting back to the coins I had the first time i had the issue. I will do that though

**Comment by MrsBokrony** [comment]
So I deleted the profile but exiting the program it deletes my progress, but saves my coins and my hat...

**Comment by tobbi** [comment]
Did it recreate the profile directory?

**Comment by MrsBokrony** [comment]
Yes, profile1 was recreated. but my levels go back to locked.

**Comment by tobbi** [comment]
That's normal when a profile was recreated. Can you try to play levels and see if the status of those levels gets saved?

**Comment by tobbi** [comment]
Hey @MrsBokrony Any updates on your issue?

**Comment by tobbi** [comment]
No response from reporter in more than 3 months. I am closing this.

**Comment by Karkus476** [comment]
I agree. Although still an issue. There is no convincing way to solve this. If you mess with the configs, the configs will mess with you.
