### ISSUE TITLE
Ideas for making Haywire more challenging

### ISSUE THREAD

**Issue by Rusty-Box** [SuperTux/supertux#924]
I personally always saw the enemy Haywire as a more difficult and "stronger" version of Mr. Bomb. However, in my opinion Haywire does not seem more challenging than his blue counterpart. Sure, he can run after being hit but even then once the player for example jumps over a small gap, Haywire cannot follow which is pretty boring as due to complex level design this and many occasions where Haywire cannot follow will happen a lot making Haywire not really diffrent from Mr. Bomb. So here are three ideas that would make Haywire a little bit more challenging:

1. Let Haywire be able to jump over a short distance or from higher platforms (similar to captain snowball) when running after Tux so he can follow the player awhile longer. (Would require additional sprite work)
2. Maybe increase their speed a little bit so it is a bit harder to out run them.
3. Make Haywire avoid enemies when chasing Tux so Haywire does not get turend around when bumping into another enemy on their path. An idea for that could be that Haywire jumps over them or is simply not affected by their hitboxes (If possible).

**Comment by brmbrmcar** [comment]
Maybe a speed increase could work, but the other two look like they'd make some things impossible and make level design harder. Older levels may break especially because of the first idea. I'd support the idea that there would be a customisable speed. But I think in cases where they're meant to be hard, they work quite well as they are, and when they're meant to be easier on longer platforms or just not hellish levels they are. It works quite well in my opinion.

**Comment by Rusty-Box** [comment]
It wouldn’t  make level design harder as they would be similar to captain snowball then, movement wise. And using them isn’t hard too, isn’t it. Besides it's the level creator’s responsibility to make their levels work with the latest version of the game, not necessarily only ours.

**Comment by brmbrmcar** [comment]
It isn't just incompatibility, it's the removal of a potentially vital feature. It's not the job of the level creator to predict the future of how the game might change and completely ruin a level.

**Comment by weluvgoatz** [comment]
Can this be closed?
