### ISSUE TITLE
AppImage does not run on Clear Linux OS

### ISSUE THREAD

**Issue by probonopd** [SuperTux/supertux#928]
**SuperTux version:**

SuperTux_2-v0.5.1-1507-g39aceb3bc.glibc2.14-x86_64.AppImage

**System information:** 

```
user@host ~ $ cat /etc/os-release 
NAME="Clear Linux OS"
VERSION=1
ID=clear-linux-os
ID_LIKE=clear-linux-os
VERSION_ID=26200
PRETTY_NAME="Clear Linux OS"
ANSI_COLOR="1;35"
HOME_URL="https://clearlinux.org"
SUPPORT_URL="https://clearlinux.org"
BUG_REPORT_URL="mailto:dev@lists.clearlinux.org"
PRIVACY_POLICY_URL="http://www.intel.com/privacy"
```

##### Expected behavior

Runs

##### Actual behavior

Does not run:
```
user@host ~ $ ./squashfs-root/AppRun 
/home/user/squashfs-root/usr/bin/supertux2: symbol lookup error: /usr/lib64/libGL.so.1: undefined symbol: xcb_dri3_get_supported_modifiers
```

##### Steps to reproduce actual behavior

Download SuperTux_2-v0.5.1-1507-g39aceb3bc.glibc2.14-x86_64.AppImage and try to run on Clear Linux OS

##### Additional debugging information

Workaround:

```
./Downloads/SuperTux_2-v0.5.1-1507-g39aceb3bc.glibc2.14-x86_64.AppImage --appimage-extract
find squashfs-root/ -iname '*libxcb-dri3*' -delete
./squashfs-root/AppRun
```

So, not bundling `libxcb-dri3` should solve this issue.

**Comment by probonopd** [comment]
Yes, I think so. Has it been resolved @tobbi?

**Comment by tobbi** [comment]
I've tried installing Clear OS in a VIrtual Machine, so far unsuccessfully. Since we're all fairly busy with release prep, I'll just assume things work until being told otherwise.
