### ISSUE TITLE
Idea: tiles that are solid to objects and badguys, but not Tux

### ISSUE THREAD

**Issue by 165your4** [SuperTux/supertux#930]
And conversely, tiles that are _only_ solid to Tux

How cool would this be? The possibilities are endless.

**Comment by divVerent** [comment]
Indeed needed this a lot recently. Ended up making bad workarounds involving unisolids.

Solid only to objects/badguys... can we call those 1F0? :)

**Comment by Rusty-Box** [comment]
Currently no need for this. Closing this.
