### ISSUE TITLE
Certain objects crash the game when placed in the Level Editor

### ISSUE THREAD

**Issue by weluvgoatz** [SuperTux/supertux#931]
Version: The third Alpha for 0.6.0.

Flying Platforms will crash the game every single time you try to place them in the level editor. Very annoying. Please fix. Also, another unknown item also crashes the game upon placement. I am unsure what it is (possibly text array). A few other items are like this, but I can't list them off the top of my head right now.

**Comment by Grumbel** [comment]
Should be fixed in master.
