### ISSUE TITLE
New Levels don't show statistics upon entering

### ISSUE THREAD

**Issue by weluvgoatz** [SuperTux/supertux#932]
Version: 3rd alpha of 0.6.0.

When opening a level created before the latest nightlies, all the statistics disappear until the end of the level. This confuses me.

**Comment by tobbi** [comment]
@weluvgoatz Please try to reproduce the issue in a nightly build from http://download.supertux.org

**Comment by weluvgoatz** [comment]
This is an issue from one of those nightly builds.
