### ISSUE TITLE
Iceslick Tiles are transparent???

### ISSUE THREAD

**Issue by weluvgoatz** [SuperTux/supertux#934]
For some reason, in the third alpha for 0.6.0, the iceslick tiles are... transparent? They are see-through! Please fix, but do tell me if it was intentional. It's a small bug, but I wanted to make it it's own issue.

**Comment by tobbi** [comment]
You mean the ones where Tux is sliding on? Yeah, it's intended that those are transparent to give off the illusion that it's ice. Maybe we should make the reflection a bit rougher though.

**Comment by weluvgoatz** [comment]
Oh. Yeah, the "reflection" in darker levels works fine, but in brighter, or daytime levels it appears to be invisible.

**Comment by weluvgoatz** [comment]
It seems this is not an issue, and I'm getting kinda used to it, so I should close this.
