### ISSUE TITLE
Make a "toggle gravity option" for Scripted Objects

### ISSUE THREAD

**Issue by Alzter** [SuperTux/supertux#938]
I believe a script that could make scripted objects toggle physics would be very useful. I thought the `enable_gravity(bool gravity_enabled)` script would do this but that just makes the object show or hide depending on if it has physics.

**Comment by tobbi** [comment]
I just tested this and enable_gravity works fine.
[level1.stl.zip](https://github.com/SuperTux/supertux/files/12065981/level1.stl.zip)
