### ISSUE TITLE
Improve font loading time, don't load font files multiple times

### ISSUE THREAD

**Issue by tobbi** [SuperTux/supertux#94]
I checked what fonts are loaded at startup using a debug statement. Result: We're loading each font file multiple times and creating surfaces for each of these. We should probably find a better way to deal with font files...

**Comment by sydneyjd** [comment]
Yes we should, but its not *completely* neccessary.
What we have works. ;)

**Comment by giby** [comment]
Yes, especially if translators of some asian languages become active…

**Comment by tobbi** [comment]
@maxteufel This mostly depended on SDL_ttf, right? So, since we use that as the default now, this can be closed right?
