### ISSUE TITLE
Block hit sound doesn't play when you hit a coin block

### ISSUE THREAD

**Issue by Alzter** [SuperTux/supertux#944]
**SuperTux version: 0.6.0 Alpha 3**
**System information:** *Windows 10*

##### Expected behavior
Hitting a coin block plays the coin get sound and the hit block sound

##### Actual behavior
Hitting a coin block only plays the coin get sound

##### Steps to reproduce actual behavior
Hit a coin block

**Comment by HybridDog** [comment]
I [searched for the place where the brick.wav sound is played](https://pastebin.com/VheGGwq3) when hitting an egg bonus block until I finally noticed that the sound is merged into the upgrade.wav sound. #1094
