### ISSUE TITLE
JPG backgrounds do not load

### ISSUE THREAD

**Issue by 165your4** [SuperTux/supertux#947]
e.g. editor background, previously forest1.jpg
![image](https://user-images.githubusercontent.com/8019640/48965901-db11e880-f01a-11e8-8a8b-e5465b290d54.png)
Can be seen in levels too, such as the forest levels where most backgrounds are jpg

**Comment by Grumbel** [comment]
Missing libjpeg.dll in probably?

**Comment by tobbi** [comment]
Fixed with aeb18c0
