### ISSUE TITLE
You can't edit the ambient light in newly created levels

### ISSUE THREAD

**Issue by weluvgoatz** [SuperTux/supertux#948]
In newly created levels (I am using the latest nightly builds) you cannot edit the ambient light whatsoever. There is no option to edit it. In old levels, there is. When I select "Ambient Light" from the option menu, and try to place it, nothing happens. (The control panel says "ambientlight" doesn't exist) and whenever I try to change ambient light with script triggers, it crashes the game. Please fix!

**Comment by Grumbel** [comment]
Ambient light is down in the bottom bar now, not in the menu, right click there.

**Comment by Rusty-Box** [comment]
@Grumbel Newly created levels should automaticlly have an ambient light object or you should be able to create one by selecting and placing the ambient light object from the objects menu.
