### ISSUE TITLE
Checkpoint Percentage not displayed

### ISSUE THREAD

**Issue by pazkero** [SuperTux/supertux#95]
On "Welcome to Antartica" Level, on World 1, it's said that "at least 25 coins" is taken to respawn at the checkpoint upon death, but the precise percentage is not said.
It would be interesting if the percentage was also displayed.

**Comment by Savsish** [comment]
Uhhh... This will require updating all the translations...

**Comment by tobbi** [comment]
yup, but it's not that important and our translator community is more than willing to do so.
