### ISSUE TITLE
Re-sprite solid clouds

### ISSUE THREAD

**Issue by Alzter** [SuperTux/supertux#952]
**SuperTux version: 0.6.0 Alpha 3**
**System information:** *Windows 10*

I think we should change the appearance of solid clouds in some way, so there's distinction between the solid ones and the background decal. Too many levels (like a path in the clouds for instance) use the clouds as solid platforms **and** as background decal interchangeably and it's confusing and inconsistent.

**Comment by Alzter** [comment]
![cloud-0](https://user-images.githubusercontent.com/22513909/49479012-afda9500-f875-11e8-8f12-da24949e2baf.png)
![cloud-1](https://user-images.githubusercontent.com/22513909/49479014-afda9500-f875-11e8-8f19-ab17d6aedd71.png)
![cloud-2](https://user-images.githubusercontent.com/22513909/49479016-b0732b80-f875-11e8-98b2-2750fe51d19f.png)
Maybe BG clouds could look like this?

**Comment by NickersonRomero** [comment]
hmmm algo haci

**Comment by Rusty-Box** [comment]
This can be closed as instead the background particle clouds have been redrawn.
