### ISSUE TITLE
Force auto-turn enemies to appear as smart variants

### ISSUE THREAD

**Issue by Alzter** [SuperTux/supertux#953]
**SuperTux version: 0.6.0 Alpha 3**
**System information:** *Windows 10*

We should make every enemy that auto-turns display as their respective "smart" variant, or just remove the auto-turn option all together. It's inconsistent when iceblocks or snowballs turn on an edge despite not being the smart variant.

**Comment by Rusty-Box** [comment]
I would rather suggest removing the auto-turn option from bad guys that are not supposed to auto-turn.

**Comment by Semphriss** [comment]
As of 0.6.2, this seems to be fixed; I cannot find any such auto-turn option and badguys either have their smart counterpart or are already known for turning around. I will close this issue, if anything else needs consideration please open a new issue.
