### ISSUE TITLE
Clean up level editor tiles and replace deprecated ones

### ISSUE THREAD

**Issue by Alzter** [SuperTux/supertux#954]
**SuperTux version: 0.6.0 Alpha 3**
**System information:** *Windows 10*

Why do we still have old art assets like the old water or the old lava, or that really old iceberg? Can't we make them automatically replace themselves with the new variant if they load in a level with them and then delete the old ones? I feel like the tileset needs a bit of cleaning up. We should merge categories like "Icebridge", "Pipes", "Points" and "Blocks", or "Jungle" and "Forest". Also we should probably re-order the categories a bit, like putting Snow and Snow mountain themes next to each other, Forest and Halloween next to each other, just correlation like that, and make only one category for global blocks used in all the levels.

**Comment by 165your4** [comment]
old assets are good. gives level designers extra choice and creativity, e.g. using the old iceberg for sails

**Comment by Grumbel** [comment]
There is a `(deprecated #t)` tag that will hide old tiles from the editor. Feel free to send patches for the .strf.

Replacing old with new is tricky, as many of the new tiles come in groups of 4 tiles, while the old ones where just one tile.

**Comment by Rusty-Box** [comment]
Since the tilegroups have been updated for v0.6.1, @Alzter is there still things that should be cleaned up?

**Comment by Alzter** [comment]
I think the level editor cleanup by @weluvgoatz should suffice as a fix, closing
