### ISSUE TITLE
Enemies should kill other enemies if you're holding them

### ISSUE THREAD

**Issue by Alzter** [SuperTux/supertux#956]
**SuperTux version: 0.6.0 Alpha 3**
**System information:** *Windows 10*
I'm suggesting that if you're holding an enemy and you hit another one on the front while holding them, both enemies die. This is a common Mario behaviour and it was in Milestone 1, can it be restored?

**Comment by brmbrmcar** [comment]
In my opinion, this is overpowered and may change some levels. I don't like the fact it was implemented, but oh well there are bigger issues.
