### ISSUE TITLE
Make fire and ice hats overlay like the other hats

### ISSUE THREAD

**Issue by Alzter** [SuperTux/supertux#957]
**SuperTux version: 0.6.0 Alpha 3**
**System information:** *Windows 10*

I think we should make the fire and ice hats separate sprites that go on top of tux like the other hats.

**Comment by Alzter** [comment]
Also, Earth and Air hats don't bounce correctly with Tux's new walking animation.

**Comment by Rusty-Box** [comment]
This issue was fixed via #1104. Closing this.
