### ISSUE TITLE
Auto-turning enemies die when placed on one tile

### ISSUE THREAD

**Issue by Alzter** [SuperTux/supertux#958]
**SuperTux version: *0.6.0 Alpha 3*
**System information:** *Windows 10*

Title basically says it all. Enemies with auto-turning on edge turned on die when they're placed on one block (horizontally).

**Comment by tobbi** [comment]
https://github.com/SuperTux/supertux/blob/master/src/badguy/walking_badguy.cpp#L205

says "if we get dizzy, we fall off the screen". Is this not intended anymore?

**Comment by Alzter** [comment]
> https://github.com/SuperTux/supertux/blob/master/src/badguy/walking_badguy.cpp#L205
> 
> says "if we get dizzy, we fall off the screen". Is this not intended anymore?

Maybe enemies just stop moving if they are auto-turning on a one block tile? They could just stay on frame 1 of their walk cycle and face Tux.

**Comment by Alzter** [comment]
Closing this, it's not really that much of an issue.
