### ISSUE TITLE
Make Flying Snowball's flight pattern not random

### ISSUE THREAD

**Issue by Alzter** [SuperTux/supertux#959]
**SuperTux version: 0.6.0 Alpha 3**
**System information:** *Windows 10*

I think Flying Snowball should have a set path of vertical movement that he follows rather than randomly jetting up or down. Would help speedruns and means you don't have to wait as long for him to lower in tricky parkour sections.

**Comment by 165your4** [comment]
I don't know, it's more challenging the way it is now. Plus if you want regular-moving Flying Snowballs in your levels you can always use a Spidermite and set the sprite file to that of the Flying Snowball

**Comment by Alzter** [comment]
Actually, thanks for the suggestion @165your4! Spidermites identically replicate the behaviour of the M1 flying snowball and skinning it with that makes it identical. Works well with my Milestone 1 themed level.

**Comment by brmbrmcar** [comment]
I agree entirely, the RNG has completely ruined me doing something cool and encourages very bad level design. It is especially bad when terrible level design forces you to jump on them to get somewhere, then it's stuck in the wrong place.

**Comment by Alasdairbugs** [comment]
> **SuperTux version: 0.6.0 Alpha 3**
> **System information:** _Windows 10_
> 
> I think Flying Snowball should have a set path of vertical movement that he follows rather than randomly jetting up or down. Would help speedruns and means you don't have to wait as long for him to lower in tricky parkour sections.

Agreed. It should not be RNG based, since you cant tinker with them cleverly with level design as well as you could ages ago.
