### ISSUE TITLE
Make ambient light spots fade in and out

### ISSUE THREAD

**Issue by Alzter** [SuperTux/supertux#960]
**SuperTux version: 0.6.0 Alpha 3**
**System information:** *Windows 10*

I feel like the ambient light spots created by things like explosions, fireballs, and enemies should fade in and out instead of appearing suddenly.

**Comment by tobbi** [comment]
nice idea! Maybe we'll get to tackling it for 0.6.1

**Comment by HybridDog** [comment]
I think realistic explosions must not have fading lights and appear only for a very short time.
In SuperTux, the explosion cloud appears for several milliseconds, so maybe the cloud corresponds to remaining fire and smoke, which fades out; the explosion should not fade in.

**Comment by Rusty-Box** [comment]
I think this is something we should actually think about doing as it indeed looks pretty weird and clunky.
