### ISSUE TITLE
Treasure in the skies scripts

### ISSUE THREAD

**Issue by Alasdairbugs** [SuperTux/supertux#965]
v0.6.0 beta-1
win10 64bit

**Comment by tobbi** [comment]
8a106fefebb7193010ff94318d58e3040b57d0f1 is the first bad commit
commit 8a106fefebb7193010ff94318d58e3040b57d0f1
Author: Ingo Ruhnke <grumbel@gmail.com>
Date:   Mon Nov 26 20:00:09 2018 +0100

    Remove special handling of Camera and treat it like any other object

:040000 040000 6029617ad25158c1da25c259e9143cba08261357 a76f097f7f32114e6bb48926429feb44bdb39e89 M	src

**Comment by tobbi** [comment]
@Grumbel Can you please take a look at this?
