### ISSUE TITLE
Level editor bars cover some of the areas

### ISSUE THREAD

**Issue by Alzter** [SuperTux/supertux#970]
**SuperTux version: 0.6.0 Alpha 3**
**System information:** *Windows 10*

Level editor should scroll past the boundaries so you can edit the parts concealed by the bottom and right bars. Possibly let it scroll 4 more tiles to the right and 1 more to the bottom.

**Comment by brmbrmcar** [comment]
Isn't it also concealed in the top left corner or was that patched?

**Comment by Alzter** [comment]
> Isn't it also concealed in the top left corner or was that patched?
It's partially concealed by the scroller, but that's hideable. The undo and redo buttons however, are not hideable and take up a bit of the left.
