### ISSUE TITLE
Ambient things (Backgrounds, Particle Effects) aren't deletable

### ISSUE THREAD

**Issue by Alzter** [SuperTux/supertux#978]
**SuperTux version: 0.6.0 Beta 1**
**System information:** *Windows 10*

##### Expected behavior
In the level editor, right-clicking an ambient thing (like a background, tileset, particle, music, etc.) on the bottom row of the level editor will bring up a menu with the Remove option. Clicking remove deletes the ambient thing.
##### Actual behavior
The Remove button does nothing.
##### Steps to reproduce actual behavior
Try to remove an ambient thing in a level using the SuperTux level editor.

**Comment by Rusty-Box** [comment]
I can confirm this issue!
