### ISSUE TITLE
Yeti's Revenge: Escape from the pirates: Cannon balls get stuck at specific position

### ISSUE THREAD

**Issue by tobbi** [SuperTux/supertux#981]
This is a regression. When playing the scape from the pirates level in Yeti's Revenge, the cannon balls get stuck in a specific position. They didn't use to do that before.

http://prntscr.com/ltai51

I'm trying to find a regression range.

**Comment by tobbi** [comment]
f4f8b88e38d589376538eac96066237bf4e1bae0 is the first bad commit
commit f4f8b88e38d589376538eac96066237bf4e1bae0
Author: Ingo Ruhnke <grumbel@gmail.com>
Date:   Tue Oct 30 12:06:14 2018 +0100

    Change Path interface to use the ::update(float dt_sec) pattern

:040000 040000 f0d3d74ef422d8c705fc557bda719a306ab03778 1452b1f8095a889012a7368be7803a61c629e5da M	src

**Comment by Semphriss** [comment]
Closing, as this level isn't in the game anymore.

**Comment by Ordoviz** [comment]
@Semphriss That level is still part of [niso-yetis-revenge_v3.zip](https://github.com/SuperTux/addons/blob/master/repository/niso-yetis-revenge_v3.zip). Can you clarify what you mean by “not in the game anymore” or did you just thought that “Escape from the pirates” was part of the main game?

Thanks a lot for the work you put into this game!

**Comment by Semphriss** [comment]
@Ordoviz Apologies - I've mistaked "Yeti's Revenge" as the addon for the last level of the Icy World! That's my bad, I'm reopening this issue now.

**Comment by weluvgoatz** [comment]
Might be related to https://github.com/SuperTux/supertux/issues/1863

**Comment by tobbi** [comment]
![Screenshot at Mar 29 13-08-33](https://github.com/SuperTux/supertux/assets/583169/65e53722-4f8c-4060-9ee2-6fcaeb7734cb)
I've retested this and this still happens. This is the screenshot.

**Comment by tobbi** [comment]
> Might be related to #1863

Turns out that it isn't. I just checked the level there and the issue still occurs.
