### ISSUE TITLE
Enemies should obey wind like Tux does

### ISSUE THREAD

**Issue by weluvgoatz** [SuperTux/supertux#982]
Right now, I have noticed that enemies do not work in wind like Tux does. I think this should be fixed, since Tux is a creature, too, and it doesn't make sense that they don't.  I know this is a small issue/suggestion, but you guys should maybe add it. :)

**Comment by Alasdairbugs** [comment]
maybe on option to toggle wether it affects enemies or not, and set to default to not affect enemies or else some levels might break.

**Comment by weluvgoatz** [comment]
@Alasdairbugs : That sounds like a better solution.
