### ISSUE TITLE
"Owls' Skydive Commando" is not beatable when you start out as smalltux

### ISSUE THREAD

**Issue by weluvgoatz** [SuperTux/supertux#986]
Title pretty much explains it. The pull request was merged before anyone could point out any bugs, so don't expect this to be my last issue witb the new story mode.

**Comment by Rusty-Box** [comment]
The level is indeed possible as small Tux. I beat it during a fast game to gather the time for the in game records as small tux without gathering any powerups so this issue needs more confirmation. If it does it might have become a bit too difficult.

**Comment by plonibarploni** [comment]
I just completed the level entirely as small Tux, without using any powerups.

**Comment by weluvgoatz** [comment]
Ha, just realized the platforms were not working on my device (Sorry). I'll
close this...
