### ISSUE TITLE
Show powerup count during level

### ISSUE THREAD

**Issue by clintmoyer** [SuperTux/supertux#987]
**SuperTux version:** 0.5.1
**System information:** Arch Linux (kernel 4.19.4)

It would be nice for the player to be able to visualize their weapon count. Each subsequent powerup [increments the weapon count](https://github.com/SuperTux/supertux/blob/v0.5.1/src/object/player.cpp#L1122). Perhaps the weapon count could be shown underneath the coin count in the top-right corner.

**Comment by Alzter** [comment]
Wait, what?? Having more fireflowers gives you more max bullets? I never knew that! It should be visually represented, yeah.
