### ISSUE TITLE
Forest World missing in 0.6.0-rc1

### ISSUE THREAD

**Issue by plonibarploni** [SuperTux/supertux#989]
It's listed in "Contrib Levels" in 0.6.0-beta.2, but is missing when running 0.6.0-rc.1. Running the AppImage package on Ubuntu Mate 18.04.1.

**Comment by Rusty-Box** [comment]
Since it has been readded to the storymode you have to beat icy island first in order get to it via a boat on the worldmap. That’s why it is not in the contrib level section anymore.

**Comment by plonibarploni** [comment]
maybe it should be clarified in the [changes](https://github.com/SuperTux/supertux/releases/tag/v0.6.0-alpha.1)? As of now there's no mention of it that I know of.
